MSG_pointerList:
UMSG_NONE:
.faraddr $00000
UMSG_MYHOME_MINNIE_INVASION:
.faraddr MSG_MYHOME_MINNIE_INVASION
UMSG_MYHOME_MINNIE_INVASION_FIGHT:
.faraddr MSG_MYHOME_MINNIE_INVASION_FIGHT
UMSG_MYHOME_MINNIE_INVASION_FIGHT_2:
.faraddr MSG_MYHOME_MINNIE_INVASION_FIGHT_2
UMSG_MYHOME_JUICE:
.faraddr MSG_MYHOME_JUICE
UMSG_MYHOME_MIMMIE_INVASION:
.faraddr MSG_MYHOME_MIMMIE_INVASION
UMSG_MYHOME_MIMMIE_INVASION_FIGHT:
.faraddr MSG_MYHOME_MIMMIE_INVASION_FIGHT
.faraddr $00000
UMSG_MYHOME_MIMMIE:
.faraddr MSG_MYHOME_MIMMIE
UMSG_MYHOME_MOM_INVASION:
.faraddr MSG_MYHOME_MOM_INVASION
UMSG_MYHOME_MOM:
.faraddr MSG_MYHOME_MOM
UMSG_MYHOME_MOM_HURT:
.faraddr MSG_MYHOME_MOM_HURT
UMSG_PHONE_NEXTLVL:
.faraddr MSG_PHONE_NEXTLVL
UMSG_MYHOME_MOM_EAT:
.faraddr MSG_MYHOME_MOM_EAT
UMSG_MYHOME_PHONE:
.faraddr MSG_MYHOME_PHONE
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
UMSG_PHONE_END:
.faraddr MSG_PHONE_END
UMSG_PHONE_INTRO:
.faraddr MSG_PHONE_INTRO
UMSG_PHONE_NEWMONEY:
.faraddr MSG_PHONE_NEWMONEY
.faraddr $005AA
.faraddr $005DF
.faraddr $00604
.faraddr $00000
.faraddr $00000
UMSG_PHONE_SAVED_RESETPROMPT:
.faraddr MSG_PHONE_SAVED_RESETPROMPT
UMSG_PHONE_RESET_YES:
.faraddr MSG_PHONE_RESET_YES
UMSG_PHONE_RESET_NO:
.faraddr MSG_PHONE_RESET_NO
UMSG_PHONE_SAVEPROMPT:
.faraddr MSG_PHONE_SAVEPROMPT
.faraddr $00000
.faraddr $00000
UMSG_PHONE_GOODLUCK:
.faraddr MSG_PHONE_GOODLUCK
.faraddr $00000
UMSG_PODUNK_PIPPIMOM_THANKS:
.faraddr MSG_PODUNK_PIPPIMOM_THANKS
UMSG_PODUNK_CEMETERYGUY1:
.faraddr MSG_PODUNK_CEMETERYGUY1
UMSG_PODUNK_CEMETERYGUY2:
.faraddr MSG_PODUNK_CEMETERYGUY2
UMSG_PODUNK_SCAREDGUY1:
.faraddr MSG_PODUNK_SCAREDGUY1
UMSG_PODUNK_SCAREDGUY2:
.faraddr MSG_PODUNK_SCAREDGUY2
UMSG_PODUNK_SCAREDGUY3:
.faraddr MSG_PODUNK_SCAREDGUY3
UMSG_PODUNK_SCAREDGUY4:
.faraddr MSG_PODUNK_SCAREDGUY4
UMSG_PODUNK_SCAREDGUY5:
.faraddr MSG_PODUNK_SCAREDGUY5
UMSG_PODUNK_SCAREDGUY6:
.faraddr MSG_PODUNK_SCAREDGUY6
UMSG_PODUNK_SCAREDGUY7:
.faraddr MSG_PODUNK_SCAREDGUY7
UMSG_PODUNK_ZOMBIE:
.faraddr MSG_PODUNK_ZOMBIE
UMSG_PODUNK_ZOMBIE2:
.faraddr MSG_PODUNK_ZOMBIE2
UMSG_PODUNK_NECROMANCERWOMAN1:
.faraddr MSG_PODUNK_NECROMANCERWOMAN1
UMSG_PODUNK_NECROMANCERWOMAN2:
.faraddr MSG_PODUNK_NECROMANCERWOMAN2
UMSG_PODUNK_WARYGUY:
.faraddr MSG_PODUNK_WARYGUY
UMSG_PODUNK_CANARYGIRL1:
.faraddr MSG_PODUNK_CANARYGIRL1
UMSG_PODUNK_CANARYGIRL2:
.faraddr MSG_PODUNK_CANARYGIRL2
UMSG_PODUNK_CANARYGIRL3:
.faraddr MSG_PODUNK_CANARYGIRL3
UMSG_PODUNK_CANARYGIRL4:
.faraddr MSG_PODUNK_CANARYGIRL4
UMSG_PODUNK_MAYORGUY:
.faraddr MSG_PODUNK_MAYORGUY
UMSG_PODUNK_CONCERNEDGUY:
.faraddr MSG_PODUNK_CONCERNEDGUY
UMSG_PODUNK_SENSIBLEGUY1:
.faraddr MSG_PODUNK_SENSIBLEGUY1
UMSG_PODUNK_SENSIBLEGUY2:
.faraddr MSG_PODUNK_SENSIBLEGUY2
UMSG_PODUNK_EVENTGIRL1:
.faraddr MSG_PODUNK_EVENTGIRL1
UMSG_PODUNK_EVENTGIRL2:
.faraddr MSG_PODUNK_EVENTGIRL2
.faraddr $00000
UMSG_PODUNK_POLTERGUY:
.faraddr MSG_PODUNK_POLTERGUY
UMSG_PODUNK_ZOOGUY:
.faraddr MSG_PODUNK_ZOOGUY
UMSG_PODUNK_BREADGIRL:
.faraddr MSG_PODUNK_BREADGIRL
.faraddr $00CA0
.faraddr $00CD6
.faraddr $00D54
.faraddr $00D7D
.faraddr $00000
.faraddr $00000
.faraddr $00E84
.faraddr $00ECC
.faraddr $00F2E
.faraddr $00F68
.faraddr $00FC6
.faraddr $01040
.faraddr $0108F
.faraddr $010BE
.faraddr $010F3
.faraddr $01127
.faraddr $01142
.faraddr $0116D
.faraddr $01194
.faraddr $011C4
.faraddr $011D8
.faraddr $0120A
UMSG_PODUNK_PIPPI_MEET_NOYES:
.faraddr MSG_PODUNK_PIPPI_MEET_NOYES
UMSG_TWINKLE_LLOYDBULLY2_LLOYD:
.faraddr MSG_TWINKLE_LLOYDBULLY2_LLOYD
.faraddr $01245
UMSG_REINDEER_DRAGONGIRL_CHECK:
.faraddr MSG_REINDEER_DRAGONGIRL_CHECK
.faraddr $012AC
.faraddr $012B4
UMSG_PODUNK_CASHCARDWOMAN:
.faraddr MSG_PODUNK_CASHCARDWOMAN
.faraddr $00000
UMSG_CANARY_MAN:
.faraddr MSG_CANARY_MAN
UMSG_CANARY_MAN_BABY:
.faraddr MSG_CANARY_MAN_BABY
UMSG_CANARY_MAN_BABY_NO:
.faraddr MSG_CANARY_MAN_BABY_NO
UMSG_CANARY_MAN_BABY_YES:
.faraddr MSG_CANARY_MAN_BABY_YES
UMSG_CANARY_MAN_MELODY:
.faraddr MSG_CANARY_MAN_MELODY
UMSG_CANARY_MAN_MELODY_NO:
.faraddr MSG_CANARY_MAN_MELODY_NO
UMSG_CANARY_MAN_MELODY_YES:
.faraddr MSG_CANARY_MAN_MELODY_YES
UMSG_GRAVEYARD_PIPPI:
.faraddr MSG_GRAVEYARD_PIPPI
UMSG_PODUNK_PIPPI_BRAVE_YES:
.faraddr MSG_PODUNK_PIPPI_BRAVE_YES
UMSG_PODUNK_PIPPI_BRAVE_NO:
.faraddr MSG_PODUNK_PIPPI_BRAVE_NO
UMSG_PODUNK_PIPPI_MEET_YES:
.faraddr MSG_PODUNK_PIPPI_MEET_YES
UMSG_PODUNK_PIPPI_MEET_NO:
.faraddr MSG_PODUNK_PIPPI_MEET_NO
.faraddr $0160E
.faraddr $00000
.faraddr $016AF
UMSG_ZOO_GATEMONKEY:
.faraddr MSG_ZOO_GATEMONKEY
.faraddr $016ED
.faraddr $01735
.faraddr $00000
.faraddr $01790
.faraddr $017D7
.faraddr $01810
.faraddr $01857
.faraddr $018A5
.faraddr $01900
.faraddr $01922
.faraddr $01946
.faraddr $0197E
.faraddr $019C3
.faraddr $01A00
.faraddr $01A59
.faraddr $01A7F
.faraddr $01A97
.faraddr $01ACC
.faraddr $01B31
.faraddr $01B96
.faraddr $01BC8
.faraddr $00000
.faraddr $01C4F
.faraddr $01CB5
.faraddr $01D52
.faraddr $01D8B
.faraddr $01DCE
.faraddr $01DDD
.faraddr $01E17
.faraddr $01E8B
.faraddr $01EB1
.faraddr $00000
.faraddr $00000
.faraddr $01EF0
.faraddr $01F66
.faraddr $01F74
.faraddr $02000
.faraddr $0202D
.faraddr $02062
.faraddr $00000
.faraddr $020CB
.faraddr $0210C
.faraddr $02154
.faraddr $02175
.faraddr $021B4
.faraddr $021E4
.faraddr $02220
.faraddr $02259
.faraddr $0227B
.faraddr $00000
.faraddr $00000
.faraddr $022E0
.faraddr $0233D
.faraddr $0236C
.faraddr $02399
.faraddr $023B5
.faraddr $02410
.faraddr $02458
.faraddr $0248E
.faraddr $024B4
.faraddr $024FC
.faraddr $02562
.faraddr $00000
.faraddr $02573
.faraddr $025A1
.faraddr $00000
UMSG_MTITOI_HEALERFAIL:
.faraddr MSG_MTITOI_HEALERFAIL
UMSG_MTITOI_HEALER:
.faraddr MSG_MTITOI_HEALER
UMSG_MAGICANT_GUITARMAN_SONG:
.faraddr MSG_MAGICANT_GUITARMAN_SONG
.faraddr $02A1A
.faraddr $02A9D
UMSG_HEALER:
.faraddr MSG_HEALER
.faraddr $02B52
.faraddr $02B67
.faraddr $02B8E
.faraddr $02BE9
.faraddr $02C14
UMSG_MERRYSVILLE_TRAINWOMAN:
.faraddr MSG_MERRYSVILLE_TRAINWOMAN
.faraddr $02CEE
.faraddr $02D27
.faraddr $02E46
UMSG_MTITOI_TEDDY_SLEEP:
.faraddr MSG_MTITOI_TEDDY_SLEEP
.faraddr $00000
.faraddr $02E76
.faraddr $02E82
.faraddr $02F05
.faraddr $02F59
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
UMSG_CANARY_GENERIC:
.faraddr MSG_CANARY_GENERIC
.faraddr $030D1
.faraddr $0310B
.faraddr $03136
.faraddr $00000
.faraddr $03144
.faraddr $00000
.faraddr $031A0
.faraddr $031EC
.faraddr $0325D
.faraddr $03282
.faraddr $032F4
.faraddr $0332F
.faraddr $00000
.faraddr $03362
.faraddr $03379
.faraddr $00000
UMSG_ELLAY_LHBOUNCERGUY_STONE:
.faraddr MSG_ELLAY_LHBOUNCERGUY_STONE
.faraddr $0348A
.faraddr $034A1
.faraddr $034B8
.faraddr $034D6
.faraddr $034F5
.faraddr $0353B
.faraddr $03558
.faraddr $03595
.faraddr $035FC
.faraddr $03682
.faraddr $036DF
.faraddr $03743
.faraddr $0378C
.faraddr $037C1
.faraddr $03816
.faraddr $03832
UMSG_MERRYSVILLE_RUMORGUY1:
.faraddr MSG_MERRYSVILLE_RUMORGUY1
UMSG_MERRYSVILLE_RUMORGUY2:
.faraddr MSG_MERRYSVILLE_RUMORGUY2
UMSG_MERRYSVILLE_HOSPITALSIGN:
.faraddr MSG_MERRYSVILLE_HOSPITALSIGN
.faraddr $00000
.faraddr $00000
UMSG_MERRYSVILLE_HOSPITALDOCTOR:
.faraddr MSG_MERRYSVILLE_HOSPITALDOCTOR
.faraddr $00000
UMSG_MERRYSVILLE_HOSPITALDOCTOR_ACCEPT:
.faraddr MSG_MERRYSVILLE_HOSPITALDOCTOR_ACCEPT
UMSG_MERRYSVILLE_HOSPITALDOCTOR_DECLINE:
.faraddr MSG_MERRYSVILLE_HOSPITALDOCTOR_DECLINE
UMSG_PODUNK_MERRYCOP:
.faraddr MSG_PODUNK_MERRYCOP
UMSG_MERRYSVILLE_COP:
.faraddr MSG_MERRYSVILLE_COP
UMSG_MERRYSVILLE_DUNCANGUY:
.faraddr MSG_MERRYSVILLE_DUNCANGUY
UMSG_DUNCANFACTORY_DOG:
.faraddr MSG_DUNCANFACTORY_DOG
UMSG_DUNCANFACTORY_DOG_PASS:
.faraddr MSG_DUNCANFACTORY_DOG_PASS
.faraddr $00000
UMSG_MERRYSVILLE_BEATUPGUY:
.faraddr MSG_MERRYSVILLE_BEATUPGUY
.faraddr $00000
UMSG_MERRYSVILLE_CURFEWGUY:
.faraddr MSG_MERRYSVILLE_CURFEWGUY
.faraddr $00000
.faraddr $00000
UMSG_TWINKLE_LLOYDBULLY:
.faraddr MSG_TWINKLE_LLOYDBULLY
UMSG_TWINKLE_LLOYDBULLY_LLOYD:
.faraddr MSG_TWINKLE_LLOYDBULLY_LLOYD
UMSG_TWINKLE_LLOYDBULLY2:
.faraddr MSG_TWINKLE_LLOYDBULLY2
.faraddr $03E3C
.faraddr $03E4C
.faraddr $03E99
.faraddr $03EC6
.faraddr $03EFF
.faraddr $03F14
.faraddr $03F47
.faraddr $03FD7
.faraddr $04000
.faraddr $04057
.faraddr $0409D
.faraddr $00000
.faraddr $0412E
.faraddr $041C1
.faraddr $041F1
.faraddr $04227
.faraddr $00000
.faraddr $042A7
.faraddr $042FB
.faraddr $04341
.faraddr $04394
UMSG_TWINKLE_HALLMONITOR:
.faraddr MSG_TWINKLE_HALLMONITOR
UMSG_TWINKLE_HALLMONITOR2:
.faraddr MSG_TWINKLE_HALLMONITOR2
UMSG_TWINKLE_HALLMONITOR2_YES:
.faraddr MSG_TWINKLE_HALLMONITOR2_YES
UMSG_ELLAY_LHCOP_SEEWEAPON:
.faraddr MSG_ELLAY_LHCOP_SEEWEAPON
.faraddr $00000
.faraddr $044A5
.faraddr $044EE
.faraddr $0453F
.faraddr $04556
UMSG_SWAMP_HOUSEPIPPI_REST:
.faraddr MSG_SWAMP_HOUSEPIPPI_REST
.faraddr $00000
.faraddr $045F5
.faraddr $04678
.faraddr $046A6
.faraddr $046E9
.faraddr $00000
.faraddr $04758
.faraddr $04788
.faraddr $00000
.faraddr $047BD
.faraddr $04802
.faraddr $04865
.faraddr $00000
.faraddr $048C9
UMSG_ELLAY_LHCOP_TAKEWEAPON:
.faraddr MSG_ELLAY_LHCOP_TAKEWEAPON
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $04958
.faraddr $00000
.faraddr $00000
UMSG_REINDEER_NOSEYGUY_HAT:
.faraddr MSG_REINDEER_NOSEYGUY_HAT
UMSG_MISLAY_MOUTHWASHGUY_LEAVE:
.faraddr MSG_MISLAY_MOUTHWASHGUY_LEAVE
.faraddr $04A21
UMSG_REINDEER_NOSEYGUY:
.faraddr MSG_REINDEER_NOSEYGUY
.faraddr $00000
.faraddr $04AF8
UMSG_REINDEER_COP1:
.faraddr MSG_REINDEER_COP1
UMSG_REINDEER_COP1_ACCEPT:
.faraddr MSG_REINDEER_COP1_ACCEPT
UMSG_REINDEER_COP1_DECLINE:
.faraddr MSG_REINDEER_COP1_DECLINE
UMSG_REINDEER_MONEYGUY:
.faraddr MSG_REINDEER_MONEYGUY
UMSG_REINDEER_MONEYGUY_ACCEPT:
.faraddr MSG_REINDEER_MONEYGUY_ACCEPT
UMSG_REINDEER_MONEYGUY_DECLINE:
.faraddr MSG_REINDEER_MONEYGUY_DECLINE
UMSG_REINDEER_MONEYGUY_AFTER:
.faraddr MSG_REINDEER_MONEYGUY_AFTER
UMSG_REINDEER_COP2:
.faraddr MSG_REINDEER_COP2
UMSG_REINDEER_COP2_ACCEPT:
.faraddr MSG_REINDEER_COP2_ACCEPT
UMSG_REINDEER_COP2_DECLINE:
.faraddr MSG_REINDEER_COP2_DECLINE
UMSG_REINDEER_FULLGIRL:
.faraddr MSG_REINDEER_FULLGIRL
UMSG_REINDEER_ELLAYGUY:
.faraddr MSG_REINDEER_ELLAYGUY
UMSG_REINDEER_SINGINGGUY:
.faraddr MSG_REINDEER_SINGINGGUY
UMSG_REINDEER_SINGINGGUY_ACCEPT:
.faraddr MSG_REINDEER_SINGINGGUY_ACCEPT
UMSG_REINDEER_SINGINGGUY_DECLINE:
.faraddr MSG_REINDEER_SINGINGGUY_DECLINE
UMSG_REINDEER_SINGINGGUY_DECLINE2:
.faraddr MSG_REINDEER_SINGINGGUY_DECLINE2
.faraddr $00000
UMSG_REINDEER_DRAGONGIRL:
.faraddr MSG_REINDEER_DRAGONGIRL
UMSG_REINDEER_SPOOKANEGIRL:
.faraddr MSG_REINDEER_SPOOKANEGIRL
.faraddr $00000
UMSG_REINDEER_FLEABAGGIRL:
.faraddr MSG_REINDEER_FLEABAGGIRL
UMSG_REINDEER_FLEABAGGIRL2:
.faraddr MSG_REINDEER_FLEABAGGIRL2
UMSG_REINDEER_FLEABAGGIRL_DECLINE:
.faraddr MSG_REINDEER_FLEABAGGIRL_DECLINE
UMSG_REINDEER_FLEABAGGIRL_ACCEPT:
.faraddr MSG_REINDEER_FLEABAGGIRL_ACCEPT
UMSG_REINDEER_FLEABAGGIRL_GIVE:
.faraddr MSG_REINDEER_FLEABAGGIRL_GIVE
UMSG_REINDEER_FLUGUY:
.faraddr MSG_REINDEER_FLUGUY
UMSG_REINDEER_RUMORMWGUY:
.faraddr MSG_REINDEER_RUMORMWGUY
UMSG_MISLAY_MOUTHWASHGUY_DENTURELESS:
.faraddr MSG_MISLAY_MOUTHWASHGUY_DENTURELESS
UMSG_MISLAY_MOUTHWASHKID:
.faraddr MSG_MISLAY_MOUTHWASHKID
UMSG_MISLAY_MOUTHWASHGUY_DENTURES:
.faraddr MSG_MISLAY_MOUTHWASHGUY_DENTURES
.faraddr $00000
UMSG_MISLAY_MOUTHWASHKID_TAKE:
.faraddr MSG_MISLAY_MOUTHWASHKID_TAKE
UMSG_REINDEER_COLDGUY:
.faraddr MSG_REINDEER_COLDGUY
UMSG_SPOOKANE_RUMORGUY:
.faraddr MSG_SPOOKANE_RUMORGUY
UMSG_SPOOKANE_RUMORGUY_ACCEPT:
.faraddr MSG_SPOOKANE_RUMORGUY_ACCEPT
UMSG_SPOOKANE_RUMORGUY_DECLINE:
.faraddr MSG_SPOOKANE_RUMORGUY_DECLINE
UMSG_SPOOKANE_HOTELBELLHOP:
.faraddr MSG_SPOOKANE_HOTELBELLHOP
.faraddr $0543D
.faraddr $0545E
.faraddr $054A6
.faraddr $054B9
.faraddr $054CF
.faraddr $054FC
UMSG_SPOOKANE_ROSEMARYGUY:
.faraddr MSG_SPOOKANE_ROSEMARYGUY
UMSG_SPOOKANE_SMALLGUY:
.faraddr MSG_SPOOKANE_SMALLGUY
UMSG_SPOOKANE_HINTGIRL:
.faraddr MSG_SPOOKANE_HINTGIRL
.faraddr $00000
UMSG_SPOOKANE_HINTGIRL_DECLINE:
.faraddr MSG_SPOOKANE_HINTGIRL_DECLINE
UMSG_SPOOKANE_HINTGIRL_ACCEPT:
.faraddr MSG_SPOOKANE_HINTGIRL_ACCEPT
UMSG_SPOOKANE_CLOWN:
.faraddr MSG_SPOOKANE_CLOWN
UMSG_SPOOKANE_CLOWN_ACCEPT:
.faraddr MSG_SPOOKANE_CLOWN_ACCEPT
UMSG_SPOOKANE_CLOWN_DECLINE:
.faraddr MSG_SPOOKANE_CLOWN_DECLINE
UMSG_SPOOKANE_MRSROSEMARY:
.faraddr MSG_SPOOKANE_MRSROSEMARY
.faraddr $05828
.faraddr $00000
.faraddr $05870
.faraddr $05993
UMSG_SPOOKANE_MRSROSEMARY_KEY:
.faraddr MSG_SPOOKANE_MRSROSEMARY_KEY
UMSG_SPOOKANE_NINTENROSEMARY:
.faraddr MSG_SPOOKANE_NINTENROSEMARY
UMSG_SPOOKANE_MRSROSEMARY1:
.faraddr MSG_SPOOKANE_MRSROSEMARY1
UMSG_SPOOKANE_MRSROSEMARY2:
.faraddr MSG_SPOOKANE_MRSROSEMARY2
.faraddr $05B6A
UMSG_SNOWMAN_YOUNGTOWNGUY:
.faraddr MSG_SNOWMAN_YOUNGTOWNGUY
.faraddr $05BBA
UMSG_SNOWMAN_SPOOKANEGUY:
.faraddr MSG_SNOWMAN_SPOOKANEGUY
UMSG_SNOWMAN_SPOOKANEGUY_ACCEPT:
.faraddr MSG_SNOWMAN_SPOOKANEGUY_ACCEPT
UMSG_SNOWMAN_SPOOKANEGUY_DECLINE:
.faraddr MSG_SNOWMAN_SPOOKANEGUY_DECLINE
UMSG_SNOWMAN_COLDGUY:
.faraddr MSG_SNOWMAN_COLDGUY
.faraddr $00000
UMSG_SNOWMAN_LIFEGIRL:
.faraddr MSG_SNOWMAN_LIFEGIRL
UMSG_SNOWMAN_SCHOOLGUY:
.faraddr MSG_SNOWMAN_SCHOOLGUY
UMSG_SNOWMAN_SCHOOLGUY2:
.faraddr MSG_SNOWMAN_SCHOOLGUY2
.faraddr $00000
UMSG_ELLAY_JAILCOP_NOMONEY:
.faraddr MSG_ELLAY_JAILCOP_NOMONEY
UMSG_SNOWMAN_NOSEGIRL:
.faraddr MSG_SNOWMAN_NOSEGIRL
UMSG_SNOWMAN_PHONE_2:
.faraddr MSG_SNOWMAN_PHONE_2
UMSG_SNOWMAN_PHONE_1:
.faraddr MSG_SNOWMAN_PHONE_1
UMSG_SNOWMAN_PHONE_3:
.faraddr MSG_SNOWMAN_PHONE_3
UMSG_SNOWMAN_PHONE_END:
.faraddr MSG_SNOWMAN_PHONE_END
.faraddr $05FBD
.faraddr $05FCC
.faraddr $06000
.faraddr $060A6
.faraddr $06104
.faraddr $06125
.faraddr $06147
.faraddr $06175
.faraddr $061AE
.faraddr $061C9
.faraddr $061E4
.faraddr $06230
.faraddr $00000
.faraddr $0628E
.faraddr $062FA
UMSG_MERRYSVILLE_PASSTRIGGER:
.faraddr MSG_MERRYSVILLE_PASSTRIGGER
.faraddr $063BA
UMSG_SNOWMAN_YUCCAGIRL:
.faraddr MSG_SNOWMAN_YUCCAGIRL
UMSG_YUCCA_NICEBONES:
.faraddr MSG_YUCCA_NICEBONES
UMSG_YUCCA_SIGNBONES:
.faraddr MSG_YUCCA_SIGNBONES
UMSG_YUCCA_BRAVEBONES:
.faraddr MSG_YUCCA_BRAVEBONES
UMSG_YUCCA_CAMELBONES:
.faraddr MSG_YUCCA_CAMELBONES
UMSG_YUCCA_CAMELBONES_ACCEPT:
.faraddr MSG_YUCCA_CAMELBONES_ACCEPT
UMSG_YUCCA_CAMELBONES_DECLINE:
.faraddr MSG_YUCCA_CAMELBONES_DECLINE
UMSG_YUCCA_GAMEBONES:
.faraddr MSG_YUCCA_GAMEBONES
UMSG_YUCCA_SIGN:
.faraddr MSG_YUCCA_SIGN
UMSG_YUCCA_PILOT_MINE:
.faraddr MSG_YUCCA_PILOT_MINE
UMSG_YUCCA_PILOT_RIDE:
.faraddr MSG_YUCCA_PILOT_RIDE
UMSG_YUCCA_PILOT_RIDE_ACCEPT:
.faraddr MSG_YUCCA_PILOT_RIDE_ACCEPT
UMSG_YUCCA_PILOT_RIDE_DECLINE:
.faraddr MSG_YUCCA_PILOT_RIDE_DECLINE
UMSG_YUCCA_PILOT_TANK:
.faraddr MSG_YUCCA_PILOT_TANK
UMSG_ELLAY_PILOT:
.faraddr MSG_ELLAY_PILOT
.faraddr $00000
UMSG_ELLAY_PILOT_ACCEPT:
.faraddr MSG_ELLAY_PILOT_ACCEPT
UMSG_ELLAY_PILOT_DECLINE:
.faraddr MSG_ELLAY_PILOT_DECLINE
.faraddr $00000
UMSG_YOUNGTOWN_PARENTGIRL:
.faraddr MSG_YOUNGTOWN_PARENTGIRL
UMSG_YOUNGTOWN_GUARD:
.faraddr MSG_YOUNGTOWN_GUARD
UMSG_YOUNGTOWN_GUARD2:
.faraddr MSG_YOUNGTOWN_GUARD2
UMSG_YOUNGTOWN_BABYGIRL:
.faraddr MSG_YOUNGTOWN_BABYGIRL
UMSG_YOUNGTOWN_MATHGUY:
.faraddr MSG_YOUNGTOWN_MATHGUY
UMSG_YOUNGTOWN_MOMGIRL:
.faraddr MSG_YOUNGTOWN_MOMGIRL
UMSG_YOUNGTOWN_DADGUY:
.faraddr MSG_YOUNGTOWN_DADGUY
UMSG_YOUNGTOWN_SHIPGIRL:
.faraddr MSG_YOUNGTOWN_SHIPGIRL
UMSG_YOUNGTOWN_GROWNUPGUY:
.faraddr MSG_YOUNGTOWN_GROWNUPGUY
UMSG_YOUNGTOWN_HOLDMEGIRL:
.faraddr MSG_YOUNGTOWN_HOLDMEGIRL
UMSG_YOUNGTOWN_HOLDMEGUY:
.faraddr MSG_YOUNGTOWN_HOLDMEGUY
UMSG_YOUNGTOWN_HOLDMEGUY2:
.faraddr MSG_YOUNGTOWN_HOLDMEGUY2
UMSG_YOUNGTOWN_PLEASEGIRL:
.faraddr MSG_YOUNGTOWN_PLEASEGIRL
.faraddr $06B9A
.faraddr $06BF1
.faraddr $00000
.faraddr $06C1D
.faraddr $06C2A
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
UMSG_YOUNGTOWN_VOICEGUY:
.faraddr MSG_YOUNGTOWN_VOICEGUY
UMSG_ELLAY_JAILCOP_NOROOM:
.faraddr MSG_ELLAY_JAILCOP_NOROOM
UMSG_ELLAY_LHCOP_JAIL:
.faraddr MSG_ELLAY_LHCOP_JAIL
UMSG_ELLAY_BBGANGFAKE:
.faraddr MSG_ELLAY_BBGANGFAKE
UMSG_ELLAY_BBGANGWOMAN:
.faraddr MSG_ELLAY_BBGANGWOMAN
UMSG_ELLAY_BBGANGGIRL:
.faraddr MSG_ELLAY_BBGANGGIRL
UMSG_ELLAY_BBGANGWOMAN2:
.faraddr MSG_ELLAY_BBGANGWOMAN2
UMSG_ELLAY_CLOUDGUY:
.faraddr MSG_ELLAY_CLOUDGUY
UMSG_ELLAY_PEACEGUY:
.faraddr MSG_ELLAY_PEACEGUY
UMSG_ELLAY_PEACEGUY_DEFAULT:
.faraddr MSG_ELLAY_PEACEGUY_DEFAULT
UMSG_ELLAY_PEACEGUY_DECLINE:
.faraddr MSG_ELLAY_PEACEGUY_DECLINE
UMSG_ELLAY_TICKETGUY:
.faraddr MSG_ELLAY_TICKETGUY
UMSG_ELLAY_JAILCOP_HASWEAPON_ACCEPT:
.faraddr MSG_ELLAY_JAILCOP_HASWEAPON_ACCEPT
UMSG_ELLAY_JAILCOP_HASWEAPON_DECLINE:
.faraddr MSG_ELLAY_JAILCOP_HASWEAPON_DECLINE
UMSG_ELLAY_SECRETGIRL:
.faraddr MSG_ELLAY_SECRETGIRL
UMSG_ELLAY_SECRETGIRL_ACCEPT:
.faraddr MSG_ELLAY_SECRETGIRL_ACCEPT
UMSG_ELLAY_SECRETGIRL_DECLINE:
.faraddr MSG_ELLAY_SECRETGIRL_DECLINE
UMSG_ELLAY_LHBACKROOMGUY:
.faraddr MSG_ELLAY_LHBACKROOMGUY
.faraddr $00000
UMSG_ELLAY_LHDRINKGIRL_OFFER:
.faraddr MSG_ELLAY_LHDRINKGIRL_OFFER
UMSG_ELLAY_LHDRINKGIRL_OFFER_REFUSE:
.faraddr MSG_ELLAY_LHDRINKGIRL_OFFER_REFUSE
UMSG_ELLAY_LHDRINKGIRL:
.faraddr MSG_ELLAY_LHDRINKGIRL
UMSG_ELLAY_LHCOP_JAILSHAME:
.faraddr MSG_ELLAY_LHCOP_JAILSHAME
UMSG_ELLAY_LHCOP_JAILSHAME_YES:
.faraddr MSG_ELLAY_LHCOP_JAILSHAME_YES
UMSG_ELLAY_LHCOP_JAILSHAME_NO:
.faraddr MSG_ELLAY_LHCOP_JAILSHAME_NO
UMSG_ELLAY_JAILCOP_HASWEAPON:
.faraddr MSG_ELLAY_JAILCOP_HASWEAPON
UMSG_ELLAY_PILOT_NOMONEY:
.faraddr MSG_ELLAY_PILOT_NOMONEY
UMSG_ELLAY_LHTEDDYGIRL:
.faraddr MSG_ELLAY_LHTEDDYGIRL
UMSG_ELLAY_LHTEDDYGIRL2:
.faraddr MSG_ELLAY_LHTEDDYGIRL2
UMSG_ELLAY_LHBOUNCERGUY_OFFER:
.faraddr MSG_ELLAY_LHBOUNCERGUY_OFFER
UMSG_ELLAY_LHBOUNCERGUY_OFFER_YES:
.faraddr MSG_ELLAY_LHBOUNCERGUY_OFFER_YES
UMSG_ELLAY_LHBOUNCERGUY_OFFER_NO:
.faraddr MSG_ELLAY_LHBOUNCERGUY_OFFER_NO
.faraddr $00000
UMSG_ELLAY_LHCUTEGUY2:
.faraddr MSG_ELLAY_LHCUTEGUY2
UMSG_ELLAY_LHCUTEGUY:
.faraddr MSG_ELLAY_LHCUTEGUY
UMSG_ELLAY_LHTEDDY_INTRO:
.faraddr MSG_ELLAY_LHTEDDY_INTRO
UMSG_ELLAY_LHTEDDY_INTRO_YES:
.faraddr MSG_ELLAY_LHTEDDY_INTRO_YES
UMSG_ELLAY_LHTEDDY_INTRO_NO:
.faraddr MSG_ELLAY_LHTEDDY_INTRO_NO
UMSG_ELLAY_LHTEDDY_POSTFIGHT:
.faraddr MSG_ELLAY_LHTEDDY_POSTFIGHT
.faraddr $00000
UMSG_MYHOME_MOM_HELP:
.faraddr MSG_MYHOME_MOM_HELP
.faraddr $075CD
UMSG_ELLAY_LHTEDDY_TEAMUP_AGREE:
.faraddr MSG_ELLAY_LHTEDDY_TEAMUP_AGREE
.faraddr $00000
.faraddr $00000
UMSG_ELLAY_LHTEDDY_TEAMUP_DECLINE2:
.faraddr MSG_ELLAY_LHTEDDY_TEAMUP_DECLINE2
UMSG_ELLAY_LHTEDDY_TEAMUP_DECLINE3:
.faraddr MSG_ELLAY_LHTEDDY_TEAMUP_DECLINE3
UMSG_ELLAY_LHTEDDY_REPLACELLOYD:
.faraddr MSG_ELLAY_LHTEDDY_REPLACELLOYD
.faraddr $00000
.faraddr $07757
.faraddr $077C8
UMSG_ELLAY_LHSIDEGUY:
.faraddr MSG_ELLAY_LHSIDEGUY
.faraddr $07843
.faraddr $07894
UMSG_SNOWMAN_REGNAME:
.faraddr MSG_SNOWMAN_REGNAME
UMSG_ELLAY_HARBORGUY:
.faraddr MSG_ELLAY_HARBORGUY
.faraddr $07933
.faraddr $0795D
.faraddr $079B5
.faraddr $079E7
.faraddr $00000
.faraddr $00000
.faraddr $07A41
.faraddr $00000
.faraddr $07A9B
.faraddr $07ADB
.faraddr $07B03
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $07BD5
.faraddr $07C08
.faraddr $07C50
.faraddr $07CB9
.faraddr $07D03
UMSG_MYHOME_MINNIE_STORAGE_INVFULL:
.faraddr MSG_MYHOME_MINNIE_STORAGE_INVFULL
.faraddr $07D43
UMSG_PODUNK_PIPPI_FRIEND:
.faraddr MSG_PODUNK_PIPPI_FRIEND
UMSG_TWINKLE_LLOYDBULLY_DEADLLOYD:
.faraddr MSG_TWINKLE_LLOYDBULLY_DEADLLOYD
UMSG_PODUNK_SIGN:
.faraddr MSG_PODUNK_SIGN
UMSG_ZOO_OFFICESIGN:
.faraddr MSG_ZOO_OFFICESIGN
UMSG_ELLAY_LOOKOUTTOWERSIGN:
.faraddr MSG_ELLAY_LOOKOUTTOWERSIGN
UMSG_HOSPITAL_NOPERSON:
.faraddr MSG_HOSPITAL_NOPERSON
.faraddr $07E95
UMSG_HEALER_MAN:
.faraddr MSG_HEALER_MAN
.faraddr $07F08
UMSG_REINDEER_MISLAYSIGN:
.faraddr MSG_REINDEER_MISLAYSIGN
UMSG_REINDEER_MISLAYSIGN2:
.faraddr MSG_REINDEER_MISLAYSIGN2
.faraddr $07FA1
.faraddr $07FCE
.faraddr $00000
UMSG_MYHOME_INVASION:
.faraddr MSG_MYHOME_INVASION
.faraddr $08032
UMSG_MYHOME_MOM_COOK:
.faraddr MSG_MYHOME_MOM_COOK
.faraddr $00000
.faraddr $00000
.faraddr $00000
UMSG_PODUNK_PIPPIMOM:
.faraddr MSG_PODUNK_PIPPIMOM
.faraddr $081A7
.faraddr $081B4
.faraddr $081E9
.faraddr $00000
.faraddr $00000
.faraddr $0826F
UMSG_ELLAY_LHBOUNCERGUY_TRIO:
.faraddr MSG_ELLAY_LHBOUNCERGUY_TRIO
.faraddr $0832A
.faraddr $00000
.faraddr $08353
.faraddr $00000
UMSG_ELLAY_LHBOUNCERGIRL:
.faraddr MSG_ELLAY_LHBOUNCERGIRL
.faraddr $00000
UMSG_MYHOME_MINNIE_STORAGE_STASH:
.faraddr MSG_MYHOME_MINNIE_STORAGE_STASH
UMSG_MYHOME_MINNIE_STORAGE_BYE:
.faraddr MSG_MYHOME_MINNIE_STORAGE_BYE
UMSG_MYHOME_MINNIE_STORAGE_TAKE:
.faraddr MSG_MYHOME_MINNIE_STORAGE_TAKE
.faraddr $08466
.faraddr $084D1
.faraddr $084E2
.faraddr $00000
UMSG_HEALER_BROKE:
.faraddr MSG_HEALER_BROKE
UMSG_YUCCA_PILOT_NOROOM:
.faraddr MSG_YUCCA_PILOT_NOROOM
UMSG_YUCCA_PILOT_NOMONEY:
.faraddr MSG_YUCCA_PILOT_NOMONEY
.faraddr $085A4
.faraddr $00000
UMSG_PODUNK_PIPPI_NOROOM:
.faraddr MSG_PODUNK_PIPPI_NOROOM
.faraddr $085F2
.faraddr $0860C
.faraddr $00000
.faraddr $08624
.faraddr $0864C
UMSG_GRAVEYARD_PIPPI_LEAVE:
.faraddr MSG_GRAVEYARD_PIPPI_LEAVE
UMSG_PODUNK_PIPPI_NOROOM2:
.faraddr MSG_PODUNK_PIPPI_NOROOM2
.faraddr $086CA
.faraddr $086EF
.faraddr $00000
UMSG_YUCCA_PILOT_CHOOSEPLAN:
.faraddr MSG_YUCCA_PILOT_CHOOSEPLAN
.faraddr $00000
.faraddr $00000
UMSG_MISLAY_MOUTHWASHGUY_DENTURES2:
.faraddr MSG_MISLAY_MOUTHWASHGUY_DENTURES2
UMSG_YUCCA_PILOT_NOMONEY2:
.faraddr MSG_YUCCA_PILOT_NOMONEY2
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
UMSG_SPOOKANE_MRSROSEMARY3:
.faraddr MSG_SPOOKANE_MRSROSEMARY3
UMSG_PODUNK_PIPPI_GOODBYE:
.faraddr MSG_PODUNK_PIPPI_GOODBYE
UMSG_ELLAY_LHTEDDY_CHALLENGE:
.faraddr MSG_ELLAY_LHTEDDY_CHALLENGE
UMSG_ELLAY_SECRETGIRL_TEDDY:
.faraddr MSG_ELLAY_SECRETGIRL_TEDDY
.faraddr $00000
UMSG_ELLAY_LHTEDDY_TEAMUP_DECLINE:
.faraddr MSG_ELLAY_LHTEDDY_TEAMUP_DECLINE
UMSG_MERRYSVILLE_PASSTRIGGER2:
.faraddr MSG_MERRYSVILLE_PASSTRIGGER2
UMSG_MISLAY_MOUTHWASHKID_NOMONEY:
.faraddr MSG_MISLAY_MOUTHWASHKID_NOMONEY
UMSG_MERRYSVILLE_QUESTIONNAIRE_NOROOM:
.faraddr MSG_MERRYSVILLE_QUESTIONNAIRE_NOROOM
.faraddr $088C6
.faraddr $0891C
.faraddr $089DA
.faraddr $08A2C
.faraddr $08A63
.faraddr $08A74
.faraddr $08AAD
.faraddr $08ADE
.faraddr $08B0A
.faraddr $08BD4
.faraddr $08BF0
UMSG_CANARY_LAURA:
.faraddr MSG_CANARY_LAURA
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $08C55
.faraddr $08CB0
.faraddr $00000
.faraddr $08CE8
.faraddr $08D0A
.faraddr $08D3E
UMSG_SWAMP_HOUSEPIPPI_MORNING:
.faraddr MSG_SWAMP_HOUSEPIPPI_MORNING
.faraddr $08D83
.faraddr $08DB2
.faraddr $08DD9
.faraddr $08E10
.faraddr $08E3F
.faraddr $08E76
.faraddr $08EC2
.faraddr $08EE8
.faraddr $08F46
.faraddr $08F79
.faraddr $08FB0
.faraddr $08FEB
.faraddr $0901C
.faraddr $00000
.faraddr $0903B
.faraddr $09077
.faraddr $090A1
.faraddr $090D9
.faraddr $09123
.faraddr $0914B
.faraddr $0916B
.faraddr $091D0
.faraddr $09223
.faraddr $09259
.faraddr $092A2
.faraddr $092CD
.faraddr $09318
.faraddr $093A4
UMSG_MYHOME_MIMMIE_INVASION2:
.faraddr MSG_MYHOME_MIMMIE_INVASION2
UMSG_MYHOME_MOM_INVASION2:
.faraddr MSG_MYHOME_MOM_INVASION2
.faraddr $0940A
.faraddr $0945E
.faraddr $09488
.faraddr $094AD
UMSG_SPOOKANE_HINTGIRL_HINT1:
.faraddr MSG_SPOOKANE_HINTGIRL_HINT1
.faraddr $00000
.faraddr $0953C
UMSG_ELLAY_LHCOP_ARREST:
.faraddr MSG_ELLAY_LHCOP_ARREST
.faraddr $00000
.faraddr $00000
UMSG_ELLAY_LHBACKROOMGUY_MINE:
.faraddr MSG_ELLAY_LHBACKROOMGUY_MINE
UMSG_ELLAY_LHSIDEGUY_MINE:
.faraddr MSG_ELLAY_LHSIDEGUY_MINE
UMSG_YUCCA_MINE:
.faraddr MSG_YUCCA_MINE
.faraddr $09747
UMSG_HOSPITAL_NURSE_DECLINE:
.faraddr MSG_HOSPITAL_NURSE_DECLINE
UMSG_HOSPITAL_NURSE_NOONE:
.faraddr MSG_HOSPITAL_NURSE_NOONE
UMSG_REINDEER_HOSPITALWEIGHTGUY:
.faraddr MSG_REINDEER_HOSPITALWEIGHTGUY
UMSG_REINDEER_HOSPITALCOLDGUY:
.faraddr MSG_REINDEER_HOSPITALCOLDGUY
UMSG_PODUNK_HOTELWOMAN:
.faraddr MSG_PODUNK_HOTELWOMAN
UMSG_REINDEER_HOTELGUY:
.faraddr MSG_REINDEER_HOTELGUY
UMSG_MERRYSVILLE_HOTELWAITER:
.faraddr MSG_MERRYSVILLE_HOTELWAITER
UMSG_MERRYSVILLE_HOTELMUSCIALGIRL:
.faraddr MSG_MERRYSVILLE_HOTELMUSCIALGIRL
UMSG_MERRYSVILLE_HOTELFAVFOODGUY:
.faraddr MSG_MERRYSVILLE_HOTELFAVFOODGUY
UMSG_MERRYSVILLE_HOTELGUY:
.faraddr MSG_MERRYSVILLE_HOTELGUY
UMSG_PODUNK_HOTELGUY:
.faraddr MSG_PODUNK_HOTELGUY
UMSG_MERRYSVILLE_TRAINWOMAN2:
.faraddr MSG_MERRYSVILLE_TRAINWOMAN2
UMSG_MYHOME_DOG:
.faraddr MSG_MYHOME_DOG
UMSG_SPOOKANE_HINTGIRL_NOMONEY:
.faraddr MSG_SPOOKANE_HINTGIRL_NOMONEY
.faraddr $09B3D
.faraddr $09B67
.faraddr $00000
.faraddr $00000
.faraddr $09B97
UMSG_ELLAY_LHBOUNCERGIRL2:
.faraddr MSG_ELLAY_LHBOUNCERGIRL2
.faraddr $09BD4
.faraddr $09C0B
.faraddr $00000
.faraddr $00000
.faraddr $09C21
UMSG_SWAMP_HOUSEPIPPI:
.faraddr MSG_SWAMP_HOUSEPIPPI
.faraddr $09D23
.faraddr $09D6F
.faraddr $09DC8
.faraddr $00000
.faraddr $09DEF
UMSG_ELLAY_LHCOP_JAILSCENE1:
.faraddr MSG_ELLAY_LHCOP_JAILSCENE1
UMSG_ELLAY_LHCOP_JAILSCENE2:
.faraddr MSG_ELLAY_LHCOP_JAILSCENE2
UMSG_PODUNK_PIPPI_BRAVE:
.faraddr MSG_PODUNK_PIPPI_BRAVE
UMSG_PODUNK_CANARYGUY:
.faraddr MSG_PODUNK_CANARYGUY
UMSG_PODUNK_SHYGUY:
.faraddr MSG_PODUNK_SHYGUY
UMSG_PODUNK_ASTHMAGIRL:
.faraddr MSG_PODUNK_ASTHMAGIRL
UMSG_MERRYSVILLE_NINTENDOGIRL:
.faraddr MSG_MERRYSVILLE_NINTENDOGIRL
UMSG_MERRYSVILLE_HAPPYGUY:
.faraddr MSG_MERRYSVILLE_HAPPYGUY
UMSG_MERRYSVILLE_STRIPGIRL:
.faraddr MSG_MERRYSVILLE_STRIPGIRL
UMSG_MERRYSVILLE_DOCTORGUY:
.faraddr MSG_MERRYSVILLE_DOCTORGUY
UMSG_MERRYSVILLE_QUESTIONNAIRE_DECLINE:
.faraddr MSG_MERRYSVILLE_QUESTIONNAIRE_DECLINE
UMSG_MERRYSVILLE_SCHOOLGUY:
.faraddr MSG_MERRYSVILLE_SCHOOLGUY
UMSG_MERRYSVILLE_MAYORGUY:
.faraddr MSG_MERRYSVILLE_MAYORGUY
UMSG_MERRYSVILLE_ROCKETGUY:
.faraddr MSG_MERRYSVILLE_ROCKETGUY
UMSG_MERRYSVILLE_ORDINARYGUY:
.faraddr MSG_MERRYSVILLE_ORDINARYGUY
UMSG_MERRYSVILLE_THINKINGGUY:
.faraddr MSG_MERRYSVILLE_THINKINGGUY
UMSG_MERRYSVILLE_HUSBANDGIRL:
.faraddr MSG_MERRYSVILLE_HUSBANDGIRL
UMSG_MERRYSVILLE_SWEETSGUY:
.faraddr MSG_MERRYSVILLE_SWEETSGUY
UMSG_MERRYSVILLE_MONSTERGIRL:
.faraddr MSG_MERRYSVILLE_MONSTERGIRL
.faraddr $0A4B7
.faraddr $0A51D
UMSG_REINDEER_RUMORMWGIRL:
.faraddr MSG_REINDEER_RUMORMWGIRL
UMSG_REINDEER_TUNNELGUY:
.faraddr MSG_REINDEER_TUNNELGUY
UMSG_REINDEER_QUIETWOMAN:
.faraddr MSG_REINDEER_QUIETWOMAN
UMSG_REINDEER_FOODGIRL:
.faraddr MSG_REINDEER_FOODGIRL
UMSG_REINDEER_PEEPINGGUY:
.faraddr MSG_REINDEER_PEEPINGGUY
UMSG_REINDEER_BICYCLEGUY:
.faraddr MSG_REINDEER_BICYCLEGUY
UMSG_REINDEER_BEGGIRL:
.faraddr MSG_REINDEER_BEGGIRL
UMSG_REINDEER_BEAUTYGIRL:
.faraddr MSG_REINDEER_BEAUTYGIRL
UMSG_REINDEER_NONBELIEVERGUY:
.faraddr MSG_REINDEER_NONBELIEVERGUY
UMSG_REINDEER_NIHILISTICGUY:
.faraddr MSG_REINDEER_NIHILISTICGUY
UMSG_REINDEER_SPOOKANEGIRL2:
.faraddr MSG_REINDEER_SPOOKANEGIRL2
UMSG_REINDEER_CHARITYWOMAN:
.faraddr MSG_REINDEER_CHARITYWOMAN
UMSG_REINDEER_MEDICINEGUY:
.faraddr MSG_REINDEER_MEDICINEGUY
UMSG_SPOOKANE_POSTMAN:
.faraddr MSG_SPOOKANE_POSTMAN
UMSG_SPOOKANE_POSTMANGIRL:
.faraddr MSG_SPOOKANE_POSTMANGIRL
UMSG_SPOOKANE_HATERGIRL:
.faraddr MSG_SPOOKANE_HATERGIRL
UMSG_SPOOKANE_STREETSGIRL:
.faraddr MSG_SPOOKANE_STREETSGIRL
UMSG_SPOOKANE_WHATGUY:
.faraddr MSG_SPOOKANE_WHATGUY
UMSG_SNOWMAN_PSYCHICGUY:
.faraddr MSG_SNOWMAN_PSYCHICGUY
UMSG_SNOWMAN_CHATEAUWOMAN:
.faraddr MSG_SNOWMAN_CHATEAUWOMAN
UMSG_SNOWMAN_CHATEAUGUY:
.faraddr MSG_SNOWMAN_CHATEAUGUY
UMSG_SNOWMAN_TSHIRTGUY:
.faraddr MSG_SNOWMAN_TSHIRTGUY
UMSG_SNOWMAN_CAMELGUY:
.faraddr MSG_SNOWMAN_CAMELGUY
.faraddr $0ACEF
.faraddr $0AD4B
.faraddr $0AD85
UMSG_ELLAY_FISHER:
.faraddr MSG_ELLAY_FISHER
UMSG_ELLAY_BBGANG1:
.faraddr MSG_ELLAY_BBGANG1
UMSG_ELLAY_BBGANG2:
.faraddr MSG_ELLAY_BBGANG2
UMSG_ELLAY_BBGANG3:
.faraddr MSG_ELLAY_BBGANG3
UMSG_ELLAY_BBGANG4:
.faraddr MSG_ELLAY_BBGANG4
UMSG_ELLAY_BBGANG5:
.faraddr MSG_ELLAY_BBGANG5
UMSG_ELLAY_BBGANG6:
.faraddr MSG_ELLAY_BBGANG6
UMSG_ELLAY_SIGNGUY:
.faraddr MSG_ELLAY_SIGNGUY
UMSG_ELLAY_CACTUSGIRL:
.faraddr MSG_ELLAY_CACTUSGIRL
UMSG_ELLAY_FISHERGUY:
.faraddr MSG_ELLAY_FISHERGUY
.faraddr $0B022
.faraddr $0B05D
.faraddr $0B0A5
.faraddr $0B132
.faraddr $0B14D
.faraddr $0B186
.faraddr $0B1D7
.faraddr $0B1F7
.faraddr $0B240
.faraddr $0B25E
.faraddr $0B29E
.faraddr $0B315
.faraddr $0B337
.faraddr $0B35C
.faraddr $0B392
UMSG_MISLAY_MOUTHWASHKID_NOTAKE:
.faraddr MSG_MISLAY_MOUTHWASHKID_NOTAKE
UMSG_HOSPITAL_NURSE_REVIVE:
.faraddr MSG_HOSPITAL_NURSE_REVIVE
UMSG_HOSPITAL_NURSE_NOREVIVE:
.faraddr MSG_HOSPITAL_NURSE_NOREVIVE
UMSG_PODUNK_HOSPITALDOCTOR:
.faraddr MSG_PODUNK_HOSPITALDOCTOR
UMSG_PODUNK_HOSPITALDOCTOR_DECLINE:
.faraddr MSG_PODUNK_HOSPITALDOCTOR_DECLINE
UMSG_PODUNK_HOSPITALDOCTOR_NORMAL:
.faraddr MSG_PODUNK_HOSPITALDOCTOR_NORMAL
UMSG_PODUNK_HOSPITALDOCTOR_ACCEPT:
.faraddr MSG_PODUNK_HOSPITALDOCTOR_ACCEPT
.faraddr $00000
UMSG_HEALER_INTRO:
.faraddr MSG_HEALER_INTRO
UMSG_HEALER_NO:
.faraddr MSG_HEALER_NO
UMSG_HEALER_PRICE:
.faraddr MSG_HEALER_PRICE
UMSG_HOTELBELLHOP:
.faraddr MSG_HOTELBELLHOP
UMSG_HOTELBELLHOP_DECLINE:
.faraddr MSG_HOTELBELLHOP_DECLINE
UMSG_HOTELBELLHOP_ACCEPT:
.faraddr MSG_HOTELBELLHOP_ACCEPT
UMSG_HOTELBELLHOP_GOODMORNING:
.faraddr MSG_HOTELBELLHOP_GOODMORNING
UMSG_HOSPITAL_NURSE_SELECT:
.faraddr MSG_HOSPITAL_NURSE_SELECT
UMSG_HOSPITAL_NURSE:
.faraddr MSG_HOSPITAL_NURSE
.faraddr $00000
UMSG_YOUNGTOWN_HOTELBELLHOP:
.faraddr MSG_YOUNGTOWN_HOTELBELLHOP
UMSG_YOUNGTOWN_HOTELBELLHOP_GOODMORNING:
.faraddr MSG_YOUNGTOWN_HOTELBELLHOP_GOODMORNING
UMSG_YOUNGTOWN_HOTELBELLHOP_DECLINE:
.faraddr MSG_YOUNGTOWN_HOTELBELLHOP_DECLINE
UMSG_ELLAY_LHBOUNCERGIRL_TICKET:
.faraddr MSG_ELLAY_LHBOUNCERGIRL_TICKET
.faraddr $0B856
.faraddr $00000
UMSG_MYHOME_MINNIE_STORAGE:
.faraddr MSG_MYHOME_MINNIE_STORAGE
UMSG_MYHOME_MINNIE_STORAGE_INVNOTHING:
.faraddr MSG_MYHOME_MINNIE_STORAGE_INVNOTHING
UMSG_MYHOME_MINNIE_STORAGE_NOTHING:
.faraddr MSG_MYHOME_MINNIE_STORAGE_NOTHING
UMSG_MYHOME_MINNIE_STORAGE_FULL:
.faraddr MSG_MYHOME_MINNIE_STORAGE_FULL
.faraddr $0B913
.faraddr $0B925
.faraddr $00000
.faraddr $0B946
.faraddr $0B963
UMSG_SPOOKANE_HOTELBELLHOP_THANKS:
.faraddr MSG_SPOOKANE_HOTELBELLHOP_THANKS
UMSG_MYHOME_DOLL:
.faraddr MSG_MYHOME_DOLL
UMSG_CANARY_PILLAR:
.faraddr MSG_CANARY_PILLAR
.faraddr $0BA39
UMSG_ELLAY_JAILCOP:
.faraddr MSG_ELLAY_JAILCOP
.faraddr $00000
.faraddr $0BAC8
.faraddr $0BADF
.faraddr $0BAF2
UMSG_DOOR_LOCKED:
.faraddr MSG_DOOR_LOCKED
UMSG_DOOR_KEYFAIL:
.faraddr MSG_DOOR_KEYFAIL
UMSG_DOOR_UNLOCKED:
.faraddr MSG_DOOR_UNLOCKED
UMSG_MENU_YES_NO:
.faraddr MSG_MENU_YES_NO
UMSG_MENU_CONTINUE_REST:
.faraddr MSG_MENU_CONTINUE_REST
UMSG_PHONE_GRAB:
.faraddr MSG_PHONE_GRAB
UMSG_HOSPITAL_NURSE_NOMONEY:
.faraddr MSG_HOSPITAL_NURSE_NOMONEY
.faraddr $0BBF4
.faraddr $0BC24
UMSG_HEALER_FIXED:
.faraddr MSG_HEALER_FIXED
.faraddr $0BCBA
UMSG_CANARY_LAURA_SING:
.faraddr MSG_CANARY_LAURA_SING
UMSG_REMEMBER_MELODY:
.faraddr MSG_REMEMBER_MELODY
UMSG_CANARY_SING:
.faraddr MSG_CANARY_SING
UMSG_ZOO_GATEMONKEY_KEY:
.faraddr MSG_ZOO_GATEMONKEY_KEY
.faraddr $0BD70
.faraddr $0BD95
UMSG_PHONE_EXPLVL:
.faraddr MSG_PHONE_EXPLVL
.faraddr $0BDE0
.faraddr $00000
.faraddr $0BDF0
.faraddr $00000
UMSG_PODUNK_PIPPIMOM_RETURN:
.faraddr MSG_PODUNK_PIPPIMOM_RETURN
UMSG_TWINKLE_F1_ROOM6ENTRANCE_NOJANITOR:
.faraddr MSG_TWINKLE_F1_ROOM6ENTRANCE_NOJANITOR
.faraddr $0BF4C
UMSG_HEALER_WHO:
.faraddr MSG_HEALER_WHO
.faraddr $0BF83
UMSG_HEALER_SOFTEN_FAIL:
.faraddr MSG_HEALER_SOFTEN_FAIL
UMSG_MERRYSVILLE_SWEETSGUY_YES:
.faraddr MSG_MERRYSVILLE_SWEETSGUY_YES
UMSG_TWINKLE_F2JANITOR:
.faraddr MSG_TWINKLE_F2JANITOR
UMSG_TWINKLE_F2JANITOR2:
.faraddr MSG_TWINKLE_F2JANITOR2
UMSG_TWINKLE_F2LLOYD:
.faraddr MSG_TWINKLE_F2LLOYD
UMSG_TWINKLE_F1LLOYD:
.faraddr MSG_TWINKLE_F1LLOYD
UMSG_ELLAY_FISHER2:
.faraddr MSG_ELLAY_FISHER2
.faraddr $0C1F3
.faraddr $0C24D
.faraddr $0C280
.faraddr $00000
UMSG_SPOOKANE_HINTGIRL_HINT2:
.faraddr MSG_SPOOKANE_HINTGIRL_HINT2
UMSG_SPOOKANE_HINTGIRL_HINT3:
.faraddr MSG_SPOOKANE_HINTGIRL_HINT3
UMSG_MYHOME_DOG_ADVICE:
.faraddr MSG_MYHOME_DOG_ADVICE
UMSG_ZOO_MONKEY:
.faraddr MSG_ZOO_MONKEY
UMSG_YUCCA_SINGINGCACTUS:
.faraddr MSG_YUCCA_SINGINGCACTUS
.faraddr $0C521
.faraddr $0C54E
.faraddr $0C5B0
UMSG_ZOO_MONKEYSIGN:
.faraddr MSG_ZOO_MONKEYSIGN
UMSG_TWINKLE_F2_UPSTAIRS_PADLOCK:
.faraddr MSG_TWINKLE_F2_UPSTAIRS_PADLOCK
.faraddr $0C683
UMSG_PHONE_PAYPHONE:
.faraddr MSG_PHONE_PAYPHONE
UMSG_GRAVEYARD_PIPPI_AFRAID:
.faraddr MSG_GRAVEYARD_PIPPI_AFRAID
UMSG_ZOO_GATE:
.faraddr MSG_ZOO_GATE
UMSG_ELLAY_BBGANG1_TEDDY:
.faraddr MSG_ELLAY_BBGANG1_TEDDY
UMSG_ELLAY_BBGANG1_TEDDY2:
.faraddr MSG_ELLAY_BBGANG1_TEDDY2
UMSG_MYHOME_MINNIE_STORAGE_CANT:
.faraddr MSG_MYHOME_MINNIE_STORAGE_CANT
.faraddr $0C7C2
.faraddr $0C81F
.faraddr $0C87A
.faraddr $0C8CD
.faraddr $0C91F
UMSG_PODUNK_MAGICOP:
.faraddr MSG_PODUNK_MAGICOP
UMSG_PODUNK_MAGICOP_LIFTED:
.faraddr MSG_PODUNK_MAGICOP_LIFTED
UMSG_PODUNK_MAGICOP2_LIFTED:
.faraddr MSG_PODUNK_MAGICOP2_LIFTED
.faraddr $0CB40
.faraddr $0CB5D
.faraddr $0CBC5
UMSG_REINDEER_SINGINGGUY_ACCEPT2:
.faraddr MSG_REINDEER_SINGINGGUY_ACCEPT2
UMSG_MERRYSVILLE_QUESTIONNAIRE:
.faraddr MSG_MERRYSVILLE_QUESTIONNAIRE
.faraddr $00000
UMSG_MERRYSVILLE_QUESTIONNAIRE_Q1:
.faraddr MSG_MERRYSVILLE_QUESTIONNAIRE_Q1
UMSG_MERRYSVILLE_QUESTIONNAIRE_Q2:
.faraddr MSG_MERRYSVILLE_QUESTIONNAIRE_Q2
UMSG_MERRYSVILLE_QUESTIONNAIRE_FINISH:
.faraddr MSG_MERRYSVILLE_QUESTIONNAIRE_FINISH
UMSG_MERRYSVILLE_QUESTIONNAIRE_DONE:
.faraddr MSG_MERRYSVILLE_QUESTIONNAIRE_DONE
.faraddr $0CDBB
UMSG_GRAVEYARD_CASKET_GENERIC:
.faraddr MSG_GRAVEYARD_CASKET_GENERIC
.faraddr $0CE2D
.faraddr $0CE4F
.faraddr $0CE89
.faraddr $0CEC1
.faraddr $0CEED
.faraddr $00000
.faraddr $0CF4A
.faraddr $0CF65
.faraddr $0CF6F
.faraddr $0CF7D
.faraddr $00000
.faraddr $00000
.faraddr $0D068
.faraddr $00000
.faraddr $00000
.faraddr $0D091
.faraddr $0D0A2
.faraddr $0D0B8
.faraddr $0D0DE
.faraddr $0D0F3
.faraddr $0D10B
.faraddr $0D122
.faraddr $0D13B
.faraddr $0D156
.faraddr $0D16E
.faraddr $0D18B
.faraddr $0D19F
.faraddr $0D1BA
UMSG_GET_ITEM:
.faraddr MSG_GET_ITEM
.faraddr $00000
UMSG_INVENTORY_FULL:
.faraddr MSG_INVENTORY_FULL
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $0D1FA
.faraddr $0D20A
UMSG_CANARY_SIGN:
.faraddr MSG_CANARY_SIGN
UMSG_PODUNK_CANARYSIGN:
.faraddr MSG_PODUNK_CANARYSIGN
UMSG_PODUNK_CITYHALLSIGN:
.faraddr MSG_PODUNK_CITYHALLSIGN
UMSG_ELLAY_RESIDENTIALSIGN:
.faraddr MSG_ELLAY_RESIDENTIALSIGN
UMSG_ELLAY_RESIDENTIALSIGN2:
.faraddr MSG_ELLAY_RESIDENTIALSIGN2
UMSG_PODUNK_GRAVESIGN:
.faraddr MSG_PODUNK_GRAVESIGN
UMSG_PODUNK_MERRYSIGN:
.faraddr MSG_PODUNK_MERRYSIGN
UMSG_PODUNK_ZOOSIGN:
.faraddr MSG_PODUNK_ZOOSIGN
UMSG_SNOWMAN_SIGN:
.faraddr MSG_SNOWMAN_SIGN
UMSG_ELLAY_INTROSIGN:
.faraddr MSG_ELLAY_INTROSIGN
UMSG_MERRYSVILLE_SCHOOLSIGN:
.faraddr MSG_MERRYSVILLE_SCHOOLSIGN
UMSG_MYHOME_SIGN:
.faraddr MSG_MYHOME_SIGN
UMSG_MERRYSVILLE_SIGN:
.faraddr MSG_MERRYSVILLE_SIGN
UMSG_REINDEER_SIGN:
.faraddr MSG_REINDEER_SIGN
UMSG_SPOOKANE_SIGN:
.faraddr MSG_SPOOKANE_SIGN
UMSG_YOUNGTOWN_SIGN:
.faraddr MSG_YOUNGTOWN_SIGN
UMSG_SPOOKANE_MANSIONSIGN:
.faraddr MSG_SPOOKANE_MANSIONSIGN
UMSG_ELLAY_JAILSIGN:
.faraddr MSG_ELLAY_JAILSIGN
UMSG_MERRYSVILLE_DUNCANSIGN:
.faraddr MSG_MERRYSVILLE_DUNCANSIGN
.faraddr $0D664
.faraddr $0D70A
.faraddr $0D729
UMSG_PODUNK_MAGICOP2_LIFTED2:
.faraddr MSG_PODUNK_MAGICOP2_LIFTED2
.faraddr $0D7B5
UMSG_PODUNK_PIPPI_GOODS:
.faraddr MSG_PODUNK_PIPPI_GOODS
UMSG_PODUNK_PIPPI_NOGOODS:
.faraddr MSG_PODUNK_PIPPI_NOGOODS
UMSG_MYHOME_MINNIE:
.faraddr MSG_MYHOME_MINNIE
UMSG_HEALER_MENU:
.faraddr MSG_HEALER_MENU
UMSG_MTITOI_TEDDY_CALL:
.faraddr MSG_MTITOI_TEDDY_CALL
.faraddr $0D8B4
.faraddr $0D8CB
.faraddr $0D92C
.faraddr $0D978
.faraddr $0D9B9
.faraddr $0D9E2
.faraddr $0DA13
.faraddr $0DA31
.faraddr $0DA88
UMSG_MERRYSVILLE_SWEETSSIGN:
.faraddr MSG_MERRYSVILLE_SWEETSSIGN
.faraddr $0DAF8
UMSG_SNOWMAN_PHONE_CHECK:
.faraddr MSG_SNOWMAN_PHONE_CHECK
.faraddr $0DB5F
.faraddr $00000
UMSG_YUCCA_PILOT_TANKRIDE:
.faraddr MSG_YUCCA_PILOT_TANKRIDE
UMSG_MYHOME_DOG_CHECK:
.faraddr MSG_MYHOME_DOG_CHECK
UMSG_PODUNK_NOISYMOUSE:
.faraddr MSG_PODUNK_NOISYMOUSE
.faraddr $00000
.faraddr $0DCFE
.faraddr $0DD3A
.faraddr $0DD79
.faraddr $0DDE5
.faraddr $0DE48
.faraddr $0DE69
.faraddr $0DE8F
.faraddr $0DEC9
.faraddr $0DF03
.faraddr $0DF25
.faraddr $0DF5A
.faraddr $0E000
.faraddr $0E03B
.faraddr $0E052
.faraddr $0E113
.faraddr $0E184
UMSG_MR_RAILROADCORPSE:
.faraddr MSG_MR_RAILROADCORPSE
.faraddr $0E261
.faraddr $0E27F
.faraddr $0E35D
.faraddr $00000
.faraddr $0E3B0
UMSG_LOOK_NULLITEM:
.faraddr MSG_LOOK_NULLITEM
UMSG_LOOK_BIG_BAG:
.faraddr MSG_LOOK_BIG_BAG
UMSG_LOOK_TELEPHONE_CARD:
.faraddr MSG_LOOK_TELEPHONE_CARD
UMSG_LOOK_BREAD_CRUMBS:
.faraddr MSG_LOOK_BREAD_CRUMBS
UMSG_LOOK_REPEL_RING:
.faraddr MSG_LOOK_REPEL_RING
UMSG_LOOK_UNKITEM5:
.faraddr MSG_LOOK_UNKITEM5
UMSG_LOOK_UNKITEM6:
.faraddr MSG_LOOK_UNKITEM6
UMSG_LOOK_UNKITEM7:
.faraddr MSG_LOOK_UNKITEM7
UMSG_LOOK_UNKITEM8:
.faraddr MSG_LOOK_UNKITEM8
UMSG_LOOK_UNKITEM9:
.faraddr MSG_LOOK_UNKITEM9
UMSG_LOOK_BUTTER_KNIFE:
.faraddr MSG_LOOK_BUTTER_KNIFE
UMSG_LOOK_SURVIVAL_KNIFE:
.faraddr MSG_LOOK_SURVIVAL_KNIFE
UMSG_LOOK_SWORD:
.faraddr MSG_LOOK_SWORD
UMSG_LOOK_KATANA:
.faraddr MSG_LOOK_KATANA
UMSG_LOOK_STUN_GUN:
.faraddr MSG_LOOK_STUN_GUN
UMSG_LOOK_AIR_GUN:
.faraddr MSG_LOOK_AIR_GUN
UMSG_LOOK_PLASTIC_BAT:
.faraddr MSG_LOOK_PLASTIC_BAT
UMSG_LOOK_WOODEN_BAT:
.faraddr MSG_LOOK_WOODEN_BAT
UMSG_LOOK_ALUMINUM_BAT:
.faraddr MSG_LOOK_ALUMINUM_BAT
UMSG_LOOK_HANKS_BAT:
.faraddr MSG_LOOK_HANKS_BAT
UMSG_LOOK_FRYING_PAN:
.faraddr MSG_LOOK_FRYING_PAN
UMSG_LOOK_NONSTICK_PAN:
.faraddr MSG_LOOK_NONSTICK_PAN
UMSG_LOOK_IRON_SKILLET:
.faraddr MSG_LOOK_IRON_SKILLET
UMSG_LOOK_SLINGSHOT:
.faraddr MSG_LOOK_SLINGSHOT
UMSG_LOOK_BOOMERANG:
.faraddr MSG_LOOK_BOOMERANG
UMSG_LOOK_INSECTICIDE:
.faraddr MSG_LOOK_INSECTICIDE
UMSG_LOOK_SUPER_SPRAY:
.faraddr MSG_LOOK_SUPER_SPRAY
UMSG_LOOK_FLEA_BAG:
.faraddr MSG_LOOK_FLEA_BAG
UMSG_LOOK_WORDS_OF_LOVE:
.faraddr MSG_LOOK_WORDS_OF_LOVE
UMSG_LOOK_SWEAR_WORDS:
.faraddr MSG_LOOK_SWEAR_WORDS
UMSG_LOOK_STICKY_MACHINE:
.faraddr MSG_LOOK_STICKY_MACHINE
UMSG_LOOK_FLASHDARK:
.faraddr MSG_LOOK_FLASHDARK
UMSG_LOOK_STONEORIGIN:
.faraddr MSG_LOOK_STONEORIGIN
UMSG_LOOK_POISON_NEEDLE:
.faraddr MSG_LOOK_POISON_NEEDLE
UMSG_LOOK_FLAME_THROWER:
.faraddr MSG_LOOK_FLAME_THROWER
UMSG_LOOK_BOMB:
.faraddr MSG_LOOK_BOMB
UMSG_LOOK_SUPER_BOMB:
.faraddr MSG_LOOK_SUPER_BOMB
UMSG_LOOK_LASER_BEAM:
.faraddr MSG_LOOK_LASER_BEAM
UMSG_LOOK_PLASMA_BEAM:
.faraddr MSG_LOOK_PLASMA_BEAM
UMSG_LOOK_UNKITEM27:
.faraddr MSG_LOOK_UNKITEM27
UMSG_LOOK_ROPE:
.faraddr MSG_LOOK_ROPE
UMSG_LOOK_UNKITEM29:
.faraddr MSG_LOOK_UNKITEM29
UMSG_LOOK_UNKITEM2A:
.faraddr MSG_LOOK_UNKITEM2A
UMSG_LOOK_UNKITEM2B:
.faraddr MSG_LOOK_UNKITEM2B
UMSG_LOOK_UNKITEM2C:
.faraddr MSG_LOOK_UNKITEM2C
UMSG_LOOK_PEACE_COIN:
.faraddr MSG_LOOK_PEACE_COIN
UMSG_LOOK_PROTECTION_COIN:
.faraddr MSG_LOOK_PROTECTION_COIN
UMSG_LOOK_MAGIC_COIN:
.faraddr MSG_LOOK_MAGIC_COIN
UMSG_LOOK_BRASS_RING:
.faraddr MSG_LOOK_BRASS_RING
UMSG_LOOK_SILVER_RING:
.faraddr MSG_LOOK_SILVER_RING
UMSG_LOOK_GOLD_RING:
.faraddr MSG_LOOK_GOLD_RING
UMSG_LOOK_H2O_PENDANT:
.faraddr MSG_LOOK_H2O_PENDANT
UMSG_LOOK_FIRE_PENDANT:
.faraddr MSG_LOOK_FIRE_PENDANT
UMSG_LOOK_EARTH_PENDANT:
.faraddr MSG_LOOK_EARTH_PENDANT
UMSG_LOOK_SEA_PENDANT:
.faraddr MSG_LOOK_SEA_PENDANT
UMSG_LOOK_UNKITEM37:
.faraddr MSG_LOOK_UNKITEM37
UMSG_LOOK_UNKITEM38:
.faraddr MSG_LOOK_UNKITEM38
UMSG_LOOK_UNKITEM39:
.faraddr MSG_LOOK_UNKITEM39
UMSG_LOOK_UNKITEM3A:
.faraddr MSG_LOOK_UNKITEM3A
UMSG_LOOK_UNKITEM3B:
.faraddr MSG_LOOK_UNKITEM3B
UMSG_LOOK_ORANGE_JUICE:
.faraddr MSG_LOOK_ORANGE_JUICE
UMSG_LOOK_FRESH_FRIES:
.faraddr MSG_LOOK_FRESH_FRIES
UMSG_LOOK_MAGIC_HERB:
.faraddr MSG_LOOK_MAGIC_HERB
UMSG_LOOK_HAMBURGER:
.faraddr MSG_LOOK_HAMBURGER
UMSG_LOOK_SPORTS_DRINK:
.faraddr MSG_LOOK_SPORTS_DRINK
UMSG_LOOK_LIFE_UP_CREAM:
.faraddr MSG_LOOK_LIFE_UP_CREAM
UMSG_LOOK_ASTHMA_SPRAY:
.faraddr MSG_LOOK_ASTHMA_SPRAY
UMSG_LOOK_ANTIDOTE:
.faraddr MSG_LOOK_ANTIDOTE
UMSG_LOOK_MOUTHWASH:
.faraddr MSG_LOOK_MOUTHWASH
UMSG_LOOK_STRAWBERRY_TOFU:
.faraddr MSG_LOOK_STRAWBERRY_TOFU
UMSG_LOOK_UNKITEM46:
.faraddr MSG_LOOK_UNKITEM46
UMSG_LOOK_BREAD:
.faraddr MSG_LOOK_BREAD
UMSG_LOOK_NOBLE_SEED:
.faraddr MSG_LOOK_NOBLE_SEED
UMSG_LOOK_PSI_STONE:
.faraddr MSG_LOOK_PSI_STONE
UMSG_LOOK_UNKITEM4A:
.faraddr MSG_LOOK_UNKITEM4A
UMSG_LOOK_MAGIC_RIBBON:
.faraddr MSG_LOOK_MAGIC_RIBBON
UMSG_LOOK_MAGIC_CANDY:
.faraddr MSG_LOOK_MAGIC_CANDY
UMSG_LOOK_UNKITEM4D:
.faraddr MSG_LOOK_UNKITEM4D
UMSG_LOOK_QUICK_CAPSULE:
.faraddr MSG_LOOK_QUICK_CAPSULE
UMSG_LOOK_WISDOM_CAPSULE:
.faraddr MSG_LOOK_WISDOM_CAPSULE
UMSG_LOOK_PHYSICAL_CAPSULE:
.faraddr MSG_LOOK_PHYSICAL_CAPSULE
UMSG_LOOK_FORCE_CAPSULE:
.faraddr MSG_LOOK_FORCE_CAPSULE
UMSG_LOOK_FIGHT_CAPSULE:
.faraddr MSG_LOOK_FIGHT_CAPSULE
UMSG_LOOK_UNKITEM53:
.faraddr MSG_LOOK_UNKITEM53
UMSG_LOOK_UNKITEM54:
.faraddr MSG_LOOK_UNKITEM54
UMSG_LOOK_BASEMENT_KEY:
.faraddr MSG_LOOK_BASEMENT_KEY
UMSG_LOOK_ZOO_KEY:
.faraddr MSG_LOOK_ZOO_KEY
UMSG_LOOK_GHOST_HOUSE_KEY:
.faraddr MSG_LOOK_GHOST_HOUSE_KEY
UMSG_LOOK_GGFS_DIARY:
.faraddr MSG_LOOK_GGFS_DIARY
UMSG_LOOK_PASS:
.faraddr MSG_LOOK_PASS
UMSG_LOOK_TICKET:
.faraddr MSG_LOOK_TICKET
UMSG_LOOK_UNKITEM5B:
.faraddr MSG_LOOK_UNKITEM5B
UMSG_LOOK_UNKITEM5C:
.faraddr MSG_LOOK_UNKITEM5C
UMSG_LOOK_UNKITEM5D:
.faraddr MSG_LOOK_UNKITEM5D
UMSG_LOOK_UNKITEM5E:
.faraddr MSG_LOOK_UNKITEM5E
UMSG_LOOK_CANARY_CHICK:
.faraddr MSG_LOOK_CANARY_CHICK
UMSG_LOOK_UNKITEM60:
.faraddr MSG_LOOK_UNKITEM60
UMSG_LOOK_BOTTLE_ROCKET:
.faraddr MSG_LOOK_BOTTLE_ROCKET
UMSG_LOOK_HAT:
.faraddr MSG_LOOK_HAT
UMSG_LOOK_DENTURES:
.faraddr MSG_LOOK_DENTURES
UMSG_LOOK_TICKET_STUB:
.faraddr MSG_LOOK_TICKET_STUB
UMSG_LOOK_IC_CHIP:
.faraddr MSG_LOOK_IC_CHIP
UMSG_LOOK_OCARINA:
.faraddr MSG_LOOK_OCARINA
UMSG_LOOK_UNKITEM67:
.faraddr MSG_LOOK_UNKITEM67
UMSG_LOOK_FRANKLIN_BADGE:
.faraddr MSG_LOOK_FRANKLIN_BADGE
UMSG_LOOK_FRIENDSHIP_RING:
.faraddr MSG_LOOK_FRIENDSHIP_RING
UMSG_LOOK_UNKITEM6A:
.faraddr MSG_LOOK_UNKITEM6A
UMSG_LOOK_ONYX_HOOK:
.faraddr MSG_LOOK_ONYX_HOOK
UMSG_LOOK_LAST_WEAPON:
.faraddr MSG_LOOK_LAST_WEAPON
UMSG_LOOK_RULER:
.faraddr MSG_LOOK_RULER
UMSG_LOOK_CASH_CARD:
.faraddr MSG_LOOK_CASH_CARD
UMSG_LOOK_RED_WEED:
.faraddr MSG_LOOK_RED_WEED
UMSG_LOOK_BULLHORN:
.faraddr MSG_LOOK_BULLHORN
UMSG_LOOK_MAP:
.faraddr MSG_LOOK_MAP
UMSG_LOOK_UNKITEM72:
.faraddr MSG_LOOK_UNKITEM72
UMSG_LOOK_UNKITEM73:
.faraddr MSG_LOOK_UNKITEM73
UMSG_LOOK_UNKITEM74:
.faraddr MSG_LOOK_UNKITEM74
UMSG_LOOK_UNKITEM75:
.faraddr MSG_LOOK_UNKITEM75
UMSG_LOOK_UNKITEM76:
.faraddr MSG_LOOK_UNKITEM76
UMSG_LOOK_UNKITEM77:
.faraddr MSG_LOOK_UNKITEM77
UMSG_LOOK_UNKITEM78:
.faraddr MSG_LOOK_UNKITEM78
UMSG_LOOK_UNKITEM79:
.faraddr MSG_LOOK_UNKITEM79
UMSG_LOOK_UNKITEM7A:
.faraddr MSG_LOOK_UNKITEM7A
UMSG_LOOK_UNKITEM7B:
.faraddr MSG_LOOK_UNKITEM7B
UMSG_LOOK_UNKITEM7C:
.faraddr MSG_LOOK_UNKITEM7C
UMSG_LOOK_UNKITEM7E:
.faraddr MSG_LOOK_UNKITEM7E
UMSG_LOOK_UNKITEM7F:
.faraddr MSG_LOOK_UNKITEM7F
UMSG_LOOK_DEBUG:
.faraddr MSG_LOOK_DEBUG
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000

.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
;relevant routine: DisplayText_battle
;Enemies get indexed by this calculation:
; ((offset_bank16-$8000) / $20) + $514
UMSG_CHECK_UNKENEMY0:
.faraddr MSG_CHECK_UNKENEMY0
UMSG_CHECK_BIGWOODOH:
.faraddr MSG_CHECK_BIGWOODOH
UMSG_CHECK_DRAGON:
.faraddr MSG_CHECK_DRAGON
UMSG_CHECK_R7038:
.faraddr MSG_CHECK_R7038
UMSG_CHECK_ELEPHANT:
.faraddr MSG_CHECK_ELEPHANT
UMSG_CHECK_BEAR:
.faraddr MSG_CHECK_BEAR
UMSG_CHECK_BIG_FOOT:
.faraddr MSG_CHECK_BIG_FOOT
UMSG_CHECK_MAD_TRUCK:
.faraddr MSG_CHECK_MAD_TRUCK
UMSG_CHECK_OLD_ROBOT:
.faraddr MSG_CHECK_OLD_ROBOT
UMSG_CHECK_MEGABORG:
.faraddr MSG_CHECK_MEGABORG
UMSG_CHECK_GARGOYLE:
.faraddr MSG_CHECK_GARGOYLE
UMSG_CHECK_GABILAN:
.faraddr MSG_CHECK_GABILAN
UMSG_CHECK_GORILLA:
.faraddr MSG_CHECK_GORILLA
UMSG_CHECK_BISON:
.faraddr MSG_CHECK_BISON
UMSG_CHECK_TIGER:
.faraddr MSG_CHECK_TIGER
UMSG_CHECK_MAD_CAR:
.faraddr MSG_CHECK_MAD_CAR
UMSG_CHECK_RAEB_YDDET:
.faraddr MSG_CHECK_RAEB_YDDET
UMSG_CHECK_MAGIC_SNAIL:
.faraddr MSG_CHECK_MAGIC_SNAIL
UMSG_CHECK_TITANEES:
.faraddr MSG_CHECK_TITANEES
UMSG_CHECK_GIEGUE:
.faraddr MSG_CHECK_GIEGUE
UMSG_CHECK_EAGLE:
.faraddr MSG_CHECK_EAGLE
UMSG_CHECK_WOLF:
.faraddr MSG_CHECK_WOLF
UMSG_CHECK_SEAGULL:
.faraddr MSG_CHECK_SEAGULL
UMSG_CHECK_ALLIGATOR:
.faraddr MSG_CHECK_ALLIGATOR
UMSG_CHECK_ENERGYROBOT:
.faraddr MSG_CHECK_ENERGYROBOT
UMSG_CHECK_THE_FISH:
.faraddr MSG_CHECK_THE_FISH
UMSG_CHECK_FUGITIVE:
.faraddr MSG_CHECK_FUGITIVE
UMSG_CHECK_BBS_BOSS:
.faraddr MSG_CHECK_BBS_BOSS
UMSG_CHECK_BARBOT:
.faraddr MSG_CHECK_BARBOT
UMSG_CHECK_NANCY:
.faraddr MSG_CHECK_NANCY
UMSG_CHECK_STARMAN:
.faraddr MSG_CHECK_STARMAN
UMSG_CHECK_ULLRICH:
.faraddr MSG_CHECK_ULLRICH
UMSG_CHECK_CEREBRUM:
.faraddr MSG_CHECK_CEREBRUM
UMSG_CHECK_MOOK:
.faraddr MSG_CHECK_MOOK
UMSG_CHECK_ARMOR:
.faraddr MSG_CHECK_ARMOR
UMSG_CHECK_WOODOH:
.faraddr MSG_CHECK_WOODOH
UMSG_CHECK_WALLY:
.faraddr MSG_CHECK_WALLY
UMSG_CHECK_THE_HIPPIE:
.faraddr MSG_CHECK_THE_HIPPIE
UMSG_CHECK_BAG_LADY:
.faraddr MSG_CHECK_BAG_LADY
UMSG_CHECK_BB_GANG:
.faraddr MSG_CHECK_BB_GANG
UMSG_CHECK_DR_DISTORTO:
.faraddr MSG_CHECK_DR_DISTORTO
UMSG_CHECK_UNKENEMY1:
.faraddr MSG_CHECK_UNKENEMY1
UMSG_CHECK_GANG_ZOMBIE:
.faraddr MSG_CHECK_GANG_ZOMBIE
UMSG_CHECK_PSEUDOZOMBI:
.faraddr MSG_CHECK_PSEUDOZOMBI
UMSG_CHECK_CROW:
.faraddr MSG_CHECK_CROW
UMSG_CHECK_SNAKE:
.faraddr MSG_CHECK_SNAKE
UMSG_CHECK_HYENA:
.faraddr MSG_CHECK_HYENA
UMSG_CHECK_COUGAR:
.faraddr MSG_CHECK_COUGAR
UMSG_CHECK_CENTIPEDE:
.faraddr MSG_CHECK_CENTIPEDE
UMSG_CHECK_DUST_BALL:
.faraddr MSG_CHECK_DUST_BALL
UMSG_CHECK_FLY:
.faraddr MSG_CHECK_FLY
UMSG_CHECK_SPIDER:
.faraddr MSG_CHECK_SPIDER
UMSG_CHECK_SCORPION:
.faraddr MSG_CHECK_SCORPION
UMSG_CHECK_ROPE:
.faraddr MSG_CHECK_ROPE
UMSG_CHECK_FIRE_BALL:
.faraddr MSG_CHECK_FIRE_BALL
UMSG_CHECK_WATCHER:
.faraddr MSG_CHECK_WATCHER
UMSG_CHECK_GROUCHO:
.faraddr MSG_CHECK_GROUCHO
UMSG_CHECK_GHOST:
.faraddr MSG_CHECK_GHOST
UMSG_CHECK_LIL_SAUCER:
.faraddr MSG_CHECK_LIL_SAUCER
UMSG_CHECK_MR_BAT:
.faraddr MSG_CHECK_MR_BAT
UMSG_CHECK_STARMAN_JR:
.faraddr MSG_CHECK_STARMAN_JR
UMSG_CHECK_SKUNK:
.faraddr MSG_CHECK_SKUNK
UMSG_CHECK_SHROUDLEY:
.faraddr MSG_CHECK_SHROUDLEY
UMSG_CHECK_RAT:
.faraddr MSG_CHECK_RAT
UMSG_CHECK_BOMBER:
.faraddr MSG_CHECK_BOMBER
UMSG_CHECK_UNKENEMY2:
.faraddr MSG_CHECK_UNKENEMY2
UMSG_CHECK_DOLL:
.faraddr MSG_CHECK_DOLL
UMSG_CHECK_LAMP:
.faraddr MSG_CHECK_LAMP
UMSG_CHECK_UNKENEMY3:
.faraddr MSG_CHECK_UNKENEMY3
UMSG_CHECK_UNKENEMY4:
.faraddr MSG_CHECK_UNKENEMY4
UMSG_CHECK_BIONICCENTI:
.faraddr MSG_CHECK_BIONICCENTI
UMSG_CHECK_BIONICSCORP:
.faraddr MSG_CHECK_BIONICSCORP
UMSG_CHECK_UNKENEMY5:
.faraddr MSG_CHECK_UNKENEMY5
UMSG_CHECK_UNKENEMY6:
.faraddr MSG_CHECK_UNKENEMY6
UMSG_CHECK_RED_SNAKE:
.faraddr MSG_CHECK_RED_SNAKE
UMSG_CHECK_LONE_WOLF:
.faraddr MSG_CHECK_LONE_WOLF
UMSG_CHECK_POLAR_BEAR:
.faraddr MSG_CHECK_POLAR_BEAR
UMSG_CHECK_UNKENEMY7:
.faraddr MSG_CHECK_UNKENEMY7
UMSG_CHECK_UNKENEMY8:
.faraddr MSG_CHECK_UNKENEMY8
UMSG_CHECK_UNKENEMY9:
.faraddr MSG_CHECK_UNKENEMY9
UMSG_CHECK_UNKENEMYA:
.faraddr MSG_CHECK_UNKENEMYA
UMSG_CHECK_RATTLESNAKE:
.faraddr MSG_CHECK_RATTLESNAKE
UMSG_CHECK_TARANTULA:
.faraddr MSG_CHECK_TARANTULA
UMSG_CHECK_CROCODILE:
.faraddr MSG_CHECK_CROCODILE
UMSG_CHECK_UNKENEMYB:
.faraddr MSG_CHECK_UNKENEMYB
UMSG_CHECK_BUFFALO:
.faraddr MSG_CHECK_BUFFALO
UMSG_CHECK_UNKENEMYC:
.faraddr MSG_CHECK_UNKENEMYC
UMSG_CHECK_BIONIC_BAT:
.faraddr MSG_CHECK_BIONIC_BAT
UMSG_CHECK_STRAY_DOG:
.faraddr MSG_CHECK_STRAY_DOG
UMSG_CHECK_PSYCHO_CAR:
.faraddr MSG_CHECK_PSYCHO_CAR
UMSG_CHECK_PSYCHOTRUCK:
.faraddr MSG_CHECK_PSYCHOTRUCK
UMSG_CHECK_MANIACTRUCK:
.faraddr MSG_CHECK_MANIACTRUCK
UMSG_CHECK_ALARM_GHOST:
.faraddr MSG_CHECK_ALARM_GHOST
UMSG_CHECK_UNKENEMYD:
.faraddr MSG_CHECK_UNKENEMYD
UMSG_CHECK_FOUREYES:
.faraddr MSG_CHECK_FOUREYES
UMSG_CHECK_DADSEYES:
.faraddr MSG_CHECK_DADSEYES
UMSG_CHECK_MOMSEYES:
.faraddr MSG_CHECK_MOMSEYES
UMSG_CHECK_UNKENEMYE:
.faraddr MSG_CHECK_UNKENEMYE
UMSG_CHECK_UNKENEMYF:
.faraddr MSG_CHECK_UNKENEMYF
UMSG_CHECK_SKY_YDDET:
.faraddr MSG_CHECK_SKY_YDDET
UMSG_CHECK_UNKENEMY10:
.faraddr MSG_CHECK_UNKENEMY10
UMSG_CHECK_GIGA_BORG:
.faraddr MSG_CHECK_GIGA_BORG
UMSG_CHECK_OMEGA_BORG:
.faraddr MSG_CHECK_OMEGA_BORG
UMSG_CHECK_SCRAPPER:
.faraddr MSG_CHECK_SCRAPPER
UMSG_CHECK_ULTRABARBOT:
.faraddr MSG_CHECK_ULTRABARBOT
UMSG_CHECK_OMEGASAUCER:
.faraddr MSG_CHECK_OMEGASAUCER
UMSG_CHECK_KELLY:
.faraddr MSG_CHECK_KELLY
UMSG_CHECK_STAR_MINER:
.faraddr MSG_CHECK_STAR_MINER
UMSG_CHECK_SUPERENERGY:
.faraddr MSG_CHECK_SUPERENERGY
UMSG_CHECK_JUANA:
.faraddr MSG_CHECK_JUANA
UMSG_CHECK_BLUESTARMAN:
.faraddr MSG_CHECK_BLUESTARMAN
UMSG_CHECK_ROCKOYLE:
.faraddr MSG_CHECK_ROCKOYLE
UMSG_CHECK_TITANIAN:
.faraddr MSG_CHECK_TITANIAN
UMSG_CHECK_OH_MOOK:
.faraddr MSG_CHECK_OH_MOOK
UMSG_CHECK_UNKENEMY11:
.faraddr MSG_CHECK_UNKENEMY11
UMSG_CHECK_ZOMBIE:
.faraddr MSG_CHECK_ZOMBIE
UMSG_CHECK_NASTYZOMBIE:
.faraddr MSG_CHECK_NASTYZOMBIE
UMSG_CHECK_SILVER_WOLF:
.faraddr MSG_CHECK_SILVER_WOLF
UMSG_CHECK_R7037:
.faraddr MSG_CHECK_R7037
UMSG_CHECK_GRIZZLYBEAR:
.faraddr MSG_CHECK_GRIZZLYBEAR
UMSG_CHECK_R7038XX:
.faraddr MSG_CHECK_R7038XX
UMSG_CHECK_LASTSTARMAN:
.faraddr MSG_CHECK_LASTSTARMAN
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
UMSG_B_UNK2:
.faraddr MSG_B_UNK2
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000

UMSG_B_NULL:
.faraddr MSG_B_NULL
UMSG_B_NULL_2:
.faraddr MSG_B_NULL_2
UMSG_B_UNK:
.faraddr MSG_B_UNK
UMSG_B_APPROACH:
.faraddr MSG_B_APPROACH
UMSG_B_ATTACK:
.faraddr MSG_B_ATTACK
UMSG_B_TANKGUN:
.faraddr MSG_B_TANKGUN
UMSG_B_DODGED:
.faraddr MSG_B_DODGED
UMSG_B_CONTINUOUS_ATTACK:
.faraddr MSG_B_CONTINUOUS_ATTACK
UMSG_B_BITE:
.faraddr MSG_B_BITE
UMSG_B_SCRATCH:
.faraddr MSG_B_SCRATCH
UMSG_B_CHARGE:
.faraddr MSG_B_CHARGE
UMSG_B_SMAAAAASH:
.faraddr MSG_B_SMAAAAASH
UMSG_B_DAMAGED:
.faraddr MSG_B_DAMAGED
UMSG_B_YOU_WIN:
.faraddr MSG_B_YOU_WIN
UMSG_B_YOU_LOST:
.faraddr MSG_B_YOU_LOST
UMSG_B_DEFEATED:
.faraddr MSG_B_DEFEATED
UMSG_B_HURT_AND_BEATEN:
.faraddr MSG_B_HURT_AND_BEATEN
UMSG_B_ALREADY_GONE:
.faraddr MSG_B_ALREADY_GONE
UMSG_B_NO_EFFECT:
.faraddr MSG_B_NO_EFFECT
UMSG_B_OUT_OF_CONTROL:
.faraddr MSG_B_OUT_OF_CONTROL
UMSG_B_EXHAUSTED:
.faraddr MSG_B_EXHAUSTED
UMSG_B_FINAL_ATTACK:
.faraddr MSG_B_FINAL_ATTACK
UMSG_B_GIEGUE_ATTACK:
.faraddr MSG_B_GIEGUE_ATTACK
UMSG_B_BARRIER:
.faraddr MSG_B_BARRIER
UMSG_B_BULLHORN_1:
.faraddr MSG_B_BULLHORN_1
UMSG_B_GOT_STONED:
.faraddr MSG_B_GOT_STONED
UMSG_B_SPIT:
.faraddr MSG_B_SPIT
UMSG_B_GOT_BLINDED:
.faraddr MSG_B_GOT_BLINDED
UMSG_B_BIND:
.faraddr MSG_B_BIND
UMSG_B_STRANGE_CRY:
.faraddr MSG_B_STRANGE_CRY
UMSG_B_EXPLODED:
.faraddr MSG_B_EXPLODED
UMSG_B_FLAMEBURST:
.faraddr MSG_B_FLAMEBURST
UMSG_B_OFFENSE_INCREASE:
.faraddr MSG_B_OFFENSE_INCREASE
UMSG_B_OFFENSE_DECREASE:
.faraddr MSG_B_OFFENSE_DECREASE
UMSG_B_DEFENSE_INCREASE:
.faraddr MSG_B_DEFENSE_INCREASE
UMSG_B_SPEED_INCREASE:
.faraddr MSG_B_SPEED_INCREASE
UMSG_B_CHECK_OFEENSE:
.faraddr MSG_B_CHECK_OFEENSE
UMSG_B_CHECK_DEFENSE:
.faraddr MSG_B_CHECK_DEFENSE
UMSG_B_FIGHT_DECREASE:
.faraddr MSG_B_FIGHT_DECREASE
UMSG_B_DEFENSE_DECREASE:
.faraddr MSG_B_DEFENSE_DECREASE
UMSG_B_SMILE:
.faraddr MSG_B_SMILE
UMSG_B_FIGHT_INCREASE:
.faraddr MSG_B_FIGHT_INCREASE
UMSG_B_RAGE:
.faraddr MSG_B_RAGE
UMSG_B_SPEED_DECREASE:
.faraddr MSG_B_SPEED_DECREASE
UMSG_B_CONFUSE:
.faraddr MSG_B_CONFUSE
UMSG_B_CALL:
.faraddr MSG_B_CALL
UMSG_B_SOW:
.faraddr MSG_B_SOW
UMSG_B_GROUCHOFUNNY2:
.faraddr MSG_B_GROUCHOFUNNY2
UMSG_B_LAUGH:
.faraddr MSG_B_LAUGH
UMSG_B_BROKEN_TANK:
.faraddr MSG_B_BROKEN_TANK
UMSG_B_THREATEN:
.faraddr MSG_B_THREATEN
UMSG_B_DIRTYWORDS:
.faraddr MSG_B_DIRTYWORDS
UMSG_B_GRIN:
.faraddr MSG_B_GRIN
UMSG_B_BULLHORN_SUCCEED:
.faraddr MSG_B_BULLHORN_SUCCEED
UMSG_B_BULLHORN_FAIL:
.faraddr MSG_B_BULLHORN_FAIL
UMSG_B_BULLHORN_SUCCEED2:
.faraddr MSG_B_BULLHORN_SUCCEED2
UMSG_B_CRITICAL:
.faraddr MSG_B_CRITICAL
UMSG_B_LOST_SENSES:
.faraddr MSG_B_LOST_SENSES
UMSG_B_CONFUSED:
.faraddr MSG_B_CONFUSED
UMSG_B_SLEEP:
.faraddr MSG_B_SLEEP
UMSG_B_ASLEEP:
.faraddr MSG_B_ASLEEP
UMSG_B_PP_RECOVER:
.faraddr MSG_B_PP_RECOVER
UMSG_B_HP_RECOVER:
.faraddr MSG_B_HP_RECOVER
UMSG_B_FLOW_ENERGY:
.faraddr MSG_B_FLOW_ENERGY
UMSG_B_CALL_FAIL:
.faraddr MSG_B_CALL_FAIL
UMSG_B_CALL_FAIL2:
.faraddr MSG_B_CALL_FAIL2
UMSG_B_CALL_SUCCEED:
.faraddr MSG_B_CALL_SUCCEED
UMSG_B_RUN_AWAY:
.faraddr MSG_B_RUN_AWAY
UMSG_B_DIDNT_WORK:
.faraddr MSG_B_DIDNT_WORK
UMSG_B_TRIP:
.faraddr MSG_B_TRIP
UMSG_B_CANT_MOVE:
.faraddr MSG_B_CANT_MOVE
UMSG_B_SELF_STONE:
.faraddr MSG_B_SELF_STONE
UMSG_B_PP_STEAL:
.faraddr MSG_B_PP_STEAL
UMSG_B_PARALYZED:
.faraddr MSG_B_PARALYZED
UMSG_B_PUFF:
.faraddr MSG_B_PUFF
UMSG_B_POISONED:
.faraddr MSG_B_POISONED
UMSG_B_DEHYDRATED:
.faraddr MSG_B_DEHYDRATED
UMSG_B_PSI_BLOCK:
.faraddr MSG_B_PSI_BLOCK
UMSG_B_BOUND:
.faraddr MSG_B_BOUND
UMSG_B_SHIELD:
.faraddr MSG_B_SHIELD
UMSG_B_MISS:
.faraddr MSG_B_MISS
UMSG_B_BUT_PSI_BLOCK:
.faraddr MSG_B_BUT_PSI_BLOCK
UMSG_B_FRANKLIN_BOUNCE:
.faraddr MSG_B_FRANKLIN_BOUNCE
UMSG_B_BOUNCE:
.faraddr MSG_B_BOUNCE
UMSG_B_NOT_ENOUGH_PP:
.faraddr MSG_B_NOT_ENOUGH_PP
UMSG_B_NO_EFFECT2:
.faraddr MSG_B_NO_EFFECT2
UMSG_B_ASTHMA_WHEEZE:
.faraddr MSG_B_ASTHMA_WHEEZE
UMSG_B_MEDITATE:
.faraddr MSG_B_MEDITATE
UMSG_B_GROUCHOFUNNY:
.faraddr MSG_B_GROUCHOFUNNY
UMSG_B_READY:
.faraddr MSG_B_READY
UMSG_B_GIEGUE_SING:
.faraddr MSG_B_GIEGUE_SING
UMSG_B_GUARD:
.faraddr MSG_B_GUARD
UMSG_B_APPROACH_SLOWLY:
.faraddr MSG_B_APPROACH_SLOWLY
UMSG_B_POISON_RECOVER:
.faraddr MSG_B_POISON_RECOVER
UMSG_B_PUZZLED_RECOVER:
.faraddr MSG_B_PUZZLED_RECOVER
UMSG_B_ITCHY:
.faraddr MSG_B_ITCHY
UMSG_B_PARALYSIS_RECOVER:
.faraddr MSG_B_PARALYSIS_RECOVER
UMSG_B_ASLEEP_RECOVER:
.faraddr MSG_B_ASLEEP_RECOVER
UMSG_B_REVIVE:
.faraddr MSG_B_REVIVE
UMSG_B_USED:
.faraddr MSG_B_USED
UMSG_B_TRIED:
.faraddr MSG_B_TRIED
UMSG_B_CANT_USE:
.faraddr MSG_B_CANT_USE
UMSG_B_CIRCUMSTANCES:
.faraddr MSG_B_CIRCUMSTANCES
UMSG_B_DO_STRANGE:
.faraddr MSG_B_DO_STRANGE
UMSG_B_DREAMING:
.faraddr MSG_B_DREAMING
UMSG_B_BREAK_SHIELD:
.faraddr MSG_B_BREAK_SHIELD
UMSG_B_CHECK:
.faraddr MSG_B_CHECK
UMSG_B_CHECK_STRONGFIRE:
.faraddr MSG_B_CHECK_STRONGFIRE
UMSG_B_CHECK_STRONGFREEZE:
.faraddr MSG_B_CHECK_STRONGFREEZE
UMSG_B_CHECK_STRONGTHUNDER:
.faraddr MSG_B_CHECK_STRONGTHUNDER
UMSG_B_CHECK_STRONGBEAM:
.faraddr MSG_B_CHECK_STRONGBEAM
UMSG_B_CHECK_WEAKSPRAYS:
.faraddr MSG_B_CHECK_WEAKSPRAYS
UMSG_B_ASTHMA_RECOVER:
.faraddr MSG_B_ASTHMA_RECOVER
UMSG_B_NOLONGER_STONED:
.faraddr MSG_B_NOLONGER_STONED
UMSG_B_WORDS_O_LOVE:
.faraddr MSG_B_WORDS_O_LOVE
UMSG_B_SWEAR_WORDS:
.faraddr MSG_B_SWEAR_WORDS
UMSG_B_ASTHMA:
.faraddr MSG_B_ASTHMA
UMSG_B_BREAK_ITEM:
.faraddr MSG_B_BREAK_ITEM
UMSG_B_WICKED_SEED:
.faraddr MSG_B_WICKED_SEED
UMSG_B_GAS:
.faraddr MSG_B_GAS
UMSG_B_STONED:
.faraddr MSG_B_STONED
UMSG_B_FULL_RECOVER:
.faraddr MSG_B_FULL_RECOVER
UMSG_B_BEATEN_1:
.faraddr MSG_B_BEATEN_1
UMSG_B_BEATEN_2:
.faraddr MSG_B_BEATEN_2
UMSG_B_BEATEN_3:
.faraddr MSG_B_BEATEN_3
UMSG_B_BEATEN_4:
.faraddr MSG_B_BEATEN_4
UMSG_B_BEATEN_5:
.faraddr MSG_B_BEATEN_5
UMSG_B_BEATEN_6:
.faraddr MSG_B_BEATEN_6
UMSG_B_BEATEN_7:
.faraddr MSG_B_BEATEN_7
UMSG_B_STEAL:
.faraddr MSG_B_STEAL
UMSG_B_STATUP:
.faraddr MSG_B_STATUP
UMSG_B_STATUP_NEW_PSI:
.faraddr MSG_B_STATUP_NEW_PSI
UMSG_B_STATUP_HP:
.faraddr MSG_B_STATUP_HP
UMSG_B_STATUP_PP:
.faraddr MSG_B_STATUP_PP
UMSG_B_STATUP_FIGHT:
.faraddr MSG_B_STATUP_FIGHT
UMSG_B_STATUP_SPEED:
.faraddr MSG_B_STATUP_SPEED
UMSG_B_STATUP_WISDOM:
.faraddr MSG_B_STATUP_WISDOM
UMSG_B_STATUP_STRENGTH:
.faraddr MSG_B_STATUP_STRENGTH
UMSG_B_STATUP_FORCE:
.faraddr MSG_B_STATUP_FORCE
UMSG_B_ESCAPE_ROPE:
.faraddr MSG_B_ESCAPE_ROPE
UMSG_B_STATUP_GET_ITEM:
.faraddr MSG_B_STATUP_GET_ITEM
UMSG_B_CONFUSE_RECOVER:
.faraddr MSG_B_CONFUSE_RECOVER
UMSG_B_AWAKE:
.faraddr MSG_B_AWAKE
UMSG_B_ZAP:
.faraddr MSG_B_ZAP
UMSG_B_BUT_NO_EFFECT:
.faraddr MSG_B_BUT_NO_EFFECT
UMSG_B_BIG_BAG_EMPTY:
.faraddr MSG_B_BIG_BAG_EMPTY
UMSG_B_INDETERMINATE_BATTLE_END:
.faraddr MSG_B_INDETERMINATE_BATTLE_END
UMSG_GIEGUE_CHECK_REAL:
.faraddr MSG_GIEGUE_CHECK_REAL
UMSG_B_NULL_3:
.faraddr MSG_B_NULL_3
UMSG_B_NULL_4:
.faraddr MSG_B_NULL_4
UMSG_B_GIEGUE_SPEECH:
.faraddr MSG_B_GIEGUE_SPEECH
UMSG_B_GIEGUE_SPEECH2:
.faraddr MSG_B_GIEGUE_SPEECH2
UMSG_B_GIEGUE_SPEECH3:
.faraddr MSG_B_GIEGUE_SPEECH3
UMSG_B_GIEGUE_SPEECH4:
.faraddr MSG_B_GIEGUE_SPEECH4
UMSG_B_GIEGUE_SPEECH5:
.faraddr MSG_B_GIEGUE_SPEECH5
UMSG_B_GIEGUE_SPEECH6:
.faraddr MSG_B_GIEGUE_SPEECH6
UMSG_B_GIEGUE_SPEECH7:
.faraddr MSG_B_GIEGUE_SPEECH7
UMSG_B_GIEGUE_SPEECH8:
.faraddr MSG_B_GIEGUE_SPEECH8
UMSG_B_GIEGUE_SPEECH9:
.faraddr MSG_B_GIEGUE_SPEECH9
UMSG_B_GIEGUE_SPEECH10:
.faraddr MSG_B_GIEGUE_SPEECH10
UMSG_B_GIEGUE_SPEECH11:
.faraddr MSG_B_GIEGUE_SPEECH11
UMSG_B_GIEGUE_SPEECH12:
.faraddr MSG_B_GIEGUE_SPEECH12
UMSG_B_GIEGUE_SPEECH13:
.faraddr MSG_B_GIEGUE_SPEECH13
UMSG_B_GIEGUE_SPEECH14:
.faraddr MSG_B_GIEGUE_SPEECH14
UMSG_B_GIEGUE_SPEECH15:
.faraddr MSG_B_GIEGUE_SPEECH15
UMSG_B_GIEGUE_SPEECH16:
.faraddr MSG_B_GIEGUE_SPEECH16
UMSG_B_GIEGUE_SPEECH17:
.faraddr MSG_B_GIEGUE_SPEECH17
UMSG_B_GIEGUE_SPEECH18:
.faraddr MSG_B_GIEGUE_SPEECH18
UMSG_B_GIEGUE_SPEECH19:
.faraddr MSG_B_GIEGUE_SPEECH19
UMSG_B_GIEGUE_SPEECH20:
.faraddr MSG_B_GIEGUE_SPEECH20
UMSG_B_GIEGUE_SPEECH21:
.faraddr MSG_B_GIEGUE_SPEECH21
UMSG_B_GIEGUE_SPEECH22:
.faraddr MSG_B_GIEGUE_SPEECH22
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $0E3B1
.faraddr $0E3B2
.faraddr $0E3CD
.faraddr $0E3E6
.faraddr $0E404
.faraddr $0E427
.faraddr $0E44B
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $0E48B
.faraddr $0E49B
.faraddr $0E4AD
.faraddr $0E4C4
.faraddr $0E4DB
.faraddr $0E4E9
.faraddr $0E4F7
.faraddr $0E509
.faraddr $0E51A
.faraddr $0E52C
.faraddr $0E540
.faraddr $0E551
.faraddr $0E58D
.faraddr $0E5B3
.faraddr $0E5E9
.faraddr $0E649
.faraddr $0E670
.faraddr $0E6BA
.faraddr $0E6E7
.faraddr $0E729
.faraddr $0E766
.faraddr $0E796
.faraddr $0E7B2
.faraddr $0E7D8
.faraddr $0E80A
.faraddr $0E81C
.faraddr $0E84B
.faraddr $0E86E
.faraddr $0E90F
.faraddr $0E927
.faraddr $0E94A
.faraddr $0E95D
.faraddr $0E97E
.faraddr $0E996
.faraddr $0E9BB
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
UMSG_ANTIPIRACY:
.faraddr MSG_ANTIPIRACY
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $0EB1E
UMSG_CREDITS_1:
.faraddr MSG_CREDITS_1
UMSG_CREDITS_2:
.faraddr MSG_CREDITS_2
UMSG_CREDITS_3:
.faraddr MSG_CREDITS_3
UMSG_CREDITS_4:
.faraddr MSG_CREDITS_4
UMSG_CREDITS_5:
.faraddr MSG_CREDITS_5
UMSG_CREDITS_6:
.faraddr MSG_CREDITS_6
UMSG_CREDITS_7:
.faraddr MSG_CREDITS_7
UMSG_CREDITS_8:
.faraddr MSG_CREDITS_8
UMSG_CREDITS_9:
.faraddr MSG_CREDITS_9
UMSG_CREDITS_PLAYERNAME:
.faraddr MSG_CREDITS_PLAYERNAME
UMSG_CREDITS_SHIGESATO_ITOI:
.faraddr MSG_CREDITS_SHIGESATO_ITOI
UMSG_CREDITS_MIYUKI_KURE:
.faraddr MSG_CREDITS_MIYUKI_KURE
UMSG_CREDITS_AKIO_OHMORI:
.faraddr MSG_CREDITS_AKIO_OHMORI
UMSG_CREDITS_RITSUO_KAMIMURA:
.faraddr MSG_CREDITS_RITSUO_KAMIMURA
UMSG_CREDITS_KEIICHI_SUZUKI:
.faraddr MSG_CREDITS_KEIICHI_SUZUKI
UMSG_CREDITS_HIROKAZU_TANAKA:
.faraddr MSG_CREDITS_HIROKAZU_TANAKA
UMSG_CREDITS_SHINBO_MINAMI:
.faraddr MSG_CREDITS_SHINBO_MINAMI
UMSG_CREDITS_TATSUYA_ISHII:
.faraddr MSG_CREDITS_TATSUYA_ISHII
UMSG_CREDITS_TOTTORI:
.faraddr MSG_CREDITS_TOTTORI
UMSG_CREDITS_KAZUYA_NAKATANI:
.faraddr MSG_CREDITS_KAZUYA_NAKATANI
UMSG_CREDITS_TAKAYUKI_ONODERA:
.faraddr MSG_CREDITS_TAKAYUKI_ONODERA
UMSG_CREDITS_MOTOO_YASUMA:
.faraddr MSG_CREDITS_MOTOO_YASUMA
UMSG_CREDITS_MASAYUKI_KAMEYAMA:
.faraddr MSG_CREDITS_MASAYUKI_KAMEYAMA
UMSG_CREDITS_HIDEO_KON:
.faraddr MSG_CREDITS_HIDEO_KON
UMSG_CREDITS_KATSUTOMO_MAEIWA:
.faraddr MSG_CREDITS_KATSUTOMO_MAEIWA
UMSG_CREDITS_KUNIKO_SAKURAI:
.faraddr MSG_CREDITS_KUNIKO_SAKURAI
UMSG_CREDITS_MASAHIRO_TATEMOTO:
.faraddr MSG_CREDITS_MASAHIRO_TATEMOTO
UMSG_CREDITS_TAKASHI_KAWAGUCHI:
.faraddr MSG_CREDITS_TAKASHI_KAWAGUCHI
UMSG_CREDITS_KEIZOH_KATOH:
.faraddr MSG_CREDITS_KEIZOH_KATOH
UMSG_CREDITS_MOTOHIRO_ISHII:
.faraddr MSG_CREDITS_MOTOHIRO_ISHII
UMSG_CREDITS_AKIHITO_TODA:
.faraddr MSG_CREDITS_AKIHITO_TODA
UMSG_CREDITS_YUKARI_SAITOH:
.faraddr MSG_CREDITS_YUKARI_SAITOH
UMSG_CREDITS_PHIL_SANDHOP:
.faraddr MSG_CREDITS_PHIL_SANDHOP
UMSG_CREDITS_TOSHIKO_WATSON:
.faraddr MSG_CREDITS_TOSHIKO_WATSON
UMSG_CREDITS_YUKA_NAKATA:
.faraddr MSG_CREDITS_YUKA_NAKATA
UMSG_CREDITS_HIROKO_FAULKNER:
.faraddr MSG_CREDITS_HIROKO_FAULKNER
UMSG_CREDITS_TONY_HARMAN:
.faraddr MSG_CREDITS_TONY_HARMAN
UMSG_CREDITS_DAYV_BROOKS:
.faraddr MSG_CREDITS_DAYV_BROOKS
UMSG_CREDITS_NORIYUKI_MINAMI:
.faraddr MSG_CREDITS_NORIYUKI_MINAMI
UMSG_CREDITS_BIN_OHGAWARA:
.faraddr MSG_CREDITS_BIN_OHGAWARA
UMSG_CREDITS_YOSHIHISA_WADA:
.faraddr MSG_CREDITS_YOSHIHISA_WADA
UMSG_CREDITS_HIKONORI_SUZUKI:
.faraddr MSG_CREDITS_HIKONORI_SUZUKI
UMSG_CREDITS_TAKAO_SHIMIZU:
.faraddr MSG_CREDITS_TAKAO_SHIMIZU
UMSG_CREDITS_SHIGERU_MIYAMOTO:
.faraddr MSG_CREDITS_SHIGERU_MIYAMOTO
UMSG_CREDITS_HIROSHI_YAMAUCHI:
.faraddr MSG_CREDITS_HIROSHI_YAMAUCHI
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $00000
.faraddr $0F055
