;there are ABSOLUTELY no differences between jp/battles and us/battles
;super cool !!

;ENEMYID is a conscious decision to make id's dependant on offset
;(since it's basically an array, anyways)
;specifically to aid in shifting and general reordering.
.define ENEMYID(ta) .LOBYTE((ta-STATS_START)/$20)
.scope ENEMIES
    NONE = $FF
    UNKENEMY0 = ENEMYID(STATS_UNKENEMY0) ;$0
    BIGWOODOH = ENEMYID(STATS_BIGWOODOH) ;$1
    DRAGON = ENEMYID(STATS_DRAGON) ;$2
    R7038 = ENEMYID(STATS_R7038) ;$3
    ELEPHANT = ENEMYID(STATS_ELEPHANT) ;$4
    BEAR = ENEMYID(STATS_BEAR) ;$5
    BIG_FOOT = ENEMYID(STATS_BIG_FOOT) ;$6
    MAD_TRUCK = ENEMYID(STATS_MAD_TRUCK) ;$7
    OLD_ROBOT = ENEMYID(STATS_OLD_ROBOT) ;$8
    MEGABORG = ENEMYID(STATS_MEGABORG) ;$9
    GARGOYLE = ENEMYID(STATS_GARGOYLE) ;$a
    GABILAN = ENEMYID(STATS_GABILAN) ;$b
    GORILLA = ENEMYID(STATS_GORILLA) ;$c
    BISON = ENEMYID(STATS_BISON) ;$d
    TIGER = ENEMYID(STATS_TIGER) ;$e
    MAD_CAR = ENEMYID(STATS_MAD_CAR) ;$f
    RAEB_YDDET = ENEMYID(STATS_RAEB_YDDET) ;$10
    MAGIC_SNAIL = ENEMYID(STATS_MAGIC_SNAIL) ;$11
    TITANEES = ENEMYID(STATS_TITANEES) ;$12
    GIEGUE = ENEMYID(STATS_GIEGUE) ;$13
    EAGLE = ENEMYID(STATS_EAGLE) ;$14
    WOLF = ENEMYID(STATS_WOLF) ;$15
    SEAGULL = ENEMYID(STATS_SEAGULL) ;$16
    ALLIGATOR = ENEMYID(STATS_ALLIGATOR) ;$17
    ENERGYROBOT = ENEMYID(STATS_ENERGYROBOT) ;$18
    THE_FISH = ENEMYID(STATS_THE_FISH) ;$19
    FUGITIVE = ENEMYID(STATS_FUGITIVE) ;$1A
    BBS_BOSS = ENEMYID(STATS_BBS_BOSS) ;$1B
    BARBOT = ENEMYID(STATS_BARBOT) ;$1C
    NANCY = ENEMYID(STATS_NANCY) ;$1D
    STARMAN = ENEMYID(STATS_STARMAN) ;$1E
    ULLRICH = ENEMYID(STATS_ULLRICH) ;$1F
    CEREBRUM = ENEMYID(STATS_CEREBRUM) ;$20
    MOOK = ENEMYID(STATS_MOOK) ;$21
    ARMOR = ENEMYID(STATS_ARMOR) ;$22
    WOODOH = ENEMYID(STATS_WOODOH) ;$23
    WALLY = ENEMYID(STATS_WALLY) ;$24
    THE_HIPPIE = ENEMYID(STATS_THE_HIPPIE) ;$25
    BAG_LADY = ENEMYID(STATS_BAG_LADY) ;$26
    BB_GANG = ENEMYID(STATS_BB_GANG) ;$27
    DR_DISTORTO = ENEMYID(STATS_DR_DISTORTO) ;$28
    UNKENEMY1 = ENEMYID(STATS_UNKENEMY1) ;$29
    GANG_ZOMBIE = ENEMYID(STATS_GANG_ZOMBIE) ;$2A
    PSEUDOZOMBI = ENEMYID(STATS_PSEUDOZOMBI) ;$2B
    CROW = ENEMYID(STATS_CROW) ;$2C
    SNAKE = ENEMYID(STATS_SNAKE) ;$2D
    HYENA = ENEMYID(STATS_HYENA) ;$2E
    COUGAR = ENEMYID(STATS_COUGAR) ;$2F
    CENTIPEDE = ENEMYID(STATS_CENTIPEDE) ;$30
    DUST_BALL = ENEMYID(STATS_DUST_BALL) ;$31
    FLY = ENEMYID(STATS_FLY) ;$32
    SPIDER = ENEMYID(STATS_SPIDER) ;$33
    SCORPION = ENEMYID(STATS_SCORPION) ;$34
    ROPE = ENEMYID(STATS_ROPE) ;$35
    FIRE_BALL = ENEMYID(STATS_FIRE_BALL) ;$36
    WATCHER = ENEMYID(STATS_WATCHER) ;$37
    GROUCHO = ENEMYID(STATS_GROUCHO) ;$38
    GHOST = ENEMYID(STATS_GHOST) ;$39
    LIL_SAUCER = ENEMYID(STATS_LIL_SAUCER) ;$3A
    MR_BAT = ENEMYID(STATS_MR_BAT) ;$3B
    STARMAN_JR = ENEMYID(STATS_STARMAN_JR) ;$3C
    SKUNK = ENEMYID(STATS_SKUNK) ;$3D
    SHROUDLEY = ENEMYID(STATS_SHROUDLEY) ;$3E
    RAT = ENEMYID(STATS_RAT) ;$3F
    BOMBER = ENEMYID(STATS_BOMBER) ;$40
    UNKENEMY2 = ENEMYID(STATS_UNKENEMY2) ;$41
    DOLL = ENEMYID(STATS_DOLL) ;$42
    LAMP = ENEMYID(STATS_LAMP) ;$43
    UNKENEMY3 = ENEMYID(STATS_UNKENEMY3) ;$44
    UNKENEMY4 = ENEMYID(STATS_UNKENEMY4) ;$45
    BIONICCENTI = ENEMYID(STATS_BIONICCENTI) ;$46
    BIONICSCORP = ENEMYID(STATS_BIONICSCORP) ;$47
    UNKENEMY5 = ENEMYID(STATS_UNKENEMY5) ;$48
    UNKENEMY6 = ENEMYID(STATS_UNKENEMY6) ;$49
    RED_SNAKE = ENEMYID(STATS_RED_SNAKE) ;$4A
    LONE_WOLF = ENEMYID(STATS_LONE_WOLF) ;$4B
    POLAR_BEAR = ENEMYID(STATS_POLAR_BEAR) ;$4C
    UNKENEMY7 = ENEMYID(STATS_UNKENEMY7) ;$4D
    UNKENEMY8 = ENEMYID(STATS_UNKENEMY8) ;$4E
    UNKENEMY9 = ENEMYID(STATS_UNKENEMY9) ;$4F
    UNKENEMYA = ENEMYID(STATS_UNKENEMYA) ;$50
    RATTLESNAKE = ENEMYID(STATS_RATTLESNAKE) ;$51
    TARANTULA = ENEMYID(STATS_TARANTULA) ;$52
    CROCODILE = ENEMYID(STATS_CROCODILE) ;$53
    UNKENEMYB = ENEMYID(STATS_UNKENEMYB) ;$54
    BUFFALO = ENEMYID(STATS_BUFFALO) ;$55
    UNKENEMYC = ENEMYID(STATS_UNKENEMYC) ;$56
    BIONIC_BAT = ENEMYID(STATS_BIONIC_BAT) ;$57
    STRAY_DOG = ENEMYID(STATS_STRAY_DOG) ;$58
    PSYCHO_CAR = ENEMYID(STATS_PSYCHO_CAR) ;$59
    PSYCHOTRUCK = ENEMYID(STATS_PSYCHOTRUCK) ;$5a
    MANIACTRUCK = ENEMYID(STATS_MANIACTRUCK) ;$5b
    ALARM_GHOST = ENEMYID(STATS_ALARM_GHOST) ;$5c
    UNKENEMYD = ENEMYID(STATS_UNKENEMYD) ;$5D
    FOUREYES = ENEMYID(STATS_FOUREYES) ;$5E
    DADSEYES = ENEMYID(STATS_DADSEYES) ;$5F
    MOMSEYES = ENEMYID(STATS_MOMSEYES) ;$60
    UNKENEMYE = ENEMYID(STATS_UNKENEMYE) ;$61
    UNKENEMYF = ENEMYID(STATS_UNKENEMYF) ;$62
    SKY_YDDET = ENEMYID(STATS_SKY_YDDET) ;$63
    UNKENEMY10 = ENEMYID(STATS_UNKENEMY10) ;$64
    GIGA_BORG = ENEMYID(STATS_GIGA_BORG) ;$65
    OMEGA_BORG = ENEMYID(STATS_OMEGA_BORG) ;$66
    SCRAPPER = ENEMYID(STATS_SCRAPPER) ;$67
    ULTRABARBOT = ENEMYID(STATS_ULTRABARBOT) ;$68
    OMEGASAUCER = ENEMYID(STATS_OMEGASAUCER) ;$69
    KELLY = ENEMYID(STATS_KELLY) ;$6A
    STAR_MINER = ENEMYID(STATS_STAR_MINER) ;$6B
    SUPERENERGY = ENEMYID(STATS_SUPERENERGY) ;$6C
    JUANA = ENEMYID(STATS_JUANA) ;$6D
    BLUESTARMAN = ENEMYID(STATS_BLUESTARMAN) ;$6E
    ROCKOYLE = ENEMYID(STATS_ROCKOYLE) ;$6F
    TITANIAN = ENEMYID(STATS_TITANIAN) ;$70
    OH_MOOK = ENEMYID(STATS_OH_MOOK) ;$71
    UNKENEMY11 = ENEMYID(STATS_UNKENEMY11) ;$72
    ZOMBIE = ENEMYID(STATS_ZOMBIE) ;$73
    NASTYZOMBIE = ENEMYID(STATS_NASTYZOMBIE) ;$74
    SILVER_WOLF = ENEMYID(STATS_SILVER_WOLF) ;$75
    R7037 = ENEMYID(STATS_R7037) ;$76
    GRIZZLYBEAR = ENEMYID(STATS_GRIZZLYBEAR) ;$77
    R7038XX = ENEMYID(STATS_R7038XX) ;$78
    LASTSTARMAN = ENEMYID(STATS_LASTSTARMAN) ;$79
.endscope

.enum MUSIC
    BATTLE_FLIPPANT = 2
    BATTLE_DANGEROUS = 3
    BATTLE_HIPPIE = 4
.endenum

;eeeppppp
.define battlebyte8(position, encounter) .byte (encounter << 5) | position
;mmmmpppp
.define battlebyte9(palette, music) .byte (music << 4) | palette

BATTLES_START:
;null/default
BATTLE_NULL:
.byte ENEMIES::NONE,$00
.byte ENEMIES::UNKENEMY0,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 3, 0
battlebyte9 0, MUSIC::BATTLE_DANGEROUS

BATTLE_MYHOUSE_RAT1:
.byte ENEMIES::RAT,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 2, 0
battlebyte9 12, MUSIC::BATTLE_FLIPPANT

BATTLE_2:
.byte ENEMIES::RAT,$01
.byte ENEMIES::RAT,$02
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 7, 0
battlebyte9 12, MUSIC::BATTLE_FLIPPANT

BATTLE_3:
.byte ENEMIES::CROW,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 2, 0
battlebyte9 11, MUSIC::BATTLE_FLIPPANT

BATTLE_4:
.byte ENEMIES::CROW,$01
.byte ENEMIES::CROW,$02
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 7, 0
battlebyte9 11, MUSIC::BATTLE_FLIPPANT

BATTLE_5:
.byte ENEMIES::CENTIPEDE,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 2, 0
battlebyte9 11, MUSIC::BATTLE_FLIPPANT

BATTLE_6:
.byte ENEMIES::CENTIPEDE,$01
.byte ENEMIES::CENTIPEDE,$02
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 7, 0
battlebyte9 11, MUSIC::BATTLE_FLIPPANT

BATTLE_7:
.byte ENEMIES::STRAY_DOG,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 1, 0
battlebyte9 14, MUSIC::BATTLE_DANGEROUS

BATTLE_8:
.byte ENEMIES::WALLY,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 2, 0
battlebyte9 10, MUSIC::BATTLE_FLIPPANT

BATTLE_9:
.byte ENEMIES::THE_HIPPIE,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 2, 0
battlebyte9 11, MUSIC::BATTLE_HIPPIE

BATTLE_A:
.byte ENEMIES::BAG_LADY,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 2, 0
battlebyte9 8, MUSIC::BATTLE_FLIPPANT

BATTLE_B:
.byte ENEMIES::SNAKE,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 2, 0
battlebyte9 6, MUSIC::BATTLE_FLIPPANT

BATTLE_C:
.byte ENEMIES::MR_BAT,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 2, 0
battlebyte9 7, MUSIC::BATTLE_FLIPPANT

BATTLE_D:
.byte ENEMIES::MR_BAT,$01
.byte ENEMIES::MR_BAT,$02
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 7, 0
battlebyte9 7, MUSIC::BATTLE_FLIPPANT

BATTLE_E:
.byte ENEMIES::MR_BAT,$01
.byte ENEMIES::MR_BAT,$02
.byte ENEMIES::MR_BAT,$03
.byte ENEMIES::NONE,$00
battlebyte8 10, 0
battlebyte9 7, MUSIC::BATTLE_FLIPPANT

BATTLE_F:
.byte ENEMIES::MR_BAT,$01
.byte ENEMIES::MR_BAT,$02
.byte ENEMIES::MR_BAT,$03
.byte ENEMIES::MR_BAT,$04
battlebyte8 12, 0
battlebyte9 7, MUSIC::BATTLE_FLIPPANT

BATTLE_10:
.byte ENEMIES::PSEUDOZOMBI,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 2, 0
battlebyte9 12, MUSIC::BATTLE_DANGEROUS

BATTLE_11:
.byte ENEMIES::GANG_ZOMBIE,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 2, 0
battlebyte9 12, MUSIC::BATTLE_DANGEROUS

BATTLE_12:
.byte ENEMIES::ELEPHANT,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 0, 0
battlebyte9 6, MUSIC::BATTLE_DANGEROUS

BATTLE_13:
.byte ENEMIES::TIGER,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 0, 0
battlebyte9 0, MUSIC::BATTLE_DANGEROUS

BATTLE_14:
.byte ENEMIES::GORILLA,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 1, 0
battlebyte9 7, MUSIC::BATTLE_DANGEROUS

BATTLE_15:
.byte ENEMIES::HYENA,$01
.byte ENEMIES::HYENA,$02
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 8, 0
battlebyte9 6, MUSIC::BATTLE_FLIPPANT

BATTLE_16:
.byte ENEMIES::HYENA,$01
.byte ENEMIES::HYENA,$02
.byte ENEMIES::HYENA,$03
.byte ENEMIES::NONE,$00
battlebyte8 11, 0
battlebyte9 6, MUSIC::BATTLE_FLIPPANT

BATTLE_17:
.byte ENEMIES::ALLIGATOR,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 1, 0
battlebyte9 9, MUSIC::BATTLE_DANGEROUS

BATTLE_18:
.byte ENEMIES::ALLIGATOR,$01
.byte ENEMIES::ALLIGATOR,$02
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 8, 0
battlebyte9 9, MUSIC::BATTLE_DANGEROUS

BATTLE_19:
.byte ENEMIES::FLY,$01
.byte ENEMIES::FLY,$82
.byte ENEMIES::FLY,$83
.byte ENEMIES::FLY,$84
battlebyte8 12, 0
battlebyte9 1, MUSIC::BATTLE_FLIPPANT

BATTLE_1A:
.byte ENEMIES::FLY,$01
.byte ENEMIES::FLY,$02
.byte ENEMIES::FLY,$83
.byte ENEMIES::FLY,$84
battlebyte8 12, 0
battlebyte9 1, MUSIC::BATTLE_FLIPPANT

BATTLE_1B:
.byte ENEMIES::BIONICCENTI,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 2, 0
battlebyte9 1, MUSIC::BATTLE_FLIPPANT

BATTLE_1C:
.byte ENEMIES::LIL_SAUCER,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 2, 0
battlebyte9 0, MUSIC::BATTLE_DANGEROUS

BATTLE_1D:
.byte ENEMIES::LIL_SAUCER,$01
.byte ENEMIES::LIL_SAUCER,$02
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 7, 0
battlebyte9 0, MUSIC::BATTLE_DANGEROUS

BATTLE_1E:
.byte ENEMIES::BARBOT,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 2, 0
battlebyte9 0, MUSIC::BATTLE_DANGEROUS

BATTLE_1F:
.byte ENEMIES::BARBOT,$00
.byte ENEMIES::LIL_SAUCER,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 7, 0
battlebyte9 0, MUSIC::BATTLE_DANGEROUS

BATTLE_20:
.byte ENEMIES::LIL_SAUCER,$01
.byte ENEMIES::BARBOT,$00
.byte ENEMIES::LIL_SAUCER,$02
.byte ENEMIES::NONE,$00
battlebyte8 10, 0
battlebyte9 0, MUSIC::BATTLE_DANGEROUS

BATTLE_21:
.byte ENEMIES::LIL_SAUCER,$01
.byte ENEMIES::LIL_SAUCER,$02
.byte ENEMIES::BARBOT,$00
.byte ENEMIES::LIL_SAUCER,$03
battlebyte8 12, 0
battlebyte9 0, MUSIC::BATTLE_DANGEROUS

BATTLE_22:
.byte ENEMIES::RAEB_YDDET,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 1, 0
battlebyte9 1, MUSIC::BATTLE_DANGEROUS

BATTLE_23:
.byte ENEMIES::RAEB_YDDET,$00
.byte ENEMIES::SKY_YDDET,$80
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 8, 0
battlebyte9 1, MUSIC::BATTLE_DANGEROUS

BATTLE_MAGICANT_BIGWOODOH:
.byte ENEMIES::BIGWOODOH,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 0, 0
battlebyte9 1, MUSIC::BATTLE_DANGEROUS

BATTLE_MAGICANT_WOODOH:
.byte ENEMIES::WOODOH,$01
.byte ENEMIES::WOODOH,$82
.byte ENEMIES::WOODOH,$83
.byte ENEMIES::NONE,$00
battlebyte8 10, 0
battlebyte9 6, MUSIC::BATTLE_DANGEROUS

BATTLE_26:
.byte ENEMIES::MAGIC_SNAIL,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 1, 0
battlebyte9 11, MUSIC::BATTLE_DANGEROUS

BATTLE_27:
.byte ENEMIES::MAGIC_SNAIL,$01
.byte ENEMIES::MAGIC_SNAIL,$02
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 8, 0
battlebyte9 11, MUSIC::BATTLE_DANGEROUS

BATTLE_28:
.byte ENEMIES::WATCHER,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 2, 0
battlebyte9 0, MUSIC::BATTLE_FLIPPANT

BATTLE_29:
.byte ENEMIES::MOMSEYES,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 2, 0
battlebyte9 0, MUSIC::BATTLE_FLIPPANT

BATTLE_2A:
.byte ENEMIES::DADSEYES,$00
.byte ENEMIES::WATCHER,$00
.byte ENEMIES::MOMSEYES,$00
.byte ENEMIES::NONE,$00
battlebyte8 10, 0
battlebyte9 0, MUSIC::BATTLE_FLIPPANT

BATTLE_2B:
.byte ENEMIES::DADSEYES,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 2, 0
battlebyte9 0, MUSIC::BATTLE_FLIPPANT

BATTLE_2C:
.byte ENEMIES::FOUREYES,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 2, 0
battlebyte9 0, MUSIC::BATTLE_FLIPPANT

BATTLE_2D:
.byte ENEMIES::NONE,$00
.byte ENEMIES::GROUCHO,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 4, 0
battlebyte9 0, MUSIC::BATTLE_FLIPPANT

BATTLE_2E:
.byte ENEMIES::DRAGON,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 0, 0
battlebyte9 6, MUSIC::BATTLE_DANGEROUS

BATTLE_2F:
.byte ENEMIES::THE_FISH,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 2, 0
battlebyte9 5, MUSIC::BATTLE_DANGEROUS

BATTLE_30:
.byte ENEMIES::BEAR,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 1, 0
battlebyte9 13, MUSIC::BATTLE_DANGEROUS

BATTLE_31:
.byte ENEMIES::NONE,$00
.byte ENEMIES::EAGLE,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 3, 0
battlebyte9 10, MUSIC::BATTLE_DANGEROUS

BATTLE_32:
.byte ENEMIES::NONE,$00
.byte ENEMIES::EAGLE,$01
.byte ENEMIES::EAGLE,$02
.byte ENEMIES::NONE,$00
battlebyte8 20, 0
battlebyte9 10, MUSIC::BATTLE_DANGEROUS

BATTLE_33:
.byte ENEMIES::NONE,$00
.byte ENEMIES::EAGLE,$01
.byte ENEMIES::EAGLE,$02
.byte ENEMIES::EAGLE,$03
battlebyte8 21, 0
battlebyte9 10, MUSIC::BATTLE_DANGEROUS

BATTLE_34:
.byte ENEMIES::SKUNK,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 2, 0
battlebyte9 12, MUSIC::BATTLE_DANGEROUS

BATTLE_35:
.byte ENEMIES::SKUNK,$01
.byte ENEMIES::SKUNK,$02
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 7, 0
battlebyte9 12, MUSIC::BATTLE_DANGEROUS

BATTLE_36:
.byte ENEMIES::COUGAR,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 1, 0
battlebyte9 12, MUSIC::BATTLE_DANGEROUS

BATTLE_37:
.byte ENEMIES::COUGAR,$01
.byte ENEMIES::COUGAR,$02
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 8, 0
battlebyte9 12, MUSIC::BATTLE_DANGEROUS

BATTLE_38:
.byte ENEMIES::COUGAR,$00
.byte ENEMIES::SKUNK,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 17, 0
battlebyte9 12, MUSIC::BATTLE_DANGEROUS

BATTLE_39:
.byte ENEMIES::COUGAR,$00
.byte ENEMIES::SKUNK,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 17, 0
battlebyte9 12, MUSIC::BATTLE_DANGEROUS

BATTLE_3A:
.byte ENEMIES::WOLF,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 1, 0
battlebyte9 14, MUSIC::BATTLE_DANGEROUS

BATTLE_3B:
.byte ENEMIES::WOLF,$01
.byte ENEMIES::WOLF,$02
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 8, 0
battlebyte9 14, MUSIC::BATTLE_DANGEROUS

BATTLE_3C:
.byte ENEMIES::MAD_CAR,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 1, 0
battlebyte9 1, MUSIC::BATTLE_HIPPIE

BATTLE_3D:
.byte ENEMIES::MAD_CAR,$00
.byte ENEMIES::MAD_TRUCK,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 8, 0
battlebyte9 1, MUSIC::BATTLE_HIPPIE

BATTLE_3E:
.byte ENEMIES::PSYCHO_CAR,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 1, 0
battlebyte9 0, MUSIC::BATTLE_HIPPIE

BATTLE_3F:
.byte ENEMIES::NONE,$00
.byte ENEMIES::PSYCHOTRUCK,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 3, 0
battlebyte9 0, MUSIC::BATTLE_HIPPIE

BATTLE_40:
.byte ENEMIES::NONE,$00
.byte ENEMIES::MANIACTRUCK,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 3, 0
battlebyte9 4, MUSIC::BATTLE_HIPPIE

BATTLE_41:
.byte ENEMIES::OLD_ROBOT,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 1, 0
battlebyte9 2, MUSIC::BATTLE_DANGEROUS

BATTLE_42:
.byte ENEMIES::SCRAPPER,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 1, 0
battlebyte9 3, MUSIC::BATTLE_DANGEROUS

BATTLE_43:
.byte ENEMIES::DR_DISTORTO,$00
.byte ENEMIES::OLD_ROBOT,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 14, 0
battlebyte9 2, MUSIC::BATTLE_DANGEROUS

BATTLE_44:
.byte ENEMIES::DR_DISTORTO,$00
.byte ENEMIES::SCRAPPER,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 14, 0
battlebyte9 3, MUSIC::BATTLE_DANGEROUS

BATTLE_45:
.byte ENEMIES::BOMBER,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 2, 0
battlebyte9 5, MUSIC::BATTLE_FLIPPANT

BATTLE_46:
.byte ENEMIES::FIRE_BALL,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 2, 0
battlebyte9 6, MUSIC::BATTLE_FLIPPANT

BATTLE_47:
.byte ENEMIES::RED_SNAKE,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 2, 0
battlebyte9 1, MUSIC::BATTLE_DANGEROUS

BATTLE_48:
.byte ENEMIES::GHOST,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 2, 0
battlebyte9 4, MUSIC::BATTLE_FLIPPANT

BATTLE_49:
.byte ENEMIES::GHOST,$01
.byte ENEMIES::GHOST,$02
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 7, 0
battlebyte9 4, MUSIC::BATTLE_FLIPPANT

BATTLE_4A:
.byte ENEMIES::GHOST,$01
.byte ENEMIES::GHOST,$02
.byte ENEMIES::GHOST,$03
.byte ENEMIES::NONE,$00
battlebyte8 10, 0
battlebyte9 4, MUSIC::BATTLE_FLIPPANT

BATTLE_4B:
.byte ENEMIES::ARMOR,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 2, 0
battlebyte9 4, MUSIC::BATTLE_DANGEROUS

BATTLE_4C:
.byte ENEMIES::ARMOR,$01
.byte ENEMIES::ARMOR,$02
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 7, 0
battlebyte9 4, MUSIC::BATTLE_DANGEROUS

BATTLE_4D:
.byte ENEMIES::DUST_BALL,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 1, 0
battlebyte9 5, MUSIC::BATTLE_DANGEROUS

BATTLE_4E:
.byte ENEMIES::BIONIC_BAT,$01
.byte ENEMIES::BIONIC_BAT,$02
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 7, 0
battlebyte9 5, MUSIC::BATTLE_FLIPPANT

BATTLE_4F:
.byte ENEMIES::BIONIC_BAT,$01
.byte ENEMIES::BIONIC_BAT,$02
.byte ENEMIES::BIONIC_BAT,$83
.byte ENEMIES::BIONIC_BAT,$84
battlebyte8 12, 0
battlebyte9 5, MUSIC::BATTLE_FLIPPANT

BATTLE_50:
.byte ENEMIES::GHOST,$81
.byte ENEMIES::GHOST,$82
.byte ENEMIES::ALARM_GHOST,$00
.byte ENEMIES::GHOST,$83
battlebyte8 12, 0
battlebyte9 4, MUSIC::BATTLE_DANGEROUS

BATTLE_51:
.byte ENEMIES::ZOMBIE,$80
.byte ENEMIES::GHOST,$80
.byte ENEMIES::ALARM_GHOST,$00
.byte ENEMIES::ARMOR,$80
battlebyte8 12, 0
battlebyte9 4, MUSIC::BATTLE_DANGEROUS

BATTLE_52:
.byte ENEMIES::ZOMBIE,$01
.byte ENEMIES::ZOMBIE,$02
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 7, 0
battlebyte9 4, MUSIC::BATTLE_DANGEROUS

BATTLE_53:
.byte ENEMIES::ZOMBIE,$00
.byte ENEMIES::NASTYZOMBIE,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 7, 0
battlebyte9 4, MUSIC::BATTLE_DANGEROUS

BATTLE_54:
.byte ENEMIES::BIONIC_BAT,$80
.byte ENEMIES::DUST_BALL,$81
.byte ENEMIES::ALARM_GHOST,$00
.byte ENEMIES::DUST_BALL,$82
battlebyte8 18, 0
battlebyte9 5, MUSIC::BATTLE_DANGEROUS

BATTLE_55:
.byte ENEMIES::SILVER_WOLF,$01
.byte ENEMIES::SILVER_WOLF,$02
.byte ENEMIES::SILVER_WOLF,$03
.byte ENEMIES::NONE,$00
battlebyte8 11, 0
battlebyte9 14, MUSIC::BATTLE_DANGEROUS

BATTLE_56:
.byte ENEMIES::SILVER_WOLF,$01
.byte ENEMIES::SILVER_WOLF,$02
.byte ENEMIES::SILVER_WOLF,$03
.byte ENEMIES::SILVER_WOLF,$04
battlebyte8 13, 0
battlebyte9 14, MUSIC::BATTLE_DANGEROUS

BATTLE_57:
.byte ENEMIES::LONE_WOLF,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 1, 0
battlebyte9 14, MUSIC::BATTLE_DANGEROUS

BATTLE_58:
.byte ENEMIES::POLAR_BEAR,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 1, 0
battlebyte9 13, MUSIC::BATTLE_DANGEROUS

BATTLE_59:
.byte ENEMIES::BIG_FOOT,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 0, 0
battlebyte9 7, MUSIC::BATTLE_FLIPPANT

BATTLE_5A:
.byte ENEMIES::OMEGASAUCER,$01
.byte ENEMIES::OMEGASAUCER,$02
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 7, 0
battlebyte9 3, MUSIC::BATTLE_DANGEROUS

BATTLE_5B:
.byte ENEMIES::OMEGASAUCER,$01
.byte ENEMIES::OMEGASAUCER,$02
.byte ENEMIES::OMEGASAUCER,$03
.byte ENEMIES::NONE,$00
battlebyte8 10, 0
battlebyte9 3, MUSIC::BATTLE_DANGEROUS

BATTLE_5C:
.byte ENEMIES::ULTRABARBOT,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 2, 0
battlebyte9 3, MUSIC::BATTLE_DANGEROUS

BATTLE_5D:
.byte ENEMIES::OMEGASAUCER,$01
.byte ENEMIES::ULTRABARBOT,$00
.byte ENEMIES::OMEGASAUCER,$02
.byte ENEMIES::NONE,$00
battlebyte8 10, 0
battlebyte9 3, MUSIC::BATTLE_DANGEROUS

BATTLE_5E:
.byte ENEMIES::OMEGASAUCER,$01
.byte ENEMIES::OMEGASAUCER,$02
.byte ENEMIES::ULTRABARBOT,$00
.byte ENEMIES::OMEGASAUCER,$03
battlebyte8 12, 0
battlebyte9 3, MUSIC::BATTLE_DANGEROUS

BATTLE_5F:
.byte ENEMIES::ULTRABARBOT,$00
.byte ENEMIES::STARMAN,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 7, 0
battlebyte9 8, MUSIC::BATTLE_DANGEROUS

BATTLE_60:
.byte ENEMIES::STARMAN,$01
.byte ENEMIES::ULTRABARBOT,$00
.byte ENEMIES::STARMAN,$02
.byte ENEMIES::NONE,$00
battlebyte8 10, 0
battlebyte9 8, MUSIC::BATTLE_DANGEROUS

BATTLE_61:
.byte ENEMIES::ULTRABARBOT,$00
.byte ENEMIES::ENERGYROBOT,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 14, 0
battlebyte9 3, MUSIC::BATTLE_DANGEROUS

BATTLE_62:
.byte ENEMIES::TITANEES,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 1, 0
battlebyte9 2, MUSIC::BATTLE_DANGEROUS

BATTLE_63:
.byte ENEMIES::TITANEES,$01
.byte ENEMIES::TITANEES,$02
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 8, 0
battlebyte9 2, MUSIC::BATTLE_DANGEROUS

BATTLE_64:
.byte ENEMIES::NANCY,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 2, 0
battlebyte9 2, MUSIC::BATTLE_DANGEROUS

BATTLE_65:
.byte ENEMIES::NANCY,$00
.byte ENEMIES::ENERGYROBOT,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 14, 0
battlebyte9 2, MUSIC::BATTLE_DANGEROUS

BATTLE_66:
.byte ENEMIES::SPIDER,$01
.byte ENEMIES::SPIDER,$82
.byte ENEMIES::SPIDER,$83
.byte ENEMIES::NONE,$00
battlebyte8 10, 0
battlebyte9 0, MUSIC::BATTLE_FLIPPANT

BATTLE_67:
.byte ENEMIES::GABILAN,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 1, 0
battlebyte9 6, MUSIC::BATTLE_DANGEROUS

BATTLE_68:
.byte ENEMIES::GABILAN,$01
.byte ENEMIES::GABILAN,$02
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 8, 0
battlebyte9 6, MUSIC::BATTLE_DANGEROUS

BATTLE_69:
.byte ENEMIES::STARMAN,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 2, 0
battlebyte9 0, MUSIC::BATTLE_DANGEROUS

BATTLE_6A:
.byte ENEMIES::RATTLESNAKE,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 2, 0
battlebyte9 0, MUSIC::BATTLE_DANGEROUS

BATTLE_6B:
.byte ENEMIES::TARANTULA,$01
.byte ENEMIES::TARANTULA,$82
.byte ENEMIES::TARANTULA,$83
.byte ENEMIES::NONE,$00
battlebyte8 10, 0
battlebyte9 1, MUSIC::BATTLE_FLIPPANT

BATTLE_6C:
.byte ENEMIES::SCORPION,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 2, 0
battlebyte9 1, MUSIC::BATTLE_DANGEROUS

BATTLE_6D:
.byte ENEMIES::SCORPION,$01
.byte ENEMIES::SCORPION,$02
.byte ENEMIES::NONE,$03 ;?
.byte ENEMIES::NONE,$00
battlebyte8 7, 0
battlebyte9 1, MUSIC::BATTLE_DANGEROUS

BATTLE_6E:
.byte ENEMIES::BIONICSCORP,$00
.byte ENEMIES::SCORPION,$01
.byte ENEMIES::SCORPION,$02
.byte ENEMIES::NONE,$00
battlebyte8 10, 0
battlebyte9 1, MUSIC::BATTLE_DANGEROUS

BATTLE_6F:
.byte ENEMIES::R7037,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 0, 2
battlebyte9 0, MUSIC::BATTLE_DANGEROUS

BATTLE_70:
.byte ENEMIES::KELLY,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 2, 0
battlebyte9 2, MUSIC::BATTLE_DANGEROUS

BATTLE_71:
.byte ENEMIES::KELLY,$00
.byte ENEMIES::ENERGYROBOT,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 14, 0
battlebyte9 2, MUSIC::BATTLE_DANGEROUS

BATTLE_72:
.byte ENEMIES::NONE,$00
.byte ENEMIES::MOOK,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 4, 0
battlebyte9 10, MUSIC::BATTLE_DANGEROUS

BATTLE_73:
.byte ENEMIES::NONE,$00
.byte ENEMIES::MOOK,$01
.byte ENEMIES::MOOK,$02
.byte ENEMIES::NONE,$00
battlebyte8 5, 0
battlebyte9 10, MUSIC::BATTLE_DANGEROUS

BATTLE_74:
.byte ENEMIES::NONE,$00
.byte ENEMIES::MOOK,$01
.byte ENEMIES::MOOK,$02
.byte ENEMIES::MOOK,$03
battlebyte8 6, 0
battlebyte9 10, MUSIC::BATTLE_DANGEROUS

BATTLE_75:
.byte ENEMIES::CROCODILE,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 1, 0
battlebyte9 9, MUSIC::BATTLE_DANGEROUS

BATTLE_76:
.byte ENEMIES::CROCODILE,$01
.byte ENEMIES::CROCODILE,$02
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 8, 0
battlebyte9 9, MUSIC::BATTLE_DANGEROUS

BATTLE_77:
.byte ENEMIES::CROCODILE,$01
.byte ENEMIES::CROCODILE,$02
.byte ENEMIES::CROCODILE,$03
.byte ENEMIES::NONE,$00
battlebyte8 11, 0
battlebyte9 9, MUSIC::BATTLE_DANGEROUS

BATTLE_78:
.byte ENEMIES::BISON,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 0, 0
battlebyte9 15, MUSIC::BATTLE_FLIPPANT

BATTLE_79:
.byte ENEMIES::BISON,$01
.byte ENEMIES::BISON,$02
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 9, 0
battlebyte9 15, MUSIC::BATTLE_FLIPPANT

BATTLE_7A:
.byte ENEMIES::BUFFALO,$01
.byte ENEMIES::BUFFALO,$02
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 9, 0
battlebyte9 13, MUSIC::BATTLE_DANGEROUS

BATTLE_7B:
.byte ENEMIES::BUFFALO,$01
.byte ENEMIES::BUFFALO,$02
.byte ENEMIES::BUFFALO,$03
.byte ENEMIES::NONE,$00
battlebyte8 19, 0
battlebyte9 13, MUSIC::BATTLE_DANGEROUS

BATTLE_7C:
.byte ENEMIES::SEAGULL,$01
.byte ENEMIES::SEAGULL,$02
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 8, 0
battlebyte9 13, MUSIC::BATTLE_FLIPPANT

BATTLE_7D:
.byte ENEMIES::SEAGULL,$01
.byte ENEMIES::SEAGULL,$02
.byte ENEMIES::SEAGULL,$03
.byte ENEMIES::NONE,$00
battlebyte8 11, 0
battlebyte9 13, MUSIC::BATTLE_FLIPPANT

BATTLE_7E:
.byte ENEMIES::BLUESTARMAN,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 2, 0
battlebyte9 9, MUSIC::BATTLE_DANGEROUS

BATTLE_7F:
.byte ENEMIES::BLUESTARMAN,$01
.byte ENEMIES::BLUESTARMAN,$02
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 7, 0
battlebyte9 9, MUSIC::BATTLE_DANGEROUS

BATTLE_80:
.byte ENEMIES::BLUESTARMAN,$01
.byte ENEMIES::BLUESTARMAN,$02
.byte ENEMIES::BLUESTARMAN,$03
.byte ENEMIES::NONE,$00
battlebyte8 10, 0
battlebyte9 9, MUSIC::BATTLE_DANGEROUS

BATTLE_81:
.byte ENEMIES::GRIZZLYBEAR,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 1, 0
battlebyte9 13, MUSIC::BATTLE_DANGEROUS

BATTLE_82:
.byte ENEMIES::CEREBRUM,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 2, 0
battlebyte9 10, MUSIC::BATTLE_DANGEROUS

BATTLE_83:
.byte ENEMIES::TITANIAN,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 1, 0
battlebyte9 8, MUSIC::BATTLE_DANGEROUS

BATTLE_84:
.byte ENEMIES::TITANIAN,$01
.byte ENEMIES::TITANIAN,$02
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 8, 0
battlebyte9 8, MUSIC::BATTLE_DANGEROUS

BATTLE_85:
.byte ENEMIES::GARGOYLE,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 0, 0
battlebyte9 7, MUSIC::BATTLE_DANGEROUS

BATTLE_86:
.byte ENEMIES::GARGOYLE,$01
.byte ENEMIES::GARGOYLE,$02
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 9, 0
battlebyte9 7, MUSIC::BATTLE_DANGEROUS

BATTLE_87:
.byte ENEMIES::ROCKOYLE,$01
.byte ENEMIES::ROCKOYLE,$02
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 9, 0
battlebyte9 7, MUSIC::BATTLE_DANGEROUS

BATTLE_88:
.byte ENEMIES::ROCKOYLE,$01
.byte ENEMIES::ROCKOYLE,$02
.byte ENEMIES::ROCKOYLE,$03
.byte ENEMIES::NONE,$00
battlebyte8 19, 0
battlebyte9 7, MUSIC::BATTLE_DANGEROUS

BATTLE_89:
.byte ENEMIES::MEGABORG,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 1, 0
battlebyte9 2, MUSIC::BATTLE_DANGEROUS

BATTLE_8A:
.byte ENEMIES::MEGABORG,$01
.byte ENEMIES::MEGABORG,$02
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 8, 0
battlebyte9 2, MUSIC::BATTLE_DANGEROUS

BATTLE_8B:
.byte ENEMIES::MEGABORG,$00
.byte ENEMIES::SUPERENERGY,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 8, 0
battlebyte9 2, MUSIC::BATTLE_DANGEROUS

BATTLE_8C:
.byte ENEMIES::NONE,$00
.byte ENEMIES::OH_MOOK,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 4, 0
battlebyte9 10, MUSIC::BATTLE_DANGEROUS

BATTLE_8D:
.byte ENEMIES::NONE,$00
.byte ENEMIES::OH_MOOK,$01
.byte ENEMIES::OH_MOOK,$02
.byte ENEMIES::NONE,$00
battlebyte8 5, 0
battlebyte9 10, MUSIC::BATTLE_DANGEROUS

BATTLE_8E:
.byte ENEMIES::NONE,$00
.byte ENEMIES::OH_MOOK,$01
.byte ENEMIES::OH_MOOK,$02
.byte ENEMIES::OH_MOOK,$03
battlebyte8 6, 0
battlebyte9 10, MUSIC::BATTLE_DANGEROUS

BATTLE_8F:
.byte ENEMIES::NONE,$00
.byte ENEMIES::OH_MOOK,$01
.byte ENEMIES::OH_MOOK,$02
.byte ENEMIES::OH_MOOK,$03
battlebyte8 6, 0
battlebyte9 10, MUSIC::BATTLE_DANGEROUS

BATTLE_90:
.byte ENEMIES::R7038XX,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 0, 3
battlebyte9 15, MUSIC::BATTLE_DANGEROUS

BATTLE_91:
.byte ENEMIES::R7038,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 0, 4
battlebyte9 6, MUSIC::BATTLE_DANGEROUS

BATTLE_92:
.byte ENEMIES::STAR_MINER,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 2, 0
battlebyte9 12, MUSIC::BATTLE_DANGEROUS

BATTLE_93:
.byte ENEMIES::JUANA,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 2, 0
battlebyte9 2, MUSIC::BATTLE_DANGEROUS

BATTLE_94:
.byte ENEMIES::JUANA,$00
.byte ENEMIES::SUPERENERGY,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 14, 0
battlebyte9 2, MUSIC::BATTLE_DANGEROUS

BATTLE_95:
.byte ENEMIES::GIGA_BORG,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 1, 0
battlebyte9 0, MUSIC::BATTLE_DANGEROUS

BATTLE_96:
.byte ENEMIES::GIGA_BORG,$01
.byte ENEMIES::GIGA_BORG,$02
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 8, 0
battlebyte9 0, MUSIC::BATTLE_DANGEROUS

BATTLE_97:
.byte ENEMIES::OMEGA_BORG,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 1, 0
battlebyte9 0, MUSIC::BATTLE_DANGEROUS

BATTLE_98:
.byte ENEMIES::OMEGA_BORG,$00
.byte ENEMIES::GIGA_BORG,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 8, 0
battlebyte9 0, MUSIC::BATTLE_DANGEROUS

BATTLE_99:
.byte ENEMIES::LASTSTARMAN,$01
.byte ENEMIES::LASTSTARMAN,$02
.byte ENEMIES::LASTSTARMAN,$03
.byte ENEMIES::NONE,$00
battlebyte8 10, 0
battlebyte9 0, MUSIC::BATTLE_DANGEROUS

BATTLE_9A:
.byte ENEMIES::LASTSTARMAN,$01
.byte ENEMIES::LASTSTARMAN,$02
.byte ENEMIES::LASTSTARMAN,$03
.byte ENEMIES::LASTSTARMAN,$04
battlebyte8 12, 0
battlebyte9 0, MUSIC::BATTLE_DANGEROUS

BATTLE_9B:
.byte ENEMIES::LASTSTARMAN,$01
.byte ENEMIES::LASTSTARMAN,$02
.byte ENEMIES::LASTSTARMAN,$03
.byte ENEMIES::LASTSTARMAN,$04
battlebyte8 12, 0
battlebyte9 0, MUSIC::BATTLE_DANGEROUS

BATTLE_9C:
.byte ENEMIES::NONE,$00
.byte ENEMIES::FUGITIVE,$00
.byte ENEMIES::ROPE,$00
.byte ENEMIES::NONE,$00
battlebyte8 5, 0
battlebyte9 3, MUSIC::BATTLE_FLIPPANT

;Teddy fight
BATTLE_9D:
.byte ENEMIES::BBS_BOSS,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 2, 1
battlebyte9 7, MUSIC::BATTLE_HIPPIE

;B.B. Gang
BATTLE_9E:
.byte ENEMIES::BB_GANG,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 2, 0
battlebyte9 11, MUSIC::BATTLE_HIPPIE

;Doll
BATTLE_9F:
.byte ENEMIES::DOLL,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 2, 0
battlebyte9 15, MUSIC::BATTLE_DANGEROUS

;Lamp
BATTLE_A0:
.byte ENEMIES::LAMP,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 2, 0
battlebyte9 6, MUSIC::BATTLE_DANGEROUS

;Ullrich
BATTLE_A1:
.byte ENEMIES::ULLRICH,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 1, 0
battlebyte9 9, MUSIC::BATTLE_DANGEROUS

;giegue intro
BATTLE_A2:
.byte ENEMIES::GIEGUE,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 0, 5
battlebyte9 9, 5

;shroudley
BATTLE_A3:
.byte ENEMIES::NONE,$00
.byte ENEMIES::SHROUDLEY,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 3, 0
battlebyte9 15, MUSIC::BATTLE_DANGEROUS

;starman jr
BATTLE_A4:
.byte ENEMIES::STARMAN_JR,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
.byte ENEMIES::NONE,$00
battlebyte8 1, 0
battlebyte9 14, MUSIC::BATTLE_DANGEROUS
