;these are ordered the same as their choicers. have fun
.addr TRAINPATH_UNION_REINDEER
.addr TRAINPATH_UNION_SPOOKANE
.addr TRAINPATH_UNION_SNOWMAN
.addr TRAINPATH_REINDEER_UNION
.addr TRAINPATH_SPOOKANE_UNION
.addr TRAINPATH_SNOWMAN_UNION
.addr TRAINPATH_REINDEER_SPOOKANE
.addr TRAINPATH_REINDEER_SNOWMAN
.addr TRAINPATH_SPOOKANE_REINDEER
.addr TRAINPATH_SPOOKANE_SNOWMAN
.addr TRAINPATH_SNOWMAN_REINDEER
.addr TRAINPATH_SNOWMAN_SPOOKANE

;leaving merrysville
TRAINPATH_UNION_REINDEER:
moveDef DIRECTIONS::DOWN_LEFT, 2, 14
moveDef DIRECTIONS::DOWN, 2, 1
moveDef DIRECTIONS::DOWN_RIGHT, 2, 113
moveDef DIRECTIONS::RIGHT, 2, 16
MOVE_WARP 0, 10, DIRECTIONS::RIGHT, 1018
moveDef DIRECTIONS::RIGHT, 2, 200
moveDef DIRECTIONS::RIGHT, 2, 148
MOVE_WARP 0, 432, DIRECTIONS::DOWN_LEFT, 741
moveDef DIRECTIONS::DOWN_LEFT, 2, 40
moveDef DIRECTIONS::DOWN, 2, 1
moveDef DIRECTIONS::DOWN_RIGHT, 2, 49
moveDef DIRECTIONS::RIGHT, 2, 77
OBJ_STOP
moveDef DIRECTIONS::UP_LEFT, 1, 155
moveDef DIRECTIONS::LEFT, 8, 242

TRAINPATH_UNION_SPOOKANE:
moveDef DIRECTIONS::DOWN_LEFT, 2, 14
moveDef DIRECTIONS::DOWN, 2, 1
moveDef DIRECTIONS::DOWN_RIGHT, 2, 113
moveDef DIRECTIONS::RIGHT, 2, 16
MOVE_WARP 0, 10, DIRECTIONS::RIGHT, 1018
moveDef DIRECTIONS::RIGHT, 2, 200
moveDef DIRECTIONS::RIGHT, 2, 148
MOVE_WARP 0, 432, DIRECTIONS::DOWN_LEFT, 741
moveDef DIRECTIONS::DOWN_LEFT, 2, 40
moveDef DIRECTIONS::DOWN, 2, 1
moveDef DIRECTIONS::DOWN_RIGHT, 2, 49
moveDef DIRECTIONS::RIGHT, 2, 245
OBJ_STOP
moveDef DIRECTIONS::UP_LEFT, 1, 167
moveDef DIRECTIONS::LEFT, 8, 250

TRAINPATH_UNION_SNOWMAN:
moveDef DIRECTIONS::DOWN_LEFT, 2, 14
moveDef DIRECTIONS::DOWN, 2, 1
moveDef DIRECTIONS::DOWN_RIGHT, 2, 113
moveDef DIRECTIONS::RIGHT, 2, 16
MOVE_WARP 0, 10, DIRECTIONS::RIGHT, 1018
moveDef DIRECTIONS::RIGHT, 2, 200
moveDef DIRECTIONS::RIGHT, 2, 148
MOVE_WARP 0, 432, DIRECTIONS::DOWN_LEFT, 741
moveDef DIRECTIONS::DOWN_LEFT, 2, 40
moveDef DIRECTIONS::DOWN, 2, 1
moveDef DIRECTIONS::DOWN_RIGHT, 2, 49
moveDef DIRECTIONS::RIGHT, 2, 180
moveDef DIRECTIONS::RIGHT, 2, 100
MOVE_WARP 0, 10, DIRECTIONS::RIGHT, 522
moveDef DIRECTIONS::RIGHT, 2, 108
MOVE_WARP 0, 832, DIRECTIONS::DOWN_LEFT, 969
moveDef DIRECTIONS::DOWN_LEFT, 2, 8
moveDef DIRECTIONS::DOWN, 2, 1
moveDef DIRECTIONS::DOWN_RIGHT, 2, 13
moveDef DIRECTIONS::RIGHT, 2, 22
OBJ_STOP
moveDef DIRECTIONS::RIGHT, 1, 183
moveDef DIRECTIONS::LEFT, 8, 242

TRAINPATH_REINDEER_UNION:
moveDef DIRECTIONS::LEFT, 2, 76
moveDef DIRECTIONS::UP_LEFT, 2, 49
moveDef DIRECTIONS::UP, 2, 1
moveDef DIRECTIONS::UP_RIGHT, 2, 42
MOVE_WARP 0, 357, DIRECTIONS::LEFT, 1018
moveDef DIRECTIONS::LEFT, 2, 200
moveDef DIRECTIONS::LEFT, 2, 148
MOVE_WARP 0, 432, DIRECTIONS::LEFT, 463
moveDef DIRECTIONS::LEFT, 2, 15
moveDef DIRECTIONS::UP_LEFT, 2, 113
moveDef DIRECTIONS::UP, 2, 1
moveDef DIRECTIONS::UP_RIGHT, 2, 15
OBJ_STOP
moveDef DIRECTIONS::UP_LEFT, 1, 167
moveDef DIRECTIONS::LEFT, 8, 242

TRAINPATH_REINDEER_SPOOKANE:
moveDef DIRECTIONS::RIGHT, 2, 168
OBJ_STOP
moveDef DIRECTIONS::UP_LEFT, 1, 167
moveDef DIRECTIONS::LEFT, 8, 250

TRAINPATH_REINDEER_SNOWMAN:
moveDef DIRECTIONS::RIGHT, 2, 203
MOVE_WARP 0, 10, DIRECTIONS::RIGHT, 522
moveDef DIRECTIONS::RIGHT, 2, 108
MOVE_WARP 0, 832, DIRECTIONS::DOWN_LEFT, 969
moveDef DIRECTIONS::DOWN_LEFT, 2, 8
moveDef DIRECTIONS::DOWN, 2, 1
moveDef DIRECTIONS::DOWN_RIGHT, 2, 13
moveDef DIRECTIONS::RIGHT, 2, 22
OBJ_STOP
moveDef DIRECTIONS::RIGHT, 1, 183
moveDef DIRECTIONS::LEFT, 8, 242

TRAINPATH_SPOOKANE_UNION:
moveDef DIRECTIONS::LEFT, 2, 244
moveDef DIRECTIONS::UP_LEFT, 2, 49
moveDef DIRECTIONS::UP, 2, 1
moveDef DIRECTIONS::UP_RIGHT, 2, 42
MOVE_WARP 0, 357, DIRECTIONS::LEFT, 1018
moveDef DIRECTIONS::LEFT, 2, 200
moveDef DIRECTIONS::LEFT, 2, 148
MOVE_WARP 0, 432, DIRECTIONS::LEFT, 463
moveDef DIRECTIONS::LEFT, 2, 15
moveDef DIRECTIONS::UP_LEFT, 2, 113
moveDef DIRECTIONS::UP, 2, 1
moveDef DIRECTIONS::UP_RIGHT, 2, 15
OBJ_STOP
moveDef DIRECTIONS::UP_LEFT, 1, 167
moveDef DIRECTIONS::LEFT, 8, 242

TRAINPATH_SPOOKANE_REINDEER:
moveDef DIRECTIONS::LEFT, 2, 168
OBJ_STOP
moveDef DIRECTIONS::UP_LEFT, 1, 155
moveDef DIRECTIONS::LEFT, 8, 242

TRAINPATH_SPOOKANE_SNOWMAN:
moveDef DIRECTIONS::RIGHT, 2, 35
MOVE_WARP 0, 10, DIRECTIONS::RIGHT, 522
moveDef DIRECTIONS::RIGHT, 2, 108
MOVE_WARP 0, 832, DIRECTIONS::DOWN_LEFT, 969
moveDef DIRECTIONS::DOWN_LEFT, 2, 8
moveDef DIRECTIONS::DOWN, 2, 1
moveDef DIRECTIONS::DOWN_RIGHT, 2, 13
moveDef DIRECTIONS::RIGHT, 2, 22
OBJ_STOP
moveDef DIRECTIONS::RIGHT, 1, 183
moveDef DIRECTIONS::LEFT, 8, 242

TRAINPATH_SNOWMAN_UNION:
moveDef DIRECTIONS::LEFT, 2, 22
moveDef DIRECTIONS::UP_LEFT, 2, 13
moveDef DIRECTIONS::UP, 2, 1
moveDef DIRECTIONS::UP_RIGHT, 2, 10
MOVE_WARP 0, 117, DIRECTIONS::LEFT, 522
moveDef DIRECTIONS::LEFT, 2, 108
MOVE_WARP 0, 720, DIRECTIONS::LEFT, 831
moveDef DIRECTIONS::LEFT, 2, 179
moveDef DIRECTIONS::LEFT, 2, 100
moveDef DIRECTIONS::UP_LEFT, 2, 49
moveDef DIRECTIONS::UP, 2, 1
moveDef DIRECTIONS::UP_RIGHT, 2, 42
MOVE_WARP 0, 357, DIRECTIONS::LEFT, 1018
moveDef DIRECTIONS::LEFT, 2, 200
moveDef DIRECTIONS::LEFT, 2, 148
MOVE_WARP 0, 432, DIRECTIONS::LEFT, 463
moveDef DIRECTIONS::LEFT, 2, 15
moveDef DIRECTIONS::UP_LEFT, 2, 113
moveDef DIRECTIONS::UP, 2, 1
moveDef DIRECTIONS::UP_RIGHT, 2, 15
OBJ_STOP
moveDef DIRECTIONS::UP_LEFT, 1, 167
moveDef DIRECTIONS::LEFT, 8, 242

TRAINPATH_SNOWMAN_REINDEER:
moveDef DIRECTIONS::LEFT, 2, 22
moveDef DIRECTIONS::UP_LEFT, 2, 13
moveDef DIRECTIONS::UP, 2, 1
moveDef DIRECTIONS::UP_RIGHT, 2, 10
MOVE_WARP 0, 117, DIRECTIONS::LEFT, 522
moveDef DIRECTIONS::LEFT, 2, 108
MOVE_WARP 0, 720, DIRECTIONS::LEFT, 831
moveDef DIRECTIONS::LEFT, 2, 203
OBJ_STOP
moveDef DIRECTIONS::UP_LEFT, 1, 155
moveDef DIRECTIONS::LEFT, 8, 242

TRAINPATH_SNOWMAN_SPOOKANE:
moveDef DIRECTIONS::LEFT, 2, 22
moveDef DIRECTIONS::UP_LEFT, 2, 13
moveDef DIRECTIONS::UP, 2, 1
moveDef DIRECTIONS::UP_RIGHT, 2, 10
MOVE_WARP 0, 117, DIRECTIONS::LEFT, 522
moveDef DIRECTIONS::LEFT, 2, 108
MOVE_WARP 0, 720, DIRECTIONS::LEFT, 831
moveDef DIRECTIONS::LEFT, 2, 36
OBJ_STOP
moveDef DIRECTIONS::UP_LEFT, 1, 167
moveDef DIRECTIONS::LEFT, 8, 250
