.ifndef VER_JP
OBJ_UNK2_OJSUBROUTINE2 := $8D31
OBJ_UNK2 := $8D09
.else
OBJ_UNK2_OJSUBROUTINE2 := $8C8B
OBJ_UNK2 := $8C63
.endif

OBJ_BANK_1B:
.addr OBJ_MYHOME_HOUSEEXIT
.addr OBJ_MYHOME_HOUSEUPSTAIRS
.addr OBJ_MYHOME_HOUSEBASEMENTENTRANCE
.addr OBJ_MYHOME_MIMMIEROOMEXIT
.addr OBJ_MYHOME_MINNIEROOMEXIT
.addr OBJ_REINDEER_HEALERHOUSEEXIT
.addr OBJ_PODUNK_HEALERHOUSEEXIT
.addr OBJ_SNOWMAN_HEALERHOUSEEXIT
.addr OBJ_REINDEER_MOUTHWASHHOUSEEXIT
.addr OBJ_MYHOME_MOM_INVASION
.addr OBJ_MYHOME_MOM
.addr OBJ_MYHOME_MINNIE_INVASION
.addr OBJ_MYHOME_MINNIE
.addr OBJ_MYHOME_MIMMIE
.addr OBJ_MYHOME_PHONE
.addr OBJ_MYHOME_DOLL_INVASION
.addr OBJ_MYHOME_DOLL
.addr OBJ_MYHOME_MINNIELAMP
.addr OBJ_MISLAY_MOUTHWASHGUY
.addr OBJ_MISLAY_MOUTHWASHKID
.addr OBJ_PODUNK_HEALER
.addr OBJ_REINDEER_HEALER
.addr OBJ_SNOWMAN_HEALER
.addr OBJ_PODUNK_HEALERPHONE
.addr OBJ_REINDEER_HEALERPHONE
.addr OBJ_SNOWMAN_HEALERPHONE
.addr OBJ_SWAMP_HOUSEEXIT
.addr OBJ_SWAMP_HOUSEPIPPI
.addr 0

OBJ_MYHOME_HOUSEEXIT:
objectDef OBJ_TYPE::DOOR, $2e, DIRECTIONS::RIGHT, $86
doorArgDef $6, $B1, DIRECTIONS::DOWN, $13C

OBJ_MYHOME_HOUSEUPSTAIRS:
objectDef OBJ_TYPE::STAIRS, $22, DIRECTIONS::LEFT, $85
doorArgDef $0, $22, DIRECTIONS::RIGHT, $E6

OBJ_MYHOME_HOUSEBASEMENTENTRANCE:
objectDef $18, $29, DIRECTIONS::UP, $83
.byte SCRIPTS::J_UNK, OBJ_THING2_JUNK0-OBJ_MYHOME_HOUSEBASEMENTENTRANCE
.byte SCRIPTS::IJ_USE, $55, OBJ_THING2_IJUSE1-OBJ_MYHOME_HOUSEBASEMENTENTRANCE
.byte SCRIPTS::DIALOGUE
.word UMSG::DOOR_UNLOCKED
.byte SCRIPTS::S_PLAYSOUND2, $8
.byte SCRIPTS::DA_TELEPORT
doorArgDef $11, $2FD, DIRECTIONS::LEFT, $86
.byte 0
      OBJ_THING2_IJUSE1:
.byte SCRIPTS::IJ_USE, $56, OBJ_THING2_IJUSE2-OBJ_MYHOME_HOUSEBASEMENTENTRANCE
.byte SCRIPTS::J_JUMP, OBJ_THING2J_JUMP3-OBJ_MYHOME_HOUSEBASEMENTENTRANCE
      OBJ_THING2_IJUSE2:
.byte SCRIPTS::IJ_USE, $57, OBJ_THING2_IJUSE4-OBJ_MYHOME_HOUSEBASEMENTENTRANCE
      OBJ_THING2J_JUMP3:
.byte SCRIPTS::DIALOGUE
.word UMSG::DOOR_KEYFAIL
      OBJ_THING2_IJUSE4:
.byte SCRIPTS::J_TOUCH, OBJ_THING2_JUNK0-OBJ_MYHOME_HOUSEBASEMENTENTRANCE
.byte SCRIPTS::DIALOGUE
.word UMSG::DOOR_LOCKED
      OBJ_THING2_JUNK0:
.byte 0

OBJ_MYHOME_MIMMIEROOMEXIT:
objectDef OBJ_TYPE::DOOR, $1ce, DIRECTIONS::RIGHT, $86
doorArgDef $0, $26, DIRECTIONS::DOWN, $E4

OBJ_MYHOME_MINNIEROOMEXIT:
objectDef OBJ_TYPE::DOOR, $27e, DIRECTIONS::RIGHT, $3f6
doorArgDef $0, $29, DIRECTIONS::DOWN, $E4

OBJ_REINDEER_HEALERHOUSEEXIT:
objectDef OBJ_TYPE::DOOR, $2e, DIRECTIONS::RIGHT, $a6
doorArgDef $6, $199, DIRECTIONS::DOWN, $338

OBJ_PODUNK_HEALERHOUSEEXIT:
objectDef OBJ_TYPE::DOOR, $e, DIRECTIONS::RIGHT, $c6
doorArgDef $6, $9D, DIRECTIONS::DOWN, $1F0

OBJ_SNOWMAN_HEALERHOUSEEXIT:
objectDef OBJ_TYPE::DOOR, $2e, DIRECTIONS::RIGHT, $106
doorArgDef $A, $381, DIRECTIONS::DOWN, $3D0

OBJ_REINDEER_MOUTHWASHHOUSEEXIT:
objectDef OBJ_TYPE::DOOR, $26e, DIRECTIONS::RIGHT, $86
doorArgDef $6, $160, DIRECTIONS::DOWN, $2CA

OBJ_MYHOME_MOM_INVASION:
objectDef OBJ_TYPE::STATIONARY_NPC_CHECKSPAWN, $2d, DIRECTIONS::LEFT, $86
.addr SPRITEDEF_172 ;sprite
.byte SCRIPTS::F_DISAPPEAR, $A
.byte SCRIPTS::J_TALK, OBJ_MYHOME_MOM_INVASION_JTALK0-OBJ_MYHOME_MOM_INVASION
.byte SCRIPTS::DIALOGUE
.word UMSG::MYHOME_MOM_INVASION
.byte SCRIPTS::FJ_JUMP, $40, OBJ_MYHOME_MOM_INVASION_FJJUMP1-OBJ_MYHOME_MOM_INVASION
.byte SCRIPTS::J_JUMP, OBJ_MYHOME_MOM_INVASIONJ_JUMP2-OBJ_MYHOME_MOM_INVASION
      OBJ_MYHOME_MOM_INVASION_FJJUMP1:
.byte SCRIPTS::M_MUSIC, $2F
.byte SCRIPTS::DIALOGUE
.word UMSG::MYHOME_MOM_INVASION2
.byte 0
      OBJ_MYHOME_MOM_INVASION_JTALK0:
.byte SCRIPTS::J_SIGNALED, OBJ_MYHOME_MOM_INVASIONJ_JUMP2-OBJ_MYHOME_MOM_INVASION
.byte SCRIPTS::M_MOVE
.addr OBJ_MYHOME_MOM_INVASION_MOVE0
.byte SCRIPTS::F_SETFLAG, $A
      OBJ_MYHOME_MOM_INVASIONJ_JUMP2:
.byte 0
        OBJ_MYHOME_MOM_INVASION_MOVE0:
moveDef DIRECTIONS::LEFT, MOVE_CMD::MOVEFACE, $4
moveDef DIRECTIONS::DOWN, MOVE_CMD::ABOUTFACE, $1
.byte 0

OBJ_MYHOME_MOM:
objectDef OBJ_TYPE::WANDERING_NPC_CHECKSPAWN, $29, DIRECTIONS::DOWN, $86
.addr SPRITEDEF_172 ;sprite
.byte SCRIPTS::F_APPEAR, $A
.byte SCRIPTS::J_TALK, OBJ_MYHOME_MOM_JTALK0-OBJ_MYHOME_MOM
.byte SCRIPTS::FJ_JUMP, $32, OBJ_MYHOME_MOM_FJJUMP1-OBJ_MYHOME_MOM
.byte SCRIPTS::C_SELECT, $1
.byte SCRIPTS::SJ_PRESENT, $80, OBJ_MYHOME_MOM_SJPRESENT2-OBJ_MYHOME_MOM
.byte SCRIPTS::NJ_BELOWLEVEL, $5, OBJ_MYHOME_MOM_NJBELOWLEVEL3-OBJ_MYHOME_MOM
.byte SCRIPTS::DIALOGUE
.word UMSG::MYHOME_MOM_HURT
.byte SCRIPTS::J_JUMP, OBJ_MYHOME_MOMJ_JUMP4-OBJ_MYHOME_MOM
      OBJ_MYHOME_MOM_NJBELOWLEVEL3:
.byte SCRIPTS::DIALOGUE
.word UMSG::MYHOME_MOM
      OBJ_MYHOME_MOMJ_JUMP4:
.byte SCRIPTS::DIALOGUE
.word UMSG::MYHOME_MOM_COOK
.byte SCRIPTS::SLEEP
.byte SCRIPTS::DIALOGUE
.word UMSG::MYHOME_MOM_EAT
.byte 0
      OBJ_MYHOME_MOM_SJPRESENT2:
.byte SCRIPTS::DIALOGUE
.word UMSG::MYHOME_MOM_HELP
.byte 0
      OBJ_MYHOME_MOM_FJJUMP1:
.byte SCRIPTS::DIALOGUE
.word UMSG::MYHOME_MOM_INVASION
      OBJ_MYHOME_MOM_JTALK0:
.byte 0

OBJ_MYHOME_MINNIE_INVASION:
objectDef OBJ_TYPE::WANDERING_NPC_CHECKSPAWN, $274, DIRECTIONS::RIGHT, $3f6
.addr SPRITEDEF_19F ;sprite
.byte SCRIPTS::F_DISAPPEAR, $32
.byte SCRIPTS::J_TALK, OBJ_MYHOME_MINNIE_INVASION_JTALK0-OBJ_MYHOME_MINNIE_INVASION
.byte SCRIPTS::FJ_JUMP, $25, OBJ_MYHOME_MINNIE_INVASION_FJJUMP1-OBJ_MYHOME_MINNIE_INVASION
.byte SCRIPTS::FJ_JUMP, $26, OBJ_MYHOME_MINNIE_INVASION_FJJUMP2-OBJ_MYHOME_MINNIE_INVASION
.byte SCRIPTS::DIALOGUE
.word UMSG::MYHOME_JUICE
.byte SCRIPTS::IJ_HASITEM, $0, OBJ_MYHOME_MINNIE_INVASION_IJHASITEM3-OBJ_MYHOME_MINNIE_INVASION
.byte SCRIPTS::S_PLAYSOUND, $6
.byte SCRIPTS::I_PICKITEM, $3C
.byte SCRIPTS::J_GIVEITEM, OBJ_MYHOME_MINNIE_INVASION_JTALK0-OBJ_MYHOME_MINNIE_INVASION
.byte 0
      OBJ_MYHOME_MINNIE_INVASION_IJHASITEM3:
.byte SCRIPTS::DIALOGUE
.word UMSG::PODUNK_PIPPI_NOROOM2
.byte 0
      OBJ_MYHOME_MINNIE_INVASION_FJJUMP2:
.byte SCRIPTS::DIALOGUE
.word UMSG::MYHOME_MINNIE_INVASION_FIGHT
.byte SCRIPTS::DIALOGUE
.word UMSG::MYHOME_MINNIE_INVASION_FIGHT_2
.byte 0
      OBJ_MYHOME_MINNIE_INVASION_FJJUMP1:
.byte SCRIPTS::DIALOGUE
.word UMSG::MYHOME_MINNIE_INVASION
      OBJ_MYHOME_MINNIE_INVASION_JTALK0:
.byte 0

OBJ_MYHOME_MINNIE:
objectDef OBJ_TYPE::WANDERING_NPC_CHECKSPAWN, $27, DIRECTIONS::DOWN, $85
.addr SPRITEDEF_19F ;sprite
.byte SCRIPTS::F_APPEAR, $32
.byte SCRIPTS::J_TALK, OBJ_MYHOME_MINNIE_JTALK0-OBJ_MYHOME_MINNIE
.byte SCRIPTS::DIALOGUE
.word UMSG::MYHOME_MINNIE
.byte SCRIPTS::DIALOGUE
.word UMSG::ELLAY_LHBOUNCERGIRL
.byte SCRIPTS::JJ_CUSTOMMENU
.word UMSG::MYHOME_MINNIE_STORAGE
.byte OBJ_MYHOME_MINNIE_JJCUSTOMMENU_21-OBJ_MYHOME_MINNIE,OBJ_MYHOME_MINNIE_JJCUSTOMMENU_B2-OBJ_MYHOME_MINNIE
      OBJ_MYHOME_MINNIEJ_JUMP7:
.byte SCRIPTS::J_NOITEMS, OBJ_MYHOME_MINNIE_JNOITEMS3-OBJ_MYHOME_MINNIE
.byte SCRIPTS::J_CHOOSEITEM, OBJ_MYHOME_MINNIE_JJCUSTOMMENU_B2-OBJ_MYHOME_MINNIE
.byte SCRIPTS::IJ_SELECTEDITEM, $3, OBJ_MYHOME_MINNIE_IJSELECTEDITEM4-OBJ_MYHOME_MINNIE
.byte SCRIPTS::J_JUMP, OBJ_MYHOME_MINNIEJ_JUMP5-OBJ_MYHOME_MINNIE
      OBJ_MYHOME_MINNIE_IJSELECTEDITEM4:
.byte SCRIPTS::J_ADDITEMCLOSET, OBJ_MYHOME_MINNIE_JADDITEMCLOSET6-OBJ_MYHOME_MINNIE
.byte SCRIPTS::S_PLAYSOUND, $6
.byte SCRIPTS::J_REMOVEITEM, OBJ_MYHOME_MINNIE_JTALK0-OBJ_MYHOME_MINNIE
.byte SCRIPTS::DIALOGUE
.word UMSG::MYHOME_MINNIE_STORAGE_STASH
.byte SCRIPTS::J_YESNO, OBJ_MYHOME_MINNIE_JJCUSTOMMENU_B2-OBJ_MYHOME_MINNIE
.byte SCRIPTS::J_JUMP, OBJ_MYHOME_MINNIEJ_JUMP7-OBJ_MYHOME_MINNIE
      OBJ_MYHOME_MINNIE_JJCUSTOMMENU_21:
.byte SCRIPTS::J_NOITEMSCLOSET, OBJ_MYHOME_MINNIE_JNOITEMSCLOSET8-OBJ_MYHOME_MINNIE
.byte SCRIPTS::J_CHOOSEITEMCLOSET, OBJ_MYHOME_MINNIE_JJCUSTOMMENU_B2-OBJ_MYHOME_MINNIE
.byte SCRIPTS::C_SELECT, $1
.byte SCRIPTS::CJ_SELECTPARTY, $1, OBJ_MYHOME_MINNIE_CJSELECTPARTY9-OBJ_MYHOME_MINNIE
      OBJ_MYHOME_MINNIEJ_JUMP12:
.byte SCRIPTS::J_CHOOSECHAR, OBJ_MYHOME_MINNIE_JJCUSTOMMENU_B2-OBJ_MYHOME_MINNIE
      OBJ_MYHOME_MINNIE_CJSELECTPARTY9:
.byte SCRIPTS::J_GIVEITEM, OBJ_MYHOME_MINNIE_JGIVEITEM10-OBJ_MYHOME_MINNIE
.byte SCRIPTS::S_PLAYSOUND, $6
.byte SCRIPTS::J_TAKEITEMCLOSET, OBJ_MYHOME_MINNIE_JTALK0-OBJ_MYHOME_MINNIE
.byte SCRIPTS::DIALOGUE
.word UMSG::MYHOME_MINNIE_STORAGE_TAKE
.byte SCRIPTS::J_YESNO, OBJ_MYHOME_MINNIE_JJCUSTOMMENU_B2-OBJ_MYHOME_MINNIE
.byte SCRIPTS::J_JUMP, OBJ_MYHOME_MINNIE_JJCUSTOMMENU_21-OBJ_MYHOME_MINNIE
      OBJ_MYHOME_MINNIE_JGIVEITEM10:
.byte SCRIPTS::CJ_SELECTPARTY, $1, OBJ_MYHOME_MINNIE_CJSELECTPARTY11-OBJ_MYHOME_MINNIE
.byte SCRIPTS::DIALOGUE
.word UMSG::MYHOME_MINNIE_STORAGE_INVFULL
.byte SCRIPTS::J_YESNO, OBJ_MYHOME_MINNIE_JJCUSTOMMENU_B2-OBJ_MYHOME_MINNIE
.byte SCRIPTS::J_JUMP, OBJ_MYHOME_MINNIEJ_JUMP12-OBJ_MYHOME_MINNIE
      OBJ_MYHOME_MINNIE_CJSELECTPARTY11:
.byte SCRIPTS::DIALOGUE
.word UMSG::PODUNK_PIPPI_NOROOM2
.byte 0
      OBJ_MYHOME_MINNIE_JADDITEMCLOSET6:
.byte SCRIPTS::DIALOGUE
.word UMSG::MYHOME_MINNIE_STORAGE_FULL
.byte 0
      OBJ_MYHOME_MINNIEJ_JUMP5:
.byte SCRIPTS::DIALOGUE
.word UMSG::MYHOME_MINNIE_STORAGE_CANT
.byte 0
      OBJ_MYHOME_MINNIE_JJCUSTOMMENU_B2:
.byte SCRIPTS::DIALOGUE
.word UMSG::MYHOME_MINNIE_STORAGE_BYE
.byte 0
      OBJ_MYHOME_MINNIE_JNOITEMS3:
.byte SCRIPTS::DIALOGUE
.word UMSG::MYHOME_MINNIE_STORAGE_INVNOTHING
.byte 0
      OBJ_MYHOME_MINNIE_JNOITEMSCLOSET8:
.byte SCRIPTS::DIALOGUE
.word UMSG::MYHOME_MINNIE_STORAGE_NOTHING
      OBJ_MYHOME_MINNIE_JTALK0:
.byte 0

OBJ_MYHOME_MIMMIE:
objectDef OBJ_TYPE::WANDERING_NPC, $1cb, DIRECTIONS::RIGHT, $86
.addr SPRITEDEF_18B ;sprite
.byte SCRIPTS::J_TALK, OBJ_MYHOME_MIMMIE_JTALK0-OBJ_MYHOME_MIMMIE
.byte SCRIPTS::FJ_JUMP, $26, OBJ_MYHOME_MIMMIE_FJJUMP1-OBJ_MYHOME_MIMMIE
.byte SCRIPTS::FJ_JUMP, $F7, OBJ_MYHOME_MIMMIE_FJJUMP2-OBJ_MYHOME_MIMMIE
.byte SCRIPTS::FJ_JUMP, $32, OBJ_MYHOME_MIMMIE_FJJUMP3-OBJ_MYHOME_MIMMIE
.byte SCRIPTS::DIALOGUE
.word UMSG::MYHOME_MIMMIE
.byte 0
      OBJ_MYHOME_MIMMIE_FJJUMP3:
.byte SCRIPTS::DIALOGUE
.word UMSG::MYHOME_JUICE
.byte SCRIPTS::IJ_HASITEM, $0, OBJ_MYHOME_MIMMIE_IJHASITEM4-OBJ_MYHOME_MIMMIE
.byte SCRIPTS::S_PLAYSOUND, $6
.byte SCRIPTS::I_PICKITEM, $3C
.byte SCRIPTS::J_GIVEITEM, OBJ_MYHOME_MIMMIE_JTALK0-OBJ_MYHOME_MIMMIE
.byte 0
      OBJ_MYHOME_MIMMIE_IJHASITEM4:
.byte SCRIPTS::DIALOGUE
.word UMSG::PODUNK_PIPPI_NOROOM2
.byte 0
      OBJ_MYHOME_MIMMIE_FJJUMP2:
.byte SCRIPTS::DIALOGUE
.word UMSG::MYHOME_MIMMIE_INVASION_FIGHT
.byte 0
      OBJ_MYHOME_MIMMIE_FJJUMP1:
.byte SCRIPTS::DIALOGUE
.word UMSG::MYHOME_MIMMIE_INVASION2
      OBJ_MYHOME_MIMMIE_JTALK0:
.byte 0

OBJ_MYHOME_PHONE:
objectDef $19, $2b, DIRECTIONS::UP, $84
.addr SPRITEDEF_19C ;sprite
.byte SCRIPTS::J_TALK, OBJ_MYHOME_PHONE_JTALK0-OBJ_MYHOME_PHONE
.byte SCRIPTS::DIALOGUE
.word UMSG::PHONE_GRAB
.byte SCRIPTS::FJ_JUMP, $26, OBJ_MYHOME_PHONE_FJJUMP1-OBJ_MYHOME_PHONE
.byte SCRIPTS::M_MUSIC, $12
.byte SCRIPTS::J_JUMP, OBJ_MYHOME_PHONEJ_JUMP2-OBJ_MYHOME_PHONE
      OBJ_MYHOME_PHONE_FJJUMP1:
.byte SCRIPTS::M_MUSIC, $10
      OBJ_MYHOME_PHONEJ_JUMP2:
.byte SCRIPTS::FJ_JUMP, $40, OBJ_MYHOME_PHONE_FJJUMP3-OBJ_MYHOME_PHONE
.byte SCRIPTS::DIALOGUE
.word UMSG::PHONE_INTRO
.byte SCRIPTS::J_NONEWMONEY, OBJ_MYHOME_PHONE_JNONEWMONEY4-OBJ_MYHOME_PHONE
.byte SCRIPTS::DIALOGUE
.word UMSG::PHONE_NEWMONEY
      OBJ_MYHOME_PHONE_JNONEWMONEY4:
.byte SCRIPTS::DIALOGUE
.word UMSG::PHONE_NEXTLVL
.byte SCRIPTS::CJ_SELECTPARTY, $0, OBJ_MYHOME_PHONE_CJSELECTPARTY5-OBJ_MYHOME_PHONE
.byte SCRIPTS::GETCHARNEXTEXP
.byte SCRIPTS::DIALOGUE
.word UMSG::PHONE_EXPLVL
.byte SCRIPTS::CJ_SELECTPARTY, $1, OBJ_MYHOME_PHONE_CJSELECTPARTY5-OBJ_MYHOME_PHONE
.byte SCRIPTS::GETCHARNEXTEXP
.byte SCRIPTS::DIALOGUE
.word UMSG::PHONE_EXPLVL
.byte SCRIPTS::CJ_SELECTPARTY, $2, OBJ_MYHOME_PHONE_CJSELECTPARTY5-OBJ_MYHOME_PHONE
.byte SCRIPTS::GETCHARNEXTEXP
.byte SCRIPTS::DIALOGUE
.word UMSG::PHONE_EXPLVL
      OBJ_MYHOME_PHONE_CJSELECTPARTY5:
.byte SCRIPTS::DIALOGUE
.word UMSG::PHONE_SAVEPROMPT
.byte SCRIPTS::JJ_CUSTOMMENU
.word UMSG::MENU_YES_NO
.byte OBJ_MYHOME_PHONE_JJCUSTOMMENU_26-OBJ_MYHOME_PHONE,OBJ_MYHOME_PHONE_JJCUSTOMMENU_26-OBJ_MYHOME_PHONE
.byte SCRIPTS::SAVE
.byte SCRIPTS::DIALOGUE
.word UMSG::PHONE_SAVED_RESETPROMPT
.byte SCRIPTS::JJ_CUSTOMMENU
.word UMSG::MENU_CONTINUE_REST
.byte OBJ_MYHOME_PHONE_JJCUSTOMMENU_27-OBJ_MYHOME_PHONE,OBJ_MYHOME_PHONE_JJCUSTOMMENU_B8-OBJ_MYHOME_PHONE
      OBJ_MYHOME_PHONE_JJCUSTOMMENU_B8:
.byte SCRIPTS::DIALOGUE
.word UMSG::PHONE_RESET_NO
.byte SCRIPTS::DIALOGUE
.word UMSG::PHONE_END
.byte 0
      OBJ_MYHOME_PHONE_JJCUSTOMMENU_27:
.byte SCRIPTS::DIALOGUE
.word UMSG::PHONE_RESET_YES
.byte SCRIPTS::DIALOGUE
.word UMSG::PHONE_END
.byte SCRIPTS::RESET
      OBJ_MYHOME_PHONE_JJCUSTOMMENU_26:
.byte SCRIPTS::DIALOGUE
.word UMSG::PHONE_GOODLUCK
.byte SCRIPTS::DIALOGUE
.word UMSG::PHONE_END
.byte 0
      OBJ_MYHOME_PHONE_FJJUMP3:
.byte SCRIPTS::DIALOGUE
.word UMSG::PHONE_INTRO
.byte SCRIPTS::DIALOGUE
.word UMSG::MYHOME_PHONE
.byte SCRIPTS::DIALOGUE
.word UMSG::PHONE_END
.byte SCRIPTS::F_SETFLAG, $40
.byte SCRIPTS::FJ_JUMP, $26, OBJ_MYHOME_PHONE_JTALK0-OBJ_MYHOME_PHONE
.byte SCRIPTS::O_SIGNAL, $9
      OBJ_MYHOME_PHONE_JTALK0:
.byte 0

OBJ_MYHOME_DOLL_INVASION:
objectDef $27, $1c6, DIRECTIONS::UP, $87
.addr SPRITEDEF_19B ;sprite
.byte SCRIPTS::F_DISAPPEAR, $26
.byte SCRIPTS::J_TOUCH, OBJ_MYHOME_DOLL_INVASION_JTOUCH0-OBJ_MYHOME_DOLL_INVASION
.byte SCRIPTS::J_JUMP, OBJ_MYHOME_DOLL_INVASIONJ_JUMP1-OBJ_MYHOME_DOLL_INVASION
      OBJ_MYHOME_DOLL_INVASION_JTOUCH0:
.byte SCRIPTS::J_CHECK, OBJ_MYHOME_DOLL_INVASION_JCHECK2-OBJ_MYHOME_DOLL_INVASION
.byte SCRIPTS::DIALOGUE
.word UMSG::CANARY_PILLAR
      OBJ_MYHOME_DOLL_INVASIONJ_JUMP1:
.byte SCRIPTS::F_CLEARFLAG, $F8
.byte SCRIPTS::F_CLEARFLAG, $30
.byte SCRIPTS::B_BATTLE, $9F
.byte SCRIPTS::F_SETFLAG, $30
.byte SCRIPTS::F_SETFLAG, $26
.byte SCRIPTS::F_SETFLAG, $25
.byte SCRIPTS::M_MUSIC, $12
.byte SCRIPTS::M_MOVE
.addr OBJ_MYHOME_DOLL_INVASION_MOVE0
.byte SCRIPTS::DIALOGUE
.word UMSG::MYHOME_INVASION
.byte SCRIPTS::FJ_JUMP, $40, OBJ_MYHOME_DOLL_INVASION_FJJUMP3-OBJ_MYHOME_DOLL_INVASION
.byte SCRIPTS::F_SETFLAG, $A
      OBJ_MYHOME_DOLL_INVASION_FJJUMP3:
.byte SCRIPTS::M_MOVE
.addr OBJ_MYHOME_DOLL_INVASION_MOVE1
      OBJ_MYHOME_DOLL_INVASION_JCHECK2:
.byte 0
        OBJ_MYHOME_DOLL_INVASION_MOVE0:
moveDef DIRECTIONS::UP, $A, $1
.byte 3
        OBJ_MYHOME_DOLL_INVASION_MOVE1:
.byte 0

OBJ_MYHOME_DOLL:
objectDef $1d, $1ca, DIRECTIONS::UP, $83
.addr SPRITEDEF_19B ;sprite
.byte SCRIPTS::F_APPEAR, $26
.byte SCRIPTS::J_CHECK, OBJ_MYHOME_DOLL_JCHECK0-OBJ_MYHOME_DOLL
.byte SCRIPTS::DIALOGUE
.word UMSG::MYHOME_DOLL
.byte SCRIPTS::M_MUSIC, $24
.byte SCRIPTS::T_DELAY, $F0
.byte SCRIPTS::M_MUSIC, $12
.byte SCRIPTS::F_SETFLAG, $F7
.byte SCRIPTS::DIALOGUE
.word UMSG::REMEMBER_MELODY
.ifdef VER_JP
.byte $65
.endif
      OBJ_MYHOME_DOLL_JCHECK0:
.byte 0

OBJ_MYHOME_MINNIELAMP:
objectDef $27, $279, DIRECTIONS::UP, $3f5
.addr SPRITEDEF_19D ;sprite
.byte SCRIPTS::F_DISAPPEAR, $25
.byte SCRIPTS::J_TOUCH, OBJ_MYHOME_MINNIELAMP_JTOUCH0-OBJ_MYHOME_MINNIELAMP
.byte SCRIPTS::J_JUMP, OBJ_MYHOME_MINNIELAMPJ_JUMP1-OBJ_MYHOME_MINNIELAMP
      OBJ_MYHOME_MINNIELAMP_JTOUCH0:
.byte SCRIPTS::J_CHECK, OBJ_MYHOME_MINNIELAMP_JCHECK2-OBJ_MYHOME_MINNIELAMP
.byte SCRIPTS::DIALOGUE
.word UMSG::CANARY_PILLAR
      OBJ_MYHOME_MINNIELAMPJ_JUMP1:
.byte SCRIPTS::M_MOVE
.addr OBJ_MYHOME_MINNIELAMP_MOVE0
.byte SCRIPTS::F_CLEARFLAG, $F8
.byte SCRIPTS::F_CLEARFLAG, $30
.byte SCRIPTS::B_BATTLE, $A0
.byte SCRIPTS::F_SETFLAG, $F8
.byte SCRIPTS::F_SETFLAG, $30
.byte SCRIPTS::F_SETFLAG, $25
.byte SCRIPTS::M_MOVE
.addr OBJ_MYHOME_MINNIELAMP_MOVE1
      OBJ_MYHOME_MINNIELAMP_JCHECK2:
.byte 0
        OBJ_MYHOME_MINNIELAMP_MOVE0:
moveDef DIRECTIONS::UP, MOVE_CMD::ABOUTFACE, $1
.byte 3
        OBJ_MYHOME_MINNIELAMP_MOVE1:
.byte 0

OBJ_MISLAY_MOUTHWASHGUY:
objectDef OBJ_TYPE::STATIONARY_NPC, $265, DIRECTIONS::DOWN, $86
.addr SPRITEDEF_183 ;sprite
.byte SCRIPTS::J_TALK, OBJ_MISLAY_MOUTHWASHGUY_JTALK0-OBJ_MISLAY_MOUTHWASHGUY
.byte SCRIPTS::FJ_JUMP, $41, OBJ_MISLAY_MOUTHWASHGUY_FJJUMP1-OBJ_MISLAY_MOUTHWASHGUY
.byte SCRIPTS::DIALOGUE
.word UMSG::MISLAY_MOUTHWASHGUY_LEAVE
.byte 0
      OBJ_MISLAY_MOUTHWASHGUY_FJJUMP1:
.byte SCRIPTS::DIALOGUE
.word UMSG::MISLAY_MOUTHWASHGUY_DENTURELESS
.byte 0
      OBJ_MISLAY_MOUTHWASHGUY_JTALK0:
.byte SCRIPTS::IJ_USE, $63, OBJ_MISLAY_MOUTHWASHGUY_IJUSE2-OBJ_MISLAY_MOUTHWASHGUY
.byte SCRIPTS::I_PICKITEM, $63
.byte SCRIPTS::J_REMOVEITEM, OBJ_MISLAY_MOUTHWASHGUY_JREMOVEITEM3-OBJ_MISLAY_MOUTHWASHGUY
.byte SCRIPTS::DIALOGUE
.word UMSG::MISLAY_MOUTHWASHGUY_DENTURES
      OBJ_MISLAY_MOUTHWASHGUYJ_JUMP6:
.byte SCRIPTS::I_PICKITEM, $44
.byte SCRIPTS::S_PLAYSOUND, $6
.byte SCRIPTS::J_GIVEITEM, OBJ_MISLAY_MOUTHWASHGUY_JGIVEITEM4-OBJ_MISLAY_MOUTHWASHGUY
.byte SCRIPTS::T_DELAY, $28
.byte SCRIPTS::IJ_HASITEM, $0, OBJ_MISLAY_MOUTHWASHGUY_IJHASITEM5-OBJ_MISLAY_MOUTHWASHGUY
.byte SCRIPTS::J_JUMP, OBJ_MISLAY_MOUTHWASHGUYJ_JUMP6-OBJ_MISLAY_MOUTHWASHGUY
      OBJ_MISLAY_MOUTHWASHGUY_IJHASITEM5:
.byte SCRIPTS::F_SETFLAG, $41
.byte 0
      OBJ_MISLAY_MOUTHWASHGUY_JGIVEITEM4:
.byte SCRIPTS::DIALOGUE
.word UMSG::MISLAY_MOUTHWASHGUY_DENTURELESS
.byte 0
      OBJ_MISLAY_MOUTHWASHGUY_IJUSE2:
.byte SCRIPTS::PJ_USE, $1, OBJ_MISLAY_MOUTHWASHGUY_JREMOVEITEM3-OBJ_MISLAY_MOUTHWASHGUY
.byte SCRIPTS::DIALOGUE
.word UMSG::MISLAY_MOUTHWASHGUY_DENTURES2
      OBJ_MISLAY_MOUTHWASHGUY_JREMOVEITEM3:
.byte 0

OBJ_MISLAY_MOUTHWASHKID:
objectDef OBJ_TYPE::WANDERING_NPC, $269, DIRECTIONS::RIGHT, $86
.addr SPRITEDEF_C2 ;sprite
.byte SCRIPTS::J_TALK, OBJ_MISLAY_MOUTHWASHKID_JTALK0-OBJ_MISLAY_MOUTHWASHKID
.byte SCRIPTS::FJ_JUMP, $41, OBJ_MISLAY_MOUTHWASHKID_FJJUMP1-OBJ_MISLAY_MOUTHWASHKID
.byte SCRIPTS::N_LOADNUMBER
.word 10
.byte SCRIPTS::DIALOGUE
.word UMSG::MISLAY_MOUTHWASHKID_TAKE
.byte SCRIPTS::J_YESNO, OBJ_MISLAY_MOUTHWASHKID_JYESNO2-OBJ_MISLAY_MOUTHWASHKID
.byte SCRIPTS::IJ_HASITEM, $0, OBJ_MISLAY_MOUTHWASHKID_IJHASITEM3-OBJ_MISLAY_MOUTHWASHKID
.byte SCRIPTS::I_PICKITEM, $44
.byte SCRIPTS::N_LOADNUMBER
.word 10
.byte SCRIPTS::J_TAKEMONEY, OBJ_MISLAY_MOUTHWASHKID_JTAKEMONEY4-OBJ_MISLAY_MOUTHWASHKID
.byte SCRIPTS::S_PLAYSOUND, $6
.byte SCRIPTS::I_PICKITEM, $44
.byte SCRIPTS::J_GIVEITEM, OBJ_MISLAY_MOUTHWASHKID_JTALK0-OBJ_MISLAY_MOUTHWASHKID
.byte 0
      OBJ_MISLAY_MOUTHWASHKID_JTAKEMONEY4:
.byte SCRIPTS::DIALOGUE
.word UMSG::MISLAY_MOUTHWASHKID_NOMONEY
.byte 0
      OBJ_MISLAY_MOUTHWASHKID_IJHASITEM3:
.byte SCRIPTS::DIALOGUE
.word UMSG::MERRYSVILLE_QUESTIONNAIRE_NOROOM
.byte 0
      OBJ_MISLAY_MOUTHWASHKID_JYESNO2:
.byte SCRIPTS::DIALOGUE
.word UMSG::MISLAY_MOUTHWASHKID_NOTAKE
.byte 0
      OBJ_MISLAY_MOUTHWASHKID_FJJUMP1:
.byte SCRIPTS::DIALOGUE
.word UMSG::MISLAY_MOUTHWASHKID
      OBJ_MISLAY_MOUTHWASHKID_JTALK0:
.byte 0

OBJ_PODUNK_HEALER:
objectDef OBJ_TYPE::WANDERING_NPC, $4, DIRECTIONS::RIGHT, $c4
.addr SPRITEDEF_183 ;sprite
.byte SCRIPTS::N_LOADNUMBER
.word 30
.byte SCRIPTS::OJ_SUBROUTINE
.addr OBJ_PODUNK_HEALER
.byte OBJ_PODUNK_HEALER_OJSUBROUTINE0-OBJ_PODUNK_HEALER
.byte 0
      OBJ_PODUNK_HEALER_OJSUBROUTINE0:
.byte SCRIPTS::J_TALK, OBJ_PODUNK_HEALER_JTALK0-OBJ_PODUNK_HEALER
.byte SCRIPTS::DIALOGUE
.word UMSG::HEALER
.byte SCRIPTS::JJ_CUSTOMMENU
.word UMSG::HEALER_MENU
.byte OBJ_PODUNK_HEALER_JJCUSTOMMENU_21-OBJ_PODUNK_HEALER,OBJ_PODUNK_HEALER_JJCUSTOMMENU_B2-OBJ_PODUNK_HEALER
.byte SCRIPTS::N_MULNUMBER, 60
.byte SCRIPTS::DIALOGUE
.word UMSG::HEALER_PRICE
.byte SCRIPTS::J_YESNO, OBJ_PODUNK_HEALER_JJCUSTOMMENU_B2-OBJ_PODUNK_HEALER
.byte SCRIPTS::J_TAKEMONEY, OBJ_PODUNK_HEALER_JTAKEMONEY3-OBJ_PODUNK_HEALER
.byte SCRIPTS::CJ_SELECTPARTY, $1, OBJ_PODUNK_HEALER_CJSELECTPARTY4-OBJ_PODUNK_HEALER
.byte SCRIPTS::J_CHOOSECHAR, OBJ_PODUNK_HEALER_JCHOOSECHAR5-OBJ_PODUNK_HEALER
.byte SCRIPTS::J_JUMP, OBJ_PODUNK_HEALERJ_JUMP6-OBJ_PODUNK_HEALER
      OBJ_PODUNK_HEALER_CJSELECTPARTY4:
.byte SCRIPTS::CJ_SELECTPARTY, $0, OBJ_PODUNK_HEALER_JTALK0-OBJ_PODUNK_HEALER
      OBJ_PODUNK_HEALERJ_JUMP6:
.byte SCRIPTS::SJ_PRESENT, $80, OBJ_PODUNK_HEALER_SJPRESENT7-OBJ_PODUNK_HEALER
.byte SCRIPTS::J_NOTMAXPP, OBJ_PODUNK_HEALER_JNOTMAXPP8-OBJ_PODUNK_HEALER
.byte SCRIPTS::J_GIVEMONEY, OBJ_PODUNK_HEALER_JTALK0-OBJ_PODUNK_HEALER
.byte SCRIPTS::DIALOGUE
.word UMSG::PODUNK_HOSPITALDOCTOR_NORMAL
.byte SCRIPTS::RETURN
      OBJ_PODUNK_HEALER_JNOTMAXPP8:
.byte SCRIPTS::N_HEALPP, $FF
.byte SCRIPTS::J_NOTMAXPP, OBJ_PODUNK_HEALER_JNOTMAXPP8-OBJ_PODUNK_HEALER
.byte SCRIPTS::DIALOGUE
.word UMSG::HEALER_FIXED
.byte SCRIPTS::S_PLAYSOUND, $7
.byte SCRIPTS::RETURN
      OBJ_PODUNK_HEALER_JJCUSTOMMENU_21:
.byte SCRIPTS::DIALOGUE
.word UMSG::HEALER_PRICE
.byte SCRIPTS::J_YESNO, OBJ_PODUNK_HEALER_JJCUSTOMMENU_B2-OBJ_PODUNK_HEALER
.byte SCRIPTS::J_TAKEMONEY, OBJ_PODUNK_HEALER_JTAKEMONEY3-OBJ_PODUNK_HEALER
.byte SCRIPTS::CJ_SELECTPARTY, $1, OBJ_PODUNK_HEALER_CJSELECTPARTY9-OBJ_PODUNK_HEALER
.byte SCRIPTS::DIALOGUE
.word UMSG::HEALER_WHO
.byte SCRIPTS::J_CHOOSECHAR, OBJ_PODUNK_HEALER_JCHOOSECHAR5-OBJ_PODUNK_HEALER
.byte SCRIPTS::J_JUMP, OBJ_PODUNK_HEALERJ_JUMP10-OBJ_PODUNK_HEALER
      OBJ_PODUNK_HEALER_CJSELECTPARTY9:
.byte SCRIPTS::CJ_SELECTPARTY, $0, OBJ_PODUNK_HEALER_JTALK0-OBJ_PODUNK_HEALER
      OBJ_PODUNK_HEALERJ_JUMP10:
.byte SCRIPTS::SJ_PRESENT, $80, OBJ_PODUNK_HEALER_SJPRESENT7-OBJ_PODUNK_HEALER
.byte SCRIPTS::SJ_PRESENT, $40, OBJ_PODUNK_HEALER_SJPRESENT11-OBJ_PODUNK_HEALER
.byte SCRIPTS::J_GIVEMONEY, OBJ_PODUNK_HEALER_JTALK0-OBJ_PODUNK_HEALER
.byte SCRIPTS::DIALOGUE
.word UMSG::HEALER_SOFTEN_FAIL
.byte SCRIPTS::RETURN
      OBJ_PODUNK_HEALER_SJPRESENT11:
.byte SCRIPTS::DIALOGUE
.word UMSG::HEALER_FIXED
.byte SCRIPTS::S_PLAYSOUND, $7
.byte SCRIPTS::S_REMOVEBUT, $BF
.byte SCRIPTS::RETURN
      OBJ_PODUNK_HEALER_JCHOOSECHAR5:
.byte SCRIPTS::J_GIVEMONEY, OBJ_PODUNK_HEALER_JTALK0-OBJ_PODUNK_HEALER
      OBJ_PODUNK_HEALER_JJCUSTOMMENU_B2:
.byte SCRIPTS::DIALOGUE
.word UMSG::HEALER_NO
.byte SCRIPTS::RETURN
      OBJ_PODUNK_HEALER_JTAKEMONEY3:
.byte SCRIPTS::DIALOGUE
.word UMSG::HEALER_BROKE
.byte SCRIPTS::RETURN
      OBJ_PODUNK_HEALER_SJPRESENT7:
.byte SCRIPTS::J_GIVEMONEY, OBJ_PODUNK_HEALER_JTALK0-OBJ_PODUNK_HEALER
.byte SCRIPTS::DIALOGUE
.word UMSG::HEALER_MAN
      OBJ_PODUNK_HEALER_JTALK0:
.byte SCRIPTS::RETURN

OBJ_REINDEER_HEALER:
objectDef OBJ_TYPE::WANDERING_NPC, $24, DIRECTIONS::RIGHT, $a4
.addr SPRITEDEF_183 ;sprite
.byte SCRIPTS::N_LOADNUMBER
.word 75
.byte SCRIPTS::OJ_SUBROUTINE

;jp is a normal healer
.ifdef VER_JP
.addr OBJ_PODUNK_HEALER
.byte OBJ_PODUNK_HEALER_OJSUBROUTINE0-OBJ_PODUNK_HEALER
.byte 0
.else
.addr OBJ_REINDEER_HEALER
.byte OBJ_REINDEER_HEALER_OJSUBROUTINE1-OBJ_REINDEER_HEALER
.byte 0
      OBJ_REINDEER_HEALER_OJSUBROUTINE1:
.byte SCRIPTS::J_TALK, OBJ_REINDEER_HEALER_JTALK0-OBJ_REINDEER_HEALER
.byte SCRIPTS::DIALOGUE
.word UMSG::HEALER_INTRO
.byte SCRIPTS::JJ_CUSTOMMENU
.word UMSG::HEALER_MENU
.byte OBJ_REINDEER_HEALER_JJCUSTOMMENU_21-OBJ_REINDEER_HEALER,OBJ_REINDEER_HEALER_JJCUSTOMMENU_B2-OBJ_REINDEER_HEALER
.byte SCRIPTS::N_MULNUMBER, 60
.byte SCRIPTS::DIALOGUE
.word UMSG::HEALER_PRICE
.byte SCRIPTS::J_YESNO, OBJ_REINDEER_HEALER_JJCUSTOMMENU_B2-OBJ_REINDEER_HEALER
.byte SCRIPTS::J_TAKEMONEY, OBJ_REINDEER_HEALER_JTAKEMONEY3-OBJ_REINDEER_HEALER
.byte SCRIPTS::CJ_SELECTPARTY, $1, OBJ_REINDEER_HEALER_CJSELECTPARTY4-OBJ_REINDEER_HEALER
.byte SCRIPTS::J_CHOOSECHAR, OBJ_REINDEER_HEALER_JCHOOSECHAR5-OBJ_REINDEER_HEALER
.byte SCRIPTS::J_JUMP, OBJ_REINDEER_HEALERJ_JUMP6-OBJ_REINDEER_HEALER
      OBJ_REINDEER_HEALER_CJSELECTPARTY4:
.byte SCRIPTS::CJ_SELECTPARTY, $0, OBJ_REINDEER_HEALER_JTALK0-OBJ_REINDEER_HEALER
      OBJ_REINDEER_HEALERJ_JUMP6:
.byte SCRIPTS::SJ_PRESENT, $80, OBJ_REINDEER_HEALER_SJPRESENT7-OBJ_REINDEER_HEALER
.byte SCRIPTS::J_NOTMAXPP, OBJ_REINDEER_HEALER_JNOTMAXPP8-OBJ_REINDEER_HEALER
.byte SCRIPTS::J_GIVEMONEY, OBJ_REINDEER_HEALER_JTALK0-OBJ_REINDEER_HEALER
.byte SCRIPTS::DIALOGUE
.word UMSG::PODUNK_HOSPITALDOCTOR_NORMAL
.byte SCRIPTS::RETURN
      OBJ_REINDEER_HEALER_JNOTMAXPP8:
.byte SCRIPTS::N_HEALPP, $FF
.byte SCRIPTS::J_NOTMAXPP, OBJ_REINDEER_HEALER_JNOTMAXPP8-OBJ_REINDEER_HEALER
.byte SCRIPTS::DIALOGUE
.word UMSG::HEALER_FIXED
.byte SCRIPTS::S_PLAYSOUND, $7
.byte SCRIPTS::RETURN
      OBJ_REINDEER_HEALER_JJCUSTOMMENU_21:
.byte SCRIPTS::DIALOGUE
.word UMSG::HEALER_PRICE
.byte SCRIPTS::J_YESNO, OBJ_REINDEER_HEALER_JJCUSTOMMENU_B2-OBJ_REINDEER_HEALER
.byte SCRIPTS::J_TAKEMONEY, OBJ_REINDEER_HEALER_JTAKEMONEY3-OBJ_REINDEER_HEALER
.byte SCRIPTS::CJ_SELECTPARTY, $1, OBJ_REINDEER_HEALER_CJSELECTPARTY9-OBJ_REINDEER_HEALER
.byte SCRIPTS::DIALOGUE
.word UMSG::HEALER_WHO
.byte SCRIPTS::J_CHOOSECHAR, OBJ_REINDEER_HEALER_JCHOOSECHAR5-OBJ_REINDEER_HEALER
.byte SCRIPTS::J_JUMP, OBJ_REINDEER_HEALERJ_JUMP10-OBJ_REINDEER_HEALER
      OBJ_REINDEER_HEALER_CJSELECTPARTY9:
.byte SCRIPTS::CJ_SELECTPARTY, $0, OBJ_REINDEER_HEALER_JTALK0-OBJ_REINDEER_HEALER
      OBJ_REINDEER_HEALERJ_JUMP10:
.byte SCRIPTS::SJ_PRESENT, $80, OBJ_REINDEER_HEALER_SJPRESENT7-OBJ_REINDEER_HEALER
.byte SCRIPTS::SJ_PRESENT, $40, OBJ_REINDEER_HEALER_SJPRESENT11-OBJ_REINDEER_HEALER
.byte SCRIPTS::J_GIVEMONEY, OBJ_REINDEER_HEALER_JTALK0-OBJ_REINDEER_HEALER
.byte SCRIPTS::DIALOGUE
.word UMSG::HEALER_SOFTEN_FAIL
.byte SCRIPTS::RETURN
      OBJ_REINDEER_HEALER_SJPRESENT11:
.byte SCRIPTS::DIALOGUE
.word UMSG::HEALER_FIXED
.byte SCRIPTS::S_PLAYSOUND, $7
.byte SCRIPTS::S_REMOVEBUT, $BF
.byte SCRIPTS::RETURN
      OBJ_REINDEER_HEALER_JCHOOSECHAR5:
.byte SCRIPTS::J_GIVEMONEY, OBJ_REINDEER_HEALER_JTALK0-OBJ_REINDEER_HEALER
      OBJ_REINDEER_HEALER_JJCUSTOMMENU_B2:
.byte SCRIPTS::DIALOGUE
.word UMSG::HEALER_NO
.byte SCRIPTS::RETURN
      OBJ_REINDEER_HEALER_JTAKEMONEY3:
.byte SCRIPTS::DIALOGUE
.word UMSG::HEALER_BROKE
.byte SCRIPTS::RETURN
      OBJ_REINDEER_HEALER_SJPRESENT7:
.byte SCRIPTS::J_GIVEMONEY, OBJ_REINDEER_HEALER_JTALK0-OBJ_REINDEER_HEALER
.byte SCRIPTS::DIALOGUE
.word UMSG::HEALER_MAN
      OBJ_REINDEER_HEALER_JTALK0:
.byte SCRIPTS::RETURN
.endif

OBJ_SNOWMAN_HEALER:
objectDef OBJ_TYPE::WANDERING_NPC, $24, DIRECTIONS::RIGHT, $104
.addr SPRITEDEF_183 ;sprite
.byte SCRIPTS::N_LOADNUMBER
.word 88
.byte SCRIPTS::OJ_SUBROUTINE

;jp is a normal healer
.ifdef VER_JP
.addr OBJ_PODUNK_HEALER
.byte OBJ_PODUNK_HEALER_OJSUBROUTINE0-OBJ_PODUNK_HEALER
.else
.addr OBJ_REINDEER_HEALER
.byte OBJ_REINDEER_HEALER_OJSUBROUTINE1-OBJ_REINDEER_HEALER
.endif
.byte 0

OBJ_PODUNK_HEALERPHONE:
objectDef $19, $b, DIRECTIONS::UP, $c4
.addr SPRITEDEF_19C ;sprite
.byte SCRIPTS::J_TALK, OBJ_PODUNK_HEALERPHONE_JTALK0-OBJ_PODUNK_HEALERPHONE
.byte SCRIPTS::OJ_SUBROUTINE
.addr OBJ_UNK2
.byte OBJ_UNK2_OJSUBROUTINE2-OBJ_UNK2
      OBJ_PODUNK_HEALERPHONE_JTALK0:
.byte 0

OBJ_REINDEER_HEALERPHONE:
objectDef $19, $2b, DIRECTIONS::UP, $a4
.addr SPRITEDEF_19C ;sprite
.byte SCRIPTS::J_TALK, OBJ_REINDEER_HEALERPHONE_JTALK0-OBJ_REINDEER_HEALERPHONE
.byte SCRIPTS::OJ_SUBROUTINE
.addr OBJ_UNK2
.byte OBJ_UNK2_OJSUBROUTINE2-OBJ_UNK2
      OBJ_REINDEER_HEALERPHONE_JTALK0:
.byte 0

OBJ_SNOWMAN_HEALERPHONE:
objectDef $19, $2b, DIRECTIONS::UP, $104
.addr SPRITEDEF_19C ;sprite
.byte SCRIPTS::J_TALK, OBJ_SNOWMAN_HEALERPHONE_JTALK0-OBJ_SNOWMAN_HEALERPHONE
.byte SCRIPTS::FJ_JUMP, $80, OBJ_SNOWMAN_HEALERPHONE_FJJUMP1-OBJ_SNOWMAN_HEALERPHONE
.byte SCRIPTS::OJ_SUBROUTINE
.addr OBJ_UNK2
.byte OBJ_UNK2_OJSUBROUTINE2-OBJ_UNK2
.byte 0
      OBJ_SNOWMAN_HEALERPHONE_FJJUMP1:
.byte SCRIPTS::DIALOGUE
.word UMSG::PHONE_INTRO
.byte SCRIPTS::J_JUMP, OBJ_SNOWMAN_HEALERPHONEJ_JUMP2-OBJ_SNOWMAN_HEALERPHONE
      OBJ_SNOWMAN_HEALERPHONE_JYESNO3:
.byte SCRIPTS::DIALOGUE
.word UMSG::SNOWMAN_PHONE_1
      OBJ_SNOWMAN_HEALERPHONEJ_JUMP2:
.byte SCRIPTS::DIALOGUE
.word UMSG::SNOWMAN_PHONE_2
.byte SCRIPTS::J_YESNO, OBJ_SNOWMAN_HEALERPHONE_JYESNO3-OBJ_SNOWMAN_HEALERPHONE
.byte SCRIPTS::DIALOGUE
.word UMSG::SNOWMAN_PHONE_3
.byte SCRIPTS::J_JUMP, OBJ_SNOWMAN_HEALERPHONEJ_JUMP4-OBJ_SNOWMAN_HEALERPHONE
      OBJ_SNOWMAN_HEALERPHONE_JYESNO5:
.byte SCRIPTS::DIALOGUE
.word UMSG::SNOWMAN_REGNAME
      OBJ_SNOWMAN_HEALERPHONEJ_JUMP4:
.byte SCRIPTS::REGNAME
.byte SCRIPTS::DIALOGUE
.word UMSG::SNOWMAN_PHONE_CHECK
.byte SCRIPTS::J_YESNO, OBJ_SNOWMAN_HEALERPHONE_JYESNO5-OBJ_SNOWMAN_HEALERPHONE
.byte SCRIPTS::DIALOGUE
.word UMSG::SNOWMAN_PHONE_END
.byte SCRIPTS::DIALOGUE
.word UMSG::PHONE_END
.byte SCRIPTS::F_SETFLAG, $80
      OBJ_SNOWMAN_HEALERPHONE_JTALK0:
.byte 0

OBJ_SWAMP_HOUSEEXIT:
objectDef OBJ_TYPE::DOOR, $38e, DIRECTIONS::RIGHT, $e6
doorArgDef $6, $365, DIRECTIONS::DOWN, $198

OBJ_SWAMP_HOUSEPIPPI:
objectDef OBJ_TYPE::WANDERING_NPC_CHECKSPAWN, $38a, DIRECTIONS::DOWN, $e5
.addr SPRITEDEF_20 ;sprite
.byte SCRIPTS::F_APPEAR, $2D
.byte SCRIPTS::J_TALK, OBJ_SWAMP_HOUSEPIPPI_JTALK0-OBJ_SWAMP_HOUSEPIPPI
.byte SCRIPTS::FJ_JUMP, $86, OBJ_SWAMP_HOUSEPIPPI_FJJUMP1-OBJ_SWAMP_HOUSEPIPPI
.byte SCRIPTS::J_JUMP, OBJ_SWAMP_HOUSEPIPPIJ_JUMP2-OBJ_SWAMP_HOUSEPIPPI
      OBJ_SWAMP_HOUSEPIPPI_FJJUMP1:
.byte SCRIPTS::DIALOGUE
.word UMSG::SWAMP_HOUSEPIPPI
      OBJ_SWAMP_HOUSEPIPPIJ_JUMP2:
.byte SCRIPTS::DIALOGUE
.word UMSG::SWAMP_HOUSEPIPPI_REST
.byte SCRIPTS::SLEEP
.byte SCRIPTS::DIALOGUE
.word UMSG::SWAMP_HOUSEPIPPI_MORNING
.byte SCRIPTS::F_SETFLAG, $86
      OBJ_SWAMP_HOUSEPIPPI_JTALK0:
.byte 0