OBJ_BANK_1E:
.addr OBJ_ROSEMARYHOUSE_DOOR27
.addr OBJ_ROSEMARYHOUSE_DOOR28
.addr OBJ_ROSEMARYHOUSE_DOOR29
.addr OBJ_ROSEMARYHOUSE_DOOR30
.addr OBJ_ROSEMARYHOUSE_DOOR31
.addr OBJ_ROSEMARYHOUSE_DOOR32
.addr OBJ_ROSEMARYHOUSE_DOOR33
.addr OBJ_ROSEMARYHOUSE_DOOR34
.addr OBJ_ROSEMARYHOUSE_DOOR35
.addr OBJ_ROSEMARYHOUSE_DOOR36
.ifdef VER_JP
.addr OBJ_ROSEMARYHOUSE_DOOR66
.addr OBJ_ROSEMARYHOUSE_DOOR67
.else
.addr OBJ_ROSEMARYHOUSE_DOOR37
.endif
.addr OBJ_ROSEMARYHOUSE_DOOR38
.addr OBJ_ROSEMARYHOUSE_DOOR39
.addr OBJ_ROSEMARYHOUSE_DOOR40
.addr OBJ_ROSEMARYHOUSE_DOOR41
.addr OBJ_ROSEMARYHOUSE_DOOR42
.addr OBJ_ROSEMARYHOUSE_DOOR43
.addr OBJ_ROSEMARYHOUSE_DOOR44
.addr OBJ_ROSEMARYHOUSE_DOOR45
.addr OBJ_ROSEMARYHOUSE_DOOR46
.addr OBJ_ROSEMARYHOUSE_DOOR47
.ifdef VER_JP
.addr OBJ_ROSEMARYHOUSE_DOOR68
.endif
.addr OBJ_ROSEMARYHOUSE_DOOR48
.addr OBJ_ROSEMARYHOUSE_PRESENT6
.addr OBJ_ROSEMARYHOUSE_NEVERMAKEIT
.addr OBJ_ROSEMARYHOUSE_TURNBACK
.addr OBJ_ROSEMARYHOUSE_AGH
.addr 0

OBJ_ROSEMARYHOUSE_DOOR27:
objectDef OBJ_TYPE::DOOR, 655, DIRECTIONS::RIGHT, 978
doorArgDef 0, 435, DIRECTIONS::RIGHT, 133

OBJ_ROSEMARYHOUSE_DOOR28:
objectDef OBJ_TYPE::DOOR, 592, DIRECTIONS::LEFT, 1019
doorArgDef 0, 509, DIRECTIONS::LEFT, 134


OBJ_ROSEMARYHOUSE_DOOR29:
objectDef OBJ_TYPE::DOOR, 31, DIRECTIONS::RIGHT, 134
doorArgDef 0, 499, DIRECTIONS::RIGHT, 133

OBJ_ROSEMARYHOUSE_DOOR30:
objectDef OBJ_TYPE::DOOR, 16, DIRECTIONS::LEFT, 135
doorArgDef 0, 669, DIRECTIONS::LEFT, 134


OBJ_ROSEMARYHOUSE_DOOR31:
objectDef OBJ_TYPE::DOOR, 30, DIRECTIONS::RIGHT, 326
doorArgDef 0, 19, DIRECTIONS::RIGHT, 165


OBJ_ROSEMARYHOUSE_DOOR32:
objectDef OBJ_TYPE::DOOR, 62, DIRECTIONS::RIGHT, 262
doorArgDef 0, 17, DIRECTIONS::RIGHT, 167

OBJ_ROSEMARYHOUSE_DOOR33:
objectDef OBJ_TYPE::DOOR, 48, DIRECTIONS::LEFT, 263
doorArgDef 0, 540, DIRECTIONS::LEFT, 133

OBJ_ROSEMARYHOUSE_DOOR34:
objectDef OBJ_TYPE::DOOR, 50, DIRECTIONS::LEFT, 261
doorArgDef 0, 572, DIRECTIONS::LEFT, 133


OBJ_ROSEMARYHOUSE_DOOR35:
objectDef OBJ_TYPE::DOOR, 655, DIRECTIONS::RIGHT, 946
doorArgDef 0, 51, DIRECTIONS::RIGHT, 165

OBJ_ROSEMARYHOUSE_DOOR36:
objectDef OBJ_TYPE::DOOR, 628, DIRECTIONS::LEFT, 959
doorArgDef 0, 61, DIRECTIONS::LEFT, 134

.ifdef VER_JP
OBJ_ROSEMARYHOUSE_DOOR66:
objectDef OBJ_TYPE::DOOR, 63, DIRECTIONS::RIGHT, 199
doorArgDef 0, 18, DIRECTIONS::RIGHT, 262

OBJ_ROSEMARYHOUSE_DOOR67:
objectDef OBJ_TYPE::DOOR, 61, DIRECTIONS::RIGHT, 197
doorArgDef 0, 659, DIRECTIONS::RIGHT, 133
.else
OBJ_ROSEMARYHOUSE_DOOR37:
objectDef OBJ_TYPE::DOOR, 62, DIRECTIONS::RIGHT, 198
doorArgDef 0, 658, DIRECTIONS::RIGHT, 134
.endif


OBJ_ROSEMARYHOUSE_DOOR38:
objectDef OBJ_TYPE::DOOR, 799, DIRECTIONS::RIGHT, 994
doorArgDef 0, 627, DIRECTIONS::RIGHT, 133

OBJ_ROSEMARYHOUSE_DOOR39:
objectDef OBJ_TYPE::DOOR, 772, DIRECTIONS::LEFT, 1007
doorArgDef 0, 61, DIRECTIONS::LEFT, 294


OBJ_ROSEMARYHOUSE_DOOR40:
objectDef OBJ_TYPE::DOOR, 751, DIRECTIONS::RIGHT, 946
doorArgDef 0, 625, DIRECTIONS::RIGHT, 135

OBJ_ROSEMARYHOUSE_DOOR41:
objectDef OBJ_TYPE::DOOR, 724, DIRECTIONS::LEFT, 959
doorArgDef 0, 29, DIRECTIONS::LEFT, 230


OBJ_ROSEMARYHOUSE_DOOR42:
.ifdef VER_JP
objectDef OBJ_TYPE::DOOR, 17, DIRECTIONS::LEFT, 198
doorArgDef 0, 702, DIRECTIONS::LEFT, 135
.else
objectDef OBJ_TYPE::DOOR, 17, DIRECTIONS::LEFT, 198
doorArgDef 0, 701, DIRECTIONS::LEFT, 134
.endif

OBJ_ROSEMARYHOUSE_DOOR43:
objectDef OBJ_TYPE::DOOR, 30, DIRECTIONS::RIGHT, 198
doorArgDef 0, 657, DIRECTIONS::RIGHT, 1023


OBJ_ROSEMARYHOUSE_DOOR44:
objectDef OBJ_TYPE::DOOR, 656, DIRECTIONS::LEFT, 1023
doorArgDef 0, 29, DIRECTIONS::LEFT, 198

OBJ_ROSEMARYHOUSE_DOOR45:
objectDef OBJ_TYPE::DOOR, 703, DIRECTIONS::RIGHT, 994
doorArgDef 0, 51, DIRECTIONS::RIGHT, 133


OBJ_ROSEMARYHOUSE_DOOR46:
objectDef OBJ_TYPE::DOOR, 703, DIRECTIONS::RIGHT, 946
doorArgDef 0, 49, DIRECTIONS::RIGHT, 135

OBJ_ROSEMARYHOUSE_DOOR47:
objectDef OBJ_TYPE::DOOR, 676, DIRECTIONS::LEFT, 959
doorArgDef 0, 29, DIRECTIONS::LEFT, 294

.ifdef VER_JP
OBJ_ROSEMARYHOUSE_DOOR68:
objectDef OBJ_TYPE::DOOR, 17, DIRECTIONS::LEFT, 262
doorArgDef 0, 62, DIRECTIONS::LEFT, 199
.endif

OBJ_ROSEMARYHOUSE_DOOR48:
objectDef OBJ_TYPE::DOOR, 30, DIRECTIONS::RIGHT, 262
doorArgDef 0, 51, DIRECTIONS::RIGHT, 325

OBJ_ROSEMARYHOUSE_PRESENT6:
objectDef OBJ_TYPE::PRESENT, 24, DIRECTIONS::UP, 261
.addr SPRITEDEF_PRESENT
.byte 65 ; item
.byte 24 ; flag


OBJ_ROSEMARYHOUSE_NEVERMAKEIT:
objectDef OBJ_TYPE::TRIGGER_CHECKSPAWN, 620, DIRECTIONS::UP, 1002
OBJ_FLAG_DISAPPEAR 15
OBJ_IS_NOT_TOUCHING @J_IS_NOT_TOUCHING-OBJ_ROSEMARYHOUSE_NEVERMAKEIT
OBJ_DIALOGUE UMSG::ROSEMARYHOUSE_NEVERMAKEIT
	@J_IS_NOT_TOUCHING:
OBJ_STOP

OBJ_ROSEMARYHOUSE_TURNBACK:
objectDef OBJ_TYPE::TRIGGER_CHECKSPAWN, 729, DIRECTIONS::UP, 959
OBJ_FLAG_DISAPPEAR 15
OBJ_IS_NOT_TOUCHING @J_IS_NOT_TOUCHING-OBJ_ROSEMARYHOUSE_TURNBACK
OBJ_DIALOGUE UMSG::ROSEMARYHOUSE_TURNBACK
	@J_IS_NOT_TOUCHING:
OBJ_STOP

OBJ_ROSEMARYHOUSE_AGH:
objectDef OBJ_TYPE::TRIGGER_CHECKSPAWN, 676, DIRECTIONS::UP, 1010
OBJ_FLAG_DISAPPEAR 15
OBJ_IS_NOT_TOUCHING @J_IS_NOT_TOUCHING-OBJ_ROSEMARYHOUSE_AGH
OBJ_DIALOGUE UMSG::ROSEMARYHOUSE_AGH
	@J_IS_NOT_TOUCHING:
OBJ_STOP