OBJ_BANK_1A:
.addr OBJ_TWINKLE_EXIT
.addr OBJ_TWINKLE_F1_ROOM1ENTRANCE
.addr OBJ_TWINKLE_F1_ROOM2ENTRANCE
.addr OBJ_TWINKLE_F1_ROOM3ENTRANCE
.addr OBJ_TWINKLE_F1_ROOM4ENTRANCE
.addr OBJ_TWINKLE_F1_ROOM5ENTRANCE
.addr OBJ_TWINKLE_F1_ROOM6ENTRANCE
.addr OBJ_TWINKLE_F1_UPSTAIRS
.addr OBJ_TWINKLE_F2_DOWNSTAIRS
.addr OBJ_TWINKLE_F2_ROOM1ENTRANCE
.addr OBJ_TWINKLE_F2_ROOM2ENTRANCE
.addr OBJ_TWINKLE_F2_ROOM3ENTRANCE
.addr OBJ_TWINKLE_F2_ROOM4ENTRANCE
.addr OBJ_TWINKLE_F2_ROOM5ENTRANCE
.addr OBJ_TWINKLE_F2_ROOM6ENTRANCE
.addr OBJ_TWINKLE_F2_UPSTAIRS
.addr OBJ_MERRYSVILLE_HOTELDOWNSTAIRS
.addr OBJ_MERRYSVILLE_HOTELUPROOM1ENTRANCE
.addr OBJ_MERRYSVILLE_HOTELUPROOM2ENTRANCE
.addr OBJ_MERRYSVILLE_HOTELUPUPSTAIRS
.addr OBJ_TWINKLE_HALLMONITOR
.addr OBJ_TWINKLE_LLOYDBULLY
.addr OBJ_TWINKLE_LLOYDBULLY2
.addr OBJ_TWINKLE_HALLMONITOR2
.addr OBJ_TWINKLE_F1JANITOR
.addr OBJ_TWINKLE_F2JANITOR
.addr OBJ_TWINKLE_F2LLOYD
.addr OBJ_TWINKLE_F1LLOYD
.addr 0

OBJ_TWINKLE_EXIT:
objectDef OBJ_TYPE::DOOR, $305, DIRECTIONS::UP, $3b4
doorArgDef $6, $169, DIRECTIONS::DOWN, $1E6

OBJ_TWINKLE_F1_ROOM1ENTRANCE:
objectDef OBJ_TYPE::DOOR, $2f6, DIRECTIONS::UP, $3b7
doorArgDef $0, $26D, DIRECTIONS::LEFT, $3D6

OBJ_TWINKLE_F1_ROOM2ENTRANCE:
objectDef OBJ_TYPE::DOOR, $2fa, DIRECTIONS::UP, $3b7
doorArgDef $0, $2CD, DIRECTIONS::LEFT, $3D6

OBJ_TWINKLE_F1_ROOM3ENTRANCE:
objectDef OBJ_TYPE::DOOR, $2fd, DIRECTIONS::UP, $3b7
doorArgDef $0, $2CD, DIRECTIONS::LEFT, $3F6

OBJ_TWINKLE_F1_ROOM4ENTRANCE:
objectDef OBJ_TYPE::DOOR, $30e, DIRECTIONS::UP, $3b7
doorArgDef $0, $2AD, DIRECTIONS::LEFT, $3D6

OBJ_TWINKLE_F1_ROOM5ENTRANCE:
objectDef OBJ_TYPE::DOOR, $312, DIRECTIONS::UP, $3b7
doorArgDef $0, $28D, DIRECTIONS::LEFT, $3F6

OBJ_TWINKLE_F1_ROOM6ENTRANCE:
objectDef $18, $315, DIRECTIONS::UP, $3b7
OBJ_IS_NOT_FACING @JUNK0-OBJ_TWINKLE_F1_ROOM6ENTRANCE
OBJ_IS_NOT_TOUCHING @JTOUCH1-OBJ_TWINKLE_F1_ROOM6ENTRANCE
OBJ_IS_NOT_FLAG $5B, @FJJUMP2-OBJ_TWINKLE_F1_ROOM6ENTRANCE
OBJ_TELEPORT $0, $31D, DIRECTIONS::LEFT, $3C6
OBJ_STOP
    @FJJUMP2:
OBJ_DIALOGUE UMSG::TWINKLE_F1_ROOM6ENTRANCE_NOJANITOR
OBJ_STOP
    @JTOUCH1:
OBJ_IS_NOT_USING $55, @IJUSE3-OBJ_TWINKLE_F1_ROOM6ENTRANCE
OBJ_JUMP @JUMP4-OBJ_TWINKLE_F1_ROOM6ENTRANCE
    @IJUSE3:
OBJ_IS_NOT_USING $56, @IJUSE5-OBJ_TWINKLE_F1_ROOM6ENTRANCE
OBJ_JUMP @JUMP4-OBJ_TWINKLE_F1_ROOM6ENTRANCE
    @IJUSE5:
OBJ_IS_NOT_USING $57, @JUNK0-OBJ_TWINKLE_F1_ROOM6ENTRANCE
    @JUMP4:
OBJ_DIALOGUE UMSG::DOOR_KEYFAIL
    @JUNK0:
OBJ_STOP

OBJ_TWINKLE_F1_UPSTAIRS:
objectDef OBJ_TYPE::STAIRS, $2f2, DIRECTIONS::LEFT, $3b9
doorArgDef $0, $2FA, DIRECTIONS::RIGHT, $3D6

OBJ_TWINKLE_F2_DOWNSTAIRS:
objectDef OBJ_TYPE::STAIRS, $2f9, DIRECTIONS::LEFT, $3d6
doorArgDef $0, $2F3, DIRECTIONS::RIGHT, $3B9

OBJ_TWINKLE_F2_ROOM1ENTRANCE:
objectDef OBJ_TYPE::DOOR, $2fe, DIRECTIONS::UP, $3d3
doorArgDef $0, $2CD, DIRECTIONS::LEFT, $3B6

OBJ_TWINKLE_F2_ROOM2ENTRANCE:
objectDef OBJ_TYPE::DOOR, $302, DIRECTIONS::UP, $3d3
doorArgDef $0, $2ED, DIRECTIONS::LEFT, $3D6

OBJ_TWINKLE_F2_ROOM3ENTRANCE:
objectDef OBJ_TYPE::DOOR, $306, DIRECTIONS::UP, $3d3
doorArgDef $0, $2ED, DIRECTIONS::LEFT, $3F6

OBJ_TWINKLE_F2_ROOM4ENTRANCE:
objectDef OBJ_TYPE::DOOR, $30a, DIRECTIONS::UP, $3d3
doorArgDef $0, $37D, DIRECTIONS::LEFT, $96

OBJ_TWINKLE_F2_ROOM5ENTRANCE:
objectDef OBJ_TYPE::DOOR, $30e, DIRECTIONS::UP, $3d3
doorArgDef $0, $26D, DIRECTIONS::LEFT, $3B6

OBJ_TWINKLE_F2_ROOM6ENTRANCE:
objectDef OBJ_TYPE::DOOR, $311, DIRECTIONS::UP, $3d3
doorArgDef $0, $3D, DIRECTIONS::LEFT, $156

OBJ_TWINKLE_F2_UPSTAIRS:
objectDef $18, $315, DIRECTIONS::RIGHT, $3d5
OBJ_IS_NOT_FACING @JUNK0-OBJ_TWINKLE_F2_UPSTAIRS
OBJ_IS_NOT_TOUCHING @JTOUCH1-OBJ_TWINKLE_F2_UPSTAIRS
OBJ_IS_NOT_FLAG $3C, @FJJUMP2-OBJ_TWINKLE_F2_UPSTAIRS
OBJ_TELEPORT $0, $6B, DIRECTIONS::DOWN, $170
OBJ_STOP
    @FJJUMP2:
OBJ_DIALOGUE UMSG::TWINKLE_F2_UPSTAIRS_PADLOCK
OBJ_SET_FLAG $5B
OBJ_STOP
    @JTOUCH1:
OBJ_IS_NOT_USING $55, @IJUSE3-OBJ_TWINKLE_F2_UPSTAIRS
OBJ_JUMP @JUMP4-OBJ_TWINKLE_F2_UPSTAIRS
    @IJUSE3:
OBJ_IS_NOT_USING $56, @IJUSE5-OBJ_TWINKLE_F2_UPSTAIRS
OBJ_JUMP @JUMP4-OBJ_TWINKLE_F2_UPSTAIRS
    @IJUSE5:
OBJ_IS_NOT_USING $57, @JUNK0-OBJ_TWINKLE_F2_UPSTAIRS
    @JUMP4:
OBJ_DIALOGUE UMSG::DOOR_KEYFAIL
    @JUNK0:
OBJ_STOP

OBJ_MERRYSVILLE_HOTELDOWNSTAIRS:
objectDef OBJ_TYPE::STAIRS, $301, DIRECTIONS::LEFT, $3f6
doorArgDef $0, $2D3, DIRECTIONS::RIGHT, $3D5

OBJ_MERRYSVILLE_HOTELUPROOM1ENTRANCE:
objectDef OBJ_TYPE::DOOR, $306, DIRECTIONS::UP, $3f3
doorArgDef $0, $2ED, DIRECTIONS::LEFT, $86

OBJ_MERRYSVILLE_HOTELUPROOM2ENTRANCE:
objectDef OBJ_TYPE::DOOR, $309, DIRECTIONS::UP, $3f3
doorArgDef $0, $36D, DIRECTIONS::LEFT, $86

OBJ_MERRYSVILLE_HOTELUPUPSTAIRS:
objectDef OBJ_TYPE::STAIRS, $302, DIRECTIONS::LEFT, $3f5
doorArgDef $0, $272, DIRECTIONS::RIGHT, $3C6

OBJ_TWINKLE_HALLMONITOR:
objectDef OBJ_TYPE::WANDERING_NPC, $317, DIRECTIONS::RIGHT, $3ba
.addr SPRITEDEF_HAIR_GIRL ;sprite
OBJ_IS_NOT_TALKING @JTALK0-OBJ_TWINKLE_HALLMONITOR
OBJ_DIALOGUE UMSG::TWINKLE_HALLMONITOR
    @JTALK0:
OBJ_STOP

OBJ_TWINKLE_LLOYDBULLY:
objectDef OBJ_TYPE::WANDERING_NPC, $30d, DIRECTIONS::LEFT, $3d6
.addr SPRITEDEF_CAP_KID ;sprite
OBJ_IS_NOT_TALKING @JTALK0-OBJ_TWINKLE_LLOYDBULLY
OBJ_NOT_HAS_CHARACTER $3, @CJPRESENT1-OBJ_TWINKLE_LLOYDBULLY
OBJ_HAS_STATUS $80, @SJPRESENT2-OBJ_TWINKLE_LLOYDBULLY
OBJ_DIALOGUE UMSG::TWINKLE_LLOYDBULLY_LLOYD
OBJ_STOP
    @SJPRESENT2:
OBJ_DIALOGUE UMSG::TWINKLE_LLOYDBULLY_DEADLLOYD
OBJ_STOP
    @CJPRESENT1:
OBJ_DIALOGUE UMSG::TWINKLE_LLOYDBULLY
    @JTALK0:
OBJ_STOP

OBJ_TWINKLE_LLOYDBULLY2:
objectDef OBJ_TYPE::WANDERING_NPC, $30f, DIRECTIONS::RIGHT, $3d7
.addr SPRITEDEF_HEADBAND_KID ;sprite
OBJ_IS_NOT_TALKING @JTALK0-OBJ_TWINKLE_LLOYDBULLY2
OBJ_NOT_HAS_CHARACTER $3, @CJPRESENT1-OBJ_TWINKLE_LLOYDBULLY2
OBJ_DIALOGUE UMSG::TWINKLE_LLOYDBULLY2_LLOYD
OBJ_STOP
    @CJPRESENT1:
OBJ_DIALOGUE UMSG::TWINKLE_LLOYDBULLY2
    @JTALK0:
OBJ_STOP

OBJ_TWINKLE_HALLMONITOR2:
objectDef OBJ_TYPE::WANDERING_NPC, $2fb, DIRECTIONS::LEFT, $3bb
.addr SPRITEDEF_LONG_GUY ;sprite
OBJ_IS_NOT_TALKING @JTALK0-OBJ_TWINKLE_HALLMONITOR2
OBJ_DIALOGUE UMSG::TWINKLE_HALLMONITOR2
OBJ_YESNO_IS_NO @JYESNO1-OBJ_TWINKLE_HALLMONITOR2
OBJ_DIALOGUE UMSG::TWINKLE_HALLMONITOR2_YES
OBJ_STOP
    @JYESNO1:
OBJ_DIALOGUE UMSG::ELLAY_LHCOP_SEEWEAPON
    @JTALK0:
OBJ_STOP

OBJ_TWINKLE_F1JANITOR:
objectDef OBJ_TYPE::STATIONARY_NPC_CHECKSPAWN, $315, DIRECTIONS::LEFT, $3b9
.addr SPRITEDEF_JANITOR ;sprite
OBJ_FLAG_APPEAR $23
OBJ_IS_NOT_TOUCHING @JTOUCH0-OBJ_TWINKLE_F1JANITOR
OBJ_MOVE @MOVE0
    @JTOUCH0:
OBJ_STOP
    @MOVE0:
moveDef DIRECTIONS::LEFT, $6, $22
moveDef DIRECTIONS::LEFT, $2, $1
moveDef DIRECTIONS::RIGHT, $2, $1
.byte 3

OBJ_TWINKLE_F2JANITOR:
objectDef OBJ_TYPE::STATIONARY_NPC_CHECKSPAWN, $2fb, DIRECTIONS::UP, $3d6
.addr SPRITEDEF_JANITOR ;sprite
OBJ_FLAG_APPEAR $23
OBJ_IS_NOT_TOUCHING @JTOUCH0-OBJ_TWINKLE_F2JANITOR
OBJ_MOVE @MOVE0
OBJ_DIALOGUE UMSG::TWINKLE_F2JANITOR
OBJ_MOVE @MOVE1
OBJ_DIALOGUE UMSG::TWINKLE_F2JANITOR2
OBJ_MOVE @MOVE2
OBJ_SET_FLAG $3C
OBJ_CLEAR_FLAG $23
    @JTOUCH0:
OBJ_STOP
    @MOVE0:
moveDef DIRECTIONS::UP, $6, $1
moveDef DIRECTIONS::RIGHT, $6, $A
.byte 3
    @MOVE1:
moveDef DIRECTIONS::RIGHT, $6, $F
moveDef DIRECTIONS::LEFT, MOVE_CMD::ABOUTFACE, $1
moveDef DIRECTIONS::RIGHT, MOVE_CMD::MOVEFACE, $1
moveDef DIRECTIONS::RIGHT, $A, $1
moveDef DIRECTIONS::LEFT, $A, $1
moveDef DIRECTIONS::LEFT, MOVE_CMD::MOVEFACE, $1
.byte 3
    @MOVE2:
moveDef DIRECTIONS::DOWN, MOVE_CMD::MOVEFACE, $1
moveDef DIRECTIONS::LEFT, MOVE_CMD::MOVEFACE, $9
OBJ_STOP

OBJ_TWINKLE_F2LLOYD:
objectDef OBJ_TYPE::STATIONARY_NPC_CHECKSPAWN, $313, DIRECTIONS::RIGHT, $3d5
.addr SPRITEDEF_LLOYD ;sprite
OBJ_FLAG_APPEAR $24
OBJ_IS_NOT_TOUCHING @JTOUCH0-OBJ_TWINKLE_F2LLOYD
OBJ_DIALOGUE UMSG::TWINKLE_F2LLOYD
OBJ_MOVE @MOVE0
    @JTOUCH0:
OBJ_STOP
    @MOVE0:
moveDef DIRECTIONS::LEFT, $6, $F
moveDef DIRECTIONS::DOWN, $6, $1
moveDef DIRECTIONS::LEFT, $6, $A
moveDef DIRECTIONS::LEFT, $2, $1
moveDef DIRECTIONS::RIGHT, $2, $1
.byte 3

OBJ_TWINKLE_F1LLOYD:
objectDef OBJ_TYPE::STATIONARY_NPC_CHECKSPAWN, $2f4, DIRECTIONS::LEFT, $3b9
.addr SPRITEDEF_LLOYD ;sprite
OBJ_FLAG_APPEAR $24
OBJ_IS_NOT_TOUCHING @JTOUCH0-OBJ_TWINKLE_F1LLOYD
OBJ_DIALOGUE UMSG::TWINKLE_F1LLOYD
OBJ_MOVE @MOVE0
    @JTOUCH0:
OBJ_STOP
    @MOVE0:
moveDef DIRECTIONS::RIGHT, $6, $1A
moveDef DIRECTIONS::UP, $6, $1
moveDef DIRECTIONS::UP, $2, $1
moveDef DIRECTIONS::LEFT, $2, $1
.byte 3