OBJ_BANK_24:
.addr OBJ_PODUNK_MAYOREXIT
.addr OBJ_PODUNK_MAYORUPSTAIRS
.addr OBJ_PODUNK_MAYORDOWNSTAIRS
.addr OBJ_ELLAY_HOSPITALDOWNSTAIRS
.addr OBJ_ELLAY_HOSPITALROOMLEFTENTRANCE
.addr OBJ_ELLAY_HOSPITALROOMRIGHTENTRANCE
.addr OBJ_PODUNK_MAYORSECRETARY
.addr OBJ_PODUNK_MAYOR
.addr OBJ_PODUNK_ABBOTT
.addr OBJ_PODUNK_MAYORPIPPI
.addr 0

OBJ_PODUNK_MAYOREXIT:
objectDef OBJ_TYPE::DOOR, 702, DIRECTIONS::RIGHT, 150
doorArgDef 6, 187, DIRECTIONS::DOWN, 433

OBJ_PODUNK_MAYORUPSTAIRS:
objectDef OBJ_TYPE::STAIRS, 690, DIRECTIONS::LEFT, 149
doorArgDef 0, 818, DIRECTIONS::RIGHT, 150

OBJ_PODUNK_MAYORDOWNSTAIRS:
objectDef 24, 817, DIRECTIONS::LEFT, 150
OBJ_IS_NOT_FACING @J_IS_NOT_FACING-OBJ_PODUNK_MAYORDOWNSTAIRS
OBJ_IS_NOT_TOUCHING @J_IS_NOT_FACING-OBJ_PODUNK_MAYORDOWNSTAIRS
OBJ_IS_NOT_FLAG 44, @J_IS_NOT_FLAG-OBJ_PODUNK_MAYORDOWNSTAIRS
;sets pippi_was_saved on
OBJ_CLEAR_FLAG 44
OBJ_SET_FLAG 45
	@J_IS_NOT_FLAG:
OBJ_PLAY_SOUND2 8
OBJ_TELEPORT 0, 691, DIRECTIONS::RIGHT, 149
	@J_IS_NOT_FACING:
OBJ_STOP

OBJ_ELLAY_HOSPITALDOWNSTAIRS:
objectDef OBJ_TYPE::STAIRS, 849, DIRECTIONS::LEFT, 150
doorArgDef 0, 755, DIRECTIONS::RIGHT, 1013

OBJ_ELLAY_HOSPITALROOMLEFTENTRANCE:
objectDef OBJ_TYPE::DOOR, 854, DIRECTIONS::UP, 147
doorArgDef 0, 45, DIRECTIONS::LEFT, 294

OBJ_ELLAY_HOSPITALROOMRIGHTENTRANCE:
objectDef OBJ_TYPE::DOOR, 857, DIRECTIONS::UP, 147
doorArgDef 0, 45, DIRECTIONS::LEFT, 326

OBJ_PODUNK_MAYORSECRETARY:
objectDef OBJ_TYPE::STATIONARY_NPC, 696, DIRECTIONS::DOWN, 148
.addr SPRITEDEF_HAIR_GIRL
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_PODUNK_MAYORSECRETARY
OBJ_IS_NOT_FLAG 13, @J_IS_NOT_FLAG-OBJ_PODUNK_MAYORSECRETARY
OBJ_DIALOGUE UMSG::SECRETARY_ANA
OBJ_STOP
	@J_IS_NOT_FLAG:
OBJ_DIALOGUE UMSG::SECRETARY_SECRET
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_PODUNK_MAYOR:
objectDef OBJ_TYPE::STATIONARY_NPC, 825, DIRECTIONS::DOWN, 149
.addr SPRITEDEF_MAYOR
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_PODUNK_MAYOR
OBJ_NOT_HAS_CHARACTER 5, @J_NOT_HAS_CHARACTER-OBJ_PODUNK_MAYOR
OBJ_HAS_STATUS %10000000, @J_HAS_STATUS-OBJ_PODUNK_MAYOR
OBJ_JUMP @J_JUMP-OBJ_PODUNK_MAYOR
	@J_HAS_STATUS:
OBJ_DIALOGUE UMSG::MAYOR_PIPPI_DEAD
OBJ_MOVE @MOVE_DATA_3
OBJ_STOP
	@J_JUMP:
OBJ_NOT_HAS_CHARACTER 1, @J_NOT_HAS_CHARACTER-OBJ_PODUNK_MAYOR
OBJ_HAS_STATUS %10000000, @J_HAS_STATUS1-OBJ_PODUNK_MAYOR
OBJ_LOAD_NUMBER 100
OBJ_DIALOGUE UMSG::MAYOR_RETURNPIPPI
OBJ_PLAY_SOUND 6
OBJ_GIVE_MONEY @J_IS_NOT_TALKING-OBJ_PODUNK_MAYOR
OBJ_SHOW_MONEY
OBJ_SET_FLAG 11
OBJ_MOVE @MOVE_DATA_1
OBJ_DIALOGUE UMSG::MAYOR_SEE_ZOO
OBJ_YESNO_IS_NO @J_YESNO_IS_NO-OBJ_PODUNK_MAYOR
	@J_YESNO_IS_NO:
OBJ_DIALOGUE UMSG::MAYOR_SEE_ZOO_ACCEPT
OBJ_SET_FLAG 94
OBJ_SET_FLAG 11
OBJ_SIGNAL 9
OBJ_MOVE @MOVE_DATA_2
OBJ_STOP
	@J_HAS_STATUS1:
OBJ_DIALOGUE UMSG::MAYOR_NINTEN_DEAD
OBJ_MOVE @MOVE_DATA_3
OBJ_STOP
	@J_NOT_HAS_CHARACTER:
OBJ_IS_NOT_FLAG 13, @J_IS_NOT_FLAG-OBJ_PODUNK_MAYOR
OBJ_DIALOGUE UMSG::MAYOR_POST_ZOO
OBJ_MOVE @MOVE_DATA_3
OBJ_STOP
	@J_IS_NOT_FLAG:
OBJ_IS_NOT_FLAG 11, @J_IS_NOT_FLAG1-OBJ_PODUNK_MAYOR
OBJ_DIALOGUE UMSG::MAYOR_HERO
OBJ_MOVE @MOVE_DATA_3
OBJ_STOP
	@J_IS_NOT_FLAG1:
OBJ_IS_NOT_FLAG 93, @J_IS_NOT_FLAG2-OBJ_PODUNK_MAYOR
OBJ_DIALOGUE UMSG::MAYOR_HELPTOWN
OBJ_MOVE @MOVE_DATA_3
OBJ_STOP
	@J_IS_NOT_FLAG2:
OBJ_DIALOGUE UMSG::MAYOR_HELPTOWN
OBJ_DIALOGUE UMSG::MAYOR_PIPPIQUEST
OBJ_YESNO_IS_NO @J_YESNO_IS_NO1-OBJ_PODUNK_MAYOR
	@J_YESNO_IS_NO1:
OBJ_DIALOGUE UMSG::MAYOR_PIPPIQUESTYES
OBJ_DIALOGUE UMSG::MAYOR_HERO
OBJ_MOVE @MOVE_DATA_3
OBJ_SET_FLAG 93
	@J_IS_NOT_TALKING:
OBJ_STOP

@MOVE_DATA_1:
moveDef DIRECTIONS::LEFT, 6, 2
moveDef DIRECTIONS::DOWN, 6, 2
moveDef DIRECTIONS::RIGHT, 6, 3
moveDef DIRECTIONS::RIGHT, MOVE_CMD::MOVEFACE, 1
moveDef DIRECTIONS::LEFT, MOVE_CMD::ABOUTFACE, 6
OBJ_RETURN
@MOVE_DATA_2:
OBJ_STOP
@MOVE_DATA_3:
moveDef DIRECTIONS::DOWN, MOVE_CMD::ABOUTFACE, 1
OBJ_STOP

OBJ_PODUNK_ABBOTT:
objectDef OBJ_TYPE::STATIONARY_NPC, 820, DIRECTIONS::DOWN, 148
.addr SPRITEDEF_LONG_GUY
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_PODUNK_ABBOTT
OBJ_IS_NOT_FLAG 13, @J_IS_NOT_FLAG-OBJ_PODUNK_ABBOTT
OBJ_DIALOGUE UMSG::ABBOTT_INTRO
OBJ_STOP
	@J_IS_NOT_FLAG:
OBJ_IS_NOT_FLAG 95, @J_IS_NOT_FLAG1-OBJ_PODUNK_ABBOTT
OBJ_DIALOGUE UMSG::ABBOTT_NEWKEY
	@J_JUMP:
OBJ_NOT_HAS_ITEM 0, @J_NOT_HAS_ITEM-OBJ_PODUNK_ABBOTT
OBJ_PLAY_SOUND 6
OBJ_PICK_ITEM 86
OBJ_GIVE_ITEM @J_IS_NOT_TALKING-OBJ_PODUNK_ABBOTT
OBJ_SET_FLAG 95
OBJ_CLEAR_FLAG 33
OBJ_STOP
	@J_NOT_HAS_ITEM:
OBJ_DIALOGUE UMSG::ABBOTT_CANTHOLD
OBJ_STOP
	@J_IS_NOT_FLAG1:
OBJ_IS_NOT_FLAG 94, @J_IS_NOT_FLAG2-OBJ_PODUNK_ABBOTT
OBJ_DIALOGUE UMSG::ABBOTT_GET_KEY
OBJ_JUMP @J_JUMP-OBJ_PODUNK_ABBOTT
	@J_IS_NOT_FLAG2:
OBJ_DIALOGUE UMSG::ABBOTT_MAYOR
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_PODUNK_MAYORPIPPI:
objectDef OBJ_TYPE::STATIONARY_NPC_CHECKSPAWN, 824, DIRECTIONS::RIGHT, 151
.addr SPRITEDEF_PIPPI
OBJ_FLAG_APPEAR 44
OBJ_IS_SIGNAL @J_IS_SIGNAL-OBJ_PODUNK_MAYORPIPPI
OBJ_PICK_CHARACTER 5
OBJ_CHARA_NOT_HAS_ITEM 3, @J_CHARA_NOT_HAS_ITEM-OBJ_PODUNK_MAYORPIPPI
OBJ_PICK_ITEM 3
OBJ_REMOVE_ITEM @J_REMOVE_ITEM-OBJ_PODUNK_MAYORPIPPI
	@J_CHARA_NOT_HAS_ITEM:
OBJ_SET_FLAG 44
OBJ_REMOVE_CHARACTER 5, @J_REMOVE_ITEM-OBJ_PODUNK_MAYORPIPPI
OBJ_MOVE @MOVE_DATA
OBJ_STOP
	@J_IS_SIGNAL:
OBJ_IS_NOT_TALKING @J_REMOVE_ITEM-OBJ_PODUNK_MAYORPIPPI
OBJ_DIALOGUE UMSG::PODUNK_MAYORPIPPI
OBJ_YESNO_IS_NO @J_YESNO_IS_NO-OBJ_PODUNK_MAYORPIPPI
	@J_YESNO_IS_NO:
OBJ_DIALOGUE UMSG::PODUNK_MAYORPIPPI_YES
	@J_REMOVE_ITEM:
OBJ_STOP

@MOVE_DATA:
moveDef DIRECTIONS::UP, MOVE_CMD::MOVEFACE, 1
moveDef DIRECTIONS::RIGHT, MOVE_CMD::MOVEFACE, 2
moveDef DIRECTIONS::LEFT, MOVE_CMD::ABOUTFACE, 1
OBJ_STOP