OBJ_BANK_23:
.addr OBJ_ELLAY_HOSPITALOFFICEEXIT
.addr OBJ_ELLAY_HOTELRIGHTROOMEXIT
.addr OBJ_REINDEER_HOTELDOWNSTAIRS
.addr OBJ_REINDEER_HOTELROOMLEFTENTRANCE
.addr OBJ_REINDEER_HOTELROOMRIGHTENTRANCE
.addr OBJ_REINDEER_HOTELUPSTAIRS2
.addr OBJ_REINDEER_HOSPITALROOMLEFTEXIT
.addr OBJ_REINDEER_HOSPITALROOMRIGHTEXIT
.addr OBJ_SPOOKANE_HOSPITALOFFICEEXIT
.addr OBJ_SPOOKANE_HOSPITALDOWNSTAIRS
.addr OBJ_SPOOKANE_HOSPITALROOMLEFTENTRANCE
.addr OBJ_SPOOKANE_HOSPITALROOMRIGHTENTRANCE
.addr OBJ_SPOOKANE_HOSPITALROOMLEFTEXIT
.addr OBJ_SPOOKANE_HOSPITALROOMRIGHTEXIT
.addr OBJ_SPOOKANE_HOTELROOMLEFTEXIT
.addr OBJ_SPOOKANE_HOTELROOMRIGHTEXIT
.addr OBJ_ELLAY_DOCTOR
.addr OBJ_SPOOKANE_DOCTOR
.addr 0

OBJ_ELLAY_HOSPITALOFFICEEXIT:
objectDef OBJ_TYPE::DOOR, 734, DIRECTIONS::RIGHT, 150
doorArgDef 0, 758, DIRECTIONS::DOWN, 1012

OBJ_ELLAY_HOTELRIGHTROOMEXIT:
objectDef OBJ_TYPE::DOOR, 606, DIRECTIONS::RIGHT, 150
doorArgDef 0, 505, DIRECTIONS::DOWN, 148

OBJ_REINDEER_HOTELDOWNSTAIRS:
objectDef OBJ_TYPE::STAIRS, 17, DIRECTIONS::LEFT, 214
doorArgDef 0, 3, DIRECTIONS::RIGHT, 261

OBJ_REINDEER_HOTELROOMLEFTENTRANCE:
objectDef OBJ_TYPE::DOOR, 22, DIRECTIONS::UP, 211
doorArgDef 0, 29, DIRECTIONS::LEFT, 246

OBJ_REINDEER_HOTELROOMRIGHTENTRANCE:
objectDef OBJ_TYPE::DOOR, 25, DIRECTIONS::UP, 211
doorArgDef 0, 29, DIRECTIONS::LEFT, 278

OBJ_REINDEER_HOTELUPSTAIRS2:
objectDef OBJ_TYPE::STAIRS, 18, DIRECTIONS::LEFT, 213
doorArgDef 0, 50, DIRECTIONS::RIGHT, 278

OBJ_REINDEER_HOSPITALROOMLEFTEXIT:
objectDef OBJ_TYPE::DOOR, 30, DIRECTIONS::RIGHT, 150
doorArgDef 0, 22, DIRECTIONS::DOWN, 340

OBJ_REINDEER_HOSPITALROOMRIGHTEXIT:
objectDef OBJ_TYPE::DOOR, 30, DIRECTIONS::RIGHT, 182
doorArgDef 0, 25, DIRECTIONS::DOWN, 340

OBJ_SPOOKANE_HOSPITALOFFICEEXIT:
objectDef OBJ_TYPE::DOOR, 30, DIRECTIONS::RIGHT, 310
doorArgDef 0, 600, DIRECTIONS::DOWN, 980

OBJ_SPOOKANE_HOSPITALDOWNSTAIRS:
objectDef OBJ_TYPE::STAIRS, 49, DIRECTIONS::LEFT, 310
doorArgDef 0, 595, DIRECTIONS::RIGHT, 981

OBJ_SPOOKANE_HOSPITALROOMLEFTENTRANCE:
objectDef OBJ_TYPE::DOOR, 54, DIRECTIONS::UP, 307
doorArgDef 0, 61, DIRECTIONS::LEFT, 150

OBJ_SPOOKANE_HOSPITALROOMRIGHTENTRANCE:
objectDef OBJ_TYPE::DOOR, 57, DIRECTIONS::UP, 307
doorArgDef 0, 61, DIRECTIONS::LEFT, 182

OBJ_SPOOKANE_HOSPITALROOMLEFTEXIT:
objectDef OBJ_TYPE::DOOR, 62, DIRECTIONS::RIGHT, 150
doorArgDef 0, 54, DIRECTIONS::DOWN, 308

OBJ_SPOOKANE_HOSPITALROOMRIGHTEXIT:
objectDef OBJ_TYPE::DOOR, 62, DIRECTIONS::RIGHT, 182
doorArgDef 0, 57, DIRECTIONS::DOWN, 308

OBJ_SPOOKANE_HOTELROOMLEFTEXIT:
objectDef OBJ_TYPE::DOOR, 62, DIRECTIONS::RIGHT, 246
doorArgDef 0, 54, DIRECTIONS::DOWN, 212

OBJ_SPOOKANE_HOTELROOMRIGHTEXIT:
objectDef OBJ_TYPE::DOOR, 478, DIRECTIONS::RIGHT, 150
doorArgDef 0, 57, DIRECTIONS::DOWN, 212

OBJ_ELLAY_DOCTOR:
objectDef OBJ_TYPE::STATIONARY_NPC, 724, DIRECTIONS::DOWN, 148
.addr SPRITEDEF_DOCTOR
OBJ_LOAD_NUMBER 92
OBJ_SUBROUTINE OBJ_ELLAY_DOCTOR, SUBR_DOCTOR-OBJ_ELLAY_DOCTOR
OBJ_STOP

SUBR_DOCTOR:
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_ELLAY_DOCTOR
OBJ_DIALOGUE UMSG::PODUNK_HOSPITALDOCTOR
OBJ_YESNO_IS_NO @J_YESNO_IS_NO-OBJ_ELLAY_DOCTOR
OBJ_TAKE_MONEY @J_TAKE_MONEY-OBJ_ELLAY_DOCTOR
OBJ_PICK_CHARACTER_J 1, @J_PICK_CHARACTER_J-OBJ_ELLAY_DOCTOR
OBJ_CHOOSE_CHARACTER @J_CHOOSE_CHARACTER-OBJ_ELLAY_DOCTOR
OBJ_JUMP @J_JUMP-OBJ_ELLAY_DOCTOR
	@J_PICK_CHARACTER_J:
OBJ_PICK_CHARACTER_J 0, @J_JUMP-OBJ_ELLAY_DOCTOR
	@J_JUMP:
OBJ_HAS_STATUS %10000000, @J_HAS_STATUS-OBJ_ELLAY_DOCTOR
OBJ_NOT_MAX_HEALTH @J_NOT_MAX_HEALTH-OBJ_ELLAY_DOCTOR
OBJ_HAS_STATUS 3, @J_NOT_MAX_HEALTH-OBJ_ELLAY_DOCTOR
OBJ_DIALOGUE UMSG::PODUNK_HOSPITALDOCTOR_NORMAL
OBJ_GIVE_MONEY @J_IS_NOT_TALKING-OBJ_ELLAY_DOCTOR
OBJ_RETURN
	@J_NOT_MAX_HEALTH:
OBJ_HEAL 255
OBJ_NOT_MAX_HEALTH @J_NOT_MAX_HEALTH-OBJ_ELLAY_DOCTOR
OBJ_AND_STATUS %11111100
OBJ_SHOW_MONEY
OBJ_PLAY_SOUND 7
OBJ_DIALOGUE UMSG::PODUNK_HOSPITALDOCTOR_ACCEPT
OBJ_RETURN
	@J_CHOOSE_CHARACTER:
OBJ_GIVE_MONEY @J_IS_NOT_TALKING-OBJ_ELLAY_DOCTOR
	@J_YESNO_IS_NO:
OBJ_DIALOGUE UMSG::PODUNK_HOSPITALDOCTOR_DECLINE
OBJ_RETURN
	@J_HAS_STATUS:
OBJ_GIVE_MONEY @J_IS_NOT_TALKING-OBJ_ELLAY_DOCTOR
OBJ_DIALOGUE UMSG::HOSPITAL_NOPERSON
OBJ_RETURN
	@J_TAKE_MONEY:
OBJ_DIALOGUE UMSG::YUCCA_PILOT_NOMONEY
	@J_IS_NOT_TALKING:
OBJ_RETURN

OBJ_SPOOKANE_DOCTOR:
objectDef OBJ_TYPE::STATIONARY_NPC, 20, DIRECTIONS::DOWN, 308
.addr SPRITEDEF_DOCTOR
OBJ_LOAD_NUMBER 78
OBJ_SUBROUTINE OBJ_ELLAY_DOCTOR, SUBR_DOCTOR-OBJ_ELLAY_DOCTOR
OBJ_STOP