.ifndef VER_JP
OBJ_UNK2_OJSUBROUTINE2 := $8D31
OBJ_UNK2 := $8D09
.else
OBJ_UNK2_OJSUBROUTINE2 := $8C8B
OBJ_UNK2 := $8C63
.endif

OBJ_BANK_1B:
.addr OBJ_MYHOME_HOUSEEXIT
.addr OBJ_MYHOME_HOUSEUPSTAIRS
.addr OBJ_MYHOME_HOUSEBASEMENTENTRANCE
.addr OBJ_MYHOME_MIMMIEROOMEXIT
.addr OBJ_MYHOME_MINNIEROOMEXIT
.addr OBJ_REINDEER_HEALERHOUSEEXIT
.addr OBJ_PODUNK_HEALERHOUSEEXIT
.addr OBJ_SNOWMAN_HEALERHOUSEEXIT
.addr OBJ_REINDEER_MOUTHWASHHOUSEEXIT
.addr OBJ_MYHOME_MOM_INVASION
.addr OBJ_MYHOME_MOM
.addr OBJ_MYHOME_MINNIE_INVASION
.addr OBJ_MYHOME_MINNIE
.addr OBJ_MYHOME_MIMMIE
.addr OBJ_MYHOME_PHONE
.addr OBJ_MYHOME_DOLL_INVASION
.addr OBJ_MYHOME_DOLL
.addr OBJ_MYHOME_MINNIELAMP
.addr OBJ_MISLAY_MOUTHWASHGUY
.addr OBJ_MISLAY_MOUTHWASHKID
.addr OBJ_PODUNK_HEALER
.addr OBJ_REINDEER_HEALER
.addr OBJ_SNOWMAN_HEALER
.addr OBJ_PODUNK_HEALERPHONE
.addr OBJ_REINDEER_HEALERPHONE
.addr OBJ_SNOWMAN_HEALERPHONE
.addr OBJ_SWAMP_HOUSEEXIT
.addr OBJ_SWAMP_HOUSEPIPPI
.addr 0

OBJ_MYHOME_HOUSEEXIT:
objectDef OBJ_TYPE::DOOR, $2e, DIRECTIONS::RIGHT, $86
doorArgDef $6, $B1, DIRECTIONS::DOWN, $13C

OBJ_MYHOME_HOUSEUPSTAIRS:
objectDef OBJ_TYPE::STAIRS, $22, DIRECTIONS::LEFT, $85
doorArgDef $0, $22, DIRECTIONS::RIGHT, $E6

OBJ_MYHOME_HOUSEBASEMENTENTRANCE:
objectDef $18, $29, DIRECTIONS::UP, $83
.byte SCRIPTS::J_UNK, OBJ_THING2_JUNK0-OBJ_MYHOME_HOUSEBASEMENTENTRANCE
OBJ_IS_NOT_USING  $55, OBJ_THING2_IJUSE1-OBJ_MYHOME_HOUSEBASEMENTENTRANCE
OBJ_DIALOGUE UMSG::DOOR_UNLOCKED
OBJ_PLAY_SOUND2 $8
OBJ_TELEPORT $11, $2FD, DIRECTIONS::LEFT, $86
OBJ_STOP
      OBJ_THING2_IJUSE1:
OBJ_IS_NOT_USING  $56, OBJ_THING2_IJUSE2-OBJ_MYHOME_HOUSEBASEMENTENTRANCE
OBJ_JUMP  OBJ_THING2J_JUMP3-OBJ_MYHOME_HOUSEBASEMENTENTRANCE
      OBJ_THING2_IJUSE2:
OBJ_IS_NOT_USING  $57, OBJ_THING2_IJUSE4-OBJ_MYHOME_HOUSEBASEMENTENTRANCE
      OBJ_THING2J_JUMP3:
OBJ_DIALOGUE UMSG::DOOR_KEYFAIL
      OBJ_THING2_IJUSE4:
OBJ_IS_NOT_TOUCHING  OBJ_THING2_JUNK0-OBJ_MYHOME_HOUSEBASEMENTENTRANCE
OBJ_DIALOGUE UMSG::DOOR_LOCKED
      OBJ_THING2_JUNK0:
OBJ_STOP

OBJ_MYHOME_MIMMIEROOMEXIT:
objectDef OBJ_TYPE::DOOR, $1ce, DIRECTIONS::RIGHT, $86
doorArgDef $0, $26, DIRECTIONS::DOWN, $E4

OBJ_MYHOME_MINNIEROOMEXIT:
objectDef OBJ_TYPE::DOOR, $27e, DIRECTIONS::RIGHT, $3f6
doorArgDef $0, $29, DIRECTIONS::DOWN, $E4

OBJ_REINDEER_HEALERHOUSEEXIT:
objectDef OBJ_TYPE::DOOR, $2e, DIRECTIONS::RIGHT, $a6
doorArgDef $6, $199, DIRECTIONS::DOWN, $338

OBJ_PODUNK_HEALERHOUSEEXIT:
objectDef OBJ_TYPE::DOOR, $e, DIRECTIONS::RIGHT, $c6
doorArgDef $6, $9D, DIRECTIONS::DOWN, $1F0

OBJ_SNOWMAN_HEALERHOUSEEXIT:
objectDef OBJ_TYPE::DOOR, $2e, DIRECTIONS::RIGHT, $106
doorArgDef $A, $381, DIRECTIONS::DOWN, $3D0

OBJ_REINDEER_MOUTHWASHHOUSEEXIT:
objectDef OBJ_TYPE::DOOR, $26e, DIRECTIONS::RIGHT, $86
doorArgDef $6, $160, DIRECTIONS::DOWN, $2CA

OBJ_MYHOME_MOM_INVASION:
objectDef OBJ_TYPE::STATIONARY_NPC_CHECKSPAWN, $2d, DIRECTIONS::LEFT, $86
.addr SPRITEDEF_172 ;sprite
OBJ_FLAG_DISAPPEAR  $A
OBJ_IS_NOT_TALKING  OBJ_MYHOME_MOM_INVASION_JTALK0-OBJ_MYHOME_MOM_INVASION
OBJ_DIALOGUE UMSG::MYHOME_MOM_INVASION
OBJ_IS_NOT_FLAG  $40, OBJ_MYHOME_MOM_INVASION_FJJUMP1-OBJ_MYHOME_MOM_INVASION
OBJ_JUMP  OBJ_MYHOME_MOM_INVASIONJ_JUMP2-OBJ_MYHOME_MOM_INVASION
      OBJ_MYHOME_MOM_INVASION_FJJUMP1:
OBJ_PLAY_MUSIC  $2F
OBJ_DIALOGUE UMSG::MYHOME_MOM_INVASION2
OBJ_STOP
      OBJ_MYHOME_MOM_INVASION_JTALK0:
OBJ_IS_SIGNAL  OBJ_MYHOME_MOM_INVASIONJ_JUMP2-OBJ_MYHOME_MOM_INVASION
OBJ_MOVE OBJ_MYHOME_MOM_INVASION_MOVE0
OBJ_SET_FLAG  $A
      OBJ_MYHOME_MOM_INVASIONJ_JUMP2:
OBJ_STOP
        OBJ_MYHOME_MOM_INVASION_MOVE0:
moveDef DIRECTIONS::LEFT, MOVE_CMD::MOVEFACE, $4
moveDef DIRECTIONS::DOWN, MOVE_CMD::ABOUTFACE, $1
OBJ_STOP

OBJ_MYHOME_MOM:
objectDef OBJ_TYPE::WANDERING_NPC_CHECKSPAWN, $29, DIRECTIONS::DOWN, $86
.addr SPRITEDEF_172 ;sprite
OBJ_FLAG_APPEAR  $A
OBJ_IS_NOT_TALKING  OBJ_MYHOME_MOM_JTALK0-OBJ_MYHOME_MOM
OBJ_IS_NOT_FLAG  $32, OBJ_MYHOME_MOM_FJJUMP1-OBJ_MYHOME_MOM
OBJ_PICK_CHARACTER  $1
OBJ_HAS_STATUS  $80, OBJ_MYHOME_MOM_SJPRESENT2-OBJ_MYHOME_MOM
.byte SCRIPTS::NJ_BELOWLEVEL, $5, OBJ_MYHOME_MOM_NJBELOWLEVEL3-OBJ_MYHOME_MOM
OBJ_DIALOGUE UMSG::MYHOME_MOM_HURT
OBJ_JUMP  OBJ_MYHOME_MOMJ_JUMP4-OBJ_MYHOME_MOM
      OBJ_MYHOME_MOM_NJBELOWLEVEL3:
OBJ_DIALOGUE UMSG::MYHOME_MOM
      OBJ_MYHOME_MOMJ_JUMP4:
OBJ_DIALOGUE UMSG::MYHOME_MOM_COOK
OBJ_SLEEP
OBJ_DIALOGUE UMSG::MYHOME_MOM_EAT
OBJ_STOP
      OBJ_MYHOME_MOM_SJPRESENT2:
OBJ_DIALOGUE UMSG::MYHOME_MOM_HELP
OBJ_STOP
      OBJ_MYHOME_MOM_FJJUMP1:
OBJ_DIALOGUE UMSG::MYHOME_MOM_INVASION
      OBJ_MYHOME_MOM_JTALK0:
OBJ_STOP

OBJ_MYHOME_MINNIE_INVASION:
objectDef OBJ_TYPE::WANDERING_NPC_CHECKSPAWN, $274, DIRECTIONS::RIGHT, $3f6
.addr SPRITEDEF_19F ;sprite
OBJ_FLAG_DISAPPEAR  $32
OBJ_IS_NOT_TALKING  OBJ_MYHOME_MINNIE_INVASION_JTALK0-OBJ_MYHOME_MINNIE_INVASION
OBJ_IS_NOT_FLAG  $25, OBJ_MYHOME_MINNIE_INVASION_FJJUMP1-OBJ_MYHOME_MINNIE_INVASION
OBJ_IS_NOT_FLAG  $26, OBJ_MYHOME_MINNIE_INVASION_FJJUMP2-OBJ_MYHOME_MINNIE_INVASION
OBJ_DIALOGUE UMSG::MYHOME_JUICE
OBJ_NOT_HAS_ITEM  $0, OBJ_MYHOME_MINNIE_INVASION_IJHASITEM3-OBJ_MYHOME_MINNIE_INVASION
OBJ_PLAY_SOUND  $6
OBJ_PICK_ITEM  $3C
OBJ_GIVE_ITEM OBJ_MYHOME_MINNIE_INVASION_JTALK0-OBJ_MYHOME_MINNIE_INVASION
OBJ_STOP
      OBJ_MYHOME_MINNIE_INVASION_IJHASITEM3:
OBJ_DIALOGUE UMSG::PODUNK_PIPPI_NOROOM2
OBJ_STOP
      OBJ_MYHOME_MINNIE_INVASION_FJJUMP2:
OBJ_DIALOGUE UMSG::MYHOME_MINNIE_INVASION_FIGHT
OBJ_DIALOGUE UMSG::MYHOME_MINNIE_INVASION_FIGHT_2
OBJ_STOP
      OBJ_MYHOME_MINNIE_INVASION_FJJUMP1:
OBJ_DIALOGUE UMSG::MYHOME_MINNIE_INVASION
      OBJ_MYHOME_MINNIE_INVASION_JTALK0:
OBJ_STOP

OBJ_MYHOME_MINNIE:
objectDef OBJ_TYPE::WANDERING_NPC_CHECKSPAWN, $27, DIRECTIONS::DOWN, $85
.addr SPRITEDEF_19F ;sprite
OBJ_FLAG_APPEAR  $32
OBJ_IS_NOT_TALKING  OBJ_MYHOME_MINNIE_JTALK0-OBJ_MYHOME_MINNIE
OBJ_DIALOGUE UMSG::MYHOME_MINNIE
OBJ_DIALOGUE UMSG::ELLAY_LHBOUNCERGIRL
OBJ_MENU UMSG::MYHOME_MINNIE_STORAGE, OBJ_MYHOME_MINNIE_JJCUSTOMMENU_21-OBJ_MYHOME_MINNIE,OBJ_MYHOME_MINNIE_JJCUSTOMMENU_B2-OBJ_MYHOME_MINNIE
      OBJ_MYHOME_MINNIEJ_JUMP7:
.byte SCRIPTS::J_NOITEMS, OBJ_MYHOME_MINNIE_JNOITEMS3-OBJ_MYHOME_MINNIE
OBJ_CHOOSE_ITEM OBJ_MYHOME_MINNIE_JJCUSTOMMENU_B2-OBJ_MYHOME_MINNIE
OBJ_IS_NOT_SELECTED $3, OBJ_MYHOME_MINNIE_IJSELECTEDITEM4-OBJ_MYHOME_MINNIE
OBJ_JUMP  OBJ_MYHOME_MINNIEJ_JUMP5-OBJ_MYHOME_MINNIE
      OBJ_MYHOME_MINNIE_IJSELECTEDITEM4:
.byte SCRIPTS::J_ADDITEMCLOSET, OBJ_MYHOME_MINNIE_JADDITEMCLOSET6-OBJ_MYHOME_MINNIE
OBJ_PLAY_SOUND  $6
OBJ_REMOVE_ITEM  OBJ_MYHOME_MINNIE_JTALK0-OBJ_MYHOME_MINNIE
OBJ_DIALOGUE UMSG::MYHOME_MINNIE_STORAGE_STASH
OBJ_YESNO_IS_NO  OBJ_MYHOME_MINNIE_JJCUSTOMMENU_B2-OBJ_MYHOME_MINNIE
OBJ_JUMP  OBJ_MYHOME_MINNIEJ_JUMP7-OBJ_MYHOME_MINNIE
      OBJ_MYHOME_MINNIE_JJCUSTOMMENU_21:
.byte SCRIPTS::J_NOITEMSCLOSET, OBJ_MYHOME_MINNIE_JNOITEMSCLOSET8-OBJ_MYHOME_MINNIE
.byte SCRIPTS::J_CHOOSEITEMCLOSET, OBJ_MYHOME_MINNIE_JJCUSTOMMENU_B2-OBJ_MYHOME_MINNIE
OBJ_PICK_CHARACTER  $1
OBJ_PICK_CHARACTER_J  $1, OBJ_MYHOME_MINNIE_CJSELECTPARTY9-OBJ_MYHOME_MINNIE
      OBJ_MYHOME_MINNIEJ_JUMP12:
.byte SCRIPTS::J_CHOOSECHAR, OBJ_MYHOME_MINNIE_JJCUSTOMMENU_B2-OBJ_MYHOME_MINNIE
      OBJ_MYHOME_MINNIE_CJSELECTPARTY9:
OBJ_GIVE_ITEM OBJ_MYHOME_MINNIE_JGIVEITEM10-OBJ_MYHOME_MINNIE
OBJ_PLAY_SOUND  $6
.byte SCRIPTS::J_TAKEITEMCLOSET, OBJ_MYHOME_MINNIE_JTALK0-OBJ_MYHOME_MINNIE
OBJ_DIALOGUE UMSG::MYHOME_MINNIE_STORAGE_TAKE
OBJ_YESNO_IS_NO  OBJ_MYHOME_MINNIE_JJCUSTOMMENU_B2-OBJ_MYHOME_MINNIE
OBJ_JUMP  OBJ_MYHOME_MINNIE_JJCUSTOMMENU_21-OBJ_MYHOME_MINNIE
      OBJ_MYHOME_MINNIE_JGIVEITEM10:
OBJ_PICK_CHARACTER_J  $1, OBJ_MYHOME_MINNIE_CJSELECTPARTY11-OBJ_MYHOME_MINNIE
OBJ_DIALOGUE UMSG::MYHOME_MINNIE_STORAGE_INVFULL
OBJ_YESNO_IS_NO  OBJ_MYHOME_MINNIE_JJCUSTOMMENU_B2-OBJ_MYHOME_MINNIE
OBJ_JUMP  OBJ_MYHOME_MINNIEJ_JUMP12-OBJ_MYHOME_MINNIE
      OBJ_MYHOME_MINNIE_CJSELECTPARTY11:
OBJ_DIALOGUE UMSG::PODUNK_PIPPI_NOROOM2
OBJ_STOP
      OBJ_MYHOME_MINNIE_JADDITEMCLOSET6:
OBJ_DIALOGUE UMSG::MYHOME_MINNIE_STORAGE_FULL
OBJ_STOP
      OBJ_MYHOME_MINNIEJ_JUMP5:
OBJ_DIALOGUE UMSG::MYHOME_MINNIE_STORAGE_CANT
OBJ_STOP
      OBJ_MYHOME_MINNIE_JJCUSTOMMENU_B2:
OBJ_DIALOGUE UMSG::MYHOME_MINNIE_STORAGE_BYE
OBJ_STOP
      OBJ_MYHOME_MINNIE_JNOITEMS3:
OBJ_DIALOGUE UMSG::MYHOME_MINNIE_STORAGE_INVNOTHING
OBJ_STOP
      OBJ_MYHOME_MINNIE_JNOITEMSCLOSET8:
OBJ_DIALOGUE UMSG::MYHOME_MINNIE_STORAGE_NOTHING
      OBJ_MYHOME_MINNIE_JTALK0:
OBJ_STOP

OBJ_MYHOME_MIMMIE:
objectDef OBJ_TYPE::WANDERING_NPC, $1cb, DIRECTIONS::RIGHT, $86
.addr SPRITEDEF_18B ;sprite
OBJ_IS_NOT_TALKING  OBJ_MYHOME_MIMMIE_JTALK0-OBJ_MYHOME_MIMMIE
OBJ_IS_NOT_FLAG  $26, OBJ_MYHOME_MIMMIE_FJJUMP1-OBJ_MYHOME_MIMMIE
OBJ_IS_NOT_FLAG  $F7, OBJ_MYHOME_MIMMIE_FJJUMP2-OBJ_MYHOME_MIMMIE
OBJ_IS_NOT_FLAG  $32, OBJ_MYHOME_MIMMIE_FJJUMP3-OBJ_MYHOME_MIMMIE
OBJ_DIALOGUE UMSG::MYHOME_MIMMIE
OBJ_STOP
      OBJ_MYHOME_MIMMIE_FJJUMP3:
OBJ_DIALOGUE UMSG::MYHOME_JUICE
OBJ_NOT_HAS_ITEM  $0, OBJ_MYHOME_MIMMIE_IJHASITEM4-OBJ_MYHOME_MIMMIE
OBJ_PLAY_SOUND  $6
OBJ_PICK_ITEM  $3C
OBJ_GIVE_ITEM OBJ_MYHOME_MIMMIE_JTALK0-OBJ_MYHOME_MIMMIE
OBJ_STOP
      OBJ_MYHOME_MIMMIE_IJHASITEM4:
OBJ_DIALOGUE UMSG::PODUNK_PIPPI_NOROOM2
OBJ_STOP
      OBJ_MYHOME_MIMMIE_FJJUMP2:
OBJ_DIALOGUE UMSG::MYHOME_MIMMIE_INVASION_FIGHT
OBJ_STOP
      OBJ_MYHOME_MIMMIE_FJJUMP1:
OBJ_DIALOGUE UMSG::MYHOME_MIMMIE_INVASION2
      OBJ_MYHOME_MIMMIE_JTALK0:
OBJ_STOP

OBJ_MYHOME_PHONE:
objectDef $19, $2b, DIRECTIONS::UP, $84
.addr SPRITEDEF_19C ;sprite
OBJ_IS_NOT_TALKING  OBJ_MYHOME_PHONE_JTALK0-OBJ_MYHOME_PHONE
OBJ_DIALOGUE UMSG::PHONE_GRAB
OBJ_IS_NOT_FLAG  $26, OBJ_MYHOME_PHONE_FJJUMP1-OBJ_MYHOME_PHONE
OBJ_PLAY_MUSIC  $12
OBJ_JUMP  OBJ_MYHOME_PHONEJ_JUMP2-OBJ_MYHOME_PHONE
      OBJ_MYHOME_PHONE_FJJUMP1:
OBJ_PLAY_MUSIC  $10
      OBJ_MYHOME_PHONEJ_JUMP2:
OBJ_IS_NOT_FLAG  $40, OBJ_MYHOME_PHONE_FJJUMP3-OBJ_MYHOME_PHONE
OBJ_DIALOGUE UMSG::PHONE_INTRO
.byte SCRIPTS::J_NONEWMONEY, OBJ_MYHOME_PHONE_JNONEWMONEY4-OBJ_MYHOME_PHONE
OBJ_DIALOGUE UMSG::PHONE_NEWMONEY
      OBJ_MYHOME_PHONE_JNONEWMONEY4:
OBJ_DIALOGUE UMSG::PHONE_NEXTLVL
OBJ_PICK_CHARACTER_J  $0, OBJ_MYHOME_PHONE_CJSELECTPARTY5-OBJ_MYHOME_PHONE
.byte SCRIPTS::GETCHARNEXTEXP
OBJ_DIALOGUE UMSG::PHONE_EXPLVL
OBJ_PICK_CHARACTER_J  $1, OBJ_MYHOME_PHONE_CJSELECTPARTY5-OBJ_MYHOME_PHONE
.byte SCRIPTS::GETCHARNEXTEXP
OBJ_DIALOGUE UMSG::PHONE_EXPLVL
OBJ_PICK_CHARACTER_J  $2, OBJ_MYHOME_PHONE_CJSELECTPARTY5-OBJ_MYHOME_PHONE
.byte SCRIPTS::GETCHARNEXTEXP
OBJ_DIALOGUE UMSG::PHONE_EXPLVL
      OBJ_MYHOME_PHONE_CJSELECTPARTY5:
OBJ_DIALOGUE UMSG::PHONE_SAVEPROMPT
OBJ_MENU UMSG::MENU_YES_NO, OBJ_MYHOME_PHONE_JJCUSTOMMENU_26-OBJ_MYHOME_PHONE,OBJ_MYHOME_PHONE_JJCUSTOMMENU_26-OBJ_MYHOME_PHONE
OBJ_SAVE
OBJ_DIALOGUE UMSG::PHONE_SAVED_RESETPROMPT
OBJ_MENU UMSG::MENU_CONTINUE_REST, OBJ_MYHOME_PHONE_JJCUSTOMMENU_27-OBJ_MYHOME_PHONE,OBJ_MYHOME_PHONE_JJCUSTOMMENU_B8-OBJ_MYHOME_PHONE
      OBJ_MYHOME_PHONE_JJCUSTOMMENU_B8:
OBJ_DIALOGUE UMSG::PHONE_RESET_NO
OBJ_DIALOGUE UMSG::PHONE_END
OBJ_STOP
      OBJ_MYHOME_PHONE_JJCUSTOMMENU_27:
OBJ_DIALOGUE UMSG::PHONE_RESET_YES
OBJ_DIALOGUE UMSG::PHONE_END
OBJ_RESET
      OBJ_MYHOME_PHONE_JJCUSTOMMENU_26:
OBJ_DIALOGUE UMSG::PHONE_GOODLUCK
OBJ_DIALOGUE UMSG::PHONE_END
OBJ_STOP
      OBJ_MYHOME_PHONE_FJJUMP3:
OBJ_DIALOGUE UMSG::PHONE_INTRO
OBJ_DIALOGUE UMSG::MYHOME_PHONE
OBJ_DIALOGUE UMSG::PHONE_END
OBJ_SET_FLAG  $40
OBJ_IS_NOT_FLAG  $26, OBJ_MYHOME_PHONE_JTALK0-OBJ_MYHOME_PHONE
OBJ_SIGNAL  $9
      OBJ_MYHOME_PHONE_JTALK0:
OBJ_STOP

OBJ_MYHOME_DOLL_INVASION:
objectDef $27, $1c6, DIRECTIONS::UP, $87
.addr SPRITEDEF_19B ;sprite
OBJ_FLAG_DISAPPEAR  $26
OBJ_IS_NOT_TOUCHING  OBJ_MYHOME_DOLL_INVASION_JTOUCH0-OBJ_MYHOME_DOLL_INVASION
OBJ_JUMP  OBJ_MYHOME_DOLL_INVASIONJ_JUMP1-OBJ_MYHOME_DOLL_INVASION
      OBJ_MYHOME_DOLL_INVASION_JTOUCH0:
OBJ_IS_NOT_CHECKING  OBJ_MYHOME_DOLL_INVASION_JCHECK2-OBJ_MYHOME_DOLL_INVASION
OBJ_DIALOGUE UMSG::CANARY_PILLAR
      OBJ_MYHOME_DOLL_INVASIONJ_JUMP1:
OBJ_CLEAR_FLAG  $F8
OBJ_CLEAR_FLAG  $30
OBJ_BATTLE  $9F
OBJ_SET_FLAG  $30
OBJ_SET_FLAG  $26
OBJ_SET_FLAG  $25
OBJ_PLAY_MUSIC  $12
OBJ_MOVE OBJ_MYHOME_DOLL_INVASION_MOVE0
OBJ_DIALOGUE UMSG::MYHOME_INVASION
OBJ_IS_NOT_FLAG  $40, OBJ_MYHOME_DOLL_INVASION_FJJUMP3-OBJ_MYHOME_DOLL_INVASION
OBJ_SET_FLAG  $A
      OBJ_MYHOME_DOLL_INVASION_FJJUMP3:
OBJ_MOVE OBJ_MYHOME_DOLL_INVASION_MOVE1
      OBJ_MYHOME_DOLL_INVASION_JCHECK2:
OBJ_STOP
        OBJ_MYHOME_DOLL_INVASION_MOVE0:
moveDef DIRECTIONS::UP, $A, $1
.byte 3
        OBJ_MYHOME_DOLL_INVASION_MOVE1:
OBJ_STOP

OBJ_MYHOME_DOLL:
objectDef $1d, $1ca, DIRECTIONS::UP, $83
.addr SPRITEDEF_19B ;sprite
OBJ_FLAG_APPEAR  $26
OBJ_IS_NOT_CHECKING  OBJ_MYHOME_DOLL_JCHECK0-OBJ_MYHOME_DOLL
OBJ_DIALOGUE UMSG::MYHOME_DOLL
OBJ_PLAY_MUSIC  $24
OBJ_DELAY  $F0
OBJ_PLAY_MUSIC  $12
OBJ_SET_FLAG  $F7
OBJ_DIALOGUE UMSG::REMEMBER_MELODY
.ifdef VER_JP
.byte $65
.endif
      OBJ_MYHOME_DOLL_JCHECK0:
OBJ_STOP

OBJ_MYHOME_MINNIELAMP:
objectDef $27, $279, DIRECTIONS::UP, $3f5
.addr SPRITEDEF_19D ;sprite
OBJ_FLAG_DISAPPEAR  $25
OBJ_IS_NOT_TOUCHING  OBJ_MYHOME_MINNIELAMP_JTOUCH0-OBJ_MYHOME_MINNIELAMP
OBJ_JUMP  OBJ_MYHOME_MINNIELAMPJ_JUMP1-OBJ_MYHOME_MINNIELAMP
      OBJ_MYHOME_MINNIELAMP_JTOUCH0:
OBJ_IS_NOT_CHECKING  OBJ_MYHOME_MINNIELAMP_JCHECK2-OBJ_MYHOME_MINNIELAMP
OBJ_DIALOGUE UMSG::CANARY_PILLAR
      OBJ_MYHOME_MINNIELAMPJ_JUMP1:
OBJ_MOVE OBJ_MYHOME_MINNIELAMP_MOVE0
OBJ_CLEAR_FLAG  $F8
OBJ_CLEAR_FLAG  $30
OBJ_BATTLE  $A0
OBJ_SET_FLAG  $F8
OBJ_SET_FLAG  $30
OBJ_SET_FLAG  $25
OBJ_MOVE OBJ_MYHOME_MINNIELAMP_MOVE1
      OBJ_MYHOME_MINNIELAMP_JCHECK2:
OBJ_STOP
        OBJ_MYHOME_MINNIELAMP_MOVE0:
moveDef DIRECTIONS::UP, MOVE_CMD::ABOUTFACE, $1
.byte 3
        OBJ_MYHOME_MINNIELAMP_MOVE1:
OBJ_STOP

OBJ_MISLAY_MOUTHWASHGUY:
objectDef OBJ_TYPE::STATIONARY_NPC, $265, DIRECTIONS::DOWN, $86
.addr SPRITEDEF_183 ;sprite
OBJ_IS_NOT_TALKING  OBJ_MISLAY_MOUTHWASHGUY_JTALK0-OBJ_MISLAY_MOUTHWASHGUY
OBJ_IS_NOT_FLAG  $41, OBJ_MISLAY_MOUTHWASHGUY_FJJUMP1-OBJ_MISLAY_MOUTHWASHGUY
OBJ_DIALOGUE UMSG::MISLAY_MOUTHWASHGUY_LEAVE
OBJ_STOP
      OBJ_MISLAY_MOUTHWASHGUY_FJJUMP1:
OBJ_DIALOGUE UMSG::MISLAY_MOUTHWASHGUY_DENTURELESS
OBJ_STOP
      OBJ_MISLAY_MOUTHWASHGUY_JTALK0:
OBJ_IS_NOT_USING  $63, OBJ_MISLAY_MOUTHWASHGUY_IJUSE2-OBJ_MISLAY_MOUTHWASHGUY
OBJ_PICK_ITEM  $63
OBJ_REMOVE_ITEM  OBJ_MISLAY_MOUTHWASHGUY_JREMOVEITEM3-OBJ_MISLAY_MOUTHWASHGUY
OBJ_DIALOGUE UMSG::MISLAY_MOUTHWASHGUY_DENTURES
      OBJ_MISLAY_MOUTHWASHGUYJ_JUMP6:
OBJ_PICK_ITEM  $44
OBJ_PLAY_SOUND  $6
OBJ_GIVE_ITEM OBJ_MISLAY_MOUTHWASHGUY_JGIVEITEM4-OBJ_MISLAY_MOUTHWASHGUY
OBJ_DELAY  $28
OBJ_NOT_HAS_ITEM  $0, OBJ_MISLAY_MOUTHWASHGUY_IJHASITEM5-OBJ_MISLAY_MOUTHWASHGUY
OBJ_JUMP  OBJ_MISLAY_MOUTHWASHGUYJ_JUMP6-OBJ_MISLAY_MOUTHWASHGUY
      OBJ_MISLAY_MOUTHWASHGUY_IJHASITEM5:
OBJ_SET_FLAG  $41
OBJ_STOP
      OBJ_MISLAY_MOUTHWASHGUY_JGIVEITEM4:
OBJ_DIALOGUE UMSG::MISLAY_MOUTHWASHGUY_DENTURELESS
OBJ_STOP
      OBJ_MISLAY_MOUTHWASHGUY_IJUSE2:
OBJ_IS_NOT_CASTING  $1, OBJ_MISLAY_MOUTHWASHGUY_JREMOVEITEM3-OBJ_MISLAY_MOUTHWASHGUY
OBJ_DIALOGUE UMSG::MISLAY_MOUTHWASHGUY_DENTURES2
      OBJ_MISLAY_MOUTHWASHGUY_JREMOVEITEM3:
OBJ_STOP

OBJ_MISLAY_MOUTHWASHKID:
objectDef OBJ_TYPE::WANDERING_NPC, $269, DIRECTIONS::RIGHT, $86
.addr SPRITEDEF_C2 ;sprite
OBJ_IS_NOT_TALKING  OBJ_MISLAY_MOUTHWASHKID_JTALK0-OBJ_MISLAY_MOUTHWASHKID
OBJ_IS_NOT_FLAG  $41, OBJ_MISLAY_MOUTHWASHKID_FJJUMP1-OBJ_MISLAY_MOUTHWASHKID
OPJ_LOAD_NUMBER 10
OBJ_DIALOGUE UMSG::MISLAY_MOUTHWASHKID_TAKE
OBJ_YESNO_IS_NO  OBJ_MISLAY_MOUTHWASHKID_JYESNO2-OBJ_MISLAY_MOUTHWASHKID
OBJ_NOT_HAS_ITEM  $0, OBJ_MISLAY_MOUTHWASHKID_IJHASITEM3-OBJ_MISLAY_MOUTHWASHKID
OBJ_PICK_ITEM  $44
OPJ_LOAD_NUMBER 10
OBJ_TAKE_MONEY OBJ_MISLAY_MOUTHWASHKID_JTAKEMONEY4-OBJ_MISLAY_MOUTHWASHKID
OBJ_PLAY_SOUND  $6
OBJ_PICK_ITEM  $44
OBJ_GIVE_ITEM OBJ_MISLAY_MOUTHWASHKID_JTALK0-OBJ_MISLAY_MOUTHWASHKID
OBJ_STOP
      OBJ_MISLAY_MOUTHWASHKID_JTAKEMONEY4:
OBJ_DIALOGUE UMSG::MISLAY_MOUTHWASHKID_NOMONEY
OBJ_STOP
      OBJ_MISLAY_MOUTHWASHKID_IJHASITEM3:
OBJ_DIALOGUE UMSG::MERRYSVILLE_QUESTIONNAIRE_NOROOM
OBJ_STOP
      OBJ_MISLAY_MOUTHWASHKID_JYESNO2:
OBJ_DIALOGUE UMSG::MISLAY_MOUTHWASHKID_NOTAKE
OBJ_STOP
      OBJ_MISLAY_MOUTHWASHKID_FJJUMP1:
OBJ_DIALOGUE UMSG::MISLAY_MOUTHWASHKID
      OBJ_MISLAY_MOUTHWASHKID_JTALK0:
OBJ_STOP

OBJ_PODUNK_HEALER:
objectDef OBJ_TYPE::WANDERING_NPC, $4, DIRECTIONS::RIGHT, $c4
.addr SPRITEDEF_183 ;sprite
OPJ_LOAD_NUMBER 30
OBJ_SUBROUTINE OBJ_PODUNK_HEALER, OBJ_PODUNK_HEALER_OJSUBROUTINE0-OBJ_PODUNK_HEALER
OBJ_STOP
      OBJ_PODUNK_HEALER_OJSUBROUTINE0:
OBJ_IS_NOT_TALKING  OBJ_PODUNK_HEALER_JTALK0-OBJ_PODUNK_HEALER
OBJ_DIALOGUE UMSG::HEALER
OBJ_MENU UMSG::HEALER_MENU, OBJ_PODUNK_HEALER_JJCUSTOMMENU_21-OBJ_PODUNK_HEALER,OBJ_PODUNK_HEALER_JJCUSTOMMENU_B2-OBJ_PODUNK_HEALER
.byte SCRIPTS::N_MULNUMBER, 60
OBJ_DIALOGUE UMSG::HEALER_PRICE
OBJ_YESNO_IS_NO  OBJ_PODUNK_HEALER_JJCUSTOMMENU_B2-OBJ_PODUNK_HEALER
OBJ_TAKE_MONEY OBJ_PODUNK_HEALER_JTAKEMONEY3-OBJ_PODUNK_HEALER
OBJ_PICK_CHARACTER_J  $1, OBJ_PODUNK_HEALER_CJSELECTPARTY4-OBJ_PODUNK_HEALER
.byte SCRIPTS::J_CHOOSECHAR, OBJ_PODUNK_HEALER_JCHOOSECHAR5-OBJ_PODUNK_HEALER
OBJ_JUMP  OBJ_PODUNK_HEALERJ_JUMP6-OBJ_PODUNK_HEALER
      OBJ_PODUNK_HEALER_CJSELECTPARTY4:
OBJ_PICK_CHARACTER_J  $0, OBJ_PODUNK_HEALER_JTALK0-OBJ_PODUNK_HEALER
      OBJ_PODUNK_HEALERJ_JUMP6:
OBJ_HAS_STATUS  $80, OBJ_PODUNK_HEALER_SJPRESENT7-OBJ_PODUNK_HEALER
OBJ_NOT_MAX_PP  OBJ_PODUNK_HEALER_JNOTMAXPP8-OBJ_PODUNK_HEALER
OBJ_GIVE_WEAPON OBJ_PODUNK_HEALER_JTALK0-OBJ_PODUNK_HEALER
OBJ_DIALOGUE UMSG::PODUNK_HOSPITALDOCTOR_NORMAL
OBJ_RETURN
      OBJ_PODUNK_HEALER_JNOTMAXPP8:
OBJ_PPHEAL  $FF
OBJ_NOT_MAX_PP  OBJ_PODUNK_HEALER_JNOTMAXPP8-OBJ_PODUNK_HEALER
OBJ_DIALOGUE UMSG::HEALER_FIXED
OBJ_PLAY_SOUND  $7
OBJ_RETURN
      OBJ_PODUNK_HEALER_JJCUSTOMMENU_21:
OBJ_DIALOGUE UMSG::HEALER_PRICE
OBJ_YESNO_IS_NO  OBJ_PODUNK_HEALER_JJCUSTOMMENU_B2-OBJ_PODUNK_HEALER
OBJ_TAKE_MONEY OBJ_PODUNK_HEALER_JTAKEMONEY3-OBJ_PODUNK_HEALER
OBJ_PICK_CHARACTER_J  $1, OBJ_PODUNK_HEALER_CJSELECTPARTY9-OBJ_PODUNK_HEALER
OBJ_DIALOGUE UMSG::HEALER_WHO
.byte SCRIPTS::J_CHOOSECHAR, OBJ_PODUNK_HEALER_JCHOOSECHAR5-OBJ_PODUNK_HEALER
OBJ_JUMP  OBJ_PODUNK_HEALERJ_JUMP10-OBJ_PODUNK_HEALER
      OBJ_PODUNK_HEALER_CJSELECTPARTY9:
OBJ_PICK_CHARACTER_J  $0, OBJ_PODUNK_HEALER_JTALK0-OBJ_PODUNK_HEALER
      OBJ_PODUNK_HEALERJ_JUMP10:
OBJ_HAS_STATUS  $80, OBJ_PODUNK_HEALER_SJPRESENT7-OBJ_PODUNK_HEALER
OBJ_HAS_STATUS  $40, OBJ_PODUNK_HEALER_SJPRESENT11-OBJ_PODUNK_HEALER
OBJ_GIVE_WEAPON OBJ_PODUNK_HEALER_JTALK0-OBJ_PODUNK_HEALER
OBJ_DIALOGUE UMSG::HEALER_SOFTEN_FAIL
OBJ_RETURN
      OBJ_PODUNK_HEALER_SJPRESENT11:
OBJ_DIALOGUE UMSG::HEALER_FIXED
OBJ_PLAY_SOUND  $7
OBJ_AND_STATUS  $BF
OBJ_RETURN
      OBJ_PODUNK_HEALER_JCHOOSECHAR5:
OBJ_GIVE_WEAPON OBJ_PODUNK_HEALER_JTALK0-OBJ_PODUNK_HEALER
      OBJ_PODUNK_HEALER_JJCUSTOMMENU_B2:
OBJ_DIALOGUE UMSG::HEALER_NO
OBJ_RETURN
      OBJ_PODUNK_HEALER_JTAKEMONEY3:
OBJ_DIALOGUE UMSG::HEALER_BROKE
OBJ_RETURN
      OBJ_PODUNK_HEALER_SJPRESENT7:
OBJ_GIVE_WEAPON OBJ_PODUNK_HEALER_JTALK0-OBJ_PODUNK_HEALER
OBJ_DIALOGUE UMSG::HEALER_MAN
      OBJ_PODUNK_HEALER_JTALK0:
OBJ_RETURN

OBJ_REINDEER_HEALER:
objectDef OBJ_TYPE::WANDERING_NPC, $24, DIRECTIONS::RIGHT, $a4
.addr SPRITEDEF_183 ;sprite
OPJ_LOAD_NUMBER 75

;jp is a normal healer
.ifdef VER_JP
OBJ_SUBROUTINE OBJ_PODUNK_HEALER, OBJ_PODUNK_HEALER_OJSUBROUTINE0-OBJ_PODUNK_HEALER
OBJ_STOP
.else
OBJ_SUBROUTINE OBJ_REINDEER_HEALER, OBJ_REINDEER_HEALER_OJSUBROUTINE1-OBJ_REINDEER_HEALER
OBJ_STOP
      OBJ_REINDEER_HEALER_OJSUBROUTINE1:
OBJ_IS_NOT_TALKING  OBJ_REINDEER_HEALER_JTALK0-OBJ_REINDEER_HEALER
OBJ_DIALOGUE UMSG::HEALER_INTRO
OBJ_MENU UMSG::HEALER_MENU, OBJ_REINDEER_HEALER_JJCUSTOMMENU_21-OBJ_REINDEER_HEALER,OBJ_REINDEER_HEALER_JJCUSTOMMENU_B2-OBJ_REINDEER_HEALER
.byte SCRIPTS::N_MULNUMBER, 60
OBJ_DIALOGUE UMSG::HEALER_PRICE
OBJ_YESNO_IS_NO  OBJ_REINDEER_HEALER_JJCUSTOMMENU_B2-OBJ_REINDEER_HEALER
OBJ_TAKE_MONEY OBJ_REINDEER_HEALER_JTAKEMONEY3-OBJ_REINDEER_HEALER
OBJ_PICK_CHARACTER_J  $1, OBJ_REINDEER_HEALER_CJSELECTPARTY4-OBJ_REINDEER_HEALER
.byte SCRIPTS::J_CHOOSECHAR, OBJ_REINDEER_HEALER_JCHOOSECHAR5-OBJ_REINDEER_HEALER
OBJ_JUMP  OBJ_REINDEER_HEALERJ_JUMP6-OBJ_REINDEER_HEALER
      OBJ_REINDEER_HEALER_CJSELECTPARTY4:
OBJ_PICK_CHARACTER_J  $0, OBJ_REINDEER_HEALER_JTALK0-OBJ_REINDEER_HEALER
      OBJ_REINDEER_HEALERJ_JUMP6:
OBJ_HAS_STATUS  $80, OBJ_REINDEER_HEALER_SJPRESENT7-OBJ_REINDEER_HEALER
OBJ_NOT_MAX_PP  OBJ_REINDEER_HEALER_JNOTMAXPP8-OBJ_REINDEER_HEALER
OBJ_GIVE_WEAPON OBJ_REINDEER_HEALER_JTALK0-OBJ_REINDEER_HEALER
OBJ_DIALOGUE UMSG::PODUNK_HOSPITALDOCTOR_NORMAL
OBJ_RETURN
      OBJ_REINDEER_HEALER_JNOTMAXPP8:
OBJ_PPHEAL  $FF
OBJ_NOT_MAX_PP  OBJ_REINDEER_HEALER_JNOTMAXPP8-OBJ_REINDEER_HEALER
OBJ_DIALOGUE UMSG::HEALER_FIXED
OBJ_PLAY_SOUND  $7
OBJ_RETURN
      OBJ_REINDEER_HEALER_JJCUSTOMMENU_21:
OBJ_DIALOGUE UMSG::HEALER_PRICE
OBJ_YESNO_IS_NO  OBJ_REINDEER_HEALER_JJCUSTOMMENU_B2-OBJ_REINDEER_HEALER
OBJ_TAKE_MONEY OBJ_REINDEER_HEALER_JTAKEMONEY3-OBJ_REINDEER_HEALER
OBJ_PICK_CHARACTER_J  $1, OBJ_REINDEER_HEALER_CJSELECTPARTY9-OBJ_REINDEER_HEALER
OBJ_DIALOGUE UMSG::HEALER_WHO
.byte SCRIPTS::J_CHOOSECHAR, OBJ_REINDEER_HEALER_JCHOOSECHAR5-OBJ_REINDEER_HEALER
OBJ_JUMP  OBJ_REINDEER_HEALERJ_JUMP10-OBJ_REINDEER_HEALER
      OBJ_REINDEER_HEALER_CJSELECTPARTY9:
OBJ_PICK_CHARACTER_J  $0, OBJ_REINDEER_HEALER_JTALK0-OBJ_REINDEER_HEALER
      OBJ_REINDEER_HEALERJ_JUMP10:
OBJ_HAS_STATUS  $80, OBJ_REINDEER_HEALER_SJPRESENT7-OBJ_REINDEER_HEALER
OBJ_HAS_STATUS  $40, OBJ_REINDEER_HEALER_SJPRESENT11-OBJ_REINDEER_HEALER
OBJ_GIVE_WEAPON OBJ_REINDEER_HEALER_JTALK0-OBJ_REINDEER_HEALER
OBJ_DIALOGUE UMSG::HEALER_SOFTEN_FAIL
OBJ_RETURN
      OBJ_REINDEER_HEALER_SJPRESENT11:
OBJ_DIALOGUE UMSG::HEALER_FIXED
OBJ_PLAY_SOUND  $7
OBJ_AND_STATUS  $BF
OBJ_RETURN
      OBJ_REINDEER_HEALER_JCHOOSECHAR5:
OBJ_GIVE_WEAPON OBJ_REINDEER_HEALER_JTALK0-OBJ_REINDEER_HEALER
      OBJ_REINDEER_HEALER_JJCUSTOMMENU_B2:
OBJ_DIALOGUE UMSG::HEALER_NO
OBJ_RETURN
      OBJ_REINDEER_HEALER_JTAKEMONEY3:
OBJ_DIALOGUE UMSG::HEALER_BROKE
OBJ_RETURN
      OBJ_REINDEER_HEALER_SJPRESENT7:
OBJ_GIVE_WEAPON OBJ_REINDEER_HEALER_JTALK0-OBJ_REINDEER_HEALER
OBJ_DIALOGUE UMSG::HEALER_MAN
      OBJ_REINDEER_HEALER_JTALK0:
OBJ_RETURN
.endif

OBJ_SNOWMAN_HEALER:
objectDef OBJ_TYPE::WANDERING_NPC, $24, DIRECTIONS::RIGHT, $104
.addr SPRITEDEF_183 ;sprite
OPJ_LOAD_NUMBER 88

;jp is a normal healer
.ifdef VER_JP
OBJ_SUBROUTINE OBJ_PODUNK_HEALER, OBJ_PODUNK_HEALER_OJSUBROUTINE0-OBJ_PODUNK_HEALER
.else
OBJ_SUBROUTINE OBJ_REINDEER_HEALER, OBJ_REINDEER_HEALER_OJSUBROUTINE1-OBJ_REINDEER_HEALER
.endif
OBJ_STOP

OBJ_PODUNK_HEALERPHONE:
objectDef $19, $b, DIRECTIONS::UP, $c4
.addr SPRITEDEF_19C ;sprite
OBJ_IS_NOT_TALKING  OBJ_PODUNK_HEALERPHONE_JTALK0-OBJ_PODUNK_HEALERPHONE
OBJ_SUBROUTINE OBJ_UNK2, OBJ_UNK2_OJSUBROUTINE2-OBJ_UNK2
      OBJ_PODUNK_HEALERPHONE_JTALK0:
OBJ_STOP

OBJ_REINDEER_HEALERPHONE:
objectDef $19, $2b, DIRECTIONS::UP, $a4
.addr SPRITEDEF_19C ;sprite
OBJ_IS_NOT_TALKING  OBJ_REINDEER_HEALERPHONE_JTALK0-OBJ_REINDEER_HEALERPHONE
OBJ_SUBROUTINE OBJ_UNK2, OBJ_UNK2_OJSUBROUTINE2-OBJ_UNK2
      OBJ_REINDEER_HEALERPHONE_JTALK0:
OBJ_STOP

OBJ_SNOWMAN_HEALERPHONE:
objectDef $19, $2b, DIRECTIONS::UP, $104
.addr SPRITEDEF_19C ;sprite
OBJ_IS_NOT_TALKING  OBJ_SNOWMAN_HEALERPHONE_JTALK0-OBJ_SNOWMAN_HEALERPHONE
OBJ_IS_NOT_FLAG  $80, OBJ_SNOWMAN_HEALERPHONE_FJJUMP1-OBJ_SNOWMAN_HEALERPHONE
OBJ_SUBROUTINE OBJ_UNK2, OBJ_UNK2_OJSUBROUTINE2-OBJ_UNK2
OBJ_STOP
      OBJ_SNOWMAN_HEALERPHONE_FJJUMP1:
OBJ_DIALOGUE UMSG::PHONE_INTRO
OBJ_JUMP  OBJ_SNOWMAN_HEALERPHONEJ_JUMP2-OBJ_SNOWMAN_HEALERPHONE
      OBJ_SNOWMAN_HEALERPHONE_JYESNO3:
OBJ_DIALOGUE UMSG::SNOWMAN_PHONE_1
      OBJ_SNOWMAN_HEALERPHONEJ_JUMP2:
OBJ_DIALOGUE UMSG::SNOWMAN_PHONE_2
OBJ_YESNO_IS_NO  OBJ_SNOWMAN_HEALERPHONE_JYESNO3-OBJ_SNOWMAN_HEALERPHONE
OBJ_DIALOGUE UMSG::SNOWMAN_PHONE_3
OBJ_JUMP  OBJ_SNOWMAN_HEALERPHONEJ_JUMP4-OBJ_SNOWMAN_HEALERPHONE
      OBJ_SNOWMAN_HEALERPHONE_JYESNO5:
OBJ_DIALOGUE UMSG::SNOWMAN_REGNAME
      OBJ_SNOWMAN_HEALERPHONEJ_JUMP4:
.byte SCRIPTS::REGNAME
OBJ_DIALOGUE UMSG::SNOWMAN_PHONE_CHECK
OBJ_YESNO_IS_NO  OBJ_SNOWMAN_HEALERPHONE_JYESNO5-OBJ_SNOWMAN_HEALERPHONE
OBJ_DIALOGUE UMSG::SNOWMAN_PHONE_END
OBJ_DIALOGUE UMSG::PHONE_END
OBJ_SET_FLAG  $80
      OBJ_SNOWMAN_HEALERPHONE_JTALK0:
OBJ_STOP

OBJ_SWAMP_HOUSEEXIT:
objectDef OBJ_TYPE::DOOR, $38e, DIRECTIONS::RIGHT, $e6
doorArgDef $6, $365, DIRECTIONS::DOWN, $198

OBJ_SWAMP_HOUSEPIPPI:
objectDef OBJ_TYPE::WANDERING_NPC_CHECKSPAWN, $38a, DIRECTIONS::DOWN, $e5
.addr SPRITEDEF_20 ;sprite
OBJ_FLAG_APPEAR  $2D
OBJ_IS_NOT_TALKING  OBJ_SWAMP_HOUSEPIPPI_JTALK0-OBJ_SWAMP_HOUSEPIPPI
OBJ_IS_NOT_FLAG  $86, OBJ_SWAMP_HOUSEPIPPI_FJJUMP1-OBJ_SWAMP_HOUSEPIPPI
OBJ_JUMP  OBJ_SWAMP_HOUSEPIPPIJ_JUMP2-OBJ_SWAMP_HOUSEPIPPI
      OBJ_SWAMP_HOUSEPIPPI_FJJUMP1:
OBJ_DIALOGUE UMSG::SWAMP_HOUSEPIPPI
      OBJ_SWAMP_HOUSEPIPPIJ_JUMP2:
OBJ_DIALOGUE UMSG::SWAMP_HOUSEPIPPI_REST
OBJ_SLEEP
OBJ_DIALOGUE UMSG::SWAMP_HOUSEPIPPI_MORNING
OBJ_SET_FLAG  $86
      OBJ_SWAMP_HOUSEPIPPI_JTALK0:
OBJ_STOP