OBJ_BANK_22:
.addr OBJ_PODUNK_DEPTEXIT
.addr OBJ_PODUNK_DEPTUPSTAIRS
.addr OBJ_PODUNK_DEPTDOWNSTAIRS2
.addr OBJ_PODUNK_DEPTUPSTAIRS3
.addr OBJ_PODUNK_DEPTDOWNSTAIRS3
.addr OBJ_PODUNK_DEPTUPSTAIRS4
.addr OBJ_PODUNK_DEPTDOWNSTAIRS4
.addr OBJ_MERRYSVILLE_DEPTEXIT
.addr OBJ_MERRYSVILLE_DEPTUPSTAIRS
.addr OBJ_REINDEER_DEPTEXIT
.addr OBJ_REINDEER_DEPTUPSTAIRS
.addr OBJ_ELLAY_DEPTEXIT
.addr OBJ_ELLAY_DEPTUPSTAIRS
.addr OBJ_SNOWMAN_FAKEDEPTEXIT
.addr OBJ_ELLAY_PAYPHONE
.addr OBJ_MERRYSVILLE_PAYPHONE
.addr OBJ_REINDEER_PAYPHONE
.addr OBJ_PODUNK_PAYPHONE
.addr OBJ_ELLAY_ATM
.addr OBJ_MERRYSVILLE_ATM
.addr OBJ_REINDEER_ATM
.addr OBJ_PODUNK_ATM
.addr OBJ_ELLAY_RETURNS
.addr OBJ_PODUNK_RETURNS
.addr OBJ_MERRYSVILLE_RETURNS
.addr OBJ_REINDEER_RETURNS
.addr OBJ_PODUNK_SPORTSVENDOR
.addr OBJ_PODUNK_FOODSVENDOR
.addr OBJ_PODUNK_PETVENDOR
.addr OBJ_PODUNK_PETVENDOR2
.addr OBJ_SNOWMAN_FAKEVENDOR
.addr OBJ_SNOWMAN_FAKEDEPTATM
.addr 0

OBJ_PODUNK_DEPTEXIT:
objectDef OBJ_TYPE::DOOR, 14, DIRECTIONS::RIGHT, 278
doorArgDef 6, 194, DIRECTIONS::DOWN, 433

OBJ_PODUNK_DEPTUPSTAIRS:
objectDef OBJ_TYPE::STAIRS, 1, DIRECTIONS::LEFT, 278
doorArgDef 0, 35, DIRECTIONS::RIGHT, 245

OBJ_PODUNK_DEPTDOWNSTAIRS2:
objectDef OBJ_TYPE::STAIRS, 482, DIRECTIONS::LEFT, 149
doorArgDef 0, 34, DIRECTIONS::RIGHT, 246

OBJ_PODUNK_DEPTUPSTAIRS3:
objectDef OBJ_TYPE::STAIRS, 481, DIRECTIONS::LEFT, 150
doorArgDef 0, 547, DIRECTIONS::RIGHT, 149

OBJ_PODUNK_DEPTDOWNSTAIRS3:
objectDef OBJ_TYPE::STAIRS, 546, DIRECTIONS::LEFT, 149
doorArgDef 0, 482, DIRECTIONS::RIGHT, 150

OBJ_PODUNK_DEPTUPSTAIRS4:
objectDef OBJ_TYPE::STAIRS, 545, DIRECTIONS::LEFT, 150
doorArgDef 0, 611, DIRECTIONS::RIGHT, 149

OBJ_PODUNK_DEPTDOWNSTAIRS4:
objectDef OBJ_TYPE::STAIRS, 610, DIRECTIONS::LEFT, 149
doorArgDef 0, 546, DIRECTIONS::RIGHT, 150

OBJ_MERRYSVILLE_DEPTEXIT:
objectDef OBJ_TYPE::DOOR, 14, DIRECTIONS::RIGHT, 182
doorArgDef 6, 354, DIRECTIONS::DOWN, 461

OBJ_MERRYSVILLE_DEPTUPSTAIRS:
objectDef OBJ_TYPE::STAIRS, 1, DIRECTIONS::LEFT, 182
doorArgDef 0, 675, DIRECTIONS::RIGHT, 149

OBJ_REINDEER_DEPTEXIT:
objectDef OBJ_TYPE::DOOR, 462, DIRECTIONS::RIGHT, 150
doorArgDef 6, 442, DIRECTIONS::DOWN, 957

OBJ_REINDEER_DEPTUPSTAIRS:
objectDef OBJ_TYPE::STAIRS, 449, DIRECTIONS::LEFT, 150
doorArgDef 0, 35, DIRECTIONS::RIGHT, 309

OBJ_ELLAY_DEPTEXIT:
objectDef OBJ_TYPE::DOOR, 46, DIRECTIONS::RIGHT, 342
doorArgDef 6, 790, DIRECTIONS::DOWN, 281

OBJ_ELLAY_DEPTUPSTAIRS:
objectDef OBJ_TYPE::STAIRS, 33, DIRECTIONS::LEFT, 342
doorArgDef 0, 739, DIRECTIONS::RIGHT, 149

OBJ_SNOWMAN_FAKEDEPTEXIT:
objectDef OBJ_TYPE::DOOR, 654, DIRECTIONS::RIGHT, 150
doorArgDef 10, 905, DIRECTIONS::DOWN, 996

OBJ_ELLAY_PAYPHONE:
objectDef 24, 42, DIRECTIONS::UP, 339
OBJ_SUBROUTINE OBJ_YOUNGTOWN_PAYPHONE, OBJ_PAYPHONE_SUBR-OBJ_YOUNGTOWN_PAYPHONE
OBJ_STOP

OBJ_MERRYSVILLE_PAYPHONE:
objectDef 24, 10, DIRECTIONS::UP, 179
OBJ_SUBROUTINE OBJ_YOUNGTOWN_PAYPHONE, OBJ_PAYPHONE_SUBR-OBJ_YOUNGTOWN_PAYPHONE
OBJ_STOP

OBJ_REINDEER_PAYPHONE:
objectDef 24, 458, DIRECTIONS::UP, 147
OBJ_SUBROUTINE OBJ_YOUNGTOWN_PAYPHONE, OBJ_PAYPHONE_SUBR-OBJ_YOUNGTOWN_PAYPHONE
OBJ_STOP

OBJ_PODUNK_PAYPHONE:
objectDef 24, 10, DIRECTIONS::UP, 275
OBJ_SUBROUTINE OBJ_YOUNGTOWN_PAYPHONE, OBJ_PAYPHONE_SUBR-OBJ_YOUNGTOWN_PAYPHONE
OBJ_STOP

OBJ_ELLAY_ATM:
objectDef 24, 36, DIRECTIONS::UP, 339
OBJ_SUBROUTINE OBJ_YOUNGTOWN_ATM, OBJ_ATM_SUBR-OBJ_YOUNGTOWN_ATM
OBJ_STOP

OBJ_MERRYSVILLE_ATM:
objectDef 24, 4, DIRECTIONS::UP, 179
OBJ_SUBROUTINE OBJ_YOUNGTOWN_ATM, OBJ_ATM_SUBR-OBJ_YOUNGTOWN_ATM
OBJ_STOP

OBJ_REINDEER_ATM:
objectDef 24, 452, DIRECTIONS::UP, 147
OBJ_SUBROUTINE OBJ_YOUNGTOWN_ATM, OBJ_ATM_SUBR-OBJ_YOUNGTOWN_ATM
OBJ_STOP

OBJ_PODUNK_ATM:
objectDef 24, 4, DIRECTIONS::UP, 275
OBJ_SUBROUTINE OBJ_YOUNGTOWN_ATM, OBJ_ATM_SUBR-OBJ_YOUNGTOWN_ATM
OBJ_STOP

OBJ_ELLAY_RETURNS:
objectDef OBJ_TYPE::STATIONARY_NPC, 39, DIRECTIONS::DOWN, 340
.addr SPRITEDEF_SUIT_GIRL
OBJ_SUBROUTINE OBJ_REINDEER_RETURNS, OBJ_RETURNS_SUBR-OBJ_REINDEER_RETURNS
OBJ_STOP

OBJ_PODUNK_RETURNS:
objectDef OBJ_TYPE::STATIONARY_NPC, 7, DIRECTIONS::DOWN, 276
.addr SPRITEDEF_SUIT_GIRL
OBJ_SUBROUTINE OBJ_REINDEER_RETURNS, OBJ_RETURNS_SUBR-OBJ_REINDEER_RETURNS
OBJ_STOP

OBJ_MERRYSVILLE_RETURNS:
objectDef OBJ_TYPE::STATIONARY_NPC, 7, DIRECTIONS::DOWN, 180
.addr SPRITEDEF_SUIT_GIRL
OBJ_SUBROUTINE OBJ_REINDEER_RETURNS, OBJ_RETURNS_SUBR-OBJ_REINDEER_RETURNS
OBJ_STOP

OBJ_REINDEER_RETURNS:
objectDef OBJ_TYPE::STATIONARY_NPC, 455, DIRECTIONS::DOWN, 148
.addr SPRITEDEF_SUIT_GIRL
OBJ_SUBROUTINE OBJ_REINDEER_RETURNS, OBJ_RETURNS_SUBR-OBJ_REINDEER_RETURNS
OBJ_STOP

OBJ_RETURNS_SUBR:
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_REINDEER_RETURNS
OBJ_DIALOGUE UMSG::RETURNS_INTRO
OBJ_YESNO_IS_NO @J_YESNO_IS_NO-OBJ_REINDEER_RETURNS
OBJ_DIALOGUE UMSG::RETURNS_WHICH
OBJ_CHOOSE_ITEM @J_YESNO_IS_NO-OBJ_REINDEER_RETURNS
OBJ_UNSELLABLE @J_UNSELLABLE-OBJ_REINDEER_RETURNS
OBJ_MULTIPLY_NUMBER 50
OBJ_NUMBERLESSTHAN 10, @J_NUMBERLESSTHAN-OBJ_REINDEER_RETURNS
OBJ_DIALOGUE UMSG::RETURNS_PRICE
OBJ_YESNO_IS_NO @J_YESNO_IS_NO1-OBJ_REINDEER_RETURNS
OBJ_GIVE_MONEY @J_GIVE_MONEY-OBJ_REINDEER_RETURNS
OBJ_SHOW_MONEY
OBJ_DIALOGUE UMSG::RETURNS_ACCEPT
OBJ_RETURN
	@J_GIVE_MONEY:
OBJ_GIVE_ITEM @J_IS_NOT_TALKING-OBJ_REINDEER_RETURNS
OBJ_DIALOGUE UMSG::PODUNK_PIPPI_NOROOM2
OBJ_RETURN
	@J_YESNO_IS_NO1:
OBJ_GIVE_ITEM @J_IS_NOT_TALKING-OBJ_REINDEER_RETURNS
	@J_YESNO_IS_NO:
OBJ_DIALOGUE UMSG::RETURNS_DECLINE
OBJ_DIALOGUE UMSG::RETURNS_ACCEPT
OBJ_RETURN
	@J_NUMBERLESSTHAN:
OBJ_GIVE_ITEM @J_IS_NOT_TALKING-OBJ_REINDEER_RETURNS
	@J_UNSELLABLE:
OBJ_DIALOGUE UMSG::RETURNS_CANTSELL
	@J_IS_NOT_TALKING:
OBJ_RETURN

OBJ_PODUNK_SPORTSVENDOR:
objectDef OBJ_TYPE::WANDERING_NPC, 488, DIRECTIONS::DOWN, 148
.addr SPRITEDEF_SUIT_GIRL
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_PODUNK_SPORTSVENDOR
.ifndef VER_JP
OBJ_DIALOGUE UMSG::DRUGSVENDOR_WELCOME
	@J_JUMP:
.endif
OBJ_SET_FLAG 0
OBJ_NOT_HAS_ITEM 0, @J_NOT_HAS_ITEM-OBJ_PODUNK_SPORTSVENDOR
OBJ_CLEAR_FLAG 0
	@J_NOT_HAS_ITEM:
.ifdef VER_JP
OBJ_DIALOGUE UMSG::DRUGSVENDOR_WELCOME
.endif
OBJ_DISPLAY_ITEMS 16, 23, 17, 0, @J_DISPLAY_ITEMS-OBJ_PODUNK_SPORTSVENDOR
OBJ_IS_NOT_FLAG 0, @J_IS_NOT_FLAG-OBJ_PODUNK_SPORTSVENDOR
OBJ_DIALOGUE UMSG::BURGERSHOP_NO_ROOM
OBJ_CLEAR_FLAG 0
OBJ_STOP
	@J_IS_NOT_FLAG:
OBJ_TAKE_MONEY @J_TAKE_MONEY-OBJ_PODUNK_SPORTSVENDOR
OBJ_DIALOGUE UMSG::SHOP_CONFIRM
OBJ_YESNO_IS_NO @J_YESNO_IS_NO-OBJ_PODUNK_SPORTSVENDOR
OBJ_DIALOGUE UMSG::BURGERSHOP_GOODBYE
OBJ_PLAY_SOUND 11
OBJ_SHOW_MONEY
OBJ_GIVE_ITEM @J_IS_NOT_TALKING-OBJ_PODUNK_SPORTSVENDOR
.ifndef VER_JP
OBJ_DIALOGUE UMSG::BURGERSHOP_ANYMORE
OBJ_YESNO_IS_NO @J_YESNO_IS_NO1-OBJ_PODUNK_SPORTSVENDOR
OBJ_JUMP @J_JUMP-OBJ_PODUNK_SPORTSVENDOR
	@J_YESNO_IS_NO1:
OBJ_DIALOGUE UMSG::BURGERSHOP_GOODBYE
.endif
OBJ_STOP
	@J_YESNO_IS_NO:
OBJ_GIVE_MONEY @J_IS_NOT_TALKING-OBJ_PODUNK_SPORTSVENDOR
	@J_DISPLAY_ITEMS:
OBJ_DIALOGUE UMSG::BURGERSHOP_NO_BUY
OBJ_CLEAR_FLAG 0
OBJ_STOP
	@J_TAKE_MONEY:
OBJ_DIALOGUE UMSG::BURGERSHOP_NOMONEY
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_PODUNK_FOODSVENDOR:
objectDef OBJ_TYPE::WANDERING_NPC, 552, DIRECTIONS::DOWN, 148
.addr SPRITEDEF_SUIT_GIRL
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_PODUNK_FOODSVENDOR
.ifndef VER_JP
OBJ_DIALOGUE UMSG::DRUGSVENDOR_WELCOME
	@J_JUMP:
.endif
OBJ_SET_FLAG 0
OBJ_NOT_HAS_ITEM 0, @J_NOT_HAS_ITEM-OBJ_PODUNK_FOODSVENDOR
OBJ_CLEAR_FLAG 0
	@J_NOT_HAS_ITEM:
.ifdef VER_JP
OBJ_DIALOGUE UMSG::DRUGSVENDOR_WELCOME
.endif
OBJ_DISPLAY_ITEMS 60, 71, 64, 0, @J_DISPLAY_ITEMS-OBJ_PODUNK_FOODSVENDOR
OBJ_IS_NOT_FLAG 0, @J_IS_NOT_FLAG-OBJ_PODUNK_FOODSVENDOR
OBJ_DIALOGUE UMSG::BURGERSHOP_NO_ROOM
OBJ_CLEAR_FLAG 0
OBJ_STOP
	@J_IS_NOT_FLAG:
OBJ_TAKE_MONEY @J_TAKE_MONEY-OBJ_PODUNK_FOODSVENDOR
OBJ_DIALOGUE UMSG::SHOP_CONFIRM
OBJ_YESNO_IS_NO @J_YESNO_IS_NO-OBJ_PODUNK_FOODSVENDOR
OBJ_DIALOGUE UMSG::BURGERSHOP_GOODBYE
OBJ_PLAY_SOUND 11
OBJ_SHOW_MONEY
OBJ_GIVE_ITEM @J_IS_NOT_TALKING-OBJ_PODUNK_FOODSVENDOR
.ifndef VER_JP
OBJ_DIALOGUE UMSG::BURGERSHOP_ANYMORE
OBJ_YESNO_IS_NO @J_YESNO_IS_NO1-OBJ_PODUNK_FOODSVENDOR
OBJ_JUMP @J_JUMP-OBJ_PODUNK_FOODSVENDOR
	@J_YESNO_IS_NO1:
OBJ_DIALOGUE UMSG::BURGERSHOP_GOODBYE
.endif
OBJ_STOP
	@J_YESNO_IS_NO:
OBJ_GIVE_MONEY @J_IS_NOT_TALKING-OBJ_PODUNK_FOODSVENDOR
	@J_DISPLAY_ITEMS:
OBJ_DIALOGUE UMSG::BURGERSHOP_NO_BUY
OBJ_CLEAR_FLAG 0
OBJ_STOP
	@J_TAKE_MONEY:
OBJ_DIALOGUE UMSG::BURGERSHOP_NOMONEY
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_PODUNK_PETVENDOR:
objectDef OBJ_TYPE::STATIONARY_NPC, 616, DIRECTIONS::UP, 148
.addr SPRITEDEF_SUIT_GUY
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_PODUNK_PETVENDOR
OBJ_IS_NOT_FLAG 12, @J_IS_NOT_FLAG-OBJ_PODUNK_PETVENDOR
OBJ_DIALOGUE UMSG::PETVENDOR_INTRO
OBJ_STOP
	@J_IS_NOT_FLAG:
OBJ_IS_NOT_FLAG 66, @J_IS_NOT_FLAG1-OBJ_PODUNK_PETVENDOR
OBJ_DIALOGUE UMSG::PETVENDOR_CANARYCHECK
OBJ_STOP
	@J_IS_NOT_FLAG1:
OBJ_DIALOGUE UMSG::PETVENDOR_INTRO
OBJ_DIALOGUE UMSG::PETVENDOR_INTRO2
OBJ_YESNO_IS_NO @J_YESNO_IS_NO-OBJ_PODUNK_PETVENDOR
OBJ_PICK_ITEM 95
OBJ_DIALOGUE UMSG::PETVENDOR_PITCH
OBJ_YESNO_IS_NO @J_YESNO_IS_NO1-OBJ_PODUNK_PETVENDOR
OBJ_TAKE_MONEY @J_TAKE_MONEY-OBJ_PODUNK_PETVENDOR
OBJ_NOT_HAS_ITEM 0, @J_NOT_HAS_ITEM-OBJ_PODUNK_PETVENDOR
OBJ_PLAY_SOUND 11
OBJ_SHOW_MONEY
OBJ_PICK_ITEM 95
OBJ_GIVE_ITEM 0
OBJ_SET_FLAG 66
OBJ_DIALOGUE UMSG::PETVENDOR_ACCEPTPITCH
OBJ_STOP
	@J_NOT_HAS_ITEM:
OBJ_PICK_ITEM 95
OBJ_GIVE_MONEY @J_IS_NOT_TALKING-OBJ_PODUNK_PETVENDOR
OBJ_DIALOGUE UMSG::DRUGSVENDOR_NOMORE
OBJ_STOP
	@J_TAKE_MONEY:
OBJ_DIALOGUE UMSG::HEALER_BROKE
OBJ_STOP
	@J_YESNO_IS_NO1:
OBJ_DIALOGUE UMSG::PETVENDOR_DECLINEPITCH
OBJ_NOT_HAS_ITEM 0, @J_NOT_HAS_ITEM1-OBJ_PODUNK_PETVENDOR
OBJ_PLAY_SOUND 11
OBJ_SHOW_MONEY
OBJ_PICK_ITEM 95
OBJ_GIVE_ITEM 0
OBJ_SET_FLAG 66
OBJ_STOP
	@J_NOT_HAS_ITEM1:
OBJ_DIALOGUE UMSG::PETVENDOR_NOCARRY
OBJ_STOP
	@J_YESNO_IS_NO:
OBJ_DIALOGUE UMSG::PETVENDOR_DECLINE
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_PODUNK_PETVENDOR2:
objectDef OBJ_TYPE::WANDERING_NPC, 618, DIRECTIONS::DOWN, 148
.addr SPRITEDEF_SUIT_GIRL
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_PODUNK_PETVENDOR2
OBJ_IS_NOT_FLAG 13, @J_IS_NOT_FLAG-OBJ_PODUNK_PETVENDOR2
OBJ_DIALOGUE UMSG::PETVENDOR2_CUTEPETS
OBJ_YESNO_IS_NO @J_YESNO_IS_NO-OBJ_PODUNK_PETVENDOR2
OBJ_DIALOGUE UMSG::PODUNK_PIPPI_MEET_NOYES
OBJ_STOP
	@J_YESNO_IS_NO:
OBJ_DIALOGUE UMSG::TWINKLE_LLOYDBULLY2_LLOYD
OBJ_STOP
	@J_IS_NOT_FLAG:
OBJ_DIALOGUE UMSG::PETVENDOR2_BRAINWASH
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_SNOWMAN_FAKEVENDOR:
objectDef OBJ_TYPE::WANDERING_NPC, 648, DIRECTIONS::DOWN, 148
.addr SPRITEDEF_MOUSTACHE_GUY
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_SNOWMAN_FAKEVENDOR
.ifndef VER_JP
OBJ_DIALOGUE UMSG::DRUGSVENDOR_WELCOME
	@J_JUMP:
.endif
OBJ_SET_FLAG 0
OBJ_NOT_HAS_ITEM 0, @J_NOT_HAS_ITEM-OBJ_SNOWMAN_FAKEVENDOR
OBJ_CLEAR_FLAG 0
	@J_NOT_HAS_ITEM:
.ifdef VER_JP
OBJ_DIALOGUE UMSG::DRUGSVENDOR_WELCOME
.endif
OBJ_DISPLAY_ITEMS 71, 68, 65, 20, @J_DISPLAY_ITEMS-OBJ_SNOWMAN_FAKEVENDOR
OBJ_IS_NOT_FLAG 0, @J_IS_NOT_FLAG-OBJ_SNOWMAN_FAKEVENDOR
OBJ_DIALOGUE UMSG::DRUGSVENDOR_NOMORE
OBJ_CLEAR_FLAG 0
OBJ_STOP
	@J_IS_NOT_FLAG:
OBJ_TAKE_MONEY @J_TAKE_MONEY-OBJ_SNOWMAN_FAKEVENDOR
OBJ_DIALOGUE UMSG::SHOP_CONFIRM
OBJ_YESNO_IS_NO @J_YESNO_IS_NO-OBJ_SNOWMAN_FAKEVENDOR
OBJ_DIALOGUE UMSG::BURGERSHOP_GOODBYE
OBJ_PLAY_SOUND 11
OBJ_SHOW_MONEY
OBJ_GIVE_ITEM @J_IS_NOT_TALKING-OBJ_SNOWMAN_FAKEVENDOR
.ifndef VER_JP
OBJ_DIALOGUE UMSG::BURGERSHOP_ANYMORE
OBJ_YESNO_IS_NO @J_YESNO_IS_NO1-OBJ_SNOWMAN_FAKEVENDOR
OBJ_JUMP @J_JUMP-OBJ_SNOWMAN_FAKEVENDOR
	@J_YESNO_IS_NO1:
OBJ_DIALOGUE UMSG::BURGERSHOP_GOODBYE
.endif
OBJ_STOP
	@J_YESNO_IS_NO:
OBJ_GIVE_MONEY @J_IS_NOT_TALKING-OBJ_SNOWMAN_FAKEVENDOR
	@J_DISPLAY_ITEMS:
OBJ_DIALOGUE UMSG::MISLAY_MOUTHWASHKID_NOTAKE
OBJ_CLEAR_FLAG 0
OBJ_STOP
	@J_TAKE_MONEY:
OBJ_DIALOGUE UMSG::HOSPITAL_NURSE_NOMONEY
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_SNOWMAN_FAKEDEPTATM:
objectDef 24, 644, DIRECTIONS::UP, 147
OBJ_SUBROUTINE OBJ_YOUNGTOWN_ATM, OBJ_ATM_SUBR-OBJ_YOUNGTOWN_ATM
OBJ_STOP