OBJ_BANK_1A:
.word OBJ_TWINKLE_EXIT
.word OBJ_TWINKLE_F1_ROOM1ENTRANCE
.word OBJ_TWINKLE_F1_ROOM2ENTRANCE
.word OBJ_TWINKLE_F1_ROOM3ENTRANCE
.word OBJ_TWINKLE_F1_ROOM4ENTRANCE
.word OBJ_TWINKLE_F1_ROOM5ENTRANCE
.word OBJ_TWINKLE_F1_ROOM6ENTRANCE
.word OBJ_TWINKLE_F1_UPSTAIRS
.word OBJ_TWINKLE_F2_DOWNSTAIRS
.word OBJ_TWINKLE_F2_ROOM1ENTRANCE
.word OBJ_TWINKLE_F2_ROOM2ENTRANCE
.word OBJ_TWINKLE_F2_ROOM3ENTRANCE
.word OBJ_TWINKLE_F2_ROOM4ENTRANCE
.word OBJ_TWINKLE_F2_ROOM5ENTRANCE
.word OBJ_TWINKLE_F2_ROOM6ENTRANCE
.word OBJ_TWINKLE_F2_UPSTAIRS
.word OBJ_MERRYSVILLE_HOTELDOWNSTAIRS
.word OBJ_MERRYSVILLE_HOTELUPROOM1ENTRANCE
.word OBJ_MERRYSVILLE_HOTELUPROOM2ENTRANCE
.word OBJ_MERRYSVILLE_HOTELUPUPSTAIRS
.word OBJ_TWINKLE_HALLMONITOR
.word OBJ_TWINKLE_LLOYDBULLY
.word OBJ_TWINKLE_LLOYDBULLY2
.word OBJ_TWINKLE_HALLMONITOR2
.word OBJ_TWINKLE_F1JANITOR
.word OBJ_TWINKLE_F2JANITOR
.word OBJ_TWINKLE_F2LLOYD
.word OBJ_TWINKLE_F1LLOYD
.word 0

OBJ_TWINKLE_EXIT:
objectDef OBJ_TYPE::DOOR, $305, DIRECTIONS::UP, $3b4
doorArgDef $6, $169, DIRECTIONS::DOWN, $1E6

OBJ_TWINKLE_F1_ROOM1ENTRANCE:
objectDef OBJ_TYPE::DOOR, $2f6, DIRECTIONS::UP, $3b7
doorArgDef $0, $26D, DIRECTIONS::LEFT, $3D6

OBJ_TWINKLE_F1_ROOM2ENTRANCE:
objectDef OBJ_TYPE::DOOR, $2fa, DIRECTIONS::UP, $3b7
doorArgDef $0, $2CD, DIRECTIONS::LEFT, $3D6

OBJ_TWINKLE_F1_ROOM3ENTRANCE:
objectDef OBJ_TYPE::DOOR, $2fd, DIRECTIONS::UP, $3b7
doorArgDef $0, $2CD, DIRECTIONS::LEFT, $3F6

OBJ_TWINKLE_F1_ROOM4ENTRANCE:
objectDef OBJ_TYPE::DOOR, $30e, DIRECTIONS::UP, $3b7
doorArgDef $0, $2AD, DIRECTIONS::LEFT, $3D6

OBJ_TWINKLE_F1_ROOM5ENTRANCE:
objectDef OBJ_TYPE::DOOR, $312, DIRECTIONS::UP, $3b7
doorArgDef $0, $28D, DIRECTIONS::LEFT, $3F6

OBJ_TWINKLE_F1_ROOM6ENTRANCE:
objectDef $18, $315, DIRECTIONS::UP, $3b7
.byte SCRIPTS::J_UNK, OBJ_TWINKLE_F1_ROOM6ENTRANCE_JUNK0-OBJ_TWINKLE_F1_ROOM6ENTRANCE
.byte SCRIPTS::J_TOUCH, OBJ_TWINKLE_F1_ROOM6ENTRANCE_JTOUCH1-OBJ_TWINKLE_F1_ROOM6ENTRANCE
.byte SCRIPTS::FJ_JUMP, $5B, OBJ_TWINKLE_F1_ROOM6ENTRANCE_FJJUMP2-OBJ_TWINKLE_F1_ROOM6ENTRANCE
.byte SCRIPTS::DA_TELEPORT
doorArgDef $0, $31D, DIRECTIONS::LEFT, $3C6
.byte 0
      OBJ_TWINKLE_F1_ROOM6ENTRANCE_FJJUMP2:
.byte SCRIPTS::DIALOGUE
.word UMSG::TWINKLE_F1_ROOM6ENTRANCE_NOJANITOR
.byte 0
      OBJ_TWINKLE_F1_ROOM6ENTRANCE_JTOUCH1:
.byte SCRIPTS::IJ_USE, $55, OBJ_TWINKLE_F1_ROOM6ENTRANCE_IJUSE3-OBJ_TWINKLE_F1_ROOM6ENTRANCE
.byte SCRIPTS::J_JUMP, OBJ_TWINKLE_F1_ROOM6ENTRANCEJ_JUMP4-OBJ_TWINKLE_F1_ROOM6ENTRANCE
      OBJ_TWINKLE_F1_ROOM6ENTRANCE_IJUSE3:
.byte SCRIPTS::IJ_USE, $56, OBJ_TWINKLE_F1_ROOM6ENTRANCE_IJUSE5-OBJ_TWINKLE_F1_ROOM6ENTRANCE
.byte SCRIPTS::J_JUMP, OBJ_TWINKLE_F1_ROOM6ENTRANCEJ_JUMP4-OBJ_TWINKLE_F1_ROOM6ENTRANCE
      OBJ_TWINKLE_F1_ROOM6ENTRANCE_IJUSE5:
.byte SCRIPTS::IJ_USE, $57, OBJ_TWINKLE_F1_ROOM6ENTRANCE_JUNK0-OBJ_TWINKLE_F1_ROOM6ENTRANCE
      OBJ_TWINKLE_F1_ROOM6ENTRANCEJ_JUMP4:
.byte SCRIPTS::DIALOGUE
.word UMSG::DOOR_KEYFAIL
      OBJ_TWINKLE_F1_ROOM6ENTRANCE_JUNK0:
.byte 0

OBJ_TWINKLE_F1_UPSTAIRS:
objectDef OBJ_TYPE::STAIRS, $2f2, DIRECTIONS::LEFT, $3b9
doorArgDef $0, $2FA, DIRECTIONS::RIGHT, $3D6

OBJ_TWINKLE_F2_DOWNSTAIRS:
objectDef OBJ_TYPE::STAIRS, $2f9, DIRECTIONS::LEFT, $3d6
doorArgDef $0, $2F3, DIRECTIONS::RIGHT, $3B9

OBJ_TWINKLE_F2_ROOM1ENTRANCE:
objectDef OBJ_TYPE::DOOR, $2fe, DIRECTIONS::UP, $3d3
doorArgDef $0, $2CD, DIRECTIONS::LEFT, $3B6

OBJ_TWINKLE_F2_ROOM2ENTRANCE:
objectDef OBJ_TYPE::DOOR, $302, DIRECTIONS::UP, $3d3
doorArgDef $0, $2ED, DIRECTIONS::LEFT, $3D6

OBJ_TWINKLE_F2_ROOM3ENTRANCE:
objectDef OBJ_TYPE::DOOR, $306, DIRECTIONS::UP, $3d3
doorArgDef $0, $2ED, DIRECTIONS::LEFT, $3F6

OBJ_TWINKLE_F2_ROOM4ENTRANCE:
objectDef OBJ_TYPE::DOOR, $30a, DIRECTIONS::UP, $3d3
doorArgDef $0, $37D, DIRECTIONS::LEFT, $96

OBJ_TWINKLE_F2_ROOM5ENTRANCE:
objectDef OBJ_TYPE::DOOR, $30e, DIRECTIONS::UP, $3d3
doorArgDef $0, $26D, DIRECTIONS::LEFT, $3B6

OBJ_TWINKLE_F2_ROOM6ENTRANCE:
objectDef OBJ_TYPE::DOOR, $311, DIRECTIONS::UP, $3d3
doorArgDef $0, $3D, DIRECTIONS::LEFT, $156

OBJ_TWINKLE_F2_UPSTAIRS:
objectDef $18, $315, DIRECTIONS::RIGHT, $3d5
.byte SCRIPTS::J_UNK, OBJ_TWINKLE_F2_UPSTAIRS_JUNK0-OBJ_TWINKLE_F2_UPSTAIRS
.byte SCRIPTS::J_TOUCH, OBJ_TWINKLE_F2_UPSTAIRS_JTOUCH1-OBJ_TWINKLE_F2_UPSTAIRS
.byte SCRIPTS::FJ_JUMP, $3C, OBJ_TWINKLE_F2_UPSTAIRS_FJJUMP2-OBJ_TWINKLE_F2_UPSTAIRS
.byte SCRIPTS::DA_TELEPORT
doorArgDef $0, $6B, DIRECTIONS::DOWN, $170
.byte 0
      OBJ_TWINKLE_F2_UPSTAIRS_FJJUMP2:
.byte SCRIPTS::DIALOGUE
.word UMSG::TWINKLE_F2_UPSTAIRS_PADLOCK
.byte SCRIPTS::F_SETFLAG, $5B
.byte 0
      OBJ_TWINKLE_F2_UPSTAIRS_JTOUCH1:
.byte SCRIPTS::IJ_USE, $55, OBJ_TWINKLE_F2_UPSTAIRS_IJUSE3-OBJ_TWINKLE_F2_UPSTAIRS
.byte SCRIPTS::J_JUMP, OBJ_TWINKLE_F2_UPSTAIRSJ_JUMP4-OBJ_TWINKLE_F2_UPSTAIRS
      OBJ_TWINKLE_F2_UPSTAIRS_IJUSE3:
.byte SCRIPTS::IJ_USE, $56, OBJ_TWINKLE_F2_UPSTAIRS_IJUSE5-OBJ_TWINKLE_F2_UPSTAIRS
.byte SCRIPTS::J_JUMP, OBJ_TWINKLE_F2_UPSTAIRSJ_JUMP4-OBJ_TWINKLE_F2_UPSTAIRS
      OBJ_TWINKLE_F2_UPSTAIRS_IJUSE5:
.byte SCRIPTS::IJ_USE, $57, OBJ_TWINKLE_F2_UPSTAIRS_JUNK0-OBJ_TWINKLE_F2_UPSTAIRS
      OBJ_TWINKLE_F2_UPSTAIRSJ_JUMP4:
.byte SCRIPTS::DIALOGUE
.word UMSG::DOOR_KEYFAIL
      OBJ_TWINKLE_F2_UPSTAIRS_JUNK0:
.byte 0

OBJ_MERRYSVILLE_HOTELDOWNSTAIRS:
objectDef OBJ_TYPE::STAIRS, $301, DIRECTIONS::LEFT, $3f6
doorArgDef $0, $2D3, DIRECTIONS::RIGHT, $3D5

OBJ_MERRYSVILLE_HOTELUPROOM1ENTRANCE:
objectDef OBJ_TYPE::DOOR, $306, DIRECTIONS::UP, $3f3
doorArgDef $0, $2ED, DIRECTIONS::LEFT, $86

OBJ_MERRYSVILLE_HOTELUPROOM2ENTRANCE:
objectDef OBJ_TYPE::DOOR, $309, DIRECTIONS::UP, $3f3
doorArgDef $0, $36D, DIRECTIONS::LEFT, $86

OBJ_MERRYSVILLE_HOTELUPUPSTAIRS:
objectDef OBJ_TYPE::STAIRS, $302, DIRECTIONS::LEFT, $3f5
doorArgDef $0, $272, DIRECTIONS::RIGHT, $3C6

OBJ_TWINKLE_HALLMONITOR:
objectDef OBJ_TYPE::WANDERING_NPC2, $317, DIRECTIONS::RIGHT, $3ba
.word $8328 ;sprite
.byte SCRIPTS::J_TALK, OBJ_TWINKLE_HALLMONITOR_JTALK0-OBJ_TWINKLE_HALLMONITOR
.byte SCRIPTS::DIALOGUE
.word UMSG::TWINKLE_HALLMONITOR
      OBJ_TWINKLE_HALLMONITOR_JTALK0:
.byte 0

OBJ_TWINKLE_LLOYDBULLY:
objectDef OBJ_TYPE::WANDERING_NPC2, $30d, DIRECTIONS::LEFT, $3d6
.word $8308 ;sprite
.byte SCRIPTS::J_TALK, OBJ_TWINKLE_LLOYDBULLY_JTALK0-OBJ_TWINKLE_LLOYDBULLY
.byte SCRIPTS::CJ_PRESENT, $3, OBJ_TWINKLE_LLOYDBULLY_CJPRESENT1-OBJ_TWINKLE_LLOYDBULLY
.byte SCRIPTS::SJ_PRESENT, $80, OBJ_TWINKLE_LLOYDBULLY_SJPRESENT2-OBJ_TWINKLE_LLOYDBULLY
.byte SCRIPTS::DIALOGUE
.word UMSG::TWINKLE_LLOYDBULLY_LLOYD
.byte 0
      OBJ_TWINKLE_LLOYDBULLY_SJPRESENT2:
.byte SCRIPTS::DIALOGUE
.word UMSG::TWINKLE_LLOYDBULLY_DEADLLOYD
.byte 0
      OBJ_TWINKLE_LLOYDBULLY_CJPRESENT1:
.byte SCRIPTS::DIALOGUE
.word UMSG::TWINKLE_LLOYDBULLY
      OBJ_TWINKLE_LLOYDBULLY_JTALK0:
.byte 0

OBJ_TWINKLE_LLOYDBULLY2:
objectDef OBJ_TYPE::WANDERING_NPC2, $30f, DIRECTIONS::RIGHT, $3d7
.word $8388 ;sprite
.byte SCRIPTS::J_TALK, OBJ_TWINKLE_LLOYDBULLY2_JTALK0-OBJ_TWINKLE_LLOYDBULLY2
.byte SCRIPTS::CJ_PRESENT, $3, OBJ_TWINKLE_LLOYDBULLY2_CJPRESENT1-OBJ_TWINKLE_LLOYDBULLY2
.byte SCRIPTS::DIALOGUE
.word UMSG::TWINKLE_LLOYDBULLY2_LLOYD
.byte 0
      OBJ_TWINKLE_LLOYDBULLY2_CJPRESENT1:
.byte SCRIPTS::DIALOGUE
.word UMSG::TWINKLE_LLOYDBULLY2
      OBJ_TWINKLE_LLOYDBULLY2_JTALK0:
.byte 0

OBJ_TWINKLE_HALLMONITOR2:
objectDef OBJ_TYPE::WANDERING_NPC2, $2fb, DIRECTIONS::LEFT, $3bb
.word $8348 ;sprite
.byte SCRIPTS::J_TALK, OBJ_TWINKLE_HALLMONITOR2_JTALK0-OBJ_TWINKLE_HALLMONITOR2
.byte SCRIPTS::DIALOGUE
.word UMSG::TWINKLE_HALLMONITOR2
.byte SCRIPTS::J_YESNO, OBJ_TWINKLE_HALLMONITOR2_JYESNO1-OBJ_TWINKLE_HALLMONITOR2
.byte SCRIPTS::DIALOGUE
.word UMSG::TWINKLE_HALLMONITOR2_YES
.byte 0
      OBJ_TWINKLE_HALLMONITOR2_JYESNO1:
.byte SCRIPTS::DIALOGUE
.word UMSG::ELLAY_LHCOP_SEEWEAPON
      OBJ_TWINKLE_HALLMONITOR2_JTALK0:
.byte 0

OBJ_TWINKLE_F1JANITOR:
objectDef $14, $315, DIRECTIONS::LEFT, $3b9
.word $8408 ;sprite
.byte SCRIPTS::F_APPEAR, $23
.byte SCRIPTS::J_TOUCH, OBJ_TWINKLE_F1JANITOR_JTOUCH0-OBJ_TWINKLE_F1JANITOR
.byte SCRIPTS::M_MOVE
.word OBJ_TWINKLE_F1JANITOR_MOVE0
      OBJ_TWINKLE_F1JANITOR_JTOUCH0:
.byte 0
        OBJ_TWINKLE_F1JANITOR_MOVE0:
moveDef DIRECTIONS::LEFT, $6, $22
moveDef DIRECTIONS::LEFT, $2, $1
moveDef DIRECTIONS::RIGHT, $2, $1
.byte 3

OBJ_TWINKLE_F2JANITOR:
objectDef $14, $2fb, DIRECTIONS::UP, $3d6
.word $8408 ;sprite
.byte SCRIPTS::F_APPEAR, $23
.byte SCRIPTS::J_TOUCH, OBJ_TWINKLE_F2JANITOR_JTOUCH0-OBJ_TWINKLE_F2JANITOR
.byte SCRIPTS::M_MOVE
.word OBJ_TWINKLE_F2JANITOR_MOVE0
.byte SCRIPTS::DIALOGUE
.word UMSG::TWINKLE_F2JANITOR
.byte SCRIPTS::M_MOVE
.word OBJ_TWINKLE_F2JANITOR_MOVE1
.byte SCRIPTS::DIALOGUE
.word UMSG::TWINKLE_F2JANITOR2
.byte SCRIPTS::M_MOVE
.word OBJ_TWINKLE_F2JANITOR_MOVE2
.byte SCRIPTS::F_SETFLAG, $3C
.byte SCRIPTS::F_CLEARFLAG, $23
      OBJ_TWINKLE_F2JANITOR_JTOUCH0:
.byte 0
        OBJ_TWINKLE_F2JANITOR_MOVE0:
moveDef DIRECTIONS::UP, $6, $1
moveDef DIRECTIONS::RIGHT, $6, $A
.byte 3
        OBJ_TWINKLE_F2JANITOR_MOVE1:
moveDef DIRECTIONS::RIGHT, $6, $F
moveDef DIRECTIONS::LEFT, MOVE_CMD::ABOUTFACE, $1
moveDef DIRECTIONS::RIGHT, MOVE_CMD::MOVEFACE, $1
moveDef DIRECTIONS::RIGHT, $A, $1
moveDef DIRECTIONS::LEFT, $A, $1
moveDef DIRECTIONS::LEFT, MOVE_CMD::MOVEFACE, $1
.byte 3
        OBJ_TWINKLE_F2JANITOR_MOVE2:
moveDef DIRECTIONS::DOWN, MOVE_CMD::MOVEFACE, $1
moveDef DIRECTIONS::LEFT, MOVE_CMD::MOVEFACE, $9
.byte 0

OBJ_TWINKLE_F2LLOYD:
objectDef $14, $313, DIRECTIONS::RIGHT, $3d5
.word $8040 ;sprite
.byte SCRIPTS::F_APPEAR, $24
.byte SCRIPTS::J_TOUCH, OBJ_TWINKLE_F2LLOYD_JTOUCH0-OBJ_TWINKLE_F2LLOYD
.byte SCRIPTS::DIALOGUE
.word UMSG::TWINKLE_F2LLOYD
.byte SCRIPTS::M_MOVE
.word OBJ_TWINKLE_F2LLOYD_MOVE0
      OBJ_TWINKLE_F2LLOYD_JTOUCH0:
.byte 0
        OBJ_TWINKLE_F2LLOYD_MOVE0:
moveDef DIRECTIONS::LEFT, $6, $F
moveDef DIRECTIONS::DOWN, $6, $1
moveDef DIRECTIONS::LEFT, $6, $A
moveDef DIRECTIONS::LEFT, $2, $1
moveDef DIRECTIONS::RIGHT, $2, $1
.byte 3

OBJ_TWINKLE_F1LLOYD:
objectDef $14, $2f4, DIRECTIONS::LEFT, $3b9
.word $8040 ;sprite
.byte SCRIPTS::F_APPEAR, $24
.byte SCRIPTS::J_TOUCH, OBJ_TWINKLE_F1LLOYD_JTOUCH0-OBJ_TWINKLE_F1LLOYD
.byte SCRIPTS::DIALOGUE
.word UMSG::TWINKLE_F1LLOYD
.byte SCRIPTS::M_MOVE
.word OBJ_TWINKLE_F1LLOYD_MOVE0
      OBJ_TWINKLE_F1LLOYD_JTOUCH0:
.byte 0
        OBJ_TWINKLE_F1LLOYD_MOVE0:
moveDef DIRECTIONS::RIGHT, $6, $1A
moveDef DIRECTIONS::UP, $6, $1
moveDef DIRECTIONS::UP, $2, $1
moveDef DIRECTIONS::LEFT, $2, $1
.byte 3