OBJ_BANK_1D:
.addr OBJ_ROSEMARYHOUSE_DOOR14
.addr OBJ_ROSEMARYHOUSE_DOOR15
.addr OBJ_ROSEMARYHOUSE_DOOR16
.addr OBJ_ROSEMARYHOUSE_DOOR17
.addr OBJ_ROSEMARYHOUSE_DOOR18
.addr OBJ_ROSEMARYHOUSE_DOOR19
.addr OBJ_ROSEMARYHOUSE_DOOR20
.addr OBJ_ROSEMARYHOUSE_DOOR21
.addr OBJ_ROSEMARYHOUSE_DOOR22
.addr OBJ_ROSEMARYHOUSE_DOOR23
.addr OBJ_ROSEMARYHOUSE_DOOR24
.addr OBJ_ROSEMARYHOUSE_DOOR25
.addr OBJ_ROSEMARYHOUSE_DOOR26
.addr OBJ_ROSEMARYHOUSE_WORSTNIGHTMARE
.addr OBJ_ROSEMARYHOUSE_PRESENT2
.addr OBJ_ROSEMARYHOUSE_PRESENT3
.addr OBJ_ROSEMARYHOUSE_PRESENT4
.addr OBJ_ROSEMARYHOUSE_PRESENT5
.addr 0

OBJ_ROSEMARYHOUSE_DOOR14:
objectDef OBJ_TYPE::DOOR, 606, DIRECTIONS::RIGHT, 134
doorArgDef 0, 467, DIRECTIONS::RIGHT, 133

OBJ_ROSEMARYHOUSE_DOOR15:
objectDef OBJ_TYPE::DOOR, 594, DIRECTIONS::LEFT, 133
doorArgDef 0, 542, DIRECTIONS::LEFT, 135

OBJ_ROSEMARYHOUSE_DOOR16:
objectDef OBJ_TYPE::DOOR, 592, DIRECTIONS::LEFT, 135
doorArgDef 0, 574, DIRECTIONS::LEFT, 135


OBJ_ROSEMARYHOUSE_DOOR17:
objectDef OBJ_TYPE::DOOR, 62, DIRECTIONS::RIGHT, 166
doorArgDef 0, 465, DIRECTIONS::RIGHT, 135

OBJ_ROSEMARYHOUSE_DOOR18:
objectDef OBJ_TYPE::DOOR, 50, DIRECTIONS::LEFT, 165
doorArgDef 0, 654, DIRECTIONS::LEFT, 946

OBJ_ROSEMARYHOUSE_DOOR19:
objectDef OBJ_TYPE::DOOR, 48, DIRECTIONS::LEFT, 167
doorArgDef 0, 61, DIRECTIONS::LEFT, 326


OBJ_ROSEMARYHOUSE_DOOR20:
objectDef OBJ_TYPE::DOOR, 62, DIRECTIONS::RIGHT, 326
doorArgDef 0, 49, DIRECTIONS::RIGHT, 167

OBJ_ROSEMARYHOUSE_DOOR21:
objectDef OBJ_TYPE::DOOR, 50, DIRECTIONS::LEFT, 325
doorArgDef 0, 29, DIRECTIONS::LEFT, 262

OBJ_ROSEMARYHOUSE_DOOR22:
objectDef OBJ_TYPE::DOOR, 48, DIRECTIONS::LEFT, 327
doorArgDef 0, 61, DIRECTIONS::LEFT, 230


OBJ_ROSEMARYHOUSE_DOOR23:
objectDef OBJ_TYPE::DOOR, 702, DIRECTIONS::RIGHT, 134
doorArgDef 0, 18, DIRECTIONS::RIGHT, 198


OBJ_ROSEMARYHOUSE_DOOR24:
objectDef OBJ_TYPE::DOOR, 62, DIRECTIONS::RIGHT, 294
doorArgDef 0, 773, DIRECTIONS::RIGHT, 1007


OBJ_ROSEMARYHOUSE_DOOR25:
objectDef OBJ_TYPE::DOOR, 30, DIRECTIONS::RIGHT, 294
doorArgDef 0, 677, DIRECTIONS::RIGHT, 959


OBJ_ROSEMARYHOUSE_DOOR26:
objectDef OBJ_TYPE::DOOR, 62, DIRECTIONS::RIGHT, 230
doorArgDef 0, 49, DIRECTIONS::RIGHT, 327


OBJ_ROSEMARYHOUSE_WORSTNIGHTMARE:
objectDef OBJ_TYPE::TRIGGER_CHECKSPAWN, 51, DIRECTIONS::UP, 325
OBJ_FLAG_DISAPPEAR 15
OBJ_IS_NOT_TOUCHING @J_IS_NOT_TOUCHING-OBJ_ROSEMARYHOUSE_WORSTNIGHTMARE
OBJ_DIALOGUE UMSG::ROSEMARYHOUSE_WORSTNIGHTMARE
	@J_IS_NOT_TOUCHING:
OBJ_STOP

OBJ_ROSEMARYHOUSE_PRESENT2:
objectDef OBJ_TYPE::PRESENT, 54, DIRECTIONS::UP, 164
.addr SPRITEDEF_PRESENT
.byte 67 ; item
.byte 20 ; flag

OBJ_ROSEMARYHOUSE_PRESENT3:
objectDef OBJ_TYPE::PRESENT, 25, DIRECTIONS::UP, 295
.addr SPRITEDEF_PRESENT
.byte 71 ; item
.byte 21 ; flag

OBJ_ROSEMARYHOUSE_PRESENT4:
objectDef OBJ_TYPE::PRESENT, 59, DIRECTIONS::UP, 231
.addr SPRITEDEF_PRESENT
.byte 67 ; item
.byte 22 ; flag

OBJ_ROSEMARYHOUSE_PRESENT5:
objectDef OBJ_TYPE::PRESENT, 50, DIRECTIONS::UP, 295
.addr SPRITEDEF_PRESENT
.byte 0 ; item
.byte 23 ; flag

