OBJ_BANK_1F:
.addr OBJ_PODUNK_BURGEREXIT
.addr OBJ_MERRYSVILLE_BURGEREXIT
.addr OBJ_REINDEER_BURGEREXIT
.addr OBJ_ELLAY_BURGEREXIT
.addr OBJ_PODUNK_DEPTDOWNSTAIRS
.addr OBJ_PODUNK_DEPTUPSTAIRS2
.addr OBJ_MERRYSVILLE_DEPTDOWNSTAIRS
.addr OBJ_MERRYSVILLE_DEPTUPSTAIRS2
.addr OBJ_REINDEER_DEPTDOWNSTAIRS
.addr OBJ_REINDEER_DEPTUPSTAIRS2
.addr OBJ_ELLAY_DEPTDOWNSTAIRS
.addr OBJ_ELLAY_DEPTUPSTAIRS2
.addr OBJ_PODUNK_BURGERWAITRESS
.addr OBJ_ELLAY_BURGERWAITRESS
.addr OBJ_MERRYSVILLE_BURGERWAITRESS
.addr OBJ_REINDEER_BURGERWAITRESS
.addr OBJ_PODUNK_BURGERWAITRESS2
.addr OBJ_REINDEER_BURGERWAITRESS2
.addr OBJ_MERRYSVILLE_DRUGSVENDOR
.addr OBJ_ELLAY_DRUGSVENDOR
.addr OBJ_REINDEER_DRUGSVENDOR
.addr OBJ_PODUNK_DRUGSVENDOR
.addr 0

OBJ_PODUNK_BURGEREXIT:
objectDef OBJ_TYPE::DOOR, 14, DIRECTIONS::RIGHT, 342
doorArgDef 6, 183, DIRECTIONS::DOWN, 433


OBJ_MERRYSVILLE_BURGEREXIT:
objectDef OBJ_TYPE::DOOR, 14, DIRECTIONS::RIGHT, 246
doorArgDef 6, 355, DIRECTIONS::DOWN, 449


OBJ_REINDEER_BURGEREXIT:
objectDef OBJ_TYPE::DOOR, 590, DIRECTIONS::RIGHT, 150
doorArgDef 6, 467, DIRECTIONS::DOWN, 957


OBJ_ELLAY_BURGEREXIT:
objectDef OBJ_TYPE::DOOR, 46, DIRECTIONS::RIGHT, 182
doorArgDef 6, 799, DIRECTIONS::DOWN, 281


OBJ_PODUNK_DEPTDOWNSTAIRS:
objectDef OBJ_TYPE::STAIRS, 34, DIRECTIONS::LEFT, 245
doorArgDef 0, 2, DIRECTIONS::RIGHT, 278

OBJ_PODUNK_DEPTUPSTAIRS2:
objectDef OBJ_TYPE::STAIRS, 33, DIRECTIONS::LEFT, 246
doorArgDef 0, 483, DIRECTIONS::RIGHT, 149


OBJ_MERRYSVILLE_DEPTDOWNSTAIRS:
objectDef OBJ_TYPE::STAIRS, 674, DIRECTIONS::LEFT, 149
doorArgDef 0, 2, DIRECTIONS::RIGHT, 182

OBJ_MERRYSVILLE_DEPTUPSTAIRS2:
objectDef OBJ_TYPE::STAIRS, 673, DIRECTIONS::LEFT, 150
doorArgDef 0, 3, DIRECTIONS::RIGHT, 309


OBJ_REINDEER_DEPTDOWNSTAIRS:
objectDef OBJ_TYPE::STAIRS, 34, DIRECTIONS::LEFT, 309
doorArgDef 0, 450, DIRECTIONS::RIGHT, 150

OBJ_REINDEER_DEPTUPSTAIRS2:
objectDef OBJ_TYPE::STAIRS, 33, DIRECTIONS::LEFT, 310
doorArgDef 0, 35, DIRECTIONS::RIGHT, 149


OBJ_ELLAY_DEPTDOWNSTAIRS:
objectDef OBJ_TYPE::STAIRS, 738, DIRECTIONS::LEFT, 149
doorArgDef 0, 34, DIRECTIONS::RIGHT, 342

OBJ_ELLAY_DEPTUPSTAIRS2:
objectDef OBJ_TYPE::STAIRS, 737, DIRECTIONS::LEFT, 150
doorArgDef 0, 771, DIRECTIONS::RIGHT, 149


OBJ_PODUNK_BURGERWAITRESS:
objectDef OBJ_TYPE::WANDERING_NPC, 6, DIRECTIONS::DOWN, 340
.addr SPRITEDEF_BELLHOP_WOMAN
OBJ_SUBROUTINE OBJ_PODUNK_BURGERWAITRESS, OBJ_BURGER_SUBR-OBJ_PODUNK_BURGERWAITRESS
OBJ_STOP

OBJ_BURGER_SUBR:
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_PODUNK_BURGERWAITRESS
OBJ_DIALOGUE UMSG::BURGERSHOP_MENU
	@J_JUMP:
OBJ_SET_FLAG 0
OBJ_NOT_HAS_ITEM 0, @J_NOT_HAS_ITEM-OBJ_PODUNK_BURGERWAITRESS
OBJ_CLEAR_FLAG 0
	@J_NOT_HAS_ITEM:
OBJ_DISPLAY_ITEMS 60, 61, 63, 0, @J_DISPLAY_ITEMS-OBJ_PODUNK_BURGERWAITRESS
OBJ_IS_NOT_FLAG 0, @J_IS_NOT_FLAG-OBJ_PODUNK_BURGERWAITRESS
OBJ_DIALOGUE UMSG::BURGERSHOP_NO_ROOM
OBJ_CLEAR_FLAG 0
OBJ_RETURN
	@J_IS_NOT_FLAG:
OBJ_TAKE_MONEY @J_TAKE_MONEY-OBJ_PODUNK_BURGERWAITRESS
OBJ_DIALOGUE UMSG::SHOP_CONFIRM
OBJ_YESNO_IS_NO @J_YESNO_IS_NO-OBJ_PODUNK_BURGERWAITRESS
OBJ_DIALOGUE UMSG::BURGERSHOP_BUY
OBJ_PLAY_SOUND 11
OBJ_SHOW_MONEY
OBJ_GIVE_ITEM @J_IS_NOT_TALKING-OBJ_PODUNK_BURGERWAITRESS
OBJ_DIALOGUE UMSG::BURGERSHOP_ANYMORE
OBJ_YESNO_IS_NO @J_YESNO_IS_NO1-OBJ_PODUNK_BURGERWAITRESS
OBJ_JUMP @J_JUMP-OBJ_PODUNK_BURGERWAITRESS
	@J_YESNO_IS_NO1:
OBJ_DIALOGUE UMSG::BURGERSHOP_GOODBYE
OBJ_RETURN
	@J_YESNO_IS_NO:
OBJ_GIVE_MONEY @J_IS_NOT_TALKING-OBJ_PODUNK_BURGERWAITRESS
	@J_DISPLAY_ITEMS:
OBJ_DIALOGUE UMSG::BURGERSHOP_NO_BUY
OBJ_CLEAR_FLAG 0
OBJ_RETURN
	@J_TAKE_MONEY:
OBJ_DIALOGUE UMSG::BURGERSHOP_NOMONEY
	@J_IS_NOT_TALKING:
OBJ_RETURN

OBJ_ELLAY_BURGERWAITRESS:
objectDef OBJ_TYPE::WANDERING_NPC, 38, DIRECTIONS::DOWN, 180
.addr SPRITEDEF_BELLHOP_WOMAN
OBJ_SUBROUTINE OBJ_PODUNK_BURGERWAITRESS, OBJ_BURGER_SUBR-OBJ_PODUNK_BURGERWAITRESS
OBJ_STOP

OBJ_MERRYSVILLE_BURGERWAITRESS:
objectDef OBJ_TYPE::WANDERING_NPC, 6, DIRECTIONS::DOWN, 244
.addr SPRITEDEF_BELLHOP_WOMAN
OBJ_SUBROUTINE OBJ_PODUNK_BURGERWAITRESS, OBJ_BURGER_SUBR-OBJ_PODUNK_BURGERWAITRESS
OBJ_STOP

OBJ_REINDEER_BURGERWAITRESS:
objectDef OBJ_TYPE::WANDERING_NPC, 582, DIRECTIONS::DOWN, 148
.addr SPRITEDEF_BELLHOP_WOMAN
OBJ_SUBROUTINE OBJ_PODUNK_BURGERWAITRESS, OBJ_BURGER_SUBR-OBJ_PODUNK_BURGERWAITRESS
OBJ_STOP

OBJ_PODUNK_BURGERWAITRESS2:
objectDef OBJ_TYPE::WANDERING_NPC, 8, DIRECTIONS::RIGHT, 343
.addr SPRITEDEF_BELLHOP_WOMAN
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_PODUNK_BURGERWAITRESS2
OBJ_DIALOGUE UMSG::BURGERSHOP_SNOTNOSED
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_REINDEER_BURGERWAITRESS2:
objectDef OBJ_TYPE::WANDERING_NPC, 580, DIRECTIONS::RIGHT, 150
.addr SPRITEDEF_BELLHOP_WOMAN
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_REINDEER_BURGERWAITRESS2
OBJ_DIALOGUE UMSG::BURGERSHOP_CASHNCARRY
	@J_IS_NOT_TALKING:
OBJ_STOP


OBJ_MERRYSVILLE_DRUGSVENDOR:
objectDef OBJ_TYPE::WANDERING_NPC, 680, DIRECTIONS::DOWN, 148
.addr SPRITEDEF_GLASSES_GUY
OBJ_SUBROUTINE OBJ_MERRYSVILLE_DRUGSVENDOR, OBJ_DRUGSVENDOR_SUBR-OBJ_MERRYSVILLE_DRUGSVENDOR
OBJ_STOP

OBJ_DRUGSVENDOR_SUBR:
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_MERRYSVILLE_DRUGSVENDOR
OBJ_DIALOGUE UMSG::DRUGSVENDOR_WELCOME
	@J_JUMP:
OBJ_SET_FLAG 0
OBJ_NOT_HAS_ITEM 0, @J_NOT_HAS_ITEM-OBJ_MERRYSVILLE_DRUGSVENDOR
OBJ_CLEAR_FLAG 0
	@J_NOT_HAS_ITEM:
OBJ_DISPLAY_ITEMS 67, 66, 65, 25, @J_DISPLAY_ITEMS-OBJ_MERRYSVILLE_DRUGSVENDOR
OBJ_IS_NOT_FLAG 0, @J_IS_NOT_FLAG-OBJ_MERRYSVILLE_DRUGSVENDOR
OBJ_DIALOGUE UMSG::DRUGSVENDOR_NOMORE
OBJ_CLEAR_FLAG 0
OBJ_RETURN
	@J_IS_NOT_FLAG:
OBJ_TAKE_MONEY @J_TAKE_MONEY-OBJ_MERRYSVILLE_DRUGSVENDOR
OBJ_DIALOGUE UMSG::SHOP_CONFIRM
OBJ_YESNO_IS_NO @J_YESNO_IS_NO-OBJ_MERRYSVILLE_DRUGSVENDOR
OBJ_DIALOGUE UMSG::BURGERSHOP_GOODBYE
OBJ_PLAY_SOUND 11
OBJ_SHOW_MONEY
OBJ_GIVE_ITEM @J_IS_NOT_TALKING-OBJ_MERRYSVILLE_DRUGSVENDOR
OBJ_DIALOGUE UMSG::BURGERSHOP_ANYMORE
OBJ_YESNO_IS_NO @J_YESNO_IS_NO1-OBJ_MERRYSVILLE_DRUGSVENDOR
OBJ_JUMP @J_JUMP-OBJ_MERRYSVILLE_DRUGSVENDOR
	@J_YESNO_IS_NO1:
OBJ_DIALOGUE UMSG::BURGERSHOP_GOODBYE
OBJ_RETURN
	@J_YESNO_IS_NO:
OBJ_GIVE_MONEY @J_IS_NOT_TALKING-OBJ_MERRYSVILLE_DRUGSVENDOR
	@J_DISPLAY_ITEMS:
OBJ_DIALOGUE UMSG::MISLAY_MOUTHWASHKID_NOTAKE
OBJ_CLEAR_FLAG 0
OBJ_RETURN
	@J_TAKE_MONEY:
OBJ_DIALOGUE UMSG::HOSPITAL_NURSE_NOMONEY
	@J_IS_NOT_TALKING:
OBJ_RETURN

OBJ_ELLAY_DRUGSVENDOR:
objectDef OBJ_TYPE::WANDERING_NPC, 744, DIRECTIONS::DOWN, 148
.addr SPRITEDEF_GLASSES_GUY
OBJ_SUBROUTINE OBJ_MERRYSVILLE_DRUGSVENDOR, OBJ_DRUGSVENDOR_SUBR-OBJ_MERRYSVILLE_DRUGSVENDOR
OBJ_STOP

OBJ_REINDEER_DRUGSVENDOR:
objectDef OBJ_TYPE::WANDERING_NPC, 40, DIRECTIONS::DOWN, 308
.addr SPRITEDEF_GLASSES_GUY
OBJ_SUBROUTINE OBJ_MERRYSVILLE_DRUGSVENDOR, OBJ_DRUGSVENDOR_SUBR-OBJ_MERRYSVILLE_DRUGSVENDOR
OBJ_STOP

OBJ_PODUNK_DRUGSVENDOR:
objectDef OBJ_TYPE::WANDERING_NPC, 40, DIRECTIONS::DOWN, 244
.addr SPRITEDEF_GLASSES_GUY
OBJ_SUBROUTINE OBJ_MERRYSVILLE_DRUGSVENDOR, OBJ_DRUGSVENDOR_SUBR-OBJ_MERRYSVILLE_DRUGSVENDOR
OBJ_STOP

