OBJ_BANK_26:
.addr OBJ_ELLAY_HOTELDOWNSTAIRS
.addr OBJ_ELLAY_HOTELROOMLEFTENTRANCE
.addr OBJ_ELLAY_HOTELROOMRIGHTENTRANCE
.addr OBJ_ELLAY_HOTELROOMLEFTEXIT
.addr OBJ_REINDEER_HOTELROOMLEFTEXIT
.addr OBJ_REINDEER_HOTELROOMRIGHTEXIT
.addr OBJ_REINDEER_HOTELDOWNSTAIRS2
.addr OBJ_YOUNGTOWN_INNTOPROOMEXIT
.addr OBJ_YOUNGTOWN_INNBOTTOMROOMEXIT
.addr OBJ_SPOOKANE_HOTELDOWNSTAIRS
.addr OBJ_SPOOKANE_HOTELROOMLEFTENTRANCE
.addr OBJ_SPOOKANE_HOTELROOMRIGHTENTRANCE
.addr OBJ_REINDEER_HOSPITALDOWNSTAIRS
.addr OBJ_REINDEER_HOSPITALROOMLEFTENTRANCE
.addr OBJ_REINDEER_HOSPITALROOMRIGHTENTRANCE
.addr OBJ_ELLAY_HOTELLADY
.addr OBJ_ELLAY_HOTELBIGLADY
.addr OBJ_ELLAY_HOTELCOLDLADY
.addr OBJ_REINDEER_HOTELMEANGUY
.addr OBJ_REINDEER_HOTELWAITER
.addr OBJ_REINDEER_HOTELWAITINGGUY
.addr OBJ_REINDEER_HOTELFAVFOODGIRL
.addr 0

OBJ_ELLAY_HOTELDOWNSTAIRS:
objectDef OBJ_TYPE::STAIRS, 497, DIRECTIONS::LEFT, 150
doorArgDef 0, 691, DIRECTIONS::RIGHT, 1013

OBJ_ELLAY_HOTELROOMLEFTENTRANCE:
objectDef OBJ_TYPE::DOOR, 502, DIRECTIONS::UP, 147
doorArgDef 0, 573, DIRECTIONS::LEFT, 150

OBJ_ELLAY_HOTELROOMRIGHTENTRANCE:
objectDef OBJ_TYPE::DOOR, 505, DIRECTIONS::UP, 147
doorArgDef 0, 605, DIRECTIONS::LEFT, 150

OBJ_ELLAY_HOTELROOMLEFTEXIT:
objectDef OBJ_TYPE::DOOR, 574, DIRECTIONS::RIGHT, 150
doorArgDef 0, 502, DIRECTIONS::DOWN, 148

OBJ_REINDEER_HOTELROOMLEFTEXIT:
objectDef OBJ_TYPE::DOOR, 30, DIRECTIONS::RIGHT, 246
doorArgDef 0, 22, DIRECTIONS::DOWN, 212

OBJ_REINDEER_HOTELROOMRIGHTEXIT:
objectDef OBJ_TYPE::DOOR, 30, DIRECTIONS::RIGHT, 278
doorArgDef 0, 25, DIRECTIONS::DOWN, 212

OBJ_REINDEER_HOTELDOWNSTAIRS2:
objectDef OBJ_TYPE::STAIRS, 49, DIRECTIONS::LEFT, 278
doorArgDef 0, 19, DIRECTIONS::RIGHT, 213

OBJ_YOUNGTOWN_INNTOPROOMEXIT:
objectDef OBJ_TYPE::DOOR, 542, DIRECTIONS::RIGHT, 150
doorArgDef 0, 691, DIRECTIONS::RIGHT, 981

OBJ_YOUNGTOWN_INNBOTTOMROOMEXIT:
objectDef OBJ_TYPE::DOOR, 446, DIRECTIONS::RIGHT, 150
doorArgDef 0, 689, DIRECTIONS::RIGHT, 983

OBJ_SPOOKANE_HOTELDOWNSTAIRS:
objectDef OBJ_TYPE::STAIRS, 49, DIRECTIONS::LEFT, 214
doorArgDef 0, 3, DIRECTIONS::RIGHT, 229

OBJ_SPOOKANE_HOTELROOMLEFTENTRANCE:
objectDef OBJ_TYPE::DOOR, 54, DIRECTIONS::UP, 211
doorArgDef 0, 61, DIRECTIONS::LEFT, 246

OBJ_SPOOKANE_HOTELROOMRIGHTENTRANCE:
objectDef OBJ_TYPE::DOOR, 57, DIRECTIONS::UP, 211
doorArgDef 0, 477, DIRECTIONS::LEFT, 150

OBJ_REINDEER_HOSPITALDOWNSTAIRS:
objectDef OBJ_TYPE::STAIRS, 17, DIRECTIONS::LEFT, 342
doorArgDef 0, 723, DIRECTIONS::RIGHT, 1013

OBJ_REINDEER_HOSPITALROOMLEFTENTRANCE:
objectDef OBJ_TYPE::DOOR, 22, DIRECTIONS::UP, 339
doorArgDef 0, 29, DIRECTIONS::LEFT, 150

OBJ_REINDEER_HOSPITALROOMRIGHTENTRANCE:
objectDef OBJ_TYPE::DOOR, 25, DIRECTIONS::UP, 339
doorArgDef 0, 29, DIRECTIONS::LEFT, 182

OBJ_ELLAY_HOTELLADY:
objectDef OBJ_TYPE::WANDERING_NPC, 507, DIRECTIONS::RIGHT, 150
.addr SPRITEDEF_WOMAN
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_ELLAY_HOTELLADY
OBJ_DIALOGUE UMSG::ELLAY_HOTELLADY
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_ELLAY_HOTELBIGLADY:
objectDef OBJ_TYPE::WANDERING_NPC, 565, DIRECTIONS::RIGHT, 151
.addr SPRITEDEF_BIGLADY
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_ELLAY_HOTELBIGLADY
OBJ_DIALOGUE UMSG::ELLAY_HOTELBIGLADY
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_ELLAY_HOTELCOLDLADY:
objectDef OBJ_TYPE::WANDERING_NPC, 22, DIRECTIONS::DOWN, 247
.addr SPRITEDEF_OLD_WOMAN
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_ELLAY_HOTELCOLDLADY
OBJ_DIALOGUE UMSG::ELLAY_HOTELCOLDLADY
OBJ_PICK_CHARACTER_J 0, @J_IS_NOT_TALKING-OBJ_ELLAY_HOTELCOLDLADY
OBJ_GIVE_STATUS 1
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_REINDEER_HOTELMEANGUY:
objectDef OBJ_TYPE::WANDERING_NPC, 24, DIRECTIONS::LEFT, 277
.addr SPRITEDEF_MAN
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_REINDEER_HOTELMEANGUY
OBJ_DIALOGUE UMSG::REINDEER_HOTELMEANGUY
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_REINDEER_HOTELWAITER:
objectDef OBJ_TYPE::WANDERING_NPC, 52, DIRECTIONS::DOWN, 276
.addr SPRITEDEF_MOUSTACHE_GUY
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_REINDEER_HOTELWAITER
OBJ_DIALOGUE UMSG::MERRYSVILLE_HOTELWAITER
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_REINDEER_HOTELWAITINGGUY:
objectDef OBJ_TYPE::WANDERING_NPC, 56, DIRECTIONS::RIGHT, 277
.addr SPRITEDEF_MAN
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_REINDEER_HOTELWAITINGGUY
OBJ_DIALOGUE UMSG::REINDEER_HOTELWAITINGGUY
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_REINDEER_HOTELFAVFOODGIRL:
objectDef OBJ_TYPE::WANDERING_NPC, 60, DIRECTIONS::DOWN, 279
.addr SPRITEDEF_SECRETARY
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_REINDEER_HOTELFAVFOODGIRL
OBJ_DIALOGUE UMSG::REINDEER_HOTELFAVFOODGIRL
	@J_IS_NOT_TALKING:
OBJ_STOP