OBJ_BANK_1C:
.addr OBJ_ROSEMARYHOUSE_DOOR1
.addr OBJ_ROSEMARYHOUSE_DOOR2
.addr OBJ_ROSEMARYHOUSE_DOOR3
.addr OBJ_ROSEMARYHOUSE_DOOR4
.addr OBJ_ROSEMARYHOUSE_DOOR5
.addr OBJ_ROSEMARYHOUSE_DOOR6
.addr OBJ_ROSEMARYHOUSE_DOOR7
.addr OBJ_ROSEMARYHOUSE_DOOR8
.addr OBJ_ROSEMARYHOUSE_DOOR9
.addr OBJ_ROSEMARYHOUSE_DOOR10
.addr OBJ_ROSEMARYHOUSE_DOOR11
.addr OBJ_ROSEMARYHOUSE_DOOR12
.addr OBJ_ROSEMARYHOUSE_DOOR13
.addr OBJ_ROSEMARYHOUSE_PRESENT1
.addr OBJ_ROSEMARYHOUSE_PIANOLEFT
.addr OBJ_ROSEMARYHOUSE_PIANORIGHT
.addr 0

OBJ_ROSEMARYHOUSE_DOOR1:
objectDef OBJ_TYPE::DOOR, $27e, DIRECTIONS::RIGHT, $86
doorArgDef $0, $1F1, DIRECTIONS::RIGHT, $87

OBJ_ROSEMARYHOUSE_DOOR2:
objectDef OBJ_TYPE::DOOR, $272, DIRECTIONS::LEFT, $85
doorArgDef $0, $31E, DIRECTIONS::LEFT, $3E2

OBJ_ROSEMARYHOUSE_DOOR3:
objectDef OBJ_TYPE::DOOR, $270, DIRECTIONS::LEFT, $87
doorArgDef $0, $2EE, DIRECTIONS::LEFT, $3B2


OBJ_ROSEMARYHOUSE_DOOR4:
objectDef OBJ_TYPE::DOOR, $21d, DIRECTIONS::RIGHT, $85
doorArgDef $0, $31, DIRECTIONS::RIGHT, $107

OBJ_ROSEMARYHOUSE_DOOR5:
objectDef OBJ_TYPE::DOOR, $21f, DIRECTIONS::RIGHT, $87
doorArgDef $0, $253, DIRECTIONS::RIGHT, $85


OBJ_ROSEMARYHOUSE_DOOR6:
objectDef OBJ_TYPE::DOOR, $29e, DIRECTIONS::RIGHT, $86
doorArgDef $0, $11, DIRECTIONS::RIGHT, $87

OBJ_ROSEMARYHOUSE_DOOR7:
objectDef OBJ_TYPE::DOOR, $291, DIRECTIONS::LEFT, $86
doorArgDef $0, $3D, DIRECTIONS::LEFT, $C6


OBJ_ROSEMARYHOUSE_DOOR8:
objectDef OBJ_TYPE::DOOR, $23d, DIRECTIONS::RIGHT, $85
doorArgDef $0, $33, DIRECTIONS::RIGHT, $105

OBJ_ROSEMARYHOUSE_DOOR9:
objectDef OBJ_TYPE::DOOR, $23f, DIRECTIONS::RIGHT, $87
doorArgDef $0, $251, DIRECTIONS::RIGHT, $87


OBJ_ROSEMARYHOUSE_DOOR10:
objectDef OBJ_TYPE::DOOR, $3e, DIRECTIONS::RIGHT, $86
doorArgDef $0, $275, DIRECTIONS::RIGHT, $3BF

OBJ_ROSEMARYHOUSE_DOOR11:
objectDef OBJ_TYPE::DOOR, $32, DIRECTIONS::LEFT, $85
doorArgDef $0, $2BE, DIRECTIONS::LEFT, $3E2

OBJ_ROSEMARYHOUSE_DOOR12:
objectDef OBJ_TYPE::DOOR, $30, DIRECTIONS::LEFT, $87
doorArgDef $0, $2BE, DIRECTIONS::LEFT, $3B2


OBJ_ROSEMARYHOUSE_DOOR13:
objectDef OBJ_TYPE::DOOR, $1e, DIRECTIONS::RIGHT, $e6
doorArgDef $0, $2D5, DIRECTIONS::RIGHT, $3BF

OBJ_ROSEMARYHOUSE_PRESENT1:
objectDef OBJ_TYPE::PRESENT, 23, DIRECTIONS::UP, 230
.addr SPRITEDEF_PRESENT
.byte 65 ; item
.byte 3 ; flag

OBJ_ROSEMARYHOUSE_PIANOLEFT:
objectDef $19, $14, DIRECTIONS::UP, $e4
.addr SPRITEDEF_PIANOLEFT ;sprite
OBJ_IS_NOT_CHECKING @JCHECK0-OBJ_ROSEMARYHOUSE_PIANOLEFT
OBJ_SIGNAL $F
    @JCHECK0:
OBJ_STOP

OBJ_ROSEMARYHOUSE_PIANORIGHT:
objectDef $19, $15, DIRECTIONS::UP, $e4
.addr SPRITEDEF_PIANORIGHT ;sprite
OBJ_IS_NOT_CHECKING @JCHECK0-OBJ_ROSEMARYHOUSE_PIANORIGHT
OBJ_JUMP @JUMP1-OBJ_ROSEMARYHOUSE_PIANORIGHT
    @JCHECK0:
OBJ_IS_SIGNAL @JSIGNALED2-OBJ_ROSEMARYHOUSE_PIANORIGHT
    @JUMP1:
OBJ_DIALOGUE UMSG::ROSEMARYHOUSE_PIANO_MELODY
OBJ_PLAY_MUSIC $27
OBJ_DELAY $F0
OBJ_PLAY_MUSIC $D
OBJ_SET_FLAG $F4
OBJ_SET_FLAG $F
OBJ_DIALOGUE UMSG::REMEMBER_MELODY
.ifdef VER_JP
OBJ_CHECK_MELODIES
.endif
    @JSIGNALED2:
OBJ_STOP