OBJ_BANK_21:
.addr OBJ_MERRYSVILLE_DEPTDOWNSTAIRS4
.addr OBJ_ELLAY_DEPTDOWNSTAIRS2
.addr OBJ_ELLAY_DEPTUPSTAIRS3
.addr OBJ_REINDEER_STATIONEXIT
.addr OBJ_MERRYSVILLE_STATIONEXIT
.addr OBJ_SNOWMAN_STATIONEXIT
.addr OBJ_SPOOKANE_STATIONEXIT
.addr OBJ_YOUNGTOWN_STATIONEXIT
.addr OBJ_MERRYSVILLE_VARIETYVENDOR
.addr OBJ_ELLAY_FOODSVENDOR
.addr OBJ_MERRYSVILLE_TRAINGUARDIAN
.addr OBJ_SNOWMAN_TRAINDAUGHTER
.addr OBJ_SNOWMAN_TRAINDAD
.addr OBJ_REINDEER_ANAHATWOMAN
.addr OBJ_YOUNGTOWN_TRAINMAN
.addr OBJ_MERRYSVILLE_TRAINMAN
.addr OBJ_REINDEER_TRAINMAN
.addr OBJ_SPOOKANE_TRAINMAN
.addr OBJ_SNOWMAN_TRAINMAN
.addr 0

OBJ_MERRYSVILLE_DEPTDOWNSTAIRS4:
objectDef OBJ_TYPE::STAIRS, 2, DIRECTIONS::LEFT, 213
doorArgDef 0, 2, DIRECTIONS::RIGHT, 150

OBJ_ELLAY_DEPTDOWNSTAIRS2:
objectDef OBJ_TYPE::STAIRS, 770, DIRECTIONS::LEFT, 149
doorArgDef 0, 738, DIRECTIONS::RIGHT, 150

OBJ_ELLAY_DEPTUPSTAIRS3:
objectDef OBJ_TYPE::STAIRS, 769, DIRECTIONS::LEFT, 150
doorArgDef 0, 739, DIRECTIONS::RIGHT, 997

OBJ_REINDEER_STATIONEXIT:
objectDef OBJ_TYPE::DOOR, 609, DIRECTIONS::UP, 964
doorArgDef 6, 513, DIRECTIONS::DOWN, 831

OBJ_MERRYSVILLE_STATIONEXIT:
objectDef OBJ_TYPE::DOOR, 657, DIRECTIONS::UP, 964
doorArgDef 6, 321, DIRECTIONS::DOWN, 335

OBJ_SNOWMAN_STATIONEXIT:
objectDef OBJ_TYPE::DOOR, 721, DIRECTIONS::UP, 964
doorArgDef 10, 862, DIRECTIONS::DOWN, 995

OBJ_SPOOKANE_STATIONEXIT:
objectDef OBJ_TYPE::DOOR, 657, DIRECTIONS::UP, 996
doorArgDef 6, 681, DIRECTIONS::DOWN, 831

OBJ_YOUNGTOWN_STATIONEXIT:
objectDef OBJ_TYPE::DOOR, 721, DIRECTIONS::UP, 996
doorArgDef 8, 745, DIRECTIONS::DOWN, 415

OBJ_MERRYSVILLE_VARIETYVENDOR:
objectDef OBJ_TYPE::WANDERING_NPC, 8, DIRECTIONS::DOWN, 212
.addr SPRITEDEF_SUIT_GIRL
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_MERRYSVILLE_VARIETYVENDOR
.ifndef VER_JP
OBJ_DIALOGUE UMSG::DRUGSVENDOR_WELCOME
	@J_JUMP:
.endif
OBJ_SET_FLAG 0
OBJ_NOT_HAS_ITEM 0, @J_NOT_HAS_ITEM-OBJ_MERRYSVILLE_VARIETYVENDOR
OBJ_CLEAR_FLAG 0
	@J_NOT_HAS_ITEM:
.ifdef VER_JP
OBJ_DIALOGUE UMSG::DRUGSVENDOR_WELCOME
OBJ_DISPLAY_ITEMS 109, 2, 14, 40, @J_DISPLAY_ITEMS-OBJ_MERRYSVILLE_VARIETYVENDOR
.else
OBJ_DISPLAY_ITEMS 109, 14, 40, 4, @J_DISPLAY_ITEMS-OBJ_MERRYSVILLE_VARIETYVENDOR
.endif
OBJ_IS_NOT_SELECTED 2, @J_IS_NOT_SELECTED-OBJ_MERRYSVILLE_VARIETYVENDOR
OBJ_DIALOGUE UMSG::VARIETYVENDOR_OUTOFSTOCK
OBJ_CLEAR_FLAG 0
OBJ_STOP
	@J_IS_NOT_SELECTED:
OBJ_IS_NOT_FLAG 0, @J_IS_NOT_FLAG-OBJ_MERRYSVILLE_VARIETYVENDOR
OBJ_DIALOGUE UMSG::BURGERSHOP_NO_ROOM
OBJ_CLEAR_FLAG 0
OBJ_STOP
	@J_IS_NOT_FLAG:
OBJ_TAKE_MONEY @J_TAKE_MONEY-OBJ_MERRYSVILLE_VARIETYVENDOR
OBJ_DIALOGUE UMSG::SHOP_CONFIRM
OBJ_YESNO_IS_NO @J_YESNO_IS_NO-OBJ_MERRYSVILLE_VARIETYVENDOR
OBJ_DIALOGUE UMSG::BURGERSHOP_GOODBYE
OBJ_PLAY_SOUND 11
OBJ_SHOW_MONEY
OBJ_GIVE_ITEM @J_IS_NOT_TALKING-OBJ_MERRYSVILLE_VARIETYVENDOR
.ifndef VER_JP
OBJ_DIALOGUE UMSG::BURGERSHOP_ANYMORE
OBJ_YESNO_IS_NO @J_YESNO_IS_NO1-OBJ_MERRYSVILLE_VARIETYVENDOR
OBJ_JUMP @J_JUMP-OBJ_MERRYSVILLE_VARIETYVENDOR
	@J_YESNO_IS_NO1:
OBJ_DIALOGUE UMSG::BURGERSHOP_GOODBYE
.endif
OBJ_STOP
	@J_YESNO_IS_NO:
OBJ_GIVE_MONEY @J_IS_NOT_TALKING-OBJ_MERRYSVILLE_VARIETYVENDOR
	@J_DISPLAY_ITEMS:
OBJ_DIALOGUE UMSG::BURGERSHOP_NO_BUY
OBJ_CLEAR_FLAG 0
OBJ_STOP
	@J_TAKE_MONEY:
OBJ_DIALOGUE UMSG::BURGERSHOP_NOMONEY
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_ELLAY_FOODSVENDOR:
objectDef OBJ_TYPE::WANDERING_NPC, 776, DIRECTIONS::DOWN, 148
.addr SPRITEDEF_SUIT_GUY
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_ELLAY_FOODSVENDOR
.ifndef VER_JP
OBJ_DIALOGUE UMSG::DRUGSVENDOR_WELCOME
	@J_JUMP:
.endif
OBJ_SET_FLAG 0
OBJ_NOT_HAS_ITEM 0, @J_NOT_HAS_ITEM-OBJ_ELLAY_FOODSVENDOR
OBJ_CLEAR_FLAG 0
	@J_NOT_HAS_ITEM:
.ifdef VER_JP
OBJ_DIALOGUE UMSG::DRUGSVENDOR_WELCOME
.endif
OBJ_DISPLAY_ITEMS 60, 71, 64, 69, @J_DISPLAY_ITEMS-OBJ_ELLAY_FOODSVENDOR
OBJ_IS_NOT_FLAG 0, @J_IS_NOT_FLAG-OBJ_ELLAY_FOODSVENDOR
OBJ_DIALOGUE UMSG::DRUGSVENDOR_NOMORE
OBJ_CLEAR_FLAG 0
OBJ_STOP
	@J_IS_NOT_FLAG:
OBJ_TAKE_MONEY @J_TAKE_MONEY-OBJ_ELLAY_FOODSVENDOR
OBJ_DIALOGUE UMSG::SHOP_CONFIRM
OBJ_YESNO_IS_NO @J_YESNO_IS_NO-OBJ_ELLAY_FOODSVENDOR
OBJ_DIALOGUE UMSG::BURGERSHOP_GOODBYE
OBJ_PLAY_SOUND 11
OBJ_SHOW_MONEY
OBJ_GIVE_ITEM @J_IS_NOT_TALKING-OBJ_ELLAY_FOODSVENDOR
.ifndef VER_JP
OBJ_DIALOGUE UMSG::BURGERSHOP_ANYMORE
OBJ_YESNO_IS_NO @J_YESNO_IS_NO1-OBJ_ELLAY_FOODSVENDOR
OBJ_JUMP @J_JUMP-OBJ_ELLAY_FOODSVENDOR
	@J_YESNO_IS_NO1:
OBJ_DIALOGUE UMSG::BURGERSHOP_GOODBYE
.endif
OBJ_STOP
	@J_YESNO_IS_NO:
OBJ_GIVE_MONEY @J_IS_NOT_TALKING-OBJ_ELLAY_FOODSVENDOR
	@J_DISPLAY_ITEMS:
OBJ_DIALOGUE UMSG::MISLAY_MOUTHWASHKID_NOTAKE
OBJ_CLEAR_FLAG 0
OBJ_STOP
	@J_TAKE_MONEY:
OBJ_DIALOGUE UMSG::HOSPITAL_NURSE_NOMONEY
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_MERRYSVILLE_TRAINGUARDIAN:
objectDef OBJ_TYPE::WANDERING_NPC, 653, DIRECTIONS::DOWN, 967
.addr SPRITEDEF_SUIT_GUY
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_MERRYSVILLE_TRAINGUARDIAN
OBJ_DIALOGUE UMSG::TRAINGUARDIAN
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_SNOWMAN_TRAINDAUGHTER:
objectDef OBJ_TYPE::WANDERING_NPC, 721, DIRECTIONS::UP, 970
.addr SPRITEDEF_WOMAN
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_SNOWMAN_TRAINDAUGHTER
OBJ_DIALOGUE UMSG::SNOWMAN_TRAINDAUGHTER
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_SNOWMAN_TRAINDAD:
objectDef OBJ_TYPE::WANDERING_NPC, 720, DIRECTIONS::RIGHT, 970
.addr SPRITEDEF_MOUSTACHE_GUY
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_SNOWMAN_TRAINDAD
OBJ_DIALOGUE UMSG::SNOWMAN_TRAINDAD
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_REINDEER_ANAHATWOMAN:
objectDef OBJ_TYPE::STATIONARY_NPC_CHECKSPAWN, 613, DIRECTIONS::LEFT, 967
.addr SPRITEDEF_OLD_WOMAN
OBJ_FLAG_DISAPPEAR 47
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_REINDEER_ANAHATWOMAN
OBJ_DIALOGUE UMSG::ANAHAT_WOMAN1
OBJ_YESNO_IS_NO @J_YESNO_IS_NO-OBJ_REINDEER_ANAHATWOMAN
OBJ_DIALOGUE UMSG::ANAHAT_WOMAN_YES
OBJ_NOT_HAS_ITEM 0, @J_NOT_HAS_ITEM-OBJ_REINDEER_ANAHATWOMAN
OBJ_PLAY_SOUND 6
OBJ_PICK_ITEM 98
OBJ_GIVE_ITEM @J_IS_NOT_TALKING-OBJ_REINDEER_ANAHATWOMAN
OBJ_MOVE @MOVE_DATA
OBJ_SET_FLAG 47
OBJ_STOP
	@J_NOT_HAS_ITEM:
OBJ_DIALOGUE UMSG::PODUNK_PIPPI_NOROOM2
OBJ_STOP
	@J_YESNO_IS_NO:
OBJ_DIALOGUE UMSG::ANAHAT_WOMAN_NO
	@J_IS_NOT_TALKING:
OBJ_STOP

@MOVE_DATA:
moveDef DIRECTIONS::LEFT, MOVE_CMD::MOVEFACE, 4
moveDef DIRECTIONS::UP, MOVE_CMD::MOVEFACE, 2
OBJ_STOP

OBJ_YOUNGTOWN_TRAINMAN:
objectDef OBJ_TYPE::STATIONARY_NPC, 733, DIRECTIONS::DOWN, 1001
.addr SPRITEDEF_SUIT_GUY
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_YOUNGTOWN_TRAINMAN
OBJ_DIALOGUE UMSG::YOUNGTOWN_TRAINMAN
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_MERRYSVILLE_TRAINMAN:
objectDef OBJ_TYPE::STATIONARY_NPC, 669, DIRECTIONS::LEFT, 969
.addr SPRITEDEF_SUIT_GUY
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_MERRYSVILLE_TRAINMAN
OBJ_IS_NOT_FLAG 113, @J_IS_NOT_FLAG-OBJ_MERRYSVILLE_TRAINMAN
OBJ_JUMP @J_JUMP-OBJ_MERRYSVILLE_TRAINMAN
	@J_IS_NOT_FLAG:
OBJ_DIALOGUE UMSG::TRAIN_CANTMOVE
OBJ_STOP
	@J_JUMP:
OBJ_DIALOGUE UMSG::TRAIN1
OBJ_DISPLAY_ITEMS 144, 145, 146, 0, @J_DISPLAY_ITEMS-OBJ_MERRYSVILLE_TRAINMAN
OBJ_MULTIPLY_BY_PARTY
OBJ_DIALOGUE UMSG::TRAIN_ACCEPT
OBJ_YESNO_IS_NO @J_DISPLAY_ITEMS-OBJ_MERRYSVILLE_TRAINMAN
OBJ_TAKE_MONEY @J_TAKE_MONEY-OBJ_MERRYSVILLE_TRAINMAN
OBJ_TRAIN
OBJ_STOP
	@J_TAKE_MONEY:
OBJ_DIALOGUE UMSG::YUCCA_PILOT_NOMONEY
OBJ_STOP
	@J_DISPLAY_ITEMS:
OBJ_DIALOGUE UMSG::TRAIN_DECLINE
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_REINDEER_TRAINMAN:
objectDef OBJ_TYPE::STATIONARY_NPC, 621, DIRECTIONS::LEFT, 969
.addr SPRITEDEF_SUIT_GUY
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_REINDEER_TRAINMAN
OBJ_IS_NOT_FLAG 113, @J_IS_NOT_FLAG-OBJ_REINDEER_TRAINMAN
OBJ_JUMP @J_JUMP-OBJ_REINDEER_TRAINMAN
	@J_IS_NOT_FLAG:
OBJ_DIALOGUE UMSG::TRAIN_CANTMOVE
OBJ_STOP
	@J_JUMP:
OBJ_DIALOGUE UMSG::TRAIN1
OBJ_DISPLAY_ITEMS 147, 150, 151, 0, @J_DISPLAY_ITEMS-OBJ_REINDEER_TRAINMAN
OBJ_MULTIPLY_BY_PARTY
OBJ_DIALOGUE UMSG::TRAIN_ACCEPT
OBJ_YESNO_IS_NO @J_DISPLAY_ITEMS-OBJ_REINDEER_TRAINMAN
OBJ_TAKE_MONEY @J_TAKE_MONEY-OBJ_REINDEER_TRAINMAN
OBJ_TRAIN
OBJ_STOP
	@J_TAKE_MONEY:
OBJ_DIALOGUE UMSG::YUCCA_PILOT_NOMONEY
OBJ_STOP
	@J_DISPLAY_ITEMS:
OBJ_DIALOGUE UMSG::TRAIN_DECLINE
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_SPOOKANE_TRAINMAN:
objectDef OBJ_TYPE::STATIONARY_NPC, 669, DIRECTIONS::LEFT, 1001
.addr SPRITEDEF_SUIT_GUY
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_SPOOKANE_TRAINMAN
OBJ_IS_NOT_FLAG 113, @J_IS_NOT_FLAG-OBJ_SPOOKANE_TRAINMAN
OBJ_JUMP @J_JUMP-OBJ_SPOOKANE_TRAINMAN
	@J_IS_NOT_FLAG:
OBJ_DIALOGUE UMSG::TRAIN_CANTMOVE
OBJ_STOP
	@J_JUMP:
OBJ_DIALOGUE UMSG::TRAIN1
OBJ_DISPLAY_ITEMS 148, 152, 153, 0, @J_DISPLAY_ITEMS-OBJ_SPOOKANE_TRAINMAN
OBJ_MULTIPLY_BY_PARTY
OBJ_DIALOGUE UMSG::TRAIN_ACCEPT
OBJ_YESNO_IS_NO @J_DISPLAY_ITEMS-OBJ_SPOOKANE_TRAINMAN
OBJ_TAKE_MONEY @J_TAKE_MONEY-OBJ_SPOOKANE_TRAINMAN
OBJ_TRAIN
OBJ_STOP
	@J_TAKE_MONEY:
OBJ_DIALOGUE UMSG::YUCCA_PILOT_NOMONEY
OBJ_STOP
	@J_DISPLAY_ITEMS:
OBJ_DIALOGUE UMSG::TRAIN_DECLINE
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_SNOWMAN_TRAINMAN:
objectDef OBJ_TYPE::STATIONARY_NPC, 733, DIRECTIONS::LEFT, 969
.addr SPRITEDEF_SUIT_GUY
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_SNOWMAN_TRAINMAN
OBJ_IS_NOT_FLAG 113, @J_IS_NOT_FLAG-OBJ_SNOWMAN_TRAINMAN
OBJ_JUMP @J_JUMP-OBJ_SNOWMAN_TRAINMAN
	@J_IS_NOT_FLAG:
OBJ_DIALOGUE UMSG::TRAIN_CANTMOVE
OBJ_STOP
	@J_JUMP:
OBJ_DIALOGUE UMSG::SNOWMAN_TRAIN
OBJ_DIALOGUE UMSG::TRAIN1
OBJ_DISPLAY_ITEMS 149, 154, 155, 0, @J_DISPLAY_ITEMS-OBJ_SNOWMAN_TRAINMAN
OBJ_MULTIPLY_BY_PARTY
OBJ_DIALOGUE UMSG::TRAIN_ACCEPT
OBJ_YESNO_IS_NO @J_DISPLAY_ITEMS-OBJ_SNOWMAN_TRAINMAN
OBJ_TAKE_MONEY @J_TAKE_MONEY-OBJ_SNOWMAN_TRAINMAN
OBJ_TRAIN
OBJ_STOP
	@J_TAKE_MONEY:
OBJ_DIALOGUE UMSG::YUCCA_PILOT_NOMONEY
OBJ_STOP
	@J_DISPLAY_ITEMS:
OBJ_DIALOGUE UMSG::TRAIN_DECLINE
	@J_IS_NOT_TALKING:
OBJ_STOP