OBJ_BANK_27:
.addr OBJ_TWINKLE_F2_ROOM6EXIT
.addr OBJ_TWINKLE_F1_ROOM1EXIT
.addr OBJ_TWINKLE_F1_ROOM2EXIT
.addr OBJ_TWINKLE_F2_ROOM1EXIT
.addr OBJ_TWINKLE_F2_ROOM2EXIT
.addr OBJ_TWINKLE_F1_ROOM3EXIT
.addr OBJ_TWINKLE_F2_ROOM3EXIT
.addr OBJ_TWINKLE_JANITOREXIT
.addr OBJ_TWINKLE_ENGINEERKID
.addr OBJ_TWINKLE_COLDGIRL
.addr OBJ_TWINKLE_MUSICGIRL
.addr OBJ_TWINKLE_GLASSESGIRL
.addr OBJ_TWINKLE_SUZY
.addr OBJ_TWINKLE_JANITORGIRL
.addr OBJ_TWINKLE_ALLCARTWHEELGIRL
.addr OBJ_TWINKLE_CANTCARTWHEELGIRL
.addr OBJ_TWINKLE_SUBTRACTIONGIRL
.addr OBJ_TWINKLE_GAMEBOYKID
.addr OBJ_TWINKLE_SITUPSKID
.addr OBJ_TWINKLE_TOFUKID
.addr OBJ_TWINKLE_BAFFLEDKID
.addr OBJ_TWINKLE_HUNGRYKID
.addr OBJ_TWINKLE_DADGIRL
.addr OBJ_TWINKLE_LATEGIRL
.addr OBJ_TWINKLE_STRANGEGIRL
.addr OBJ_TWINKLE_GAMEKID
.addr OBJ_TWINKLE_JANITOR
.addr 0

OBJ_TWINKLE_F2_ROOM6EXIT:
objectDef OBJ_TYPE::DOOR, 62, DIRECTIONS::RIGHT, 342
doorArgDef 0, 785, DIRECTIONS::DOWN, 980

OBJ_TWINKLE_F1_ROOM1EXIT:
objectDef OBJ_TYPE::DOOR, 622, DIRECTIONS::RIGHT, 982
doorArgDef 0, 758, DIRECTIONS::DOWN, 952

OBJ_TWINKLE_F1_ROOM2EXIT:
objectDef OBJ_TYPE::DOOR, 718, DIRECTIONS::RIGHT, 982
doorArgDef 0, 762, DIRECTIONS::DOWN, 952

OBJ_TWINKLE_F2_ROOM1EXIT:
objectDef OBJ_TYPE::DOOR, 718, DIRECTIONS::RIGHT, 950
doorArgDef 0, 766, DIRECTIONS::DOWN, 980

OBJ_TWINKLE_F2_ROOM2EXIT:
objectDef OBJ_TYPE::DOOR, 750, DIRECTIONS::RIGHT, 982
doorArgDef 0, 770, DIRECTIONS::DOWN, 980

OBJ_TWINKLE_F1_ROOM3EXIT:
objectDef OBJ_TYPE::DOOR, 718, DIRECTIONS::RIGHT, 1014
doorArgDef 0, 765, DIRECTIONS::DOWN, 952

OBJ_TWINKLE_F2_ROOM3EXIT:
objectDef OBJ_TYPE::DOOR, 750, DIRECTIONS::RIGHT, 1014
doorArgDef 0, 774, DIRECTIONS::DOWN, 980

OBJ_TWINKLE_JANITOREXIT:
objectDef OBJ_TYPE::DOOR, 798, DIRECTIONS::RIGHT, 966
doorArgDef 0, 789, DIRECTIONS::DOWN, 952

OBJ_TWINKLE_ENGINEERKID:
objectDef OBJ_TYPE::STATIONARY_NPC, 52, DIRECTIONS::DOWN, 340
.addr SPRITEDEF_HEADBAND_KID
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_TWINKLE_ENGINEERKID
OBJ_DIALOGUE UMSG::TWINKLE_ENGINEERKID
OBJ_MOVE OBJ_TWINKLE_FACEBACKDOWN
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_TWINKLE_COLDGIRL:
objectDef OBJ_TYPE::STATIONARY_NPC, 50, DIRECTIONS::DOWN, 342
.addr SPRITEDEF_PIGTAIL_GIRL
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_TWINKLE_COLDGIRL
OBJ_DIALOGUE UMSG::TWINKLE_COLDGIRL
OBJ_MOVE OBJ_TWINKLE_FACEBACKDOWN
OBJ_PICK_CHARACTER_J 0, @J_IS_NOT_TALKING-OBJ_TWINKLE_COLDGIRL
OBJ_GIVE_STATUS 1
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_TWINKLE_MUSICGIRL:
objectDef OBJ_TYPE::STATIONARY_NPC, 55, DIRECTIONS::DOWN, 340
.addr SPRITEDEF_PONYTAIL_GIRL
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_TWINKLE_MUSICGIRL
OBJ_DIALOGUE UMSG::TWINKLE_MUSICGIRL
OBJ_MOVE OBJ_TWINKLE_FACEBACKDOWN
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_TWINKLE_FACEBACKDOWN:
moveDef DIRECTIONS::DOWN, MOVE_CMD::ABOUTFACE, 1
OBJ_STOP

OBJ_TWINKLE_GLASSESGIRL:
objectDef OBJ_TYPE::WANDERING_NPC, 614, DIRECTIONS::RIGHT, 983
.addr SPRITEDEF_PONYTAIL_GIRL
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_TWINKLE_GLASSESGIRL
OBJ_NOT_HAS_CHARACTER 3, @J_NOT_HAS_CHARACTER-OBJ_TWINKLE_GLASSESGIRL
OBJ_HAS_STATUS %10000000, @J_HAS_STATUS-OBJ_TWINKLE_GLASSESGIRL
OBJ_DIALOGUE UMSG::TWINKLE_GLASSESSLIPPED
OBJ_STOP
	@J_HAS_STATUS:
OBJ_DIALOGUE UMSG::TWINKLE_LLOYDMATTER
OBJ_STOP
	@J_NOT_HAS_CHARACTER:
OBJ_DIALOGUE UMSG::TWINKLE_LLOYDEXPLOSIVES
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_TWINKLE_SUZY:
objectDef OBJ_TYPE::WANDERING_NPC, 615, DIRECTIONS::RIGHT, 980
.addr SPRITEDEF_PIGTAIL_GIRL
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_TWINKLE_SUZY
OBJ_DIALOGUE UMSG::TWINKLE_SUZY
OBJ_YESNO_IS_NO @J_YESNO_IS_NO-OBJ_TWINKLE_SUZY
OBJ_DIALOGUE UMSG::TWINKLE_SUZY_YES
OBJ_STOP
	@J_YESNO_IS_NO:
OBJ_DIALOGUE UMSG::TWINKLE_SUZY_NO
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_TWINKLE_JANITORGIRL:
objectDef OBJ_TYPE::WANDERING_NPC, 622, DIRECTIONS::RIGHT, 983
.addr SPRITEDEF_PONYTAIL_GIRL
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_TWINKLE_JANITORGIRL
OBJ_DIALOGUE UMSG::TWINKLE_JANITORGIRL
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_TWINKLE_ALLCARTWHEELGIRL:
objectDef OBJ_TYPE::WANDERING_NPC, 705, DIRECTIONS::DOWN, 983
.addr SPRITEDEF_PONYTAIL_GIRL
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_TWINKLE_ALLCARTWHEELGIRL
OBJ_DIALOGUE UMSG::TWINKLE_ALLCARTWHEELGIRL
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_TWINKLE_CANTCARTWHEELGIRL:
objectDef OBJ_TYPE::WANDERING_NPC, 715, DIRECTIONS::DOWN, 980
.addr SPRITEDEF_HEADBAND_KID_2
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_TWINKLE_CANTCARTWHEELGIRL
OBJ_DIALOGUE UMSG::TWINKLE_CANTCARTWHEELGIRL
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_TWINKLE_SUBTRACTIONGIRL:
objectDef OBJ_TYPE::WANDERING_NPC, 715, DIRECTIONS::LEFT, 982
.addr SPRITEDEF_PIGTAIL_GIRL
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_TWINKLE_SUBTRACTIONGIRL
OBJ_DIALOGUE UMSG::TWINKLE_SUBTRACTIONGIRL
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_TWINKLE_GAMEBOYKID:
objectDef OBJ_TYPE::WANDERING_NPC, 712, DIRECTIONS::RIGHT, 951
.addr SPRITEDEF_SMALLCAP_KID
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_TWINKLE_GAMEBOYKID
OBJ_DIALOGUE UMSG::TWINKLE_GAMEBOYKID
OBJ_YESNO_IS_NO @J_YESNO_IS_NO-OBJ_TWINKLE_GAMEBOYKID
	@J_YESNO_IS_NO:
OBJ_DIALOGUE UMSG::TWINKLE_GAMEBOYKID2
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_TWINKLE_SITUPSKID:
objectDef OBJ_TYPE::WANDERING_NPC, 710, DIRECTIONS::LEFT, 948
.addr SPRITEDEF_HEADBAND_KID_2
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_TWINKLE_SITUPSKID
OBJ_DIALOGUE UMSG::TWINKLE_SITUPSKID
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_TWINKLE_TOFUKID:
objectDef OBJ_TYPE::WANDERING_NPC, 707, DIRECTIONS::DOWN, 951
.addr SPRITEDEF_CAP_KID
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_TWINKLE_TOFUKID
OBJ_DIALOGUE UMSG::TWINKLE_TOFUKID
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_TWINKLE_BAFFLEDKID:
objectDef OBJ_TYPE::WANDERING_NPC, 742, DIRECTIONS::LEFT, 983
.addr SPRITEDEF_PIGTAIL_GIRL_2
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_TWINKLE_BAFFLEDKID
OBJ_DIALOGUE UMSG::TWINKLE_BAFFLEDKID
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_TWINKLE_HUNGRYKID:
objectDef OBJ_TYPE::WANDERING_NPC, 740, DIRECTIONS::DOWN, 983
.addr SPRITEDEF_HEADBAND_KID_2
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_TWINKLE_HUNGRYKID
OBJ_DIALOGUE UMSG::TWINKLE_HUNGRYKID
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_TWINKLE_DADGIRL:
objectDef OBJ_TYPE::WANDERING_NPC, 743, DIRECTIONS::RIGHT, 980
.addr SPRITEDEF_PONYTAIL_GIRL
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_TWINKLE_DADGIRL
OBJ_DIALOGUE UMSG::TWINKLE_DADGIRL
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_TWINKLE_LATEGIRL:
objectDef OBJ_TYPE::WANDERING_NPC, 710, DIRECTIONS::LEFT, 1012
.addr SPRITEDEF_PIGTAIL_GIRL_2
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_TWINKLE_LATEGIRL
OBJ_DIALOGUE UMSG::TWINKLE_LATEGIRL
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_TWINKLE_STRANGEGIRL:
objectDef OBJ_TYPE::WANDERING_NPC, 711, DIRECTIONS::RIGHT, 1015
.addr SPRITEDEF_PONYTAIL_GIRL
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_TWINKLE_STRANGEGIRL
OBJ_DIALOGUE UMSG::TWINKLE_STRANGEGIRL
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_TWINKLE_GAMEKID:
objectDef OBJ_TYPE::WANDERING_NPC, 715, DIRECTIONS::DOWN, 1015
.addr SPRITEDEF_CAP_KID
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_TWINKLE_GAMEKID
OBJ_DIALOGUE UMSG::TWINKLE_GAMEKID
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_TWINKLE_JANITOR:
objectDef OBJ_TYPE::STATIONARY_NPC, 791, DIRECTIONS::RIGHT, 965
.addr SPRITEDEF_JANITOR
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_TWINKLE_JANITOR
OBJ_IS_NOT_FLAG 60, @J_IS_NOT_FLAG-OBJ_TWINKLE_JANITOR
OBJ_DIALOGUE UMSG::TWINKLE_JANITOR_TEA
OBJ_STOP
	@J_IS_NOT_FLAG:
OBJ_DIALOGUE UMSG::TWINKLE_JANITOR1
OBJ_YESNO_IS_NO @J_YESNO_IS_NO-OBJ_TWINKLE_JANITOR
OBJ_DIALOGUE UMSG::TWINKLE_JANITOR2
OBJ_YESNO_IS_NO @J_YESNO_IS_NO1-OBJ_TWINKLE_JANITOR
OBJ_DIALOGUE UMSG::TWINKLE_JANITOR3
OBJ_YESNO_IS_NO @J_YESNO_IS_NO2-OBJ_TWINKLE_JANITOR
OBJ_DIALOGUE UMSG::TWINKLE_JANITOR_WIFE
OBJ_STOP
	@J_YESNO_IS_NO2:
OBJ_DIALOGUE UMSG::TWINKLE_JANITOR4
OBJ_YESNO_IS_NO @J_YESNO_IS_NO3-OBJ_TWINKLE_JANITOR
OBJ_DIALOGUE UMSG::TWINKLE_JANITOR5
OBJ_MOVE @MOVE_DATA
OBJ_SET_FLAG 35
OBJ_STOP
	@J_YESNO_IS_NO3:
OBJ_DIALOGUE UMSG::TWINKLE_JANTIORNOTEA
OBJ_STOP
	@J_YESNO_IS_NO1:
OBJ_DIALOGUE UMSG::TWINKLE_JANITORNOTHORRIBLE
OBJ_STOP
	@J_YESNO_IS_NO:
OBJ_DIALOGUE UMSG::TWINKLE_JANITOR_TEA
	@J_IS_NOT_TALKING:
OBJ_STOP

@MOVE_DATA:
moveDef DIRECTIONS::DOWN, 6, 1
moveDef DIRECTIONS::RIGHT, 6, 6
moveDef DIRECTIONS::RIGHT, 2, 1
moveDef DIRECTIONS::DOWN, 2, 1
OBJ_RETURN