OBJ_BANK_29:
.addr OBJ_ZOO_BUILDINGEXIT
.addr OBJ_ZOO_BUILDINGR1ENTRANCE
.addr OBJ_ZOO_BUILDINGR2ENTRANCE
.addr OBJ_ZOO_BUILDINGUPSTAIRS
.addr OBJ_ZOO_BUILDINGDOWNSTAIRS
.addr OBJ_ZOO_BUILDINGR3ENTRANCE
.addr OBJ_ZOO_BUILDINGR4NTRANCE
.addr OBJ_ZOO_BUILDINGUPSTAIRS2
.addr OBJ_ZOO_BUILDINGDOWNSTAIRS2
.addr OBJ_ZOO_BUILDINGR5ENTRANCE
.addr OBJ_ZOO_BUILDINGR6ENTRANCE
.addr OBJ_ZOO_BUILDINGR1EXIT
.addr OBJ_ZOO_BUILDINGR2EXIT
.addr OBJ_ZOO_BUILDINGR3EXIT
.addr OBJ_ZOO_BUILDINGR4EXIT
.addr OBJ_ZOO_BUILDINGR5EXIT
.addr OBJ_ZOO_BUILDINGR6EXIT
.addr OBJ_ZOO_PRESENT1
.addr OBJ_ZOO_PRESENT2
.addr OBJ_ZOO_PRESENT3
.addr OBJ_ZOO_PRESENT4
.addr OBJ_ZOO_STARMAN
.addr 0

OBJ_ZOO_BUILDINGEXIT:
objectDef 24, 494, DIRECTIONS::RIGHT, 134
OBJ_IS_NOT_FACING @J_IS_NOT_FACING-OBJ_ZOO_BUILDINGEXIT
OBJ_IS_NOT_TOUCHING @J_IS_NOT_FACING-OBJ_ZOO_BUILDINGEXIT
OBJ_IS_NOT_FLAG 13, @J_IS_NOT_FLAG-OBJ_ZOO_BUILDINGEXIT
OBJ_TELEPORT 0, 190, DIRECTIONS::DOWN, 244
OBJ_STOP
	@J_IS_NOT_FLAG:
OBJ_TELEPORT 17, 190, DIRECTIONS::DOWN, 244
	@J_IS_NOT_FACING:
OBJ_STOP

OBJ_ZOO_BUILDINGR1ENTRANCE:
objectDef OBJ_TYPE::DOOR, 486, DIRECTIONS::UP, 131
doorArgDef 0, 637, DIRECTIONS::LEFT, 150

OBJ_ZOO_BUILDINGR2ENTRANCE:
objectDef OBJ_TYPE::DOOR, 489, DIRECTIONS::UP, 131
doorArgDef 0, 765, DIRECTIONS::LEFT, 150

OBJ_ZOO_BUILDINGUPSTAIRS:
objectDef OBJ_TYPE::STAIRS, 482, DIRECTIONS::LEFT, 133
doorArgDef 0, 658, DIRECTIONS::RIGHT, 950

OBJ_ZOO_BUILDINGDOWNSTAIRS:
objectDef OBJ_TYPE::STAIRS, 657, DIRECTIONS::LEFT, 950
doorArgDef 0, 483, DIRECTIONS::RIGHT, 133

OBJ_ZOO_BUILDINGR3ENTRANCE:
objectDef OBJ_TYPE::DOOR, 662, DIRECTIONS::UP, 947
doorArgDef 0, 525, DIRECTIONS::LEFT, 134

OBJ_ZOO_BUILDINGR4NTRANCE:
objectDef OBJ_TYPE::DOOR, 665, DIRECTIONS::UP, 947
doorArgDef 0, 669, DIRECTIONS::LEFT, 150

OBJ_ZOO_BUILDINGUPSTAIRS2:
objectDef OBJ_TYPE::STAIRS, 658, DIRECTIONS::LEFT, 949
doorArgDef 0, 642, DIRECTIONS::RIGHT, 134

OBJ_ZOO_BUILDINGDOWNSTAIRS2:
objectDef OBJ_TYPE::STAIRS, 641, DIRECTIONS::LEFT, 134
doorArgDef 0, 659, DIRECTIONS::RIGHT, 949

OBJ_ZOO_BUILDINGR5ENTRANCE:
objectDef OBJ_TYPE::DOOR, 646, DIRECTIONS::UP, 131
doorArgDef 0, 797, DIRECTIONS::LEFT, 150

OBJ_ZOO_BUILDINGR6ENTRANCE:
objectDef OBJ_TYPE::DOOR, 649, DIRECTIONS::UP, 131
doorArgDef 0, 557, DIRECTIONS::LEFT, 134

OBJ_ZOO_BUILDINGR1EXIT:
objectDef OBJ_TYPE::DOOR, 638, DIRECTIONS::RIGHT, 150
doorArgDef 0, 486, DIRECTIONS::DOWN, 132

OBJ_ZOO_BUILDINGR2EXIT:
objectDef OBJ_TYPE::DOOR, 766, DIRECTIONS::RIGHT, 150
doorArgDef 0, 489, DIRECTIONS::DOWN, 132

OBJ_ZOO_BUILDINGR3EXIT:
objectDef OBJ_TYPE::DOOR, 526, DIRECTIONS::RIGHT, 134
doorArgDef 0, 662, DIRECTIONS::DOWN, 948

OBJ_ZOO_BUILDINGR4EXIT:
objectDef OBJ_TYPE::DOOR, 670, DIRECTIONS::RIGHT, 150
doorArgDef 0, 665, DIRECTIONS::DOWN, 948

OBJ_ZOO_BUILDINGR5EXIT:
objectDef OBJ_TYPE::DOOR, 798, DIRECTIONS::RIGHT, 150
doorArgDef 0, 646, DIRECTIONS::DOWN, 132

OBJ_ZOO_BUILDINGR6EXIT:
objectDef OBJ_TYPE::DOOR, 558, DIRECTIONS::RIGHT, 134
doorArgDef 0, 649, DIRECTIONS::DOWN, 132

OBJ_ZOO_PRESENT1:
objectDef OBJ_TYPE::PRESENT, 629, DIRECTIONS::UP, 150
.addr SPRITEDEF_PRESENT
.byte 67 ; item
.byte 25 ; flag

OBJ_ZOO_PRESENT2:
objectDef OBJ_TYPE::PRESENT, 756, DIRECTIONS::UP, 150
.addr SPRITEDEF_PRESENT
.byte 40 ; item
.byte 26 ; flag

OBJ_ZOO_PRESENT3:
objectDef OBJ_TYPE::PRESENT, 663, DIRECTIONS::UP, 150
.addr SPRITEDEF_PRESENT
.byte 71 ; item
.byte 27 ; flag

OBJ_ZOO_PRESENT4:
objectDef OBJ_TYPE::PRESENT, 554, DIRECTIONS::UP, 134
.addr SPRITEDEF_PRESENT
.byte 65 ; item
.byte 28 ; flag

OBJ_ZOO_STARMAN:
objectDef 33, 792, DIRECTIONS::UP, 150
.addr SPRITEDEF_PILL_BLUE
OBJ_FLAG_DISAPPEAR 13
OBJ_IS_NOT_CHECKING @J_IS_NOT_CHECKING-OBJ_ZOO_STARMAN
OBJ_DIALOGUE UMSG::ZOO_CAPSULE
OBJ_BATTLE 164
OBJ_PLAY_SOUND2 9
OBJ_MOVE @MOVE_DATA_1
OBJ_DIALOGUE UMSG::ZOO_WIN
OBJ_WRITE_SAVEMETA 28, 0
OBJ_WRITE_SAVEMETA 29, 0
OBJ_SET_FLAG 13
OBJ_PLAY_MUSIC 18
OBJ_MOVE @MOVE_DATA_2
	@J_IS_NOT_CHECKING:
OBJ_STOP

@MOVE_DATA_1:
moveDef DIRECTIONS::UP, MOVE_CMD::MOVEFACE, 6
moveDef DIRECTIONS::DOWN, $A, 1
OBJ_RETURN
@MOVE_DATA_2:
OBJ_STOP
