OBJ_BANK_28:
.addr OBJ_TWINKLE_F2_ROOM5EXIT
.addr OBJ_TWINKLE_F1_ROOM4EXIT
.addr OBJ_TWINKLE_F1_ROOM4BLOWNUPEXIT
.addr OBJ_TWINKLE_F1_ROOM5EXIT
.addr OBJ_ELLAY_FAKEHEALEREXIT
.addr OBJ_ELLAY_FAKEHEALERROOMENTRANCE
.addr OBJ_ELLAY_FAKEHEALERROOMEXIT
.addr OBJ_ELLAY_FAKEHEALERROOM2ENTRANCE
.addr OBJ_ELLAY_FAKEHEALERROOM2EXIT
.addr OBJ_YOUNGTOWN_BABYHOUSEEXIT
.addr OBJ_TWINKLE_SCIENTIST
.addr OBJ_TWINKLE_LABLLOYD
.addr OBJ_TWINKLE_NURSE
.addr OBJ_ELLAY_FAKEHEALER
.addr OBJ_ELLAY_FAKEHEALER_TEDDYBED
.addr OBJ_ELLAY_LLOYD_TEDDYBED
.addr OBJ_ELLAY_TEDDY_TEDDYBED
.addr OBJ_YOUNGTOWN_TOMGARRICKSON
.addr OBJ_YOUNGTOWN_MYSTICGIRL
.addr OBJ_YOUNGTOWN_BABY
.addr OBJ_TWINKLE_PRESENT1
.addr OBJ_TWINKLE_PRESENT2
.addr 0

OBJ_TWINKLE_F2_ROOM5EXIT:
objectDef OBJ_TYPE::DOOR, 622, DIRECTIONS::RIGHT, 950
doorArgDef 0, 782, DIRECTIONS::DOWN, 980

OBJ_TWINKLE_F1_ROOM4EXIT:
objectDef OBJ_TYPE::DOOR, 686, DIRECTIONS::RIGHT, 982
doorArgDef 0, 782, DIRECTIONS::DOWN, 952

OBJ_TWINKLE_F1_ROOM4BLOWNUPEXIT:
objectDef OBJ_TYPE::DOOR, 926, DIRECTIONS::RIGHT, 134
doorArgDef 0, 782, DIRECTIONS::DOWN, 952

OBJ_TWINKLE_F1_ROOM5EXIT:
objectDef OBJ_TYPE::DOOR, 654, DIRECTIONS::RIGHT, 1014
doorArgDef 0, 786, DIRECTIONS::DOWN, 952

OBJ_ELLAY_FAKEHEALEREXIT:
objectDef OBJ_TYPE::DOOR, 606, DIRECTIONS::RIGHT, 998
doorArgDef 6, 933, DIRECTIONS::DOWN, 376

OBJ_ELLAY_FAKEHEALERROOMENTRANCE:
objectDef 24, 593, DIRECTIONS::LEFT, 998
OBJ_IS_NOT_FACING @J_IS_NOT_FACING-OBJ_ELLAY_FAKEHEALERROOMENTRANCE
OBJ_IS_NOT_TOUCHING @J_IS_NOT_FACING-OBJ_ELLAY_FAKEHEALERROOMENTRANCE
OBJ_IS_NOT_FLAG 140, @J_IS_NOT_FLAG-OBJ_ELLAY_FAKEHEALERROOMENTRANCE
OBJ_TELEPORT 27, 765, DIRECTIONS::LEFT, 998
OBJ_STOP
	@J_IS_NOT_FLAG:
OBJ_TELEPORT 18, 765, DIRECTIONS::LEFT, 998
	@J_IS_NOT_FACING:
OBJ_STOP

OBJ_ELLAY_FAKEHEALERROOMEXIT:
objectDef OBJ_TYPE::DOOR, 766, DIRECTIONS::RIGHT, 998
doorArgDef 18, 594, DIRECTIONS::RIGHT, 998

OBJ_ELLAY_FAKEHEALERROOM2ENTRANCE:
objectDef OBJ_TYPE::DOOR, 758, DIRECTIONS::UP, 995
doorArgDef 18, 765, DIRECTIONS::LEFT, 966

OBJ_ELLAY_FAKEHEALERROOM2EXIT:
objectDef 24, 766, DIRECTIONS::RIGHT, 966
OBJ_IS_NOT_FACING @J_IS_NOT_FACING-OBJ_ELLAY_FAKEHEALERROOM2EXIT
OBJ_IS_NOT_TOUCHING @J_IS_NOT_FACING-OBJ_ELLAY_FAKEHEALERROOM2EXIT
OBJ_IS_NOT_FLAG 140, @J_IS_NOT_FLAG-OBJ_ELLAY_FAKEHEALERROOM2EXIT
OBJ_TELEPORT 27, 758, DIRECTIONS::DOWN, 996
OBJ_STOP
	@J_IS_NOT_FLAG:
OBJ_TELEPORT 18, 758, DIRECTIONS::DOWN, 996
	@J_IS_NOT_FACING:
OBJ_STOP

OBJ_YOUNGTOWN_BABYHOUSEEXIT:
objectDef OBJ_TYPE::DOOR, 862, DIRECTIONS::RIGHT, 134
doorArgDef 48, 674, DIRECTIONS::DOWN, 456

OBJ_TWINKLE_SCIENTIST:
objectDef OBJ_TYPE::STATIONARY_NPC_CHECKSPAWN, 678, DIRECTIONS::DOWN, 980
.addr SPRITEDEF_GLASSES_GUY
OBJ_FLAG_APPEAR 70
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_TWINKLE_SCIENTIST
OBJ_IS_NOT_FLAG 67, @J_IS_NOT_FLAG-OBJ_TWINKLE_SCIENTIST
OBJ_DIALOGUE UMSG::TWINKLE_SCIENTIST_NOPROGRESS
OBJ_YESNO_IS_NO @J_YESNO_IS_NO-OBJ_TWINKLE_SCIENTIST
OBJ_JUMP @J_JUMP-OBJ_TWINKLE_SCIENTIST
	@J_IS_NOT_FLAG:
OBJ_DIALOGUE UMSG::TWINKLE_SCIENTIST_INTRO
OBJ_YESNO_IS_NO @J_YESNO_IS_NO-OBJ_TWINKLE_SCIENTIST
OBJ_DIALOGUE UMSG::TWINKLE_SCIENTIST_AGREE
	@J_JUMP:
.ifndef VER_JP
OBJ_SET_FLAG 0
OBJ_NOT_HAS_ITEM 0, @J_NOT_HAS_ITEM-OBJ_TWINKLE_SCIENTIST
OBJ_CLEAR_FLAG 0
	@J_NOT_HAS_ITEM:
.endif
OBJ_SET_FLAG 67
.ifdef VER_JP
OBJ_DISPLAY_ITEMS 108, 167, 30, 166, @J_DISPLAY_ITEMS-OBJ_TWINKLE_SCIENTIST
.else
OBJ_DISPLAY_ITEMS 108, 36, 30, 166, @J_DISPLAY_ITEMS-OBJ_TWINKLE_SCIENTIST
OBJ_IS_NOT_FLAG 0, @J_IS_NOT_FLAG1-OBJ_TWINKLE_SCIENTIST
OBJ_DIALOGUE UMSG::YUCCA_PILOT_NOROOM
OBJ_DIALOGUE UMSG::TWINKLE_SCIENTIST_GOODBYE
OBJ_CLEAR_FLAG 0
OBJ_STOP
	@J_IS_NOT_FLAG1:
.endif
OBJ_TAKE_MONEY @J_TAKE_MONEY-OBJ_TWINKLE_SCIENTIST
.ifdef VER_JP
OBJ_IS_NOT_SELECTED 167, @J_IS_NOT_SELECTED-OBJ_TWINKLE_SCIENTIST
OBJ_DIALOGUE UMSG::TWINKLE_SCIENTISTROCKET1
OBJ_DIALOGUE UMSG::TWINKLE_SCIENTISTROCKET2
OBJ_TELEPORT 0, 917, DIRECTIONS::RIGHT, 134
OBJ_STOP
	@J_IS_NOT_SELECTED:
.endif
OBJ_IS_NOT_SELECTED 166, @J_IS_NOT_SELECTED1-OBJ_TWINKLE_SCIENTIST
OBJ_DIALOGUE UMSG::TWINKLE_SCIENTISTROCKET1
OBJ_DIALOGUE UMSG::TWINKLE_SCIENTISTROCKET2
OBJ_PLAY_SOUND2 9
OBJ_DIALOGUE UMSG::TWINKLE_SCIENTISTROCKET3
OBJ_STOP
	@J_IS_NOT_SELECTED1:
.ifdef VER_JP
OBJ_GIVE_ITEM @J_GIVE_ITEM-OBJ_TWINKLE_SCIENTIST
.else
OBJ_GIVE_ITEM @J_IS_NOT_TALKING-OBJ_TWINKLE_SCIENTIST
OBJ_PLAY_SOUND 6
.endif
OBJ_DIALOGUE UMSG::TWINKLE_SCIENTIST_GOODBYE
OBJ_STOP
	@J_GIVE_ITEM:
.ifdef VER_JP
OBJ_GIVE_MONEY @J_IS_NOT_TALKING-OBJ_TWINKLE_SCIENTIST
OBJ_DIALOGUE UMSG::YUCCA_PILOT_NOROOM
OBJ_DIALOGUE UMSG::TWINKLE_SCIENTIST_GOODBYE
OBJ_STOP
.endif
	@J_TAKE_MONEY:
OBJ_DIALOGUE UMSG::HEALER_BROKE
OBJ_DIALOGUE UMSG::TWINKLE_SCIENTIST_GOODBYE
.ifndef VER_JP
OBJ_CLEAR_FLAG 0
.endif
OBJ_STOP
	@J_DISPLAY_ITEMS:
OBJ_DIALOGUE UMSG::TWINKLE_SCIENTIST_GOODBYE
.ifndef VER_JP
OBJ_CLEAR_FLAG 0
.endif
OBJ_STOP
	@J_YESNO_IS_NO:
OBJ_DIALOGUE UMSG::TWINKLE_SCIENTIST_DECLINE
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_TWINKLE_LABLLOYD:
objectDef OBJ_TYPE::STATIONARY_NPC_CHECKSPAWN, 684, DIRECTIONS::RIGHT, 982
.addr SPRITEDEF_LLOYD
OBJ_FLAG_APPEAR 36
OBJ_IS_NOT_TOUCHING @J_IS_NOT_TOUCHING-OBJ_TWINKLE_LABLLOYD
OBJ_MOVE @MOVE_DATA_1
OBJ_DIALOGUE UMSG::TWINKLE_LABLLOYD
OBJ_MOVE @MOVE_DATA_2
OBJ_ADD_CHARACTER 3, @J_IS_NOT_TOUCHING-OBJ_TWINKLE_LABLLOYD
OBJ_SET_FLAG 118
OBJ_SET_FLAG 70
OBJ_CLEAR_FLAG 36
OBJ_TELEPORT 0, 917, DIRECTIONS::RIGHT, 134
OBJ_SET_FADE 3
	@J_IS_NOT_TOUCHING:
OBJ_STOP

@MOVE_DATA_1:
moveDef DIRECTIONS::LEFT, 7, 4
moveDef DIRECTIONS::LEFT, 6, 4
moveDef DIRECTIONS::DOWN, MOVE_CMD::ABOUTFACE, 1
OBJ_RETURN
@MOVE_DATA_2:
moveDef DIRECTIONS::DOWN, MOVE_CMD::ABOUTFACE, 1
moveDef DIRECTIONS::RIGHT, MOVE_CMD::MOVE, 2
moveDef DIRECTIONS::LEFT, MOVE_CMD::ABOUTFACE, 1
OBJ_STOP

OBJ_TWINKLE_NURSE:
objectDef OBJ_TYPE::WANDERING_NPC, 644, DIRECTIONS::RIGHT, 1012
.addr SPRITEDEF_NURSE
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_TWINKLE_NURSE
OBJ_DIALOGUE UMSG::TWINKLE_NURSE
OBJ_PLAY_SOUND 7
OBJ_PICK_CHARACTER_J 0, @J_IS_NOT_TALKING-OBJ_TWINKLE_NURSE
OBJ_HAS_STATUS %10000000, @J_HAS_STATUS-OBJ_TWINKLE_NURSE
OBJ_HEAL 80
	@J_HAS_STATUS:
OBJ_PICK_CHARACTER_J 1, @J_IS_NOT_TALKING-OBJ_TWINKLE_NURSE
OBJ_HAS_STATUS %10000000, @J_HAS_STATUS1-OBJ_TWINKLE_NURSE
OBJ_HEAL 80
	@J_HAS_STATUS1:
OBJ_PICK_CHARACTER_J 2, @J_IS_NOT_TALKING-OBJ_TWINKLE_NURSE
OBJ_HAS_STATUS %10000000, @J_IS_NOT_TALKING-OBJ_TWINKLE_NURSE
OBJ_HEAL 80
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_ELLAY_FAKEHEALER:
objectDef OBJ_TYPE::STATIONARY_NPC_CHECKSPAWN, 599, DIRECTIONS::DOWN, 996
.addr SPRITEDEF_GLASSES_GUY
OBJ_FLAG_DISAPPEAR 143
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_ELLAY_FAKEHEALER
OBJ_IS_NOT_FLAG 127, @J_IS_NOT_FLAG-OBJ_ELLAY_FAKEHEALER
OBJ_DIALOGUE UMSG::ELLAY_FAKEHEALER_ASK
OBJ_MENU UMSG::ELLAY_FAKEHEALER_MENU, @J_MENU-OBJ_ELLAY_FAKEHEALER, @J_MENU1-OBJ_ELLAY_FAKEHEALER
OBJ_DIALOGUE UMSG::ELLAY_FAKEHEALER_LIFEUP
OBJ_NOT_HAS_ITEM 0, @J_NOT_HAS_ITEM-OBJ_ELLAY_FAKEHEALER
OBJ_PICK_ITEM 65
OBJ_GIVE_ITEM @J_IS_NOT_TALKING-OBJ_ELLAY_FAKEHEALER
OBJ_PLAY_SOUND 6
OBJ_STOP
	@J_NOT_HAS_ITEM:
OBJ_DIALOGUE UMSG::ABBOTT_CANTHOLD
OBJ_STOP
	@J_MENU:
OBJ_DIALOGUE UMSG::ELLAY_FAKEHEALER_SLEEP
OBJ_SLEEP
	@J_MENU1:
OBJ_DIALOGUE UMSG::ELLAY_FAKEHEALER_GOODBYE
OBJ_STOP
	@J_IS_NOT_FLAG:
OBJ_DIALOGUE UMSG::ELLAY_FAKEHEALER
OBJ_SET_FLAG 127
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_ELLAY_FAKEHEALER_TEDDYBED:
objectDef OBJ_TYPE::STATIONARY_NPC_CHECKSPAWN, 756, DIRECTIONS::LEFT, 997
.addr SPRITEDEF_GLASSES_GUY
OBJ_FLAG_APPEAR 143
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_ELLAY_FAKEHEALER_TEDDYBED
OBJ_DIALOGUE UMSG::CANARY_GENERIC
OBJ_STOP
	@J_IS_NOT_TALKING:
OBJ_IS_SIGNAL @J_IS_SIGNAL-OBJ_ELLAY_FAKEHEALER_TEDDYBED
OBJ_HAS_MOVED @J_HAS_MOVED-OBJ_ELLAY_FAKEHEALER_TEDDYBED
OBJ_MOVE @MOVE_DATA_1
OBJ_DIALOGUE UMSG::ELLAY_FAKEHEALER_LLOYD
OBJ_SIGNAL 15
OBJ_MOVE @MOVE_DATA_2
OBJ_STOP
	@J_HAS_MOVED:
OBJ_CLEAR_FLAG 143
OBJ_MOVE @MOVE_DATA_3
	@J_IS_SIGNAL:
OBJ_STOP

@MOVE_DATA_1:
moveDef DIRECTIONS::RIGHT, MOVE_CMD::MOVEFACE, 4
OBJ_RETURN
@MOVE_DATA_2:
moveDef DIRECTIONS::LEFT, MOVE_CMD::ABOUTFACE, 1
OBJ_STOP
@MOVE_DATA_3:
moveDef DIRECTIONS::RIGHT, MOVE_CMD::MOVEFACE, 3
OBJ_STOP

OBJ_ELLAY_LLOYD_TEDDYBED:
objectDef OBJ_TYPE::STATIONARY_NPC_CHECKSPAWN, 761, DIRECTIONS::DOWN, 997
.addr SPRITEDEF_LLOYD
OBJ_FLAG_APPEAR 142
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_ELLAY_LLOYD_TEDDYBED
OBJ_DIALOGUE UMSG::CANARY_GENERIC
OBJ_STOP
	@J_IS_NOT_TALKING:
OBJ_IS_SIGNAL @J_IS_SIGNAL-OBJ_ELLAY_LLOYD_TEDDYBED
OBJ_MOVE @MOVE_DATA_1
OBJ_DIALOGUE UMSG::ELLAY_LLOYD_TEDDYBED
OBJ_MOVE @MOVE_DATA_2
;loop to transfer teddy items to lloyd
	@J_JUMP:
OBJ_PICK_CHARACTER 4
OBJ_PICK_CHARACTER_ITEM 0, @J_PICK_CHARACTER_ITEM-OBJ_ELLAY_LLOYD_TEDDYBED
OBJ_REMOVE_ITEM $2e ;unconditional
OBJ_IS_NOT_SELECTED 3, @ISNT_BREADCRUMBS-OBJ_ELLAY_LLOYD_TEDDYBED
OBJ_JUMP @J_JUMP-OBJ_ELLAY_LLOYD_TEDDYBED
	@ISNT_BREADCRUMBS:
OBJ_PICK_CHARACTER 3
OBJ_GIVE_ITEM @J_PICK_CHARACTER_ITEM-OBJ_ELLAY_LLOYD_TEDDYBED
OBJ_JUMP @J_JUMP-OBJ_ELLAY_LLOYD_TEDDYBED
	@J_PICK_CHARACTER_ITEM:
OBJ_PICK_CHARACTER 3
OBJ_AND_STATUS 0
	@J_NOT_MAX_HEALTH:
OBJ_HEAL 255
OBJ_NOT_MAX_HEALTH @J_NOT_MAX_HEALTH-OBJ_ELLAY_LLOYD_TEDDYBED
	@J_NOT_MAX_PP:
OBJ_PPHEAL 255
OBJ_NOT_MAX_PP @J_NOT_MAX_PP-OBJ_ELLAY_LLOYD_TEDDYBED
OBJ_PLAY_MUSIC 33
OBJ_DELAY 180
OBJ_PLAY_MUSIC 27
.ifdef VER_JP
OBJ_ADD_CHARACTER 3, $61 ;unconditional
.else
OBJ_ADD_CHARACTER 3, $62 ;unconditional
.endif
OBJ_CLEAR_FLAG 142
OBJ_SIGNAL 14
OBJ_MOVE @MOVE_DATA_3
	@J_IS_SIGNAL:
OBJ_STOP

@MOVE_DATA_1:
moveDef DIRECTIONS::DOWN_LEFT, MOVE_CMD::MOVEFACE, 1
moveDef DIRECTIONS::LEFT, MOVE_CMD::MOVEFACE, 3
moveDef DIRECTIONS::UP_LEFT, MOVE_CMD::MOVEFACE, 1
moveDef DIRECTIONS::DOWN, MOVE_CMD::ABOUTFACE, 1
OBJ_RETURN
@MOVE_DATA_2:
moveDef DIRECTIONS::DOWN, MOVE_CMD::MOVEFACE, 1
moveDef DIRECTIONS::LEFT, MOVE_CMD::MOVEFACE, 1
OBJ_RETURN
@MOVE_DATA_3:
OBJ_STOP

OBJ_ELLAY_TEDDY_TEDDYBED:
objectDef 29, 755, DIRECTIONS::UP, 997
.addr SPRITEDEF_TEDDY_LYING
OBJ_FLAG_APPEAR 200
OBJ_IS_NOT_CHECKING @J_IS_NOT_CHECKING-OBJ_ELLAY_TEDDY_TEDDYBED
OBJ_DIALOGUE UMSG::ELLAY_TEDDY_TEDDYBED
OBJ_STOP
	@J_IS_NOT_CHECKING:
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_ELLAY_TEDDY_TEDDYBED
OBJ_IS_NOT_FLAG 141, @J_IS_NOT_FLAG-OBJ_ELLAY_TEDDY_TEDDYBED
OBJ_DIALOGUE UMSG::CANARY_GENERIC
OBJ_STOP
	@J_IS_NOT_FLAG:
OBJ_DIALOGUE UMSG::ELLAY_TEDDY_TEDDYBED_SPEECH
OBJ_SET_FLAG 141
OBJ_SIGNAL 14
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_YOUNGTOWN_TOMGARRICKSON:
objectDef OBJ_TYPE::WANDERING_NPC, 855, DIRECTIONS::DOWN, 133
.addr SPRITEDEF_ABLE_BAKER
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_YOUNGTOWN_TOMGARRICKSON
OBJ_DIALOGUE UMSG::YOUNGTOWN_TOMGARRICKSON
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_YOUNGTOWN_MYSTICGIRL:
objectDef OBJ_TYPE::WANDERING_NPC, 857, DIRECTIONS::DOWN, 135
.addr SPRITEDEF_ANA_NOHAT
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_YOUNGTOWN_MYSTICGIRL
OBJ_DIALOGUE UMSG::YOUNGTOWN_MYSTICGIRL
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_YOUNGTOWN_BABY:
objectDef 25, 851, DIRECTIONS::UP, 133
.addr SPRITEDEF_BABY
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_YOUNGTOWN_BABY
OBJ_DIALOGUE UMSG::YOUNGTOWN_BABYTALK
OBJ_STOP
	@J_IS_NOT_TALKING:
OBJ_IS_NOT_CASTING 1, @J_IS_NOT_CASTING-OBJ_YOUNGTOWN_BABY
OBJ_IS_NOT_FLAG 148, @J_IS_NOT_FLAG-OBJ_YOUNGTOWN_BABY
OBJ_DIALOGUE UMSG::YOUNGTOWN_BABY_AFTER
OBJ_STOP
	@J_IS_NOT_FLAG:
OBJ_DIALOGUE UMSG::YOUNGTOWN_BABY
OBJ_TEACH_TELEPORT
OBJ_SET_FLAG 238
OBJ_PLAY_MUSIC 33
OBJ_DELAY 180
OBJ_SET_FLAG 148
OBJ_PLAY_MUSIC 48
	@J_IS_NOT_CASTING:
OBJ_STOP

OBJ_TWINKLE_PRESENT1:
objectDef OBJ_TYPE::PRESENT, 615, DIRECTIONS::UP, 948
.addr SPRITEDEF_PRESENT
.byte 23 ; item
.byte 50 ; flag

OBJ_TWINKLE_PRESENT2:
objectDef OBJ_TYPE::PRESENT, 619, DIRECTIONS::UP, 951
.addr SPRITEDEF_PRESENT
.byte 16 ; item
.byte 51 ; flag