OBJ_BANK_25:
.addr OBJ_TWINKLE_F2_ROOM4EXIT
.addr OBJ_SPOOKANE_SNOWMAN_TUNNELLEFTEXIT
.addr OBJ_SPOOKANE_SNOWMAN_TUNNELRIGHTEXIT
.ifdef VER_JP
.addr OBJTHING_25_3
.addr OBJTHING_25_4
.endif
.addr OBJ_ISLAND_ENTRANCE
.addr OBJ_ELLAY_TOWERTOPELEVATOR
.addr OBJ_TWINKLE_PIANOLEFT
.addr OBJ_TWINKLE_PIANORIGHT
.addr OBJ_ELLAY_TOWER_TELESCOPEUNUSED
.addr OBJ_ELLAY_TOWER_TELESCOPE
.addr OBJ_ELLAY_TOWER_ROCKETTELESCOPE
.addr OBJ_ELLAY_TOWER_ROCKET1
.addr OBJ_ELLAY_TOWER_ROCKET2
.addr OBJ_ELLAY_TOWER_ROCKETFLAME
.addr OBJ_ELLAY_TOWER_ROCKET
.addr OBJ_ELLAY_TOWER_ROCKETFLAME_TOISLAND
.addr OBJ_ELLAY_ISLAND_ROCKET
.addr OBJ_ELLAY_ISLAND_ROCKETFLAME
.addr OBJ_GAMEOVER
.addr 0

OBJ_TWINKLE_F2_ROOM4EXIT:
objectDef OBJ_TYPE::DOOR, 894, DIRECTIONS::RIGHT, 150
doorArgDef 0, 778, DIRECTIONS::DOWN, 980

OBJ_SPOOKANE_SNOWMAN_TUNNELLEFTEXIT:
objectDef OBJ_TYPE::DOOR, 8, DIRECTIONS::LEFT, 522
doorArgDef 6, 721, DIRECTIONS::LEFT, 831

OBJ_SPOOKANE_SNOWMAN_TUNNELRIGHTEXIT:
objectDef OBJ_TYPE::DOOR, 119, DIRECTIONS::RIGHT, 522
doorArgDef 10, 834, DIRECTIONS::DOWN, 968

.ifdef VER_JP
OBJTHING_25_3:
objectDef OBJ_TYPE::DOOR, 8, DIRECTIONS::LEFT, 1018
doorArgDef 6, 433, DIRECTIONS::LEFT, 463

OBJTHING_25_4:
objectDef OBJ_TYPE::DOOR, 359, DIRECTIONS::RIGHT, 1018
doorArgDef 6, 434, DIRECTIONS::DOWN, 740
.endif

OBJ_ISLAND_ENTRANCE:
objectDef OBJ_TYPE::DOOR, 977, DIRECTIONS::UP, 475
doorArgDef 15, 1005, DIRECTIONS::LEFT, 134

OBJ_ELLAY_TOWERTOPELEVATOR:
objectDef OBJ_TYPE::DOOR, 59, DIRECTIONS::UP, 363
doorArgDef 0, 40, DIRECTIONS::DOWN, 212

OBJ_TWINKLE_PIANOLEFT:
objectDef 25, 884, DIRECTIONS::UP, 148
.addr SPRITEDEF_PIANOLEFT
OBJ_STOP

OBJ_TWINKLE_PIANORIGHT:
objectDef 25, 885, DIRECTIONS::UP, 148
.addr SPRITEDEF_PIANORIGHT
OBJ_STOP

;unused by proxy of being oob.
;and technically no image. but thats because
;all of the telescopes have no image
OBJ_ELLAY_TOWER_TELESCOPEUNUSED:
objectDef 24, 25, DIRECTIONS::UP, 362
OBJ_IS_NOT_CHECKING @J_IS_NOT_CHECKING-OBJ_ELLAY_TOWER_TELESCOPEUNUSED
OBJ_DIALOGUE UMSG::ELLAY_TOWER_TELESCOPE
OBJ_DIALOGUE UMSG::ELLAY_TOWER_TELESCOPE2
	@J_IS_NOT_CHECKING:
OBJ_STOP

OBJ_ELLAY_TOWER_TELESCOPE:
objectDef 24, 49, DIRECTIONS::UP, 362
OBJ_IS_NOT_CHECKING @J_IS_NOT_CHECKING-OBJ_ELLAY_TOWER_TELESCOPE
OBJ_DIALOGUE UMSG::ELLAY_TOWER_TELESCOPE
OBJ_DIALOGUE UMSG::ELLAY_TOWER_TELESCOPE2
	@J_IS_NOT_CHECKING:
OBJ_STOP

OBJ_ELLAY_TOWER_ROCKETTELESCOPE:
objectDef 24, 37, DIRECTIONS::UP, 362
OBJ_IS_NOT_CHECKING @J_IS_NOT_CHECKING-OBJ_ELLAY_TOWER_ROCKETTELESCOPE
OBJ_IS_NOT_FLAG 121, @J_IS_NOT_FLAG-OBJ_ELLAY_TOWER_ROCKETTELESCOPE
OBJ_DIALOGUE UMSG::ELLAY_TOWER_TELESCOPE
OBJ_DIALOGUE UMSG::ELLAY_TOWER_TELESCOPE2
OBJ_STOP
	@J_IS_NOT_FLAG:
OBJ_DIALOGUE UMSG::ELLAY_TOWER_TELESCOPE
OBJ_DIALOGUE UMSG::ELLAY_TOWER_TELESCOPE_ROCKET
.ifdef VER_JP
OBJ_SIGNAL 12
.else
OBJ_SIGNAL 10
.endif
	@J_IS_NOT_CHECKING:
OBJ_STOP

OBJ_ELLAY_TOWER_ROCKET1:
objectDef 29, 41, DIRECTIONS::UP, 358
.addr SPRITEDEF_ISLAND_ROCKET_SMALL
OBJ_FLAG_APPEAR 1
OBJ_IS_SIGNAL @J_IS_SIGNAL-OBJ_ELLAY_TOWER_ROCKET1
OBJ_MOVE @MOVE_DATA
OBJ_DELAY 90
.ifdef VER_JP
OBJ_SIGNAL 13
.else
OBJ_SIGNAL 11
.endif
	@J_IS_SIGNAL:
OBJ_STOP

@MOVE_DATA:
moveDef DIRECTIONS::UP, MOVE_CMD::ABOUTFACE, 1
moveDef DIRECTIONS::UP, MOVE_CMD::MOVE, 2
OBJ_STOP

OBJ_ELLAY_TOWER_ROCKET2:
objectDef 29, 41, DIRECTIONS::UP, 356
.addr SPRITEDEF_ISLAND_ROCKET
OBJ_FLAG_APPEAR 1
OBJ_IS_SIGNAL @J_IS_SIGNAL-OBJ_ELLAY_TOWER_ROCKET2
.ifdef VER_JP
OBJ_SIGNAL 14
.else
OBJ_SIGNAL 12
.endif
OBJ_PLAY_SOUND2 9
OBJ_MOVE @MOVE_DATA
	@J_IS_SIGNAL:
OBJ_STOP

@MOVE_DATA:
moveDef DIRECTIONS::DOWN, MOVE_CMD::MOVE, 8
OBJ_STOP

OBJ_ELLAY_TOWER_ROCKETFLAME:
objectDef 29, 41, DIRECTIONS::UP, 356
.addr SPRITEDEF_ISLAND_ROCKET_FLAME
OBJ_FLAG_APPEAR 1
OBJ_IS_SIGNAL @J_IS_SIGNAL-OBJ_ELLAY_TOWER_ROCKETFLAME
OBJ_MOVE @MOVE_DATA_1
OBJ_SET_FLAG 121
OBJ_MOVE @MOVE_DATA_2
	@J_IS_SIGNAL:
OBJ_STOP

@MOVE_DATA_1:
moveDef DIRECTIONS::DOWN, MOVE_CMD::MOVE, 8
OBJ_RETURN
@MOVE_DATA_2:
moveDef DIRECTIONS::UP, MOVE_CMD::ABOUTFACE, 1
OBJ_STOP

OBJ_ELLAY_TOWER_ROCKET:
objectDef 45, 41, DIRECTIONS::UP, 364
.addr SPRITEDEF_ISLAND_ROCKET
OBJ_FLAG_APPEAR 121
OBJ_IS_NOT_CHECKING @J_IS_NOT_CHECKING-OBJ_ELLAY_TOWER_ROCKET
OBJ_DIALOGUE UMSG::ELLAY_TOWER_ROCKETCHECK
OBJ_STOP
	@J_IS_NOT_CHECKING:
OBJ_IS_NOT_TOUCHING @J_IS_NOT_TOUCHING-OBJ_ELLAY_TOWER_ROCKET
OBJ_DIALOGUE UMSG::ELLAY_TOWER_ROCKET
OBJ_ROCKET 0
.ifdef VER_JP
OBJ_SIGNAL 16
.else
OBJ_SIGNAL 14
.endif
OBJ_PLAY_SOUND2 9
OBJ_MOVE @MOVE_DATA
	@J_IS_NOT_TOUCHING:
OBJ_STOP

@MOVE_DATA:
moveDef DIRECTIONS::UP, MOVE_CMD::MOVE, 7
OBJ_STOP

OBJ_ELLAY_TOWER_ROCKETFLAME_TOISLAND:
objectDef 29, 41, DIRECTIONS::UP, 364
.addr SPRITEDEF_ISLAND_ROCKET_FLAME
OBJ_FLAG_APPEAR 1
OBJ_IS_SIGNAL @J_IS_SIGNAL-OBJ_ELLAY_TOWER_ROCKETFLAME_TOISLAND
OBJ_MOVE @MOVE_DATA_1
OBJ_EXIT_VEHICLE 0
OBJ_TELEPORT 6, 976, DIRECTIONS::DOWN, 479
OBJ_MOVE @MOVE_DATA_2
	@J_IS_SIGNAL:
OBJ_STOP

@MOVE_DATA_1:
moveDef DIRECTIONS::UP, MOVE_CMD::MOVE, 7
OBJ_RETURN
@MOVE_DATA_2:
OBJ_STOP

OBJ_ELLAY_ISLAND_ROCKET:
objectDef 45, 976, DIRECTIONS::UP, 479
.addr SPRITEDEF_ISLAND_ROCKET
OBJ_FLAG_APPEAR 121
OBJ_IS_NOT_CHECKING @J_IS_NOT_CHECKING-OBJ_ELLAY_ISLAND_ROCKET
OBJ_DIALOGUE UMSG::ELLAY_TOWER_ROCKETCHECK
OBJ_STOP
	@J_IS_NOT_CHECKING:
OBJ_IS_NOT_TOUCHING @J_IS_NOT_TOUCHING-OBJ_ELLAY_ISLAND_ROCKET
OBJ_DIALOGUE UMSG::ELLAY_TOWER_ROCKET
OBJ_ROCKET 0
.ifdef VER_JP
OBJ_SIGNAL 18
.else
OBJ_SIGNAL 16
.endif
OBJ_PLAY_SOUND2 9
OBJ_MOVE @MOVE_DATA
	@J_IS_NOT_TOUCHING:
OBJ_STOP

@MOVE_DATA:
moveDef DIRECTIONS::UP, MOVE_CMD::MOVE, 7
OBJ_STOP

OBJ_ELLAY_ISLAND_ROCKETFLAME:
objectDef 29, 976, DIRECTIONS::UP, 479
.addr SPRITEDEF_ISLAND_ROCKET_FLAME
OBJ_FLAG_APPEAR 1
OBJ_IS_SIGNAL @J_IS_SIGNAL-OBJ_ELLAY_ISLAND_ROCKETFLAME
OBJ_MOVE @MOVE_DATA_1
OBJ_EXIT_VEHICLE 0
OBJ_TELEPORT 15, 41, DIRECTIONS::DOWN, 364
OBJ_MOVE @MOVE_DATA_2
	@J_IS_SIGNAL:
OBJ_STOP

@MOVE_DATA_1:
moveDef DIRECTIONS::UP, MOVE_CMD::MOVE, 7
OBJ_RETURN
@MOVE_DATA_2:
OBJ_STOP

OBJ_GAMEOVER:
objectDef 24, 901, DIRECTIONS::UP, 150
OBJ_IS_NOT_TOUCHING @J_IS_NOT_TOUCHING-OBJ_GAMEOVER
OBJ_IS_NOT_FLAG 192, @J_IS_NOT_FLAG-OBJ_GAMEOVER
OBJ_CLEAR_FLAG 192
OBJ_CLEAR_FLAG 254
OBJ_SET_FLAG 193
OBJ_SET_FLAG 147
	@J_IS_NOT_FLAG:
OBJ_DIALOGUE UMSG::GAMEOVER1
OBJ_MENU UMSG::MENU_CONTINUE_REST, @J_MENU-OBJ_GAMEOVER, @J_MENU-OBJ_GAMEOVER
OBJ_JUMP @J_JUMP-OBJ_GAMEOVER
	@J_MENU:
OBJ_DIALOGUE UMSG::GAMEOVER_SAVEDATA
OBJ_YESNO_IS_NO @J_JUMP-OBJ_GAMEOVER
OBJ_DIALOGUE UMSG::GAMEOVER_DREAM
OBJ_RESET
	@J_JUMP:
OBJ_DIALOGUE UMSG::GAMEOVER2
OBJ_TELEPORT_TO_SAVEGAME
	@J_IS_NOT_TOUCHING:
OBJ_STOP

