OBJ_BANK_20:
.addr OBJ_MERRYSVILLE_DEPTDOWNSTAIRS2
.addr OBJ_MERRYSVILLE_DEPTUPSTAIRS3
.addr OBJ_MERRYSVILLE_DEPTDOWNSTAIRS3
.addr OBJ_MERRYSVILLE_DEPTUPSTAIRS4
.addr OBJ_REINDEER_DEPTDOWNSTAIRS2
.addr OBJ_REINDEER_DEPTUPSTAIRS3
.addr OBJ_REINDEER_DEPTDOWNSTAIRS3
.addr OBJ_ELLAY_DEPTDOWNSTAIRS4
.ifndef VER_JP
.addr OBJ_REINDEER_DEPTUPSTAIRS4
.addr OBJ_REINDEER_DEPTDOWNSTAIRS4
.endif
.addr OBJ_YOUNGTOWN_FAKEDEPTEXIT
.addr OBJ_YOUNGTOWN_FAKEDEPTVENDOR
.addr OBJ_MERRYSVILLE_SPORTSVENDOR
.addr OBJ_MERRYSVILLE_FOODSVENDOR
.addr OBJ_REINDEER_SPORTSVENDOR
.addr OBJ_REINDEER_FOODSVENDOR
.addr OBJ_REINDEER_FOODSWOMAN
.addr OBJ_ELLAY_VARIETYVENDOR
.addr OBJ_YOUNGTOWN_ATM
.addr OBJ_YOUNGTOWN_PAYPHONE
.ifndef VER_JP
.addr OBJ_REINDEER_WEAPONVENDOR
.endif
.addr 0

OBJ_MERRYSVILLE_DEPTDOWNSTAIRS2:
objectDef OBJ_TYPE::STAIRS, 2, DIRECTIONS::LEFT, 309
doorArgDef 0, 674, DIRECTIONS::RIGHT, 150

OBJ_MERRYSVILLE_DEPTUPSTAIRS3:
objectDef OBJ_TYPE::STAIRS, 1, DIRECTIONS::LEFT, 310
doorArgDef 0, 3, DIRECTIONS::RIGHT, 149

OBJ_MERRYSVILLE_DEPTDOWNSTAIRS3:
objectDef OBJ_TYPE::STAIRS, 2, DIRECTIONS::LEFT, 149
doorArgDef 0, 2, DIRECTIONS::RIGHT, 310

OBJ_MERRYSVILLE_DEPTUPSTAIRS4:
objectDef OBJ_TYPE::STAIRS, 1, DIRECTIONS::LEFT, 150
doorArgDef 0, 3, DIRECTIONS::RIGHT, 213


OBJ_REINDEER_DEPTDOWNSTAIRS2:
objectDef OBJ_TYPE::STAIRS, 34, DIRECTIONS::LEFT, 149
doorArgDef 0, 34, DIRECTIONS::RIGHT, 310

OBJ_REINDEER_DEPTUPSTAIRS3:
objectDef OBJ_TYPE::STAIRS, 33, DIRECTIONS::LEFT, 150
doorArgDef 0, 707, DIRECTIONS::RIGHT, 149

OBJ_REINDEER_DEPTDOWNSTAIRS3:
objectDef OBJ_TYPE::STAIRS, 706, DIRECTIONS::LEFT, 149
doorArgDef 0, 34, DIRECTIONS::RIGHT, 150

OBJ_ELLAY_DEPTDOWNSTAIRS4:
objectDef OBJ_TYPE::STAIRS, 738, DIRECTIONS::LEFT, 997
doorArgDef 0, 770, DIRECTIONS::RIGHT, 150

.ifndef VER_JP
OBJ_REINDEER_DEPTUPSTAIRS4:
objectDef OBJ_TYPE::STAIRS, 705, DIRECTIONS::LEFT, 150
doorArgDef 0, 3, DIRECTIONS::RIGHT, 437

OBJ_REINDEER_DEPTDOWNSTAIRS4:
objectDef OBJ_TYPE::STAIRS, 2, DIRECTIONS::LEFT, 437
doorArgDef 0, 706, DIRECTIONS::RIGHT, 150
.endif

OBJ_YOUNGTOWN_FAKEDEPTEXIT:
objectDef OBJ_TYPE::DOOR, 46, DIRECTIONS::RIGHT, 278
doorArgDef 48, 717, DIRECTIONS::DOWN, 448

OBJ_YOUNGTOWN_FAKEDEPTVENDOR:
objectDef OBJ_TYPE::WANDERING_NPC, 40, DIRECTIONS::DOWN, 276
.addr SPRITEDEF_COOL_GUY
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_YOUNGTOWN_FAKEDEPTVENDOR
.ifndef VER_JP
OBJ_DIALOGUE UMSG::DRUGSVENDOR_WELCOME
	@J_JUMP:
.endif
OBJ_SET_FLAG 0
OBJ_NOT_HAS_ITEM 0, @J_NOT_HAS_ITEM-OBJ_YOUNGTOWN_FAKEDEPTVENDOR
OBJ_CLEAR_FLAG 0
	@J_NOT_HAS_ITEM:
.ifdef VER_JP
OBJ_DIALOGUE UMSG::DRUGSVENDOR_WELCOME
.endif
OBJ_DISPLAY_ITEMS 71, 65, 21, 15, @J_DISPLAY_ITEMS-OBJ_YOUNGTOWN_FAKEDEPTVENDOR
OBJ_IS_NOT_FLAG 0, @J_IS_NOT_FLAG-OBJ_YOUNGTOWN_FAKEDEPTVENDOR
OBJ_DIALOGUE UMSG::DRUGSVENDOR_NOMORE
OBJ_CLEAR_FLAG 0
OBJ_STOP
	@J_IS_NOT_FLAG:
OBJ_TAKE_MONEY @J_TAKE_MONEY-OBJ_YOUNGTOWN_FAKEDEPTVENDOR
OBJ_DIALOGUE UMSG::SHOP_CONFIRM
OBJ_YESNO_IS_NO @J_YESNO_IS_NO-OBJ_YOUNGTOWN_FAKEDEPTVENDOR
OBJ_DIALOGUE UMSG::BURGERSHOP_GOODBYE
OBJ_PLAY_SOUND 11
OBJ_SHOW_MONEY
OBJ_GIVE_ITEM @J_IS_NOT_TALKING-OBJ_YOUNGTOWN_FAKEDEPTVENDOR
.ifndef VER_JP
OBJ_DIALOGUE UMSG::BURGERSHOP_ANYMORE
OBJ_YESNO_IS_NO @J_YESNO_IS_NO1-OBJ_YOUNGTOWN_FAKEDEPTVENDOR
OBJ_JUMP @J_JUMP-OBJ_YOUNGTOWN_FAKEDEPTVENDOR
	@J_YESNO_IS_NO1:
OBJ_DIALOGUE UMSG::BURGERSHOP_GOODBYE
.endif
OBJ_STOP
	@J_YESNO_IS_NO:
OBJ_GIVE_MONEY @J_IS_NOT_TALKING-OBJ_YOUNGTOWN_FAKEDEPTVENDOR
	@J_DISPLAY_ITEMS:
OBJ_DIALOGUE UMSG::MISLAY_MOUTHWASHKID_NOTAKE
OBJ_CLEAR_FLAG 0
OBJ_STOP
	@J_TAKE_MONEY:
OBJ_DIALOGUE UMSG::HOSPITAL_NURSE_NOMONEY
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_MERRYSVILLE_SPORTSVENDOR:
objectDef OBJ_TYPE::WANDERING_NPC, 8, DIRECTIONS::DOWN, 308
.addr SPRITEDEF_SUIT_GIRL
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_MERRYSVILLE_SPORTSVENDOR
.ifndef VER_JP
OBJ_DIALOGUE UMSG::DRUGSVENDOR_WELCOME
	@J_JUMP:
.endif
OBJ_SET_FLAG 0
OBJ_NOT_HAS_ITEM 0, @J_NOT_HAS_ITEM-OBJ_MERRYSVILLE_SPORTSVENDOR
OBJ_CLEAR_FLAG 0
	@J_NOT_HAS_ITEM:
.ifdef VER_JP
OBJ_DIALOGUE UMSG::DRUGSVENDOR_WELCOME
.endif
OBJ_DISPLAY_ITEMS 17, 18, 24, 0, @J_DISPLAY_ITEMS-OBJ_MERRYSVILLE_SPORTSVENDOR
OBJ_IS_NOT_FLAG 0, @J_IS_NOT_FLAG-OBJ_MERRYSVILLE_SPORTSVENDOR
OBJ_DIALOGUE UMSG::BURGERSHOP_NO_ROOM
OBJ_CLEAR_FLAG 0
OBJ_STOP
	@J_IS_NOT_FLAG:
OBJ_TAKE_MONEY @J_TAKE_MONEY-OBJ_MERRYSVILLE_SPORTSVENDOR
OBJ_DIALOGUE UMSG::SHOP_CONFIRM
OBJ_YESNO_IS_NO @J_YESNO_IS_NO-OBJ_MERRYSVILLE_SPORTSVENDOR
OBJ_DIALOGUE UMSG::BURGERSHOP_GOODBYE
OBJ_PLAY_SOUND 11
OBJ_SHOW_MONEY
OBJ_GIVE_ITEM @J_IS_NOT_TALKING-OBJ_MERRYSVILLE_SPORTSVENDOR
.ifndef VER_JP
OBJ_DIALOGUE UMSG::BURGERSHOP_ANYMORE
OBJ_YESNO_IS_NO @J_YESNO_IS_NO1-OBJ_MERRYSVILLE_SPORTSVENDOR
OBJ_JUMP @J_JUMP-OBJ_MERRYSVILLE_SPORTSVENDOR
	@J_YESNO_IS_NO1:
OBJ_DIALOGUE UMSG::BURGERSHOP_GOODBYE
.endif
OBJ_STOP
	@J_YESNO_IS_NO:
OBJ_GIVE_MONEY @J_IS_NOT_TALKING-OBJ_MERRYSVILLE_SPORTSVENDOR
	@J_DISPLAY_ITEMS:
OBJ_DIALOGUE UMSG::BURGERSHOP_NO_BUY
OBJ_CLEAR_FLAG 0
OBJ_STOP
	@J_TAKE_MONEY:
OBJ_DIALOGUE UMSG::BURGERSHOP_NOMONEY
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_MERRYSVILLE_FOODSVENDOR:
objectDef OBJ_TYPE::WANDERING_NPC, 8, DIRECTIONS::DOWN, 148
.addr SPRITEDEF_SUIT_GUY
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_MERRYSVILLE_FOODSVENDOR
.ifndef VER_JP
OBJ_DIALOGUE UMSG::DRUGSVENDOR_WELCOME
	@J_JUMP:
.endif
OBJ_SET_FLAG 0
OBJ_NOT_HAS_ITEM 0, @J_NOT_HAS_ITEM-OBJ_MERRYSVILLE_FOODSVENDOR
OBJ_CLEAR_FLAG 0
	@J_NOT_HAS_ITEM:
.ifdef VER_JP
OBJ_DIALOGUE UMSG::DRUGSVENDOR_WELCOME
.endif
OBJ_DISPLAY_ITEMS 60, 71, 64, 0, @J_DISPLAY_ITEMS-OBJ_MERRYSVILLE_FOODSVENDOR
OBJ_IS_NOT_FLAG 0, @J_IS_NOT_FLAG-OBJ_MERRYSVILLE_FOODSVENDOR
OBJ_DIALOGUE UMSG::DRUGSVENDOR_NOMORE
OBJ_CLEAR_FLAG 0
OBJ_STOP
	@J_IS_NOT_FLAG:
OBJ_TAKE_MONEY @J_TAKE_MONEY-OBJ_MERRYSVILLE_FOODSVENDOR
OBJ_DIALOGUE UMSG::SHOP_CONFIRM
OBJ_YESNO_IS_NO @J_YESNO_IS_NO-OBJ_MERRYSVILLE_FOODSVENDOR
OBJ_DIALOGUE UMSG::BURGERSHOP_GOODBYE
OBJ_PLAY_SOUND 11
OBJ_SHOW_MONEY
OBJ_GIVE_ITEM @J_IS_NOT_TALKING-OBJ_MERRYSVILLE_FOODSVENDOR
.ifndef VER_JP
OBJ_DIALOGUE UMSG::BURGERSHOP_ANYMORE
OBJ_YESNO_IS_NO @J_YESNO_IS_NO1-OBJ_MERRYSVILLE_FOODSVENDOR
OBJ_JUMP @J_JUMP-OBJ_MERRYSVILLE_FOODSVENDOR
	@J_YESNO_IS_NO1:
OBJ_DIALOGUE UMSG::BURGERSHOP_GOODBYE
.endif
OBJ_STOP
	@J_YESNO_IS_NO:
OBJ_GIVE_MONEY @J_IS_NOT_TALKING-OBJ_MERRYSVILLE_FOODSVENDOR
	@J_DISPLAY_ITEMS:
OBJ_DIALOGUE UMSG::MISLAY_MOUTHWASHKID_NOTAKE
OBJ_CLEAR_FLAG 0
OBJ_STOP
	@J_TAKE_MONEY:
OBJ_DIALOGUE UMSG::HOSPITAL_NURSE_NOMONEY
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_REINDEER_SPORTSVENDOR:
objectDef OBJ_TYPE::WANDERING_NPC, 40, DIRECTIONS::DOWN, 148
.addr SPRITEDEF_SUIT_GIRL
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_REINDEER_SPORTSVENDOR
.ifndef VER_JP
OBJ_DIALOGUE UMSG::DRUGSVENDOR_WELCOME
	@J_JUMP:
.endif
OBJ_SET_FLAG 0
OBJ_NOT_HAS_ITEM 0, @J_NOT_HAS_ITEM-OBJ_REINDEER_SPORTSVENDOR
OBJ_CLEAR_FLAG 0
	@J_NOT_HAS_ITEM:
.ifdef VER_JP
OBJ_DIALOGUE UMSG::DRUGSVENDOR_WELCOME
.endif
OBJ_DISPLAY_ITEMS 18, 24, 0, 0, @J_DISPLAY_ITEMS-OBJ_REINDEER_SPORTSVENDOR
OBJ_IS_NOT_FLAG 0, @J_IS_NOT_FLAG-OBJ_REINDEER_SPORTSVENDOR
OBJ_DIALOGUE UMSG::BURGERSHOP_NO_ROOM
OBJ_CLEAR_FLAG 0
OBJ_STOP
	@J_IS_NOT_FLAG:
OBJ_TAKE_MONEY @J_TAKE_MONEY-OBJ_REINDEER_SPORTSVENDOR
OBJ_DIALOGUE UMSG::SHOP_CONFIRM
OBJ_YESNO_IS_NO @J_YESNO_IS_NO-OBJ_REINDEER_SPORTSVENDOR
OBJ_DIALOGUE UMSG::BURGERSHOP_GOODBYE
OBJ_PLAY_SOUND 11
OBJ_SHOW_MONEY
OBJ_GIVE_ITEM @J_IS_NOT_TALKING-OBJ_REINDEER_SPORTSVENDOR
.ifndef VER_JP
OBJ_DIALOGUE UMSG::BURGERSHOP_ANYMORE
OBJ_YESNO_IS_NO @J_YESNO_IS_NO1-OBJ_REINDEER_SPORTSVENDOR
OBJ_JUMP @J_JUMP-OBJ_REINDEER_SPORTSVENDOR
	@J_YESNO_IS_NO1:
OBJ_DIALOGUE UMSG::BURGERSHOP_GOODBYE
.endif
OBJ_STOP
	@J_YESNO_IS_NO:
OBJ_GIVE_MONEY @J_IS_NOT_TALKING-OBJ_REINDEER_SPORTSVENDOR
	@J_DISPLAY_ITEMS:
OBJ_DIALOGUE UMSG::BURGERSHOP_NO_BUY
OBJ_CLEAR_FLAG 0
OBJ_STOP
	@J_TAKE_MONEY:
OBJ_DIALOGUE UMSG::BURGERSHOP_NOMONEY
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_REINDEER_FOODSVENDOR:
objectDef OBJ_TYPE::WANDERING_NPC, 712, DIRECTIONS::DOWN, 148
.addr SPRITEDEF_SUIT_GUY
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_REINDEER_FOODSVENDOR
.ifndef VER_JP
OBJ_DIALOGUE UMSG::DRUGSVENDOR_WELCOME
	@J_JUMP:
.endif
OBJ_SET_FLAG 0
OBJ_NOT_HAS_ITEM 0, @J_NOT_HAS_ITEM-OBJ_REINDEER_FOODSVENDOR
OBJ_CLEAR_FLAG 0
	@J_NOT_HAS_ITEM:
.ifdef VER_JP
OBJ_DIALOGUE UMSG::DRUGSVENDOR_WELCOME
.endif
OBJ_DISPLAY_ITEMS 60, 71, 64, 69, @J_DISPLAY_ITEMS-OBJ_REINDEER_FOODSVENDOR
OBJ_IS_NOT_FLAG 0, @J_IS_NOT_FLAG-OBJ_REINDEER_FOODSVENDOR
OBJ_DIALOGUE UMSG::DRUGSVENDOR_NOMORE
OBJ_CLEAR_FLAG 0
OBJ_STOP
	@J_IS_NOT_FLAG:
OBJ_TAKE_MONEY @J_TAKE_MONEY-OBJ_REINDEER_FOODSVENDOR
OBJ_DIALOGUE UMSG::SHOP_CONFIRM
OBJ_YESNO_IS_NO @J_YESNO_IS_NO-OBJ_REINDEER_FOODSVENDOR
OBJ_DIALOGUE UMSG::BURGERSHOP_GOODBYE
OBJ_PLAY_SOUND 11
OBJ_SHOW_MONEY
OBJ_GIVE_ITEM @J_IS_NOT_TALKING-OBJ_REINDEER_FOODSVENDOR
.ifndef VER_JP
OBJ_DIALOGUE UMSG::BURGERSHOP_ANYMORE
OBJ_YESNO_IS_NO @J_YESNO_IS_NO1-OBJ_REINDEER_FOODSVENDOR
OBJ_JUMP @J_JUMP-OBJ_REINDEER_FOODSVENDOR
	@J_YESNO_IS_NO1:
OBJ_DIALOGUE UMSG::BURGERSHOP_GOODBYE
.endif
OBJ_STOP
	@J_YESNO_IS_NO:
OBJ_GIVE_MONEY @J_IS_NOT_TALKING-OBJ_REINDEER_FOODSVENDOR
	@J_DISPLAY_ITEMS:
OBJ_DIALOGUE UMSG::MISLAY_MOUTHWASHKID_NOTAKE
OBJ_CLEAR_FLAG 0
OBJ_STOP
	@J_TAKE_MONEY:
OBJ_DIALOGUE UMSG::HOSPITAL_NURSE_NOMONEY
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_REINDEER_FOODSWOMAN:
objectDef OBJ_TYPE::WANDERING_NPC, 714, DIRECTIONS::DOWN, 148
.addr SPRITEDEF_SUIT_GIRL
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_REINDEER_FOODSWOMAN
OBJ_DIALOGUE UMSG::REINDEER_FOODSWOMAN
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_ELLAY_VARIETYVENDOR:
objectDef OBJ_TYPE::WANDERING_NPC, 744, DIRECTIONS::DOWN, 996
.addr SPRITEDEF_SUIT_GUY
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_ELLAY_VARIETYVENDOR
.ifndef VER_JP
OBJ_DIALOGUE UMSG::DRUGSVENDOR_WELCOME
	@J_JUMP:
.endif
OBJ_SET_FLAG 0
OBJ_NOT_HAS_ITEM 0, @J_NOT_HAS_ITEM-OBJ_ELLAY_VARIETYVENDOR
OBJ_CLEAR_FLAG 0
	@J_NOT_HAS_ITEM:
.ifdef VER_JP
OBJ_DIALOGUE UMSG::DRUGSVENDOR_WELCOME
.endif
OBJ_DISPLAY_ITEMS 90, 10, 40, 11, @J_DISPLAY_ITEMS-OBJ_ELLAY_VARIETYVENDOR
OBJ_IS_NOT_FLAG 0, @J_IS_NOT_FLAG-OBJ_ELLAY_VARIETYVENDOR
OBJ_DIALOGUE UMSG::DRUGSVENDOR_NOMORE
OBJ_CLEAR_FLAG 0
OBJ_STOP
	@J_IS_NOT_FLAG:
OBJ_TAKE_MONEY @J_TAKE_MONEY-OBJ_ELLAY_VARIETYVENDOR
OBJ_DIALOGUE UMSG::SHOP_CONFIRM
OBJ_YESNO_IS_NO @J_YESNO_IS_NO-OBJ_ELLAY_VARIETYVENDOR
OBJ_DIALOGUE UMSG::BURGERSHOP_GOODBYE
OBJ_PLAY_SOUND 11
OBJ_SHOW_MONEY
OBJ_GIVE_ITEM @J_IS_NOT_TALKING-OBJ_ELLAY_VARIETYVENDOR
.ifndef VER_JP
OBJ_DIALOGUE UMSG::BURGERSHOP_ANYMORE
OBJ_YESNO_IS_NO @J_YESNO_IS_NO1-OBJ_ELLAY_VARIETYVENDOR
OBJ_JUMP @J_JUMP-OBJ_ELLAY_VARIETYVENDOR
	@J_YESNO_IS_NO1:
OBJ_DIALOGUE UMSG::BURGERSHOP_GOODBYE
.endif
OBJ_STOP
	@J_YESNO_IS_NO:
OBJ_GIVE_MONEY @J_IS_NOT_TALKING-OBJ_ELLAY_VARIETYVENDOR
	@J_DISPLAY_ITEMS:
OBJ_DIALOGUE UMSG::MISLAY_MOUTHWASHKID_NOTAKE
OBJ_CLEAR_FLAG 0
OBJ_STOP
	@J_TAKE_MONEY:
OBJ_DIALOGUE UMSG::HOSPITAL_NURSE_NOMONEY
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_YOUNGTOWN_ATM:
objectDef 24, 36, DIRECTIONS::UP, 275
OBJ_SUBROUTINE OBJ_YOUNGTOWN_ATM, OBJ_ATM_SUBR-OBJ_YOUNGTOWN_ATM
OBJ_STOP

OBJ_ATM_SUBR:
OBJ_IS_NOT_USING 110, @J_IS_NOT_USING-OBJ_YOUNGTOWN_ATM
OBJ_DIALOGUE UMSG::ATM_INTRO
OBJ_MENU UMSG::ATM_MENU, @J_MENU-OBJ_YOUNGTOWN_ATM, @J_MENU1-OBJ_YOUNGTOWN_ATM
OBJ_DIALOGUE UMSG::ATM_CURRENT_BALANCE
OBJ_DIALOGUE UMSG::ATM_HOWMUCH_WITHDRAW
OBJ_INPUT_NUMBER @J_MENU1-OBJ_YOUNGTOWN_ATM
OBJ_DEPOSIT @J_DEPOSIT-OBJ_YOUNGTOWN_ATM
OBJ_GIVE_MONEY @J_GIVE_MONEY-OBJ_YOUNGTOWN_ATM
OBJ_SHOW_MONEY
OBJ_DIALOGUE UMSG::SPOOKANE_HOTELBELLHOP_THANKS
OBJ_RETURN
	@J_GIVE_MONEY:
OBJ_WITHDRAW @J_WITHDRAW-OBJ_YOUNGTOWN_ATM
OBJ_DIALOGUE UMSG::ATM_TOO_MUCH_CASH
OBJ_RETURN
	@J_DEPOSIT:
OBJ_DIALOGUE UMSG::ATM_INSUFFICIENT
OBJ_RETURN
	@J_MENU:
OBJ_DIALOGUE UMSG::ATM_CURRENT_BALANCE
OBJ_DIALOGUE UMSG::ATM_HOWMUCH_DEPOSIT
OBJ_INPUT_NUMBER @J_MENU1-OBJ_YOUNGTOWN_ATM
OBJ_TAKE_MONEY @J_TAKE_MONEY-OBJ_YOUNGTOWN_ATM
OBJ_WITHDRAW @J_WITHDRAW1-OBJ_YOUNGTOWN_ATM
OBJ_SHOW_MONEY
OBJ_DIALOGUE UMSG::SPOOKANE_HOTELBELLHOP_THANKS
OBJ_RETURN
	@J_WITHDRAW1:
OBJ_GIVE_MONEY @J_WITHDRAW-OBJ_YOUNGTOWN_ATM
OBJ_DIALOGUE UMSG::ATM_DEPOSIT_TOO_MUCH
OBJ_RETURN
	@J_TAKE_MONEY:
OBJ_DIALOGUE UMSG::ATM_NOT_ENOUGH_STORED
OBJ_RETURN
	@J_MENU1:
OBJ_DIALOGUE UMSG::SPOOKANE_HOTELBELLHOP_THANKS
OBJ_RETURN
	@J_IS_NOT_USING:
OBJ_IS_NOT_CHECKING @J_WITHDRAW-OBJ_YOUNGTOWN_ATM
OBJ_DIALOGUE UMSG::ATM_INSERT_CASHCARD
	@J_WITHDRAW:
OBJ_RETURN

OBJ_YOUNGTOWN_PAYPHONE:
objectDef 24, 42, DIRECTIONS::UP, 275
OBJ_SUBROUTINE OBJ_YOUNGTOWN_PAYPHONE, OBJ_PAYPHONE_SUBR-OBJ_YOUNGTOWN_PAYPHONE
OBJ_STOP

OBJ_PAYPHONE_SUBR:
OBJ_IS_NOT_USING 2, @J_IS_NOT_USING-OBJ_YOUNGTOWN_PAYPHONE
OBJ_DIALOGUE UMSG::PAYPHONE_USECARD
OBJ_DECREMENT_COUNTER 4
OBJ_COUNTERLESSTHAN 4, 1, @J_COUNTERLESSTHAN-OBJ_YOUNGTOWN_PAYPHONE
OBJ_JUMP PHONE_SHARE_SUBR-OBJ_YOUNGTOWN_PAYPHONE
	@J_COUNTERLESSTHAN:
OBJ_PICK_ITEM 2
OBJ_DIALOGUE UMSG::PAYPHONE_CARDEXPIRE
OBJ_REMOVE_ITEM 0
OBJ_JUMP PHONE_SHARE_SUBR-OBJ_YOUNGTOWN_PAYPHONE
	@J_IS_NOT_USING:
OBJ_IS_NOT_TALKING PHONE_SHARE_J_IS_NOT_TALKING-OBJ_YOUNGTOWN_PAYPHONE
OBJ_LOAD_NUMBER 1
OBJ_TAKE_MONEY PHONE_SHARE_J_TAKE_MONEY-OBJ_YOUNGTOWN_PAYPHONE
OBJ_SHOW_MONEY
	PHONE_SHARE_SUBR:
OBJ_DIALOGUE UMSG::PHONE_GRAB
OBJ_DIALOGUE UMSG::PHONE_INTRO
OBJ_NO_NEW_MONEY @J_NO_NEW_MONEY-OBJ_YOUNGTOWN_PAYPHONE
OBJ_DIALOGUE UMSG::PHONE_NEWMONEY
	@J_NO_NEW_MONEY:
OBJ_DIALOGUE UMSG::PHONE_NEXTLVL
.repeat 3, I
OBJ_PICK_CHARACTER_J I, @J_PICK_CHARACTER_J-OBJ_YOUNGTOWN_PAYPHONE
OBJ_GET_NEXT_EXP
OBJ_DIALOGUE UMSG::PHONE_EXPLVL
.endrepeat
	@J_PICK_CHARACTER_J:
OBJ_DIALOGUE UMSG::PHONE_SAVEPROMPT
OBJ_MENU UMSG::MENU_YES_NO, @J_MENU-OBJ_YOUNGTOWN_PAYPHONE, @J_MENU-OBJ_YOUNGTOWN_PAYPHONE
OBJ_SAVE
OBJ_DIALOGUE UMSG::PHONE_SAVED_RESETPROMPT
OBJ_MENU UMSG::MENU_CONTINUE_REST, @J_MENU1-OBJ_YOUNGTOWN_PAYPHONE, @J_MENU2-OBJ_YOUNGTOWN_PAYPHONE
	@J_MENU2:
OBJ_DIALOGUE UMSG::PHONE_RESET_NO
OBJ_DIALOGUE UMSG::PHONE_END
OBJ_RETURN
	@J_MENU1:
OBJ_DIALOGUE UMSG::PHONE_RESET_YES
OBJ_DIALOGUE UMSG::PHONE_END
OBJ_RESET
	@J_MENU:
OBJ_DIALOGUE UMSG::PHONE_GOODLUCK
OBJ_DIALOGUE UMSG::PHONE_END
OBJ_RETURN
	PHONE_SHARE_J_TAKE_MONEY:
OBJ_DIALOGUE UMSG::PHONE_PAYPHONE
	PHONE_SHARE_J_IS_NOT_TALKING:
OBJ_RETURN

.ifndef VER_JP
OBJ_REINDEER_WEAPONVENDOR:
objectDef OBJ_TYPE::WANDERING_NPC, 8, DIRECTIONS::DOWN, 436
.addr SPRITEDEF_SUIT_GUY
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_REINDEER_WEAPONVENDOR
OBJ_DIALOGUE UMSG::WEAPONSHOP
	@J_JUMP:
OBJ_SET_FLAG 0
OBJ_NOT_HAS_ITEM 0, @J_NOT_HAS_ITEM-OBJ_REINDEER_WEAPONVENDOR
OBJ_CLEAR_FLAG 0
	@J_NOT_HAS_ITEM:
OBJ_DISPLAY_ITEMS 35, 37, 38, 0, @J_DISPLAY_ITEMS-OBJ_REINDEER_WEAPONVENDOR
OBJ_IS_NOT_FLAG 0, @J_IS_NOT_FLAG-OBJ_REINDEER_WEAPONVENDOR
OBJ_DIALOGUE UMSG::DRUGSVENDOR_NOMORE
OBJ_CLEAR_FLAG 0
OBJ_STOP
	@J_IS_NOT_FLAG:
OBJ_TAKE_MONEY @J_TAKE_MONEY-OBJ_REINDEER_WEAPONVENDOR
OBJ_DIALOGUE UMSG::SHOP_CONFIRM
OBJ_YESNO_IS_NO @J_YESNO_IS_NO-OBJ_REINDEER_WEAPONVENDOR
OBJ_DIALOGUE UMSG::BURGERSHOP_GOODBYE
OBJ_PLAY_SOUND 11
OBJ_SHOW_MONEY
OBJ_GIVE_ITEM @J_IS_NOT_TALKING-OBJ_REINDEER_WEAPONVENDOR
OBJ_DIALOGUE UMSG::BURGERSHOP_ANYMORE
OBJ_YESNO_IS_NO @J_YESNO_IS_NO1-OBJ_REINDEER_WEAPONVENDOR
OBJ_JUMP @J_JUMP-OBJ_REINDEER_WEAPONVENDOR
	@J_YESNO_IS_NO1:
OBJ_DIALOGUE UMSG::BURGERSHOP_GOODBYE
OBJ_STOP
	@J_YESNO_IS_NO:
OBJ_GIVE_MONEY @J_IS_NOT_TALKING-OBJ_REINDEER_WEAPONVENDOR
	@J_DISPLAY_ITEMS:
OBJ_DIALOGUE UMSG::MISLAY_MOUTHWASHKID_NOTAKE
OBJ_CLEAR_FLAG 0
OBJ_STOP
	@J_TAKE_MONEY:
OBJ_DIALOGUE UMSG::HOSPITAL_NURSE_NOMONEY
	@J_IS_NOT_TALKING:
OBJ_STOP
.endif