OBJ_BANK_2A:
.addr OBJ_TWINKLE_ROOFEXIT
.addr OBJ_MCAVE_HOLE1
.addr OBJ_MCAVE_HOLE2
.addr OBJ_MCAVE_LADDEREXIT
.addr OBJ_MCAVE_LADDER2
.addr OBJ_TWINKLE_TRASHLLOYD
.addr OBJ_TWINKLE_LLOYDINTRO
.addr OBJ_MCAVE_BEWAREMONKEY
.addr OBJ_MCAVE_RACCOON
.addr OBJ_MCAVE_CHILLMONKEY
.addr OBJ_MCAVE_QUICKMONKEY
.addr OBJ_MCAVE_DIRECTIONMONKEY
.addr OBJ_MCAVE_QUIETMONKEY
.addr OBJ_MCAVE_TRUTHMONKEY
.addr OBJ_MCAVE_LADYMONKEY
.addr OBJ_MCAVE_MELODYMONKEY
.addr OBJ_MCAVE_TIMEMONKEY
.addr OBJ_MCAVE_STORYMONKEY
.addr OBJ_MCAVE_WARNINGMONKEY
.addr OBJ_MCAVE_BTWMONKEY
.addr OBJ_MCAVE_GOBACKMONKEY
.addr OBJ_MCAVE_TEDDYMONKEY
.addr OBJ_MCAVE_SHYMONKEY
.addr OBJ_MCAVE_ANAMONKEY
.addr OBJ_MCAVE_LIEMONKEY
.addr OBJ_MCAVE_BOSSMONKEY
.addr OBJ_MCAVE_PENGUIN
.addr OBJ_MCAVE_PRESENT1
.addr OBJ_MCAVE_PRESENT2
.addr OBJ_MCAVE_PRESENT3
.addr 0

OBJ_TWINKLE_ROOFEXIT:
objectDef OBJ_TYPE::STAIRS, 107, DIRECTIONS::UP, 367
doorArgDef 0, 788, DIRECTIONS::LEFT, 981

OBJ_MCAVE_HOLE1:
objectDef OBJ_TYPE::HOLE, 61, DIRECTIONS::UP, 470
doorArgDef 0, 173, DIRECTIONS::DOWN, 648

OBJ_MCAVE_HOLE2:
objectDef OBJ_TYPE::HOLE, 77, DIRECTIONS::UP, 665
doorArgDef 49, 994, DIRECTIONS::DOWN, 553

OBJ_MCAVE_LADDEREXIT:
objectDef OBJ_TYPE::DOOR, 81, DIRECTIONS::UP, 459
doorArgDef 8, 634, DIRECTIONS::DOWN, 275

OBJ_MCAVE_LADDER2:
objectDef OBJ_TYPE::DOOR, 173, DIRECTIONS::UP, 647
doorArgDef 0, 61, DIRECTIONS::DOWN, 471

OBJ_TWINKLE_TRASHLLOYD:
objectDef 33, 110, DIRECTIONS::UP, 367
.addr SPRITEDEF_TRASH_CAN
OBJ_FLAG_DISAPPEAR 39
OBJ_IS_NOT_CHECKING @J_IS_NOT_CHECKING-OBJ_TWINKLE_TRASHLLOYD
OBJ_DIALOGUE UMSG::CANARY_PILLAR
OBJ_STOP
	@J_IS_NOT_CHECKING:
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_TWINKLE_TRASHLLOYD
OBJ_IS_NOT_FLAG 68, @J_IS_NOT_FLAG-OBJ_TWINKLE_TRASHLLOYD
OBJ_DIALOGUE UMSG::TWINKLE_TRASHLLOYD2
OBJ_YESNO_IS_NO @J_YESNO_IS_NO-OBJ_TWINKLE_TRASHLLOYD
OBJ_DIALOGUE UMSG::TWINKLE_TRASHLLOYD_YES
OBJ_SET_FLAG 40
OBJ_SET_FLAG 39
OBJ_SIGNAL 6
OBJ_MOVE @MOVE_DATA
OBJ_STOP
	@J_YESNO_IS_NO:
OBJ_DIALOGUE UMSG::CANARY_GENERIC
OBJ_STOP
	@J_IS_NOT_FLAG:
OBJ_DIALOGUE UMSG::TWINKLE_TRASHLLOYD1
OBJ_SET_FLAG 68
OBJ_STOP
	@J_IS_NOT_TALKING:
OBJ_STOP

@MOVE_DATA:
moveDef DIRECTIONS::UP, $a, 1
OBJ_STOP

OBJ_TWINKLE_LLOYDINTRO:
objectDef OBJ_TYPE::STATIONARY_NPC_CHECKSPAWN, 110, DIRECTIONS::DOWN, 367
.addr SPRITEDEF_LLOYD
OBJ_FLAG_APPEAR 40
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_TWINKLE_LLOYDINTRO
OBJ_DIALOGUE UMSG::TWINKLE_LLOYD_INTRODUCTION
OBJ_NOT_HAS_ITEM 97, @J_NOT_HAS_ITEM-OBJ_TWINKLE_LLOYDINTRO
OBJ_DIALOGUE UMSG::TWINKLE_LLOYDGETROCKET
OBJ_PLAY_MUSIC 33
OBJ_DELAY 180
OBJ_PLAY_MUSIC 14
OBJ_MOVE @MOVE_DATA_1
OBJ_SET_FLAG 36
OBJ_CLEAR_FLAG 40
	@J_IS_NOT_TALKING:
OBJ_IS_SIGNAL @J_NOT_HAS_ITEM-OBJ_TWINKLE_LLOYDINTRO
OBJ_MOVE @MOVE_DATA_2
OBJ_PLAY_MUSIC 29
OBJ_DELAY 180
OBJ_PLAY_MUSIC 14
	@J_NOT_HAS_ITEM:
OBJ_STOP

@MOVE_DATA_1:
moveDef DIRECTIONS::DOWN, 6, 2
moveDef DIRECTIONS::LEFT, 6, 3
moveDef DIRECTIONS::UP, 6, 1
moveDef DIRECTIONS::UP, 2, 1
moveDef DIRECTIONS::LEFT, 2, 1
OBJ_RETURN
@MOVE_DATA_2:
moveDef DIRECTIONS::DOWN, MOVE_CMD::ABOUTFACE, 1
OBJ_STOP

OBJ_MCAVE_BEWAREMONKEY:
objectDef OBJ_TYPE::WANDERING_NPC, 89, DIRECTIONS::UP, 462
.addr SPRITEDEF_MONKEY
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_MCAVE_BEWAREMONKEY
OBJ_DIALOGUE UMSG::MCAVE_BEWAREMONKEY
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_MCAVE_RACCOON:
objectDef OBJ_TYPE::WANDERING_NPC, 97, DIRECTIONS::RIGHT, 658
.addr SPRITEDEF_MONKEY
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_MCAVE_RACCOON
OBJ_DIALOGUE UMSG::MCAVE_RACCOON
OBJ_YESNO_IS_NO @J_YESNO_IS_NO-OBJ_MCAVE_RACCOON
OBJ_DIALOGUE UMSG::MCAVE_RACCOON_YES
OBJ_STOP
	@J_YESNO_IS_NO:
OBJ_DIALOGUE UMSG::MCAVE_RACCOON_NO
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_MCAVE_CHILLMONKEY:
objectDef OBJ_TYPE::WANDERING_NPC, 110, DIRECTIONS::DOWN, 665
.addr SPRITEDEF_MONKEY
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_MCAVE_CHILLMONKEY
OBJ_DIALOGUE UMSG::MCAVE_CHILLMONKEY
OBJ_YESNO_IS_NO @J_YESNO_IS_NO-OBJ_MCAVE_CHILLMONKEY
OBJ_DIALOGUE UMSG::MCAVE_CHILLMONKEY_YES
OBJ_STOP
	@J_YESNO_IS_NO:
OBJ_DIALOGUE UMSG::MCAVE_CHILLMONKEY_NO
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_MCAVE_QUICKMONKEY:
objectDef OBJ_TYPE::WANDERINGFAST_NPC, 78, DIRECTIONS::RIGHT, 689
.addr SPRITEDEF_MONKEY
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_MCAVE_QUICKMONKEY
OBJ_IS_NOT_FLAG 69, @J_IS_NOT_FLAG-OBJ_MCAVE_QUICKMONKEY
OBJ_DIALOGUE UMSG::MCAVE_QUICKMONKEY_CAUGHT
OBJ_STOP
	@J_IS_NOT_FLAG:
OBJ_DIALOGUE UMSG::MCAVE_QUICKMONKEY
OBJ_NOT_HAS_ITEM 0, @J_NOT_HAS_ITEM-OBJ_MCAVE_QUICKMONKEY
OBJ_PICK_ITEM 78
OBJ_GIVE_ITEM @J_IS_NOT_TALKING-OBJ_MCAVE_QUICKMONKEY
OBJ_PLAY_SOUND 6
OBJ_SET_FLAG 69
OBJ_STOP
	@J_NOT_HAS_ITEM:
OBJ_DIALOGUE UMSG::YUCCA_PILOT_NOROOM
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_MCAVE_DIRECTIONMONKEY:
objectDef OBJ_TYPE::WANDERING_NPC, 45, DIRECTIONS::LEFT, 661
.addr SPRITEDEF_MONKEY
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_MCAVE_DIRECTIONMONKEY
OBJ_DIALOGUE UMSG::MCAVE_DIRECTIONMONKEY
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_MCAVE_QUIETMONKEY:
objectDef OBJ_TYPE::WANDERING_NPC, 28, DIRECTIONS::UP, 489
.addr SPRITEDEF_MONKEY
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_MCAVE_QUIETMONKEY
OBJ_DIALOGUE UMSG::MCAVE_QUIETMONKEY
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_MCAVE_TRUTHMONKEY:
objectDef OBJ_TYPE::WANDERING_NPC, 167, DIRECTIONS::LEFT, 649
.addr SPRITEDEF_MONKEY
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_MCAVE_TRUTHMONKEY
OBJ_DIALOGUE UMSG::MCAVE_TRUTHMONKEY
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_MCAVE_LADYMONKEY:
objectDef OBJ_TYPE::WANDERING_NPC, 45, DIRECTIONS::RIGHT, 493
.addr SPRITEDEF_MONKEY
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_MCAVE_LADYMONKEY
OBJ_DIALOGUE UMSG::MCAVE_LADYMONKEY
OBJ_YESNO_IS_NO @J_YESNO_IS_NO-OBJ_MCAVE_LADYMONKEY
OBJ_DIALOGUE UMSG::MCAVE_LADYMONKEY_LIE
OBJ_STOP
	@J_YESNO_IS_NO:
OBJ_DIALOGUE UMSG::PODUNK_PIPPI_MEET_NOYES
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_MCAVE_MELODYMONKEY:
objectDef OBJ_TYPE::WANDERING_NPC, 105, DIRECTIONS::DOWN, 659
.addr SPRITEDEF_MONKEY
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_MCAVE_MELODYMONKEY
OBJ_DIALOGUE UMSG::MCAVE_MELODYMONKEY
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_MCAVE_TIMEMONKEY:
objectDef OBJ_TYPE::WANDERING_NPC, 125, DIRECTIONS::DOWN, 665
.addr SPRITEDEF_MONKEY
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_MCAVE_TIMEMONKEY
OBJ_DIALOGUE UMSG::MCAVE_TIMEMONKEY
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_MCAVE_STORYMONKEY:
objectDef OBJ_TYPE::WANDERING_NPC, 65, DIRECTIONS::RIGHT, 481
.addr SPRITEDEF_MONKEY
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_MCAVE_STORYMONKEY
OBJ_DIALOGUE UMSG::MCAVE_STORYMONKEY
OBJ_YESNO_IS_NO @J_YESNO_IS_NO-OBJ_MCAVE_STORYMONKEY
OBJ_DIALOGUE UMSG::MCAVE_STORYMONKEY_YES
OBJ_STOP
	@J_YESNO_IS_NO:
OBJ_DIALOGUE UMSG::MCAVE_STORYMONKEY_NO
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_MCAVE_WARNINGMONKEY:
objectDef OBJ_TYPE::WANDERING_NPC, 69, DIRECTIONS::UP, 649
.addr SPRITEDEF_MONKEY
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_MCAVE_WARNINGMONKEY
OBJ_DIALOGUE UMSG::MCAVE_WARNINGMONKEY
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_MCAVE_BTWMONKEY:
objectDef OBJ_TYPE::WANDERING_NPC, 66, DIRECTIONS::DOWN, 658
.addr SPRITEDEF_MONKEY
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_MCAVE_BTWMONKEY
OBJ_DIALOGUE UMSG::MCAVE_BTWMONKEY
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_MCAVE_GOBACKMONKEY:
objectDef OBJ_TYPE::WANDERING_NPC, 114, DIRECTIONS::LEFT, 674
.addr SPRITEDEF_MONKEY
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_MCAVE_GOBACKMONKEY
OBJ_DIALOGUE UMSG::MCAVE_GOBACKMONKEY
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_MCAVE_TEDDYMONKEY:
objectDef OBJ_TYPE::WANDERING_NPC, 73, DIRECTIONS::RIGHT, 474
.addr SPRITEDEF_MONKEY
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_MCAVE_TEDDYMONKEY
OBJ_DIALOGUE UMSG::MCAVE_TEDDYMONKEY
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_MCAVE_SHYMONKEY:
objectDef OBJ_TYPE::WANDERING_NPC, 119, DIRECTIONS::DOWN, 657
.addr SPRITEDEF_MONKEY
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_MCAVE_SHYMONKEY
OBJ_DIALOGUE UMSG::MCAVE_SHYMONKEY
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_MCAVE_ANAMONKEY:
objectDef OBJ_TYPE::WANDERING_NPC, 73, DIRECTIONS::LEFT, 680
.addr SPRITEDEF_MONKEY
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_MCAVE_ANAMONKEY
OBJ_DIALOGUE UMSG::MCAVE_ANAMONKEY
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_MCAVE_LIEMONKEY:
objectDef OBJ_TYPE::WANDERING_NPC, 92, DIRECTIONS::DOWN, 665
.addr SPRITEDEF_MONKEY
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_MCAVE_LIEMONKEY
OBJ_DIALOGUE UMSG::MCAVE_LIEMONKEY
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_MCAVE_BOSSMONKEY:
objectDef OBJ_TYPE::WANDERING_NPC, 101, DIRECTIONS::RIGHT, 661
.addr SPRITEDEF_MONKEY
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_MCAVE_BOSSMONKEY
OBJ_DIALOGUE UMSG::MCAVE_BOSSMONKEY
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_MCAVE_PENGUIN:
objectDef OBJ_TYPE::WANDERING_NPC, 98, DIRECTIONS::UP, 661
.addr SPRITEDEF_PENGUIN
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_MCAVE_PENGUIN
OBJ_DIALOGUE UMSG::MCAVE_PENGUIN
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_MCAVE_PRESENT1:
objectDef OBJ_TYPE::PRESENT, 108, DIRECTIONS::UP, 649
.addr SPRITEDEF_PRESENT
.byte 73 ; item
.byte 29 ; flag

OBJ_MCAVE_PRESENT2:
objectDef OBJ_TYPE::PRESENT, 142, DIRECTIONS::UP, 674
.addr SPRITEDEF_PRESENT
.byte 73 ; item
.byte 30 ; flag

OBJ_MCAVE_PRESENT3:
objectDef OBJ_TYPE::PRESENT, 17, DIRECTIONS::UP, 691
.addr SPRITEDEF_PRESENT
.byte 73 ; item
.byte 31 ; flag

