;differences are the us added mt. itoi rooms
;and the cheapest flightplan added a loop around the cactus

OBJ_BANK_8:
.addr OBJ_YUCCA_PILOT
.addr OBJ_YUCCA_TANK
.addr OBJ_YUCCA_PLANE
.addr OBJ_YUCCA_SIGN
.addr OBJ_YUCCA_TANK2
.addr OBJ_YUCCA_R7037_TANK
.ifndef VER_JP ;us only
.addr OBJ_MTITOI_GIEGUECAVEEXIT
.addr OBJ_MTITOI_TUBESENTRANCE
.addr OBJ_MTITOI_GIEGUECAVETOP
.endif
.addr 0

OBJ_YUCCA_PILOT:
objectDef OBJ_TYPE::STATIONARY_NPC_CHECKSPAWN, $1f3, DIRECTIONS::DOWN, $121
.addr SPRITEDEF_PILOT_VEHIC ;sprite
OBJ_FLAG_DISAPPEAR $17
OBJ_IS_NOT_USING $64, @IJUSE0-OBJ_YUCCA_PILOT
OBJ_RESET_COUNTER $5
    @CNJCOMPCOUNTER2:
OBJ_NOT_HAS_ITEM $64, @IJHASITEM1-OBJ_YUCCA_PILOT
OBJ_SHOW_MONEY
OBJ_PICK_ITEM $64
OBJ_REMOVE_ITEM @IJHASITEM1-OBJ_YUCCA_PILOT
OBJ_INCREMENT_COUNTER $5
OBJ_COUNTERLESSTHAN $5, $A, @CNJCOMPCOUNTER2-OBJ_YUCCA_PILOT
OBJ_DIALOGUE UMSG::YUCCA_PILOT_TANK
OBJ_SET_FLAG $88
OBJ_STOP
    @IJHASITEM1:
OBJ_COUNTERLESSTHAN $5, $1, @CNJCOMPCOUNTER3-OBJ_YUCCA_PILOT
OBJ_NOT_HAS_ITEM $0, @CNJCOMPCOUNTER3-OBJ_YUCCA_PILOT
OBJ_PICK_ITEM $64
OBJ_GIVE_ITEM @CNJCOMPCOUNTER3-OBJ_YUCCA_PILOT
OBJ_DECREMENT_COUNTER $5
OBJ_JUMP @IJHASITEM1-OBJ_YUCCA_PILOT
    @CNJCOMPCOUNTER3:
OBJ_DIALOGUE UMSG::YUCCA_PILOT_NOMONEY2
OBJ_STOP
    @IJUSE0:
OBJ_IS_NOT_TALKING @JTALK4-OBJ_YUCCA_PILOT
OBJ_IS_NOT_FLAG $88, @FJJUMP5-OBJ_YUCCA_PILOT
OBJ_DIALOGUE UMSG::YUCCA_PILOT_TANKRIDE
OBJ_STOP
    @FJJUMP5:
OBJ_IS_NOT_FLAG $3A, @FJJUMP6-OBJ_YUCCA_PILOT
OBJ_DIALOGUE UMSG::YUCCA_PILOT_RIDE
OBJ_YESNO_IS_NO @JYESNO7-OBJ_YUCCA_PILOT
OBJ_DIALOGUE UMSG::YUCCA_PILOT_CHOOSEPLAN
OBJ_DISPLAY_ITEMS $9C, $9D, $9E, $0, @JYESNO7-OBJ_YUCCA_PILOT
OBJ_CLEAR_FLAG $89
OBJ_CLEAR_FLAG $8A
OBJ_CLEAR_FLAG $8B
OBJ_IS_NOT_SELECTED $9C, @IJSELECTEDITEM8-OBJ_YUCCA_PILOT
OBJ_SET_FLAG $89
OBJ_JUMP @JUMP9-OBJ_YUCCA_PILOT
    @IJSELECTEDITEM8:
OBJ_IS_NOT_SELECTED $9D, @IJSELECTEDITEM10-OBJ_YUCCA_PILOT
OBJ_SET_FLAG $8A
OBJ_JUMP @JUMP9-OBJ_YUCCA_PILOT
    @IJSELECTEDITEM10:
OBJ_IS_NOT_SELECTED $9E, @JUMP9-OBJ_YUCCA_PILOT
OBJ_SET_FLAG $8B
    @JUMP9:
OBJ_RESET_COUNTER $0
OBJ_INCREMENT_COUNTER $0
OBJ_PICK_CHARACTER_J $1, @CJSELECTPARTY11-OBJ_YUCCA_PILOT
OBJ_HAS_STATUS $80, @SJPRESENT12-OBJ_YUCCA_PILOT
OBJ_INCREMENT_COUNTER $0
    @SJPRESENT12:
OBJ_PICK_CHARACTER_J $2, @CJSELECTPARTY11-OBJ_YUCCA_PILOT
OBJ_HAS_STATUS $80, @CJSELECTPARTY11-OBJ_YUCCA_PILOT
OBJ_INCREMENT_COUNTER $0
    @CJSELECTPARTY11:
OBJ_MULTIPLY_BY_PARTY
OBJ_DIALOGUE UMSG::YUCCA_PILOT_RIDE_ACCEPT
OBJ_TAKE_MONEY @JTAKEMONEY13-OBJ_YUCCA_PILOT
OBJ_RESET_COUNTER $6
    @JUMP16:
OBJ_COUNTERLESSTHAN $0, $1, @CNJCOMPCOUNTER14-OBJ_YUCCA_PILOT
OBJ_NOT_HAS_ITEM $0, @IJHASITEM15-OBJ_YUCCA_PILOT
OBJ_PICK_ITEM $64
OBJ_GIVE_ITEM @IJHASITEM15-OBJ_YUCCA_PILOT
OBJ_INCREMENT_COUNTER $6
OBJ_DECREMENT_COUNTER $0
OBJ_JUMP @JUMP16-OBJ_YUCCA_PILOT
    @IJHASITEM15:
OBJ_COUNTERLESSTHAN $6, $1, @CNJCOMPCOUNTER17-OBJ_YUCCA_PILOT
OBJ_NOT_HAS_ITEM $64, @JTALK4-OBJ_YUCCA_PILOT
OBJ_PICK_ITEM $64
OBJ_REMOVE_ITEM @JTALK4-OBJ_YUCCA_PILOT
OBJ_DECREMENT_COUNTER $6
OBJ_JUMP @IJHASITEM15-OBJ_YUCCA_PILOT
    @CNJCOMPCOUNTER17:
OBJ_DIALOGUE UMSG::YUCCA_PILOT_NOROOM
OBJ_IS_NOT_FLAG $89, @FJJUMP18-OBJ_YUCCA_PILOT
OBJ_PICK_ITEM $9C
OBJ_JUMP @JUMP19-OBJ_YUCCA_PILOT
    @FJJUMP18:
OBJ_IS_NOT_FLAG $8A, @FJJUMP20-OBJ_YUCCA_PILOT
OBJ_PICK_ITEM $9D
OBJ_JUMP @JUMP19-OBJ_YUCCA_PILOT
    @FJJUMP20:
OBJ_PICK_ITEM $9E
    @JUMP19:
OBJ_MULTIPLY_BY_PARTY
OBJ_GIVE_MONEY @JTALK4-OBJ_YUCCA_PILOT
OBJ_STOP
    @JTAKEMONEY13:
OBJ_DIALOGUE UMSG::YUCCA_PILOT_NOMONEY
OBJ_STOP
    @JYESNO7:
OBJ_DIALOGUE UMSG::YUCCA_PILOT_RIDE_DECLINE
OBJ_STOP
    @FJJUMP6:
OBJ_DIALOGUE UMSG::YUCCA_PILOT_MINE
OBJ_SET_FLAG $3A
    @JTALK4:
OBJ_STOP
    @CNJCOMPCOUNTER14:
OBJ_PLAY_SOUND $6
OBJ_MOVE @MOVE0
OBJ_SIGNAL $2
OBJ_SET_FLAG $17
OBJ_STOP
    @MOVE0:
moveDef DIRECTIONS::UP, $6, $1
moveDef DIRECTIONS::DOWN, $2, $1
OBJ_STOP

OBJ_YUCCA_TANK:
objectDef $1e, $1f8, DIRECTIONS::DOWN, $124
.addr SPRITEDEF_TANK+16 ;sprite
OBJ_FLAG_DISAPPEAR $18
OBJ_IS_NOT_TOUCHING @JTOUCH0-OBJ_YUCCA_TANK
OBJ_IS_NOT_FLAG $88, @JTOUCH0-OBJ_YUCCA_TANK
OBJ_PLAY_MUSIC $17
OBJ_TANK DIRECTIONS::DOWN
OBJ_SET_FLAG $18
OBJ_SET_FLAG $73
    @JTOUCH0:
OBJ_STOP

OBJ_YUCCA_PLANE:
objectDef $1e, $1f3, DIRECTIONS::LEFT, $120
.addr SPRITEDEF_PLANE+24 ;sprite
OBJ_FLAG_DISAPPEAR $19
OBJ_IS_SIGNAL @JSIGNALED0-OBJ_YUCCA_PLANE
OBJ_IS_NOT_FLAG $89, @FJJUMP1-OBJ_YUCCA_PLANE
OBJ_AIRPLANE DIRECTIONS::LEFT
OBJ_PLAY_MUSIC $1E
OBJ_MOVE @MOVE0
OBJ_END_PLANE
OBJ_MOVE @MOVE1
OBJ_EXIT_VEHICLE DIRECTIONS::DOWN
OBJ_PLAY_MUSIC $8
OBJ_CLEAR_FLAG $17
OBJ_STOP
    @FJJUMP1:
OBJ_IS_NOT_FLAG $8A, @FJJUMP2-OBJ_YUCCA_PLANE
OBJ_AIRPLANE DIRECTIONS::LEFT
OBJ_PLAY_MUSIC $1E
OBJ_MOVE @MOVE2
OBJ_END_PLANE
OBJ_MOVE @MOVE1
OBJ_EXIT_VEHICLE DIRECTIONS::DOWN
OBJ_PLAY_MUSIC $8
OBJ_CLEAR_FLAG $17
OBJ_STOP
    @FJJUMP2:
OBJ_IS_NOT_FLAG $8B, @JSIGNALED0-OBJ_YUCCA_PLANE
OBJ_AIRPLANE DIRECTIONS::LEFT
OBJ_PLAY_MUSIC $1E
OBJ_MOVE @MOVE3
OBJ_END_PLANE
OBJ_MOVE @MOVE1
OBJ_EXIT_VEHICLE DIRECTIONS::DOWN
OBJ_PLAY_MUSIC $8
OBJ_CLEAR_FLAG $17
    @JSIGNALED0:
OBJ_STOP
    @MOVE0:
;jp didnt have the loop
.ifdef VER_JP
moveDef DIRECTIONS::LEFT, $2, $30
moveDef DIRECTIONS::UP_LEFT, $2, $5
moveDef DIRECTIONS::UP, $2, $4C
moveDef DIRECTIONS::UP_RIGHT, $2, $5
moveDef DIRECTIONS::RIGHT, $2, $B4
.else
moveDef DIRECTIONS::LEFT, $2, $33
moveDef DIRECTIONS::UP_LEFT, $2, $5
moveDef DIRECTIONS::UP, $2, $A
moveDef DIRECTIONS::UP, $2, $2
moveDef DIRECTIONS::UP_RIGHT, $2, $2
moveDef DIRECTIONS::RIGHT, $2, $4
moveDef DIRECTIONS::DOWN_RIGHT, $2, $2
moveDef DIRECTIONS::DOWN, $2, $4
moveDef DIRECTIONS::DOWN_LEFT, $2, $2
moveDef DIRECTIONS::LEFT, $2, $4
moveDef DIRECTIONS::UP_LEFT, $2, $2
moveDef DIRECTIONS::UP, $2, $4
moveDef DIRECTIONS::UP_RIGHT, $2, $2
moveDef DIRECTIONS::RIGHT, $2, $4
moveDef DIRECTIONS::DOWN_RIGHT, $2, $2
moveDef DIRECTIONS::DOWN, $2, $4
moveDef DIRECTIONS::DOWN_LEFT, $2, $2
moveDef DIRECTIONS::LEFT, $2, $4
moveDef DIRECTIONS::UP_LEFT, $2, $2
moveDef DIRECTIONS::UP, $2, $1
moveDef DIRECTIONS::UP, $2, $43
moveDef DIRECTIONS::UP_RIGHT, $2, $5
moveDef DIRECTIONS::RIGHT, $2, $B7
.endif
moveDef DIRECTIONS::DOWN_RIGHT, $2, $5
moveDef DIRECTIONS::DOWN, $2, $4C
moveDef DIRECTIONS::DOWN_LEFT, $2, $5
moveDef DIRECTIONS::LEFT, $2, $7A
.byte 3
    @MOVE2:
moveDef DIRECTIONS::LEFT, $2, $D6
moveDef DIRECTIONS::DOWN_LEFT, $2, $2E
moveDef DIRECTIONS::LEFT, $2, $32
moveDef DIRECTIONS::UP_LEFT, $2, $A
moveDef DIRECTIONS::UP, $2, $40
moveDef DIRECTIONS::UP_RIGHT, $2, $D
moveDef DIRECTIONS::RIGHT, $2, $C8
moveDef DIRECTIONS::RIGHT, $2, $7A
moveDef DIRECTIONS::DOWN_RIGHT, $2, $8
moveDef DIRECTIONS::DOWN, $2, $19
moveDef DIRECTIONS::DOWN_LEFT, $2, $8
moveDef DIRECTIONS::LEFT, $2, $5
.byte 3
    @MOVE3:
moveDef DIRECTIONS::LEFT, $2, $F
moveDef DIRECTIONS::UP_LEFT, $2, $5
moveDef DIRECTIONS::UP, $2, $4C
moveDef DIRECTIONS::UP_RIGHT, $2, $5
moveDef DIRECTIONS::RIGHT, $2, $C8
moveDef DIRECTIONS::RIGHT, $2, $46
moveDef DIRECTIONS::DOWN_RIGHT, $2, $A
moveDef DIRECTIONS::DOWN, $2, $C3
moveDef DIRECTIONS::DOWN_LEFT, $2, $5
moveDef DIRECTIONS::LEFT, $2, $54
moveDef DIRECTIONS::UP_LEFT, $2, $7C
moveDef DIRECTIONS::LEFT, $2, $2A
.byte 3
    @MOVE1:
moveDef DIRECTIONS::LEFT, $2, $A
OBJ_STOP

OBJ_YUCCA_SIGN:
objectDef $19, $1e9, DIRECTIONS::UP, $122
.addr SPRITEDEF_SIGN ;sprite
OBJ_IS_NOT_CHECKING @JCHECK0-OBJ_YUCCA_SIGN
OBJ_DIALOGUE UMSG::YUCCA_SIGN
    @JCHECK0:
OBJ_STOP

OBJ_YUCCA_TANK2:
objectDef OBJ_TYPE::TRIGGER_CHECKSPAWN, $1f8, DIRECTIONS::UP, $124
OBJ_FLAG_APPEAR $73
OBJ_IS_NOT_TOUCHING @JTOUCH0-OBJ_YUCCA_TANK2
OBJ_CLEAR_FLAG $18
OBJ_CLEAR_FLAG $73
OBJ_PLAY_MUSIC $8
OBJ_EXIT_VEHICLE DIRECTIONS::UP
    @JTOUCH0:
OBJ_STOP

OBJ_YUCCA_R7037_TANK:
objectDef $1c, $275, DIRECTIONS::UP, $119
OBJ_FLAG_APPEAR $73
OBJ_IS_NOT_TOUCHING @JTOUCH0-OBJ_YUCCA_R7037_TANK
OBJ_BATTLE $6F
OBJ_SET_FLAG $78
OBJ_SET_FLAG $90
OBJ_CLEAR_FLAG $73
OBJ_SET_FLAG $17
OBJ_SET_FLAG $19
OBJ_SET_FLAG $1A
OBJ_PLAY_MUSIC $8
OBJ_EXIT_VEHICLE DIRECTIONS::UP
    @JTOUCH0:
OBJ_STOP

;us only
.ifndef VER_JP
OBJ_MTITOI_GIEGUECAVEEXIT:
objectDef OBJ_TYPE::DOOR, $305, DIRECTIONS::UP, $280
doorArgDef $B, $389, DIRECTIONS::DOWN, $246

OBJ_MTITOI_TUBESENTRANCE:
objectDef OBJ_TYPE::DOOR, $30d, DIRECTIONS::UP, $274
doorArgDef $0, $38D, DIRECTIONS::LEFT, $B6

OBJ_MTITOI_GIEGUECAVETOP:
objectDef $18, $306, DIRECTIONS::UP, $248
OBJ_IS_NOT_FACING @JUNK0-OBJ_MTITOI_GIEGUECAVETOP
OBJ_IS_NOT_TOUCHING @JUNK0-OBJ_MTITOI_GIEGUECAVETOP
OBJ_BATTLE $A2
    @JUNK0:
OBJ_STOP
.endif