OBJ_BANK_18:
.addr OBJ_PODUNK_HOTELEXIT
.addr OBJ_PODUNK_HOTELUPSTAIRS
.addr OBJ_PODUNK_HOTELUPROOM1EXIT
.addr OBJ_PODUNK_HOTELUPROOM2EXIT
.addr OBJ_YOUNGTOWN_FAKEHOTELEXIT
.addr OBJ_YOUNGTOWN_FAKEHOTELROOM1ENTRANCE
.addr OBJ_YOUNGTOWN_FAKEHOTELROOM2ENTRANCE
.addr OBJ_MERRYSVILLE_HOTELEXIT
.addr OBJ_MERRYSVILLE_HOTELUPSTAIRS
.addr OBJ_MERRYSVILLE_HOTELUPROOM1EXIT
.addr OBJ_MERRYSVILLE_HOTELUPROOM2EXIT
.addr OBJ_MERRYSVILLE_HOTELDOWN2STAIRS
.addr OBJ_ELLAY_HOTELEXIT
.addr OBJ_ELLAY_HOTELUPSTAIRS
.addr OBJ_REINDEER_HOTELEXIT
.addr OBJ_REINDEER_HOTELUPSTAIRS
.addr OBJ_PODUNK_HOTELBELLHOP
.addr OBJ_REINDEER_HOTELBELLHOP
.addr OBJ_ELLAY_HOTELBELLHOP
.addr OBJ_MERRYSVILLE_HOTELBELLHOP
.addr OBJ_YOUNGTOWN_FAKEHOTELBELLHOP
.addr OBJ_PODUNK_HOTELWOMAN
.addr OBJ_REINDEER_HOTELGUY
.addr OBJ_PODUNK_HOTELGUY
.addr OBJ_MERRYSVILLE_HOTELGUY
.addr OBJ_MERRYSVILLE_HOTELWAITER
.addr OBJ_MERRYSVILLE_HOTELMUSCIALGIRL
.addr OBJ_MERRYSVILLE_HOTELFAVFOODGUY
.addr 0

OBJ_PODUNK_HOTELEXIT:
objectDef OBJ_TYPE::DOOR, $25e, DIRECTIONS::RIGHT, $3b6
doorArgDef $6, $C7, DIRECTIONS::DOWN, $1A5

OBJ_PODUNK_HOTELUPSTAIRS:
objectDef OBJ_TYPE::STAIRS, $252, DIRECTIONS::LEFT, $3b5
doorArgDef $0, $2, DIRECTIONS::RIGHT, $A6

OBJ_PODUNK_HOTELUPROOM1EXIT:
objectDef OBJ_TYPE::DOOR, $2ce, DIRECTIONS::RIGHT, $86
doorArgDef $0, $6, DIRECTIONS::DOWN, $A4

OBJ_PODUNK_HOTELUPROOM2EXIT:
objectDef OBJ_TYPE::DOOR, $34e, DIRECTIONS::RIGHT, $86
doorArgDef $0, $9, DIRECTIONS::DOWN, $A4

OBJ_YOUNGTOWN_FAKEHOTELEXIT:
objectDef OBJ_TYPE::DOOR, $2be, DIRECTIONS::RIGHT, $3d6
doorArgDef $30, $2C9, DIRECTIONS::DOWN, $1C0

OBJ_YOUNGTOWN_FAKEHOTELROOM1ENTRANCE:
objectDef OBJ_TYPE::DOOR, $2b2, DIRECTIONS::LEFT, $3d5
doorArgDef $0, $21D, DIRECTIONS::LEFT, $96

OBJ_YOUNGTOWN_FAKEHOTELROOM2ENTRANCE:
objectDef OBJ_TYPE::DOOR, $2b0, DIRECTIONS::LEFT, $3d7
doorArgDef $0, $1BD, DIRECTIONS::LEFT, $96

OBJ_MERRYSVILLE_HOTELEXIT:
objectDef OBJ_TYPE::DOOR, $2de, DIRECTIONS::RIGHT, $3d6
doorArgDef $6, $16B, DIRECTIONS::DOWN, $1CD

OBJ_MERRYSVILLE_HOTELUPSTAIRS:
objectDef OBJ_TYPE::STAIRS, $2d2, DIRECTIONS::LEFT, $3d5
doorArgDef $0, $302, DIRECTIONS::RIGHT, $3F6

OBJ_MERRYSVILLE_HOTELUPROOM1EXIT:
objectDef OBJ_TYPE::DOOR, $2ee, DIRECTIONS::RIGHT, $86
doorArgDef $0, $306, DIRECTIONS::DOWN, $3F4

OBJ_MERRYSVILLE_HOTELUPROOM2EXIT:
objectDef OBJ_TYPE::DOOR, $36e, DIRECTIONS::RIGHT, $86
doorArgDef $0, $309, DIRECTIONS::DOWN, $3F4

OBJ_MERRYSVILLE_HOTELDOWN2STAIRS:
objectDef OBJ_TYPE::STAIRS, $271, DIRECTIONS::LEFT, $3c6
doorArgDef $0, $303, DIRECTIONS::RIGHT, $3F5

OBJ_ELLAY_HOTELEXIT:
objectDef OBJ_TYPE::DOOR, $2be, DIRECTIONS::RIGHT, $3f6
doorArgDef $6, $307, DIRECTIONS::DOWN, $12D

OBJ_ELLAY_HOTELUPSTAIRS:
objectDef OBJ_TYPE::STAIRS, $2b2, DIRECTIONS::LEFT, $3f5
doorArgDef $0, $1F2, DIRECTIONS::RIGHT, $96

OBJ_REINDEER_HOTELEXIT:
objectDef OBJ_TYPE::DOOR, $e, DIRECTIONS::RIGHT, $106
doorArgDef $6, $1A7, DIRECTIONS::DOWN, $3BD

OBJ_REINDEER_HOTELUPSTAIRS:
objectDef OBJ_TYPE::STAIRS, $2, DIRECTIONS::LEFT, $105
doorArgDef $0, $12, DIRECTIONS::RIGHT, $D6

OBJ_PODUNK_HOTELBELLHOP:
objectDef OBJ_TYPE::WANDERING_NPC, $258, DIRECTIONS::DOWN, $3b4
.addr SPRITEDEF_SUIT_GUY ;sprite
OBJ_LOAD_NUMBER 39
OBJ_SUBROUTINE OBJ_PODUNK_HOTELBELLHOP, OBJ_PODUNK_HOTELBELLHOP_OJSUBROUTINE0-OBJ_PODUNK_HOTELBELLHOP
OBJ_STOP
    OBJ_PODUNK_HOTELBELLHOP_OJSUBROUTINE0:
OBJ_IS_NOT_TALKING @JTALK0-OBJ_PODUNK_HOTELBELLHOP
OBJ_MULTIPLY_BY_PARTY
OBJ_DIALOGUE UMSG::HOTELBELLHOP
OBJ_YESNO_IS_NO @JYESNO1-OBJ_PODUNK_HOTELBELLHOP
OBJ_TAKE_MONEY @JTAKEMONEY2-OBJ_PODUNK_HOTELBELLHOP
OBJ_DIALOGUE UMSG::HOTELBELLHOP_ACCEPT
OBJ_SLEEP
OBJ_SHOW_MONEY
OBJ_DIALOGUE UMSG::HOTELBELLHOP_GOODMORNING
OBJ_RETURN
    @JTAKEMONEY2:
OBJ_DIALOGUE UMSG::HOSPITAL_NURSE_NOMONEY
OBJ_RETURN
    @JYESNO1:
OBJ_DIALOGUE UMSG::HOTELBELLHOP_DECLINE
    @JTALK0:
OBJ_RETURN

OBJ_REINDEER_HOTELBELLHOP:
objectDef OBJ_TYPE::WANDERING_NPC, $8, DIRECTIONS::DOWN, $104
.addr SPRITEDEF_SUIT_GUY ;sprite
OBJ_LOAD_NUMBER 100
OBJ_SUBROUTINE OBJ_PODUNK_HOTELBELLHOP, OBJ_PODUNK_HOTELBELLHOP_OJSUBROUTINE0-OBJ_PODUNK_HOTELBELLHOP
OBJ_STOP

OBJ_ELLAY_HOTELBELLHOP:
objectDef OBJ_TYPE::WANDERING_NPC, $2b8, DIRECTIONS::DOWN, $3f4
.addr SPRITEDEF_SUIT_GUY ;sprite
OBJ_LOAD_NUMBER 165
OBJ_SUBROUTINE OBJ_PODUNK_HOTELBELLHOP, OBJ_PODUNK_HOTELBELLHOP_OJSUBROUTINE0-OBJ_PODUNK_HOTELBELLHOP
OBJ_STOP

OBJ_MERRYSVILLE_HOTELBELLHOP:
objectDef OBJ_TYPE::WANDERING_NPC, $2d8, DIRECTIONS::DOWN, $3d4
.addr SPRITEDEF_SUIT_GUY ;sprite
OBJ_LOAD_NUMBER 65
OBJ_SUBROUTINE OBJ_PODUNK_HOTELBELLHOP, OBJ_PODUNK_HOTELBELLHOP_OJSUBROUTINE0-OBJ_PODUNK_HOTELBELLHOP
OBJ_STOP

OBJ_YOUNGTOWN_FAKEHOTELBELLHOP:
objectDef OBJ_TYPE::WANDERING_NPC, $2b5, DIRECTIONS::DOWN, $3d4
.addr SPRITEDEF_MAN ;sprite
OBJ_IS_NOT_TALKING @JTALK0-OBJ_YOUNGTOWN_FAKEHOTELBELLHOP
OBJ_DIALOGUE UMSG::YOUNGTOWN_HOTELBELLHOP
OBJ_YESNO_IS_NO @JYESNO1-OBJ_YOUNGTOWN_FAKEHOTELBELLHOP
OBJ_DIALOGUE UMSG::HOTELBELLHOP_ACCEPT
OBJ_SLEEP
OBJ_DIALOGUE UMSG::YOUNGTOWN_HOTELBELLHOP_GOODMORNING
OBJ_STOP
    @JYESNO1:
OBJ_DIALOGUE UMSG::YOUNGTOWN_HOTELBELLHOP_DECLINE
    @JTALK0:
OBJ_STOP

OBJ_PODUNK_HOTELWOMAN:
objectDef OBJ_TYPE::WANDERING_NPC, $255, DIRECTIONS::DOWN, $3b6
.addr SPRITEDEF_OLD_WOMAN ;sprite
OBJ_IS_NOT_TALKING @JTALK0-OBJ_PODUNK_HOTELWOMAN
OBJ_DIALOGUE UMSG::PODUNK_HOTELWOMAN
    @JTALK0:
OBJ_STOP

OBJ_REINDEER_HOTELGUY:
objectDef OBJ_TYPE::WANDERING_NPC, $5, DIRECTIONS::RIGHT, $106
.addr SPRITEDEF_COOL_GUY ;sprite
OBJ_IS_NOT_TALKING @JTALK0-OBJ_REINDEER_HOTELGUY
.ifdef VER_JP
OBJ_DIALOGUE UMSG::ELLAY_BBGANG1_TEDDY
.else
OBJ_DIALOGUE UMSG::REINDEER_HOTELGUY
.endif
    @JTALK0:
OBJ_STOP

OBJ_PODUNK_HOTELGUY:
objectDef OBJ_TYPE::WANDERING_NPC, $257, DIRECTIONS::LEFT, $3b6
.addr SPRITEDEF_MAN ;sprite
OBJ_IS_NOT_TALKING @JTALK0-OBJ_PODUNK_HOTELGUY
OBJ_DIALOGUE UMSG::PODUNK_HOTELGUY
    @JTALK0:
OBJ_STOP

OBJ_MERRYSVILLE_HOTELGUY:
objectDef OBJ_TYPE::WANDERING_NPC, $2d5, DIRECTIONS::RIGHT, $3d6
.addr SPRITEDEF_MAN ;sprite
OBJ_IS_NOT_TALKING @JTALK0-OBJ_MERRYSVILLE_HOTELGUY
OBJ_DIALOGUE UMSG::MERRYSVILLE_HOTELGUY
    @JTALK0:
OBJ_STOP

OBJ_MERRYSVILLE_HOTELWAITER:
objectDef OBJ_TYPE::WANDERING_NPC, $274, DIRECTIONS::DOWN, $3c4
.addr SPRITEDEF_MOUSTACHE_GUY ;sprite
OBJ_IS_NOT_TALKING @JTALK0-OBJ_MERRYSVILLE_HOTELWAITER
OBJ_DIALOGUE UMSG::MERRYSVILLE_HOTELWAITER
    @JTALK0:
OBJ_STOP

OBJ_MERRYSVILLE_HOTELMUSCIALGIRL:
objectDef OBJ_TYPE::WANDERING_NPC, $279, DIRECTIONS::LEFT, $3c6
.addr SPRITEDEF_WOMAN ;sprite
OBJ_IS_NOT_TALKING @JTALK0-OBJ_MERRYSVILLE_HOTELMUSCIALGIRL
OBJ_DIALOGUE UMSG::MERRYSVILLE_HOTELMUSCIALGIRL
    @JTALK0:
OBJ_STOP

OBJ_MERRYSVILLE_HOTELFAVFOODGUY:
objectDef OBJ_TYPE::WANDERING_NPC, $27c, DIRECTIONS::LEFT, $3c7
.addr SPRITEDEF_MAN ;sprite
OBJ_IS_NOT_TALKING @JTALK0-OBJ_MERRYSVILLE_HOTELFAVFOODGUY
OBJ_DIALOGUE UMSG::MERRYSVILLE_HOTELFAVFOODGUY
    @JTALK0:
OBJ_STOP