OBJ_BANK_16:
.addr OBJ_ELLAY_MTITOIENTRANCE
.addr OBJ_ELLAY_INTROSIGN
.addr 0

OBJ_ELLAY_MTITOIENTRANCE:
objectDef OBJ_TYPE::DOOR, $3e5, DIRECTIONS::UP, $14f
doorArgDef $13, $39A, DIRECTIONS::DOWN, $F9

OBJ_ELLAY_INTROSIGN:
objectDef $19, $360, DIRECTIONS::UP, $13a
.addr SPRITEDEF_SIGN ;sprite
OBJ_IS_NOT_CHECKING @JCHECK0-OBJ_ELLAY_INTROSIGN
OBJ_DIALOGUE UMSG::ELLAY_INTROSIGN
    @JCHECK0:
OBJ_STOP