OBJ_BANK_3:
.addr OBJ_MERRYSVILLE_DEPTENTRANCE
.addr OBJ_MERRYSVILLE_HOSPITALENTRANCE
.addr OBJ_MERRYSVILLE_HOTELENTRANCE
.addr OBJ_MERRYSVILLE_BURGERENTRANCE
.addr OBJ_MERRYSVILLE_SCHOOLENTRANCE
.addr OBJ_MERRYSVILLE_UNIONENTRANCE
.addr OBJ_MERRYSVILLE_RUMORGUY
.addr OBJ_MERRYSVILLE_COP
.addr OBJ_MERRYSVILLE_DUNCANGUY
.addr OBJ_MERRYSVILLE_BEATUPGUY
.addr OBJ_MERRYSVILLE_CURFEWGUY
.addr OBJ_MERRYSVILLE_TRAINWOMAN
.addr OBJ_MERRYSVILLE_NINTENDOGIRL
.addr OBJ_MERRYSVILLE_HAPPYGUY
.addr OBJ_MERRYSVILLE_STRIPGIRL
.addr OBJ_MERRYSVILLE_DOCTORGUY
.addr OBJ_MERRYSVILLE_QUESTIONNAIRE
.addr OBJ_MERRYSVILLE_SCHOOLGUY
.addr OBJ_MERRYSVILLE_MAYORGUY
.addr OBJ_MERRYSVILLE_ROCKETGUY
.addr OBJ_MERRYSVILLE_ORDINARYGUY
.addr OBJ_MERRYSVILLE_THINKINGGUY
.addr OBJ_MERRYSVILLE_HUSBANDGIRL
.addr OBJ_MERRYSVILLE_SWEETSGUY
.addr OBJ_MERRYSVILLE_MONSTERGIRL
.addr OBJ_MERRYSVILLE_HOSPITALSIGN
.addr OBJ_MERRYSVILLE_SIGN
.addr OBJ_MERRYSVILLE_DUNCANSIGN
.addr OBJ_MERRYSVILLE_SCHOOLSIGN
.addr OBJ_MERRYSVILLE_TELEPORTGAIN1
.addr OBJ_MERRYSVILLE_TELEPORTGAIN2
.addr OBJ_MERRYSVILLE_TELEPORTGAIN3
.addr OBJ_MERRYSVILLE_TELEPORTGAIN4
.addr OBJ_MERRYSVILLE_TELEPORTGAIN5
.addr OBJ_MERRYSVILLE_TELEPORTGAIN6
.addr OBJ_MERRYSVILLE_TELEPORTGAIN7
.addr OBJ_MERRYSVILLE_TELEPORTGAIN8
.addr OBJ_MERRYSVILLE_TELEPORTGAIN9
.addr OBJ_MERRYSVILLE_TELEPORTGAINA
.addr 0

OBJ_MERRYSVILLE_DEPTENTRANCE:
objectDef OBJ_TYPE::DOOR, $162, DIRECTIONS::UP, $1cc
doorArgDef $F, $D, DIRECTIONS::LEFT, $B6

OBJ_MERRYSVILLE_HOSPITALENTRANCE:
objectDef OBJ_TYPE::DOOR, $16e, DIRECTIONS::UP, $1c0
doorArgDef $12, $D, DIRECTIONS::LEFT, $146

OBJ_MERRYSVILLE_HOTELENTRANCE:
objectDef OBJ_TYPE::DOOR, $16b, DIRECTIONS::UP, $1cc
doorArgDef $12, $2DD, DIRECTIONS::LEFT, $3D6

OBJ_MERRYSVILLE_BURGERENTRANCE:
objectDef OBJ_TYPE::DOOR, $163, DIRECTIONS::UP, $1c0
doorArgDef $F, $D, DIRECTIONS::LEFT, $F6

OBJ_MERRYSVILLE_SCHOOLENTRANCE:
objectDef OBJ_TYPE::DOOR, $169, DIRECTIONS::UP, $1e5
doorArgDef $E, $305, DIRECTIONS::DOWN, $3B5

OBJ_MERRYSVILLE_UNIONENTRANCE:
objectDef OBJ_TYPE::DOOR, $141, DIRECTIONS::UP, $14e
doorArgDef $F, $291, DIRECTIONS::DOWN, $3C5

OBJ_MERRYSVILLE_RUMORGUY:
objectDef OBJ_TYPE::WANDERING_NPC, $14d, DIRECTIONS::RIGHT, $19d
.addr SPRITEDEF_MAN ;sprite
OBJ_IS_NOT_TALKING @JTALK0-OBJ_MERRYSVILLE_RUMORGUY
OBJ_DIALOGUE UMSG::MERRYSVILLE_RUMORGUY1
OBJ_YESNO_IS_NO @JYESNO1-OBJ_MERRYSVILLE_RUMORGUY
OBJ_DIALOGUE UMSG::MERRYSVILLE_RUMORGUY2
OBJ_STOP
    @JYESNO1:
OBJ_DIALOGUE UMSG::PODUNK_CANARYGIRL2
    @JTALK0:
OBJ_STOP

OBJ_MERRYSVILLE_COP:
objectDef OBJ_TYPE::WANDERING_NPC, $15f, DIRECTIONS::LEFT, $1bd
.addr SPRITEDEF_COP ;sprite
OBJ_IS_NOT_TALKING @JTALK0-OBJ_MERRYSVILLE_COP
OBJ_DIALOGUE UMSG::MERRYSVILLE_COP
    @JTALK0:
OBJ_STOP

OBJ_MERRYSVILLE_DUNCANGUY:
objectDef OBJ_TYPE::WANDERING_NPC, $154, DIRECTIONS::LEFT, $1d2
.addr SPRITEDEF_MOUSTACHE_GUY ;sprite
OBJ_IS_NOT_TALKING @JTALK0-OBJ_MERRYSVILLE_DUNCANGUY
OBJ_DIALOGUE UMSG::MERRYSVILLE_DUNCANGUY
    @JTALK0:
OBJ_STOP

OBJ_MERRYSVILLE_BEATUPGUY:
objectDef OBJ_TYPE::WANDERING_NPC, $159, DIRECTIONS::DOWN, $1de
.addr SPRITEDEF_COOL_GUY ;sprite
OBJ_IS_NOT_TALKING @JTALK0-OBJ_MERRYSVILLE_BEATUPGUY
OBJ_DIALOGUE UMSG::MERRYSVILLE_BEATUPGUY
    @JTALK0:
OBJ_STOP

OBJ_MERRYSVILLE_CURFEWGUY:
objectDef OBJ_TYPE::WANDERING_NPC, $15b, DIRECTIONS::RIGHT, $1de
.addr SPRITEDEF_BIGLADY ;sprite
OBJ_IS_NOT_TALKING @JTALK0-OBJ_MERRYSVILLE_CURFEWGUY
OBJ_DIALOGUE UMSG::MERRYSVILLE_CURFEWGUY
    @JTALK0:
OBJ_STOP

OBJ_MERRYSVILLE_TRAINWOMAN:
objectDef OBJ_TYPE::WANDERING_NPC, $16a, DIRECTIONS::DOWN, $1c2
.addr SPRITEDEF_OLD_WOMAN ;sprite
OBJ_IS_NOT_TALKING @JTALK0-OBJ_MERRYSVILLE_TRAINWOMAN
OBJ_IS_NOT_FLAG $71, @FJJUMP1-OBJ_MERRYSVILLE_TRAINWOMAN
OBJ_DIALOGUE UMSG::MERRYSVILLE_TRAINWOMAN
OBJ_STOP
    @FJJUMP1:
OBJ_DIALOGUE UMSG::MERRYSVILLE_TRAINWOMAN2
    @JTALK0:
OBJ_STOP

OBJ_MERRYSVILLE_NINTENDOGIRL:
objectDef OBJ_TYPE::WANDERING_NPC, $170, DIRECTIONS::DOWN, $1d0
.addr SPRITEDEF_SECRETARY ;sprite
OBJ_IS_NOT_TALKING @JTALK0-OBJ_MERRYSVILLE_NINTENDOGIRL
OBJ_DIALOGUE UMSG::MERRYSVILLE_NINTENDOGIRL
    @JTALK0:
OBJ_STOP

OBJ_MERRYSVILLE_HAPPYGUY:
objectDef OBJ_TYPE::WANDERING_NPC, $174, DIRECTIONS::RIGHT, $1d6
.addr SPRITEDEF_COOL_GUY ;sprite
OBJ_IS_NOT_TALKING @JTALK0-OBJ_MERRYSVILLE_HAPPYGUY
OBJ_DIALOGUE UMSG::MERRYSVILLE_HAPPYGUY
    @JTALK0:
OBJ_STOP

OBJ_MERRYSVILLE_STRIPGIRL:
objectDef OBJ_TYPE::WANDERING_NPC, $166, DIRECTIONS::LEFT, $1ce
.addr SPRITEDEF_WOMAN ;sprite
OBJ_IS_NOT_TALKING @JTALK0-OBJ_MERRYSVILLE_STRIPGIRL
OBJ_DIALOGUE UMSG::MERRYSVILLE_STRIPGIRL
    @JTALK0:
OBJ_STOP

OBJ_MERRYSVILLE_DOCTORGUY:
objectDef OBJ_TYPE::WANDERING_NPC, $173, DIRECTIONS::LEFT, $1c2
.addr SPRITEDEF_SUIT_GUY ;sprite
OBJ_IS_NOT_TALKING @JTALK0-OBJ_MERRYSVILLE_DOCTORGUY
OBJ_DIALOGUE UMSG::MERRYSVILLE_DOCTORGUY
    @JTALK0:
OBJ_STOP

OBJ_MERRYSVILLE_QUESTIONNAIRE:
objectDef OBJ_TYPE::WANDERING_NPC, $168, DIRECTIONS::DOWN, $1c6
.addr SPRITEDEF_MAN ;sprite
OBJ_IS_NOT_TALKING @JTALK0-OBJ_MERRYSVILLE_QUESTIONNAIRE
OBJ_IS_NOT_FLAG $6F, @FJJUMP1-OBJ_MERRYSVILLE_QUESTIONNAIRE
OBJ_DIALOGUE UMSG::MERRYSVILLE_QUESTIONNAIRE_DONE
OBJ_STOP
    @FJJUMP1:
OBJ_DIALOGUE UMSG::MERRYSVILLE_QUESTIONNAIRE
OBJ_YESNO_IS_NO @JYESNO2-OBJ_MERRYSVILLE_QUESTIONNAIRE
OBJ_DIALOGUE UMSG::MERRYSVILLE_QUESTIONNAIRE_Q1
OBJ_YESNO_IS_NO @JYESNO3-OBJ_MERRYSVILLE_QUESTIONNAIRE
    @JYESNO3:
OBJ_DIALOGUE UMSG::MERRYSVILLE_QUESTIONNAIRE_Q2
OBJ_YESNO_IS_NO @JYESNO4-OBJ_MERRYSVILLE_QUESTIONNAIRE
    @JYESNO4:
OBJ_DIALOGUE UMSG::MERRYSVILLE_QUESTIONNAIRE_FINISH
OBJ_NOT_HAS_ITEM $0, @IJHASITEM5-OBJ_MERRYSVILLE_QUESTIONNAIRE
OBJ_PICK_ITEM $2
OBJ_GIVE_ITEM @JTALK0-OBJ_MERRYSVILLE_QUESTIONNAIRE
OBJ_RESET_COUNTER $4
    @CNJCOMPCOUNTER6:
OBJ_INCREMENT_COUNTER $4
OBJ_COUNTERLESSTHAN $4, $32, @CNJCOMPCOUNTER6-OBJ_MERRYSVILLE_QUESTIONNAIRE
OBJ_PLAY_SOUND $6
OBJ_SET_FLAG $6F
OBJ_STOP
    @IJHASITEM5:
OBJ_DIALOGUE UMSG::MERRYSVILLE_QUESTIONNAIRE_NOROOM
OBJ_STOP
    @JYESNO2:
OBJ_DIALOGUE UMSG::MERRYSVILLE_QUESTIONNAIRE_DECLINE
    @JTALK0:
OBJ_STOP

OBJ_MERRYSVILLE_SCHOOLGUY:
objectDef OBJ_TYPE::WANDERING_NPC, $150, DIRECTIONS::UP, $1a8
.addr SPRITEDEF_COOL_GUY ;sprite
OBJ_IS_NOT_TALKING @JTALK0-OBJ_MERRYSVILLE_SCHOOLGUY
OBJ_DIALOGUE UMSG::MERRYSVILLE_SCHOOLGUY
    @JTALK0:
OBJ_STOP

OBJ_MERRYSVILLE_MAYORGUY:
objectDef OBJ_TYPE::WANDERING_NPC, $157, DIRECTIONS::UP, $1aa
.addr SPRITEDEF_MAN ;sprite
OBJ_IS_NOT_TALKING @JTALK0-OBJ_MERRYSVILLE_MAYORGUY
OBJ_IS_NOT_FLAG $71, @FJJUMP1-OBJ_MERRYSVILLE_MAYORGUY
OBJ_DIALOGUE UMSG::MERRYSVILLE_TRAINWOMAN
OBJ_STOP
    @FJJUMP1:
OBJ_DIALOGUE UMSG::MERRYSVILLE_MAYORGUY
    @JTALK0:
OBJ_STOP

OBJ_MERRYSVILLE_ROCKETGUY:
objectDef OBJ_TYPE::WANDERING_NPC, $160, DIRECTIONS::DOWN, $1ad
.addr SPRITEDEF_BIGLADY ;sprite
OBJ_IS_NOT_TALKING @JTALK0-OBJ_MERRYSVILLE_ROCKETGUY
OBJ_DIALOGUE UMSG::MERRYSVILLE_ROCKETGUY
    @JTALK0:
OBJ_STOP

OBJ_MERRYSVILLE_ORDINARYGUY:
objectDef OBJ_TYPE::WANDERING_NPC, $15c, DIRECTIONS::RIGHT, $1c2
.addr SPRITEDEF_MOUSTACHE_GUY ;sprite
OBJ_IS_NOT_TALKING @JTALK0-OBJ_MERRYSVILLE_ORDINARYGUY
OBJ_DIALOGUE UMSG::MERRYSVILLE_ORDINARYGUY
    @JTALK0:
OBJ_STOP

OBJ_MERRYSVILLE_THINKINGGUY:
objectDef OBJ_TYPE::WANDERING_NPC, $162, DIRECTIONS::DOWN, $1ce
.addr SPRITEDEF_MAN ;sprite
OBJ_IS_NOT_TALKING @JTALK0-OBJ_MERRYSVILLE_THINKINGGUY
OBJ_IS_NOT_FLAG $71, @FJJUMP1-OBJ_MERRYSVILLE_THINKINGGUY
OBJ_DIALOGUE UMSG::MERRYSVILLE_TRAINWOMAN
OBJ_STOP
    @FJJUMP1:
OBJ_DIALOGUE UMSG::MERRYSVILLE_THINKINGGUY
    @JTALK0:
OBJ_STOP

OBJ_MERRYSVILLE_HUSBANDGIRL:
objectDef OBJ_TYPE::WANDERING_NPC, $150, DIRECTIONS::LEFT, $1c4
.addr SPRITEDEF_SECRETARY ;sprite
OBJ_IS_NOT_TALKING @JTALK0-OBJ_MERRYSVILLE_HUSBANDGIRL
OBJ_DIALOGUE UMSG::MERRYSVILLE_HUSBANDGIRL
    @JTALK0:
OBJ_STOP

OBJ_MERRYSVILLE_SWEETSGUY:
objectDef OBJ_TYPE::WANDERING_NPC, $153, DIRECTIONS::DOWN, $1b6
.addr SPRITEDEF_COOL_GUY ;sprite
OBJ_IS_NOT_TALKING @JTALK0-OBJ_MERRYSVILLE_SWEETSGUY
OBJ_DIALOGUE UMSG::MERRYSVILLE_SWEETSGUY
OBJ_YESNO_IS_NO @JYESNO1-OBJ_MERRYSVILLE_SWEETSGUY
OBJ_DIALOGUE UMSG::MERRYSVILLE_SWEETSGUY_YES
OBJ_STOP
    @JYESNO1:
OBJ_DIALOGUE UMSG::PODUNK_CANARYGIRL2
    @JTALK0:
OBJ_STOP

OBJ_MERRYSVILLE_MONSTERGIRL:
objectDef OBJ_TYPE::WANDERING_NPC, $14f, DIRECTIONS::LEFT, $1c0
.addr SPRITEDEF_PIGPEN ;sprite
OBJ_IS_NOT_TALKING @JTALK0-OBJ_MERRYSVILLE_MONSTERGIRL
OBJ_DIALOGUE UMSG::MERRYSVILLE_MONSTERGIRL
    @JTALK0:
OBJ_STOP

OBJ_MERRYSVILLE_HOSPITALSIGN:
objectDef $19, $16d, DIRECTIONS::UP, $1c1
.addr SPRITEDEF_SIGN ;sprite
OBJ_IS_NOT_CHECKING @JCHECK0-OBJ_MERRYSVILLE_HOSPITALSIGN
OBJ_DIALOGUE UMSG::MERRYSVILLE_HOSPITALSIGN
    @JCHECK0:
OBJ_STOP

OBJ_MERRYSVILLE_SIGN:
objectDef $19, $14a, DIRECTIONS::UP, $19d
.addr SPRITEDEF_SIGN ;sprite
OBJ_IS_NOT_CHECKING @JCHECK0-OBJ_MERRYSVILLE_SIGN
OBJ_DIALOGUE UMSG::MERRYSVILLE_SIGN
    @JCHECK0:
OBJ_STOP

OBJ_MERRYSVILLE_DUNCANSIGN:
objectDef $19, $174, DIRECTIONS::UP, $1cd
.addr SPRITEDEF_SIGN ;sprite
OBJ_IS_NOT_CHECKING @JCHECK0-OBJ_MERRYSVILLE_DUNCANSIGN
OBJ_DIALOGUE UMSG::MERRYSVILLE_DUNCANSIGN
    @JCHECK0:
OBJ_STOP

OBJ_MERRYSVILLE_SCHOOLSIGN:
objectDef $19, $169, DIRECTIONS::UP, $1d0
.addr SPRITEDEF_SIGN ;sprite
OBJ_IS_NOT_CHECKING @JCHECK0-OBJ_MERRYSVILLE_SCHOOLSIGN
OBJ_DIALOGUE UMSG::MERRYSVILLE_SCHOOLSIGN
    @JCHECK0:
OBJ_STOP

OBJ_MERRYSVILLE_TELEPORTGAIN1:
objectDef $29, $157, DIRECTIONS::UP, $1cb
teleportFlagDef 2, $1D
OBJ_STOP
OBJ_MERRYSVILLE_TELEPORTGAIN2:
objectDef $29, $165, DIRECTIONS::UP, $1cb
teleportFlagDef 2, $1D
OBJ_STOP
OBJ_MERRYSVILLE_TELEPORTGAIN3:
objectDef $29, $173, DIRECTIONS::UP, $1cb
teleportFlagDef 2, $1D
OBJ_STOP
OBJ_MERRYSVILLE_TELEPORTGAIN4:
objectDef $29, $157, DIRECTIONS::UP, $1bd
teleportFlagDef 2, $1D
OBJ_STOP
OBJ_MERRYSVILLE_TELEPORTGAIN5:
objectDef $29, $173, DIRECTIONS::UP, $1bd
teleportFlagDef 2, $1D
OBJ_STOP
OBJ_MERRYSVILLE_TELEPORTGAIN6:
objectDef $29, $157, DIRECTIONS::UP, $1af
teleportFlagDef 2, $1D
OBJ_STOP
OBJ_MERRYSVILLE_TELEPORTGAIN7:
objectDef $29, $173, DIRECTIONS::UP, $1af
teleportFlagDef 2, $1D
OBJ_STOP
OBJ_MERRYSVILLE_TELEPORTGAIN8:
objectDef $29, $157, DIRECTIONS::UP, $1a1
teleportFlagDef 2, $1D
OBJ_STOP
OBJ_MERRYSVILLE_TELEPORTGAIN9:
objectDef $29, $165, DIRECTIONS::UP, $1a1
teleportFlagDef 2, $1D
OBJ_STOP
OBJ_MERRYSVILLE_TELEPORTGAINA:
objectDef $29, $173, DIRECTIONS::UP, $1a1
teleportFlagDef 2, $1D
OBJ_STOP