OBJ_BANK_11:
.addr OBJ_SPOOKANE_RAILROADENTRANCE
.addr OBJ_SPOOKANE_HOSPITALENTRANCE
.addr OBJ_SPOOKANE_HOTELENTRANCE
.addr OBJ_SPOOKANE_STATIONENTRANCE
.addr OBJ_SPOOKANE_SIGN
.addr OBJ_SPOOKANE_MANSIONSIGN
.addr 0

OBJ_SPOOKANE_RAILROADENTRANCE:
objectDef OBJ_TYPE::DOOR, $2d2, DIRECTIONS::RIGHT, $33f
doorArgDef $0, $9, DIRECTIONS::RIGHT, $20A

OBJ_SPOOKANE_HOSPITALENTRANCE:
objectDef OBJ_TYPE::DOOR, $2a7, DIRECTIONS::UP, $354
doorArgDef $12, $25D, DIRECTIONS::LEFT, $3D6

OBJ_SPOOKANE_HOTELENTRANCE:
objectDef OBJ_TYPE::DOOR, $2a7, DIRECTIONS::UP, $36c
doorArgDef $11, $D, DIRECTIONS::LEFT, $E6

OBJ_SPOOKANE_STATIONENTRANCE:
objectDef OBJ_TYPE::DOOR, $2a9, DIRECTIONS::UP, $33e
doorArgDef $F, $291, DIRECTIONS::DOWN, $3E5

OBJ_SPOOKANE_SIGN:
objectDef $19, $2ae, DIRECTIONS::UP, $355
.addr SPRITEDEF_SIGN ;sprite
OBJ_IS_NOT_CHECKING @JCHECK0-OBJ_SPOOKANE_SIGN
OBJ_DIALOGUE UMSG::SPOOKANE_SIGN
    @JCHECK0:
OBJ_STOP

OBJ_SPOOKANE_MANSIONSIGN:
objectDef $19, $2f5, DIRECTIONS::UP, $344
.addr SPRITEDEF_SIGN ;sprite
OBJ_IS_NOT_CHECKING @JCHECK0-OBJ_SPOOKANE_MANSIONSIGN
OBJ_DIALOGUE UMSG::SPOOKANE_MANSIONSIGN
    @JCHECK0:
OBJ_STOP