
;debating on whether or not to give every single npc a unique name.
;we'll see

OBJ_BANK_2:
.addr OBJ_PODUNK_DEPTENTRANCE
.addr OBJ_PODUNK_CITYHALLENTRANCE
.addr OBJ_PODUNK_HOTELENTRANCE
.addr OBJ_PODUNK_HOSPITALENTRANCE
.addr OBJ_PODUNK_BURGERENTRANCE
.addr OBJ_PODUNK_CHURCHENTRANCE
.addr OBJ_PODUNK_CEMETERYGUY
.addr OBJ_PODUNK_SCAREDGUY
.addr OBJ_PODUNK_NECROMANCERWOMAN
.addr OBJ_PODUNK_WARYGUY
.addr OBJ_PODUNK_CANARYGIRL
.addr OBJ_PODUNK_MAYORGUY
.addr OBJ_PODUNK_CONCERNEDGUY
.addr OBJ_PODUNK_SENSIBLEGUY
.addr OBJ_PODUNK_EVENTGIRL
.addr OBJ_PODUNK_POLTERGUY
.addr OBJ_PODUNK_ZOOGUY
.addr OBJ_PODUNK_BREADGIRL
.addr OBJ_PODUNK_CASHCARDWOMAN
.addr OBJ_PODUNK_ZOMBIE
.addr OBJ_PODUNK_ZOMBIE2
.addr OBJ_PODUNK_CANARYGUY
.addr OBJ_PODUNK_SHYGUY
.addr OBJ_PODUNK_ASTHMAGIRL
.addr OBJ_PODUNK_NOISYMOUSEENTRANCE
.addr OBJ_PODUNK_CANARYSIGN
.addr OBJ_PODUNK_CITYHALLSIGN
.addr OBJ_PODUNK_SIGN
.addr OBJ_PODUNK_TELEPORTGAIN1
.addr OBJ_PODUNK_TELEPORTGAIN2
.addr OBJ_PODUNK_TELEPORTGAIN3
.addr OBJ_PODUNK_TELEPORTGAIN4
.addr OBJ_PODUNK_TELEPORTGAIN5
.addr OBJ_PODUNK_TELEPORTGAIN6
.addr 0

OBJ_PODUNK_DEPTENTRANCE:
objectDef OBJ_TYPE::DOOR, $c2, DIRECTIONS::UP, $1b0
doorArgDef $F, $D, DIRECTIONS::LEFT, $116

OBJ_PODUNK_CITYHALLENTRANCE:
objectDef OBJ_TYPE::DOOR, $bb, DIRECTIONS::UP, $1b0
doorArgDef $F, $2BD, DIRECTIONS::LEFT, $96

OBJ_PODUNK_HOTELENTRANCE:
objectDef OBJ_TYPE::DOOR, $c7, DIRECTIONS::UP, $1a4
doorArgDef $12, $25D, DIRECTIONS::LEFT, $3B6

OBJ_PODUNK_HOSPITALENTRANCE:
objectDef OBJ_TYPE::DOOR, $bf, DIRECTIONS::UP, $1bc
doorArgDef $12, $31D, DIRECTIONS::LEFT, $3F6

OBJ_PODUNK_BURGERENTRANCE:
objectDef OBJ_TYPE::DOOR, $b7, DIRECTIONS::UP, $1b0
doorArgDef $F, $D, DIRECTIONS::LEFT, $156

OBJ_PODUNK_CHURCHENTRANCE:
objectDef OBJ_TYPE::DOOR, $9d, DIRECTIONS::UP, $1ef
doorArgDef $12, $D, DIRECTIONS::LEFT, $C6

OBJ_PODUNK_CEMETERYGUY:
objectDef OBJ_TYPE::WANDERING_NPC, $c8, DIRECTIONS::RIGHT, $193
.addr SPRITEDEF_8A ;sprite
OBJ_IS_NOT_TALKING  OBJ_PODUNK_CEMETERYGUY_JTALK0-OBJ_PODUNK_CEMETERYGUY
OBJ_IS_NOT_FLAG  $B, OBJ_PODUNK_CEMETERYGUY_FJJUMP1-OBJ_PODUNK_CEMETERYGUY
OBJ_DIALOGUE UMSG::PODUNK_CEMETERYGUY2
OBJ_STOP
    OBJ_PODUNK_CEMETERYGUY_FJJUMP1:
OBJ_DIALOGUE UMSG::PODUNK_CEMETERYGUY1
    OBJ_PODUNK_CEMETERYGUY_JTALK0:
OBJ_STOP

OBJ_PODUNK_SCAREDGUY:
objectDef OBJ_TYPE::STATIONARY_NPC, $d6, DIRECTIONS::DOWN, $1a9
.addr SPRITEDEF_8A ;sprite
OBJ_IS_NOT_TALKING  OBJ_PODUNK_SCAREDGUY_JTALK0-OBJ_PODUNK_SCAREDGUY
OBJ_IS_NOT_FLAG  $B, OBJ_PODUNK_SCAREDGUY_FJJUMP1-OBJ_PODUNK_SCAREDGUY
OBJ_DIALOGUE UMSG::PODUNK_SCAREDGUY7
OBJ_STOP
    OBJ_PODUNK_SCAREDGUY_FJJUMP1:
OBJ_DIALOGUE UMSG::PODUNK_SCAREDGUY1
OBJ_YESNO_IS_NO  OBJ_PODUNK_SCAREDGUY_JYESNO2-OBJ_PODUNK_SCAREDGUY
OBJ_DIALOGUE UMSG::PODUNK_SCAREDGUY2
OBJ_CHANGE_TYPE $26
OBJ_STOP
    OBJ_PODUNK_SCAREDGUY_JYESNO2:
OBJ_DIALOGUE UMSG::PODUNK_SCAREDGUY3
OBJ_YESNO_IS_NO  OBJ_PODUNK_SCAREDGUY_JYESNO3-OBJ_PODUNK_SCAREDGUY
OBJ_DIALOGUE UMSG::PODUNK_SCAREDGUY4
OBJ_STOP
    OBJ_PODUNK_SCAREDGUY_JYESNO3:
OBJ_DIALOGUE UMSG::PODUNK_SCAREDGUY5
OBJ_DIALOGUE UMSG::PODUNK_SCAREDGUY6
    OBJ_PODUNK_SCAREDGUY_JTALK0:
OBJ_STOP

OBJ_PODUNK_NECROMANCERWOMAN:
objectDef OBJ_TYPE::WANDERING_NPC, $d0, DIRECTIONS::DOWN, $19a
.addr SPRITEDEF_A2 ;sprite
OBJ_IS_NOT_TALKING  OBJ_PODUNK_NECROMANCERWOMAN_JTALK0-OBJ_PODUNK_NECROMANCERWOMAN
OBJ_IS_NOT_FLAG  $B, OBJ_PODUNK_NECROMANCERWOMAN_FJJUMP1-OBJ_PODUNK_NECROMANCERWOMAN
OBJ_DIALOGUE UMSG::PODUNK_NECROMANCERWOMAN2
OBJ_STOP
    OBJ_PODUNK_NECROMANCERWOMAN_FJJUMP1:
OBJ_DIALOGUE UMSG::PODUNK_NECROMANCERWOMAN1
    OBJ_PODUNK_NECROMANCERWOMAN_JTALK0:
OBJ_STOP

OBJ_PODUNK_WARYGUY:
objectDef OBJ_TYPE::WANDERING_NPC, $d5, DIRECTIONS::RIGHT, $1a6
.addr SPRITEDEF_6A ;sprite
OBJ_IS_NOT_TALKING  OBJ_PODUNK_WARYGUY_JTALK0-OBJ_PODUNK_WARYGUY
OBJ_IS_NOT_FLAG  $B, OBJ_PODUNK_WARYGUY_FJJUMP1-OBJ_PODUNK_WARYGUY
OBJ_DIALOGUE UMSG::PODUNK_CEMETERYGUY2
OBJ_STOP
    OBJ_PODUNK_WARYGUY_FJJUMP1:
OBJ_DIALOGUE UMSG::PODUNK_WARYGUY
    OBJ_PODUNK_WARYGUY_JTALK0:
OBJ_STOP

OBJ_PODUNK_CANARYGIRL:
objectDef OBJ_TYPE::WANDERING_NPC, $c7, DIRECTIONS::LEFT, $1b3
.addr SPRITEDEF_AA ;sprite
OBJ_IS_NOT_TALKING  OBJ_PODUNK_CANARYGIRL_JTALK0-OBJ_PODUNK_CANARYGIRL
OBJ_IS_NOT_FLAG  $C, OBJ_PODUNK_CANARYGIRL_FJJUMP1-OBJ_PODUNK_CANARYGIRL
OBJ_JUMP  OBJ_PODUNK_CANARYGIRL_JJUMP2-OBJ_PODUNK_CANARYGIRL
    OBJ_PODUNK_CANARYGIRL_FJJUMP1:
OBJ_NOT_HAS_ITEM  $5F, OBJ_PODUNK_CANARYGIRL_JJUMP2-OBJ_PODUNK_CANARYGIRL
OBJ_DIALOGUE UMSG::PODUNK_CANARYGIRL1
OBJ_YESNO_IS_NO  OBJ_PODUNK_CANARYGIRL_JYESNO3-OBJ_PODUNK_CANARYGIRL
OBJ_DIALOGUE UMSG::PODUNK_CANARYGIRL2
OBJ_STOP
    OBJ_PODUNK_CANARYGIRL_JYESNO3:
OBJ_DIALOGUE UMSG::PODUNK_CANARYGIRL3
OBJ_STOP
    OBJ_PODUNK_CANARYGIRL_JJUMP2:
OBJ_DIALOGUE UMSG::PODUNK_CANARYGIRL4
    OBJ_PODUNK_CANARYGIRL_JTALK0:
OBJ_STOP

OBJ_PODUNK_MAYORGUY:
objectDef OBJ_TYPE::WANDERING_NPC, $b4, DIRECTIONS::RIGHT, $1b6
.addr SPRITEDEF_B2 ;sprite
OBJ_IS_NOT_TALKING  OBJ_PODUNK_MAYORGUY_JTALK0-OBJ_PODUNK_MAYORGUY
OBJ_DIALOGUE UMSG::PODUNK_MAYORGUY
    OBJ_PODUNK_MAYORGUY_JTALK0:
OBJ_STOP

OBJ_PODUNK_CONCERNEDGUY:
objectDef OBJ_TYPE::WANDERING_NPC, $b2, DIRECTIONS::DOWN, $1c4
.addr SPRITEDEF_7A ;sprite
OBJ_IS_NOT_TALKING  OBJ_PODUNK_CONCERNEDGUY_JTALK0-OBJ_PODUNK_CONCERNEDGUY
OBJ_DIALOGUE UMSG::PODUNK_CONCERNEDGUY
    OBJ_PODUNK_CONCERNEDGUY_JTALK0:
OBJ_STOP

OBJ_PODUNK_SENSIBLEGUY:
objectDef OBJ_TYPE::WANDERING_NPC, $d1, DIRECTIONS::DOWN, $1ce
.addr SPRITEDEF_6A ;sprite
OBJ_IS_NOT_TALKING  OBJ_PODUNK_SENSIBLEGUY_JTALK0-OBJ_PODUNK_SENSIBLEGUY
OBJ_IS_NOT_FLAG  $B, OBJ_PODUNK_SENSIBLEGUY_FJJUMP1-OBJ_PODUNK_SENSIBLEGUY
OBJ_DIALOGUE UMSG::PODUNK_CEMETERYGUY2
OBJ_STOP
    OBJ_PODUNK_SENSIBLEGUY_FJJUMP1:
OBJ_DIALOGUE UMSG::PODUNK_SENSIBLEGUY1
OBJ_YESNO_IS_NO  OBJ_PODUNK_SENSIBLEGUY_JYESNO2-OBJ_PODUNK_SENSIBLEGUY
    OBJ_PODUNK_SENSIBLEGUY_JYESNO2:
OBJ_DIALOGUE UMSG::PODUNK_SENSIBLEGUY2
    OBJ_PODUNK_SENSIBLEGUY_JTALK0:
OBJ_STOP

OBJ_PODUNK_EVENTGIRL:
objectDef OBJ_TYPE::WANDERING_NPC, $be, DIRECTIONS::RIGHT, $1a6
.addr SPRITEDEF_92 ;sprite
OBJ_IS_NOT_TALKING  OBJ_PODUNK_EVENTGIRL_JTALK0-OBJ_PODUNK_EVENTGIRL
OBJ_IS_NOT_FLAG  $D, OBJ_PODUNK_EVENTGIRL_FJJUMP1-OBJ_PODUNK_EVENTGIRL
OBJ_DIALOGUE UMSG::PODUNK_EVENTGIRL2
OBJ_STOP
    OBJ_PODUNK_EVENTGIRL_FJJUMP1:
OBJ_DIALOGUE UMSG::PODUNK_EVENTGIRL1
    OBJ_PODUNK_EVENTGIRL_JTALK0:
OBJ_STOP

OBJ_PODUNK_POLTERGUY:
objectDef OBJ_TYPE::WANDERING_NPC, $b6, DIRECTIONS::RIGHT, $18a
.addr SPRITEDEF_7A ;sprite
OBJ_IS_NOT_TALKING  OBJ_PODUNK_POLTERGUY_JTALK0-OBJ_PODUNK_POLTERGUY
OBJ_IS_NOT_FLAG  $B, OBJ_PODUNK_POLTERGUY_FJJUMP1-OBJ_PODUNK_POLTERGUY
OBJ_DIALOGUE UMSG::PODUNK_SCAREDGUY7
OBJ_STOP
    OBJ_PODUNK_POLTERGUY_FJJUMP1:
OBJ_DIALOGUE UMSG::PODUNK_POLTERGUY
    OBJ_PODUNK_POLTERGUY_JTALK0:
OBJ_STOP

OBJ_PODUNK_ZOOGUY:
objectDef OBJ_TYPE::WANDERING_NPC, $d0, DIRECTIONS::RIGHT, $1b7
.addr SPRITEDEF_9A ;sprite
OBJ_IS_NOT_TALKING  OBJ_PODUNK_ZOOGUY_JTALK0-OBJ_PODUNK_ZOOGUY
OBJ_IS_NOT_FLAG  $D, OBJ_PODUNK_ZOOGUY_FJJUMP1-OBJ_PODUNK_ZOOGUY
OBJ_DIALOGUE UMSG::PODUNK_CEMETERYGUY2
OBJ_STOP
    OBJ_PODUNK_ZOOGUY_FJJUMP1:
OBJ_DIALOGUE UMSG::PODUNK_ZOOGUY
    OBJ_PODUNK_ZOOGUY_JTALK0:
OBJ_STOP

OBJ_PODUNK_BREADGIRL:
objectDef OBJ_TYPE::WANDERING_NPC, $d0, DIRECTIONS::DOWN, $1b9
.addr SPRITEDEF_92 ;sprite
OBJ_IS_NOT_TALKING  OBJ_PODUNK_BREADGIRL_JTALK0-OBJ_PODUNK_BREADGIRL
OBJ_DIALOGUE UMSG::PODUNK_BREADGIRL
    OBJ_PODUNK_BREADGIRL_JTALK0:
OBJ_STOP

OBJ_PODUNK_CASHCARDWOMAN:
objectDef OBJ_TYPE::WANDERING_NPC, $ca, DIRECTIONS::DOWN, $1b0
.addr SPRITEDEF_A2 ;sprite
OBJ_IS_NOT_TALKING  OBJ_PODUNK_CASHCARDWOMAN_JTALK0-OBJ_PODUNK_CASHCARDWOMAN
OBJ_DIALOGUE UMSG::PODUNK_CASHCARDWOMAN
    OBJ_PODUNK_CASHCARDWOMAN_JTALK0:
OBJ_STOP

OBJ_PODUNK_ZOMBIE:
objectDef OBJ_TYPE::WANDERING_NPC_CHECKSPAWN, $cb, DIRECTIONS::LEFT, $1d3
.addr SPRITEDEF_8A ;sprite
OBJ_FLAG_DISAPPEAR  $14
OBJ_IS_NOT_TALKING  OBJ_PODUNK_ZOMBIE_JTALK0-OBJ_PODUNK_ZOMBIE
OBJ_DIALOGUE UMSG::PODUNK_ZOMBIE
OBJ_BATTLE  $10
OBJ_SET_FLAG  $14
    OBJ_PODUNK_ZOMBIE_JTALK0:
OBJ_STOP

OBJ_PODUNK_ZOMBIE2:
objectDef OBJ_TYPE::WANDERING_NPC_CHECKSPAWN, $d5, DIRECTIONS::DOWN, $1d5
.addr SPRITEDEF_8A ;sprite
OBJ_FLAG_DISAPPEAR  $15
OBJ_IS_NOT_TALKING  OBJ_PODUNK_ZOMBIE2_JTALK0-OBJ_PODUNK_ZOMBIE2
OBJ_DIALOGUE UMSG::PODUNK_ZOMBIE2
OBJ_BATTLE  $10
OBJ_SET_FLAG  $15
    OBJ_PODUNK_ZOMBIE2_JTALK0:
OBJ_STOP

OBJ_PODUNK_CANARYGUY:
objectDef OBJ_TYPE::WANDERING_NPC, $b9, DIRECTIONS::LEFT, $1a8
.addr SPRITEDEF_9A ;sprite
OBJ_IS_NOT_TALKING  OBJ_PODUNK_CANARYGUY_JTALK0-OBJ_PODUNK_CANARYGUY
OBJ_DIALOGUE UMSG::PODUNK_CANARYGUY
    OBJ_PODUNK_CANARYGUY_JTALK0:
OBJ_STOP

OBJ_PODUNK_SHYGUY:
objectDef OBJ_TYPE::WANDERING_NPC, $bc, DIRECTIONS::RIGHT, $1b4
.addr SPRITEDEF_8A ;sprite
OBJ_IS_NOT_TALKING  OBJ_PODUNK_SHYGUY_JTALK0-OBJ_PODUNK_SHYGUY
OBJ_DIALOGUE UMSG::PODUNK_SHYGUY
    OBJ_PODUNK_SHYGUY_JTALK0:
OBJ_STOP

OBJ_PODUNK_ASTHMAGIRL:
objectDef OBJ_TYPE::WANDERING_NPC, $bb, DIRECTIONS::DOWN, $1be
.addr SPRITEDEF_82 ;sprite
OBJ_IS_NOT_TALKING  OBJ_PODUNK_ASTHMAGIRL_JTALK0-OBJ_PODUNK_ASTHMAGIRL
OBJ_DIALOGUE UMSG::PODUNK_ASTHMAGIRL
    OBJ_PODUNK_ASTHMAGIRL_JTALK0:
OBJ_STOP

OBJ_PODUNK_NOISYMOUSEENTRANCE:
objectDef OBJ_TYPE::DOOR, $bd, DIRECTIONS::UP, $18f
doorArgDef $12, $3AD, DIRECTIONS::LEFT, $106

OBJ_PODUNK_CANARYSIGN:
objectDef $19, $aa, DIRECTIONS::UP, $17b
.addr SPRITEDEF_65 ;sprite
OBJ_IS_NOT_CHECKING  OBJ_PODUNK_CANARYSIGN_JCHECK0-OBJ_PODUNK_CANARYSIGN
OBJ_DIALOGUE UMSG::PODUNK_CANARYSIGN
    OBJ_PODUNK_CANARYSIGN_JCHECK0:
OBJ_STOP

OBJ_PODUNK_CITYHALLSIGN:
objectDef $19, $ba, DIRECTIONS::UP, $1b1
.addr SPRITEDEF_65 ;sprite
OBJ_IS_NOT_CHECKING  OBJ_PODUNK_CITYHALLSIGN_JCHECK0-OBJ_PODUNK_CITYHALLSIGN
OBJ_DIALOGUE UMSG::PODUNK_CITYHALLSIGN
    OBJ_PODUNK_CITYHALLSIGN_JCHECK0:
OBJ_STOP

OBJ_PODUNK_SIGN:
objectDef $19, $c2, DIRECTIONS::UP, $17d
.addr SPRITEDEF_65 ;sprite
OBJ_IS_NOT_CHECKING  OBJ_PODUNK_SIGN_JCHECK0-OBJ_PODUNK_SIGN
OBJ_DIALOGUE UMSG::PODUNK_SIGN
    OBJ_PODUNK_SIGN_JCHECK0:
OBJ_STOP

OBJ_PODUNK_TELEPORTGAIN1:
objectDef $29, $b7, DIRECTIONS::UP, $1b7
teleportFlagDef 1, $1D
OBJ_STOP
OBJ_PODUNK_TELEPORTGAIN2:
objectDef $29, $c5, DIRECTIONS::UP, $1b7
teleportFlagDef 1, $1D
OBJ_STOP
OBJ_PODUNK_TELEPORTGAIN3:
objectDef $29, $d3, DIRECTIONS::UP, $1b7
teleportFlagDef 1, $1D
OBJ_STOP
OBJ_PODUNK_TELEPORTGAIN4:
objectDef $29, $b7, DIRECTIONS::UP, $1a9
teleportFlagDef 1, $1D
OBJ_STOP
OBJ_PODUNK_TELEPORTGAIN5:
objectDef $29, $c5, DIRECTIONS::UP, $1a9
teleportFlagDef 1, $1D
OBJ_STOP
OBJ_PODUNK_TELEPORTGAIN6:
objectDef $29, $d3, DIRECTIONS::UP, $1a9
teleportFlagDef 1, $1D
OBJ_STOP