OBJ_BANK_9:
.addr OBJ_YOUNGTOWN_FAKEHOTELENTRANCE
.addr OBJ_YOUNGTOWN_FAKEDEPTENTRANCE
.addr OBJ_ELLAY_RESTHOUSEENTRANCE
.addr OBJ_YOUNGTOWN_CHURCHENTRANCE
.addr OBJ_YOUNGTOWN_STATIONENTRANCE
.addr OBJ_YOUNGTOWN_BABYHOUSEENTRANCE
.addr OBJ_YOUNGTOWN_GUARD
.addr OBJ_YOUNGTOWN_MOMGIRL
.addr OBJ_YOUNGTOWN_BABYGIRL
.addr OBJ_YOUNGTOWN_DADGUY
.addr OBJ_YOUNGTOWN_SHIPGIRL
.addr OBJ_YOUNGTOWN_GROWNUPGUY
.addr OBJ_YOUNGTOWN_HOLDMEGUY
.addr OBJ_YOUNGTOWN_HOLDMEGIRL
.addr OBJ_YOUNGTOWN_HOLDMEGUY2
.addr OBJ_YOUNGTOWN_HOLDMEGIRL2
.addr OBJ_YOUNGTOWN_PLEASEGIRL
.addr OBJ_YOUNGTOWN_VOICEGUY
.addr OBJ_YOUNGTOWN_GUARD2
.addr OBJ_YOUNGTOWN_MATHGUY
.addr OBJ_YOUNGTOWN_PARENTGIRL
.addr OBJ_YOUNGTOWN_MUSICSWAP
.addr OBJ_YOUNGTOWN_MUSICSWAP2
.addr OBJ_YOUNGTOWN_MUSICSWAP3
.addr OBJ_YOUNGTOWN_MUSICSWAP4
.addr OBJ_YOUNGTOWN_SIGN
.addr OBJ_YOUNGTOWN_TELEPORTGAIN1
.addr 0

OBJ_YOUNGTOWN_FAKEHOTELENTRANCE:
objectDef OBJ_TYPE::DOOR, $2c9, DIRECTIONS::UP, $1bf
doorArgDef $0, $2BD, DIRECTIONS::LEFT, $3D6

OBJ_YOUNGTOWN_FAKEDEPTENTRANCE:
objectDef OBJ_TYPE::DOOR, $2cd, DIRECTIONS::UP, $1bf
doorArgDef $0, $2D, DIRECTIONS::LEFT, $116

OBJ_ELLAY_RESTHOUSEENTRANCE:
objectDef OBJ_TYPE::DOOR, $3a5, DIRECTIONS::UP, $177
doorArgDef $12, $25D, DIRECTIONS::LEFT, $3E6

OBJ_YOUNGTOWN_CHURCHENTRANCE:
objectDef OBJ_TYPE::DOOR, $2c5, DIRECTIONS::UP, $1cf
doorArgDef $0, $36D, DIRECTIONS::LEFT, $96

OBJ_YOUNGTOWN_STATIONENTRANCE:
objectDef OBJ_TYPE::DOOR, $2e9, DIRECTIONS::UP, $19e
doorArgDef $F, $2D1, DIRECTIONS::DOWN, $3E5

OBJ_YOUNGTOWN_BABYHOUSEENTRANCE:
objectDef OBJ_TYPE::DOOR, $2a2, DIRECTIONS::UP, $1c7
doorArgDef $0, $35D, DIRECTIONS::LEFT, $86

OBJ_YOUNGTOWN_GUARD:
objectDef OBJ_TYPE::STATIONARY_NPC, $2b6, DIRECTIONS::LEFT, $1b8
.addr SPRITEDEF_HEADBAND_KID_2 ;sprite
OBJ_IS_NOT_TALKING @JTALK0-OBJ_YOUNGTOWN_GUARD
OBJ_DIALOGUE UMSG::YOUNGTOWN_GUARD
OBJ_DIALOGUE UMSG::MYHOME_MINNIE_INVASION_FIGHT_2
    @JTALK0:
OBJ_STOP

OBJ_YOUNGTOWN_MOMGIRL:
objectDef OBJ_TYPE::WANDERING_NPC, $2ab, DIRECTIONS::RIGHT, $1c1
.addr SPRITEDEF_PONYTAIL_GIRL ;sprite
OBJ_IS_NOT_TALKING @JTALK0-OBJ_YOUNGTOWN_MOMGIRL
OBJ_DIALOGUE UMSG::YOUNGTOWN_MOMGIRL
    @JTALK0:
OBJ_STOP

OBJ_YOUNGTOWN_BABYGIRL:
objectDef OBJ_TYPE::WANDERING_NPC, $2d1, DIRECTIONS::DOWN, $1cb
.addr SPRITEDEF_PIGTAIL_GIRL_2 ;sprite
OBJ_IS_NOT_TALKING @JTALK0-OBJ_YOUNGTOWN_BABYGIRL
OBJ_DIALOGUE UMSG::YOUNGTOWN_BABYGIRL
    @JTALK0:
OBJ_STOP

OBJ_YOUNGTOWN_DADGUY:
objectDef OBJ_TYPE::WANDERING_NPC, $2ac, DIRECTIONS::UP, $1c4
.addr SPRITEDEF_CAP_KID ;sprite
OBJ_IS_NOT_TALKING @JTALK0-OBJ_YOUNGTOWN_DADGUY
OBJ_DIALOGUE UMSG::YOUNGTOWN_DADGUY
    @JTALK0:
OBJ_STOP

OBJ_YOUNGTOWN_SHIPGIRL:
objectDef OBJ_TYPE::WANDERING_NPC, $2be, DIRECTIONS::LEFT, $1e6
.addr SPRITEDEF_PONYTAIL_GIRL ;sprite
OBJ_IS_NOT_TALKING @JTALK0-OBJ_YOUNGTOWN_SHIPGIRL
OBJ_DIALOGUE UMSG::YOUNGTOWN_SHIPGIRL
    @JTALK0:
OBJ_STOP

OBJ_YOUNGTOWN_GROWNUPGUY:
objectDef OBJ_TYPE::WANDERING_NPC, $2ca, DIRECTIONS::LEFT, $1e0
.addr SPRITEDEF_CAP_KID ;sprite
OBJ_IS_NOT_TALKING @JTALK0-OBJ_YOUNGTOWN_GROWNUPGUY
OBJ_DIALOGUE UMSG::YOUNGTOWN_GROWNUPGUY
    @JTALK0:
OBJ_STOP

OBJ_YOUNGTOWN_HOLDMEGUY:
objectDef OBJ_TYPE::WANDERINGFAST_NPC, $2b4, DIRECTIONS::UP, $1d1
.addr SPRITEDEF_SMALLCAP_KID ;sprite
OBJ_IS_NOT_TALKING @JTALK0-OBJ_YOUNGTOWN_HOLDMEGUY
OBJ_DIALOGUE UMSG::YOUNGTOWN_HOLDMEGUY
    @JTALK0:
OBJ_STOP

OBJ_YOUNGTOWN_HOLDMEGIRL:
objectDef OBJ_TYPE::WANDERING_NPC, $2ba, DIRECTIONS::UP, $1d1
.addr SPRITEDEF_PIGTAIL_GIRL ;sprite
OBJ_IS_NOT_TALKING @JTALK0-OBJ_YOUNGTOWN_HOLDMEGIRL
OBJ_DIALOGUE UMSG::YOUNGTOWN_HOLDMEGIRL
    @JTALK0:
OBJ_STOP

OBJ_YOUNGTOWN_HOLDMEGUY2:
objectDef OBJ_TYPE::WANDERINGFAST_NPC, $2b7, DIRECTIONS::LEFT, $1d4
.addr SPRITEDEF_HEADBAND_KID ;sprite
OBJ_IS_NOT_TALKING @JTALK0-OBJ_YOUNGTOWN_HOLDMEGUY2
OBJ_DIALOGUE UMSG::YOUNGTOWN_HOLDMEGUY2
    @JTALK0:
OBJ_STOP

OBJ_YOUNGTOWN_HOLDMEGIRL2:
objectDef OBJ_TYPE::WANDERING_NPC, $2ba, DIRECTIONS::DOWN, $1d7
.addr SPRITEDEF_PIGTAIL_GIRL ;sprite
OBJ_IS_NOT_TALKING @JTALK0-OBJ_YOUNGTOWN_HOLDMEGIRL2
OBJ_DIALOGUE UMSG::YOUNGTOWN_HOLDMEGUY2
    @JTALK0:
OBJ_STOP

OBJ_YOUNGTOWN_PLEASEGIRL:
objectDef OBJ_TYPE::WANDERINGFAST_NPC, $2bc, DIRECTIONS::DOWN, $1c2
.addr SPRITEDEF_PONYTAIL_GIRL ;sprite
OBJ_IS_NOT_TALKING @JTALK0-OBJ_YOUNGTOWN_PLEASEGIRL
OBJ_DIALOGUE UMSG::YOUNGTOWN_PLEASEGIRL
    @JTALK0:
OBJ_STOP

OBJ_YOUNGTOWN_VOICEGUY:
objectDef OBJ_TYPE::WANDERINGFAST_NPC, $2aa, DIRECTIONS::RIGHT, $1ea
.addr SPRITEDEF_CAP_KID ;sprite
OBJ_IS_NOT_TALKING @JTALK0-OBJ_YOUNGTOWN_VOICEGUY
OBJ_DIALOGUE UMSG::YOUNGTOWN_VOICEGUY
    @JTALK0:
OBJ_STOP

OBJ_YOUNGTOWN_GUARD2:
objectDef OBJ_TYPE::STATIONARY_NPC, $2f5, DIRECTIONS::DOWN, $1d7
.addr SPRITEDEF_CAP_KID ;sprite
OBJ_IS_NOT_TALKING @JTALK0-OBJ_YOUNGTOWN_GUARD2
OBJ_DIALOGUE UMSG::YOUNGTOWN_GUARD2
    @JTALK0:
OBJ_STOP

OBJ_YOUNGTOWN_MATHGUY:
objectDef OBJ_TYPE::WANDERING_NPC, $2ca, DIRECTIONS::RIGHT, $1c3
.addr SPRITEDEF_CAP_KID ;sprite
OBJ_IS_NOT_TALKING @JTALK0-OBJ_YOUNGTOWN_MATHGUY
OBJ_DIALOGUE UMSG::YOUNGTOWN_MATHGUY
    @JTALK0:
OBJ_STOP

OBJ_YOUNGTOWN_PARENTGIRL:
objectDef OBJ_TYPE::WANDERING_NPC, $2a2, DIRECTIONS::DOWN, $1cd
.addr SPRITEDEF_PONYTAIL_GIRL ;sprite
OBJ_IS_NOT_TALKING @JTALK0-OBJ_YOUNGTOWN_PARENTGIRL
OBJ_DIALOGUE UMSG::YOUNGTOWN_PARENTGIRL
    @JTALK0:
OBJ_STOP

OBJ_YOUNGTOWN_MUSICSWAP:
objectDef OBJ_TYPE::TRIGGER, $2b5, DIRECTIONS::UP, $1b6
OBJ_IS_NOT_TOUCHING @JTOUCH0-OBJ_YOUNGTOWN_MUSICSWAP
OBJ_PLAY_MUSIC $8
    @JTOUCH0:
OBJ_STOP

OBJ_YOUNGTOWN_MUSICSWAP2:
objectDef OBJ_TYPE::TRIGGER, $2b5, DIRECTIONS::UP, $1b7
OBJ_IS_NOT_TOUCHING @JTOUCH0-OBJ_YOUNGTOWN_MUSICSWAP2
OBJ_PLAY_MUSIC $30
    @JTOUCH0:
OBJ_STOP

OBJ_YOUNGTOWN_MUSICSWAP3:
objectDef OBJ_TYPE::TRIGGER, $2f5, DIRECTIONS::UP, $1d8
OBJ_IS_NOT_TOUCHING @JTOUCH0-OBJ_YOUNGTOWN_MUSICSWAP3
OBJ_PLAY_MUSIC $6
    @JTOUCH0:
OBJ_STOP

OBJ_YOUNGTOWN_MUSICSWAP4:
objectDef OBJ_TYPE::TRIGGER, $2f4, DIRECTIONS::UP, $1d8
OBJ_IS_NOT_TOUCHING @JTOUCH0-OBJ_YOUNGTOWN_MUSICSWAP4
OBJ_PLAY_MUSIC $30
    @JTOUCH0:
OBJ_STOP

OBJ_YOUNGTOWN_SIGN:
objectDef $19, $2f4, DIRECTIONS::UP, $1d7
.addr SPRITEDEF_SIGN ;sprite
OBJ_IS_NOT_CHECKING @JCHECK0-OBJ_YOUNGTOWN_SIGN
OBJ_DIALOGUE UMSG::YOUNGTOWN_SIGN
    @JCHECK0:
OBJ_STOP

OBJ_YOUNGTOWN_TELEPORTGAIN1:
objectDef OBJ_TYPE::FLAGSET_SEE, $2b2, DIRECTIONS::UP, $1be
teleportFlagDef 6, $1D
OBJ_STOP