OBJ_BANK_B:
.addr OBJ_PODUNK_MERRYCOP
.addr OBJ_PODUNK_MERRYCOP2
.addr OBJ_PODUNK_GRAVESIGN
.addr OBJ_PODUNK_MERRYSIGN
.addr OBJ_PODUNK_ZOOSIGN
.addr 0

OBJ_PODUNK_MERRYCOP:
objectDef OBJ_TYPE::STATIONARY_NPC_CHECKSPAWN, $10d, DIRECTIONS::LEFT, $197
.addr SPRITEDEF_COP ;sprite
OBJ_FLAG_DISAPPEAR $77
OBJ_IS_NOT_TALKING @JTALK0-OBJ_PODUNK_MERRYCOP
OBJ_DIALOGUE UMSG::PODUNK_MERRYCOP
    @JTALK0:
OBJ_STOP

OBJ_PODUNK_MERRYCOP2:
objectDef OBJ_TYPE::STATIONARY_NPC_CHECKSPAWN, $10d, DIRECTIONS::LEFT, $198
.addr SPRITEDEF_COP ;sprite
OBJ_FLAG_DISAPPEAR $77
OBJ_IS_NOT_TALKING @JTALK0-OBJ_PODUNK_MERRYCOP2
OBJ_DIALOGUE UMSG::PODUNK_MERRYCOP
    @JTALK0:
OBJ_STOP

OBJ_PODUNK_GRAVESIGN:
objectDef $19, $bb, DIRECTIONS::UP, $1f3
.addr SPRITEDEF_SIGN ;sprite
OBJ_IS_NOT_CHECKING @JCHECK0-OBJ_PODUNK_GRAVESIGN
OBJ_DIALOGUE UMSG::PODUNK_GRAVESIGN
    @JCHECK0:
OBJ_STOP

OBJ_PODUNK_MERRYSIGN:
objectDef $19, $108, DIRECTIONS::UP, $195
.addr SPRITEDEF_SIGN ;sprite
OBJ_IS_NOT_CHECKING @JCHECK0-OBJ_PODUNK_MERRYSIGN
OBJ_DIALOGUE UMSG::PODUNK_MERRYSIGN
    @JCHECK0:
OBJ_STOP

OBJ_PODUNK_ZOOSIGN:
objectDef $19, $d2, DIRECTIONS::UP, $10b
.addr SPRITEDEF_SIGN ;sprite
OBJ_IS_NOT_CHECKING @JCHECK0-OBJ_PODUNK_ZOOSIGN
OBJ_DIALOGUE UMSG::PODUNK_ZOOSIGN
    @JCHECK0:
OBJ_STOP