OBJ_BANK_11:
.word OBJ_SPOOKANE_RAILROADENTRANCE
.word OBJ_SPOOKANE_HOSPITALENTRANCE
.word OBJ_SPOOKANE_HOTELENTRANCE
.word OBJ_SPOOKANE_STATIONENTRANCE
.word OBJ_SPOOKANE_SIGN
.word OBJ_SPOOKANE_MANSIONSIGN
.word 0

OBJ_SPOOKANE_RAILROADENTRANCE:
objectDef OBJ_TYPE::DOOR, $2d2, DIRECTIONS::RIGHT, $33f
doorArgDef $0, $9, DIRECTIONS::RIGHT, $20A

OBJ_SPOOKANE_HOSPITALENTRANCE:
objectDef OBJ_TYPE::DOOR, $2a7, DIRECTIONS::UP, $354
doorArgDef $12, $25D, DIRECTIONS::LEFT, $3D6

OBJ_SPOOKANE_HOTELENTRANCE:
objectDef OBJ_TYPE::DOOR, $2a7, DIRECTIONS::UP, $36c
doorArgDef $11, $D, DIRECTIONS::LEFT, $E6

OBJ_SPOOKANE_STATIONENTRANCE:
objectDef OBJ_TYPE::DOOR, $2a9, DIRECTIONS::UP, $33e
doorArgDef $F, $291, DIRECTIONS::DOWN, $3E5

OBJ_SPOOKANE_SIGN:
objectDef $19, $2ae, DIRECTIONS::UP, $355
.word $8194 ;sprite
.byte SCRIPTS::J_CHECK, OBJ_SPOOKANE_SIGN_JCHECK0-OBJ_SPOOKANE_SIGN
.byte SCRIPTS::DIALOGUE
.word UMSG::SPOOKANE_SIGN
    OBJ_SPOOKANE_SIGN_JCHECK0:
.byte 0

OBJ_SPOOKANE_MANSIONSIGN:
objectDef $19, $2f5, DIRECTIONS::UP, $344
.word $8194 ;sprite
.byte SCRIPTS::J_CHECK, OBJ_SPOOKANE_MANSIONSIGN_JCHECK0-OBJ_SPOOKANE_MANSIONSIGN
.byte SCRIPTS::DIALOGUE
.word UMSG::SPOOKANE_MANSIONSIGN
    OBJ_SPOOKANE_MANSIONSIGN_JCHECK0:
.byte 0