OBJ_BANK_D:
.word OBJ_ZOO_OFFICEENTRANCE
.word OBJ_ZOO_MONKEYSIGN
.word OBJ_ZOO_MONKEY
.word OBJ_ZOO_PANDA1
.word OBJ_ZOO_PANDA2
.word OBJ_ZOO_BUNNY1
.word OBJ_ZOO_BUNNY2
.word OBJ_ZOO_BUNNY3
.word OBJ_ZOO_BUNNY4
.word OBJ_ZOO_PENGUIN1
.word OBJ_ZOO_PENGUIN2
.word OBJ_ZOO_PENGUIN3
.word OBJ_ZOO_PENGUIN4
.word OBJ_ZOO_FLAMINGO1
.word OBJ_ZOO_FLAMINGO2
.word OBJ_ZOO_FLAMINGO3
.word OBJ_ZOO_FLAMINGO4
.word OBJ_ZOO_MONKEY2
.word OBJ_ZOO_MONKEY3
.word OBJ_ZOO_MONKEY4
.word OBJ_ZOO_MONKEY5
.word OBJ_ZOO_GATESIGN
.word OBJ_ZOO_GATEMONKEY
.word OBJ_ZOO_GATE
.word OBJ_ZOO_MUSICSWITCHER1
.word OBJ_ZOO_MUSICSWITCHER2
.word OBJ_ZOO_OFFICESIGN
.word 0

OBJ_ZOO_OFFICEENTRANCE:
objectDef $18, $be, DIRECTIONS::UP, $f3
.byte SCRIPTS::J_UNK, OBJ_ZOO_OFFICEENTRANCE_JUNK0-OBJ_ZOO_OFFICEENTRANCE
.byte SCRIPTS::J_TOUCH, OBJ_ZOO_OFFICEENTRANCE_JUNK0-OBJ_ZOO_OFFICEENTRANCE
.byte SCRIPTS::FJ_JUMP, $D, OBJ_ZOO_OFFICEENTRANCE_FJJUMP1-OBJ_ZOO_OFFICEENTRANCE
.byte SCRIPTS::DA_TELEPORT
doorArgDef $0, $1ED, DIRECTIONS::LEFT, $86
.byte 0
      OBJ_ZOO_OFFICEENTRANCE_FJJUMP1:
.byte SCRIPTS::DA_TELEPORT
doorArgDef $2E, $1ED, DIRECTIONS::LEFT, $86
      OBJ_ZOO_OFFICEENTRANCE_JUNK0:
.byte 0

OBJ_ZOO_MONKEYSIGN:
objectDef $19, $c3, DIRECTIONS::UP, $db
.word $8868 ;sprite
.byte SCRIPTS::J_CHECK, OBJ_ZOO_MONKEYSIGN_JCHECK0-OBJ_ZOO_MONKEYSIGN
.byte SCRIPTS::DIALOGUE
.word UMSG::ZOO_MONKEYSIGN
.byte SCRIPTS::FJ_JUMP, $D, OBJ_ZOO_MONKEYSIGN_JCHECK0-OBJ_ZOO_MONKEYSIGN
.byte SCRIPTS::O_SIGNAL, $2
      OBJ_ZOO_MONKEYSIGN_JCHECK0:
.byte 0

OBJ_ZOO_MONKEY:
objectDef OBJ_TYPE::WANDERING_NPC, $c0, DIRECTIONS::DOWN, $d9
.word $87C4 ;sprite
.byte SCRIPTS::F_APPEAR, $D
.byte SCRIPTS::J_SIGNALED, OBJ_ZOO_MONKEY_JSIGNALED0-OBJ_ZOO_MONKEY
.byte SCRIPTS::DIALOGUE
.word UMSG::ZOO_MONKEY
.byte SCRIPTS::M_MOVE
.word OBJ_ZOO_MONKEY_MOVE0
.byte SCRIPTS::M_MUSIC, $26
.byte SCRIPTS::T_DELAY, $F0
.byte SCRIPTS::M_MUSIC, $12
.byte SCRIPTS::F_SETFLAG, $F5
.byte SCRIPTS::DIALOGUE
.word UMSG::REMEMBER_MELODY
.ifdef VER_JP
.byte $65
.endif
      OBJ_ZOO_MONKEY_JSIGNALED0:
.byte 0
        OBJ_ZOO_MONKEY_MOVE0:
moveDef DIRECTIONS::DOWN, MOVE_CMD::ABOUTFACE, $1
.byte 0

OBJ_ZOO_PANDA1:
objectDef $19, $a8, DIRECTIONS::UP, $d8
.word $889C ;sprite
.byte 0

OBJ_ZOO_PANDA2:
objectDef $19, $aa, DIRECTIONS::UP, $d9
.word $889C ;sprite
.byte 0

OBJ_ZOO_BUNNY1:
objectDef $22, $6f, DIRECTIONS::LEFT, $ed
.word $8878 ;sprite
.byte 0

OBJ_ZOO_BUNNY2:
objectDef $22, $73, DIRECTIONS::LEFT, $ef
.word $8878 ;sprite
.byte 0

OBJ_ZOO_BUNNY3:
objectDef $22, $6d, DIRECTIONS::RIGHT, $f1
.word $8878 ;sprite
.byte 0

OBJ_ZOO_BUNNY4:
objectDef $22, $6f, DIRECTIONS::DOWN, $f0
.word $8878 ;sprite
.byte 0

OBJ_ZOO_PENGUIN1:
objectDef OBJ_TYPE::WANDERING_NPC2, $88, DIRECTIONS::RIGHT, $f1
.word $8844 ;sprite
.byte 0

OBJ_ZOO_PENGUIN2:
objectDef OBJ_TYPE::WANDERING_NPC2, $89, DIRECTIONS::LEFT, $f3
.word $8844 ;sprite
.byte 0

OBJ_ZOO_PENGUIN3:
objectDef OBJ_TYPE::WANDERING_NPC2, $82, DIRECTIONS::DOWN, $f5
.word $8844 ;sprite
.byte 0

OBJ_ZOO_PENGUIN4:
objectDef OBJ_TYPE::WANDERING_NPC2, $87, DIRECTIONS::RIGHT, $f2
.word $8844 ;sprite
.byte 0

OBJ_ZOO_FLAMINGO1:
objectDef $19, $ba, DIRECTIONS::UP, $e0
.word $8898 ;sprite
.byte 0

OBJ_ZOO_FLAMINGO2:
objectDef $19, $b8, DIRECTIONS::UP, $e1
.word $8898 ;sprite
.byte 0

OBJ_ZOO_FLAMINGO3:
objectDef $19, $bc, DIRECTIONS::UP, $e1
.word $8898 ;sprite
.byte 0

OBJ_ZOO_FLAMINGO4:
objectDef $19, $b7, DIRECTIONS::UP, $e5
.word $8898 ;sprite
.byte 0

OBJ_ZOO_MONKEY2:
objectDef OBJ_TYPE::WANDERINGFAST_NPC, $94, DIRECTIONS::DOWN, $e1
.word $87C4 ;sprite
.byte 0

OBJ_ZOO_MONKEY3:
objectDef OBJ_TYPE::WANDERINGFAST_NPC, $95, DIRECTIONS::RIGHT, $e4
.word $87C4 ;sprite
.byte 0

OBJ_ZOO_MONKEY4:
objectDef OBJ_TYPE::WANDERING_NPC2, $92, DIRECTIONS::RIGHT, $e5
.word $87C4 ;sprite
.byte 0

OBJ_ZOO_MONKEY5:
objectDef OBJ_TYPE::WANDERINGFAST_NPC, $97, DIRECTIONS::DOWN, $e5
.word $87C4 ;sprite
.byte 0

OBJ_ZOO_GATESIGN:
objectDef $24, $7d, DIRECTIONS::UP, $102
.word $8864 ;sprite
.byte 0

OBJ_ZOO_GATEMONKEY:
objectDef $14, $7d, DIRECTIONS::DOWN, $104
.word $87C4 ;sprite
.byte SCRIPTS::F_DISAPPEAR, $21
.byte SCRIPTS::J_TOUCH, OBJ_ZOO_GATEMONKEY_JTOUCH0-OBJ_ZOO_GATEMONKEY
.byte SCRIPTS::J_JUMP, OBJ_ZOO_GATEMONKEYJ_JUMP1-OBJ_ZOO_GATEMONKEY
      OBJ_ZOO_GATEMONKEY_JTOUCH0:
.byte SCRIPTS::J_TALK, OBJ_ZOO_GATEMONKEY_JTALK2-OBJ_ZOO_GATEMONKEY
      OBJ_ZOO_GATEMONKEYJ_JUMP1:
.byte SCRIPTS::DIALOGUE
.word UMSG::ZOO_GATEMONKEY
.byte SCRIPTS::IJ_HASITEM, $56, OBJ_ZOO_GATEMONKEY_JTALK2-OBJ_ZOO_GATEMONKEY
.byte SCRIPTS::DIALOGUE
.word UMSG::ZOO_GATEMONKEY_KEY
.byte SCRIPTS::I_PICKITEM, $56
.byte SCRIPTS::J_REMOVEITEM, OBJ_ZOO_GATEMONKEY_JTALK2-OBJ_ZOO_GATEMONKEY
.byte SCRIPTS::T_CHANGETYPE, $26
.byte SCRIPTS::F_SETFLAG, $21
      OBJ_ZOO_GATEMONKEY_JTALK2:
.byte 0

OBJ_ZOO_GATE:
objectDef $1d, $7d, DIRECTIONS::UP, $103
.word $886C ;sprite
.byte SCRIPTS::F_DISAPPEAR, $20
.byte SCRIPTS::J_CHECK, OBJ_ZOO_GATE_JCHECK0-OBJ_ZOO_GATE
.byte SCRIPTS::J_JUMP, OBJ_ZOO_GATEJ_JUMP1-OBJ_ZOO_GATE
      OBJ_ZOO_GATE_JCHECK0:
.byte SCRIPTS::J_TOUCH, OBJ_ZOO_GATE_JTOUCH2-OBJ_ZOO_GATE
      OBJ_ZOO_GATEJ_JUMP1:
.byte SCRIPTS::DIALOGUE
.word UMSG::ZOO_GATE
.byte SCRIPTS::F_SETFLAG, $20
      OBJ_ZOO_GATE_JTOUCH2:
.byte 0

OBJ_ZOO_MUSICSWITCHER1:
objectDef $1f, $7d, DIRECTIONS::UP, $104
.byte SCRIPTS::F_APPEAR, $21
.byte SCRIPTS::J_TOUCH, OBJ_ZOO_MUSICSWITCHER1_JTOUCH0-OBJ_ZOO_MUSICSWITCHER1
.byte SCRIPTS::M_MUSIC, $6
      OBJ_ZOO_MUSICSWITCHER1_JTOUCH0:
.byte 0

OBJ_ZOO_MUSICSWITCHER2:
objectDef OBJ_TYPE::TRIGGER, $7d, DIRECTIONS::UP, $101
.byte SCRIPTS::J_TOUCH, OBJ_ZOO_MUSICSWITCHER2_JTOUCH0-OBJ_ZOO_MUSICSWITCHER2
.byte SCRIPTS::FJ_JUMP, $D, OBJ_ZOO_MUSICSWITCHER2_FJJUMP1-OBJ_ZOO_MUSICSWITCHER2
.byte SCRIPTS::M_MUSIC, $12
.byte 0
      OBJ_ZOO_MUSICSWITCHER2_FJJUMP1:
.byte SCRIPTS::M_MUSIC, $11
      OBJ_ZOO_MUSICSWITCHER2_JTOUCH0:
.byte 0

OBJ_ZOO_OFFICESIGN:
objectDef $19, $bd, DIRECTIONS::UP, $f4
.word $8194 ;sprite
.byte SCRIPTS::J_CHECK, OBJ_ZOO_OFFICESIGN_JCHECK0-OBJ_ZOO_OFFICESIGN
.byte SCRIPTS::DIALOGUE
.word UMSG::ZOO_OFFICESIGN
      OBJ_ZOO_OFFICESIGN_JCHECK0:
.byte 0