OBJ_BANK_4:
.addr OBJ_REINDEER_HEALERENTRANCE
.addr OBJ_REINDEER_MOUTHWASHENTRANCE
.addr OBJ_REINDEER_STATIONENTRANCE
.addr OBJ_ELLAY_LIVEHOUSEEXIT
.addr OBJ_ELLAY_LIVEHOUSESIDEIN
.addr OBJ_ELLAY_JAILEXIT
.addr OBJ_REINDEER_NOSEYGUY
.addr OBJ_REINDEER_RUMORMWGUY
.addr OBJ_REINDEER_RUMORMWGIRL
.addr OBJ_REINDEER_SPOOKANEGIRL
.addr OBJ_REINDEER_TUNNELGUY
.addr OBJ_REINDEER_QUIETWOMAN
.addr OBJ_REINDEER_FOODGIRL
.addr OBJ_REINDEER_PEEPINGGUY
.addr OBJ_REINDEER_BICYCLEGUY
.addr OBJ_REINDEER_BEGGIRL
.addr OBJ_ELLAY_LHBACKROOMGUY
.addr OBJ_ELLAY_LHDRINKGIRL
.addr OBJ_ELLAY_LHTEDDYGIRL
.addr OBJ_ELLAY_LHCUTEGUY
.addr OBJ_ELLAY_LHBOUNCERGIRL
.addr OBJ_ELLAY_LHBOUNCERGUY
.addr OBJ_ELLAY_LHTEDDY
.addr OBJ_ELLAY_LHCOP
.addr OBJ_ELLAY_LHCOP_JAILSCENE
.addr OBJ_ELLAY_LHCOP_JAIL
.addr OBJ_ELLAY_JAILCOP
.addr OBJ_REINDEER_MISLAYSIGN
.addr 0

OBJ_REINDEER_HEALERENTRANCE:
objectDef OBJ_TYPE::DOOR, $199, DIRECTIONS::UP, $337
doorArgDef $12, $2D, DIRECTIONS::LEFT, $A6

OBJ_REINDEER_MOUTHWASHENTRANCE:
objectDef OBJ_TYPE::DOOR, $160, DIRECTIONS::UP, $2c9
doorArgDef $12, $26D, DIRECTIONS::LEFT, $86

OBJ_REINDEER_STATIONENTRANCE:
objectDef OBJ_TYPE::DOOR, $201, DIRECTIONS::UP, $33e
doorArgDef $F, $261, DIRECTIONS::DOWN, $3C5

OBJ_ELLAY_LIVEHOUSEEXIT:
objectDef OBJ_TYPE::DOOR, $2bc, DIRECTIONS::RIGHT, $3c8
doorArgDef $6, $323, DIRECTIONS::DOWN, $12D

OBJ_ELLAY_LIVEHOUSESIDEIN:
objectDef OBJ_TYPE::DOOR, $2a9, DIRECTIONS::LEFT, $3ca
doorArgDef $0, $2ED, DIRECTIONS::LEFT, $3C6

OBJ_ELLAY_JAILEXIT:
objectDef OBJ_TYPE::DOOR, $30e, DIRECTIONS::RIGHT, $3c6
doorArgDef $6, $30A, DIRECTIONS::DOWN, $121

OBJ_REINDEER_NOSEYGUY:
objectDef OBJ_TYPE::WANDERING_NPC, $206, DIRECTIONS::DOWN, $344
.addr SPRITEDEF_MOUSTACHE_GUY ;sprite
OBJ_IS_NOT_TALKING @JTALK0-OBJ_REINDEER_NOSEYGUY
OBJ_NOT_HAS_ITEM $62, @IJHASITEM1-OBJ_REINDEER_NOSEYGUY
OBJ_DIALOGUE UMSG::REINDEER_NOSEYGUY_HAT
OBJ_STOP
    @IJHASITEM1:
OBJ_DIALOGUE UMSG::REINDEER_NOSEYGUY
    @JTALK0:
OBJ_STOP

OBJ_REINDEER_RUMORMWGUY:
objectDef OBJ_TYPE::WANDERING_NPC, $209, DIRECTIONS::RIGHT, $347
.addr SPRITEDEF_MAN ;sprite
OBJ_IS_NOT_TALKING @JTALK0-OBJ_REINDEER_RUMORMWGUY
OBJ_DIALOGUE UMSG::REINDEER_RUMORMWGUY
    @JTALK0:
OBJ_STOP

OBJ_REINDEER_RUMORMWGIRL:
objectDef OBJ_TYPE::WANDERING_NPC, $1fd, DIRECTIONS::DOWN, $346
.addr SPRITEDEF_SECRETARY ;sprite
OBJ_IS_NOT_TALKING @JTALK0-OBJ_REINDEER_RUMORMWGIRL
OBJ_DIALOGUE UMSG::REINDEER_RUMORMWGIRL
    @JTALK0:
OBJ_STOP

OBJ_REINDEER_SPOOKANEGIRL:
objectDef OBJ_TYPE::WANDERING_NPC, $1a4, DIRECTIONS::LEFT, $368
.addr SPRITEDEF_WOMAN ;sprite
OBJ_IS_NOT_TALKING @JTALK0-OBJ_REINDEER_SPOOKANEGIRL
OBJ_DIALOGUE UMSG::REINDEER_SPOOKANEGIRL
    @JTALK0:
OBJ_STOP

OBJ_REINDEER_TUNNELGUY:
objectDef OBJ_TYPE::WANDERING_NPC, $1a8, DIRECTIONS::RIGHT, $372
.addr SPRITEDEF_BIGLADY ;sprite
OBJ_IS_NOT_TALKING @JTALK0-OBJ_REINDEER_TUNNELGUY
OBJ_DIALOGUE UMSG::REINDEER_TUNNELGUY
    @JTALK0:
OBJ_STOP

OBJ_REINDEER_QUIETWOMAN:
objectDef OBJ_TYPE::WANDERING_NPC, $1b4, DIRECTIONS::LEFT, $375
.addr SPRITEDEF_OLD_WOMAN ;sprite
OBJ_IS_NOT_TALKING @JTALK0-OBJ_REINDEER_QUIETWOMAN
OBJ_DIALOGUE UMSG::REINDEER_QUIETWOMAN
    @JTALK0:
OBJ_STOP

OBJ_REINDEER_FOODGIRL:
objectDef OBJ_TYPE::WANDERING_NPC, $1b4, DIRECTIONS::RIGHT, $368
.addr SPRITEDEF_SECRETARY ;sprite
OBJ_IS_NOT_TALKING @JTALK0-OBJ_REINDEER_FOODGIRL
OBJ_DIALOGUE UMSG::REINDEER_FOODGIRL
    @JTALK0:
OBJ_STOP

OBJ_REINDEER_PEEPINGGUY:
objectDef OBJ_TYPE::STATIONARY_NPC, $1b9, DIRECTIONS::UP, $37b
.addr SPRITEDEF_COOL_GUY ;sprite
OBJ_IS_NOT_TALKING @JTALK0-OBJ_REINDEER_PEEPINGGUY
OBJ_DIALOGUE UMSG::REINDEER_PEEPINGGUY
    @JTALK0:
OBJ_STOP

OBJ_REINDEER_BICYCLEGUY:
objectDef OBJ_TYPE::WANDERING_NPC, $1a1, DIRECTIONS::DOWN, $396
.addr SPRITEDEF_MAN ;sprite
OBJ_IS_NOT_TALKING @JTALK0-OBJ_REINDEER_BICYCLEGUY
OBJ_DIALOGUE UMSG::REINDEER_BICYCLEGUY
    @JTALK0:
OBJ_STOP

OBJ_REINDEER_BEGGIRL:
objectDef OBJ_TYPE::WANDERING_NPC, $1be, DIRECTIONS::DOWN, $396
.addr SPRITEDEF_PIGPEN ;sprite
OBJ_IS_NOT_TALKING @JTALK0-OBJ_REINDEER_BEGGIRL
OBJ_DIALOGUE UMSG::REINDEER_BEGGIRL
    @JTALK0:
OBJ_STOP

OBJ_ELLAY_LHBACKROOMGUY:
objectDef OBJ_TYPE::WANDERING_NPC, $2ad, DIRECTIONS::RIGHT, $3cb
.addr SPRITEDEF_SUIT_GUY ;sprite
OBJ_IS_NOT_TALKING @JTALK0-OBJ_ELLAY_LHBACKROOMGUY
OBJ_IS_NOT_FLAG $3B, @FJJUMP1-OBJ_ELLAY_LHBACKROOMGUY
OBJ_DIALOGUE UMSG::ELLAY_LHBACKROOMGUY_MINE
OBJ_STOP
    @FJJUMP1:
OBJ_DIALOGUE UMSG::ELLAY_LHBACKROOMGUY
    @JTALK0:
OBJ_STOP

OBJ_ELLAY_LHDRINKGIRL:
objectDef OBJ_TYPE::SPINNING_NPC, $2b5, DIRECTIONS::LEFT, $3cb
.addr SPRITEDEF_WOMAN ;sprite
OBJ_IS_NOT_TALKING @JTALK0-OBJ_ELLAY_LHDRINKGIRL
OBJ_IS_NOT_FLAG $34, @FJJUMP1-OBJ_ELLAY_LHDRINKGIRL
OBJ_DIALOGUE UMSG::ELLAY_LHDRINKGIRL
OBJ_STOP
    @FJJUMP1:
OBJ_DIALOGUE UMSG::ELLAY_LHDRINKGIRL_OFFER
OBJ_YESNO_IS_NO @JYESNO2-OBJ_ELLAY_LHDRINKGIRL
OBJ_SET_FLAG $34
OBJ_MOVE @MOVE0
OBJ_DIALOGUE UMSG::PODUNK_PIPPI_MEET_NOYES
OBJ_SET_FLAG $2B
OBJ_SIGNAL $17
OBJ_STOP
    @JYESNO2:
OBJ_DIALOGUE UMSG::ELLAY_LHDRINKGIRL_OFFER_REFUSE
    @JTALK0:
OBJ_STOP
    @MOVE0:
moveDef DIRECTIONS::UP, $6, $1
moveDef DIRECTIONS::LEFT, $6, $2
moveDef DIRECTIONS::LEFT, MOVE_CMD::MOVEFACE, $1
moveDef DIRECTIONS::RIGHT, MOVE_CMD::ABOUTFACE, $1
OBJ_STOP

OBJ_ELLAY_LHTEDDYGIRL:
objectDef OBJ_TYPE::SPINNING_NPC, $2b0, DIRECTIONS::UP, $3cb
.addr SPRITEDEF_SECRETARY ;sprite
OBJ_IS_NOT_TALKING @JTALK0-OBJ_ELLAY_LHTEDDYGIRL
OBJ_NOT_HAS_CHARACTER $4, @CJPRESENT1-OBJ_ELLAY_LHTEDDYGIRL
OBJ_DIALOGUE UMSG::ELLAY_LHTEDDYGIRL2
OBJ_STOP
    @CJPRESENT1:
OBJ_DIALOGUE UMSG::ELLAY_LHTEDDYGIRL
    @JTALK0:
OBJ_STOP

OBJ_ELLAY_LHCUTEGUY:
objectDef OBJ_TYPE::SPINNING_NPC, $2b2, DIRECTIONS::LEFT, $3c9
.addr SPRITEDEF_COOL_GUY ;sprite
OBJ_IS_NOT_TALKING @JTALK0-OBJ_ELLAY_LHCUTEGUY
OBJ_NOT_HAS_CHARACTER $2, @CJPRESENT1-OBJ_ELLAY_LHCUTEGUY
OBJ_HAS_STATUS $80, @CJPRESENT1-OBJ_ELLAY_LHCUTEGUY
OBJ_DIALOGUE UMSG::ELLAY_LHCUTEGUY2
OBJ_STOP
    @CJPRESENT1:
OBJ_DIALOGUE UMSG::ELLAY_LHCUTEGUY
    @JTALK0:
OBJ_STOP

OBJ_ELLAY_LHBOUNCERGIRL:
objectDef OBJ_TYPE::STATIONARY_NPC, $2b8, DIRECTIONS::LEFT, $3c8
.addr SPRITEDEF_SUIT_GIRL ;sprite
OBJ_IS_NOT_TALKING @JTALK0-OBJ_ELLAY_LHBOUNCERGIRL
OBJ_HAS_MOVED @JUNK21-OBJ_ELLAY_LHBOUNCERGIRL
OBJ_IS_NOT_FACING @JUNK2-OBJ_ELLAY_LHBOUNCERGIRL
OBJ_JUMP @JUMP3-OBJ_ELLAY_LHBOUNCERGIRL
    @JUNK2:
OBJ_DIALOGUE UMSG::ELLAY_LHBOUNCERGIRL
OBJ_MOVE @MOVE0
OBJ_STOP
    @JUMP3:
OBJ_DIALOGUE UMSG::ELLAY_LHBOUNCERGIRL_TICKET
OBJ_STOP
    @JTALK0:
OBJ_IS_NOT_USING $5A, @IJUSE4-OBJ_ELLAY_LHBOUNCERGIRL
OBJ_HAS_MOVED @JUNK21-OBJ_ELLAY_LHBOUNCERGIRL
OBJ_DIALOGUE UMSG::ELLAY_LHBOUNCERGIRL2
OBJ_NOT_HAS_ITEM $5A, @IJUSE4-OBJ_ELLAY_LHBOUNCERGIRL
OBJ_PICK_ITEM $5A
OBJ_REMOVE_ITEM @IJUSE4-OBJ_ELLAY_LHBOUNCERGIRL
OBJ_MOVE @MOVE0
OBJ_STOP
    @JUNK21:
OBJ_DIALOGUE UMSG::ELLAY_LHBOUNCERGIRL
    @IJUSE4:
OBJ_STOP
    @MOVE0:
moveDef DIRECTIONS::UP, MOVE_CMD::ABOUTFACE, $1
moveDef DIRECTIONS::DOWN, MOVE_CMD::MOVE, $1
OBJ_STOP

OBJ_ELLAY_LHBOUNCERGUY:
objectDef OBJ_TYPE::STATIONARY_NPC, $2af, DIRECTIONS::RIGHT, $3c8
.addr SPRITEDEF_MOUSTACHE_GUY ;sprite
OBJ_IS_NOT_TALKING @JTALK0-OBJ_ELLAY_LHBOUNCERGUY
OBJ_DIALOGUE UMSG::ELLAY_LHBOUNCERGUY_OFFER
OBJ_YESNO_IS_NO @JYESNO1-OBJ_ELLAY_LHBOUNCERGUY
OBJ_MOVE @MOVE0
OBJ_DIALOGUE UMSG::ELLAY_LHBOUNCERGUY_OFFER_YES
OBJ_MOVE @MOVE1
OBJ_IS_NOT_FLAG $35, @FJJUMP2-OBJ_ELLAY_LHBOUNCERGUY
OBJ_PICK_CHARACTER_J $2, @CJSELECTPARTY3-OBJ_ELLAY_LHBOUNCERGUY
OBJ_DO_LIVE_SHOW
OBJ_DELAY $78
OBJ_PLAY_MUSIC $22
OBJ_STOP
    @FJJUMP2:
OBJ_PICK_CHARACTER_J $0, @CJSELECTPARTY3-OBJ_ELLAY_LHBOUNCERGUY
OBJ_HAS_STATUS $40, @SJPRESENT4-OBJ_ELLAY_LHBOUNCERGUY
OBJ_HAS_STATUS $80, @CJSELECTPARTY3-OBJ_ELLAY_LHBOUNCERGUY
OBJ_PICK_CHARACTER_J $1, @CJSELECTPARTY3-OBJ_ELLAY_LHBOUNCERGUY
OBJ_HAS_STATUS $80, @CJSELECTPARTY3-OBJ_ELLAY_LHBOUNCERGUY
OBJ_PICK_CHARACTER_J $2, @CJSELECTPARTY3-OBJ_ELLAY_LHBOUNCERGUY
OBJ_HAS_STATUS $80, @CJSELECTPARTY3-OBJ_ELLAY_LHBOUNCERGUY
OBJ_PICK_CHARACTER_J $1, @CJSELECTPARTY3-OBJ_ELLAY_LHBOUNCERGUY
OBJ_DO_LIVE_SHOW
OBJ_DELAY $78
OBJ_PLAY_MUSIC $22
OBJ_SIGNAL $16
OBJ_STOP
    @SJPRESENT4:
OBJ_DIALOGUE UMSG::ELLAY_LHBOUNCERGUY_STONE
OBJ_STOP
    @CJSELECTPARTY3:
OBJ_DIALOGUE UMSG::ELLAY_LHBOUNCERGUY_TRIO
OBJ_STOP
    @JYESNO1:
OBJ_DIALOGUE UMSG::ELLAY_LHBOUNCERGUY_OFFER_NO
    @JTALK0:
OBJ_STOP
    @MOVE0:
moveDef DIRECTIONS::RIGHT, $6, $2
moveDef DIRECTIONS::UP, $6, $1
moveDef DIRECTIONS::RIGHT, $6, $4
moveDef DIRECTIONS::LEFT, MOVE_CMD::ABOUTFACE, $1
.byte 3
    @MOVE1:
moveDef DIRECTIONS::DOWN, MOVE_CMD::MOVEFACE, $1
moveDef DIRECTIONS::LEFT, MOVE_CMD::MOVEFACE, $6
moveDef DIRECTIONS::RIGHT, MOVE_CMD::ABOUTFACE, $1
OBJ_STOP

OBJ_ELLAY_LHTEDDY:
objectDef OBJ_TYPE::STATIONARY_NPC_CHECKSPAWN, $2bb, DIRECTIONS::LEFT, $3c8
.addr SPRITEDEF_TEDDY ;sprite
OBJ_FLAG_APPEAR $1
OBJ_IS_SIGNAL @JSIGNALED0-OBJ_ELLAY_LHTEDDY
OBJ_MOVE @MOVE0
OBJ_DIALOGUE UMSG::ELLAY_LHTEDDY_INTRO
OBJ_YESNO_IS_NO @JYESNO1-OBJ_ELLAY_LHTEDDY
OBJ_DIALOGUE UMSG::ELLAY_LHTEDDY_INTRO_YES
OBJ_JUMP @JUMP2-OBJ_ELLAY_LHTEDDY
    @JYESNO1:
OBJ_DIALOGUE UMSG::ELLAY_LHTEDDY_INTRO_NO
    @JUMP2:
OBJ_DIALOGUE UMSG::ELLAY_LHTEDDY_CHALLENGE
OBJ_PICK_CHARACTER $1
    @JNOTMAX3:
OBJ_HEAL $FF
OBJ_NOT_MAX_HEALTH @JNOTMAX3-OBJ_ELLAY_LHTEDDY
OBJ_BATTLE $9D
OBJ_MOVE @MOVE1
OBJ_JUMP @JUMP4-OBJ_ELLAY_LHTEDDY
    @JUMP9:
OBJ_DIALOGUE UMSG::ELLAY_LHTEDDY_TEAMUP_AGREE
OBJ_MOVE @MOVE2
OBJ_PICK_CHARACTER_J $2, @CJSELECTPARTY5-OBJ_ELLAY_LHTEDDY
OBJ_NOT_CHARACTER_SELECTED $3, @CJSELECTPARTY5-OBJ_ELLAY_LHTEDDY
OBJ_MOVE @MOVE3
    @CJSELECTPARTY5:
OBJ_MOVE @MOVE4
OBJ_DIALOGUE UMSG::ELLAY_LHTEDDY_REPLACELLOYD
OBJ_PLAY_MUSIC $21
OBJ_DELAY $B4
OBJ_PLAY_MUSIC $22
OBJ_MOVE @MOVE5
OBJ_ADD_CHARACTER $4, @JSIGNALED0-OBJ_ELLAY_LHTEDDY
OBJ_REMOVE_CHARACTER $3, @JSIGNALED0-OBJ_ELLAY_LHTEDDY
OBJ_SET_FLAG $35
    @JUMP7:
OBJ_PICK_CHARACTER $3
OBJ_PICK_CHARACTER_ITEM $0, @JSIGNALED0-OBJ_ELLAY_LHTEDDY
OBJ_REMOVE_ITEM @JSIGNALED0-OBJ_ELLAY_LHTEDDY
OBJ_IS_NOT_SELECTED $3, @IJSELECTEDITEM6-OBJ_ELLAY_LHTEDDY
OBJ_JUMP @JUMP7-OBJ_ELLAY_LHTEDDY
    @IJSELECTEDITEM6:
OBJ_PICK_CHARACTER $4
OBJ_GIVE_ITEM @JSIGNALED0-OBJ_ELLAY_LHTEDDY
OBJ_JUMP @JUMP7-OBJ_ELLAY_LHTEDDY
    @JUMP4:
OBJ_DIALOGUE UMSG::ELLAY_LHTEDDY_POSTFIGHT
OBJ_YESNO_IS_NO @JYESNO8-OBJ_ELLAY_LHTEDDY
OBJ_JUMP @JUMP9-OBJ_ELLAY_LHTEDDY
    @JYESNO8:
OBJ_DIALOGUE UMSG::ELLAY_LHTEDDY_TEAMUP_DECLINE
OBJ_YESNO_IS_NO @JYESNO10-OBJ_ELLAY_LHTEDDY
OBJ_JUMP @JUMP9-OBJ_ELLAY_LHTEDDY
    @JYESNO10:
OBJ_DIALOGUE UMSG::ELLAY_LHTEDDY_TEAMUP_DECLINE2
OBJ_YESNO_IS_NO @JYESNO11-OBJ_ELLAY_LHTEDDY
OBJ_JUMP @JUMP9-OBJ_ELLAY_LHTEDDY
    @JYESNO11:
OBJ_DIALOGUE UMSG::ELLAY_LHTEDDY_TEAMUP_DECLINE3
OBJ_YESNO_IS_NO @JYESNO12-OBJ_ELLAY_LHTEDDY
OBJ_JUMP @JUMP9-OBJ_ELLAY_LHTEDDY
    @JYESNO12:
OBJ_TELEPORT $6, $B1, DIRECTIONS::DOWN, $13C
OBJ_MOVE @MOVE6
    @JSIGNALED0:
OBJ_STOP
    @MOVE0:
moveDef DIRECTIONS::LEFT, MOVE_CMD::MOVEFACE, $4
moveDef DIRECTIONS::UP, MOVE_CMD::MOVEFACE, $1
moveDef DIRECTIONS::LEFT, MOVE_CMD::MOVEFACE, $2
.byte 3
    @MOVE2:
moveDef DIRECTIONS::UP, MOVE_CMD::MOVEFACE, $1
moveDef DIRECTIONS::LEFT, MOVE_CMD::MOVEFACE, $2
.byte 3
    @MOVE3:
moveDef DIRECTIONS::LEFT, MOVE_CMD::MOVEFACE, $1
.byte 3
    @MOVE4:
moveDef DIRECTIONS::DOWN, MOVE_CMD::ABOUTFACE, $1
.byte 3
    @MOVE5:
moveDef DIRECTIONS::DOWN, MOVE_CMD::MOVEFACE, $1
moveDef DIRECTIONS::RIGHT, MOVE_CMD::ABOUTFACE, $1
OBJ_STOP
    @MOVE6:
OBJ_STOP
    @MOVE1:
moveDef DIRECTIONS::LEFT, MOVE_CMD::ABOUTFACE, $1
.byte 3

OBJ_ELLAY_LHCOP:
objectDef OBJ_TYPE::STATIONARY_NPC_CHECKSPAWN, $2bb, DIRECTIONS::DOWN, $3c8
.addr SPRITEDEF_COP ;sprite
OBJ_FLAG_APPEAR $2B
OBJ_IS_SIGNAL @JSIGNALED0-OBJ_ELLAY_LHCOP
OBJ_MOVE @MOVE0
OBJ_DIALOGUE UMSG::ELLAY_LHCOP_ARREST
OBJ_MOVE @MOVE1
    @JSIGNALED0:
OBJ_STOP
    @MOVE0:
moveDef DIRECTIONS::LEFT, MOVE_CMD::MOVEFACE, $8
moveDef DIRECTIONS::RIGHT, MOVE_CMD::ABOUTFACE, $1
moveDef DIRECTIONS::DOWN, MOVE_CMD::ABOUTFACE, $1
moveDef DIRECTIONS::LEFT, MOVE_CMD::ABOUTFACE, $1
moveDef DIRECTIONS::LEFT, MOVE_CMD::MOVEFACE, $3
moveDef DIRECTIONS::DOWN, MOVE_CMD::MOVEFACE, $2
moveDef DIRECTIONS::RIGHT, MOVE_CMD::MOVEFACE, $1
moveDef DIRECTIONS::DOWN, MOVE_CMD::MOVEFACE, $1
moveDef DIRECTIONS::RIGHT, MOVE_CMD::MOVEFACE, $2
moveDef DIRECTIONS::UP, MOVE_CMD::MOVEFACE, $1
moveDef DIRECTIONS::LEFT, MOVE_CMD::ABOUTFACE, $1
moveDef DIRECTIONS::RIGHT, MOVE_CMD::ABOUTFACE, $1
.byte 3
    @MOVE1:
moveDef DIRECTIONS::DOWN, $6, $1
moveDef DIRECTIONS::RIGHT, $6, $2
moveDef DIRECTIONS::UP, $6, $2
moveDef DIRECTIONS::RIGHT, $6, $1
moveDef DIRECTIONS::UP, $6, $1
moveDef DIRECTIONS::RIGHT, $6, $5
moveDef DIRECTIONS::RIGHT, $2, $1
moveDef DIRECTIONS::DOWN, $2, $1
.byte 3

OBJ_ELLAY_LHCOP_JAILSCENE:
objectDef OBJ_TYPE::STATIONARY_NPC_CHECKSPAWN, $30c, DIRECTIONS::RIGHT, $3c6
.addr SPRITEDEF_COP ;sprite
OBJ_FLAG_APPEAR $2B
OBJ_IS_NOT_TOUCHING @JTOUCH0-OBJ_ELLAY_LHCOP_JAILSCENE
OBJ_DIALOGUE UMSG::ELLAY_LHCOP_JAILSCENE1
OBJ_MOVE @MOVE0
OBJ_DIALOGUE UMSG::ELLAY_LHCOP_JAILSCENE2
OBJ_JUMP @JUMP1-OBJ_ELLAY_LHCOP_JAILSCENE
    @JYESNO2:
OBJ_DIALOGUE UMSG::ELLAY_LHCOP_JAILSHAME_NO
    @JUMP1:
OBJ_SLEEP
OBJ_DIALOGUE UMSG::ELLAY_LHCOP_JAILSHAME
OBJ_YESNO_IS_NO @JYESNO2-OBJ_ELLAY_LHCOP_JAILSCENE
OBJ_DIALOGUE UMSG::ELLAY_LHCOP_JAILSHAME_YES
OBJ_PICK_CHARACTER_J $0, @CJSELECTPARTY3-OBJ_ELLAY_LHCOP_JAILSCENE
OBJ_TAKE_WEAPON @CJSELECTPARTY3-OBJ_ELLAY_LHCOP_JAILSCENE
OBJ_SET_FLAG $63
OBJ_DIALOGUE UMSG::ELLAY_LHCOP_TAKEWEAPON
OBJ_CLEAR_FLAG $2B
OBJ_SET_FLAG $2E
OBJ_STOP
    @CJSELECTPARTY3:
OBJ_DIALOGUE UMSG::ELLAY_LHCOP_SEEWEAPON
OBJ_CLEAR_FLAG $2B
OBJ_SET_FLAG $2E
    @JTOUCH0:
OBJ_STOP
    @MOVE0:
moveDef DIRECTIONS::LEFT, $6, $6
moveDef DIRECTIONS::UP, $6, $1
moveDef DIRECTIONS::RIGHT, $6, $1
moveDef DIRECTIONS::LEFT, MOVE_CMD::ABOUTFACE, $1
moveDef DIRECTIONS::RIGHT, MOVE_CMD::MOVEFACE, $2
moveDef DIRECTIONS::UP, MOVE_CMD::MOVEFACE, $1
moveDef DIRECTIONS::LEFT, MOVE_CMD::MOVEFACE, $3
moveDef DIRECTIONS::DOWN, MOVE_CMD::ABOUTFACE, $1
OBJ_STOP

OBJ_ELLAY_LHCOP_JAIL:
objectDef OBJ_TYPE::STATIONARY_NPC_CHECKSPAWN, $306, DIRECTIONS::DOWN, $3c4
.addr SPRITEDEF_COP ;sprite
OBJ_FLAG_APPEAR $2E
OBJ_IS_NOT_TALKING @JTALK0-OBJ_ELLAY_LHCOP_JAIL
OBJ_DIALOGUE UMSG::ELLAY_LHCOP_JAIL
    @JTALK0:
OBJ_STOP

OBJ_ELLAY_JAILCOP:
objectDef OBJ_TYPE::WANDERING_NPC, $301, DIRECTIONS::LEFT, $3c7
.addr SPRITEDEF_COP ;sprite
OBJ_IS_NOT_TALKING @JTALK0-OBJ_ELLAY_JAILCOP
OBJ_IS_NOT_FLAG $63, @FJJUMP1-OBJ_ELLAY_JAILCOP
OBJ_SELECT_CONFWEAPON @FJJUMP1-OBJ_ELLAY_JAILCOP
OBJ_DIALOGUE UMSG::ELLAY_JAILCOP_HASWEAPON
OBJ_YESNO_IS_NO @JYESNO2-OBJ_ELLAY_JAILCOP
OBJ_TAKE_MONEY @JTAKEMONEY3-OBJ_ELLAY_JAILCOP
OBJ_NOT_HAS_ITEM $0, @IJHASITEM4-OBJ_ELLAY_JAILCOP
OBJ_DIALOGUE UMSG::ELLAY_JAILCOP_HASWEAPON_ACCEPT
OBJ_SELECT_CONFWEAPON @FJJUMP1-OBJ_ELLAY_JAILCOP
OBJ_GIVE_ITEM @JTALK0-OBJ_ELLAY_JAILCOP
OBJ_SHOW_MONEY
OBJ_PLAY_SOUND $6
OBJ_CLEAR_FLAG $63
OBJ_STOP
    @IJHASITEM4:
OBJ_DIALOGUE UMSG::ELLAY_JAILCOP_NOROOM
OBJ_SELECT_CONFWEAPON @FJJUMP1-OBJ_ELLAY_JAILCOP
OBJ_GIVE_MONEY @JTALK0-OBJ_ELLAY_JAILCOP
OBJ_STOP
    @JTAKEMONEY3:
OBJ_DIALOGUE UMSG::ELLAY_JAILCOP_NOMONEY
OBJ_STOP
    @JYESNO2:
OBJ_DIALOGUE UMSG::ELLAY_JAILCOP_HASWEAPON_DECLINE
OBJ_STOP
    @FJJUMP1:
OBJ_DIALOGUE UMSG::ELLAY_JAILCOP
    @JTALK0:
OBJ_STOP

OBJ_REINDEER_MISLAYSIGN:
objectDef $19, $158, DIRECTIONS::UP, $2ca
.addr SPRITEDEF_SIGN ;sprite
OBJ_IS_NOT_CHECKING @JCHECK0-OBJ_REINDEER_MISLAYSIGN
OBJ_DIALOGUE UMSG::REINDEER_MISLAYSIGN
OBJ_IS_NOT_FLAG $74, @FJJUMP1-OBJ_REINDEER_MISLAYSIGN
OBJ_JUMP @JCHECK0-OBJ_REINDEER_MISLAYSIGN
    @FJJUMP1:
OBJ_DIALOGUE UMSG::REINDEER_MISLAYSIGN2
OBJ_NOT_HAS_ITEM $0, @IJHASITEM2-OBJ_REINDEER_MISLAYSIGN
OBJ_PICK_ITEM $63
OBJ_GIVE_ITEM @JCHECK0-OBJ_REINDEER_MISLAYSIGN
OBJ_PLAY_SOUND $6
OBJ_SET_FLAG $74
OBJ_STOP
    @IJHASITEM2:
OBJ_DIALOGUE UMSG::INVENTORY_FULL
    @JCHECK0:
OBJ_STOP