OBJ_BANK_4:
.word OBJ_REINDEER_HEALERENTRANCE
.word OBJ_REINDEER_MOUTHWASHENTRANCE
.word OBJ_REINDEER_STATIONENTRANCE
.word OBJ_ELLAY_LIVEHOUSEEXIT
.word OBJ_ELLAY_LIVEHOUSESIDEIN
.word OBJ_ELLAY_JAILEXIT
.word OBJ_REINDEER_NOSEYGUY
.word OBJ_REINDEER_RUMORMWGUY
.word OBJ_REINDEER_RUMORMWGIRL
.word OBJ_REINDEER_SPOOKANEGIRL
.word OBJ_REINDEER_TUNNELGUY
.word OBJ_REINDEER_QUIETWOMAN
.word OBJ_REINDEER_FOODGIRL
.word OBJ_REINDEER_PEEPINGGUY
.word OBJ_REINDEER_BICYCLEGUY
.word OBJ_REINDEER_BEGGIRL
.word OBJ_ELLAY_LHBACKROOMGUY
.word OBJ_ELLAY_LHDRINKGIRL
.word OBJ_ELLAY_LHTEDDYGIRL
.word OBJ_ELLAY_LHCUTEGUY
.word OBJ_ELLAY_LHBOUNCERGIRL
.word OBJ_ELLAY_LHBOUNCERGUY
.word OBJ_ELLAY_LHTEDDY
.word OBJ_ELLAY_LHCOP
.word OBJ_ELLAY_LHCOP_JAILSCENE
.word OBJ_ELLAY_LHCOP_JAIL
.word OBJ_ELLAY_JAILCOP
.word OBJ_REINDEER_MISLAYSIGN
.word 0

OBJ_REINDEER_HEALERENTRANCE:
objectDef OBJ_TYPE::DOOR, $199, DIRECTIONS::UP, $337
doorArgDef $12, $2D, DIRECTIONS::LEFT, $A6

OBJ_REINDEER_MOUTHWASHENTRANCE:
objectDef OBJ_TYPE::DOOR, $160, DIRECTIONS::UP, $2c9
doorArgDef $12, $26D, DIRECTIONS::LEFT, $86

OBJ_REINDEER_STATIONENTRANCE:
objectDef OBJ_TYPE::DOOR, $201, DIRECTIONS::UP, $33e
doorArgDef $F, $261, DIRECTIONS::DOWN, $3C5

OBJ_ELLAY_LIVEHOUSEEXIT:
objectDef OBJ_TYPE::DOOR, $2bc, DIRECTIONS::RIGHT, $3c8
doorArgDef $6, $323, DIRECTIONS::DOWN, $12D

OBJ_ELLAY_LIVEHOUSESIDEIN:
objectDef OBJ_TYPE::DOOR, $2a9, DIRECTIONS::LEFT, $3ca
doorArgDef $0, $2ED, DIRECTIONS::LEFT, $3C6

OBJ_ELLAY_JAILEXIT:
objectDef OBJ_TYPE::DOOR, $30e, DIRECTIONS::RIGHT, $3c6
doorArgDef $6, $30A, DIRECTIONS::DOWN, $121

OBJ_REINDEER_NOSEYGUY:
objectDef OBJ_TYPE::WANDERING_NPC2, $206, DIRECTIONS::DOWN, $344
.word $81A8 ;sprite
.byte SCRIPTS::J_TALK, OBJ_REINDEER_NOSEYGUY_JTALK0-OBJ_REINDEER_NOSEYGUY
.byte SCRIPTS::IJ_HASITEM, $62, OBJ_REINDEER_NOSEYGUY_IJHASITEM1-OBJ_REINDEER_NOSEYGUY
.byte SCRIPTS::DIALOGUE
.word UMSG::REINDEER_NOSEYGUY_HAT
.byte 0
      OBJ_REINDEER_NOSEYGUY_IJHASITEM1:
.byte SCRIPTS::DIALOGUE
.word UMSG::REINDEER_NOSEYGUY
      OBJ_REINDEER_NOSEYGUY_JTALK0:
.byte 0

OBJ_REINDEER_RUMORMWGUY:
objectDef OBJ_TYPE::WANDERING_NPC2, $209, DIRECTIONS::RIGHT, $347
.word $8228 ;sprite
.byte SCRIPTS::J_TALK, OBJ_REINDEER_RUMORMWGUY_JTALK0-OBJ_REINDEER_RUMORMWGUY
.byte SCRIPTS::DIALOGUE
.word UMSG::REINDEER_RUMORMWGUY
      OBJ_REINDEER_RUMORMWGUY_JTALK0:
.byte 0

OBJ_REINDEER_RUMORMWGIRL:
objectDef OBJ_TYPE::WANDERING_NPC2, $1fd, DIRECTIONS::DOWN, $346
.word $8248 ;sprite
.byte SCRIPTS::J_TALK, OBJ_REINDEER_RUMORMWGIRL_JTALK0-OBJ_REINDEER_RUMORMWGIRL
.byte SCRIPTS::DIALOGUE
.word UMSG::REINDEER_RUMORMWGIRL
      OBJ_REINDEER_RUMORMWGIRL_JTALK0:
.byte 0

OBJ_REINDEER_SPOOKANEGIRL:
objectDef OBJ_TYPE::WANDERING_NPC2, $1a4, DIRECTIONS::LEFT, $368
.word $82A8 ;sprite
.byte SCRIPTS::J_TALK, OBJ_REINDEER_SPOOKANEGIRL_JTALK0-OBJ_REINDEER_SPOOKANEGIRL
.byte SCRIPTS::DIALOGUE
.word UMSG::REINDEER_SPOOKANEGIRL
      OBJ_REINDEER_SPOOKANEGIRL_JTALK0:
.byte 0

OBJ_REINDEER_TUNNELGUY:
objectDef OBJ_TYPE::WANDERING_NPC2, $1a8, DIRECTIONS::RIGHT, $372
.word $81E8 ;sprite
.byte SCRIPTS::J_TALK, OBJ_REINDEER_TUNNELGUY_JTALK0-OBJ_REINDEER_TUNNELGUY
.byte SCRIPTS::DIALOGUE
.word UMSG::REINDEER_TUNNELGUY
      OBJ_REINDEER_TUNNELGUY_JTALK0:
.byte 0

OBJ_REINDEER_QUIETWOMAN:
objectDef OBJ_TYPE::WANDERING_NPC2, $1b4, DIRECTIONS::LEFT, $375
.word $8288 ;sprite
.byte SCRIPTS::J_TALK, OBJ_REINDEER_QUIETWOMAN_JTALK0-OBJ_REINDEER_QUIETWOMAN
.byte SCRIPTS::DIALOGUE
.word UMSG::REINDEER_QUIETWOMAN
      OBJ_REINDEER_QUIETWOMAN_JTALK0:
.byte 0

OBJ_REINDEER_FOODGIRL:
objectDef OBJ_TYPE::WANDERING_NPC2, $1b4, DIRECTIONS::RIGHT, $368
.word $8248 ;sprite
.byte SCRIPTS::J_TALK, OBJ_REINDEER_FOODGIRL_JTALK0-OBJ_REINDEER_FOODGIRL
.byte SCRIPTS::DIALOGUE
.word UMSG::REINDEER_FOODGIRL
      OBJ_REINDEER_FOODGIRL_JTALK0:
.byte 0

OBJ_REINDEER_PEEPINGGUY:
objectDef OBJ_TYPE::STATIONARY_NPC2, $1b9, DIRECTIONS::UP, $37b
.word $8268 ;sprite
.byte SCRIPTS::J_TALK, OBJ_REINDEER_PEEPINGGUY_JTALK0-OBJ_REINDEER_PEEPINGGUY
.byte SCRIPTS::DIALOGUE
.word UMSG::REINDEER_PEEPINGGUY
      OBJ_REINDEER_PEEPINGGUY_JTALK0:
.byte 0

OBJ_REINDEER_BICYCLEGUY:
objectDef OBJ_TYPE::WANDERING_NPC2, $1a1, DIRECTIONS::DOWN, $396
.word $8228 ;sprite
.byte SCRIPTS::J_TALK, OBJ_REINDEER_BICYCLEGUY_JTALK0-OBJ_REINDEER_BICYCLEGUY
.byte SCRIPTS::DIALOGUE
.word UMSG::REINDEER_BICYCLEGUY
      OBJ_REINDEER_BICYCLEGUY_JTALK0:
.byte 0

OBJ_REINDEER_BEGGIRL:
objectDef OBJ_TYPE::WANDERING_NPC2, $1be, DIRECTIONS::DOWN, $396
.word $8208 ;sprite
.byte SCRIPTS::J_TALK, OBJ_REINDEER_BEGGIRL_JTALK0-OBJ_REINDEER_BEGGIRL
.byte SCRIPTS::DIALOGUE
.word UMSG::REINDEER_BEGGIRL
      OBJ_REINDEER_BEGGIRL_JTALK0:
.byte 0

OBJ_ELLAY_LHBACKROOMGUY:
objectDef OBJ_TYPE::WANDERING_NPC2, $2ad, DIRECTIONS::RIGHT, $3cb
.word $82C8 ;sprite
.byte SCRIPTS::J_TALK, OBJ_ELLAY_LHBACKROOMGUY_JTALK0-OBJ_ELLAY_LHBACKROOMGUY
.byte SCRIPTS::FJ_JUMP, $3B, OBJ_ELLAY_LHBACKROOMGUY_FJJUMP1-OBJ_ELLAY_LHBACKROOMGUY
.byte SCRIPTS::DIALOGUE
.word UMSG::ELLAY_LHBACKROOMGUY_MINE
.byte 0
      OBJ_ELLAY_LHBACKROOMGUY_FJJUMP1:
.byte SCRIPTS::DIALOGUE
.word UMSG::ELLAY_LHBACKROOMGUY
      OBJ_ELLAY_LHBACKROOMGUY_JTALK0:
.byte 0

OBJ_ELLAY_LHDRINKGIRL:
objectDef OBJ_TYPE::SPINNING_NPC, $2b5, DIRECTIONS::LEFT, $3cb
.word $82A8 ;sprite
.byte SCRIPTS::J_TALK, OBJ_ELLAY_LHDRINKGIRL_JTALK0-OBJ_ELLAY_LHDRINKGIRL
.byte SCRIPTS::FJ_JUMP, $34, OBJ_ELLAY_LHDRINKGIRL_FJJUMP1-OBJ_ELLAY_LHDRINKGIRL
.byte SCRIPTS::DIALOGUE
.word UMSG::ELLAY_LHDRINKGIRL
.byte 0
      OBJ_ELLAY_LHDRINKGIRL_FJJUMP1:
.byte SCRIPTS::DIALOGUE
.word UMSG::ELLAY_LHDRINKGIRL_OFFER
.byte SCRIPTS::J_YESNO, OBJ_ELLAY_LHDRINKGIRL_JYESNO2-OBJ_ELLAY_LHDRINKGIRL
.byte SCRIPTS::F_SETFLAG, $34
.byte SCRIPTS::M_MOVE
.word OBJ_ELLAY_LHDRINKGIRL_MOVE0
.byte SCRIPTS::DIALOGUE
.word UMSG::PODUNK_PIPPI_MEET_NOYES
.byte SCRIPTS::F_SETFLAG, $2B
.byte SCRIPTS::O_SIGNAL, $17
.byte 0
      OBJ_ELLAY_LHDRINKGIRL_JYESNO2:
.byte SCRIPTS::DIALOGUE
.word UMSG::ELLAY_LHDRINKGIRL_OFFER_REFUSE
      OBJ_ELLAY_LHDRINKGIRL_JTALK0:
.byte 0
        OBJ_ELLAY_LHDRINKGIRL_MOVE0:
moveDef DIRECTIONS::UP, $6, $1
moveDef DIRECTIONS::LEFT, $6, $2
moveDef DIRECTIONS::LEFT, MOVE_CMD::MOVEFACE, $1
moveDef DIRECTIONS::RIGHT, MOVE_CMD::ABOUTFACE, $1
.byte 0

OBJ_ELLAY_LHTEDDYGIRL:
objectDef OBJ_TYPE::SPINNING_NPC, $2b0, DIRECTIONS::UP, $3cb
.word $8248 ;sprite
.byte SCRIPTS::J_TALK, OBJ_ELLAY_LHTEDDYGIRL_JTALK0-OBJ_ELLAY_LHTEDDYGIRL
.byte SCRIPTS::CJ_PRESENT, $4, OBJ_ELLAY_LHTEDDYGIRL_CJPRESENT1-OBJ_ELLAY_LHTEDDYGIRL
.byte SCRIPTS::DIALOGUE
.word UMSG::ELLAY_LHTEDDYGIRL2
.byte 0
      OBJ_ELLAY_LHTEDDYGIRL_CJPRESENT1:
.byte SCRIPTS::DIALOGUE
.word UMSG::ELLAY_LHTEDDYGIRL
      OBJ_ELLAY_LHTEDDYGIRL_JTALK0:
.byte 0

OBJ_ELLAY_LHCUTEGUY:
objectDef OBJ_TYPE::SPINNING_NPC, $2b2, DIRECTIONS::LEFT, $3c9
.word $8268 ;sprite
.byte SCRIPTS::J_TALK, OBJ_ELLAY_LHCUTEGUY_JTALK0-OBJ_ELLAY_LHCUTEGUY
.byte SCRIPTS::CJ_PRESENT, $2, OBJ_ELLAY_LHCUTEGUY_CJPRESENT1-OBJ_ELLAY_LHCUTEGUY
.byte SCRIPTS::SJ_PRESENT, $80, OBJ_ELLAY_LHCUTEGUY_CJPRESENT1-OBJ_ELLAY_LHCUTEGUY
.byte SCRIPTS::DIALOGUE
.word UMSG::ELLAY_LHCUTEGUY2
.byte 0
      OBJ_ELLAY_LHCUTEGUY_CJPRESENT1:
.byte SCRIPTS::DIALOGUE
.word UMSG::ELLAY_LHCUTEGUY
      OBJ_ELLAY_LHCUTEGUY_JTALK0:
.byte 0

OBJ_ELLAY_LHBOUNCERGIRL:
objectDef OBJ_TYPE::STATIONARY_NPC2, $2b8, DIRECTIONS::LEFT, $3c8
.word $82E8 ;sprite
.byte SCRIPTS::J_TALK, OBJ_ELLAY_LHBOUNCERGIRL_JTALK0-OBJ_ELLAY_LHBOUNCERGIRL
.byte SCRIPTS::J_UNK2, OBJ_ELLAY_LHBOUNCERGIRL_JUNK21-OBJ_ELLAY_LHBOUNCERGIRL
.byte SCRIPTS::J_UNK, OBJ_ELLAY_LHBOUNCERGIRL_JUNK2-OBJ_ELLAY_LHBOUNCERGIRL
.byte SCRIPTS::J_JUMP, OBJ_ELLAY_LHBOUNCERGIRLJ_JUMP3-OBJ_ELLAY_LHBOUNCERGIRL
      OBJ_ELLAY_LHBOUNCERGIRL_JUNK2:
.byte SCRIPTS::DIALOGUE
.word UMSG::ELLAY_LHBOUNCERGIRL
.byte SCRIPTS::M_MOVE
.word OBJ_ELLAY_LHBOUNCERGIRL_MOVE0
.byte 0
      OBJ_ELLAY_LHBOUNCERGIRLJ_JUMP3:
.byte SCRIPTS::DIALOGUE
.word UMSG::ELLAY_LHBOUNCERGIRL_TICKET
.byte 0
      OBJ_ELLAY_LHBOUNCERGIRL_JTALK0:
.byte SCRIPTS::IJ_USE, $5A, OBJ_ELLAY_LHBOUNCERGIRL_IJUSE4-OBJ_ELLAY_LHBOUNCERGIRL
.byte SCRIPTS::J_UNK2, OBJ_ELLAY_LHBOUNCERGIRL_JUNK21-OBJ_ELLAY_LHBOUNCERGIRL
.byte SCRIPTS::DIALOGUE
.word UMSG::ELLAY_LHBOUNCERGIRL2
.byte SCRIPTS::IJ_HASITEM, $5A, OBJ_ELLAY_LHBOUNCERGIRL_IJUSE4-OBJ_ELLAY_LHBOUNCERGIRL
.byte SCRIPTS::I_PICKITEM, $5A
.byte SCRIPTS::J_REMOVEITEM, OBJ_ELLAY_LHBOUNCERGIRL_IJUSE4-OBJ_ELLAY_LHBOUNCERGIRL
.byte SCRIPTS::M_MOVE
.word OBJ_ELLAY_LHBOUNCERGIRL_MOVE0
.byte 0
      OBJ_ELLAY_LHBOUNCERGIRL_JUNK21:
.byte SCRIPTS::DIALOGUE
.word UMSG::ELLAY_LHBOUNCERGIRL
      OBJ_ELLAY_LHBOUNCERGIRL_IJUSE4:
.byte 0
        OBJ_ELLAY_LHBOUNCERGIRL_MOVE0:
moveDef DIRECTIONS::UP, MOVE_CMD::ABOUTFACE, $1
moveDef DIRECTIONS::DOWN, MOVE_CMD::MOVE, $1
.byte 0

OBJ_ELLAY_LHBOUNCERGUY:
objectDef OBJ_TYPE::STATIONARY_NPC2, $2af, DIRECTIONS::RIGHT, $3c8
.word $81A8 ;sprite
.byte SCRIPTS::J_TALK, OBJ_ELLAY_LHBOUNCERGUY_JTALK0-OBJ_ELLAY_LHBOUNCERGUY
.byte SCRIPTS::DIALOGUE
.word UMSG::ELLAY_LHBOUNCERGUY_OFFER
.byte SCRIPTS::J_YESNO, OBJ_ELLAY_LHBOUNCERGUY_JYESNO1-OBJ_ELLAY_LHBOUNCERGUY
.byte SCRIPTS::M_MOVE
.word OBJ_ELLAY_LHBOUNCERGUY_MOVE0
.byte SCRIPTS::DIALOGUE
.word UMSG::ELLAY_LHBOUNCERGUY_OFFER_YES
.byte SCRIPTS::M_MOVE
.word OBJ_ELLAY_LHBOUNCERGUY_MOVE1
.byte SCRIPTS::FJ_JUMP, $35, OBJ_ELLAY_LHBOUNCERGUY_FJJUMP2-OBJ_ELLAY_LHBOUNCERGUY
.byte SCRIPTS::CJ_SELECTPARTY, $2, OBJ_ELLAY_LHBOUNCERGUY_CJSELECTPARTY3-OBJ_ELLAY_LHBOUNCERGUY
.byte SCRIPTS::LIVESHOW
.byte SCRIPTS::T_DELAY, $78
.byte SCRIPTS::M_MUSIC, $22
.byte 0
      OBJ_ELLAY_LHBOUNCERGUY_FJJUMP2:
.byte SCRIPTS::CJ_SELECTPARTY, $0, OBJ_ELLAY_LHBOUNCERGUY_CJSELECTPARTY3-OBJ_ELLAY_LHBOUNCERGUY
.byte SCRIPTS::SJ_PRESENT, $40, OBJ_ELLAY_LHBOUNCERGUY_SJPRESENT4-OBJ_ELLAY_LHBOUNCERGUY
.byte SCRIPTS::SJ_PRESENT, $80, OBJ_ELLAY_LHBOUNCERGUY_CJSELECTPARTY3-OBJ_ELLAY_LHBOUNCERGUY
.byte SCRIPTS::CJ_SELECTPARTY, $1, OBJ_ELLAY_LHBOUNCERGUY_CJSELECTPARTY3-OBJ_ELLAY_LHBOUNCERGUY
.byte SCRIPTS::SJ_PRESENT, $80, OBJ_ELLAY_LHBOUNCERGUY_CJSELECTPARTY3-OBJ_ELLAY_LHBOUNCERGUY
.byte SCRIPTS::CJ_SELECTPARTY, $2, OBJ_ELLAY_LHBOUNCERGUY_CJSELECTPARTY3-OBJ_ELLAY_LHBOUNCERGUY
.byte SCRIPTS::SJ_PRESENT, $80, OBJ_ELLAY_LHBOUNCERGUY_CJSELECTPARTY3-OBJ_ELLAY_LHBOUNCERGUY
.byte SCRIPTS::CJ_SELECTPARTY, $1, OBJ_ELLAY_LHBOUNCERGUY_CJSELECTPARTY3-OBJ_ELLAY_LHBOUNCERGUY
.byte SCRIPTS::LIVESHOW
.byte SCRIPTS::T_DELAY, $78
.byte SCRIPTS::M_MUSIC, $22
.byte SCRIPTS::O_SIGNAL, $16
.byte 0
      OBJ_ELLAY_LHBOUNCERGUY_SJPRESENT4:
.byte SCRIPTS::DIALOGUE
.word UMSG::ELLAY_LHBOUNCERGUY_STONE
.byte 0
      OBJ_ELLAY_LHBOUNCERGUY_CJSELECTPARTY3:
.byte SCRIPTS::DIALOGUE
.word UMSG::ELLAY_LHBOUNCERGUY_TRIO
.byte 0
      OBJ_ELLAY_LHBOUNCERGUY_JYESNO1:
.byte SCRIPTS::DIALOGUE
.word UMSG::ELLAY_LHBOUNCERGUY_OFFER_NO
      OBJ_ELLAY_LHBOUNCERGUY_JTALK0:
.byte 0
        OBJ_ELLAY_LHBOUNCERGUY_MOVE0:
moveDef DIRECTIONS::RIGHT, $6, $2
moveDef DIRECTIONS::UP, $6, $1
moveDef DIRECTIONS::RIGHT, $6, $4
moveDef DIRECTIONS::LEFT, MOVE_CMD::ABOUTFACE, $1
.byte 3
        OBJ_ELLAY_LHBOUNCERGUY_MOVE1:
moveDef DIRECTIONS::DOWN, MOVE_CMD::MOVEFACE, $1
moveDef DIRECTIONS::LEFT, MOVE_CMD::MOVEFACE, $6
moveDef DIRECTIONS::RIGHT, MOVE_CMD::ABOUTFACE, $1
.byte 0

OBJ_ELLAY_LHTEDDY:
objectDef $14, $2bb, DIRECTIONS::LEFT, $3c8
.word $8060 ;sprite
.byte SCRIPTS::F_APPEAR, $1
.byte SCRIPTS::J_SIGNALED, OBJ_ELLAY_LHTEDDY_JSIGNALED0-OBJ_ELLAY_LHTEDDY
.byte SCRIPTS::M_MOVE
.word OBJ_ELLAY_LHTEDDY_MOVE0
.byte SCRIPTS::DIALOGUE
.word UMSG::ELLAY_LHTEDDY_INTRO
.byte SCRIPTS::J_YESNO, OBJ_ELLAY_LHTEDDY_JYESNO1-OBJ_ELLAY_LHTEDDY
.byte SCRIPTS::DIALOGUE
.word UMSG::ELLAY_LHTEDDY_INTRO_YES
.byte SCRIPTS::J_JUMP, OBJ_ELLAY_LHTEDDYJ_JUMP2-OBJ_ELLAY_LHTEDDY
      OBJ_ELLAY_LHTEDDY_JYESNO1:
.byte SCRIPTS::DIALOGUE
.word UMSG::ELLAY_LHTEDDY_INTRO_NO
      OBJ_ELLAY_LHTEDDYJ_JUMP2:
.byte SCRIPTS::DIALOGUE
.word UMSG::ELLAY_LHTEDDY_CHALLENGE
.byte SCRIPTS::C_SELECT, $1
      OBJ_ELLAY_LHTEDDY_JNOTMAX3:
.byte SCRIPTS::N_HEAL, $FF
.byte SCRIPTS::J_NOTMAX, OBJ_ELLAY_LHTEDDY_JNOTMAX3-OBJ_ELLAY_LHTEDDY
.byte SCRIPTS::B_BATTLE, $9D
.byte SCRIPTS::M_MOVE
.word OBJ_ELLAY_LHTEDDY_MOVE1
.byte SCRIPTS::J_JUMP, OBJ_ELLAY_LHTEDDYJ_JUMP4-OBJ_ELLAY_LHTEDDY
      OBJ_ELLAY_LHTEDDYJ_JUMP9:
.byte SCRIPTS::DIALOGUE
.word UMSG::ELLAY_LHTEDDY_TEAMUP_AGREE
.byte SCRIPTS::M_MOVE
.word OBJ_ELLAY_LHTEDDY_MOVE2
.byte SCRIPTS::CJ_SELECTPARTY, $2, OBJ_ELLAY_LHTEDDY_CJSELECTPARTY5-OBJ_ELLAY_LHTEDDY
.byte SCRIPTS::CJ_CHARSELECTED, $3, OBJ_ELLAY_LHTEDDY_CJSELECTPARTY5-OBJ_ELLAY_LHTEDDY
.byte SCRIPTS::M_MOVE
.word OBJ_ELLAY_LHTEDDY_MOVE3
      OBJ_ELLAY_LHTEDDY_CJSELECTPARTY5:
.byte SCRIPTS::M_MOVE
.word OBJ_ELLAY_LHTEDDY_MOVE4
.byte SCRIPTS::DIALOGUE
.word UMSG::ELLAY_LHTEDDY_REPLACELLOYD
.byte SCRIPTS::M_MUSIC, $21
.byte SCRIPTS::T_DELAY, $B4
.byte SCRIPTS::M_MUSIC, $22
.byte SCRIPTS::M_MOVE
.word OBJ_ELLAY_LHTEDDY_MOVE5
.byte SCRIPTS::CJ_ADDCHAR, $4, OBJ_ELLAY_LHTEDDY_JSIGNALED0-OBJ_ELLAY_LHTEDDY
.byte SCRIPTS::CJ_REMOVECHAR, $3, OBJ_ELLAY_LHTEDDY_JSIGNALED0-OBJ_ELLAY_LHTEDDY
.byte SCRIPTS::F_SETFLAG, $35
      OBJ_ELLAY_LHTEDDYJ_JUMP7:
.byte SCRIPTS::C_SELECT, $3
.byte SCRIPTS::IJ_PICKCHARITEM, $0, OBJ_ELLAY_LHTEDDY_JSIGNALED0-OBJ_ELLAY_LHTEDDY
.byte SCRIPTS::J_REMOVEITEM, OBJ_ELLAY_LHTEDDY_JSIGNALED0-OBJ_ELLAY_LHTEDDY
.byte SCRIPTS::IJ_SELECTEDITEM, $3, OBJ_ELLAY_LHTEDDY_IJSELECTEDITEM6-OBJ_ELLAY_LHTEDDY
.byte SCRIPTS::J_JUMP, OBJ_ELLAY_LHTEDDYJ_JUMP7-OBJ_ELLAY_LHTEDDY
      OBJ_ELLAY_LHTEDDY_IJSELECTEDITEM6:
.byte SCRIPTS::C_SELECT, $4
.byte SCRIPTS::J_GIVEITEM, OBJ_ELLAY_LHTEDDY_JSIGNALED0-OBJ_ELLAY_LHTEDDY
.byte SCRIPTS::J_JUMP, OBJ_ELLAY_LHTEDDYJ_JUMP7-OBJ_ELLAY_LHTEDDY
      OBJ_ELLAY_LHTEDDYJ_JUMP4:
.byte SCRIPTS::DIALOGUE
.word UMSG::ELLAY_LHTEDDY_POSTFIGHT
.byte SCRIPTS::J_YESNO, OBJ_ELLAY_LHTEDDY_JYESNO8-OBJ_ELLAY_LHTEDDY
.byte SCRIPTS::J_JUMP, OBJ_ELLAY_LHTEDDYJ_JUMP9-OBJ_ELLAY_LHTEDDY
      OBJ_ELLAY_LHTEDDY_JYESNO8:
.byte SCRIPTS::DIALOGUE
.word UMSG::ELLAY_LHTEDDY_TEAMUP_DECLINE
.byte SCRIPTS::J_YESNO, OBJ_ELLAY_LHTEDDY_JYESNO10-OBJ_ELLAY_LHTEDDY
.byte SCRIPTS::J_JUMP, OBJ_ELLAY_LHTEDDYJ_JUMP9-OBJ_ELLAY_LHTEDDY
      OBJ_ELLAY_LHTEDDY_JYESNO10:
.byte SCRIPTS::DIALOGUE
.word UMSG::ELLAY_LHTEDDY_TEAMUP_DECLINE2
.byte SCRIPTS::J_YESNO, OBJ_ELLAY_LHTEDDY_JYESNO11-OBJ_ELLAY_LHTEDDY
.byte SCRIPTS::J_JUMP, OBJ_ELLAY_LHTEDDYJ_JUMP9-OBJ_ELLAY_LHTEDDY
      OBJ_ELLAY_LHTEDDY_JYESNO11:
.byte SCRIPTS::DIALOGUE
.word UMSG::ELLAY_LHTEDDY_TEAMUP_DECLINE3
.byte SCRIPTS::J_YESNO, OBJ_ELLAY_LHTEDDY_JYESNO12-OBJ_ELLAY_LHTEDDY
.byte SCRIPTS::J_JUMP, OBJ_ELLAY_LHTEDDYJ_JUMP9-OBJ_ELLAY_LHTEDDY
      OBJ_ELLAY_LHTEDDY_JYESNO12:
.byte SCRIPTS::DA_TELEPORT
doorArgDef $6, $B1, DIRECTIONS::DOWN, $13C
.byte SCRIPTS::M_MOVE
.word OBJ_ELLAY_LHTEDDY_MOVE6
      OBJ_ELLAY_LHTEDDY_JSIGNALED0:
.byte 0
        OBJ_ELLAY_LHTEDDY_MOVE0:
moveDef DIRECTIONS::LEFT, MOVE_CMD::MOVEFACE, $4
moveDef DIRECTIONS::UP, MOVE_CMD::MOVEFACE, $1
moveDef DIRECTIONS::LEFT, MOVE_CMD::MOVEFACE, $2
.byte 3
        OBJ_ELLAY_LHTEDDY_MOVE2:
moveDef DIRECTIONS::UP, MOVE_CMD::MOVEFACE, $1
moveDef DIRECTIONS::LEFT, MOVE_CMD::MOVEFACE, $2
.byte 3
        OBJ_ELLAY_LHTEDDY_MOVE3:
moveDef DIRECTIONS::LEFT, MOVE_CMD::MOVEFACE, $1
.byte 3
        OBJ_ELLAY_LHTEDDY_MOVE4:
moveDef DIRECTIONS::DOWN, MOVE_CMD::ABOUTFACE, $1
.byte 3
        OBJ_ELLAY_LHTEDDY_MOVE5:
moveDef DIRECTIONS::DOWN, MOVE_CMD::MOVEFACE, $1
moveDef DIRECTIONS::RIGHT, MOVE_CMD::ABOUTFACE, $1
.byte 0
        OBJ_ELLAY_LHTEDDY_MOVE6:
.byte 0
        OBJ_ELLAY_LHTEDDY_MOVE1:
moveDef DIRECTIONS::LEFT, MOVE_CMD::ABOUTFACE, $1
.byte 3

OBJ_ELLAY_LHCOP:
objectDef $14, $2bb, DIRECTIONS::DOWN, $3c8
.word $81C8 ;sprite
.byte SCRIPTS::F_APPEAR, $2B
.byte SCRIPTS::J_SIGNALED, OBJ_ELLAY_LHCOP_JSIGNALED0-OBJ_ELLAY_LHCOP
.byte SCRIPTS::M_MOVE
.word OBJ_ELLAY_LHCOP_MOVE0
.byte SCRIPTS::DIALOGUE
.word UMSG::ELLAY_LHCOP_ARREST
.byte SCRIPTS::M_MOVE
.word OBJ_ELLAY_LHCOP_MOVE1
      OBJ_ELLAY_LHCOP_JSIGNALED0:
.byte 0
        OBJ_ELLAY_LHCOP_MOVE0:
moveDef DIRECTIONS::LEFT, MOVE_CMD::MOVEFACE, $8
moveDef DIRECTIONS::RIGHT, MOVE_CMD::ABOUTFACE, $1
moveDef DIRECTIONS::DOWN, MOVE_CMD::ABOUTFACE, $1
moveDef DIRECTIONS::LEFT, MOVE_CMD::ABOUTFACE, $1
moveDef DIRECTIONS::LEFT, MOVE_CMD::MOVEFACE, $3
moveDef DIRECTIONS::DOWN, MOVE_CMD::MOVEFACE, $2
moveDef DIRECTIONS::RIGHT, MOVE_CMD::MOVEFACE, $1
moveDef DIRECTIONS::DOWN, MOVE_CMD::MOVEFACE, $1
moveDef DIRECTIONS::RIGHT, MOVE_CMD::MOVEFACE, $2
moveDef DIRECTIONS::UP, MOVE_CMD::MOVEFACE, $1
moveDef DIRECTIONS::LEFT, MOVE_CMD::ABOUTFACE, $1
moveDef DIRECTIONS::RIGHT, MOVE_CMD::ABOUTFACE, $1
.byte 3
        OBJ_ELLAY_LHCOP_MOVE1:
moveDef DIRECTIONS::DOWN, $6, $1
moveDef DIRECTIONS::RIGHT, $6, $2
moveDef DIRECTIONS::UP, $6, $2
moveDef DIRECTIONS::RIGHT, $6, $1
moveDef DIRECTIONS::UP, $6, $1
moveDef DIRECTIONS::RIGHT, $6, $5
moveDef DIRECTIONS::RIGHT, $2, $1
moveDef DIRECTIONS::DOWN, $2, $1
.byte 3

OBJ_ELLAY_LHCOP_JAILSCENE:
objectDef $14, $30c, DIRECTIONS::RIGHT, $3c6
.word $81C8 ;sprite
.byte SCRIPTS::F_APPEAR, $2B
.byte SCRIPTS::J_TOUCH, OBJ_ELLAY_LHCOP_JAILSCENE_JTOUCH0-OBJ_ELLAY_LHCOP_JAILSCENE
.byte SCRIPTS::DIALOGUE
.word UMSG::ELLAY_LHCOP_JAILSCENE1
.byte SCRIPTS::M_MOVE
.word OBJ_ELLAY_LHCOP_JAILSCENE_MOVE0
.byte SCRIPTS::DIALOGUE
.word UMSG::ELLAY_LHCOP_JAILSCENE2
.byte SCRIPTS::J_JUMP, OBJ_ELLAY_LHCOP_JAILSCENEJ_JUMP1-OBJ_ELLAY_LHCOP_JAILSCENE
      OBJ_ELLAY_LHCOP_JAILSCENE_JYESNO2:
.byte SCRIPTS::DIALOGUE
.word UMSG::ELLAY_LHCOP_JAILSHAME_NO
      OBJ_ELLAY_LHCOP_JAILSCENEJ_JUMP1:
.byte SCRIPTS::SLEEP
.byte SCRIPTS::DIALOGUE
.word UMSG::ELLAY_LHCOP_JAILSHAME
.byte SCRIPTS::J_YESNO, OBJ_ELLAY_LHCOP_JAILSCENE_JYESNO2-OBJ_ELLAY_LHCOP_JAILSCENE
.byte SCRIPTS::DIALOGUE
.word UMSG::ELLAY_LHCOP_JAILSHAME_YES
.byte SCRIPTS::CJ_SELECTPARTY, $0, OBJ_ELLAY_LHCOP_JAILSCENE_CJSELECTPARTY3-OBJ_ELLAY_LHCOP_JAILSCENE
.byte SCRIPTS::J_REMOVEWEAPON, OBJ_ELLAY_LHCOP_JAILSCENE_CJSELECTPARTY3-OBJ_ELLAY_LHCOP_JAILSCENE
.byte SCRIPTS::F_SETFLAG, $63
.byte SCRIPTS::DIALOGUE
.word UMSG::ELLAY_LHCOP_TAKEWEAPON
.byte SCRIPTS::F_CLEARFLAG, $2B
.byte SCRIPTS::F_SETFLAG, $2E
.byte 0
      OBJ_ELLAY_LHCOP_JAILSCENE_CJSELECTPARTY3:
.byte SCRIPTS::DIALOGUE
.word UMSG::ELLAY_LHCOP_SEEWEAPON
.byte SCRIPTS::F_CLEARFLAG, $2B
.byte SCRIPTS::F_SETFLAG, $2E
      OBJ_ELLAY_LHCOP_JAILSCENE_JTOUCH0:
.byte 0
        OBJ_ELLAY_LHCOP_JAILSCENE_MOVE0:
moveDef DIRECTIONS::LEFT, $6, $6
moveDef DIRECTIONS::UP, $6, $1
moveDef DIRECTIONS::RIGHT, $6, $1
moveDef DIRECTIONS::LEFT, MOVE_CMD::ABOUTFACE, $1
moveDef DIRECTIONS::RIGHT, MOVE_CMD::MOVEFACE, $2
moveDef DIRECTIONS::UP, MOVE_CMD::MOVEFACE, $1
moveDef DIRECTIONS::LEFT, MOVE_CMD::MOVEFACE, $3
moveDef DIRECTIONS::DOWN, MOVE_CMD::ABOUTFACE, $1
.byte 0

OBJ_ELLAY_LHCOP_JAIL:
objectDef $14, $306, DIRECTIONS::DOWN, $3c4
.word $81C8 ;sprite
.byte SCRIPTS::F_APPEAR, $2E
.byte SCRIPTS::J_TALK, OBJ_ELLAY_LHCOP_JAIL_JTALK0-OBJ_ELLAY_LHCOP_JAIL
.byte SCRIPTS::DIALOGUE
.word UMSG::ELLAY_LHCOP_JAIL
      OBJ_ELLAY_LHCOP_JAIL_JTALK0:
.byte 0

OBJ_ELLAY_JAILCOP:
objectDef OBJ_TYPE::WANDERING_NPC2, $301, DIRECTIONS::LEFT, $3c7
.word $81C8 ;sprite
.byte SCRIPTS::J_TALK, OBJ_ELLAY_JAILCOP_JTALK0-OBJ_ELLAY_JAILCOP
.byte SCRIPTS::FJ_JUMP, $63, OBJ_ELLAY_JAILCOP_FJJUMP1-OBJ_ELLAY_JAILCOP
.byte SCRIPTS::J_CONFISC, OBJ_ELLAY_JAILCOP_FJJUMP1-OBJ_ELLAY_JAILCOP
.byte SCRIPTS::DIALOGUE
.word UMSG::ELLAY_JAILCOP_HASWEAPON
.byte SCRIPTS::J_YESNO, OBJ_ELLAY_JAILCOP_JYESNO2-OBJ_ELLAY_JAILCOP
.byte SCRIPTS::J_TAKEMONEY, OBJ_ELLAY_JAILCOP_JTAKEMONEY3-OBJ_ELLAY_JAILCOP
.byte SCRIPTS::IJ_HASITEM, $0, OBJ_ELLAY_JAILCOP_IJHASITEM4-OBJ_ELLAY_JAILCOP
.byte SCRIPTS::DIALOGUE
.word UMSG::ELLAY_JAILCOP_HASWEAPON_ACCEPT
.byte SCRIPTS::J_CONFISC, OBJ_ELLAY_JAILCOP_FJJUMP1-OBJ_ELLAY_JAILCOP
.byte SCRIPTS::J_GIVEITEM, OBJ_ELLAY_JAILCOP_JTALK0-OBJ_ELLAY_JAILCOP
.byte SCRIPTS::SHOWMONEY
.byte SCRIPTS::S_PLAYSOUND, $6
.byte SCRIPTS::F_CLEARFLAG, $63
.byte 0
      OBJ_ELLAY_JAILCOP_IJHASITEM4:
.byte SCRIPTS::DIALOGUE
.word UMSG::ELLAY_JAILCOP_NOROOM
.byte SCRIPTS::J_CONFISC, OBJ_ELLAY_JAILCOP_FJJUMP1-OBJ_ELLAY_JAILCOP
.byte SCRIPTS::J_GIVEMONEY, OBJ_ELLAY_JAILCOP_JTALK0-OBJ_ELLAY_JAILCOP
.byte 0
      OBJ_ELLAY_JAILCOP_JTAKEMONEY3:
.byte SCRIPTS::DIALOGUE
.word UMSG::ELLAY_JAILCOP_NOMONEY
.byte 0
      OBJ_ELLAY_JAILCOP_JYESNO2:
.byte SCRIPTS::DIALOGUE
.word UMSG::ELLAY_JAILCOP_HASWEAPON_DECLINE
.byte 0
      OBJ_ELLAY_JAILCOP_FJJUMP1:
.byte SCRIPTS::DIALOGUE
.word UMSG::ELLAY_JAILCOP
      OBJ_ELLAY_JAILCOP_JTALK0:
.byte 0

OBJ_REINDEER_MISLAYSIGN:
objectDef $19, $158, DIRECTIONS::UP, $2ca
.word $8194 ;sprite
.byte SCRIPTS::J_CHECK, OBJ_REINDEER_MISLAYSIGN_JCHECK0-OBJ_REINDEER_MISLAYSIGN
.byte SCRIPTS::DIALOGUE
.word UMSG::REINDEER_MISLAYSIGN
.byte SCRIPTS::FJ_JUMP, $74, OBJ_REINDEER_MISLAYSIGN_FJJUMP1-OBJ_REINDEER_MISLAYSIGN
.byte SCRIPTS::J_JUMP, OBJ_REINDEER_MISLAYSIGN_JCHECK0-OBJ_REINDEER_MISLAYSIGN
      OBJ_REINDEER_MISLAYSIGN_FJJUMP1:
.byte SCRIPTS::DIALOGUE
.word UMSG::REINDEER_MISLAYSIGN2
.byte SCRIPTS::IJ_HASITEM, $0, OBJ_REINDEER_MISLAYSIGN_IJHASITEM2-OBJ_REINDEER_MISLAYSIGN
.byte SCRIPTS::I_PICKITEM, $63
.byte SCRIPTS::J_GIVEITEM, OBJ_REINDEER_MISLAYSIGN_JCHECK0-OBJ_REINDEER_MISLAYSIGN
.byte SCRIPTS::S_PLAYSOUND, $6
.byte SCRIPTS::F_SETFLAG, $74
.byte 0
      OBJ_REINDEER_MISLAYSIGN_IJHASITEM2:
.byte SCRIPTS::DIALOGUE
.word UMSG::INVENTORY_FULL
      OBJ_REINDEER_MISLAYSIGN_JCHECK0:
.byte 0