OBJ_BANK_5:
.addr OBJ_REINDEER_DEPTENTRANCE
.addr OBJ_REINDEER_HOSPITALENTRANCE
.addr OBJ_REINDEER_BURGERENTRANCE
.addr OBJ_REINDEER_HOTELENTRANCE
.addr OBJ_ELLAY_LIVEHOUSESIDEOUT
.addr OBJ_ELLAY_LHSIDEGUY
.addr OBJ_REINDEER_MONEYGUY
.addr OBJ_REINDEER_FULLGIRL
.addr OBJ_REINDEER_ELLAYGUY
.addr OBJ_REINDEER_SINGINGGUY
.addr OBJ_REINDEER_COLDGUY
.addr OBJ_REINDEER_FLUGUY
.addr OBJ_REINDEER_FLEABAGGIRL
.addr OBJ_REINDEER_BEAUTYGIRL
.addr OBJ_REINDEER_NONBELIEVERGUY
.addr OBJ_REINDEER_NIHILISTICGUY
.addr OBJ_REINDEER_SPOOKANEGIRL2
.addr OBJ_REINDEER_CHARITYWOMAN
.addr OBJ_REINDEER_MEDICINEGUY
.addr OBJ_REINDEER_COP1
.addr OBJ_REINDEER_COP2
.addr OBJ_REINDEER_DRAGONGIRL
.addr OBJ_REINDEER_TELEPORTGAIN1
.addr OBJ_REINDEER_TELEPORTGAIN2
.addr OBJ_REINDEER_TELEPORTGAIN3
.addr OBJ_REINDEER_TELEPORTGAIN4
.addr OBJ_REINDEER_TELEPORTGAIN5
.addr OBJ_REINDEER_TELEPORTGAIN6
.addr OBJ_REINDEER_TELEPORTGAIN7
.addr OBJ_REINDEER_TELEPORTGAIN8
.addr OBJ_REINDEER_TELEPORTGAIN9
.addr OBJ_REINDEER_TELEPORTGAINA
.addr 0

OBJ_REINDEER_DEPTENTRANCE:
objectDef OBJ_TYPE::DOOR, $1ba, DIRECTIONS::UP, $3bc
doorArgDef $F, $1CD, DIRECTIONS::LEFT, $96

OBJ_REINDEER_HOSPITALENTRANCE:
objectDef OBJ_TYPE::DOOR, $1e6, DIRECTIONS::UP, $3ac
doorArgDef $12, $2DD, DIRECTIONS::LEFT, $3F6

OBJ_REINDEER_BURGERENTRANCE:
objectDef OBJ_TYPE::DOOR, $1d3, DIRECTIONS::UP, $3bc
doorArgDef $F, $24D, DIRECTIONS::LEFT, $96

OBJ_REINDEER_HOTELENTRANCE:
objectDef OBJ_TYPE::DOOR, $1a7, DIRECTIONS::UP, $3bc
doorArgDef $12, $D, DIRECTIONS::LEFT, $106

OBJ_ELLAY_LIVEHOUSESIDEOUT:
objectDef OBJ_TYPE::DOOR, $2ee, DIRECTIONS::RIGHT, $3c6
doorArgDef $0, $2AA, DIRECTIONS::RIGHT, $3CA

OBJ_ELLAY_LHSIDEGUY:
objectDef OBJ_TYPE::WANDERING_NPC, $2e6, DIRECTIONS::RIGHT, $3c6
.addr SPRITEDEF_7A ;sprite
OBJ_IS_NOT_TALKING  OBJ_ELLAY_LHSIDEGUY_JTALK0-OBJ_ELLAY_LHSIDEGUY
OBJ_IS_NOT_FLAG  $3B, OBJ_ELLAY_LHSIDEGUY_FJJUMP1-OBJ_ELLAY_LHSIDEGUY
OBJ_DIALOGUE UMSG::ELLAY_LHSIDEGUY_MINE
OBJ_STOP
    OBJ_ELLAY_LHSIDEGUY_FJJUMP1:
OBJ_DIALOGUE UMSG::ELLAY_LHSIDEGUY
    OBJ_ELLAY_LHSIDEGUY_JTALK0:
OBJ_STOP

OBJ_REINDEER_MONEYGUY:
objectDef OBJ_TYPE::WANDERINGFAST_NPC, $1b1, DIRECTIONS::RIGHT, $3bd
.addr SPRITEDEF_6A ;sprite
OBJ_IS_NOT_TALKING  OBJ_REINDEER_MONEYGUY_JTALK0-OBJ_REINDEER_MONEYGUY
OBJ_IS_NOT_FLAG  $36, OBJ_REINDEER_MONEYGUY_FJJUMP1-OBJ_REINDEER_MONEYGUY
OBJ_JUMP  OBJ_REINDEER_MONEYGUYJ_JUMP2-OBJ_REINDEER_MONEYGUY
    OBJ_REINDEER_MONEYGUY_FJJUMP1:
OBJ_DIALOGUE UMSG::REINDEER_MONEYGUY
OBJ_YESNO_IS_NO  OBJ_REINDEER_MONEYGUY_JYESNO3-OBJ_REINDEER_MONEYGUY
OBJ_DIALOGUE UMSG::REINDEER_MONEYGUY_ACCEPT
OBJ_JUMP  OBJ_REINDEER_MONEYGUYJ_JUMP4-OBJ_REINDEER_MONEYGUY
    OBJ_REINDEER_MONEYGUY_JYESNO3:
OBJ_DIALOGUE UMSG::REINDEER_MONEYGUY_DECLINE
    OBJ_REINDEER_MONEYGUYJ_JUMP4:
OBJ_PLAY_SOUND  $6
OPJ_LOAD_NUMBER 423
OBJ_GIVE_WEAPON OBJ_REINDEER_MONEYGUY_JGIVEMONEY5-OBJ_REINDEER_MONEYGUY
OBJ_SHOW_MONEY
    OBJ_REINDEER_MONEYGUY_JGIVEMONEY5:
OBJ_SET_FLAG  $36
OBJ_STOP
    OBJ_REINDEER_MONEYGUYJ_JUMP2:
OBJ_DIALOGUE UMSG::REINDEER_MONEYGUY_AFTER
    OBJ_REINDEER_MONEYGUY_JTALK0:
OBJ_STOP

OBJ_REINDEER_FULLGIRL:
objectDef OBJ_TYPE::WANDERING_NPC, $1b0, DIRECTIONS::LEFT, $3d1
.addr SPRITEDEF_7A ;sprite
OBJ_IS_NOT_TALKING  OBJ_REINDEER_FULLGIRL_JTALK0-OBJ_REINDEER_FULLGIRL
OBJ_DIALOGUE UMSG::REINDEER_FULLGIRL
    OBJ_REINDEER_FULLGIRL_JTALK0:
OBJ_STOP

OBJ_REINDEER_ELLAYGUY:
objectDef OBJ_TYPE::WANDERING_NPC, $1c2, DIRECTIONS::DOWN, $3c2
.addr SPRITEDEF_8A ;sprite
OBJ_IS_NOT_TALKING  OBJ_REINDEER_ELLAYGUY_JTALK0-OBJ_REINDEER_ELLAYGUY
OBJ_DIALOGUE UMSG::REINDEER_ELLAYGUY
    OBJ_REINDEER_ELLAYGUY_JTALK0:
OBJ_STOP

OBJ_REINDEER_SINGINGGUY:
objectDef OBJ_TYPE::WANDERING_NPC, $1c7, DIRECTIONS::UP, $3b8
.addr SPRITEDEF_9A ;sprite
OBJ_IS_NOT_TALKING  OBJ_REINDEER_SINGINGGUY_JTALK0-OBJ_REINDEER_SINGINGGUY
OBJ_DIALOGUE UMSG::REINDEER_SINGINGGUY
OBJ_YESNO_IS_NO  OBJ_REINDEER_SINGINGGUY_JYESNO1-OBJ_REINDEER_SINGINGGUY
OBJ_DIALOGUE UMSG::REINDEER_SINGINGGUY_ACCEPT
OBJ_YESNO_IS_NO  OBJ_REINDEER_SINGINGGUY_JYESNO2-OBJ_REINDEER_SINGINGGUY
OBJ_PLAY_MUSIC  $22
OBJ_DIALOGUE UMSG::REINDEER_SINGINGGUY_ACCEPT2
OBJ_PLAY_MUSIC  $6
OBJ_STOP
    OBJ_REINDEER_SINGINGGUY_JYESNO2:
OBJ_DIALOGUE UMSG::REINDEER_SINGINGGUY_DECLINE2
OBJ_STOP
    OBJ_REINDEER_SINGINGGUY_JYESNO1:
OBJ_DIALOGUE UMSG::REINDEER_SINGINGGUY_DECLINE
    OBJ_REINDEER_SINGINGGUY_JTALK0:
OBJ_STOP

OBJ_REINDEER_COLDGUY:
objectDef OBJ_TYPE::WANDERING_NPC, $1e8, DIRECTIONS::RIGHT, $3af
.addr SPRITEDEF_B2 ;sprite
OBJ_IS_NOT_TALKING  OBJ_REINDEER_COLDGUY_JTALK0-OBJ_REINDEER_COLDGUY
OBJ_DIALOGUE UMSG::REINDEER_COLDGUY
    OBJ_REINDEER_COLDGUY_JTALK0:
OBJ_STOP

OBJ_REINDEER_FLUGUY:
objectDef OBJ_TYPE::STATIONARY_NPC, $1a9, DIRECTIONS::DOWN, $3cb
.addr SPRITEDEF_B2 ;sprite
OBJ_IS_NOT_TALKING  OBJ_REINDEER_FLUGUY_JTALK0-OBJ_REINDEER_FLUGUY
OBJ_DIALOGUE UMSG::REINDEER_FLUGUY
OBJ_PICK_CHARACTER_J  $0, OBJ_REINDEER_FLUGUY_JTALK0-OBJ_REINDEER_FLUGUY
OBJ_GIVE_STATUS $1
    OBJ_REINDEER_FLUGUY_JTALK0:
OBJ_STOP

OBJ_REINDEER_FLEABAGGIRL:
objectDef OBJ_TYPE::WANDERING_NPC, $1d6, DIRECTIONS::LEFT, $3cc
.addr SPRITEDEF_82 ;sprite
OBJ_IS_NOT_TALKING  OBJ_REINDEER_FLEABAGGIRL_JTALK0-OBJ_REINDEER_FLEABAGGIRL
OBJ_DIALOGUE UMSG::REINDEER_FLEABAGGIRL
OBJ_YESNO_IS_NO  OBJ_REINDEER_FLEABAGGIRL_JYESNO1-OBJ_REINDEER_FLEABAGGIRL
OBJ_DIALOGUE UMSG::REINDEER_FLEABAGGIRL2
    OBJ_REINDEER_FLEABAGGIRL_JUNSELLABLE2:
OBJ_DIALOGUE UMSG::REINDEER_FLEABAGGIRL_ACCEPT
OBJ_CHOOSE_ITEM OBJ_REINDEER_FLEABAGGIRL_JYESNO1-OBJ_REINDEER_FLEABAGGIRL
OBJ_UNSELLABLE OBJ_REINDEER_FLEABAGGIRL_JUNSELLABLE2-OBJ_REINDEER_FLEABAGGIRL
OBJ_DIALOGUE UMSG::REINDEER_FLEABAGGIRL_GIVE
OBJ_PLAY_SOUND  $6
OBJ_PICK_ITEM  $1B
OBJ_GIVE_ITEM OBJ_REINDEER_FLEABAGGIRL_JYESNO1-OBJ_REINDEER_FLEABAGGIRL
OBJ_STOP
    OBJ_REINDEER_FLEABAGGIRL_JYESNO1:
OBJ_DIALOGUE UMSG::REINDEER_FLEABAGGIRL_DECLINE
    OBJ_REINDEER_FLEABAGGIRL_JTALK0:
OBJ_STOP

OBJ_REINDEER_BEAUTYGIRL:
objectDef OBJ_TYPE::WANDERING_NPC, $1be, DIRECTIONS::DOWN, $3be
.addr SPRITEDEF_92 ;sprite
OBJ_IS_NOT_TALKING  OBJ_REINDEER_BEAUTYGIRL_JTALK0-OBJ_REINDEER_BEAUTYGIRL
OBJ_DIALOGUE UMSG::REINDEER_BEAUTYGIRL
    OBJ_REINDEER_BEAUTYGIRL_JTALK0:
OBJ_STOP

OBJ_REINDEER_NONBELIEVERGUY:
objectDef OBJ_TYPE::WANDERING_NPC, $1dc, DIRECTIONS::LEFT, $3bb
.addr SPRITEDEF_9A ;sprite
OBJ_IS_NOT_TALKING  OBJ_REINDEER_NONBELIEVERGUY_JTALK0-OBJ_REINDEER_NONBELIEVERGUY
OBJ_DIALOGUE UMSG::REINDEER_NONBELIEVERGUY
    OBJ_REINDEER_NONBELIEVERGUY_JTALK0:
OBJ_STOP

OBJ_REINDEER_NIHILISTICGUY:
objectDef OBJ_TYPE::WANDERING_NPC, $1e0, DIRECTIONS::RIGHT, $3b2
.addr SPRITEDEF_8A ;sprite
OBJ_IS_NOT_TALKING  OBJ_REINDEER_NIHILISTICGUY_JTALK0-OBJ_REINDEER_NIHILISTICGUY
OBJ_DIALOGUE UMSG::REINDEER_NIHILISTICGUY
    OBJ_REINDEER_NIHILISTICGUY_JTALK0:
OBJ_STOP

OBJ_REINDEER_SPOOKANEGIRL2:
objectDef OBJ_TYPE::WANDERING_NPC, $1bf, DIRECTIONS::UP, $3b2
.addr SPRITEDEF_AA ;sprite
OBJ_IS_NOT_TALKING  OBJ_REINDEER_SPOOKANEGIRL2_JTALK0-OBJ_REINDEER_SPOOKANEGIRL2
OBJ_DIALOGUE UMSG::REINDEER_SPOOKANEGIRL2
    OBJ_REINDEER_SPOOKANEGIRL2_JTALK0:
OBJ_STOP

OBJ_REINDEER_CHARITYWOMAN:
objectDef OBJ_TYPE::WANDERING_NPC, $1ba, DIRECTIONS::DOWN, $3ca
.addr SPRITEDEF_A2 ;sprite
OBJ_IS_NOT_TALKING  OBJ_REINDEER_CHARITYWOMAN_JTALK0-OBJ_REINDEER_CHARITYWOMAN
OBJ_DIALOGUE UMSG::REINDEER_CHARITYWOMAN
    OBJ_REINDEER_CHARITYWOMAN_JTALK0:
OBJ_STOP

OBJ_REINDEER_MEDICINEGUY:
objectDef OBJ_TYPE::WANDERING_NPC, $1c2, DIRECTIONS::RIGHT, $3b2
.addr SPRITEDEF_8A ;sprite
OBJ_IS_NOT_TALKING  OBJ_REINDEER_MEDICINEGUY_JTALK0-OBJ_REINDEER_MEDICINEGUY
OBJ_DIALOGUE UMSG::REINDEER_MEDICINEGUY
    OBJ_REINDEER_MEDICINEGUY_JTALK0:
OBJ_STOP

OBJ_REINDEER_COP1:
objectDef OBJ_TYPE::WANDERING_NPC, $1d6, DIRECTIONS::LEFT, $3be
.addr SPRITEDEF_72 ;sprite
OBJ_IS_NOT_TALKING  OBJ_REINDEER_COP1_JTALK0-OBJ_REINDEER_COP1
OBJ_DIALOGUE UMSG::REINDEER_COP1
OBJ_YESNO_IS_NO  OBJ_REINDEER_COP1_JYESNO1-OBJ_REINDEER_COP1
OBJ_DIALOGUE UMSG::REINDEER_COP1_ACCEPT
OBJ_STOP
    OBJ_REINDEER_COP1_JYESNO1:
OBJ_DIALOGUE UMSG::REINDEER_COP1_DECLINE
    OBJ_REINDEER_COP1_JTALK0:
OBJ_STOP

OBJ_REINDEER_COP2:
objectDef OBJ_TYPE::WANDERING_NPC, $1c3, DIRECTIONS::RIGHT, $3cb
.addr SPRITEDEF_72 ;sprite
OBJ_IS_NOT_TALKING  OBJ_REINDEER_COP2_JTALK0-OBJ_REINDEER_COP2
OBJ_DIALOGUE UMSG::REINDEER_COP2
OBJ_YESNO_IS_NO  OBJ_REINDEER_COP2_JYESNO1-OBJ_REINDEER_COP2
OBJ_DIALOGUE UMSG::REINDEER_COP2_ACCEPT
OBJ_STOP
    OBJ_REINDEER_COP2_JYESNO1:
OBJ_DIALOGUE UMSG::REINDEER_COP2_DECLINE
    OBJ_REINDEER_COP2_JTALK0:
OBJ_STOP

OBJ_REINDEER_DRAGONGIRL:
objectDef OBJ_TYPE::STATIONARY_NPC, $1d9, DIRECTIONS::DOWN, $3c5
.addr SPRITEDEF_AA ;sprite
OBJ_IS_NOT_CHECKING  OBJ_REINDEER_DRAGONGIRL_JCHECK0-OBJ_REINDEER_DRAGONGIRL
OBJ_DIALOGUE UMSG::REINDEER_DRAGONGIRL_CHECK
OBJ_STOP
    OBJ_REINDEER_DRAGONGIRL_JCHECK0:
OBJ_IS_NOT_TALKING  OBJ_REINDEER_DRAGONGIRL_JTALK1-OBJ_REINDEER_DRAGONGIRL
OBJ_DIALOGUE UMSG::CANARY_GENERIC
OBJ_STOP
    OBJ_REINDEER_DRAGONGIRL_JTALK1:
OBJ_IS_NOT_CASTING  $1, OBJ_REINDEER_DRAGONGIRL_PJUSE2-OBJ_REINDEER_DRAGONGIRL
OBJ_DIALOGUE UMSG::REINDEER_DRAGONGIRL
    OBJ_REINDEER_DRAGONGIRL_PJUSE2:
OBJ_STOP

OBJ_REINDEER_TELEPORTGAIN1:
objectDef OBJ_TYPE::FLAGSET_SEE, $1ad, DIRECTIONS::UP, $3c4
teleportFlagDef 3, $1D
OBJ_STOP
OBJ_REINDEER_TELEPORTGAIN2:
objectDef OBJ_TYPE::FLAGSET_SEE, $1bb, DIRECTIONS::UP, $3c4
teleportFlagDef 3, $1D
OBJ_STOP
OBJ_REINDEER_TELEPORTGAIN3:
objectDef OBJ_TYPE::FLAGSET_SEE, $1c9, DIRECTIONS::UP, $3c4
teleportFlagDef 3, $1D
OBJ_STOP
OBJ_REINDEER_TELEPORTGAIN4:
objectDef OBJ_TYPE::FLAGSET_SEE, $1d7, DIRECTIONS::UP, $3c0
teleportFlagDef 3, $1D
OBJ_STOP
OBJ_REINDEER_TELEPORTGAIN5:
objectDef OBJ_TYPE::FLAGSET_SEE, $1e5, DIRECTIONS::UP, $3c0
teleportFlagDef 3, $1D
OBJ_STOP
OBJ_REINDEER_TELEPORTGAIN6:
objectDef OBJ_TYPE::FLAGSET_SEE, $1ad, DIRECTIONS::UP, $3b6
teleportFlagDef 3, $1D
OBJ_STOP
OBJ_REINDEER_TELEPORTGAIN7:
objectDef OBJ_TYPE::FLAGSET_SEE, $1bb, DIRECTIONS::UP, $3b6
teleportFlagDef 3, $1D
OBJ_STOP
OBJ_REINDEER_TELEPORTGAIN8:
objectDef OBJ_TYPE::FLAGSET_SEE, $1c9, DIRECTIONS::UP, $3b6
teleportFlagDef 3, $1D
OBJ_STOP
OBJ_REINDEER_TELEPORTGAIN9:
objectDef OBJ_TYPE::FLAGSET_SEE, $1d7, DIRECTIONS::UP, $3b2
teleportFlagDef 3, $1D
OBJ_STOP
OBJ_REINDEER_TELEPORTGAINA:
objectDef OBJ_TYPE::FLAGSET_SEE, $1e5, DIRECTIONS::UP, $3b2
teleportFlagDef 3, $1D
OBJ_STOP