OBJ_BANK_19:
.addr OBJ_MYHOME_NINTENROOMEXIT
.addr OBJ_MYHOME_DOWNSTAIRS
.addr OBJ_MYHOME_NINTENROOMENTRANCE
.addr OBJ_MYHOME_MIMMIEROOMENTRANCE
.addr OBJ_MYHOME_MINNIEROOMENTRANCE
.addr OBJ_SPOOKANE_HOTELEXIT
.addr OBJ_SPOOKANE_HOTELUPSTAIRS
.addr OBJ_SPOOKANE_HOSPTIALEXIT
.addr OBJ_SPOOKANE_HOSPTIALOFFICEENTRANCE
.addr OBJ_SPOOKANE_HOSPTIALUPSTAIRS
.addr OBJ_PODUNK_HOSPITALUPROOM1EXIT
.addr OBJ_PODUNK_HOSPITALUPROOM1ENTRANCE
.addr OBJ_PODUNK_HOSPITALUPROOM2EXIT
.addr OBJ_PODUNK_HOSPITALUPROOM2ENTRANCE
.addr OBJ_PODUNK_HOSPITALDOWNSTAIRS
.addr OBJ_PODUNK_HOTELDOWNSTAIRS
.addr OBJ_PODUNK_HOTELUPROOM1ENTRANCE
.addr OBJ_PODUNK_HOTELUPROOM2ENTRANCE
.addr OBJ_SNOWMAN_FAKEHOTELEXIT
.addr OBJ_SNOWMAN_FAKEHOTELROOM1ENTRANCE
.addr OBJ_SNOWMAN_FAKEHOTELROOM2ENTRANCE
.addr OBJ_SNOWMAN_FAKEHOTELROOM1EXIT
.addr OBJ_SNOWMAN_FAKEHOTELROOM2EXIT
.addr OBJ_SNOWMAN_FAKEHOTELBELLHOP
.addr OBJ_MYHOME_LAMPTRIGGER
.addr OBJ_MYHOME_LAMP
.addr OBJ_SPOOKANE_HOTELBELLHOP
.addr 0

OBJ_MYHOME_NINTENROOMEXIT:
objectDef OBJ_TYPE::DOOR, $22, DIRECTIONS::LEFT, $c5
doorArgDef $0, $2D, DIRECTIONS::LEFT, $E6

OBJ_MYHOME_DOWNSTAIRS:
objectDef OBJ_TYPE::STAIRS, $21, DIRECTIONS::LEFT, $e6
doorArgDef $0, $23, DIRECTIONS::RIGHT, $85

OBJ_MYHOME_NINTENROOMENTRANCE:
objectDef OBJ_TYPE::DOOR, $2e, DIRECTIONS::RIGHT, $e6
doorArgDef $0, $23, DIRECTIONS::RIGHT, $C5

OBJ_MYHOME_MIMMIEROOMENTRANCE:
objectDef OBJ_TYPE::DOOR, $26, DIRECTIONS::UP, $e3
doorArgDef $0, $1CD, DIRECTIONS::LEFT, $86

OBJ_MYHOME_MINNIEROOMENTRANCE:
objectDef OBJ_TYPE::DOOR, $29, DIRECTIONS::UP, $e3
doorArgDef $0, $27D, DIRECTIONS::LEFT, $3F6

OBJ_SPOOKANE_HOTELEXIT:
objectDef OBJ_TYPE::DOOR, $e, DIRECTIONS::RIGHT, $e6
doorArgDef $6, $2A7, DIRECTIONS::DOWN, $36D

OBJ_SPOOKANE_HOTELUPSTAIRS:
objectDef OBJ_TYPE::STAIRS, $2, DIRECTIONS::LEFT, $e5
doorArgDef $0, $32, DIRECTIONS::RIGHT, $D6

OBJ_SPOOKANE_HOSPTIALEXIT:
objectDef OBJ_TYPE::DOOR, $25e, DIRECTIONS::RIGHT, $3d6
doorArgDef $6, $2A7, DIRECTIONS::DOWN, $355

OBJ_SPOOKANE_HOSPTIALOFFICEENTRANCE:
objectDef OBJ_TYPE::DOOR, $258, DIRECTIONS::UP, $3d3
doorArgDef $0, $1D, DIRECTIONS::LEFT, $136

OBJ_SPOOKANE_HOSPTIALUPSTAIRS:
objectDef OBJ_TYPE::STAIRS, $252, DIRECTIONS::LEFT, $3d5
doorArgDef $0, $32, DIRECTIONS::RIGHT, $136

OBJ_PODUNK_HOSPITALUPROOM1EXIT:
objectDef OBJ_TYPE::DOOR, $2ae, DIRECTIONS::RIGHT, $86
doorArgDef $0, $306, DIRECTIONS::DOWN, $84

OBJ_PODUNK_HOSPITALUPROOM1ENTRANCE:
objectDef OBJ_TYPE::DOOR, $306, DIRECTIONS::UP, $83
doorArgDef $0, $2AD, DIRECTIONS::LEFT, $86

OBJ_PODUNK_HOSPITALUPROOM2EXIT:
objectDef OBJ_TYPE::DOOR, $32e, DIRECTIONS::RIGHT, $86
doorArgDef $0, $309, DIRECTIONS::DOWN, $84

OBJ_PODUNK_HOSPITALUPROOM2ENTRANCE:
objectDef OBJ_TYPE::DOOR, $309, DIRECTIONS::UP, $83
doorArgDef $0, $32D, DIRECTIONS::LEFT, $86

OBJ_PODUNK_HOSPITALDOWNSTAIRS:
objectDef OBJ_TYPE::STAIRS, $301, DIRECTIONS::LEFT, $86
doorArgDef $0, $313, DIRECTIONS::RIGHT, $3F5

OBJ_PODUNK_HOTELDOWNSTAIRS:
objectDef OBJ_TYPE::STAIRS, $1, DIRECTIONS::LEFT, $a6
doorArgDef $0, $253, DIRECTIONS::RIGHT, $3B5

OBJ_PODUNK_HOTELUPROOM1ENTRANCE:
objectDef OBJ_TYPE::DOOR, $6, DIRECTIONS::UP, $a3
doorArgDef $0, $2CD, DIRECTIONS::LEFT, $86

OBJ_PODUNK_HOTELUPROOM2ENTRANCE:
objectDef OBJ_TYPE::DOOR, $9, DIRECTIONS::UP, $a3
doorArgDef $0, $34D, DIRECTIONS::LEFT, $86

OBJ_SNOWMAN_FAKEHOTELEXIT:
objectDef OBJ_TYPE::DOOR, $3ae, DIRECTIONS::RIGHT, $86
doorArgDef $A, $38D, DIRECTIONS::DOWN, $3E4

OBJ_SNOWMAN_FAKEHOTELROOM1ENTRANCE:
objectDef OBJ_TYPE::DOOR, $3a2, DIRECTIONS::LEFT, $85
doorArgDef $0, $38D, DIRECTIONS::LEFT, $A6

OBJ_SNOWMAN_FAKEHOTELROOM2ENTRANCE:
objectDef OBJ_TYPE::DOOR, $3a0, DIRECTIONS::LEFT, $87
doorArgDef $0, $38D, DIRECTIONS::LEFT, $C6

OBJ_SNOWMAN_FAKEHOTELROOM1EXIT:
objectDef OBJ_TYPE::DOOR, $38e, DIRECTIONS::RIGHT, $a6
doorArgDef $0, $3A3, DIRECTIONS::RIGHT, $85

OBJ_SNOWMAN_FAKEHOTELROOM2EXIT:
objectDef OBJ_TYPE::DOOR, $38e, DIRECTIONS::RIGHT, $c6
doorArgDef $0, $3A1, DIRECTIONS::RIGHT, $87

OBJ_SNOWMAN_FAKEHOTELBELLHOP:
objectDef OBJ_TYPE::STATIONARY_NPC, $3a6, DIRECTIONS::UP, $84
.addr SPRITEDEF_PIPPI_MOM ;sprite
OBJ_IS_NOT_TALKING @JTALK0-OBJ_SNOWMAN_FAKEHOTELBELLHOP
OBJ_LOAD_NUMBER 125
OBJ_MULTIPLY_BY_PARTY
OBJ_DIALOGUE UMSG::HOTELBELLHOP
OBJ_YESNO_IS_NO @JYESNO1-OBJ_SNOWMAN_FAKEHOTELBELLHOP
OBJ_TAKE_MONEY @JTAKEMONEY2-OBJ_SNOWMAN_FAKEHOTELBELLHOP
OBJ_DIALOGUE UMSG::HOTELBELLHOP_ACCEPT
OBJ_SLEEP
OBJ_DIALOGUE UMSG::HOTELBELLHOP_GOODMORNING
OBJ_STOP
    @JTAKEMONEY2:
OBJ_DIALOGUE UMSG::HOSPITAL_NURSE_NOMONEY
OBJ_STOP
    @JYESNO1:
OBJ_DIALOGUE UMSG::HOTELBELLHOP_DECLINE
    @JTALK0:
OBJ_STOP

OBJ_MYHOME_LAMPTRIGGER:
objectDef OBJ_TYPE::TRIGGER_CHECKSPAWN, $23, DIRECTIONS::UP, $c5
OBJ_FLAG_DISAPPEAR $30
OBJ_IS_NOT_TOUCHING @JTOUCH0-OBJ_MYHOME_LAMPTRIGGER
OBJ_SIGNAL $19
    @JTOUCH0:
OBJ_STOP

OBJ_MYHOME_LAMP:
objectDef $1d, $28, DIRECTIONS::UP, $c5
.addr SPRITEDEF_LAMP ;sprite
OBJ_FLAG_DISAPPEAR $30
OBJ_IS_SIGNAL @JSIGNALED0-OBJ_MYHOME_LAMP
OBJ_PLAY_MUSIC $10
OBJ_MOVE @MOVE0
OBJ_BATTLE $A0
OBJ_SET_FLAG $F8
OBJ_SET_FLAG $30
OBJ_MOVE @MOVE1
    @JSIGNALED0:
OBJ_STOP
    @MOVE0:
moveDef DIRECTIONS::UP_LEFT, MOVE_CMD::MOVE, $2
moveDef DIRECTIONS::DOWN_LEFT, MOVE_CMD::MOVE, $2
moveDef DIRECTIONS::DOWN_RIGHT, MOVE_CMD::MOVE, $2
moveDef DIRECTIONS::UP_RIGHT, MOVE_CMD::MOVE, $2
moveDef DIRECTIONS::LEFT, MOVE_CMD::MOVE, $4
.byte 3
    @MOVE1:
OBJ_STOP

OBJ_SPOOKANE_HOTELBELLHOP:
objectDef OBJ_TYPE::STATIONARY_NPC_CHECKSPAWN, $8, DIRECTIONS::UP, $e4
.addr SPRITEDEF_SPOOKANE_BELLHOP ;sprite
OBJ_FLAG_DISAPPEAR $7A
OBJ_IS_NOT_TALKING @JTALK0-OBJ_SPOOKANE_HOTELBELLHOP
OBJ_LOAD_NUMBER 6
OBJ_MULTIPLY_BY_PARTY
OBJ_DIALOGUE UMSG::HOTELBELLHOP
OBJ_YESNO_IS_NO @JYESNO1-OBJ_SPOOKANE_HOTELBELLHOP
OBJ_TAKE_MONEY @JTAKEMONEY2-OBJ_SPOOKANE_HOTELBELLHOP
OBJ_DIALOGUE UMSG::HOTELBELLHOP_ACCEPT
OBJ_DIALOGUE UMSG::SPOOKANE_HOTELBELLHOP
OBJ_SLEEP
OBJ_SHOW_MONEY
OBJ_DIALOGUE UMSG::SPOOKANE_HOTELBELLHOP_THANKS
OBJ_BATTLE $69
OBJ_SET_FLAG $7A
OBJ_STOP
    @JTAKEMONEY2:
OBJ_DIALOGUE UMSG::HOSPITAL_NURSE_NOMONEY
OBJ_STOP
    @JYESNO1:
OBJ_DIALOGUE UMSG::HOTELBELLHOP_DECLINE
    @JTALK0:
OBJ_STOP