OBJ_BANK_6:
.addr OBJ_SPOOKANE_MANSIONENTRANCE
.addr OBJ_SPOOKANE_RUMORGUY
.addr OBJ_SPOOKANE_ROSEMARYGUY
.addr OBJ_SPOOKANE_SMALLGUY
.addr OBJ_SPOOKANE_CLOWN
.addr OBJ_SPOOKANE_HINTGIRL
.addr OBJ_SPOOKANE_MRROSEMARY
.addr OBJ_SPOOKANE_MRSROSEMARY
.addr OBJ_SPOOKANE_NINTENROSEMARY
.addr OBJ_SPOOKANE_POSTMANGIRL
.addr OBJ_SPOOKANE_HATERGIRL
.addr OBJ_SPOOKANE_STREETSGIRL
.addr OBJ_SPOOKANE_WHATGUY
.addr OBJ_SPOOKANE_POSTMAN
.addr OBJ_SPOOKANE_TELEPORTGAIN1
.addr OBJ_SPOOKANE_TELEPORTGAIN2
.addr 0

OBJ_SPOOKANE_MANSIONENTRANCE:
objectDef $18, $2f8, DIRECTIONS::UP, $325
.byte SCRIPTS::J_UNK, OBJ_SPOOKANE_MANSIONENTRANCE_JUNK0-OBJ_SPOOKANE_MANSIONENTRANCE
.byte SCRIPTS::J_TOUCH, OBJ_SPOOKANE_MANSIONENTRANCE_JTOUCH1-OBJ_SPOOKANE_MANSIONENTRANCE
.byte SCRIPTS::DIALOGUE
.word UMSG::DOOR_LOCKED
.byte 0
    OBJ_SPOOKANE_MANSIONENTRANCE_JTOUCH1:
.byte SCRIPTS::IJ_USE, $57, OBJ_SPOOKANE_MANSIONENTRANCE_IJUSE2-OBJ_SPOOKANE_MANSIONENTRANCE
.byte SCRIPTS::DIALOGUE
.word UMSG::DOOR_UNLOCKED
.byte SCRIPTS::DA_TELEPORT
doorArgDef $D, $2DD, DIRECTIONS::LEFT, $86
.byte 0
    OBJ_SPOOKANE_MANSIONENTRANCE_IJUSE2:
.byte SCRIPTS::IJ_USE, $56, OBJ_SPOOKANE_MANSIONENTRANCE_IJUSE3-OBJ_SPOOKANE_MANSIONENTRANCE
.byte SCRIPTS::J_JUMP, OBJ_SPOOKANE_MANSIONENTRANCEJ_JUMP4-OBJ_SPOOKANE_MANSIONENTRANCE
    OBJ_SPOOKANE_MANSIONENTRANCE_IJUSE3:
.byte SCRIPTS::IJ_USE, $55, OBJ_SPOOKANE_MANSIONENTRANCE_JUNK0-OBJ_SPOOKANE_MANSIONENTRANCE
    OBJ_SPOOKANE_MANSIONENTRANCEJ_JUMP4:
.byte SCRIPTS::DIALOGUE
.word UMSG::DOOR_KEYFAIL
    OBJ_SPOOKANE_MANSIONENTRANCE_JUNK0:
.byte 0

OBJ_SPOOKANE_RUMORGUY:
objectDef OBJ_TYPE::WANDERING_NPC, $2cb, DIRECTIONS::RIGHT, $358
.addr SPRITEDEF_DA ;sprite
.byte SCRIPTS::J_TALK, OBJ_SPOOKANE_RUMORGUY_JTALK0-OBJ_SPOOKANE_RUMORGUY
.byte SCRIPTS::DIALOGUE
.word UMSG::SPOOKANE_RUMORGUY
.byte SCRIPTS::J_YESNO, OBJ_SPOOKANE_RUMORGUY_JYESNO1-OBJ_SPOOKANE_RUMORGUY
.byte SCRIPTS::DIALOGUE
.word UMSG::SPOOKANE_RUMORGUY_ACCEPT
.byte 0
    OBJ_SPOOKANE_RUMORGUY_JYESNO1:
.byte SCRIPTS::DIALOGUE
.word UMSG::SPOOKANE_RUMORGUY_DECLINE
    OBJ_SPOOKANE_RUMORGUY_JTALK0:
.byte 0

OBJ_SPOOKANE_ROSEMARYGUY:
objectDef OBJ_TYPE::WANDERING_NPC, $2db, DIRECTIONS::DOWN, $367
.addr SPRITEDEF_D2 ;sprite
.byte SCRIPTS::J_TALK, OBJ_SPOOKANE_ROSEMARYGUY_JTALK0-OBJ_SPOOKANE_ROSEMARYGUY
.byte SCRIPTS::DIALOGUE
.word UMSG::SPOOKANE_ROSEMARYGUY
    OBJ_SPOOKANE_ROSEMARYGUY_JTALK0:
.byte 0

OBJ_SPOOKANE_SMALLGUY:
objectDef OBJ_TYPE::WANDERING_NPC, $2df, DIRECTIONS::LEFT, $36f
.addr SPRITEDEF_FA ;sprite
.byte SCRIPTS::J_TALK, OBJ_SPOOKANE_SMALLGUY_JTALK0-OBJ_SPOOKANE_SMALLGUY
.byte SCRIPTS::DIALOGUE
.word UMSG::SPOOKANE_SMALLGUY
    OBJ_SPOOKANE_SMALLGUY_JTALK0:
.byte 0

OBJ_SPOOKANE_CLOWN:
objectDef OBJ_TYPE::WANDERING_NPC, $2f6, DIRECTIONS::DOWN, $360
.addr SPRITEDEF_C2 ;sprite
.byte SCRIPTS::J_TALK, OBJ_SPOOKANE_CLOWN_JTALK0-OBJ_SPOOKANE_CLOWN
.byte SCRIPTS::DIALOGUE
.word UMSG::SPOOKANE_CLOWN
.byte SCRIPTS::J_YESNO, OBJ_SPOOKANE_CLOWN_JYESNO1-OBJ_SPOOKANE_CLOWN
.byte SCRIPTS::DIALOGUE
.word UMSG::SPOOKANE_CLOWN_ACCEPT
.byte 0
    OBJ_SPOOKANE_CLOWN_JYESNO1:
.byte SCRIPTS::DIALOGUE
.word UMSG::SPOOKANE_CLOWN_DECLINE
    OBJ_SPOOKANE_CLOWN_JTALK0:
.byte 0

OBJ_SPOOKANE_HINTGIRL:
objectDef OBJ_TYPE::WANDERING_NPC_CHECKSPAWN, $2e7, DIRECTIONS::RIGHT, $371
.addr SPRITEDEF_CA ;sprite
.byte SCRIPTS::F_DISAPPEAR, $31
.byte SCRIPTS::J_TALK, OBJ_SPOOKANE_HINTGIRL_JTALK0-OBJ_SPOOKANE_HINTGIRL
.byte SCRIPTS::N_LOADNUMBER
.word 1000
.byte SCRIPTS::DIALOGUE
.word UMSG::SPOOKANE_HINTGIRL
.byte SCRIPTS::J_YESNO, OBJ_SPOOKANE_HINTGIRL_JYESNO1-OBJ_SPOOKANE_HINTGIRL
.byte SCRIPTS::J_TAKEMONEY, OBJ_SPOOKANE_HINTGIRL_JTAKEMONEY2-OBJ_SPOOKANE_HINTGIRL
.byte SCRIPTS::DIALOGUE
.word UMSG::SPOOKANE_HINTGIRL_ACCEPT
.byte SCRIPTS::C_INCCOUNTER, $3
.byte SCRIPTS::CNJ_COMPCOUNTER, $3, $3, OBJ_SPOOKANE_HINTGIRL_CNJCOMPCOUNTER3-OBJ_SPOOKANE_HINTGIRL
.byte SCRIPTS::DIALOGUE
.word UMSG::SPOOKANE_HINTGIRL_HINT3
.byte SCRIPTS::F_SETFLAG, $31
.byte 0
    OBJ_SPOOKANE_HINTGIRL_CNJCOMPCOUNTER3:
.byte SCRIPTS::CNJ_COMPCOUNTER, $3, $2, OBJ_SPOOKANE_HINTGIRL_CNJCOMPCOUNTER4-OBJ_SPOOKANE_HINTGIRL
.byte SCRIPTS::DIALOGUE
.word UMSG::SPOOKANE_HINTGIRL_HINT2
.byte 0
    OBJ_SPOOKANE_HINTGIRL_CNJCOMPCOUNTER4:
.byte SCRIPTS::DIALOGUE
.word UMSG::SPOOKANE_HINTGIRL_HINT1
.byte 0
    OBJ_SPOOKANE_HINTGIRL_JTAKEMONEY2:
.byte SCRIPTS::DIALOGUE
.word UMSG::SPOOKANE_HINTGIRL_NOMONEY
.byte 0
    OBJ_SPOOKANE_HINTGIRL_JYESNO1:
.byte SCRIPTS::DIALOGUE
.word UMSG::SPOOKANE_HINTGIRL_DECLINE
.byte SCRIPTS::F_SETFLAG, $31
    OBJ_SPOOKANE_HINTGIRL_JTALK0:
.byte 0

OBJ_SPOOKANE_MRROSEMARY:
objectDef OBJ_TYPE::STATIONARY_NPC, $2f8, DIRECTIONS::DOWN, $371
.addr SPRITEDEF_DA ;sprite
.byte SCRIPTS::J_TALK, OBJ_SPOOKANE_MRROSEMARY_JTALK0-OBJ_SPOOKANE_MRROSEMARY
.byte SCRIPTS::DIALOGUE
.word UMSG::SPOOKANE_MRSROSEMARY
    OBJ_SPOOKANE_MRROSEMARY_JTALK0:
.byte 0

OBJ_SPOOKANE_MRSROSEMARY:
objectDef OBJ_TYPE::WANDERING_NPC, $2f9, DIRECTIONS::RIGHT, $375
.addr SPRITEDEF_CA ;sprite
.byte SCRIPTS::J_TALK, OBJ_SPOOKANE_MRSROSEMARY_JTALK0-OBJ_SPOOKANE_MRSROSEMARY
.byte SCRIPTS::FJ_JUMP, $F4, OBJ_SPOOKANE_MRSROSEMARY_FJJUMP1-OBJ_SPOOKANE_MRSROSEMARY
.byte SCRIPTS::FJ_JUMP, $84, OBJ_SPOOKANE_MRSROSEMARY_FJJUMP2-OBJ_SPOOKANE_MRSROSEMARY
.byte SCRIPTS::DIALOGUE
.word UMSG::SPOOKANE_MRSROSEMARY1
.byte 0
    OBJ_SPOOKANE_MRSROSEMARY_FJJUMP2:
.byte SCRIPTS::DIALOGUE
.word UMSG::SPOOKANE_MRSROSEMARY2
.byte SCRIPTS::F_SETFLAG, $84
.byte 0
    OBJ_SPOOKANE_MRSROSEMARY_FJJUMP1:
.byte SCRIPTS::FJ_JUMP, $38, OBJ_SPOOKANE_MRSROSEMARY_FJJUMP3-OBJ_SPOOKANE_MRSROSEMARY
.byte SCRIPTS::DIALOGUE
.word UMSG::SPOOKANE_MRSROSEMARY3
.byte 0
    OBJ_SPOOKANE_MRSROSEMARY_FJJUMP3:
.byte SCRIPTS::DIALOGUE
.word UMSG::SPOOKANE_MRSROSEMARY_KEY
.byte SCRIPTS::IJ_HASITEM, $0, OBJ_SPOOKANE_MRSROSEMARY_IJHASITEM4-OBJ_SPOOKANE_MRSROSEMARY
.byte SCRIPTS::I_PICKITEM, $57
.byte SCRIPTS::J_GIVEITEM, OBJ_SPOOKANE_MRSROSEMARY_JTALK0-OBJ_SPOOKANE_MRSROSEMARY
.byte SCRIPTS::S_PLAYSOUND, $6
.byte SCRIPTS::F_SETFLAG, $38
.byte 0
    OBJ_SPOOKANE_MRSROSEMARY_IJHASITEM4:
.byte SCRIPTS::DIALOGUE
.word UMSG::PODUNK_PIPPI_NOROOM
    OBJ_SPOOKANE_MRSROSEMARY_JTALK0:
.byte 0

OBJ_SPOOKANE_NINTENROSEMARY:
objectDef OBJ_TYPE::WANDERING_NPC_CHECKSPAWN, $2f8, DIRECTIONS::DOWN, $375
.addr SPRITEDEF_C2 ;sprite
.byte SCRIPTS::F_APPEAR, $F4
.byte SCRIPTS::J_TALK, OBJ_SPOOKANE_NINTENROSEMARY_JTALK0-OBJ_SPOOKANE_NINTENROSEMARY
.byte SCRIPTS::DIALOGUE
.word UMSG::SPOOKANE_NINTENROSEMARY
    OBJ_SPOOKANE_NINTENROSEMARY_JTALK0:
.byte 0

OBJ_SPOOKANE_POSTMANGIRL:
objectDef OBJ_TYPE::WANDERING_NPC, $2d4, DIRECTIONS::RIGHT, $377
.addr SPRITEDEF_F2 ;sprite
.byte SCRIPTS::J_TALK, OBJ_SPOOKANE_POSTMANGIRL_JTALK0-OBJ_SPOOKANE_POSTMANGIRL
.byte SCRIPTS::DIALOGUE
.word UMSG::SPOOKANE_POSTMANGIRL
    OBJ_SPOOKANE_POSTMANGIRL_JTALK0:
.byte 0

OBJ_SPOOKANE_HATERGIRL:
objectDef OBJ_TYPE::WANDERING_NPC, $2e3, DIRECTIONS::LEFT, $381
.addr SPRITEDEF_CA ;sprite
.byte SCRIPTS::J_TALK, OBJ_SPOOKANE_HATERGIRL_JTALK0-OBJ_SPOOKANE_HATERGIRL
.byte SCRIPTS::DIALOGUE
.word UMSG::SPOOKANE_HATERGIRL
    OBJ_SPOOKANE_HATERGIRL_JTALK0:
.byte 0

OBJ_SPOOKANE_STREETSGIRL:
objectDef OBJ_TYPE::WANDERING_NPC, $2db, DIRECTIONS::DOWN, $37a
.addr SPRITEDEF_112 ;sprite
.byte SCRIPTS::J_TALK, OBJ_SPOOKANE_STREETSGIRL_JTALK0-OBJ_SPOOKANE_STREETSGIRL
.byte SCRIPTS::DIALOGUE
.word UMSG::SPOOKANE_STREETSGIRL
    OBJ_SPOOKANE_STREETSGIRL_JTALK0:
.byte 0

OBJ_SPOOKANE_WHATGUY:
objectDef OBJ_TYPE::WANDERING_NPC, $2d5, DIRECTIONS::RIGHT, $382
.addr SPRITEDEF_D2 ;sprite
.byte SCRIPTS::J_TALK, OBJ_SPOOKANE_WHATGUY_JTALK0-OBJ_SPOOKANE_WHATGUY
.byte SCRIPTS::DIALOGUE
.word UMSG::SPOOKANE_WHATGUY
    OBJ_SPOOKANE_WHATGUY_JTALK0:
.byte 0

OBJ_SPOOKANE_POSTMAN:
objectDef OBJ_TYPE::WANDERING_NPC, $2d9, DIRECTIONS::LEFT, $358
.addr SPRITEDEF_D2 ;sprite
.byte SCRIPTS::J_TALK, OBJ_SPOOKANE_POSTMAN_JTALK0-OBJ_SPOOKANE_POSTMAN
.byte SCRIPTS::DIALOGUE
.word UMSG::SPOOKANE_POSTMAN
    OBJ_SPOOKANE_POSTMAN_JTALK0:
.byte 0

OBJ_SPOOKANE_TELEPORTGAIN1:
objectDef OBJ_TYPE::FLAGSET_SEE, $2d3, DIRECTIONS::UP, $359
teleportFlagDef 4, $1D
.byte 0
OBJ_SPOOKANE_TELEPORTGAIN2:
objectDef OBJ_TYPE::FLAGSET_SEE, $2d5, DIRECTIONS::UP, $380
teleportFlagDef 4, $1D
.byte 0