;differences are the melody command (duh) and
;the merrysville - reindeer railroad was made harder
;the encounters are similar to Yucca Desert so that explains a lot

OBJ_BANK_14:
.addr OBJ_YUCCA_MONKEYCAVEENTRANCE
.addr OBJ_YUCCA_R7037
.addr OBJ_YUCCA_NICEBONES
.addr OBJ_YUCCA_SIGNBONES
.addr OBJ_YUCCA_BRAVEBONES
.addr OBJ_YUCCA_CAMELBONES
.addr OBJ_YUCCA_GAMEBONES
.addr OBJ_YUCCA_SINGINGCACTUS
.addr OBJ_YUCCA_MINE
.ifndef VER_JP
.addr OBJ_MR_RAILROADLEFTEXIT
.addr OBJ_MR_RAILROADRIGHTEXIT
.addr OBJ_MR_RAILROADCORPSE
.endif
.addr 0

OBJ_YUCCA_MONKEYCAVEENTRANCE:
objectDef OBJ_TYPE::HOLE, $27a, DIRECTIONS::UP, $112
doorArgDef $18, $51, DIRECTIONS::DOWN, $1CC

OBJ_YUCCA_R7037:
objectDef $1c, $275, DIRECTIONS::UP, $119
OBJ_FLAG_DISAPPEAR  $78
OBJ_IS_NOT_TOUCHING  OBJ_YUCCA_R7037_JTOUCH0-OBJ_YUCCA_R7037
OBJ_BATTLE  $6F
    OBJ_YUCCA_R7037_JTOUCH0:
OBJ_STOP

OBJ_YUCCA_NICEBONES:
objectDef $19, $1a3, DIRECTIONS::UP, $fc
.addr SPRITEDEF_159 ;sprite
OBJ_IS_NOT_TALKING  OBJ_YUCCA_NICEBONES_JTALK0-OBJ_YUCCA_NICEBONES
OBJ_DIALOGUE UMSG::YUCCA_NICEBONES
    OBJ_YUCCA_NICEBONES_JTALK0:
OBJ_STOP

OBJ_YUCCA_SIGNBONES:
objectDef $19, $28d, DIRECTIONS::UP, $104
.addr SPRITEDEF_159 ;sprite
OBJ_IS_NOT_TALKING  OBJ_YUCCA_SIGNBONES_JTALK0-OBJ_YUCCA_SIGNBONES
OBJ_DIALOGUE UMSG::YUCCA_SIGNBONES
    OBJ_YUCCA_SIGNBONES_JTALK0:
OBJ_STOP

OBJ_YUCCA_BRAVEBONES:
objectDef $19, $1c0, DIRECTIONS::UP, $125
.addr SPRITEDEF_159 ;sprite
OBJ_IS_NOT_TALKING  OBJ_YUCCA_BRAVEBONES_JTALK0-OBJ_YUCCA_BRAVEBONES
OBJ_DIALOGUE UMSG::YUCCA_BRAVEBONES
    OBJ_YUCCA_BRAVEBONES_JTALK0:
OBJ_STOP

OBJ_YUCCA_CAMELBONES:
objectDef $19, $216, DIRECTIONS::UP, $100
.addr SPRITEDEF_159 ;sprite
OBJ_IS_NOT_TALKING  OBJ_YUCCA_CAMELBONES_JTALK0-OBJ_YUCCA_CAMELBONES
OBJ_DIALOGUE UMSG::YUCCA_CAMELBONES
    OBJ_YUCCA_CAMELBONESJ_JUMP2:
OBJ_YESNO_IS_NO  OBJ_YUCCA_CAMELBONES_JYESNO1-OBJ_YUCCA_CAMELBONES
OBJ_DIALOGUE UMSG::YUCCA_CAMELBONES_ACCEPT
OBJ_STOP
    OBJ_YUCCA_CAMELBONES_JYESNO1:
OBJ_DIALOGUE UMSG::YUCCA_CAMELBONES_DECLINE
OBJ_JUMP  OBJ_YUCCA_CAMELBONESJ_JUMP2-OBJ_YUCCA_CAMELBONES
OBJ_STOP
    OBJ_YUCCA_CAMELBONES_JTALK0:
OBJ_STOP

OBJ_YUCCA_GAMEBONES:
objectDef $19, $22c, DIRECTIONS::UP, $134
.addr SPRITEDEF_159 ;sprite
OBJ_IS_NOT_TALKING  OBJ_YUCCA_GAMEBONES_JTALK0-OBJ_YUCCA_GAMEBONES
OBJ_DIALOGUE UMSG::YUCCA_GAMEBONES
    OBJ_YUCCA_GAMEBONES_JTALK0:
OBJ_STOP

OBJ_YUCCA_SINGINGCACTUS:
objectDef $18, $1be, DIRECTIONS::UP, $10d
OBJ_IS_NOT_CHECKING  OBJ_YUCCA_SINGINGCACTUS_JCHECK0-OBJ_YUCCA_SINGINGCACTUS
OBJ_DIALOGUE UMSG::REINDEER_DRAGONGIRL_CHECK
OBJ_STOP
    OBJ_YUCCA_SINGINGCACTUS_JCHECK0:
OBJ_IS_NOT_CASTING  $1, OBJ_YUCCA_SINGINGCACTUS_PJUSE1-OBJ_YUCCA_SINGINGCACTUS
OBJ_DIALOGUE UMSG::YUCCA_SINGINGCACTUS
OBJ_PLAY_MUSIC  $28
OBJ_DELAY  $F0
OBJ_PLAY_MUSIC  $8
OBJ_SET_FLAG  $F3
OBJ_DIALOGUE UMSG::REMEMBER_MELODY
.ifdef VER_JP
.byte $65
.endif
    OBJ_YUCCA_SINGINGCACTUS_PJUSE1:
OBJ_STOP

OBJ_YUCCA_MINE:
objectDef $1f, $2a5, DIRECTIONS::UP, $105
OBJ_FLAG_DISAPPEAR  $3B
OBJ_IS_NOT_TOUCHING  OBJ_YUCCA_MINE_JTOUCH0-OBJ_YUCCA_MINE
OBJ_LAND_MINE
OBJ_DIALOGUE UMSG::YUCCA_MINE
OBJ_SET_FLAG  $3B
    OBJ_YUCCA_MINE_JTOUCH0:
OBJ_STOP

.ifndef VER_JP
OBJ_MR_RAILROADLEFTEXIT:
objectDef OBJ_TYPE::DOOR, $8, DIRECTIONS::LEFT, $3fa
doorArgDef $6, $1B1, DIRECTIONS::LEFT, $1CF

OBJ_MR_RAILROADRIGHTEXIT:
objectDef OBJ_TYPE::DOOR, $167, DIRECTIONS::RIGHT, $3fa
doorArgDef $6, $1B2, DIRECTIONS::DOWN, $2E4

OBJ_MR_RAILROADCORPSE:
objectDef $19, $58, DIRECTIONS::UP, $3fb
.addr SPRITEDEF_159 ;sprite
OBJ_IS_NOT_TALKING  OBJ_MR_RAILROADCORPSE_JTALK0-OBJ_MR_RAILROADCORPSE
OBJ_DIALOGUE UMSG::MR_RAILROADCORPSE
    OBJ_MR_RAILROADCORPSE_JTALK0:
OBJ_STOP
.endif