OBJ_BANK_B:
.word OBJ_PODUNK_MERRYCOP
.word OBJ_PODUNK_MERRYCOP2
.word OBJ_PODUNK_GRAVESIGN
.word OBJ_PODUNK_MERRYSIGN
.word OBJ_PODUNK_ZOOSIGN
.word 0

OBJ_PODUNK_MERRYCOP:
objectDef $14, $10d, DIRECTIONS::LEFT, $197
.word $81C8 ;sprite
.byte SCRIPTS::F_DISAPPEAR, $77
.byte SCRIPTS::J_TALK, OBJ_PODUNK_MERRYCOP_JTALK0-OBJ_PODUNK_MERRYCOP
.byte SCRIPTS::DIALOGUE
.word UMSG::PODUNK_MERRYCOP
      OBJ_PODUNK_MERRYCOP_JTALK0:
.byte 0

OBJ_PODUNK_MERRYCOP2:
objectDef $14, $10d, DIRECTIONS::LEFT, $198
.word $81C8 ;sprite
.byte SCRIPTS::F_DISAPPEAR, $77
.byte SCRIPTS::J_TALK, OBJ_PODUNK_MERRYCOP2_JTALK0-OBJ_PODUNK_MERRYCOP2
.byte SCRIPTS::DIALOGUE
.word UMSG::PODUNK_MERRYCOP
      OBJ_PODUNK_MERRYCOP2_JTALK0:
.byte 0

OBJ_PODUNK_GRAVESIGN:
objectDef $19, $bb, DIRECTIONS::UP, $1f3
.word $8194 ;sprite
.byte SCRIPTS::J_CHECK, OBJ_PODUNK_GRAVESIGN_JCHECK0-OBJ_PODUNK_GRAVESIGN
.byte SCRIPTS::DIALOGUE
.word UMSG::PODUNK_GRAVESIGN
      OBJ_PODUNK_GRAVESIGN_JCHECK0:
.byte 0

OBJ_PODUNK_MERRYSIGN:
objectDef $19, $108, DIRECTIONS::UP, $195
.word $8194 ;sprite
.byte SCRIPTS::J_CHECK, OBJ_PODUNK_MERRYSIGN_JCHECK0-OBJ_PODUNK_MERRYSIGN
.byte SCRIPTS::DIALOGUE
.word UMSG::PODUNK_MERRYSIGN
      OBJ_PODUNK_MERRYSIGN_JCHECK0:
.byte 0

OBJ_PODUNK_ZOOSIGN:
objectDef $19, $d2, DIRECTIONS::UP, $10b
.word $8194 ;sprite
.byte SCRIPTS::J_CHECK, OBJ_PODUNK_ZOOSIGN_JCHECK0-OBJ_PODUNK_ZOOSIGN
.byte SCRIPTS::DIALOGUE
.word UMSG::PODUNK_ZOOSIGN
      OBJ_PODUNK_ZOOSIGN_JCHECK0:
.byte 0