OBJ_BANK_F:
.addr OBJ_MERRYSVILLE_RAILROADENTRANCE
.addr OBJ_MERRYSVILLE_MAGICAVEENTRANCE
.addr OBJ_MERRYSVILLE_PASSTRIGGER
.addr OBJ_MERRYSVILLE_PASSTRIGGER2
.addr OBJ_MERRYSVILLE_SWEETSENTRANCE
.addr OBJ_MERRYSVILLE_SWEETSSIGN
.addr 0


OBJ_MERRYSVILLE_RAILROADENTRANCE:
objectDef OBJ_TYPE::DOOR, $1b2, DIRECTIONS::RIGHT, $1cf
doorArgDef $0, $9, DIRECTIONS::RIGHT, $3FA

OBJ_MERRYSVILLE_MAGICAVEENTRANCE:
objectDef OBJ_TYPE::DOOR, $166, DIRECTIONS::UP, $24e
doorArgDef $31, $3E6, DIRECTIONS::DOWN, $209

OBJ_MERRYSVILLE_PASSTRIGGER:
objectDef $1f, $122, DIRECTIONS::UP, $14f
OBJ_FLAG_DISAPPEAR  $85
OBJ_SUBROUTINE OBJ_MERRYSVILLE_PASSTRIGGER2, OBJ_MERRYSVILLE_PASSTRIGGER2_OJSUBROUTINE0-OBJ_MERRYSVILLE_PASSTRIGGER2
OBJ_STOP

OBJ_MERRYSVILLE_PASSTRIGGER2:
objectDef $1f, $123, DIRECTIONS::UP, $14f
OBJ_FLAG_DISAPPEAR  $85
OBJ_SUBROUTINE OBJ_MERRYSVILLE_PASSTRIGGER2, OBJ_MERRYSVILLE_PASSTRIGGER2_OJSUBROUTINE0-OBJ_MERRYSVILLE_PASSTRIGGER2
OBJ_STOP
    OBJ_MERRYSVILLE_PASSTRIGGER2_OJSUBROUTINE0:
OBJ_IS_NOT_TOUCHING  OBJ_MERRYSVILLE_PASSTRIGGER2_JTOUCH0-OBJ_MERRYSVILLE_PASSTRIGGER2
OBJ_DIALOGUE UMSG::MERRYSVILLE_PASSTRIGGER
OBJ_NOT_HAS_ITEM  $0, OBJ_MERRYSVILLE_PASSTRIGGER2_IJHASITEM1-OBJ_MERRYSVILLE_PASSTRIGGER2
OBJ_PICK_ITEM  $59
OBJ_DIALOGUE UMSG::MERRYSVILLE_PASSTRIGGER2
OBJ_PLAY_SOUND  $6
OBJ_GIVE_ITEM OBJ_MERRYSVILLE_PASSTRIGGER2_JTOUCH0-OBJ_MERRYSVILLE_PASSTRIGGER2
OBJ_SET_FLAG  $85
OBJ_RETURN
    OBJ_MERRYSVILLE_PASSTRIGGER2_IJHASITEM1:
OBJ_DIALOGUE UMSG::INVENTORY_FULL
    OBJ_MERRYSVILLE_PASSTRIGGER2_JTOUCH0:
OBJ_RETURN

OBJ_MERRYSVILLE_SWEETSENTRANCE:
objectDef OBJ_TYPE::DOOR, $156, DIRECTIONS::UP, $257
doorArgDef $C, $71, DIRECTIONS::LEFT, $1AE

OBJ_MERRYSVILLE_SWEETSSIGN:
objectDef $19, $155, DIRECTIONS::UP, $258
.addr SPRITEDEF_65 ;sprite
OBJ_IS_NOT_CHECKING  OBJ_MERRYSVILLE_SWEETSSIGN_JCHECK0-OBJ_MERRYSVILLE_SWEETSSIGN
OBJ_DIALOGUE UMSG::MERRYSVILLE_SWEETSSIGN
    OBJ_MERRYSVILLE_SWEETSSIGN_JCHECK0:
OBJ_STOP

