OBJ_BANK_17:
.word OBJ_PODUNK_HOSPITALEXIT
.word OBJ_PODUNK_HOSPITALUPSTAIRS
.word OBJ_PODUNK_HOSPITALOFFICEENTRANCE
.word OBJ_PODUNK_HOSPITALOFFICEEXIT
.word OBJ_MERRYSVILLE_HOSPITALEXIT
.word OBJ_MERRYSVILLE_HOSPITALOFFICEENTRANCE
.word OBJ_MERRYSVILLE_HOSPITALOFFICEEXIT
.word OBJ_REINDEER_HOSPITALEXIT
.word OBJ_REINDEER_HOSPITALUPSTAIRS
.word OBJ_REINDEER_HOSPITALOFFICEENTRANCE
.word OBJ_REINDEER_HOSPITALOFFICEEXIT
.word OBJ_ELLAY_HOSPITALEXIT
.word OBJ_ELLAY_HOSPITALUPSTAIRS
.word OBJ_ELLAY_HOSPITALOFFICEENTRANCE
.word OBJ_ELLAY_HOSPITAL_UPROOM1EXIT
.word OBJ_ELLAY_HOSPITAL_UPROOM2EXIT
.word OBJ_PODUNK_HOSPITALDOCTOR
.word OBJ_REINDEER_HOSPITALDOCTOR
.word OBJ_MERRYSVILLE_HOSPITALDOCTOR
.word OBJ_PODUNK_HOSPITALNURSE
.word OBJ_REINDEER_HOSPITALNURSE
.word OBJ_ELLAY_HOSPITALNURSE
.word OBJ_MERRYSVILLE_HOSPITALNURSE
.word OBJ_REINDEER_HOSPITALWEIGHTGUY
.word OBJ_REINDEER_HOSPITALCOLDGUY
.word 0


OBJ_PODUNK_HOSPITALEXIT:
objectDef OBJ_TYPE::DOOR, $31e, DIRECTIONS::RIGHT, $3f6
doorArgDef $6, $BF, DIRECTIONS::DOWN, $1BD
OBJ_PODUNK_HOSPITALUPSTAIRS:
objectDef OBJ_TYPE::STAIRS, $312, DIRECTIONS::LEFT, $3f5
doorArgDef $0, $302, DIRECTIONS::RIGHT, $86
OBJ_PODUNK_HOSPITALOFFICEENTRANCE:
objectDef OBJ_TYPE::DOOR, $318, DIRECTIONS::UP, $3f3
doorArgDef $0, $D, DIRECTIONS::LEFT, $86
OBJ_PODUNK_HOSPITALOFFICEEXIT:
objectDef OBJ_TYPE::DOOR, $e, DIRECTIONS::RIGHT, $86
doorArgDef $0, $318, DIRECTIONS::DOWN, $3F4

OBJ_MERRYSVILLE_HOSPITALEXIT:
objectDef OBJ_TYPE::DOOR, $e, DIRECTIONS::RIGHT, $146
doorArgDef $6, $16E, DIRECTIONS::DOWN, $1C1
OBJ_MERRYSVILLE_HOSPITALOFFICEENTRANCE:
objectDef OBJ_TYPE::DOOR, $1, DIRECTIONS::LEFT, $146
doorArgDef $0, $29D, DIRECTIONS::LEFT, $3D6
OBJ_MERRYSVILLE_HOSPITALOFFICEEXIT:
objectDef OBJ_TYPE::DOOR, $29e, DIRECTIONS::RIGHT, $3d6
doorArgDef $0, $2, DIRECTIONS::RIGHT, $146

OBJ_REINDEER_HOSPITALEXIT:
objectDef OBJ_TYPE::DOOR, $2de, DIRECTIONS::RIGHT, $3f6
doorArgDef $6, $1E6, DIRECTIONS::DOWN, $3AD
OBJ_REINDEER_HOSPITALUPSTAIRS:
objectDef OBJ_TYPE::STAIRS, $2d2, DIRECTIONS::LEFT, $3f5
doorArgDef $0, $12, DIRECTIONS::RIGHT, $156
OBJ_REINDEER_HOSPITALOFFICEENTRANCE:
objectDef OBJ_TYPE::DOOR, $2d6, DIRECTIONS::UP, $3f3
doorArgDef $0, $24D, DIRECTIONS::LEFT, $86
OBJ_REINDEER_HOSPITALOFFICEEXIT:
objectDef OBJ_TYPE::DOOR, $24e, DIRECTIONS::RIGHT, $86
doorArgDef $0, $2D6, DIRECTIONS::DOWN, $3F4

OBJ_ELLAY_HOSPITALEXIT:
objectDef OBJ_TYPE::DOOR, $2fe, DIRECTIONS::RIGHT, $3f6
doorArgDef $6, $30B, DIRECTIONS::DOWN, $12D
OBJ_ELLAY_HOSPITALUPSTAIRS:
objectDef OBJ_TYPE::STAIRS, $2f2, DIRECTIONS::LEFT, $3f5
doorArgDef $0, $352, DIRECTIONS::RIGHT, $96
OBJ_ELLAY_HOSPITALOFFICEENTRANCE:
objectDef OBJ_TYPE::DOOR, $2f6, DIRECTIONS::UP, $3f3
doorArgDef $0, $2DD, DIRECTIONS::LEFT, $96

OBJ_ELLAY_HOSPITAL_UPROOM1EXIT:
objectDef OBJ_TYPE::DOOR, $2e, DIRECTIONS::RIGHT, $126
doorArgDef $0, $356, DIRECTIONS::DOWN, $94
OBJ_ELLAY_HOSPITAL_UPROOM2EXIT:
objectDef OBJ_TYPE::DOOR, $2e, DIRECTIONS::RIGHT, $146
doorArgDef $0, $359, DIRECTIONS::DOWN, $94

OBJ_PODUNK_HOSPITALDOCTOR:
objectDef OBJ_TYPE::STATIONARY_NPC2, $4, DIRECTIONS::DOWN, $84
.word $84C8 ;sprite
.byte SCRIPTS::N_LOADNUMBER
.word 25
.byte SCRIPTS::OJ_SUBROUTINE
.word OBJ_PODUNK_HOSPITALDOCTOR
.byte OBJ_PODUNK_HOSPITALDOCTOR_OJSUBROUTINE0-OBJ_PODUNK_HOSPITALDOCTOR
.byte 0
      OBJ_PODUNK_HOSPITALDOCTOR_OJSUBROUTINE0:
.byte SCRIPTS::J_TALK, OBJ_PODUNK_HOSPITALDOCTOR_JTALK0-OBJ_PODUNK_HOSPITALDOCTOR
.byte SCRIPTS::DIALOGUE
.word UMSG::PODUNK_HOSPITALDOCTOR
.byte SCRIPTS::J_YESNO, OBJ_PODUNK_HOSPITALDOCTOR_JYESNO1-OBJ_PODUNK_HOSPITALDOCTOR
.byte SCRIPTS::J_TAKEMONEY, OBJ_PODUNK_HOSPITALDOCTOR_JTAKEMONEY2-OBJ_PODUNK_HOSPITALDOCTOR
.byte SCRIPTS::CJ_SELECTPARTY, $1, OBJ_PODUNK_HOSPITALDOCTOR_CJSELECTPARTY3-OBJ_PODUNK_HOSPITALDOCTOR
.byte SCRIPTS::J_CHOOSECHAR, OBJ_PODUNK_HOSPITALDOCTOR_JCHOOSECHAR4-OBJ_PODUNK_HOSPITALDOCTOR
.byte SCRIPTS::J_JUMP, OBJ_PODUNK_HOSPITALDOCTORJ_JUMP5-OBJ_PODUNK_HOSPITALDOCTOR
      OBJ_PODUNK_HOSPITALDOCTOR_CJSELECTPARTY3:
.byte SCRIPTS::CJ_SELECTPARTY, $0, OBJ_PODUNK_HOSPITALDOCTORJ_JUMP5-OBJ_PODUNK_HOSPITALDOCTOR
      OBJ_PODUNK_HOSPITALDOCTORJ_JUMP5:
.byte SCRIPTS::SJ_PRESENT, $80, OBJ_PODUNK_HOSPITALDOCTOR_SJPRESENT6-OBJ_PODUNK_HOSPITALDOCTOR
.byte SCRIPTS::J_NOTMAX, OBJ_PODUNK_HOSPITALDOCTOR_JNOTMAX7-OBJ_PODUNK_HOSPITALDOCTOR
.byte SCRIPTS::SJ_PRESENT, $3, OBJ_PODUNK_HOSPITALDOCTOR_JNOTMAX7-OBJ_PODUNK_HOSPITALDOCTOR
.byte SCRIPTS::DIALOGUE
.word UMSG::PODUNK_HOSPITALDOCTOR_NORMAL
.byte SCRIPTS::J_GIVEMONEY, OBJ_PODUNK_HOSPITALDOCTOR_JTALK0-OBJ_PODUNK_HOSPITALDOCTOR
.byte SCRIPTS::RETURN
      OBJ_PODUNK_HOSPITALDOCTOR_JNOTMAX7:
.byte SCRIPTS::N_HEAL, $FF
.byte SCRIPTS::J_NOTMAX, OBJ_PODUNK_HOSPITALDOCTOR_JNOTMAX7-OBJ_PODUNK_HOSPITALDOCTOR
.byte SCRIPTS::S_REMOVEBUT, $FC
.byte SCRIPTS::SHOWMONEY
.byte SCRIPTS::S_PLAYSOUND, $7
.byte SCRIPTS::DIALOGUE
.word UMSG::PODUNK_HOSPITALDOCTOR_ACCEPT
.byte SCRIPTS::RETURN
      OBJ_PODUNK_HOSPITALDOCTOR_JCHOOSECHAR4:
.byte SCRIPTS::J_GIVEMONEY, OBJ_PODUNK_HOSPITALDOCTOR_JTALK0-OBJ_PODUNK_HOSPITALDOCTOR
      OBJ_PODUNK_HOSPITALDOCTOR_JYESNO1:
.byte SCRIPTS::DIALOGUE
.word UMSG::PODUNK_HOSPITALDOCTOR_DECLINE
.byte SCRIPTS::RETURN
      OBJ_PODUNK_HOSPITALDOCTOR_SJPRESENT6:
.byte SCRIPTS::J_GIVEMONEY, OBJ_PODUNK_HOSPITALDOCTOR_JTALK0-OBJ_PODUNK_HOSPITALDOCTOR
.byte SCRIPTS::DIALOGUE
.word UMSG::HOSPITAL_NOPERSON
.byte SCRIPTS::RETURN
      OBJ_PODUNK_HOSPITALDOCTOR_JTAKEMONEY2:
.byte SCRIPTS::DIALOGUE
.word UMSG::YUCCA_PILOT_NOMONEY
      OBJ_PODUNK_HOSPITALDOCTOR_JTALK0:
.byte SCRIPTS::RETURN

OBJ_REINDEER_HOSPITALDOCTOR:
objectDef OBJ_TYPE::STATIONARY_NPC2, $244, DIRECTIONS::DOWN, $84
.word $84C8 ;sprite
.byte SCRIPTS::N_LOADNUMBER
.word 60
.byte SCRIPTS::OJ_SUBROUTINE
.word OBJ_PODUNK_HOSPITALDOCTOR
.byte OBJ_PODUNK_HOSPITALDOCTOR_OJSUBROUTINE0-OBJ_PODUNK_HOSPITALDOCTOR
.byte 0

OBJ_MERRYSVILLE_HOSPITALDOCTOR:
objectDef OBJ_TYPE::STATIONARY_NPC2, $294, DIRECTIONS::DOWN, $3d4
.word $84C8 ;sprite
.byte SCRIPTS::J_TALK, OBJ_MERRYSVILLE_HOSPITALDOCTOR_JTALK0-OBJ_MERRYSVILLE_HOSPITALDOCTOR
.byte SCRIPTS::GETCASH
.byte SCRIPTS::N_MULNUMBER, 50
.byte SCRIPTS::DIALOGUE
.word UMSG::MERRYSVILLE_HOSPITALDOCTOR
.byte SCRIPTS::J_YESNO, OBJ_MERRYSVILLE_HOSPITALDOCTOR_JYESNO1-OBJ_MERRYSVILLE_HOSPITALDOCTOR
.byte SCRIPTS::GETCASH
.byte SCRIPTS::N_MULNUMBER, 50
.byte SCRIPTS::J_TAKEMONEY, OBJ_MERRYSVILLE_HOSPITALDOCTOR_JTALK0-OBJ_MERRYSVILLE_HOSPITALDOCTOR
.byte SCRIPTS::CJ_SELECTPARTY, $0, OBJ_MERRYSVILLE_HOSPITALDOCTOR_CJSELECTPARTY2-OBJ_MERRYSVILLE_HOSPITALDOCTOR
.byte SCRIPTS::SJ_PRESENT, $80, OBJ_MERRYSVILLE_HOSPITALDOCTOR_CJSELECTPARTY2-OBJ_MERRYSVILLE_HOSPITALDOCTOR
.byte SCRIPTS::S_REMOVEBUT, $FC
      OBJ_MERRYSVILLE_HOSPITALDOCTOR_JNOTMAX3:
.byte SCRIPTS::N_HEAL, $FF
.byte SCRIPTS::J_NOTMAX, OBJ_MERRYSVILLE_HOSPITALDOCTOR_JNOTMAX3-OBJ_MERRYSVILLE_HOSPITALDOCTOR
.byte SCRIPTS::CJ_SELECTPARTY, $1, OBJ_MERRYSVILLE_HOSPITALDOCTOR_CJSELECTPARTY2-OBJ_MERRYSVILLE_HOSPITALDOCTOR
.byte SCRIPTS::SJ_PRESENT, $80, OBJ_MERRYSVILLE_HOSPITALDOCTOR_CJSELECTPARTY2-OBJ_MERRYSVILLE_HOSPITALDOCTOR
.byte SCRIPTS::S_REMOVEBUT, $FC
      OBJ_MERRYSVILLE_HOSPITALDOCTOR_JNOTMAX4:
.byte SCRIPTS::N_HEAL, $FF
.byte SCRIPTS::J_NOTMAX, OBJ_MERRYSVILLE_HOSPITALDOCTOR_JNOTMAX4-OBJ_MERRYSVILLE_HOSPITALDOCTOR
.byte SCRIPTS::CJ_SELECTPARTY, $2, OBJ_MERRYSVILLE_HOSPITALDOCTOR_CJSELECTPARTY2-OBJ_MERRYSVILLE_HOSPITALDOCTOR
.byte SCRIPTS::SJ_PRESENT, $80, OBJ_MERRYSVILLE_HOSPITALDOCTOR_CJSELECTPARTY2-OBJ_MERRYSVILLE_HOSPITALDOCTOR
.byte SCRIPTS::S_REMOVEBUT, $FC
      OBJ_MERRYSVILLE_HOSPITALDOCTOR_JNOTMAX5:
.byte SCRIPTS::N_HEAL, $FF
.byte SCRIPTS::J_NOTMAX, OBJ_MERRYSVILLE_HOSPITALDOCTOR_JNOTMAX5-OBJ_MERRYSVILLE_HOSPITALDOCTOR
      OBJ_MERRYSVILLE_HOSPITALDOCTOR_CJSELECTPARTY2:
.byte SCRIPTS::S_PLAYSOUND, $7
.byte SCRIPTS::SHOWMONEY
.byte SCRIPTS::DIALOGUE
.word UMSG::MERRYSVILLE_HOSPITALDOCTOR_ACCEPT
.byte 0
      OBJ_MERRYSVILLE_HOSPITALDOCTOR_JYESNO1:
.byte SCRIPTS::DIALOGUE
.word UMSG::MERRYSVILLE_HOSPITALDOCTOR_DECLINE
.byte 0
      OBJ_MERRYSVILLE_HOSPITALDOCTOR_JTALK0:
.byte 0

OBJ_PODUNK_HOSPITALNURSE:
objectDef OBJ_TYPE::STATIONARY_NPC2, $315, DIRECTIONS::DOWN, $3f4
.word $8488 ;sprite
.byte SCRIPTS::N_LOADNUMBER
.word 125
.byte SCRIPTS::OJ_SUBROUTINE
.word OBJ_PODUNK_HOSPITALNURSE
.byte OBJ_PODUNK_HOSPITALNURSE_OJSUBROUTINE1-OBJ_PODUNK_HOSPITALNURSE
.byte 0
      OBJ_PODUNK_HOSPITALNURSE_OJSUBROUTINE1:
.byte SCRIPTS::J_TALK, OBJ_PODUNK_HOSPITALNURSE_JTALK0-OBJ_PODUNK_HOSPITALNURSE
.byte SCRIPTS::DIALOGUE
.word UMSG::HOSPITAL_NURSE
.byte SCRIPTS::J_CHOOSECHAR, OBJ_PODUNK_HOSPITALNURSE_JCHOOSECHAR1-OBJ_PODUNK_HOSPITALNURSE
.byte SCRIPTS::SJ_PRESENT, $80, OBJ_PODUNK_HOSPITALNURSE_SJPRESENT2-OBJ_PODUNK_HOSPITALNURSE
.byte SCRIPTS::J_JUMP, OBJ_PODUNK_HOSPITALNURSEJ_JUMP3-OBJ_PODUNK_HOSPITALNURSE
      OBJ_PODUNK_HOSPITALNURSE_SJPRESENT2:
.byte SCRIPTS::DIALOGUE
.word UMSG::HOSPITAL_NURSE_SELECT
.byte SCRIPTS::J_YESNO, OBJ_PODUNK_HOSPITALNURSE_JYESNO4-OBJ_PODUNK_HOSPITALNURSE
.byte SCRIPTS::J_TAKEMONEY, OBJ_PODUNK_HOSPITALNURSE_JTAKEMONEY5-OBJ_PODUNK_HOSPITALNURSE
.byte SCRIPTS::S_REMOVEBUT, $0
.byte SCRIPTS::SHOWMONEY
.byte SCRIPTS::DIALOGUE
.word UMSG::HOSPITAL_NURSE_REVIVE
.byte SCRIPTS::RETURN
      OBJ_PODUNK_HOSPITALNURSE_JTAKEMONEY5:
.byte SCRIPTS::DIALOGUE
.word UMSG::HOSPITAL_NURSE_NOMONEY
.byte SCRIPTS::RETURN
      OBJ_PODUNK_HOSPITALNURSE_JYESNO4:
.byte SCRIPTS::DIALOGUE
.word UMSG::HOSPITAL_NURSE_NOREVIVE
.byte SCRIPTS::RETURN
      OBJ_PODUNK_HOSPITALNURSEJ_JUMP3:
.byte SCRIPTS::DIALOGUE
.word UMSG::HOSPITAL_NURSE_NOONE
.byte SCRIPTS::RETURN
      OBJ_PODUNK_HOSPITALNURSE_JCHOOSECHAR1:
.byte SCRIPTS::DIALOGUE
.word UMSG::HOSPITAL_NURSE_DECLINE
      OBJ_PODUNK_HOSPITALNURSE_JTALK0:
.byte SCRIPTS::RETURN

OBJ_REINDEER_HOSPITALNURSE:
objectDef OBJ_TYPE::STATIONARY_NPC2, $2d4, DIRECTIONS::DOWN, $3f4
.word $8488 ;sprite
.byte SCRIPTS::N_LOADNUMBER
.word 300
.byte SCRIPTS::OJ_SUBROUTINE
.word OBJ_PODUNK_HOSPITALNURSE
.byte OBJ_PODUNK_HOSPITALNURSE_OJSUBROUTINE1-OBJ_PODUNK_HOSPITALNURSE
.byte 0

OBJ_ELLAY_HOSPITALNURSE:
objectDef OBJ_TYPE::STATIONARY_NPC2, $2f4, DIRECTIONS::RIGHT, $3f4
.word $8488 ;sprite
.byte SCRIPTS::N_LOADNUMBER
.word 480
.byte SCRIPTS::OJ_SUBROUTINE
.word OBJ_PODUNK_HOSPITALNURSE
.byte OBJ_PODUNK_HOSPITALNURSE_OJSUBROUTINE1-OBJ_PODUNK_HOSPITALNURSE
.byte 0

OBJ_MERRYSVILLE_HOSPITALNURSE:
objectDef OBJ_TYPE::STATIONARY_NPC2, $8, DIRECTIONS::DOWN, $144
.word $8488 ;sprite
.byte SCRIPTS::N_LOADNUMBER
.word 190
.byte SCRIPTS::OJ_SUBROUTINE
.word OBJ_PODUNK_HOSPITALNURSE
.byte OBJ_PODUNK_HOSPITALNURSE_OJSUBROUTINE1-OBJ_PODUNK_HOSPITALNURSE
.byte 0

OBJ_REINDEER_HOSPITALWEIGHTGUY:
objectDef OBJ_TYPE::WANDERING_NPC2, $2d4, DIRECTIONS::LEFT, $3f7
.word $852C ;sprite
.byte SCRIPTS::J_TALK, OBJ_REINDEER_HOSPITALWEIGHTGUY_JTALK0-OBJ_REINDEER_HOSPITALWEIGHTGUY
.byte SCRIPTS::DIALOGUE
.word UMSG::REINDEER_HOSPITALWEIGHTGUY
      OBJ_REINDEER_HOSPITALWEIGHTGUY_JTALK0:
.byte 0

OBJ_REINDEER_HOSPITALCOLDGUY:
objectDef OBJ_TYPE::WANDERING_NPC2, $2d6, DIRECTIONS::RIGHT, $3f7
.word $84A8 ;sprite
.byte SCRIPTS::J_TALK, OBJ_REINDEER_HOSPITALCOLDGUY_JTALK0-OBJ_REINDEER_HOSPITALCOLDGUY
.byte SCRIPTS::DIALOGUE
.word UMSG::REINDEER_HOSPITALCOLDGUY
      OBJ_REINDEER_HOSPITALCOLDGUY_JTALK0:
.byte 0