OBJ_BANK_13:
.addr OBJ_YOUNGTOWN_MAGICAVE_ENTRANCE
.addr OBJ_YUCCA_MUSICSWITCH1
.addr OBJ_YUCCA_MUSICSWITCH2
.addr OBJ_YUCCA_MUSICSWITCH3
.addr OBJ_YUCCA_MUSICSWITCH4
.addr 0


OBJ_YOUNGTOWN_MAGICAVE_ENTRANCE:
objectDef OBJ_TYPE::DOOR, $279, DIRECTIONS::UP, $18f
doorArgDef $31, $3FD, DIRECTIONS::DOWN, $1E5

OBJ_YUCCA_MUSICSWITCH1:
objectDef OBJ_TYPE::TRIGGER, $184, DIRECTIONS::UP, $12c
OBJ_IS_NOT_TOUCHING @JTOUCH0-OBJ_YUCCA_MUSICSWITCH1
OBJ_PLAY_MUSIC $6
    @JTOUCH0:
OBJ_STOP

OBJ_YUCCA_MUSICSWITCH2:
objectDef OBJ_TYPE::TRIGGER, $184, DIRECTIONS::UP, $12d
OBJ_IS_NOT_TOUCHING @JTOUCH0-OBJ_YUCCA_MUSICSWITCH2
OBJ_PLAY_MUSIC $6
    @JTOUCH0:
OBJ_STOP

OBJ_YUCCA_MUSICSWITCH3:
objectDef OBJ_TYPE::TRIGGER, $186, DIRECTIONS::UP, $12c
OBJ_IS_NOT_TOUCHING @JTOUCH0-OBJ_YUCCA_MUSICSWITCH3
OBJ_PLAY_MUSIC $8
    @JTOUCH0:
OBJ_STOP

OBJ_YUCCA_MUSICSWITCH4:
objectDef OBJ_TYPE::TRIGGER, $186, DIRECTIONS::UP, $12d
OBJ_IS_NOT_TOUCHING @JTOUCH0-OBJ_YUCCA_MUSICSWITCH4
OBJ_PLAY_MUSIC $8
    @JTOUCH0:
OBJ_STOP