OBJ_BANK_17:
.addr OBJ_PODUNK_HOSPITALEXIT
.addr OBJ_PODUNK_HOSPITALUPSTAIRS
.addr OBJ_PODUNK_HOSPITALOFFICEENTRANCE
.addr OBJ_PODUNK_HOSPITALOFFICEEXIT
.addr OBJ_MERRYSVILLE_HOSPITALEXIT
.addr OBJ_MERRYSVILLE_HOSPITALOFFICEENTRANCE
.addr OBJ_MERRYSVILLE_HOSPITALOFFICEEXIT
.addr OBJ_REINDEER_HOSPITALEXIT
.addr OBJ_REINDEER_HOSPITALUPSTAIRS
.addr OBJ_REINDEER_HOSPITALOFFICEENTRANCE
.addr OBJ_REINDEER_HOSPITALOFFICEEXIT
.addr OBJ_ELLAY_HOSPITALEXIT
.addr OBJ_ELLAY_HOSPITALUPSTAIRS
.addr OBJ_ELLAY_HOSPITALOFFICEENTRANCE
.addr OBJ_ELLAY_HOSPITAL_UPROOM1EXIT
.addr OBJ_ELLAY_HOSPITAL_UPROOM2EXIT
.addr OBJ_PODUNK_HOSPITALDOCTOR
.addr OBJ_REINDEER_HOSPITALDOCTOR
.addr OBJ_MERRYSVILLE_HOSPITALDOCTOR
.addr OBJ_PODUNK_HOSPITALNURSE
.addr OBJ_REINDEER_HOSPITALNURSE
.addr OBJ_ELLAY_HOSPITALNURSE
.addr OBJ_MERRYSVILLE_HOSPITALNURSE
.addr OBJ_REINDEER_HOSPITALWEIGHTGUY
.addr OBJ_REINDEER_HOSPITALCOLDGUY
.addr 0


OBJ_PODUNK_HOSPITALEXIT:
objectDef OBJ_TYPE::DOOR, $31e, DIRECTIONS::RIGHT, $3f6
doorArgDef $6, $BF, DIRECTIONS::DOWN, $1BD
OBJ_PODUNK_HOSPITALUPSTAIRS:
objectDef OBJ_TYPE::STAIRS, $312, DIRECTIONS::LEFT, $3f5
doorArgDef $0, $302, DIRECTIONS::RIGHT, $86
OBJ_PODUNK_HOSPITALOFFICEENTRANCE:
objectDef OBJ_TYPE::DOOR, $318, DIRECTIONS::UP, $3f3
doorArgDef $0, $D, DIRECTIONS::LEFT, $86
OBJ_PODUNK_HOSPITALOFFICEEXIT:
objectDef OBJ_TYPE::DOOR, $e, DIRECTIONS::RIGHT, $86
doorArgDef $0, $318, DIRECTIONS::DOWN, $3F4

OBJ_MERRYSVILLE_HOSPITALEXIT:
objectDef OBJ_TYPE::DOOR, $e, DIRECTIONS::RIGHT, $146
doorArgDef $6, $16E, DIRECTIONS::DOWN, $1C1
OBJ_MERRYSVILLE_HOSPITALOFFICEENTRANCE:
objectDef OBJ_TYPE::DOOR, $1, DIRECTIONS::LEFT, $146
doorArgDef $0, $29D, DIRECTIONS::LEFT, $3D6
OBJ_MERRYSVILLE_HOSPITALOFFICEEXIT:
objectDef OBJ_TYPE::DOOR, $29e, DIRECTIONS::RIGHT, $3d6
doorArgDef $0, $2, DIRECTIONS::RIGHT, $146

OBJ_REINDEER_HOSPITALEXIT:
objectDef OBJ_TYPE::DOOR, $2de, DIRECTIONS::RIGHT, $3f6
doorArgDef $6, $1E6, DIRECTIONS::DOWN, $3AD
OBJ_REINDEER_HOSPITALUPSTAIRS:
objectDef OBJ_TYPE::STAIRS, $2d2, DIRECTIONS::LEFT, $3f5
doorArgDef $0, $12, DIRECTIONS::RIGHT, $156
OBJ_REINDEER_HOSPITALOFFICEENTRANCE:
objectDef OBJ_TYPE::DOOR, $2d6, DIRECTIONS::UP, $3f3
doorArgDef $0, $24D, DIRECTIONS::LEFT, $86
OBJ_REINDEER_HOSPITALOFFICEEXIT:
objectDef OBJ_TYPE::DOOR, $24e, DIRECTIONS::RIGHT, $86
doorArgDef $0, $2D6, DIRECTIONS::DOWN, $3F4

OBJ_ELLAY_HOSPITALEXIT:
objectDef OBJ_TYPE::DOOR, $2fe, DIRECTIONS::RIGHT, $3f6
doorArgDef $6, $30B, DIRECTIONS::DOWN, $12D
OBJ_ELLAY_HOSPITALUPSTAIRS:
objectDef OBJ_TYPE::STAIRS, $2f2, DIRECTIONS::LEFT, $3f5
doorArgDef $0, $352, DIRECTIONS::RIGHT, $96
OBJ_ELLAY_HOSPITALOFFICEENTRANCE:
objectDef OBJ_TYPE::DOOR, $2f6, DIRECTIONS::UP, $3f3
doorArgDef $0, $2DD, DIRECTIONS::LEFT, $96

OBJ_ELLAY_HOSPITAL_UPROOM1EXIT:
objectDef OBJ_TYPE::DOOR, $2e, DIRECTIONS::RIGHT, $126
doorArgDef $0, $356, DIRECTIONS::DOWN, $94
OBJ_ELLAY_HOSPITAL_UPROOM2EXIT:
objectDef OBJ_TYPE::DOOR, $2e, DIRECTIONS::RIGHT, $146
doorArgDef $0, $359, DIRECTIONS::DOWN, $94

OBJ_PODUNK_HOSPITALDOCTOR:
objectDef OBJ_TYPE::STATIONARY_NPC, $4, DIRECTIONS::DOWN, $84
.addr SPRITEDEF_132 ;sprite
OPJ_LOAD_NUMBER 25
OBJ_SUBROUTINE OBJ_PODUNK_HOSPITALDOCTOR, OBJ_PODUNK_HOSPITALDOCTOR_OJSUBROUTINE0-OBJ_PODUNK_HOSPITALDOCTOR
OBJ_STOP
    OBJ_PODUNK_HOSPITALDOCTOR_OJSUBROUTINE0:
OBJ_IS_NOT_TALKING  OBJ_PODUNK_HOSPITALDOCTOR_JTALK0-OBJ_PODUNK_HOSPITALDOCTOR
OBJ_DIALOGUE UMSG::PODUNK_HOSPITALDOCTOR
OBJ_YESNO_IS_NO  OBJ_PODUNK_HOSPITALDOCTOR_JYESNO1-OBJ_PODUNK_HOSPITALDOCTOR
OBJ_TAKE_MONEY OBJ_PODUNK_HOSPITALDOCTOR_JTAKEMONEY2-OBJ_PODUNK_HOSPITALDOCTOR
OBJ_PICK_CHARACTER_J  $1, OBJ_PODUNK_HOSPITALDOCTOR_CJSELECTPARTY3-OBJ_PODUNK_HOSPITALDOCTOR
.byte SCRIPTS::J_CHOOSECHAR, OBJ_PODUNK_HOSPITALDOCTOR_JCHOOSECHAR4-OBJ_PODUNK_HOSPITALDOCTOR
OBJ_JUMP  OBJ_PODUNK_HOSPITALDOCTORJ_JUMP5-OBJ_PODUNK_HOSPITALDOCTOR
    OBJ_PODUNK_HOSPITALDOCTOR_CJSELECTPARTY3:
OBJ_PICK_CHARACTER_J  $0, OBJ_PODUNK_HOSPITALDOCTORJ_JUMP5-OBJ_PODUNK_HOSPITALDOCTOR
    OBJ_PODUNK_HOSPITALDOCTORJ_JUMP5:
OBJ_HAS_STATUS  $80, OBJ_PODUNK_HOSPITALDOCTOR_SJPRESENT6-OBJ_PODUNK_HOSPITALDOCTOR
OBJ_NOT_MAX_HEALTH  OBJ_PODUNK_HOSPITALDOCTOR_JNOTMAX7-OBJ_PODUNK_HOSPITALDOCTOR
OBJ_HAS_STATUS  $3, OBJ_PODUNK_HOSPITALDOCTOR_JNOTMAX7-OBJ_PODUNK_HOSPITALDOCTOR
OBJ_DIALOGUE UMSG::PODUNK_HOSPITALDOCTOR_NORMAL
OBJ_GIVE_WEAPON OBJ_PODUNK_HOSPITALDOCTOR_JTALK0-OBJ_PODUNK_HOSPITALDOCTOR
OBJ_RETURN
    OBJ_PODUNK_HOSPITALDOCTOR_JNOTMAX7:
OBJ_HEAL  $FF
OBJ_NOT_MAX_HEALTH  OBJ_PODUNK_HOSPITALDOCTOR_JNOTMAX7-OBJ_PODUNK_HOSPITALDOCTOR
OBJ_AND_STATUS  $FC
OBJ_SHOW_MONEY
OBJ_PLAY_SOUND  $7
OBJ_DIALOGUE UMSG::PODUNK_HOSPITALDOCTOR_ACCEPT
OBJ_RETURN
    OBJ_PODUNK_HOSPITALDOCTOR_JCHOOSECHAR4:
OBJ_GIVE_WEAPON OBJ_PODUNK_HOSPITALDOCTOR_JTALK0-OBJ_PODUNK_HOSPITALDOCTOR
    OBJ_PODUNK_HOSPITALDOCTOR_JYESNO1:
OBJ_DIALOGUE UMSG::PODUNK_HOSPITALDOCTOR_DECLINE
OBJ_RETURN
    OBJ_PODUNK_HOSPITALDOCTOR_SJPRESENT6:
OBJ_GIVE_WEAPON OBJ_PODUNK_HOSPITALDOCTOR_JTALK0-OBJ_PODUNK_HOSPITALDOCTOR
OBJ_DIALOGUE UMSG::HOSPITAL_NOPERSON
OBJ_RETURN
    OBJ_PODUNK_HOSPITALDOCTOR_JTAKEMONEY2:
OBJ_DIALOGUE UMSG::YUCCA_PILOT_NOMONEY
    OBJ_PODUNK_HOSPITALDOCTOR_JTALK0:
OBJ_RETURN

OBJ_REINDEER_HOSPITALDOCTOR:
objectDef OBJ_TYPE::STATIONARY_NPC, $244, DIRECTIONS::DOWN, $84
.addr SPRITEDEF_132 ;sprite
OPJ_LOAD_NUMBER 60
OBJ_SUBROUTINE OBJ_PODUNK_HOSPITALDOCTOR, OBJ_PODUNK_HOSPITALDOCTOR_OJSUBROUTINE0-OBJ_PODUNK_HOSPITALDOCTOR
OBJ_STOP

OBJ_MERRYSVILLE_HOSPITALDOCTOR:
objectDef OBJ_TYPE::STATIONARY_NPC, $294, DIRECTIONS::DOWN, $3d4
.addr SPRITEDEF_132 ;sprite
OBJ_IS_NOT_TALKING  OBJ_MERRYSVILLE_HOSPITALDOCTOR_JTALK0-OBJ_MERRYSVILLE_HOSPITALDOCTOR
.byte SCRIPTS::GETCASH
.byte SCRIPTS::N_MULNUMBER, 50
OBJ_DIALOGUE UMSG::MERRYSVILLE_HOSPITALDOCTOR
OBJ_YESNO_IS_NO  OBJ_MERRYSVILLE_HOSPITALDOCTOR_JYESNO1-OBJ_MERRYSVILLE_HOSPITALDOCTOR
.byte SCRIPTS::GETCASH
.byte SCRIPTS::N_MULNUMBER, 50
OBJ_TAKE_MONEY OBJ_MERRYSVILLE_HOSPITALDOCTOR_JTALK0-OBJ_MERRYSVILLE_HOSPITALDOCTOR
OBJ_PICK_CHARACTER_J  $0, OBJ_MERRYSVILLE_HOSPITALDOCTOR_CJSELECTPARTY2-OBJ_MERRYSVILLE_HOSPITALDOCTOR
OBJ_HAS_STATUS  $80, OBJ_MERRYSVILLE_HOSPITALDOCTOR_CJSELECTPARTY2-OBJ_MERRYSVILLE_HOSPITALDOCTOR
OBJ_AND_STATUS  $FC
    OBJ_MERRYSVILLE_HOSPITALDOCTOR_JNOTMAX3:
OBJ_HEAL  $FF
OBJ_NOT_MAX_HEALTH  OBJ_MERRYSVILLE_HOSPITALDOCTOR_JNOTMAX3-OBJ_MERRYSVILLE_HOSPITALDOCTOR
OBJ_PICK_CHARACTER_J  $1, OBJ_MERRYSVILLE_HOSPITALDOCTOR_CJSELECTPARTY2-OBJ_MERRYSVILLE_HOSPITALDOCTOR
OBJ_HAS_STATUS  $80, OBJ_MERRYSVILLE_HOSPITALDOCTOR_CJSELECTPARTY2-OBJ_MERRYSVILLE_HOSPITALDOCTOR
OBJ_AND_STATUS  $FC
    OBJ_MERRYSVILLE_HOSPITALDOCTOR_JNOTMAX4:
OBJ_HEAL  $FF
OBJ_NOT_MAX_HEALTH  OBJ_MERRYSVILLE_HOSPITALDOCTOR_JNOTMAX4-OBJ_MERRYSVILLE_HOSPITALDOCTOR
OBJ_PICK_CHARACTER_J  $2, OBJ_MERRYSVILLE_HOSPITALDOCTOR_CJSELECTPARTY2-OBJ_MERRYSVILLE_HOSPITALDOCTOR
OBJ_HAS_STATUS  $80, OBJ_MERRYSVILLE_HOSPITALDOCTOR_CJSELECTPARTY2-OBJ_MERRYSVILLE_HOSPITALDOCTOR
OBJ_AND_STATUS  $FC
    OBJ_MERRYSVILLE_HOSPITALDOCTOR_JNOTMAX5:
OBJ_HEAL  $FF
OBJ_NOT_MAX_HEALTH  OBJ_MERRYSVILLE_HOSPITALDOCTOR_JNOTMAX5-OBJ_MERRYSVILLE_HOSPITALDOCTOR
    OBJ_MERRYSVILLE_HOSPITALDOCTOR_CJSELECTPARTY2:
OBJ_PLAY_SOUND  $7
OBJ_SHOW_MONEY
OBJ_DIALOGUE UMSG::MERRYSVILLE_HOSPITALDOCTOR_ACCEPT
OBJ_STOP
    OBJ_MERRYSVILLE_HOSPITALDOCTOR_JYESNO1:
OBJ_DIALOGUE UMSG::MERRYSVILLE_HOSPITALDOCTOR_DECLINE
OBJ_STOP
    OBJ_MERRYSVILLE_HOSPITALDOCTOR_JTALK0:
OBJ_STOP

OBJ_PODUNK_HOSPITALNURSE:
objectDef OBJ_TYPE::STATIONARY_NPC, $315, DIRECTIONS::DOWN, $3f4
.addr SPRITEDEF_122 ;sprite
OPJ_LOAD_NUMBER 125
OBJ_SUBROUTINE OBJ_PODUNK_HOSPITALNURSE, OBJ_PODUNK_HOSPITALNURSE_OJSUBROUTINE1-OBJ_PODUNK_HOSPITALNURSE
OBJ_STOP
    OBJ_PODUNK_HOSPITALNURSE_OJSUBROUTINE1:
OBJ_IS_NOT_TALKING  OBJ_PODUNK_HOSPITALNURSE_JTALK0-OBJ_PODUNK_HOSPITALNURSE
OBJ_DIALOGUE UMSG::HOSPITAL_NURSE
.byte SCRIPTS::J_CHOOSECHAR, OBJ_PODUNK_HOSPITALNURSE_JCHOOSECHAR1-OBJ_PODUNK_HOSPITALNURSE
OBJ_HAS_STATUS  $80, OBJ_PODUNK_HOSPITALNURSE_SJPRESENT2-OBJ_PODUNK_HOSPITALNURSE
OBJ_JUMP  OBJ_PODUNK_HOSPITALNURSEJ_JUMP3-OBJ_PODUNK_HOSPITALNURSE
    OBJ_PODUNK_HOSPITALNURSE_SJPRESENT2:
OBJ_DIALOGUE UMSG::HOSPITAL_NURSE_SELECT
OBJ_YESNO_IS_NO  OBJ_PODUNK_HOSPITALNURSE_JYESNO4-OBJ_PODUNK_HOSPITALNURSE
OBJ_TAKE_MONEY OBJ_PODUNK_HOSPITALNURSE_JTAKEMONEY5-OBJ_PODUNK_HOSPITALNURSE
OBJ_AND_STATUS  $0
OBJ_SHOW_MONEY
OBJ_DIALOGUE UMSG::HOSPITAL_NURSE_REVIVE
OBJ_RETURN
    OBJ_PODUNK_HOSPITALNURSE_JTAKEMONEY5:
OBJ_DIALOGUE UMSG::HOSPITAL_NURSE_NOMONEY
OBJ_RETURN
    OBJ_PODUNK_HOSPITALNURSE_JYESNO4:
OBJ_DIALOGUE UMSG::HOSPITAL_NURSE_NOREVIVE
OBJ_RETURN
    OBJ_PODUNK_HOSPITALNURSEJ_JUMP3:
OBJ_DIALOGUE UMSG::HOSPITAL_NURSE_NOONE
OBJ_RETURN
    OBJ_PODUNK_HOSPITALNURSE_JCHOOSECHAR1:
OBJ_DIALOGUE UMSG::HOSPITAL_NURSE_DECLINE
    OBJ_PODUNK_HOSPITALNURSE_JTALK0:
OBJ_RETURN

OBJ_REINDEER_HOSPITALNURSE:
objectDef OBJ_TYPE::STATIONARY_NPC, $2d4, DIRECTIONS::DOWN, $3f4
.addr SPRITEDEF_122 ;sprite
OPJ_LOAD_NUMBER 300
OBJ_SUBROUTINE OBJ_PODUNK_HOSPITALNURSE, OBJ_PODUNK_HOSPITALNURSE_OJSUBROUTINE1-OBJ_PODUNK_HOSPITALNURSE
OBJ_STOP

OBJ_ELLAY_HOSPITALNURSE:
objectDef OBJ_TYPE::STATIONARY_NPC, $2f4, DIRECTIONS::RIGHT, $3f4
.addr SPRITEDEF_122 ;sprite
OPJ_LOAD_NUMBER 480
OBJ_SUBROUTINE OBJ_PODUNK_HOSPITALNURSE, OBJ_PODUNK_HOSPITALNURSE_OJSUBROUTINE1-OBJ_PODUNK_HOSPITALNURSE
OBJ_STOP

OBJ_MERRYSVILLE_HOSPITALNURSE:
objectDef OBJ_TYPE::STATIONARY_NPC, $8, DIRECTIONS::DOWN, $144
.addr SPRITEDEF_122 ;sprite
OPJ_LOAD_NUMBER 190
OBJ_SUBROUTINE OBJ_PODUNK_HOSPITALNURSE, OBJ_PODUNK_HOSPITALNURSE_OJSUBROUTINE1-OBJ_PODUNK_HOSPITALNURSE
OBJ_STOP

OBJ_REINDEER_HOSPITALWEIGHTGUY:
objectDef OBJ_TYPE::WANDERING_NPC, $2d4, DIRECTIONS::LEFT, $3f7
.addr SPRITEDEF_14B ;sprite
OBJ_IS_NOT_TALKING  OBJ_REINDEER_HOSPITALWEIGHTGUY_JTALK0-OBJ_REINDEER_HOSPITALWEIGHTGUY
OBJ_DIALOGUE UMSG::REINDEER_HOSPITALWEIGHTGUY
    OBJ_REINDEER_HOSPITALWEIGHTGUY_JTALK0:
OBJ_STOP

OBJ_REINDEER_HOSPITALCOLDGUY:
objectDef OBJ_TYPE::WANDERING_NPC, $2d6, DIRECTIONS::RIGHT, $3f7
.addr SPRITEDEF_12A ;sprite
OBJ_IS_NOT_TALKING  OBJ_REINDEER_HOSPITALCOLDGUY_JTALK0-OBJ_REINDEER_HOSPITALCOLDGUY
OBJ_DIALOGUE UMSG::REINDEER_HOSPITALCOLDGUY
    OBJ_REINDEER_HOSPITALCOLDGUY_JTALK0:
OBJ_STOP