OBJ_BANK_F:
.addr OBJ_MERRYSVILLE_RAILROADENTRANCE
.addr OBJ_MERRYSVILLE_MAGICAVEENTRANCE
.addr OBJ_MERRYSVILLE_PASSTRIGGER
.addr OBJ_MERRYSVILLE_PASSTRIGGER2
.addr OBJ_MERRYSVILLE_SWEETSENTRANCE
.addr OBJ_MERRYSVILLE_SWEETSSIGN
.addr 0


OBJ_MERRYSVILLE_RAILROADENTRANCE:
objectDef OBJ_TYPE::DOOR, $1b2, DIRECTIONS::RIGHT, $1cf
doorArgDef $0, $9, DIRECTIONS::RIGHT, $3FA

OBJ_MERRYSVILLE_MAGICAVEENTRANCE:
objectDef OBJ_TYPE::DOOR, $166, DIRECTIONS::UP, $24e
doorArgDef $31, $3E6, DIRECTIONS::DOWN, $209

OBJ_MERRYSVILLE_PASSTRIGGER:
objectDef $1f, $122, DIRECTIONS::UP, $14f
.byte SCRIPTS::F_DISAPPEAR, $85
.byte SCRIPTS::OJ_SUBROUTINE
.addr OBJ_MERRYSVILLE_PASSTRIGGER2
.byte OBJ_MERRYSVILLE_PASSTRIGGER2_OJSUBROUTINE0-OBJ_MERRYSVILLE_PASSTRIGGER2
.byte 0

OBJ_MERRYSVILLE_PASSTRIGGER2:
objectDef $1f, $123, DIRECTIONS::UP, $14f
.byte SCRIPTS::F_DISAPPEAR, $85
.byte SCRIPTS::OJ_SUBROUTINE
.addr OBJ_MERRYSVILLE_PASSTRIGGER2
.byte OBJ_MERRYSVILLE_PASSTRIGGER2_OJSUBROUTINE0-OBJ_MERRYSVILLE_PASSTRIGGER2
.byte 0
    OBJ_MERRYSVILLE_PASSTRIGGER2_OJSUBROUTINE0:
.byte SCRIPTS::J_TOUCH, OBJ_MERRYSVILLE_PASSTRIGGER2_JTOUCH0-OBJ_MERRYSVILLE_PASSTRIGGER2
.byte SCRIPTS::DIALOGUE
.word UMSG::MERRYSVILLE_PASSTRIGGER
.byte SCRIPTS::IJ_HASITEM, $0, OBJ_MERRYSVILLE_PASSTRIGGER2_IJHASITEM1-OBJ_MERRYSVILLE_PASSTRIGGER2
.byte SCRIPTS::I_PICKITEM, $59
.byte SCRIPTS::DIALOGUE
.word UMSG::MERRYSVILLE_PASSTRIGGER2
.byte SCRIPTS::S_PLAYSOUND, $6
.byte SCRIPTS::J_GIVEITEM, OBJ_MERRYSVILLE_PASSTRIGGER2_JTOUCH0-OBJ_MERRYSVILLE_PASSTRIGGER2
.byte SCRIPTS::F_SETFLAG, $85
.byte SCRIPTS::RETURN
    OBJ_MERRYSVILLE_PASSTRIGGER2_IJHASITEM1:
.byte SCRIPTS::DIALOGUE
.word UMSG::INVENTORY_FULL
    OBJ_MERRYSVILLE_PASSTRIGGER2_JTOUCH0:
.byte SCRIPTS::RETURN

OBJ_MERRYSVILLE_SWEETSENTRANCE:
objectDef OBJ_TYPE::DOOR, $156, DIRECTIONS::UP, $257
doorArgDef $C, $71, DIRECTIONS::LEFT, $1AE

OBJ_MERRYSVILLE_SWEETSSIGN:
objectDef $19, $155, DIRECTIONS::UP, $258
.addr SPRITEDEF_65 ;sprite
.byte SCRIPTS::J_CHECK, OBJ_MERRYSVILLE_SWEETSSIGN_JCHECK0-OBJ_MERRYSVILLE_SWEETSSIGN
.byte SCRIPTS::DIALOGUE
.word UMSG::MERRYSVILLE_SWEETSSIGN
    OBJ_MERRYSVILLE_SWEETSSIGN_JCHECK0:
.byte 0

