OBJ_BANK_3:
.word OBJ_MERRYSVILLE_DEPTENTRANCE
.word OBJ_MERRYSVILLE_HOSPITALENTRANCE
.word OBJ_MERRYSVILLE_HOTELENTRANCE
.word OBJ_MERRYSVILLE_BURGERENTRANCE
.word OBJ_MERRYSVILLE_SCHOOLENTRANCE
.word OBJ_MERRYSVILLE_UNIONENTRANCE
.word OBJ_MERRYSVILLE_RUMORGUY
.word OBJ_MERRYSVILLE_COP
.word OBJ_MERRYSVILLE_DUNCANGUY
.word OBJ_MERRYSVILLE_BEATUPGUY
.word OBJ_MERRYSVILLE_CURFEWGUY
.word OBJ_MERRYSVILLE_TRAINWOMAN
.word OBJ_MERRYSVILLE_NINTENDOGIRL
.word OBJ_MERRYSVILLE_HAPPYGUY
.word OBJ_MERRYSVILLE_STRIPGIRL
.word OBJ_MERRYSVILLE_DOCTORGUY
.word OBJ_MERRYSVILLE_QUESTIONNAIRE
.word OBJ_MERRYSVILLE_SCHOOLGUY
.word OBJ_MERRYSVILLE_MAYORGUY
.word OBJ_MERRYSVILLE_ROCKETGUY
.word OBJ_MERRYSVILLE_ORDINARYGUY
.word OBJ_MERRYSVILLE_THINKINGGUY
.word OBJ_MERRYSVILLE_HUSBANDGIRL
.word OBJ_MERRYSVILLE_SWEETSGUY
.word OBJ_MERRYSVILLE_MONSTERGIRL
.word OBJ_MERRYSVILLE_HOSPITALSIGN
.word OBJ_MERRYSVILLE_SIGN
.word OBJ_MERRYSVILLE_DUNCANSIGN
.word OBJ_MERRYSVILLE_SCHOOLSIGN
.word OBJ_MERRYSVILLE_TELEPORTGAIN1
.word OBJ_MERRYSVILLE_TELEPORTGAIN2
.word OBJ_MERRYSVILLE_TELEPORTGAIN3
.word OBJ_MERRYSVILLE_TELEPORTGAIN4
.word OBJ_MERRYSVILLE_TELEPORTGAIN5
.word OBJ_MERRYSVILLE_TELEPORTGAIN6
.word OBJ_MERRYSVILLE_TELEPORTGAIN7
.word OBJ_MERRYSVILLE_TELEPORTGAIN8
.word OBJ_MERRYSVILLE_TELEPORTGAIN9
.word OBJ_MERRYSVILLE_TELEPORTGAINA
.word 0

OBJ_MERRYSVILLE_DEPTENTRANCE:
objectDef OBJ_TYPE::DOOR, $162, DIRECTIONS::UP, $1cc
doorArgDef $F, $D, DIRECTIONS::LEFT, $B6

OBJ_MERRYSVILLE_HOSPITALENTRANCE:
objectDef OBJ_TYPE::DOOR, $16e, DIRECTIONS::UP, $1c0
doorArgDef $12, $D, DIRECTIONS::LEFT, $146

OBJ_MERRYSVILLE_HOTELENTRANCE:
objectDef OBJ_TYPE::DOOR, $16b, DIRECTIONS::UP, $1cc
doorArgDef $12, $2DD, DIRECTIONS::LEFT, $3D6

OBJ_MERRYSVILLE_BURGERENTRANCE:
objectDef OBJ_TYPE::DOOR, $163, DIRECTIONS::UP, $1c0
doorArgDef $F, $D, DIRECTIONS::LEFT, $F6

OBJ_MERRYSVILLE_SCHOOLENTRANCE:
objectDef OBJ_TYPE::DOOR, $169, DIRECTIONS::UP, $1e5
doorArgDef $E, $305, DIRECTIONS::DOWN, $3B5

OBJ_MERRYSVILLE_UNIONENTRANCE:
objectDef OBJ_TYPE::DOOR, $141, DIRECTIONS::UP, $14e
doorArgDef $F, $291, DIRECTIONS::DOWN, $3C5

OBJ_MERRYSVILLE_RUMORGUY:
objectDef OBJ_TYPE::WANDERING_NPC2, $14d, DIRECTIONS::RIGHT, $19d
.word $8228 ;sprite
.byte SCRIPTS::J_TALK, OBJ_MERRYSVILLE_RUMORGUY_JTALK0-OBJ_MERRYSVILLE_RUMORGUY
.byte SCRIPTS::DIALOGUE
.word UMSG::MERRYSVILLE_RUMORGUY1
.byte SCRIPTS::J_YESNO, OBJ_MERRYSVILLE_RUMORGUY_JYESNO1-OBJ_MERRYSVILLE_RUMORGUY
.byte SCRIPTS::DIALOGUE
.word UMSG::MERRYSVILLE_RUMORGUY2
.byte 0
      OBJ_MERRYSVILLE_RUMORGUY_JYESNO1:
.byte SCRIPTS::DIALOGUE
.word UMSG::PODUNK_CANARYGIRL2
      OBJ_MERRYSVILLE_RUMORGUY_JTALK0:
.byte 0

OBJ_MERRYSVILLE_COP:
objectDef OBJ_TYPE::WANDERING_NPC2, $15f, DIRECTIONS::LEFT, $1bd
.word $81C8 ;sprite
.byte SCRIPTS::J_TALK, OBJ_MERRYSVILLE_COP_JTALK0-OBJ_MERRYSVILLE_COP
.byte SCRIPTS::DIALOGUE
.word UMSG::MERRYSVILLE_COP
      OBJ_MERRYSVILLE_COP_JTALK0:
.byte 0

OBJ_MERRYSVILLE_DUNCANGUY:
objectDef OBJ_TYPE::WANDERING_NPC2, $154, DIRECTIONS::LEFT, $1d2
.word $81A8 ;sprite
.byte SCRIPTS::J_TALK, OBJ_MERRYSVILLE_DUNCANGUY_JTALK0-OBJ_MERRYSVILLE_DUNCANGUY
.byte SCRIPTS::DIALOGUE
.word UMSG::MERRYSVILLE_DUNCANGUY
      OBJ_MERRYSVILLE_DUNCANGUY_JTALK0:
.byte 0

OBJ_MERRYSVILLE_BEATUPGUY:
objectDef OBJ_TYPE::WANDERING_NPC2, $159, DIRECTIONS::DOWN, $1de
.word $8268 ;sprite
.byte SCRIPTS::J_TALK, OBJ_MERRYSVILLE_BEATUPGUY_JTALK0-OBJ_MERRYSVILLE_BEATUPGUY
.byte SCRIPTS::DIALOGUE
.word UMSG::MERRYSVILLE_BEATUPGUY
      OBJ_MERRYSVILLE_BEATUPGUY_JTALK0:
.byte 0

OBJ_MERRYSVILLE_CURFEWGUY:
objectDef OBJ_TYPE::WANDERING_NPC2, $15b, DIRECTIONS::RIGHT, $1de
.word $81E8 ;sprite
.byte SCRIPTS::J_TALK, OBJ_MERRYSVILLE_CURFEWGUY_JTALK0-OBJ_MERRYSVILLE_CURFEWGUY
.byte SCRIPTS::DIALOGUE
.word UMSG::MERRYSVILLE_CURFEWGUY
      OBJ_MERRYSVILLE_CURFEWGUY_JTALK0:
.byte 0

OBJ_MERRYSVILLE_TRAINWOMAN:
objectDef OBJ_TYPE::WANDERING_NPC2, $16a, DIRECTIONS::DOWN, $1c2
.word $8288 ;sprite
.byte SCRIPTS::J_TALK, OBJ_MERRYSVILLE_TRAINWOMAN_JTALK0-OBJ_MERRYSVILLE_TRAINWOMAN
.byte SCRIPTS::FJ_JUMP, $71, OBJ_MERRYSVILLE_TRAINWOMAN_FJJUMP1-OBJ_MERRYSVILLE_TRAINWOMAN
.byte SCRIPTS::DIALOGUE
.word UMSG::MERRYSVILLE_TRAINWOMAN
.byte 0
      OBJ_MERRYSVILLE_TRAINWOMAN_FJJUMP1:
.byte SCRIPTS::DIALOGUE
.word UMSG::MERRYSVILLE_TRAINWOMAN2
      OBJ_MERRYSVILLE_TRAINWOMAN_JTALK0:
.byte 0

OBJ_MERRYSVILLE_NINTENDOGIRL:
objectDef OBJ_TYPE::WANDERING_NPC2, $170, DIRECTIONS::DOWN, $1d0
.word $8248 ;sprite
.byte SCRIPTS::J_TALK, OBJ_MERRYSVILLE_NINTENDOGIRL_JTALK0-OBJ_MERRYSVILLE_NINTENDOGIRL
.byte SCRIPTS::DIALOGUE
.word UMSG::MERRYSVILLE_NINTENDOGIRL
      OBJ_MERRYSVILLE_NINTENDOGIRL_JTALK0:
.byte 0

OBJ_MERRYSVILLE_HAPPYGUY:
objectDef OBJ_TYPE::WANDERING_NPC2, $174, DIRECTIONS::RIGHT, $1d6
.word $8268 ;sprite
.byte SCRIPTS::J_TALK, OBJ_MERRYSVILLE_HAPPYGUY_JTALK0-OBJ_MERRYSVILLE_HAPPYGUY
.byte SCRIPTS::DIALOGUE
.word UMSG::MERRYSVILLE_HAPPYGUY
      OBJ_MERRYSVILLE_HAPPYGUY_JTALK0:
.byte 0

OBJ_MERRYSVILLE_STRIPGIRL:
objectDef OBJ_TYPE::WANDERING_NPC2, $166, DIRECTIONS::LEFT, $1ce
.word $82A8 ;sprite
.byte SCRIPTS::J_TALK, OBJ_MERRYSVILLE_STRIPGIRL_JTALK0-OBJ_MERRYSVILLE_STRIPGIRL
.byte SCRIPTS::DIALOGUE
.word UMSG::MERRYSVILLE_STRIPGIRL
      OBJ_MERRYSVILLE_STRIPGIRL_JTALK0:
.byte 0

OBJ_MERRYSVILLE_DOCTORGUY:
objectDef OBJ_TYPE::WANDERING_NPC2, $173, DIRECTIONS::LEFT, $1c2
.word $82C8 ;sprite
.byte SCRIPTS::J_TALK, OBJ_MERRYSVILLE_DOCTORGUY_JTALK0-OBJ_MERRYSVILLE_DOCTORGUY
.byte SCRIPTS::DIALOGUE
.word UMSG::MERRYSVILLE_DOCTORGUY
      OBJ_MERRYSVILLE_DOCTORGUY_JTALK0:
.byte 0

OBJ_MERRYSVILLE_QUESTIONNAIRE:
objectDef OBJ_TYPE::WANDERING_NPC2, $168, DIRECTIONS::DOWN, $1c6
.word $8228 ;sprite
.byte SCRIPTS::J_TALK, OBJ_MERRYSVILLE_QUESTIONNAIRE_JTALK0-OBJ_MERRYSVILLE_QUESTIONNAIRE
.byte SCRIPTS::FJ_JUMP, $6F, OBJ_MERRYSVILLE_QUESTIONNAIRE_FJJUMP1-OBJ_MERRYSVILLE_QUESTIONNAIRE
.byte SCRIPTS::DIALOGUE
.word UMSG::MERRYSVILLE_QUESTIONNAIRE_DONE
.byte 0
      OBJ_MERRYSVILLE_QUESTIONNAIRE_FJJUMP1:
.byte SCRIPTS::DIALOGUE
.word UMSG::MERRYSVILLE_QUESTIONNAIRE
.byte SCRIPTS::J_YESNO, OBJ_MERRYSVILLE_QUESTIONNAIRE_JYESNO2-OBJ_MERRYSVILLE_QUESTIONNAIRE
.byte SCRIPTS::DIALOGUE
.word UMSG::MERRYSVILLE_QUESTIONNAIRE_Q1
.byte SCRIPTS::J_YESNO, OBJ_MERRYSVILLE_QUESTIONNAIRE_JYESNO3-OBJ_MERRYSVILLE_QUESTIONNAIRE
      OBJ_MERRYSVILLE_QUESTIONNAIRE_JYESNO3:
.byte SCRIPTS::DIALOGUE
.word UMSG::MERRYSVILLE_QUESTIONNAIRE_Q2
.byte SCRIPTS::J_YESNO, OBJ_MERRYSVILLE_QUESTIONNAIRE_JYESNO4-OBJ_MERRYSVILLE_QUESTIONNAIRE
      OBJ_MERRYSVILLE_QUESTIONNAIRE_JYESNO4:
.byte SCRIPTS::DIALOGUE
.word UMSG::MERRYSVILLE_QUESTIONNAIRE_FINISH
.byte SCRIPTS::IJ_HASITEM, $0, OBJ_MERRYSVILLE_QUESTIONNAIRE_IJHASITEM5-OBJ_MERRYSVILLE_QUESTIONNAIRE
.byte SCRIPTS::I_PICKITEM, $2
.byte SCRIPTS::J_GIVEITEM, OBJ_MERRYSVILLE_QUESTIONNAIRE_JTALK0-OBJ_MERRYSVILLE_QUESTIONNAIRE
.byte SCRIPTS::C_RESETCOUNTER, $4
      OBJ_MERRYSVILLE_QUESTIONNAIRE_CNJCOMPCOUNTER6:
.byte SCRIPTS::C_INCCOUNTER, $4
.byte SCRIPTS::CNJ_COMPCOUNTER, $4, $32, OBJ_MERRYSVILLE_QUESTIONNAIRE_CNJCOMPCOUNTER6-OBJ_MERRYSVILLE_QUESTIONNAIRE
.byte SCRIPTS::S_PLAYSOUND, $6
.byte SCRIPTS::F_SETFLAG, $6F
.byte 0
      OBJ_MERRYSVILLE_QUESTIONNAIRE_IJHASITEM5:
.byte SCRIPTS::DIALOGUE
.word UMSG::MERRYSVILLE_QUESTIONNAIRE_NOROOM
.byte 0
      OBJ_MERRYSVILLE_QUESTIONNAIRE_JYESNO2:
.byte SCRIPTS::DIALOGUE
.word UMSG::MERRYSVILLE_QUESTIONNAIRE_DECLINE
      OBJ_MERRYSVILLE_QUESTIONNAIRE_JTALK0:
.byte 0

OBJ_MERRYSVILLE_SCHOOLGUY:
objectDef OBJ_TYPE::WANDERING_NPC2, $150, DIRECTIONS::UP, $1a8
.word $8268 ;sprite
.byte SCRIPTS::J_TALK, OBJ_MERRYSVILLE_SCHOOLGUY_JTALK0-OBJ_MERRYSVILLE_SCHOOLGUY
.byte SCRIPTS::DIALOGUE
.word UMSG::MERRYSVILLE_SCHOOLGUY
      OBJ_MERRYSVILLE_SCHOOLGUY_JTALK0:
.byte 0

OBJ_MERRYSVILLE_MAYORGUY:
objectDef OBJ_TYPE::WANDERING_NPC2, $157, DIRECTIONS::UP, $1aa
.word $8228 ;sprite
.byte SCRIPTS::J_TALK, OBJ_MERRYSVILLE_MAYORGUY_JTALK0-OBJ_MERRYSVILLE_MAYORGUY
.byte SCRIPTS::FJ_JUMP, $71, OBJ_MERRYSVILLE_MAYORGUY_FJJUMP1-OBJ_MERRYSVILLE_MAYORGUY
.byte SCRIPTS::DIALOGUE
.word UMSG::MERRYSVILLE_TRAINWOMAN
.byte 0
      OBJ_MERRYSVILLE_MAYORGUY_FJJUMP1:
.byte SCRIPTS::DIALOGUE
.word UMSG::MERRYSVILLE_MAYORGUY
      OBJ_MERRYSVILLE_MAYORGUY_JTALK0:
.byte 0

OBJ_MERRYSVILLE_ROCKETGUY:
objectDef OBJ_TYPE::WANDERING_NPC2, $160, DIRECTIONS::DOWN, $1ad
.word $81E8 ;sprite
.byte SCRIPTS::J_TALK, OBJ_MERRYSVILLE_ROCKETGUY_JTALK0-OBJ_MERRYSVILLE_ROCKETGUY
.byte SCRIPTS::DIALOGUE
.word UMSG::MERRYSVILLE_ROCKETGUY
      OBJ_MERRYSVILLE_ROCKETGUY_JTALK0:
.byte 0

OBJ_MERRYSVILLE_ORDINARYGUY:
objectDef OBJ_TYPE::WANDERING_NPC2, $15c, DIRECTIONS::RIGHT, $1c2
.word $81A8 ;sprite
.byte SCRIPTS::J_TALK, OBJ_MERRYSVILLE_ORDINARYGUY_JTALK0-OBJ_MERRYSVILLE_ORDINARYGUY
.byte SCRIPTS::DIALOGUE
.word UMSG::MERRYSVILLE_ORDINARYGUY
      OBJ_MERRYSVILLE_ORDINARYGUY_JTALK0:
.byte 0

OBJ_MERRYSVILLE_THINKINGGUY:
objectDef OBJ_TYPE::WANDERING_NPC2, $162, DIRECTIONS::DOWN, $1ce
.word $8228 ;sprite
.byte SCRIPTS::J_TALK, OBJ_MERRYSVILLE_THINKINGGUY_JTALK0-OBJ_MERRYSVILLE_THINKINGGUY
.byte SCRIPTS::FJ_JUMP, $71, OBJ_MERRYSVILLE_THINKINGGUY_FJJUMP1-OBJ_MERRYSVILLE_THINKINGGUY
.byte SCRIPTS::DIALOGUE
.word UMSG::MERRYSVILLE_TRAINWOMAN
.byte 0
      OBJ_MERRYSVILLE_THINKINGGUY_FJJUMP1:
.byte SCRIPTS::DIALOGUE
.word UMSG::MERRYSVILLE_THINKINGGUY
      OBJ_MERRYSVILLE_THINKINGGUY_JTALK0:
.byte 0

OBJ_MERRYSVILLE_HUSBANDGIRL:
objectDef OBJ_TYPE::WANDERING_NPC2, $150, DIRECTIONS::LEFT, $1c4
.word $8248 ;sprite
.byte SCRIPTS::J_TALK, OBJ_MERRYSVILLE_HUSBANDGIRL_JTALK0-OBJ_MERRYSVILLE_HUSBANDGIRL
.byte SCRIPTS::DIALOGUE
.word UMSG::MERRYSVILLE_HUSBANDGIRL
      OBJ_MERRYSVILLE_HUSBANDGIRL_JTALK0:
.byte 0

OBJ_MERRYSVILLE_SWEETSGUY:
objectDef OBJ_TYPE::WANDERING_NPC2, $153, DIRECTIONS::DOWN, $1b6
.word $8268 ;sprite
.byte SCRIPTS::J_TALK, OBJ_MERRYSVILLE_SWEETSGUY_JTALK0-OBJ_MERRYSVILLE_SWEETSGUY
.byte SCRIPTS::DIALOGUE
.word UMSG::MERRYSVILLE_SWEETSGUY
.byte SCRIPTS::J_YESNO, OBJ_MERRYSVILLE_SWEETSGUY_JYESNO1-OBJ_MERRYSVILLE_SWEETSGUY
.byte SCRIPTS::DIALOGUE
.word UMSG::MERRYSVILLE_SWEETSGUY_YES
.byte 0
      OBJ_MERRYSVILLE_SWEETSGUY_JYESNO1:
.byte SCRIPTS::DIALOGUE
.word UMSG::PODUNK_CANARYGIRL2
      OBJ_MERRYSVILLE_SWEETSGUY_JTALK0:
.byte 0

OBJ_MERRYSVILLE_MONSTERGIRL:
objectDef OBJ_TYPE::WANDERING_NPC2, $14f, DIRECTIONS::LEFT, $1c0
.word $8208 ;sprite
.byte SCRIPTS::J_TALK, OBJ_MERRYSVILLE_MONSTERGIRL_JTALK0-OBJ_MERRYSVILLE_MONSTERGIRL
.byte SCRIPTS::DIALOGUE
.word UMSG::MERRYSVILLE_MONSTERGIRL
      OBJ_MERRYSVILLE_MONSTERGIRL_JTALK0:
.byte 0

OBJ_MERRYSVILLE_HOSPITALSIGN:
objectDef $19, $16d, DIRECTIONS::UP, $1c1
.word $8194 ;sprite
.byte SCRIPTS::J_CHECK, OBJ_MERRYSVILLE_HOSPITALSIGN_JCHECK0-OBJ_MERRYSVILLE_HOSPITALSIGN
.byte SCRIPTS::DIALOGUE
.word UMSG::MERRYSVILLE_HOSPITALSIGN
      OBJ_MERRYSVILLE_HOSPITALSIGN_JCHECK0:
.byte 0

OBJ_MERRYSVILLE_SIGN:
objectDef $19, $14a, DIRECTIONS::UP, $19d
.word $8194 ;sprite
.byte SCRIPTS::J_CHECK, OBJ_MERRYSVILLE_SIGN_JCHECK0-OBJ_MERRYSVILLE_SIGN
.byte SCRIPTS::DIALOGUE
.word UMSG::MERRYSVILLE_SIGN
      OBJ_MERRYSVILLE_SIGN_JCHECK0:
.byte 0

OBJ_MERRYSVILLE_DUNCANSIGN:
objectDef $19, $174, DIRECTIONS::UP, $1cd
.word $8194 ;sprite
.byte SCRIPTS::J_CHECK, OBJ_MERRYSVILLE_DUNCANSIGN_JCHECK0-OBJ_MERRYSVILLE_DUNCANSIGN
.byte SCRIPTS::DIALOGUE
.word UMSG::MERRYSVILLE_DUNCANSIGN
      OBJ_MERRYSVILLE_DUNCANSIGN_JCHECK0:
.byte 0

OBJ_MERRYSVILLE_SCHOOLSIGN:
objectDef $19, $169, DIRECTIONS::UP, $1d0
.word $8194 ;sprite
.byte SCRIPTS::J_CHECK, OBJ_MERRYSVILLE_SCHOOLSIGN_JCHECK0-OBJ_MERRYSVILLE_SCHOOLSIGN
.byte SCRIPTS::DIALOGUE
.word UMSG::MERRYSVILLE_SCHOOLSIGN
      OBJ_MERRYSVILLE_SCHOOLSIGN_JCHECK0:
.byte 0

OBJ_MERRYSVILLE_TELEPORTGAIN1:
objectDef $29, $157, DIRECTIONS::UP, $1cb
teleportFlagDef 2, $1D
.byte $00
OBJ_MERRYSVILLE_TELEPORTGAIN2:
objectDef $29, $165, DIRECTIONS::UP, $1cb
teleportFlagDef 2, $1D
.byte $00
OBJ_MERRYSVILLE_TELEPORTGAIN3:
objectDef $29, $173, DIRECTIONS::UP, $1cb
teleportFlagDef 2, $1D
.byte $00
OBJ_MERRYSVILLE_TELEPORTGAIN4:
objectDef $29, $157, DIRECTIONS::UP, $1bd
teleportFlagDef 2, $1D
.byte $00
OBJ_MERRYSVILLE_TELEPORTGAIN5:
objectDef $29, $173, DIRECTIONS::UP, $1bd
teleportFlagDef 2, $1D
.byte $00
OBJ_MERRYSVILLE_TELEPORTGAIN6:
objectDef $29, $157, DIRECTIONS::UP, $1af
teleportFlagDef 2, $1D
.byte $00
OBJ_MERRYSVILLE_TELEPORTGAIN7:
objectDef $29, $173, DIRECTIONS::UP, $1af
teleportFlagDef 2, $1D
.byte $00
OBJ_MERRYSVILLE_TELEPORTGAIN8:
objectDef $29, $157, DIRECTIONS::UP, $1a1
teleportFlagDef 2, $1D
.byte $00
OBJ_MERRYSVILLE_TELEPORTGAIN9:
objectDef $29, $165, DIRECTIONS::UP, $1a1
teleportFlagDef 2, $1D
.byte $00
OBJ_MERRYSVILLE_TELEPORTGAINA:
objectDef $29, $173, DIRECTIONS::UP, $1a1
teleportFlagDef 2, $1D
.byte $00