OBJ_BANK_E:
.addr OBJ_PODUNK_MAGICAVEENTRANCE
.addr OBJ_PODUNK_MAGICOP1
.addr OBJ_PODUNK_MAGICOP2
.addr 0

OBJ_PODUNK_MAGICAVEENTRANCE:
objectDef OBJ_TYPE::DOOR, $149, DIRECTIONS::UP, $e7
doorArgDef $31, $3C2, DIRECTIONS::DOWN, $215

OBJ_PODUNK_MAGICOP1:
objectDef OBJ_TYPE::STATIONARY_NPC, $fe, DIRECTIONS::LEFT, $d3
.addr SPRITEDEF_COP ;sprite
OBJ_IS_NOT_TALKING @JTALK0-OBJ_PODUNK_MAGICOP1
OBJ_IS_NOT_FLAG $D, @FJJUMP1-OBJ_PODUNK_MAGICOP1
OBJ_HAS_MOVED @JUNK22-OBJ_PODUNK_MAGICOP1
OBJ_DIALOGUE UMSG::PODUNK_MAGICOP_LIFTED
OBJ_SIGNAL $2
OBJ_IS_NOT_FACING @JUNK3-OBJ_PODUNK_MAGICOP1
OBJ_MOVE @MOVE0
OBJ_STOP
    @JUNK3:
OBJ_MOVE @MOVE1
OBJ_STOP
    @FJJUMP1:
OBJ_DIALOGUE UMSG::PODUNK_MAGICOP
OBJ_STOP
    @JUNK22:
OBJ_DIALOGUE UMSG::PODUNK_MAGICOP_LIFTED
OBJ_STOP
    @JTALK0:
OBJ_IS_SIGNAL @JSIGNALED4-OBJ_PODUNK_MAGICOP1
OBJ_IS_NOT_FACING @JUNK5-OBJ_PODUNK_MAGICOP1
OBJ_MOVE @MOVE0
OBJ_STOP
    @JUNK5:
OBJ_MOVE @MOVE1
    @JSIGNALED4:
OBJ_STOP
    @MOVE0:
moveDef DIRECTIONS::RIGHT, MOVE_CMD::ABOUTFACE, $1
moveDef DIRECTIONS::LEFT, MOVE_CMD::MOVE, $2
moveDef DIRECTIONS::UP, MOVE_CMD::MOVE, $1
OBJ_STOP
    @MOVE1:
moveDef DIRECTIONS::RIGHT, MOVE_CMD::MOVE, $2
moveDef DIRECTIONS::UP, MOVE_CMD::MOVE, $1
OBJ_STOP

OBJ_PODUNK_MAGICOP2:
objectDef OBJ_TYPE::STATIONARY_NPC, $fe, DIRECTIONS::LEFT, $d4
.addr SPRITEDEF_COP ;sprite
OBJ_IS_NOT_TALKING @JTALK0-OBJ_PODUNK_MAGICOP2
OBJ_IS_NOT_FLAG $D, @FJJUMP1-OBJ_PODUNK_MAGICOP2
OBJ_HAS_MOVED @JUNK22-OBJ_PODUNK_MAGICOP2
OBJ_DIALOGUE UMSG::PODUNK_MAGICOP2_LIFTED2
OBJ_DIALOGUE UMSG::PODUNK_MAGICOP2_LIFTED
OBJ_SIGNAL $1
OBJ_IS_NOT_FACING @JUNK3-OBJ_PODUNK_MAGICOP2
OBJ_MOVE @MOVE0
OBJ_STOP
    @JUNK3:
OBJ_MOVE @MOVE1
OBJ_STOP
    @FJJUMP1:
OBJ_DIALOGUE UMSG::PODUNK_MAGICOP
OBJ_STOP
    @JUNK22:
OBJ_DIALOGUE UMSG::PODUNK_MAGICOP2_LIFTED2
OBJ_DIALOGUE UMSG::PODUNK_MAGICOP2_LIFTED
OBJ_STOP
    @JTALK0:
OBJ_IS_SIGNAL @JSIGNALED4-OBJ_PODUNK_MAGICOP2
OBJ_IS_NOT_FACING @JUNK5-OBJ_PODUNK_MAGICOP2
OBJ_MOVE @MOVE0
OBJ_STOP
    @JUNK5:
OBJ_MOVE @MOVE1
    @JSIGNALED4:
OBJ_STOP
    @MOVE0:
moveDef DIRECTIONS::RIGHT, MOVE_CMD::ABOUTFACE, $1
moveDef DIRECTIONS::LEFT, MOVE_CMD::MOVE, $3
moveDef DIRECTIONS::DOWN, MOVE_CMD::MOVE, $1
OBJ_STOP
    @MOVE1:
moveDef DIRECTIONS::RIGHT, MOVE_CMD::MOVE, $1
moveDef DIRECTIONS::DOWN, MOVE_CMD::MOVE, $1
OBJ_STOP