;differences are the melody command (duh) and
;the merrysville - reindeer railroad was made harder
;the encounters are similar to Yucca Desert so that explains a lot

OBJ_BANK_14:
.word OBJ_YUCCA_MONKEYCAVEENTRANCE
.word OBJ_YUCCA_R7037
.word OBJ_YUCCA_NICEBONES
.word OBJ_YUCCA_SIGNBONES
.word OBJ_YUCCA_BRAVEBONES
.word OBJ_YUCCA_CAMELBONES
.word OBJ_YUCCA_GAMEBONES
.word OBJ_YUCCA_SINGINGCACTUS
.word OBJ_YUCCA_MINE
.ifndef VER_JP
.word OBJ_MR_RAILROADLEFTEXIT
.word OBJ_MR_RAILROADRIGHTEXIT
.word OBJ_MR_RAILROADCORPSE
.endif
.word 0

OBJ_YUCCA_MONKEYCAVEENTRANCE:
objectDef OBJ_TYPE::HOLE, $27a, DIRECTIONS::UP, $112
doorArgDef $18, $51, DIRECTIONS::DOWN, $1CC

OBJ_YUCCA_R7037:
objectDef $1c, $275, DIRECTIONS::UP, $119
.byte SCRIPTS::F_DISAPPEAR, $78
.byte SCRIPTS::J_TOUCH, OBJ_YUCCA_R7037_JTOUCH0-OBJ_YUCCA_R7037
.byte SCRIPTS::B_BATTLE, $6F
      OBJ_YUCCA_R7037_JTOUCH0:
.byte 0

OBJ_YUCCA_NICEBONES:
objectDef $19, $1a3, DIRECTIONS::UP, $fc
.word $8564 ;sprite
.byte SCRIPTS::J_TALK, OBJ_YUCCA_NICEBONES_JTALK0-OBJ_YUCCA_NICEBONES
.byte SCRIPTS::DIALOGUE
.word UMSG::YUCCA_NICEBONES
      OBJ_YUCCA_NICEBONES_JTALK0:
.byte 0

OBJ_YUCCA_SIGNBONES:
objectDef $19, $28d, DIRECTIONS::UP, $104
.word $8564 ;sprite
.byte SCRIPTS::J_TALK, OBJ_YUCCA_SIGNBONES_JTALK0-OBJ_YUCCA_SIGNBONES
.byte SCRIPTS::DIALOGUE
.word UMSG::YUCCA_SIGNBONES
      OBJ_YUCCA_SIGNBONES_JTALK0:
.byte 0

OBJ_YUCCA_BRAVEBONES:
objectDef $19, $1c0, DIRECTIONS::UP, $125
.word $8564 ;sprite
.byte SCRIPTS::J_TALK, OBJ_YUCCA_BRAVEBONES_JTALK0-OBJ_YUCCA_BRAVEBONES
.byte SCRIPTS::DIALOGUE
.word UMSG::YUCCA_BRAVEBONES
      OBJ_YUCCA_BRAVEBONES_JTALK0:
.byte 0

OBJ_YUCCA_CAMELBONES:
objectDef $19, $216, DIRECTIONS::UP, $100
.word $8564 ;sprite
.byte SCRIPTS::J_TALK, OBJ_YUCCA_CAMELBONES_JTALK0-OBJ_YUCCA_CAMELBONES
.byte SCRIPTS::DIALOGUE
.word UMSG::YUCCA_CAMELBONES
      OBJ_YUCCA_CAMELBONESJ_JUMP2:
.byte SCRIPTS::J_YESNO, OBJ_YUCCA_CAMELBONES_JYESNO1-OBJ_YUCCA_CAMELBONES
.byte SCRIPTS::DIALOGUE
.word UMSG::YUCCA_CAMELBONES_ACCEPT
.byte 0
      OBJ_YUCCA_CAMELBONES_JYESNO1:
.byte SCRIPTS::DIALOGUE
.word UMSG::YUCCA_CAMELBONES_DECLINE
.byte SCRIPTS::J_JUMP, OBJ_YUCCA_CAMELBONESJ_JUMP2-OBJ_YUCCA_CAMELBONES
.byte 0
      OBJ_YUCCA_CAMELBONES_JTALK0:
.byte 0

OBJ_YUCCA_GAMEBONES:
objectDef $19, $22c, DIRECTIONS::UP, $134
.word $8564 ;sprite
.byte SCRIPTS::J_TALK, OBJ_YUCCA_GAMEBONES_JTALK0-OBJ_YUCCA_GAMEBONES
.byte SCRIPTS::DIALOGUE
.word UMSG::YUCCA_GAMEBONES
      OBJ_YUCCA_GAMEBONES_JTALK0:
.byte 0

OBJ_YUCCA_SINGINGCACTUS:
objectDef $18, $1be, DIRECTIONS::UP, $10d
.byte SCRIPTS::J_CHECK, OBJ_YUCCA_SINGINGCACTUS_JCHECK0-OBJ_YUCCA_SINGINGCACTUS
.byte SCRIPTS::DIALOGUE
.word UMSG::REINDEER_DRAGONGIRL_CHECK
.byte 0
      OBJ_YUCCA_SINGINGCACTUS_JCHECK0:
.byte SCRIPTS::PJ_USE, $1, OBJ_YUCCA_SINGINGCACTUS_PJUSE1-OBJ_YUCCA_SINGINGCACTUS
.byte SCRIPTS::DIALOGUE
.word UMSG::YUCCA_SINGINGCACTUS
.byte SCRIPTS::M_MUSIC, $28
.byte SCRIPTS::T_DELAY, $F0
.byte SCRIPTS::M_MUSIC, $8
.byte SCRIPTS::F_SETFLAG, $F3
.byte SCRIPTS::DIALOGUE
.word UMSG::REMEMBER_MELODY
.ifdef VER_JP
.byte $65
.endif
      OBJ_YUCCA_SINGINGCACTUS_PJUSE1:
.byte 0

OBJ_YUCCA_MINE:
objectDef $1f, $2a5, DIRECTIONS::UP, $105
.byte SCRIPTS::F_DISAPPEAR, $3B
.byte SCRIPTS::J_TOUCH, OBJ_YUCCA_MINE_JTOUCH0-OBJ_YUCCA_MINE
.byte SCRIPTS::LANDMINE
.byte SCRIPTS::DIALOGUE
.word UMSG::YUCCA_MINE
.byte SCRIPTS::F_SETFLAG, $3B
      OBJ_YUCCA_MINE_JTOUCH0:
.byte 0

.ifndef VER_JP
OBJ_MR_RAILROADLEFTEXIT:
objectDef OBJ_TYPE::DOOR, $8, DIRECTIONS::LEFT, $3fa
doorArgDef $6, $1B1, DIRECTIONS::LEFT, $1CF

OBJ_MR_RAILROADRIGHTEXIT:
objectDef OBJ_TYPE::DOOR, $167, DIRECTIONS::RIGHT, $3fa
doorArgDef $6, $1B2, DIRECTIONS::DOWN, $2E4

OBJ_MR_RAILROADCORPSE:
objectDef $19, $58, DIRECTIONS::UP, $3fb
.word $8564 ;sprite
.byte SCRIPTS::J_TALK, OBJ_MR_RAILROADCORPSE_JTALK0-OBJ_MR_RAILROADCORPSE
.byte SCRIPTS::DIALOGUE
.word UMSG::MR_RAILROADCORPSE
      OBJ_MR_RAILROADCORPSE_JTALK0:
.byte 0
.endif