OBJ_BANK_17:
.addr OBJ_PODUNK_HOSPITALEXIT
.addr OBJ_PODUNK_HOSPITALUPSTAIRS
.addr OBJ_PODUNK_HOSPITALOFFICEENTRANCE
.addr OBJ_PODUNK_HOSPITALOFFICEEXIT
.addr OBJ_MERRYSVILLE_HOSPITALEXIT
.addr OBJ_MERRYSVILLE_HOSPITALOFFICEENTRANCE
.addr OBJ_MERRYSVILLE_HOSPITALOFFICEEXIT
.addr OBJ_REINDEER_HOSPITALEXIT
.addr OBJ_REINDEER_HOSPITALUPSTAIRS
.addr OBJ_REINDEER_HOSPITALOFFICEENTRANCE
.addr OBJ_REINDEER_HOSPITALOFFICEEXIT
.addr OBJ_ELLAY_HOSPITALEXIT
.addr OBJ_ELLAY_HOSPITALUPSTAIRS
.addr OBJ_ELLAY_HOSPITALOFFICEENTRANCE
.addr OBJ_ELLAY_HOSPITAL_UPROOM1EXIT
.addr OBJ_ELLAY_HOSPITAL_UPROOM2EXIT
.addr OBJ_PODUNK_HOSPITALDOCTOR
.addr OBJ_REINDEER_HOSPITALDOCTOR
.addr OBJ_MERRYSVILLE_HOSPITALDOCTOR
.addr OBJ_PODUNK_HOSPITALNURSE
.addr OBJ_REINDEER_HOSPITALNURSE
.addr OBJ_ELLAY_HOSPITALNURSE
.addr OBJ_MERRYSVILLE_HOSPITALNURSE
.addr OBJ_REINDEER_HOSPITALWEIGHTGUY
.addr OBJ_REINDEER_HOSPITALCOLDGUY
.addr 0


OBJ_PODUNK_HOSPITALEXIT:
objectDef OBJ_TYPE::DOOR, $31e, DIRECTIONS::RIGHT, $3f6
doorArgDef $6, $BF, DIRECTIONS::DOWN, $1BD
OBJ_PODUNK_HOSPITALUPSTAIRS:
objectDef OBJ_TYPE::STAIRS, $312, DIRECTIONS::LEFT, $3f5
doorArgDef $0, $302, DIRECTIONS::RIGHT, $86
OBJ_PODUNK_HOSPITALOFFICEENTRANCE:
objectDef OBJ_TYPE::DOOR, $318, DIRECTIONS::UP, $3f3
doorArgDef $0, $D, DIRECTIONS::LEFT, $86
OBJ_PODUNK_HOSPITALOFFICEEXIT:
objectDef OBJ_TYPE::DOOR, $e, DIRECTIONS::RIGHT, $86
doorArgDef $0, $318, DIRECTIONS::DOWN, $3F4

OBJ_MERRYSVILLE_HOSPITALEXIT:
objectDef OBJ_TYPE::DOOR, $e, DIRECTIONS::RIGHT, $146
doorArgDef $6, $16E, DIRECTIONS::DOWN, $1C1
OBJ_MERRYSVILLE_HOSPITALOFFICEENTRANCE:
objectDef OBJ_TYPE::DOOR, $1, DIRECTIONS::LEFT, $146
doorArgDef $0, $29D, DIRECTIONS::LEFT, $3D6
OBJ_MERRYSVILLE_HOSPITALOFFICEEXIT:
objectDef OBJ_TYPE::DOOR, $29e, DIRECTIONS::RIGHT, $3d6
doorArgDef $0, $2, DIRECTIONS::RIGHT, $146

OBJ_REINDEER_HOSPITALEXIT:
objectDef OBJ_TYPE::DOOR, $2de, DIRECTIONS::RIGHT, $3f6
doorArgDef $6, $1E6, DIRECTIONS::DOWN, $3AD
OBJ_REINDEER_HOSPITALUPSTAIRS:
objectDef OBJ_TYPE::STAIRS, $2d2, DIRECTIONS::LEFT, $3f5
doorArgDef $0, $12, DIRECTIONS::RIGHT, $156
OBJ_REINDEER_HOSPITALOFFICEENTRANCE:
objectDef OBJ_TYPE::DOOR, $2d6, DIRECTIONS::UP, $3f3
doorArgDef $0, $24D, DIRECTIONS::LEFT, $86
OBJ_REINDEER_HOSPITALOFFICEEXIT:
objectDef OBJ_TYPE::DOOR, $24e, DIRECTIONS::RIGHT, $86
doorArgDef $0, $2D6, DIRECTIONS::DOWN, $3F4

OBJ_ELLAY_HOSPITALEXIT:
objectDef OBJ_TYPE::DOOR, $2fe, DIRECTIONS::RIGHT, $3f6
doorArgDef $6, $30B, DIRECTIONS::DOWN, $12D
OBJ_ELLAY_HOSPITALUPSTAIRS:
objectDef OBJ_TYPE::STAIRS, $2f2, DIRECTIONS::LEFT, $3f5
doorArgDef $0, $352, DIRECTIONS::RIGHT, $96
OBJ_ELLAY_HOSPITALOFFICEENTRANCE:
objectDef OBJ_TYPE::DOOR, $2f6, DIRECTIONS::UP, $3f3
doorArgDef $0, $2DD, DIRECTIONS::LEFT, $96

OBJ_ELLAY_HOSPITAL_UPROOM1EXIT:
objectDef OBJ_TYPE::DOOR, $2e, DIRECTIONS::RIGHT, $126
doorArgDef $0, $356, DIRECTIONS::DOWN, $94
OBJ_ELLAY_HOSPITAL_UPROOM2EXIT:
objectDef OBJ_TYPE::DOOR, $2e, DIRECTIONS::RIGHT, $146
doorArgDef $0, $359, DIRECTIONS::DOWN, $94

OBJ_PODUNK_HOSPITALDOCTOR:
objectDef OBJ_TYPE::STATIONARY_NPC, $4, DIRECTIONS::DOWN, $84
.addr SPRITEDEF_DOCTOR ;sprite
OBJ_LOAD_NUMBER 25
OBJ_SUBROUTINE OBJ_PODUNK_HOSPITALDOCTOR, OBJ_PODUNK_HOSPITALDOCTOR_OJSUBROUTINE0-OBJ_PODUNK_HOSPITALDOCTOR
OBJ_STOP

    OBJ_PODUNK_HOSPITALDOCTOR_OJSUBROUTINE0:
OBJ_IS_NOT_TALKING @JTALK0-OBJ_PODUNK_HOSPITALDOCTOR
OBJ_DIALOGUE UMSG::PODUNK_HOSPITALDOCTOR
OBJ_YESNO_IS_NO @JYESNO1-OBJ_PODUNK_HOSPITALDOCTOR
OBJ_TAKE_MONEY @JTAKEMONEY2-OBJ_PODUNK_HOSPITALDOCTOR
OBJ_PICK_CHARACTER_J $1, @CJSELECTPARTY3-OBJ_PODUNK_HOSPITALDOCTOR
.byte SCRIPTS::J_CHOOSECHAR, @JCHOOSECHAR4-OBJ_PODUNK_HOSPITALDOCTOR
OBJ_JUMP @JUMP5-OBJ_PODUNK_HOSPITALDOCTOR
    @CJSELECTPARTY3:
OBJ_PICK_CHARACTER_J $0, @JUMP5-OBJ_PODUNK_HOSPITALDOCTOR
    @JUMP5:
OBJ_HAS_STATUS $80, @SJPRESENT6-OBJ_PODUNK_HOSPITALDOCTOR
OBJ_NOT_MAX_HEALTH @JNOTMAX7-OBJ_PODUNK_HOSPITALDOCTOR
OBJ_HAS_STATUS $3, @JNOTMAX7-OBJ_PODUNK_HOSPITALDOCTOR
OBJ_DIALOGUE UMSG::PODUNK_HOSPITALDOCTOR_NORMAL
OBJ_GIVE_MONEY @JTALK0-OBJ_PODUNK_HOSPITALDOCTOR
OBJ_RETURN
    @JNOTMAX7:
OBJ_HEAL $FF
OBJ_NOT_MAX_HEALTH @JNOTMAX7-OBJ_PODUNK_HOSPITALDOCTOR
OBJ_AND_STATUS $FC
OBJ_SHOW_MONEY
OBJ_PLAY_SOUND $7
OBJ_DIALOGUE UMSG::PODUNK_HOSPITALDOCTOR_ACCEPT
OBJ_RETURN
    @JCHOOSECHAR4:
OBJ_GIVE_MONEY @JTALK0-OBJ_PODUNK_HOSPITALDOCTOR
    @JYESNO1:
OBJ_DIALOGUE UMSG::PODUNK_HOSPITALDOCTOR_DECLINE
OBJ_RETURN
    @SJPRESENT6:
OBJ_GIVE_MONEY @JTALK0-OBJ_PODUNK_HOSPITALDOCTOR
OBJ_DIALOGUE UMSG::HOSPITAL_NOPERSON
OBJ_RETURN
    @JTAKEMONEY2:
OBJ_DIALOGUE UMSG::YUCCA_PILOT_NOMONEY
    @JTALK0:
OBJ_RETURN

OBJ_REINDEER_HOSPITALDOCTOR:
objectDef OBJ_TYPE::STATIONARY_NPC, $244, DIRECTIONS::DOWN, $84
.addr SPRITEDEF_DOCTOR ;sprite
OBJ_LOAD_NUMBER 60
OBJ_SUBROUTINE OBJ_PODUNK_HOSPITALDOCTOR, OBJ_PODUNK_HOSPITALDOCTOR_OJSUBROUTINE0-OBJ_PODUNK_HOSPITALDOCTOR
OBJ_STOP

OBJ_MERRYSVILLE_HOSPITALDOCTOR:
objectDef OBJ_TYPE::STATIONARY_NPC, $294, DIRECTIONS::DOWN, $3d4
.addr SPRITEDEF_DOCTOR ;sprite
OBJ_IS_NOT_TALKING @JTALK0-OBJ_MERRYSVILLE_HOSPITALDOCTOR
.byte SCRIPTS::GETCASH
.byte SCRIPTS::N_MULNUMBER, 50
OBJ_DIALOGUE UMSG::MERRYSVILLE_HOSPITALDOCTOR
OBJ_YESNO_IS_NO @JYESNO1-OBJ_MERRYSVILLE_HOSPITALDOCTOR
.byte SCRIPTS::GETCASH
.byte SCRIPTS::N_MULNUMBER, 50
OBJ_TAKE_MONEY @JTALK0-OBJ_MERRYSVILLE_HOSPITALDOCTOR
OBJ_PICK_CHARACTER_J $0, @CJSELECTPARTY2-OBJ_MERRYSVILLE_HOSPITALDOCTOR
OBJ_HAS_STATUS $80, @CJSELECTPARTY2-OBJ_MERRYSVILLE_HOSPITALDOCTOR
OBJ_AND_STATUS $FC
    @JNOTMAX3:
OBJ_HEAL $FF
OBJ_NOT_MAX_HEALTH @JNOTMAX3-OBJ_MERRYSVILLE_HOSPITALDOCTOR
OBJ_PICK_CHARACTER_J $1, @CJSELECTPARTY2-OBJ_MERRYSVILLE_HOSPITALDOCTOR
OBJ_HAS_STATUS $80, @CJSELECTPARTY2-OBJ_MERRYSVILLE_HOSPITALDOCTOR
OBJ_AND_STATUS $FC
    @JNOTMAX4:
OBJ_HEAL $FF
OBJ_NOT_MAX_HEALTH @JNOTMAX4-OBJ_MERRYSVILLE_HOSPITALDOCTOR
OBJ_PICK_CHARACTER_J $2, @CJSELECTPARTY2-OBJ_MERRYSVILLE_HOSPITALDOCTOR
OBJ_HAS_STATUS $80, @CJSELECTPARTY2-OBJ_MERRYSVILLE_HOSPITALDOCTOR
OBJ_AND_STATUS $FC
    @JNOTMAX5:
OBJ_HEAL $FF
OBJ_NOT_MAX_HEALTH @JNOTMAX5-OBJ_MERRYSVILLE_HOSPITALDOCTOR
    @CJSELECTPARTY2:
OBJ_PLAY_SOUND $7
OBJ_SHOW_MONEY
OBJ_DIALOGUE UMSG::MERRYSVILLE_HOSPITALDOCTOR_ACCEPT
OBJ_STOP
    @JYESNO1:
OBJ_DIALOGUE UMSG::MERRYSVILLE_HOSPITALDOCTOR_DECLINE
OBJ_STOP
    @JTALK0:
OBJ_STOP

OBJ_PODUNK_HOSPITALNURSE:
objectDef OBJ_TYPE::STATIONARY_NPC, $315, DIRECTIONS::DOWN, $3f4
.addr SPRITEDEF_NURSE ;sprite
OBJ_LOAD_NUMBER 125
OBJ_SUBROUTINE OBJ_PODUNK_HOSPITALNURSE, OBJ_PODUNK_HOSPITALNURSE_OJSUBROUTINE1-OBJ_PODUNK_HOSPITALNURSE
OBJ_STOP
    OBJ_PODUNK_HOSPITALNURSE_OJSUBROUTINE1:
OBJ_IS_NOT_TALKING @JTALK0-OBJ_PODUNK_HOSPITALNURSE
OBJ_DIALOGUE UMSG::HOSPITAL_NURSE
.byte SCRIPTS::J_CHOOSECHAR, @JCHOOSECHAR1-OBJ_PODUNK_HOSPITALNURSE
OBJ_HAS_STATUS $80, @SJPRESENT2-OBJ_PODUNK_HOSPITALNURSE
OBJ_JUMP @JUMP3-OBJ_PODUNK_HOSPITALNURSE
    @SJPRESENT2:
OBJ_DIALOGUE UMSG::HOSPITAL_NURSE_SELECT
OBJ_YESNO_IS_NO @JYESNO4-OBJ_PODUNK_HOSPITALNURSE
OBJ_TAKE_MONEY @JTAKEMONEY5-OBJ_PODUNK_HOSPITALNURSE
OBJ_AND_STATUS $0
OBJ_SHOW_MONEY
OBJ_DIALOGUE UMSG::HOSPITAL_NURSE_REVIVE
OBJ_RETURN
    @JTAKEMONEY5:
OBJ_DIALOGUE UMSG::HOSPITAL_NURSE_NOMONEY
OBJ_RETURN
    @JYESNO4:
OBJ_DIALOGUE UMSG::HOSPITAL_NURSE_NOREVIVE
OBJ_RETURN
    @JUMP3:
OBJ_DIALOGUE UMSG::HOSPITAL_NURSE_NOONE
OBJ_RETURN
    @JCHOOSECHAR1:
OBJ_DIALOGUE UMSG::HOSPITAL_NURSE_DECLINE
    @JTALK0:
OBJ_RETURN

OBJ_REINDEER_HOSPITALNURSE:
objectDef OBJ_TYPE::STATIONARY_NPC, $2d4, DIRECTIONS::DOWN, $3f4
.addr SPRITEDEF_NURSE ;sprite
OBJ_LOAD_NUMBER 300
OBJ_SUBROUTINE OBJ_PODUNK_HOSPITALNURSE, OBJ_PODUNK_HOSPITALNURSE_OJSUBROUTINE1-OBJ_PODUNK_HOSPITALNURSE
OBJ_STOP

OBJ_ELLAY_HOSPITALNURSE:
objectDef OBJ_TYPE::STATIONARY_NPC, $2f4, DIRECTIONS::RIGHT, $3f4
.addr SPRITEDEF_NURSE ;sprite
OBJ_LOAD_NUMBER 480
OBJ_SUBROUTINE OBJ_PODUNK_HOSPITALNURSE, OBJ_PODUNK_HOSPITALNURSE_OJSUBROUTINE1-OBJ_PODUNK_HOSPITALNURSE
OBJ_STOP

OBJ_MERRYSVILLE_HOSPITALNURSE:
objectDef OBJ_TYPE::STATIONARY_NPC, $8, DIRECTIONS::DOWN, $144
.addr SPRITEDEF_NURSE ;sprite
OBJ_LOAD_NUMBER 190
OBJ_SUBROUTINE OBJ_PODUNK_HOSPITALNURSE, OBJ_PODUNK_HOSPITALNURSE_OJSUBROUTINE1-OBJ_PODUNK_HOSPITALNURSE
OBJ_STOP

OBJ_REINDEER_HOSPITALWEIGHTGUY:
objectDef OBJ_TYPE::WANDERING_NPC, $2d4, DIRECTIONS::LEFT, $3f7
.addr SPRITEDEF_ABLE_BAKER ;sprite
OBJ_IS_NOT_TALKING @JTALK0-OBJ_REINDEER_HOSPITALWEIGHTGUY
OBJ_DIALOGUE UMSG::REINDEER_HOSPITALWEIGHTGUY
    @JTALK0:
OBJ_STOP

OBJ_REINDEER_HOSPITALCOLDGUY:
objectDef OBJ_TYPE::WANDERING_NPC, $2d6, DIRECTIONS::RIGHT, $3f7
.addr SPRITEDEF_GLASSES_GUY ;sprite
OBJ_IS_NOT_TALKING @JTALK0-OBJ_REINDEER_HOSPITALCOLDGUY
OBJ_DIALOGUE UMSG::REINDEER_HOSPITALCOLDGUY
    @JTALK0:
OBJ_STOP