;differences are the us added mt. itoi rooms
;and the cheapest flightplan added a loop around the cactus

OBJ_BANK_8:
.addr OBJ_YUCCA_PILOT
.addr OBJ_YUCCA_TANK
.addr OBJ_YUCCA_PLANE
.addr OBJ_YUCCA_SIGN
.addr OBJ_YUCCA_TANK2
.addr OBJ_YUCCA_R7037_TANK
.ifndef VER_JP ;us only
.addr OBJ_MTITOI_GIEGUECAVEEXIT
.addr OBJ_MTITOI_TUBESENTRANCE
.addr OBJ_MTITOI_GIEGUECAVETOP
.endif
.addr 0

OBJ_YUCCA_PILOT:
objectDef OBJ_TYPE::STATIONARY_NPC_CHECKSPAWN, $1f3, DIRECTIONS::DOWN, $121
.addr SPRITEDEF_2B5 ;sprite
OBJ_FLAG_DISAPPEAR  $17
OBJ_IS_NOT_USING  $64, OBJ_YUCCA_PILOT_IJUSE0-OBJ_YUCCA_PILOT
OBJ_RESET_COUNTER  $5
    OBJ_YUCCA_PILOT_CNJCOMPCOUNTER2:
OBJ_NOT_HAS_ITEM  $64, OBJ_YUCCA_PILOT_IJHASITEM1-OBJ_YUCCA_PILOT
OBJ_SHOW_MONEY
OBJ_PICK_ITEM  $64
OBJ_REMOVE_ITEM  OBJ_YUCCA_PILOT_IJHASITEM1-OBJ_YUCCA_PILOT
OBJ_INCREMENT_COUNTER  $5
OBJ_COUNTERLESSTHAN  $5, $A, OBJ_YUCCA_PILOT_CNJCOMPCOUNTER2-OBJ_YUCCA_PILOT
OBJ_DIALOGUE UMSG::YUCCA_PILOT_TANK
OBJ_SET_FLAG  $88
OBJ_STOP
    OBJ_YUCCA_PILOT_IJHASITEM1:
OBJ_COUNTERLESSTHAN  $5, $1, OBJ_YUCCA_PILOT_CNJCOMPCOUNTER3-OBJ_YUCCA_PILOT
OBJ_NOT_HAS_ITEM  $0, OBJ_YUCCA_PILOT_CNJCOMPCOUNTER3-OBJ_YUCCA_PILOT
OBJ_PICK_ITEM  $64
OBJ_GIVE_ITEM OBJ_YUCCA_PILOT_CNJCOMPCOUNTER3-OBJ_YUCCA_PILOT
OBJ_DECREMENT_COUNTER $5
OBJ_JUMP  OBJ_YUCCA_PILOT_IJHASITEM1-OBJ_YUCCA_PILOT
    OBJ_YUCCA_PILOT_CNJCOMPCOUNTER3:
OBJ_DIALOGUE UMSG::YUCCA_PILOT_NOMONEY2
OBJ_STOP
    OBJ_YUCCA_PILOT_IJUSE0:
OBJ_IS_NOT_TALKING  OBJ_YUCCA_PILOT_JTALK4-OBJ_YUCCA_PILOT
OBJ_IS_NOT_FLAG  $88, OBJ_YUCCA_PILOT_FJJUMP5-OBJ_YUCCA_PILOT
OBJ_DIALOGUE UMSG::YUCCA_PILOT_TANKRIDE
OBJ_STOP
    OBJ_YUCCA_PILOT_FJJUMP5:
OBJ_IS_NOT_FLAG  $3A, OBJ_YUCCA_PILOT_FJJUMP6-OBJ_YUCCA_PILOT
OBJ_DIALOGUE UMSG::YUCCA_PILOT_RIDE
OBJ_YESNO_IS_NO  OBJ_YUCCA_PILOT_JYESNO7-OBJ_YUCCA_PILOT
OBJ_DIALOGUE UMSG::YUCCA_PILOT_CHOOSEPLAN
OBJ_DISPLAY_ITEMS $9C, $9D, $9E, $0, OBJ_YUCCA_PILOT_JYESNO7-OBJ_YUCCA_PILOT
OBJ_CLEAR_FLAG  $89
OBJ_CLEAR_FLAG  $8A
OBJ_CLEAR_FLAG  $8B
OBJ_IS_NOT_SELECTED $9C, OBJ_YUCCA_PILOT_IJSELECTEDITEM8-OBJ_YUCCA_PILOT
OBJ_SET_FLAG  $89
OBJ_JUMP  OBJ_YUCCA_PILOTJ_JUMP9-OBJ_YUCCA_PILOT
    OBJ_YUCCA_PILOT_IJSELECTEDITEM8:
OBJ_IS_NOT_SELECTED $9D, OBJ_YUCCA_PILOT_IJSELECTEDITEM10-OBJ_YUCCA_PILOT
OBJ_SET_FLAG  $8A
OBJ_JUMP  OBJ_YUCCA_PILOTJ_JUMP9-OBJ_YUCCA_PILOT
    OBJ_YUCCA_PILOT_IJSELECTEDITEM10:
OBJ_IS_NOT_SELECTED $9E, OBJ_YUCCA_PILOTJ_JUMP9-OBJ_YUCCA_PILOT
OBJ_SET_FLAG  $8B
    OBJ_YUCCA_PILOTJ_JUMP9:
OBJ_RESET_COUNTER  $0
OBJ_INCREMENT_COUNTER  $0
OBJ_PICK_CHARACTER_J  $1, OBJ_YUCCA_PILOT_CJSELECTPARTY11-OBJ_YUCCA_PILOT
OBJ_HAS_STATUS  $80, OBJ_YUCCA_PILOT_SJPRESENT12-OBJ_YUCCA_PILOT
OBJ_INCREMENT_COUNTER  $0
    OBJ_YUCCA_PILOT_SJPRESENT12:
OBJ_PICK_CHARACTER_J  $2, OBJ_YUCCA_PILOT_CJSELECTPARTY11-OBJ_YUCCA_PILOT
OBJ_HAS_STATUS  $80, OBJ_YUCCA_PILOT_CJSELECTPARTY11-OBJ_YUCCA_PILOT
OBJ_INCREMENT_COUNTER  $0
    OBJ_YUCCA_PILOT_CJSELECTPARTY11:
OBJ_MULTIPLY_BY_PARTY
OBJ_DIALOGUE UMSG::YUCCA_PILOT_RIDE_ACCEPT
OBJ_TAKE_MONEY OBJ_YUCCA_PILOT_JTAKEMONEY13-OBJ_YUCCA_PILOT
OBJ_RESET_COUNTER  $6
    OBJ_YUCCA_PILOTJ_JUMP16:
OBJ_COUNTERLESSTHAN  $0, $1, OBJ_YUCCA_PILOT_CNJCOMPCOUNTER14-OBJ_YUCCA_PILOT
OBJ_NOT_HAS_ITEM  $0, OBJ_YUCCA_PILOT_IJHASITEM15-OBJ_YUCCA_PILOT
OBJ_PICK_ITEM  $64
OBJ_GIVE_ITEM OBJ_YUCCA_PILOT_IJHASITEM15-OBJ_YUCCA_PILOT
OBJ_INCREMENT_COUNTER  $6
OBJ_DECREMENT_COUNTER $0
OBJ_JUMP  OBJ_YUCCA_PILOTJ_JUMP16-OBJ_YUCCA_PILOT
    OBJ_YUCCA_PILOT_IJHASITEM15:
OBJ_COUNTERLESSTHAN  $6, $1, OBJ_YUCCA_PILOT_CNJCOMPCOUNTER17-OBJ_YUCCA_PILOT
OBJ_NOT_HAS_ITEM  $64, OBJ_YUCCA_PILOT_JTALK4-OBJ_YUCCA_PILOT
OBJ_PICK_ITEM  $64
OBJ_REMOVE_ITEM  OBJ_YUCCA_PILOT_JTALK4-OBJ_YUCCA_PILOT
OBJ_DECREMENT_COUNTER $6
OBJ_JUMP  OBJ_YUCCA_PILOT_IJHASITEM15-OBJ_YUCCA_PILOT
    OBJ_YUCCA_PILOT_CNJCOMPCOUNTER17:
OBJ_DIALOGUE UMSG::YUCCA_PILOT_NOROOM
OBJ_IS_NOT_FLAG  $89, OBJ_YUCCA_PILOT_FJJUMP18-OBJ_YUCCA_PILOT
OBJ_PICK_ITEM  $9C
OBJ_JUMP  OBJ_YUCCA_PILOTJ_JUMP19-OBJ_YUCCA_PILOT
    OBJ_YUCCA_PILOT_FJJUMP18:
OBJ_IS_NOT_FLAG  $8A, OBJ_YUCCA_PILOT_FJJUMP20-OBJ_YUCCA_PILOT
OBJ_PICK_ITEM  $9D
OBJ_JUMP  OBJ_YUCCA_PILOTJ_JUMP19-OBJ_YUCCA_PILOT
    OBJ_YUCCA_PILOT_FJJUMP20:
OBJ_PICK_ITEM  $9E
    OBJ_YUCCA_PILOTJ_JUMP19:
OBJ_MULTIPLY_BY_PARTY
OBJ_GIVE_WEAPON OBJ_YUCCA_PILOT_JTALK4-OBJ_YUCCA_PILOT
OBJ_STOP
    OBJ_YUCCA_PILOT_JTAKEMONEY13:
OBJ_DIALOGUE UMSG::YUCCA_PILOT_NOMONEY
OBJ_STOP
    OBJ_YUCCA_PILOT_JYESNO7:
OBJ_DIALOGUE UMSG::YUCCA_PILOT_RIDE_DECLINE
OBJ_STOP
    OBJ_YUCCA_PILOT_FJJUMP6:
OBJ_DIALOGUE UMSG::YUCCA_PILOT_MINE
OBJ_SET_FLAG  $3A
    OBJ_YUCCA_PILOT_JTALK4:
OBJ_STOP
    OBJ_YUCCA_PILOT_CNJCOMPCOUNTER14:
OBJ_PLAY_SOUND  $6
OBJ_MOVE OBJ_YUCCA_PILOT_MOVE0
OBJ_SIGNAL  $2
OBJ_SET_FLAG  $17
OBJ_STOP
    OBJ_YUCCA_PILOT_MOVE0:
moveDef DIRECTIONS::UP, $6, $1
moveDef DIRECTIONS::DOWN, $2, $1
OBJ_STOP

OBJ_YUCCA_TANK:
objectDef $1e, $1f8, DIRECTIONS::DOWN, $124
.addr SPRITEDEF_2CB ;sprite
OBJ_FLAG_DISAPPEAR  $18
OBJ_IS_NOT_TOUCHING  OBJ_YUCCA_TANK_JTOUCH0-OBJ_YUCCA_TANK
OBJ_IS_NOT_FLAG  $88, OBJ_YUCCA_TANK_JTOUCH0-OBJ_YUCCA_TANK
OBJ_PLAY_MUSIC  $17
OBJ_TANK DIRECTIONS::DOWN
OBJ_SET_FLAG  $18
OBJ_SET_FLAG  $73
    OBJ_YUCCA_TANK_JTOUCH0:
OBJ_STOP

OBJ_YUCCA_PLANE:
objectDef $1e, $1f3, DIRECTIONS::LEFT, $120
.addr SPRITEDEF_2C5 ;sprite
OBJ_FLAG_DISAPPEAR  $19
OBJ_IS_SIGNAL  OBJ_YUCCA_PLANE_JSIGNALED0-OBJ_YUCCA_PLANE
OBJ_IS_NOT_FLAG  $89, OBJ_YUCCA_PLANE_FJJUMP1-OBJ_YUCCA_PLANE
OBJ_AIRPLANE DIRECTIONS::LEFT
OBJ_PLAY_MUSIC  $1E
OBJ_MOVE OBJ_YUCCA_PLANE_MOVE0
OBJ_END_PLANE
OBJ_MOVE OBJ_YUCCA_PLANE_MOVE1
OBJ_EXIT_VEHICLE DIRECTIONS::DOWN
OBJ_PLAY_MUSIC  $8
OBJ_CLEAR_FLAG  $17
OBJ_STOP
    OBJ_YUCCA_PLANE_FJJUMP1:
OBJ_IS_NOT_FLAG  $8A, OBJ_YUCCA_PLANE_FJJUMP2-OBJ_YUCCA_PLANE
OBJ_AIRPLANE DIRECTIONS::LEFT
OBJ_PLAY_MUSIC  $1E
OBJ_MOVE OBJ_YUCCA_PLANE_MOVE2
OBJ_END_PLANE
OBJ_MOVE OBJ_YUCCA_PLANE_MOVE1
OBJ_EXIT_VEHICLE DIRECTIONS::DOWN
OBJ_PLAY_MUSIC  $8
OBJ_CLEAR_FLAG  $17
OBJ_STOP
    OBJ_YUCCA_PLANE_FJJUMP2:
OBJ_IS_NOT_FLAG  $8B, OBJ_YUCCA_PLANE_JSIGNALED0-OBJ_YUCCA_PLANE
OBJ_AIRPLANE DIRECTIONS::LEFT
OBJ_PLAY_MUSIC  $1E
OBJ_MOVE OBJ_YUCCA_PLANE_MOVE3
OBJ_END_PLANE
OBJ_MOVE OBJ_YUCCA_PLANE_MOVE1
OBJ_EXIT_VEHICLE DIRECTIONS::DOWN
OBJ_PLAY_MUSIC  $8
OBJ_CLEAR_FLAG  $17
    OBJ_YUCCA_PLANE_JSIGNALED0:
OBJ_STOP
    OBJ_YUCCA_PLANE_MOVE0:
;jp didnt have the loop
.ifdef VER_JP
moveDef DIRECTIONS::LEFT, $2, $30
moveDef DIRECTIONS::UP_LEFT, $2, $5
moveDef DIRECTIONS::UP, $2, $4C
moveDef DIRECTIONS::UP_RIGHT, $2, $5
moveDef DIRECTIONS::RIGHT, $2, $B4
.else
moveDef DIRECTIONS::LEFT, $2, $33
moveDef DIRECTIONS::UP_LEFT, $2, $5
moveDef DIRECTIONS::UP, $2, $A
moveDef DIRECTIONS::UP, $2, $2
moveDef DIRECTIONS::UP_RIGHT, $2, $2
moveDef DIRECTIONS::RIGHT, $2, $4
moveDef DIRECTIONS::DOWN_RIGHT, $2, $2
moveDef DIRECTIONS::DOWN, $2, $4
moveDef DIRECTIONS::DOWN_LEFT, $2, $2
moveDef DIRECTIONS::LEFT, $2, $4
moveDef DIRECTIONS::UP_LEFT, $2, $2
moveDef DIRECTIONS::UP, $2, $4
moveDef DIRECTIONS::UP_RIGHT, $2, $2
moveDef DIRECTIONS::RIGHT, $2, $4
moveDef DIRECTIONS::DOWN_RIGHT, $2, $2
moveDef DIRECTIONS::DOWN, $2, $4
moveDef DIRECTIONS::DOWN_LEFT, $2, $2
moveDef DIRECTIONS::LEFT, $2, $4
moveDef DIRECTIONS::UP_LEFT, $2, $2
moveDef DIRECTIONS::UP, $2, $1
moveDef DIRECTIONS::UP, $2, $43
moveDef DIRECTIONS::UP_RIGHT, $2, $5
moveDef DIRECTIONS::RIGHT, $2, $B7
.endif
moveDef DIRECTIONS::DOWN_RIGHT, $2, $5
moveDef DIRECTIONS::DOWN, $2, $4C
moveDef DIRECTIONS::DOWN_LEFT, $2, $5
moveDef DIRECTIONS::LEFT, $2, $7A
.byte 3
    OBJ_YUCCA_PLANE_MOVE2:
moveDef DIRECTIONS::LEFT, $2, $D6
moveDef DIRECTIONS::DOWN_LEFT, $2, $2E
moveDef DIRECTIONS::LEFT, $2, $32
moveDef DIRECTIONS::UP_LEFT, $2, $A
moveDef DIRECTIONS::UP, $2, $40
moveDef DIRECTIONS::UP_RIGHT, $2, $D
moveDef DIRECTIONS::RIGHT, $2, $C8
moveDef DIRECTIONS::RIGHT, $2, $7A
moveDef DIRECTIONS::DOWN_RIGHT, $2, $8
moveDef DIRECTIONS::DOWN, $2, $19
moveDef DIRECTIONS::DOWN_LEFT, $2, $8
moveDef DIRECTIONS::LEFT, $2, $5
.byte 3
    OBJ_YUCCA_PLANE_MOVE3:
moveDef DIRECTIONS::LEFT, $2, $F
moveDef DIRECTIONS::UP_LEFT, $2, $5
moveDef DIRECTIONS::UP, $2, $4C
moveDef DIRECTIONS::UP_RIGHT, $2, $5
moveDef DIRECTIONS::RIGHT, $2, $C8
moveDef DIRECTIONS::RIGHT, $2, $46
moveDef DIRECTIONS::DOWN_RIGHT, $2, $A
moveDef DIRECTIONS::DOWN, $2, $C3
moveDef DIRECTIONS::DOWN_LEFT, $2, $5
moveDef DIRECTIONS::LEFT, $2, $54
moveDef DIRECTIONS::UP_LEFT, $2, $7C
moveDef DIRECTIONS::LEFT, $2, $2A
.byte 3
    OBJ_YUCCA_PLANE_MOVE1:
moveDef DIRECTIONS::LEFT, $2, $A
OBJ_STOP

OBJ_YUCCA_SIGN:
objectDef $19, $1e9, DIRECTIONS::UP, $122
.addr SPRITEDEF_65 ;sprite
OBJ_IS_NOT_CHECKING  OBJ_YUCCA_SIGN_JCHECK0-OBJ_YUCCA_SIGN
OBJ_DIALOGUE UMSG::YUCCA_SIGN
    OBJ_YUCCA_SIGN_JCHECK0:
OBJ_STOP

OBJ_YUCCA_TANK2:
objectDef $1f, $1f8, DIRECTIONS::UP, $124
OBJ_FLAG_APPEAR  $73
OBJ_IS_NOT_TOUCHING  OBJ_YUCCA_TANK2_JTOUCH0-OBJ_YUCCA_TANK2
OBJ_CLEAR_FLAG  $18
OBJ_CLEAR_FLAG  $73
OBJ_PLAY_MUSIC  $8
OBJ_EXIT_VEHICLE DIRECTIONS::UP
    OBJ_YUCCA_TANK2_JTOUCH0:
OBJ_STOP

OBJ_YUCCA_R7037_TANK:
objectDef $1c, $275, DIRECTIONS::UP, $119
OBJ_FLAG_APPEAR  $73
OBJ_IS_NOT_TOUCHING  OBJ_YUCCA_R7037_TANK_JTOUCH0-OBJ_YUCCA_R7037_TANK
OBJ_BATTLE  $6F
OBJ_SET_FLAG  $78
OBJ_SET_FLAG  $90
OBJ_CLEAR_FLAG  $73
OBJ_SET_FLAG  $17
OBJ_SET_FLAG  $19
OBJ_SET_FLAG  $1A
OBJ_PLAY_MUSIC  $8
OBJ_EXIT_VEHICLE DIRECTIONS::UP
    OBJ_YUCCA_R7037_TANK_JTOUCH0:
OBJ_STOP

;us only
.ifndef VER_JP
OBJ_MTITOI_GIEGUECAVEEXIT:
objectDef OBJ_TYPE::DOOR, $305, DIRECTIONS::UP, $280
doorArgDef $B, $389, DIRECTIONS::DOWN, $246

OBJ_MTITOI_TUBESENTRANCE:
objectDef OBJ_TYPE::DOOR, $30d, DIRECTIONS::UP, $274
doorArgDef $0, $38D, DIRECTIONS::LEFT, $B6

OBJ_MTITOI_GIEGUECAVETOP:
objectDef $18, $306, DIRECTIONS::UP, $248
.byte SCRIPTS::J_UNK, OBJ_MTITOI_GIEGUECAVETOP_JUNK0-OBJ_MTITOI_GIEGUECAVETOP
OBJ_IS_NOT_TOUCHING  OBJ_MTITOI_GIEGUECAVETOP_JUNK0-OBJ_MTITOI_GIEGUECAVETOP
OBJ_BATTLE  $A2
    OBJ_MTITOI_GIEGUECAVETOP_JUNK0:
OBJ_STOP
.endif