OBJ_BANK_6:
.addr OBJ_SPOOKANE_MANSIONENTRANCE
.addr OBJ_SPOOKANE_RUMORGUY
.addr OBJ_SPOOKANE_ROSEMARYGUY
.addr OBJ_SPOOKANE_SMALLGUY
.addr OBJ_SPOOKANE_CLOWN
.addr OBJ_SPOOKANE_HINTGIRL
.addr OBJ_SPOOKANE_MRROSEMARY
.addr OBJ_SPOOKANE_MRSROSEMARY
.addr OBJ_SPOOKANE_NINTENROSEMARY
.addr OBJ_SPOOKANE_POSTMANGIRL
.addr OBJ_SPOOKANE_HATERGIRL
.addr OBJ_SPOOKANE_STREETSGIRL
.addr OBJ_SPOOKANE_WHATGUY
.addr OBJ_SPOOKANE_POSTMAN
.addr OBJ_SPOOKANE_TELEPORTGAIN1
.addr OBJ_SPOOKANE_TELEPORTGAIN2
.addr 0

OBJ_SPOOKANE_MANSIONENTRANCE:
objectDef $18, $2f8, DIRECTIONS::UP, $325
OBJ_IS_NOT_FACING @JUNK0-OBJ_SPOOKANE_MANSIONENTRANCE
OBJ_IS_NOT_TOUCHING @JTOUCH1-OBJ_SPOOKANE_MANSIONENTRANCE
OBJ_DIALOGUE UMSG::DOOR_LOCKED
OBJ_STOP
    @JTOUCH1:
OBJ_IS_NOT_USING $57, @IJUSE2-OBJ_SPOOKANE_MANSIONENTRANCE
OBJ_DIALOGUE UMSG::DOOR_UNLOCKED
OBJ_TELEPORT $D, $2DD, DIRECTIONS::LEFT, $86
OBJ_STOP
    @IJUSE2:
OBJ_IS_NOT_USING $56, @IJUSE3-OBJ_SPOOKANE_MANSIONENTRANCE
OBJ_JUMP @JUMP4-OBJ_SPOOKANE_MANSIONENTRANCE
    @IJUSE3:
OBJ_IS_NOT_USING $55, @JUNK0-OBJ_SPOOKANE_MANSIONENTRANCE
    @JUMP4:
OBJ_DIALOGUE UMSG::DOOR_KEYFAIL
    @JUNK0:
OBJ_STOP

OBJ_SPOOKANE_RUMORGUY:
objectDef OBJ_TYPE::WANDERING_NPC, $2cb, DIRECTIONS::RIGHT, $358
.addr SPRITEDEF_MAYOR ;sprite
OBJ_IS_NOT_TALKING @JTALK0-OBJ_SPOOKANE_RUMORGUY
OBJ_DIALOGUE UMSG::SPOOKANE_RUMORGUY
OBJ_YESNO_IS_NO @JYESNO1-OBJ_SPOOKANE_RUMORGUY
OBJ_DIALOGUE UMSG::SPOOKANE_RUMORGUY_ACCEPT
OBJ_STOP
    @JYESNO1:
OBJ_DIALOGUE UMSG::SPOOKANE_RUMORGUY_DECLINE
    @JTALK0:
OBJ_STOP

OBJ_SPOOKANE_ROSEMARYGUY:
objectDef OBJ_TYPE::WANDERING_NPC, $2db, DIRECTIONS::DOWN, $367
.addr SPRITEDEF_LONG_GUY ;sprite
OBJ_IS_NOT_TALKING @JTALK0-OBJ_SPOOKANE_ROSEMARYGUY
OBJ_DIALOGUE UMSG::SPOOKANE_ROSEMARYGUY
    @JTALK0:
OBJ_STOP

OBJ_SPOOKANE_SMALLGUY:
objectDef OBJ_TYPE::WANDERING_NPC, $2df, DIRECTIONS::LEFT, $36f
.addr SPRITEDEF_SMALLCAP_KID ;sprite
OBJ_IS_NOT_TALKING @JTALK0-OBJ_SPOOKANE_SMALLGUY
OBJ_DIALOGUE UMSG::SPOOKANE_SMALLGUY
    @JTALK0:
OBJ_STOP

OBJ_SPOOKANE_CLOWN:
objectDef OBJ_TYPE::WANDERING_NPC, $2f6, DIRECTIONS::DOWN, $360
.addr SPRITEDEF_CAP_KID ;sprite
OBJ_IS_NOT_TALKING @JTALK0-OBJ_SPOOKANE_CLOWN
OBJ_DIALOGUE UMSG::SPOOKANE_CLOWN
OBJ_YESNO_IS_NO @JYESNO1-OBJ_SPOOKANE_CLOWN
OBJ_DIALOGUE UMSG::SPOOKANE_CLOWN_ACCEPT
OBJ_STOP
    @JYESNO1:
OBJ_DIALOGUE UMSG::SPOOKANE_CLOWN_DECLINE
    @JTALK0:
OBJ_STOP

OBJ_SPOOKANE_HINTGIRL:
objectDef OBJ_TYPE::WANDERING_NPC_CHECKSPAWN, $2e7, DIRECTIONS::RIGHT, $371
.addr SPRITEDEF_HAIR_GIRL ;sprite
OBJ_FLAG_DISAPPEAR $31
OBJ_IS_NOT_TALKING @JTALK0-OBJ_SPOOKANE_HINTGIRL
OBJ_LOAD_NUMBER 1000
OBJ_DIALOGUE UMSG::SPOOKANE_HINTGIRL
OBJ_YESNO_IS_NO @JYESNO1-OBJ_SPOOKANE_HINTGIRL
OBJ_TAKE_MONEY @JTAKEMONEY2-OBJ_SPOOKANE_HINTGIRL
OBJ_DIALOGUE UMSG::SPOOKANE_HINTGIRL_ACCEPT
OBJ_INCREMENT_COUNTER $3
OBJ_COUNTERLESSTHAN $3, $3, @CNJCOMPCOUNTER3-OBJ_SPOOKANE_HINTGIRL
OBJ_DIALOGUE UMSG::SPOOKANE_HINTGIRL_HINT3
OBJ_SET_FLAG $31
OBJ_STOP
    @CNJCOMPCOUNTER3:
OBJ_COUNTERLESSTHAN $3, $2, @CNJCOMPCOUNTER4-OBJ_SPOOKANE_HINTGIRL
OBJ_DIALOGUE UMSG::SPOOKANE_HINTGIRL_HINT2
OBJ_STOP
    @CNJCOMPCOUNTER4:
OBJ_DIALOGUE UMSG::SPOOKANE_HINTGIRL_HINT1
OBJ_STOP
    @JTAKEMONEY2:
OBJ_DIALOGUE UMSG::SPOOKANE_HINTGIRL_NOMONEY
OBJ_STOP
    @JYESNO1:
OBJ_DIALOGUE UMSG::SPOOKANE_HINTGIRL_DECLINE
OBJ_SET_FLAG $31
    @JTALK0:
OBJ_STOP

OBJ_SPOOKANE_MRROSEMARY:
objectDef OBJ_TYPE::STATIONARY_NPC, $2f8, DIRECTIONS::DOWN, $371
.addr SPRITEDEF_MAYOR ;sprite
OBJ_IS_NOT_TALKING @JTALK0-OBJ_SPOOKANE_MRROSEMARY
OBJ_DIALOGUE UMSG::SPOOKANE_MRSROSEMARY
    @JTALK0:
OBJ_STOP

OBJ_SPOOKANE_MRSROSEMARY:
objectDef OBJ_TYPE::WANDERING_NPC, $2f9, DIRECTIONS::RIGHT, $375
.addr SPRITEDEF_HAIR_GIRL ;sprite
OBJ_IS_NOT_TALKING @JTALK0-OBJ_SPOOKANE_MRSROSEMARY
OBJ_IS_NOT_FLAG $F4, @FJJUMP1-OBJ_SPOOKANE_MRSROSEMARY
OBJ_IS_NOT_FLAG $84, @FJJUMP2-OBJ_SPOOKANE_MRSROSEMARY
OBJ_DIALOGUE UMSG::SPOOKANE_MRSROSEMARY1
OBJ_STOP
    @FJJUMP2:
OBJ_DIALOGUE UMSG::SPOOKANE_MRSROSEMARY2
OBJ_SET_FLAG $84
OBJ_STOP
    @FJJUMP1:
OBJ_IS_NOT_FLAG $38, @FJJUMP3-OBJ_SPOOKANE_MRSROSEMARY
OBJ_DIALOGUE UMSG::SPOOKANE_MRSROSEMARY3
OBJ_STOP
    @FJJUMP3:
OBJ_DIALOGUE UMSG::SPOOKANE_MRSROSEMARY_KEY
OBJ_NOT_HAS_ITEM $0, @IJHASITEM4-OBJ_SPOOKANE_MRSROSEMARY
OBJ_PICK_ITEM $57
OBJ_GIVE_ITEM @JTALK0-OBJ_SPOOKANE_MRSROSEMARY
OBJ_PLAY_SOUND $6
OBJ_SET_FLAG $38
OBJ_STOP
    @IJHASITEM4:
OBJ_DIALOGUE UMSG::PODUNK_PIPPI_NOROOM
    @JTALK0:
OBJ_STOP

OBJ_SPOOKANE_NINTENROSEMARY:
objectDef OBJ_TYPE::WANDERING_NPC_CHECKSPAWN, $2f8, DIRECTIONS::DOWN, $375
.addr SPRITEDEF_CAP_KID ;sprite
OBJ_FLAG_APPEAR $F4
OBJ_IS_NOT_TALKING @JTALK0-OBJ_SPOOKANE_NINTENROSEMARY
OBJ_DIALOGUE UMSG::SPOOKANE_NINTENROSEMARY
    @JTALK0:
OBJ_STOP

OBJ_SPOOKANE_POSTMANGIRL:
objectDef OBJ_TYPE::WANDERING_NPC, $2d4, DIRECTIONS::RIGHT, $377
.addr SPRITEDEF_PONYTAIL_GIRL ;sprite
OBJ_IS_NOT_TALKING @JTALK0-OBJ_SPOOKANE_POSTMANGIRL
OBJ_DIALOGUE UMSG::SPOOKANE_POSTMANGIRL
    @JTALK0:
OBJ_STOP

OBJ_SPOOKANE_HATERGIRL:
objectDef OBJ_TYPE::WANDERING_NPC, $2e3, DIRECTIONS::LEFT, $381
.addr SPRITEDEF_HAIR_GIRL ;sprite
OBJ_IS_NOT_TALKING @JTALK0-OBJ_SPOOKANE_HATERGIRL
OBJ_DIALOGUE UMSG::SPOOKANE_HATERGIRL
    @JTALK0:
OBJ_STOP

OBJ_SPOOKANE_STREETSGIRL:
objectDef OBJ_TYPE::WANDERING_NPC, $2db, DIRECTIONS::DOWN, $37a
.addr SPRITEDEF_PIGTAIL_GIRL_2 ;sprite
OBJ_IS_NOT_TALKING @JTALK0-OBJ_SPOOKANE_STREETSGIRL
OBJ_DIALOGUE UMSG::SPOOKANE_STREETSGIRL
    @JTALK0:
OBJ_STOP

OBJ_SPOOKANE_WHATGUY:
objectDef OBJ_TYPE::WANDERING_NPC, $2d5, DIRECTIONS::RIGHT, $382
.addr SPRITEDEF_LONG_GUY ;sprite
OBJ_IS_NOT_TALKING @JTALK0-OBJ_SPOOKANE_WHATGUY
OBJ_DIALOGUE UMSG::SPOOKANE_WHATGUY
    @JTALK0:
OBJ_STOP

OBJ_SPOOKANE_POSTMAN:
objectDef OBJ_TYPE::WANDERING_NPC, $2d9, DIRECTIONS::LEFT, $358
.addr SPRITEDEF_LONG_GUY ;sprite
OBJ_IS_NOT_TALKING @JTALK0-OBJ_SPOOKANE_POSTMAN
OBJ_DIALOGUE UMSG::SPOOKANE_POSTMAN
    @JTALK0:
OBJ_STOP

OBJ_SPOOKANE_TELEPORTGAIN1:
objectDef OBJ_TYPE::FLAGSET_SEE, $2d3, DIRECTIONS::UP, $359
teleportFlagDef 4, $1D
OBJ_STOP
OBJ_SPOOKANE_TELEPORTGAIN2:
objectDef OBJ_TYPE::FLAGSET_SEE, $2d5, DIRECTIONS::UP, $380
teleportFlagDef 4, $1D
OBJ_STOP