
;debating on whether or not to give every single npc a unique name.
;we'll see

OBJ_BANK_2:
.word OBJ_PODUNK_DEPTENTRANCE
.word OBJ_PODUNK_CITYHALLENTRANCE
.word OBJ_PODUNK_HOTELENTRANCE
.word OBJ_PODUNK_HOSPITALENTRANCE
.word OBJ_PODUNK_BURGERENTRANCE
.word OBJ_PODUNK_CHURCHENTRANCE
.word OBJ_PODUNK_CEMETERYGUY
.word OBJ_PODUNK_SCAREDGUY
.word OBJ_PODUNK_NECROMANCERWOMAN
.word OBJ_PODUNK_WARYGUY
.word OBJ_PODUNK_CANARYGIRL
.word OBJ_PODUNK_MAYORGUY
.word OBJ_PODUNK_CONCERNEDGUY
.word OBJ_PODUNK_SENSIBLEGUY
.word OBJ_PODUNK_EVENTGIRL
.word OBJ_PODUNK_POLTERGUY
.word OBJ_PODUNK_ZOOGUY
.word OBJ_PODUNK_BREADGIRL
.word OBJ_PODUNK_CASHCARDWOMAN
.word OBJ_PODUNK_ZOMBIE
.word OBJ_PODUNK_ZOMBIE2
.word OBJ_PODUNK_CANARYGUY
.word OBJ_PODUNK_SHYGUY
.word OBJ_PODUNK_ASTHMAGIRL
.word OBJ_PODUNK_NOISYMOUSEENTRANCE
.word OBJ_PODUNK_CANARYSIGN
.word OBJ_PODUNK_CITYHALLSIGN
.word OBJ_PODUNK_SIGN
.word OBJ_PODUNK_TELEPORTGAIN1
.word OBJ_PODUNK_TELEPORTGAIN2
.word OBJ_PODUNK_TELEPORTGAIN3
.word OBJ_PODUNK_TELEPORTGAIN4
.word OBJ_PODUNK_TELEPORTGAIN5
.word OBJ_PODUNK_TELEPORTGAIN6
.word 0

OBJ_PODUNK_DEPTENTRANCE:
objectDef OBJ_TYPE::DOOR, $c2, DIRECTIONS::UP, $1b0
doorArgDef $F, $D, DIRECTIONS::LEFT, $116

OBJ_PODUNK_CITYHALLENTRANCE:
objectDef OBJ_TYPE::DOOR, $bb, DIRECTIONS::UP, $1b0
doorArgDef $F, $2BD, DIRECTIONS::LEFT, $96

OBJ_PODUNK_HOTELENTRANCE:
objectDef OBJ_TYPE::DOOR, $c7, DIRECTIONS::UP, $1a4
doorArgDef $12, $25D, DIRECTIONS::LEFT, $3B6

OBJ_PODUNK_HOSPITALENTRANCE:
objectDef OBJ_TYPE::DOOR, $bf, DIRECTIONS::UP, $1bc
doorArgDef $12, $31D, DIRECTIONS::LEFT, $3F6

OBJ_PODUNK_BURGERENTRANCE:
objectDef OBJ_TYPE::DOOR, $b7, DIRECTIONS::UP, $1b0
doorArgDef $F, $D, DIRECTIONS::LEFT, $156

OBJ_PODUNK_CHURCHENTRANCE:
objectDef OBJ_TYPE::DOOR, $9d, DIRECTIONS::UP, $1ef
doorArgDef $12, $D, DIRECTIONS::LEFT, $C6

OBJ_PODUNK_CEMETERYGUY:
objectDef OBJ_TYPE::WANDERING_NPC2, $c8, DIRECTIONS::RIGHT, $193
.word $8228 ;sprite
.byte SCRIPTS::J_TALK, OBJ_PODUNK_CEMETERYGUY_JTALK0-OBJ_PODUNK_CEMETERYGUY
.byte SCRIPTS::FJ_JUMP, $B, OBJ_PODUNK_CEMETERYGUY_FJJUMP1-OBJ_PODUNK_CEMETERYGUY
.byte SCRIPTS::DIALOGUE
.word UMSG::PODUNK_CEMETERYGUY2
.byte 0
    OBJ_PODUNK_CEMETERYGUY_FJJUMP1:
.byte SCRIPTS::DIALOGUE
.word UMSG::PODUNK_CEMETERYGUY1
    OBJ_PODUNK_CEMETERYGUY_JTALK0:
.byte 0

OBJ_PODUNK_SCAREDGUY:
objectDef OBJ_TYPE::STATIONARY_NPC2, $d6, DIRECTIONS::DOWN, $1a9
.word $8228 ;sprite
.byte SCRIPTS::J_TALK, OBJ_PODUNK_SCAREDGUY_JTALK0-OBJ_PODUNK_SCAREDGUY
.byte SCRIPTS::FJ_JUMP, $B, OBJ_PODUNK_SCAREDGUY_FJJUMP1-OBJ_PODUNK_SCAREDGUY
.byte SCRIPTS::DIALOGUE
.word UMSG::PODUNK_SCAREDGUY7
.byte 0
    OBJ_PODUNK_SCAREDGUY_FJJUMP1:
.byte SCRIPTS::DIALOGUE
.word UMSG::PODUNK_SCAREDGUY1
.byte SCRIPTS::J_YESNO, OBJ_PODUNK_SCAREDGUY_JYESNO2-OBJ_PODUNK_SCAREDGUY
.byte SCRIPTS::DIALOGUE
.word UMSG::PODUNK_SCAREDGUY2
.byte SCRIPTS::T_CHANGETYPE, $26
.byte 0
    OBJ_PODUNK_SCAREDGUY_JYESNO2:
.byte SCRIPTS::DIALOGUE
.word UMSG::PODUNK_SCAREDGUY3
.byte SCRIPTS::J_YESNO, OBJ_PODUNK_SCAREDGUY_JYESNO3-OBJ_PODUNK_SCAREDGUY
.byte SCRIPTS::DIALOGUE
.word UMSG::PODUNK_SCAREDGUY4
.byte 0
    OBJ_PODUNK_SCAREDGUY_JYESNO3:
.byte SCRIPTS::DIALOGUE
.word UMSG::PODUNK_SCAREDGUY5
.byte SCRIPTS::DIALOGUE
.word UMSG::PODUNK_SCAREDGUY6
    OBJ_PODUNK_SCAREDGUY_JTALK0:
.byte 0

OBJ_PODUNK_NECROMANCERWOMAN:
objectDef OBJ_TYPE::WANDERING_NPC2, $d0, DIRECTIONS::DOWN, $19a
.word $8288 ;sprite
.byte SCRIPTS::J_TALK, OBJ_PODUNK_NECROMANCERWOMAN_JTALK0-OBJ_PODUNK_NECROMANCERWOMAN
.byte SCRIPTS::FJ_JUMP, $B, OBJ_PODUNK_NECROMANCERWOMAN_FJJUMP1-OBJ_PODUNK_NECROMANCERWOMAN
.byte SCRIPTS::DIALOGUE
.word UMSG::PODUNK_NECROMANCERWOMAN2
.byte 0
    OBJ_PODUNK_NECROMANCERWOMAN_FJJUMP1:
.byte SCRIPTS::DIALOGUE
.word UMSG::PODUNK_NECROMANCERWOMAN1
    OBJ_PODUNK_NECROMANCERWOMAN_JTALK0:
.byte 0

OBJ_PODUNK_WARYGUY:
objectDef OBJ_TYPE::WANDERING_NPC2, $d5, DIRECTIONS::RIGHT, $1a6
.word $81A8 ;sprite
.byte SCRIPTS::J_TALK, OBJ_PODUNK_WARYGUY_JTALK0-OBJ_PODUNK_WARYGUY
.byte SCRIPTS::FJ_JUMP, $B, OBJ_PODUNK_WARYGUY_FJJUMP1-OBJ_PODUNK_WARYGUY
.byte SCRIPTS::DIALOGUE
.word UMSG::PODUNK_CEMETERYGUY2
.byte 0
    OBJ_PODUNK_WARYGUY_FJJUMP1:
.byte SCRIPTS::DIALOGUE
.word UMSG::PODUNK_WARYGUY
    OBJ_PODUNK_WARYGUY_JTALK0:
.byte 0

OBJ_PODUNK_CANARYGIRL:
objectDef OBJ_TYPE::WANDERING_NPC2, $c7, DIRECTIONS::LEFT, $1b3
.word $82A8 ;sprite
.byte SCRIPTS::J_TALK, OBJ_PODUNK_CANARYGIRL_JTALK0-OBJ_PODUNK_CANARYGIRL
.byte SCRIPTS::FJ_JUMP, $C, OBJ_PODUNK_CANARYGIRL_FJJUMP1-OBJ_PODUNK_CANARYGIRL
.byte SCRIPTS::J_JUMP, OBJ_PODUNK_CANARYGIRL_JJUMP2-OBJ_PODUNK_CANARYGIRL
    OBJ_PODUNK_CANARYGIRL_FJJUMP1:
.byte SCRIPTS::IJ_HASITEM, $5F, OBJ_PODUNK_CANARYGIRL_JJUMP2-OBJ_PODUNK_CANARYGIRL
.byte SCRIPTS::DIALOGUE
.word UMSG::PODUNK_CANARYGIRL1
.byte SCRIPTS::J_YESNO, OBJ_PODUNK_CANARYGIRL_JYESNO3-OBJ_PODUNK_CANARYGIRL
.byte SCRIPTS::DIALOGUE
.word UMSG::PODUNK_CANARYGIRL2
.byte 0
    OBJ_PODUNK_CANARYGIRL_JYESNO3:
.byte SCRIPTS::DIALOGUE
.word UMSG::PODUNK_CANARYGIRL3
.byte 0
    OBJ_PODUNK_CANARYGIRL_JJUMP2:
.byte SCRIPTS::DIALOGUE
.word UMSG::PODUNK_CANARYGIRL4
    OBJ_PODUNK_CANARYGIRL_JTALK0:
.byte 0

OBJ_PODUNK_MAYORGUY:
objectDef OBJ_TYPE::WANDERING_NPC2, $b4, DIRECTIONS::RIGHT, $1b6
.word $82C8 ;sprite
.byte SCRIPTS::J_TALK, OBJ_PODUNK_MAYORGUY_JTALK0-OBJ_PODUNK_MAYORGUY
.byte SCRIPTS::DIALOGUE
.word UMSG::PODUNK_MAYORGUY
    OBJ_PODUNK_MAYORGUY_JTALK0:
.byte 0

OBJ_PODUNK_CONCERNEDGUY:
objectDef OBJ_TYPE::WANDERING_NPC2, $b2, DIRECTIONS::DOWN, $1c4
.word $81E8 ;sprite
.byte SCRIPTS::J_TALK, OBJ_PODUNK_CONCERNEDGUY_JTALK0-OBJ_PODUNK_CONCERNEDGUY
.byte SCRIPTS::DIALOGUE
.word UMSG::PODUNK_CONCERNEDGUY
    OBJ_PODUNK_CONCERNEDGUY_JTALK0:
.byte 0

OBJ_PODUNK_SENSIBLEGUY:
objectDef OBJ_TYPE::WANDERING_NPC2, $d1, DIRECTIONS::DOWN, $1ce
.word $81A8 ;sprite
.byte SCRIPTS::J_TALK, OBJ_PODUNK_SENSIBLEGUY_JTALK0-OBJ_PODUNK_SENSIBLEGUY
.byte SCRIPTS::FJ_JUMP, $B, OBJ_PODUNK_SENSIBLEGUY_FJJUMP1-OBJ_PODUNK_SENSIBLEGUY
.byte SCRIPTS::DIALOGUE
.word UMSG::PODUNK_CEMETERYGUY2
.byte 0
    OBJ_PODUNK_SENSIBLEGUY_FJJUMP1:
.byte SCRIPTS::DIALOGUE
.word UMSG::PODUNK_SENSIBLEGUY1
.byte SCRIPTS::J_YESNO, OBJ_PODUNK_SENSIBLEGUY_JYESNO2-OBJ_PODUNK_SENSIBLEGUY
    OBJ_PODUNK_SENSIBLEGUY_JYESNO2:
.byte SCRIPTS::DIALOGUE
.word UMSG::PODUNK_SENSIBLEGUY2
    OBJ_PODUNK_SENSIBLEGUY_JTALK0:
.byte 0

OBJ_PODUNK_EVENTGIRL:
objectDef OBJ_TYPE::WANDERING_NPC2, $be, DIRECTIONS::RIGHT, $1a6
.word $8248 ;sprite
.byte SCRIPTS::J_TALK, OBJ_PODUNK_EVENTGIRL_JTALK0-OBJ_PODUNK_EVENTGIRL
.byte SCRIPTS::FJ_JUMP, $D, OBJ_PODUNK_EVENTGIRL_FJJUMP1-OBJ_PODUNK_EVENTGIRL
.byte SCRIPTS::DIALOGUE
.word UMSG::PODUNK_EVENTGIRL2
.byte 0
    OBJ_PODUNK_EVENTGIRL_FJJUMP1:
.byte SCRIPTS::DIALOGUE
.word UMSG::PODUNK_EVENTGIRL1
    OBJ_PODUNK_EVENTGIRL_JTALK0:
.byte 0

OBJ_PODUNK_POLTERGUY:
objectDef OBJ_TYPE::WANDERING_NPC2, $b6, DIRECTIONS::RIGHT, $18a
.word $81E8 ;sprite
.byte SCRIPTS::J_TALK, OBJ_PODUNK_POLTERGUY_JTALK0-OBJ_PODUNK_POLTERGUY
.byte SCRIPTS::FJ_JUMP, $B, OBJ_PODUNK_POLTERGUY_FJJUMP1-OBJ_PODUNK_POLTERGUY
.byte SCRIPTS::DIALOGUE
.word UMSG::PODUNK_SCAREDGUY7
.byte 0
    OBJ_PODUNK_POLTERGUY_FJJUMP1:
.byte SCRIPTS::DIALOGUE
.word UMSG::PODUNK_POLTERGUY
    OBJ_PODUNK_POLTERGUY_JTALK0:
.byte 0

OBJ_PODUNK_ZOOGUY:
objectDef OBJ_TYPE::WANDERING_NPC2, $d0, DIRECTIONS::RIGHT, $1b7
.word $8268 ;sprite
.byte SCRIPTS::J_TALK, OBJ_PODUNK_ZOOGUY_JTALK0-OBJ_PODUNK_ZOOGUY
.byte SCRIPTS::FJ_JUMP, $D, OBJ_PODUNK_ZOOGUY_FJJUMP1-OBJ_PODUNK_ZOOGUY
.byte SCRIPTS::DIALOGUE
.word UMSG::PODUNK_CEMETERYGUY2
.byte 0
    OBJ_PODUNK_ZOOGUY_FJJUMP1:
.byte SCRIPTS::DIALOGUE
.word UMSG::PODUNK_ZOOGUY
    OBJ_PODUNK_ZOOGUY_JTALK0:
.byte 0

OBJ_PODUNK_BREADGIRL:
objectDef OBJ_TYPE::WANDERING_NPC2, $d0, DIRECTIONS::DOWN, $1b9
.word $8248 ;sprite
.byte SCRIPTS::J_TALK, OBJ_PODUNK_BREADGIRL_JTALK0-OBJ_PODUNK_BREADGIRL
.byte SCRIPTS::DIALOGUE
.word UMSG::PODUNK_BREADGIRL
    OBJ_PODUNK_BREADGIRL_JTALK0:
.byte 0

OBJ_PODUNK_CASHCARDWOMAN:
objectDef OBJ_TYPE::WANDERING_NPC2, $ca, DIRECTIONS::DOWN, $1b0
.word $8288 ;sprite
.byte SCRIPTS::J_TALK, OBJ_PODUNK_CASHCARDWOMAN_JTALK0-OBJ_PODUNK_CASHCARDWOMAN
.byte SCRIPTS::DIALOGUE
.word UMSG::PODUNK_CASHCARDWOMAN
    OBJ_PODUNK_CASHCARDWOMAN_JTALK0:
.byte 0

OBJ_PODUNK_ZOMBIE:
objectDef OBJ_TYPE::WANDERING_NPC, $cb, DIRECTIONS::LEFT, $1d3
.word $8228 ;sprite
.byte SCRIPTS::F_DISAPPEAR, $14
.byte SCRIPTS::J_TALK, OBJ_PODUNK_ZOMBIE_JTALK0-OBJ_PODUNK_ZOMBIE
.byte SCRIPTS::DIALOGUE
.word UMSG::PODUNK_ZOMBIE
.byte SCRIPTS::B_BATTLE, $10
.byte SCRIPTS::F_SETFLAG, $14
    OBJ_PODUNK_ZOMBIE_JTALK0:
.byte 0

OBJ_PODUNK_ZOMBIE2:
objectDef OBJ_TYPE::WANDERING_NPC, $d5, DIRECTIONS::DOWN, $1d5
.word $8228 ;sprite
.byte SCRIPTS::F_DISAPPEAR, $15
.byte SCRIPTS::J_TALK, OBJ_PODUNK_ZOMBIE2_JTALK0-OBJ_PODUNK_ZOMBIE2
.byte SCRIPTS::DIALOGUE
.word UMSG::PODUNK_ZOMBIE2
.byte SCRIPTS::B_BATTLE, $10
.byte SCRIPTS::F_SETFLAG, $15
    OBJ_PODUNK_ZOMBIE2_JTALK0:
.byte 0

OBJ_PODUNK_CANARYGUY:
objectDef OBJ_TYPE::WANDERING_NPC2, $b9, DIRECTIONS::LEFT, $1a8
.word $8268 ;sprite
.byte SCRIPTS::J_TALK, OBJ_PODUNK_CANARYGUY_JTALK0-OBJ_PODUNK_CANARYGUY
.byte SCRIPTS::DIALOGUE
.word UMSG::PODUNK_CANARYGUY
    OBJ_PODUNK_CANARYGUY_JTALK0:
.byte 0

OBJ_PODUNK_SHYGUY:
objectDef OBJ_TYPE::WANDERING_NPC2, $bc, DIRECTIONS::RIGHT, $1b4
.word $8228 ;sprite
.byte SCRIPTS::J_TALK, OBJ_PODUNK_SHYGUY_JTALK0-OBJ_PODUNK_SHYGUY
.byte SCRIPTS::DIALOGUE
.word UMSG::PODUNK_SHYGUY
    OBJ_PODUNK_SHYGUY_JTALK0:
.byte 0

OBJ_PODUNK_ASTHMAGIRL:
objectDef OBJ_TYPE::WANDERING_NPC2, $bb, DIRECTIONS::DOWN, $1be
.word $8208 ;sprite
.byte SCRIPTS::J_TALK, OBJ_PODUNK_ASTHMAGIRL_JTALK0-OBJ_PODUNK_ASTHMAGIRL
.byte SCRIPTS::DIALOGUE
.word UMSG::PODUNK_ASTHMAGIRL
    OBJ_PODUNK_ASTHMAGIRL_JTALK0:
.byte 0

OBJ_PODUNK_NOISYMOUSEENTRANCE:
objectDef OBJ_TYPE::DOOR, $bd, DIRECTIONS::UP, $18f
doorArgDef $12, $3AD, DIRECTIONS::LEFT, $106

OBJ_PODUNK_CANARYSIGN:
objectDef $19, $aa, DIRECTIONS::UP, $17b
.word $8194 ;sprite
.byte SCRIPTS::J_CHECK, OBJ_PODUNK_CANARYSIGN_JCHECK0-OBJ_PODUNK_CANARYSIGN
.byte SCRIPTS::DIALOGUE
.word UMSG::PODUNK_CANARYSIGN
    OBJ_PODUNK_CANARYSIGN_JCHECK0:
.byte 0

OBJ_PODUNK_CITYHALLSIGN:
objectDef $19, $ba, DIRECTIONS::UP, $1b1
.word $8194 ;sprite
.byte SCRIPTS::J_CHECK, OBJ_PODUNK_CITYHALLSIGN_JCHECK0-OBJ_PODUNK_CITYHALLSIGN
.byte SCRIPTS::DIALOGUE
.word UMSG::PODUNK_CITYHALLSIGN
    OBJ_PODUNK_CITYHALLSIGN_JCHECK0:
.byte 0

OBJ_PODUNK_SIGN:
objectDef $19, $c2, DIRECTIONS::UP, $17d
.word $8194 ;sprite
.byte SCRIPTS::J_CHECK, OBJ_PODUNK_SIGN_JCHECK0-OBJ_PODUNK_SIGN
.byte SCRIPTS::DIALOGUE
.word UMSG::PODUNK_SIGN
    OBJ_PODUNK_SIGN_JCHECK0:
.byte 0

OBJ_PODUNK_TELEPORTGAIN1:
objectDef $29, $b7, DIRECTIONS::UP, $1b7
teleportFlagDef 1, $1D
.byte $00
OBJ_PODUNK_TELEPORTGAIN2:
objectDef $29, $c5, DIRECTIONS::UP, $1b7
teleportFlagDef 1, $1D
.byte $00
OBJ_PODUNK_TELEPORTGAIN3:
objectDef $29, $d3, DIRECTIONS::UP, $1b7
teleportFlagDef 1, $1D
.byte $00
OBJ_PODUNK_TELEPORTGAIN4:
objectDef $29, $b7, DIRECTIONS::UP, $1a9
teleportFlagDef 1, $1D
.byte $00
OBJ_PODUNK_TELEPORTGAIN5:
objectDef $29, $c5, DIRECTIONS::UP, $1a9
teleportFlagDef 1, $1D
.byte $00
OBJ_PODUNK_TELEPORTGAIN6:
objectDef $29, $d3, DIRECTIONS::UP, $1a9
teleportFlagDef 1, $1D
.byte $00