OBJ_BANK_16:
.word OBJ_ELLAY_MTITOIENTRANCE
.word OBJ_ELLAY_INTROSIGN
.word 0

OBJ_ELLAY_MTITOIENTRANCE:
objectDef OBJ_TYPE::DOOR, $3e5, DIRECTIONS::UP, $14f
doorArgDef $13, $39A, DIRECTIONS::DOWN, $F9

OBJ_ELLAY_INTROSIGN:
objectDef $19, $360, DIRECTIONS::UP, $13a
.word $8194 ;sprite
.byte SCRIPTS::J_CHECK, OBJ_ELLAY_INTROSIGN_JCHECK0-OBJ_ELLAY_INTROSIGN
.byte SCRIPTS::DIALOGUE
.word UMSG::ELLAY_INTROSIGN
      OBJ_ELLAY_INTROSIGN_JCHECK0:
.byte 0