OBJ_BANK_4:
.addr OBJ_REINDEER_HEALERENTRANCE
.addr OBJ_REINDEER_MOUTHWASHENTRANCE
.addr OBJ_REINDEER_STATIONENTRANCE
.addr OBJ_ELLAY_LIVEHOUSEEXIT
.addr OBJ_ELLAY_LIVEHOUSESIDEIN
.addr OBJ_ELLAY_JAILEXIT
.addr OBJ_REINDEER_NOSEYGUY
.addr OBJ_REINDEER_RUMORMWGUY
.addr OBJ_REINDEER_RUMORMWGIRL
.addr OBJ_REINDEER_SPOOKANEGIRL
.addr OBJ_REINDEER_TUNNELGUY
.addr OBJ_REINDEER_QUIETWOMAN
.addr OBJ_REINDEER_FOODGIRL
.addr OBJ_REINDEER_PEEPINGGUY
.addr OBJ_REINDEER_BICYCLEGUY
.addr OBJ_REINDEER_BEGGIRL
.addr OBJ_ELLAY_LHBACKROOMGUY
.addr OBJ_ELLAY_LHDRINKGIRL
.addr OBJ_ELLAY_LHTEDDYGIRL
.addr OBJ_ELLAY_LHCUTEGUY
.addr OBJ_ELLAY_LHBOUNCERGIRL
.addr OBJ_ELLAY_LHBOUNCERGUY
.addr OBJ_ELLAY_LHTEDDY
.addr OBJ_ELLAY_LHCOP
.addr OBJ_ELLAY_LHCOP_JAILSCENE
.addr OBJ_ELLAY_LHCOP_JAIL
.addr OBJ_ELLAY_JAILCOP
.addr OBJ_REINDEER_MISLAYSIGN
.addr 0

OBJ_REINDEER_HEALERENTRANCE:
objectDef OBJ_TYPE::DOOR, $199, DIRECTIONS::UP, $337
doorArgDef $12, $2D, DIRECTIONS::LEFT, $A6

OBJ_REINDEER_MOUTHWASHENTRANCE:
objectDef OBJ_TYPE::DOOR, $160, DIRECTIONS::UP, $2c9
doorArgDef $12, $26D, DIRECTIONS::LEFT, $86

OBJ_REINDEER_STATIONENTRANCE:
objectDef OBJ_TYPE::DOOR, $201, DIRECTIONS::UP, $33e
doorArgDef $F, $261, DIRECTIONS::DOWN, $3C5

OBJ_ELLAY_LIVEHOUSEEXIT:
objectDef OBJ_TYPE::DOOR, $2bc, DIRECTIONS::RIGHT, $3c8
doorArgDef $6, $323, DIRECTIONS::DOWN, $12D

OBJ_ELLAY_LIVEHOUSESIDEIN:
objectDef OBJ_TYPE::DOOR, $2a9, DIRECTIONS::LEFT, $3ca
doorArgDef $0, $2ED, DIRECTIONS::LEFT, $3C6

OBJ_ELLAY_JAILEXIT:
objectDef OBJ_TYPE::DOOR, $30e, DIRECTIONS::RIGHT, $3c6
doorArgDef $6, $30A, DIRECTIONS::DOWN, $121

OBJ_REINDEER_NOSEYGUY:
objectDef OBJ_TYPE::WANDERING_NPC, $206, DIRECTIONS::DOWN, $344
.addr SPRITEDEF_6A ;sprite
OBJ_IS_NOT_TALKING  OBJ_REINDEER_NOSEYGUY_JTALK0-OBJ_REINDEER_NOSEYGUY
OBJ_NOT_HAS_ITEM  $62, OBJ_REINDEER_NOSEYGUY_IJHASITEM1-OBJ_REINDEER_NOSEYGUY
OBJ_DIALOGUE UMSG::REINDEER_NOSEYGUY_HAT
OBJ_STOP
    OBJ_REINDEER_NOSEYGUY_IJHASITEM1:
OBJ_DIALOGUE UMSG::REINDEER_NOSEYGUY
    OBJ_REINDEER_NOSEYGUY_JTALK0:
OBJ_STOP

OBJ_REINDEER_RUMORMWGUY:
objectDef OBJ_TYPE::WANDERING_NPC, $209, DIRECTIONS::RIGHT, $347
.addr SPRITEDEF_8A ;sprite
OBJ_IS_NOT_TALKING  OBJ_REINDEER_RUMORMWGUY_JTALK0-OBJ_REINDEER_RUMORMWGUY
OBJ_DIALOGUE UMSG::REINDEER_RUMORMWGUY
    OBJ_REINDEER_RUMORMWGUY_JTALK0:
OBJ_STOP

OBJ_REINDEER_RUMORMWGIRL:
objectDef OBJ_TYPE::WANDERING_NPC, $1fd, DIRECTIONS::DOWN, $346
.addr SPRITEDEF_92 ;sprite
OBJ_IS_NOT_TALKING  OBJ_REINDEER_RUMORMWGIRL_JTALK0-OBJ_REINDEER_RUMORMWGIRL
OBJ_DIALOGUE UMSG::REINDEER_RUMORMWGIRL
    OBJ_REINDEER_RUMORMWGIRL_JTALK0:
OBJ_STOP

OBJ_REINDEER_SPOOKANEGIRL:
objectDef OBJ_TYPE::WANDERING_NPC, $1a4, DIRECTIONS::LEFT, $368
.addr SPRITEDEF_AA ;sprite
OBJ_IS_NOT_TALKING  OBJ_REINDEER_SPOOKANEGIRL_JTALK0-OBJ_REINDEER_SPOOKANEGIRL
OBJ_DIALOGUE UMSG::REINDEER_SPOOKANEGIRL
    OBJ_REINDEER_SPOOKANEGIRL_JTALK0:
OBJ_STOP

OBJ_REINDEER_TUNNELGUY:
objectDef OBJ_TYPE::WANDERING_NPC, $1a8, DIRECTIONS::RIGHT, $372
.addr SPRITEDEF_7A ;sprite
OBJ_IS_NOT_TALKING  OBJ_REINDEER_TUNNELGUY_JTALK0-OBJ_REINDEER_TUNNELGUY
OBJ_DIALOGUE UMSG::REINDEER_TUNNELGUY
    OBJ_REINDEER_TUNNELGUY_JTALK0:
OBJ_STOP

OBJ_REINDEER_QUIETWOMAN:
objectDef OBJ_TYPE::WANDERING_NPC, $1b4, DIRECTIONS::LEFT, $375
.addr SPRITEDEF_A2 ;sprite
OBJ_IS_NOT_TALKING  OBJ_REINDEER_QUIETWOMAN_JTALK0-OBJ_REINDEER_QUIETWOMAN
OBJ_DIALOGUE UMSG::REINDEER_QUIETWOMAN
    OBJ_REINDEER_QUIETWOMAN_JTALK0:
OBJ_STOP

OBJ_REINDEER_FOODGIRL:
objectDef OBJ_TYPE::WANDERING_NPC, $1b4, DIRECTIONS::RIGHT, $368
.addr SPRITEDEF_92 ;sprite
OBJ_IS_NOT_TALKING  OBJ_REINDEER_FOODGIRL_JTALK0-OBJ_REINDEER_FOODGIRL
OBJ_DIALOGUE UMSG::REINDEER_FOODGIRL
    OBJ_REINDEER_FOODGIRL_JTALK0:
OBJ_STOP

OBJ_REINDEER_PEEPINGGUY:
objectDef OBJ_TYPE::STATIONARY_NPC, $1b9, DIRECTIONS::UP, $37b
.addr SPRITEDEF_9A ;sprite
OBJ_IS_NOT_TALKING  OBJ_REINDEER_PEEPINGGUY_JTALK0-OBJ_REINDEER_PEEPINGGUY
OBJ_DIALOGUE UMSG::REINDEER_PEEPINGGUY
    OBJ_REINDEER_PEEPINGGUY_JTALK0:
OBJ_STOP

OBJ_REINDEER_BICYCLEGUY:
objectDef OBJ_TYPE::WANDERING_NPC, $1a1, DIRECTIONS::DOWN, $396
.addr SPRITEDEF_8A ;sprite
OBJ_IS_NOT_TALKING  OBJ_REINDEER_BICYCLEGUY_JTALK0-OBJ_REINDEER_BICYCLEGUY
OBJ_DIALOGUE UMSG::REINDEER_BICYCLEGUY
    OBJ_REINDEER_BICYCLEGUY_JTALK0:
OBJ_STOP

OBJ_REINDEER_BEGGIRL:
objectDef OBJ_TYPE::WANDERING_NPC, $1be, DIRECTIONS::DOWN, $396
.addr SPRITEDEF_82 ;sprite
OBJ_IS_NOT_TALKING  OBJ_REINDEER_BEGGIRL_JTALK0-OBJ_REINDEER_BEGGIRL
OBJ_DIALOGUE UMSG::REINDEER_BEGGIRL
    OBJ_REINDEER_BEGGIRL_JTALK0:
OBJ_STOP

OBJ_ELLAY_LHBACKROOMGUY:
objectDef OBJ_TYPE::WANDERING_NPC, $2ad, DIRECTIONS::RIGHT, $3cb
.addr SPRITEDEF_B2 ;sprite
OBJ_IS_NOT_TALKING  OBJ_ELLAY_LHBACKROOMGUY_JTALK0-OBJ_ELLAY_LHBACKROOMGUY
OBJ_IS_NOT_FLAG  $3B, OBJ_ELLAY_LHBACKROOMGUY_FJJUMP1-OBJ_ELLAY_LHBACKROOMGUY
OBJ_DIALOGUE UMSG::ELLAY_LHBACKROOMGUY_MINE
OBJ_STOP
    OBJ_ELLAY_LHBACKROOMGUY_FJJUMP1:
OBJ_DIALOGUE UMSG::ELLAY_LHBACKROOMGUY
    OBJ_ELLAY_LHBACKROOMGUY_JTALK0:
OBJ_STOP

OBJ_ELLAY_LHDRINKGIRL:
objectDef OBJ_TYPE::SPINNING_NPC, $2b5, DIRECTIONS::LEFT, $3cb
.addr SPRITEDEF_AA ;sprite
OBJ_IS_NOT_TALKING  OBJ_ELLAY_LHDRINKGIRL_JTALK0-OBJ_ELLAY_LHDRINKGIRL
OBJ_IS_NOT_FLAG  $34, OBJ_ELLAY_LHDRINKGIRL_FJJUMP1-OBJ_ELLAY_LHDRINKGIRL
OBJ_DIALOGUE UMSG::ELLAY_LHDRINKGIRL
OBJ_STOP
    OBJ_ELLAY_LHDRINKGIRL_FJJUMP1:
OBJ_DIALOGUE UMSG::ELLAY_LHDRINKGIRL_OFFER
OBJ_YESNO_IS_NO  OBJ_ELLAY_LHDRINKGIRL_JYESNO2-OBJ_ELLAY_LHDRINKGIRL
OBJ_SET_FLAG  $34
OBJ_MOVE OBJ_ELLAY_LHDRINKGIRL_MOVE0
OBJ_DIALOGUE UMSG::PODUNK_PIPPI_MEET_NOYES
OBJ_SET_FLAG  $2B
OBJ_SIGNAL  $17
OBJ_STOP
    OBJ_ELLAY_LHDRINKGIRL_JYESNO2:
OBJ_DIALOGUE UMSG::ELLAY_LHDRINKGIRL_OFFER_REFUSE
    OBJ_ELLAY_LHDRINKGIRL_JTALK0:
OBJ_STOP
    OBJ_ELLAY_LHDRINKGIRL_MOVE0:
moveDef DIRECTIONS::UP, $6, $1
moveDef DIRECTIONS::LEFT, $6, $2
moveDef DIRECTIONS::LEFT, MOVE_CMD::MOVEFACE, $1
moveDef DIRECTIONS::RIGHT, MOVE_CMD::ABOUTFACE, $1
OBJ_STOP

OBJ_ELLAY_LHTEDDYGIRL:
objectDef OBJ_TYPE::SPINNING_NPC, $2b0, DIRECTIONS::UP, $3cb
.addr SPRITEDEF_92 ;sprite
OBJ_IS_NOT_TALKING  OBJ_ELLAY_LHTEDDYGIRL_JTALK0-OBJ_ELLAY_LHTEDDYGIRL
OBJ_NOT_HAS_CHARACTER  $4, OBJ_ELLAY_LHTEDDYGIRL_CJPRESENT1-OBJ_ELLAY_LHTEDDYGIRL
OBJ_DIALOGUE UMSG::ELLAY_LHTEDDYGIRL2
OBJ_STOP
    OBJ_ELLAY_LHTEDDYGIRL_CJPRESENT1:
OBJ_DIALOGUE UMSG::ELLAY_LHTEDDYGIRL
    OBJ_ELLAY_LHTEDDYGIRL_JTALK0:
OBJ_STOP

OBJ_ELLAY_LHCUTEGUY:
objectDef OBJ_TYPE::SPINNING_NPC, $2b2, DIRECTIONS::LEFT, $3c9
.addr SPRITEDEF_9A ;sprite
OBJ_IS_NOT_TALKING  OBJ_ELLAY_LHCUTEGUY_JTALK0-OBJ_ELLAY_LHCUTEGUY
OBJ_NOT_HAS_CHARACTER  $2, OBJ_ELLAY_LHCUTEGUY_CJPRESENT1-OBJ_ELLAY_LHCUTEGUY
OBJ_HAS_STATUS  $80, OBJ_ELLAY_LHCUTEGUY_CJPRESENT1-OBJ_ELLAY_LHCUTEGUY
OBJ_DIALOGUE UMSG::ELLAY_LHCUTEGUY2
OBJ_STOP
    OBJ_ELLAY_LHCUTEGUY_CJPRESENT1:
OBJ_DIALOGUE UMSG::ELLAY_LHCUTEGUY
    OBJ_ELLAY_LHCUTEGUY_JTALK0:
OBJ_STOP

OBJ_ELLAY_LHBOUNCERGIRL:
objectDef OBJ_TYPE::STATIONARY_NPC, $2b8, DIRECTIONS::LEFT, $3c8
.addr SPRITEDEF_BA ;sprite
OBJ_IS_NOT_TALKING  OBJ_ELLAY_LHBOUNCERGIRL_JTALK0-OBJ_ELLAY_LHBOUNCERGIRL
.byte SCRIPTS::J_UNK2, OBJ_ELLAY_LHBOUNCERGIRL_JUNK21-OBJ_ELLAY_LHBOUNCERGIRL
.byte SCRIPTS::J_UNK, OBJ_ELLAY_LHBOUNCERGIRL_JUNK2-OBJ_ELLAY_LHBOUNCERGIRL
OBJ_JUMP  OBJ_ELLAY_LHBOUNCERGIRLJ_JUMP3-OBJ_ELLAY_LHBOUNCERGIRL
    OBJ_ELLAY_LHBOUNCERGIRL_JUNK2:
OBJ_DIALOGUE UMSG::ELLAY_LHBOUNCERGIRL
OBJ_MOVE OBJ_ELLAY_LHBOUNCERGIRL_MOVE0
OBJ_STOP
    OBJ_ELLAY_LHBOUNCERGIRLJ_JUMP3:
OBJ_DIALOGUE UMSG::ELLAY_LHBOUNCERGIRL_TICKET
OBJ_STOP
    OBJ_ELLAY_LHBOUNCERGIRL_JTALK0:
OBJ_IS_NOT_USING  $5A, OBJ_ELLAY_LHBOUNCERGIRL_IJUSE4-OBJ_ELLAY_LHBOUNCERGIRL
.byte SCRIPTS::J_UNK2, OBJ_ELLAY_LHBOUNCERGIRL_JUNK21-OBJ_ELLAY_LHBOUNCERGIRL
OBJ_DIALOGUE UMSG::ELLAY_LHBOUNCERGIRL2
OBJ_NOT_HAS_ITEM  $5A, OBJ_ELLAY_LHBOUNCERGIRL_IJUSE4-OBJ_ELLAY_LHBOUNCERGIRL
OBJ_PICK_ITEM  $5A
OBJ_REMOVE_ITEM  OBJ_ELLAY_LHBOUNCERGIRL_IJUSE4-OBJ_ELLAY_LHBOUNCERGIRL
OBJ_MOVE OBJ_ELLAY_LHBOUNCERGIRL_MOVE0
OBJ_STOP
    OBJ_ELLAY_LHBOUNCERGIRL_JUNK21:
OBJ_DIALOGUE UMSG::ELLAY_LHBOUNCERGIRL
    OBJ_ELLAY_LHBOUNCERGIRL_IJUSE4:
OBJ_STOP
    OBJ_ELLAY_LHBOUNCERGIRL_MOVE0:
moveDef DIRECTIONS::UP, MOVE_CMD::ABOUTFACE, $1
moveDef DIRECTIONS::DOWN, MOVE_CMD::MOVE, $1
OBJ_STOP

OBJ_ELLAY_LHBOUNCERGUY:
objectDef OBJ_TYPE::STATIONARY_NPC, $2af, DIRECTIONS::RIGHT, $3c8
.addr SPRITEDEF_6A ;sprite
OBJ_IS_NOT_TALKING  OBJ_ELLAY_LHBOUNCERGUY_JTALK0-OBJ_ELLAY_LHBOUNCERGUY
OBJ_DIALOGUE UMSG::ELLAY_LHBOUNCERGUY_OFFER
OBJ_YESNO_IS_NO  OBJ_ELLAY_LHBOUNCERGUY_JYESNO1-OBJ_ELLAY_LHBOUNCERGUY
OBJ_MOVE OBJ_ELLAY_LHBOUNCERGUY_MOVE0
OBJ_DIALOGUE UMSG::ELLAY_LHBOUNCERGUY_OFFER_YES
OBJ_MOVE OBJ_ELLAY_LHBOUNCERGUY_MOVE1
OBJ_IS_NOT_FLAG  $35, OBJ_ELLAY_LHBOUNCERGUY_FJJUMP2-OBJ_ELLAY_LHBOUNCERGUY
OBJ_PICK_CHARACTER_J  $2, OBJ_ELLAY_LHBOUNCERGUY_CJSELECTPARTY3-OBJ_ELLAY_LHBOUNCERGUY
OBJ_DO_LIVE_SHOW
OBJ_DELAY  $78
OBJ_PLAY_MUSIC  $22
OBJ_STOP
    OBJ_ELLAY_LHBOUNCERGUY_FJJUMP2:
OBJ_PICK_CHARACTER_J  $0, OBJ_ELLAY_LHBOUNCERGUY_CJSELECTPARTY3-OBJ_ELLAY_LHBOUNCERGUY
OBJ_HAS_STATUS  $40, OBJ_ELLAY_LHBOUNCERGUY_SJPRESENT4-OBJ_ELLAY_LHBOUNCERGUY
OBJ_HAS_STATUS  $80, OBJ_ELLAY_LHBOUNCERGUY_CJSELECTPARTY3-OBJ_ELLAY_LHBOUNCERGUY
OBJ_PICK_CHARACTER_J  $1, OBJ_ELLAY_LHBOUNCERGUY_CJSELECTPARTY3-OBJ_ELLAY_LHBOUNCERGUY
OBJ_HAS_STATUS  $80, OBJ_ELLAY_LHBOUNCERGUY_CJSELECTPARTY3-OBJ_ELLAY_LHBOUNCERGUY
OBJ_PICK_CHARACTER_J  $2, OBJ_ELLAY_LHBOUNCERGUY_CJSELECTPARTY3-OBJ_ELLAY_LHBOUNCERGUY
OBJ_HAS_STATUS  $80, OBJ_ELLAY_LHBOUNCERGUY_CJSELECTPARTY3-OBJ_ELLAY_LHBOUNCERGUY
OBJ_PICK_CHARACTER_J  $1, OBJ_ELLAY_LHBOUNCERGUY_CJSELECTPARTY3-OBJ_ELLAY_LHBOUNCERGUY
OBJ_DO_LIVE_SHOW
OBJ_DELAY  $78
OBJ_PLAY_MUSIC  $22
OBJ_SIGNAL  $16
OBJ_STOP
    OBJ_ELLAY_LHBOUNCERGUY_SJPRESENT4:
OBJ_DIALOGUE UMSG::ELLAY_LHBOUNCERGUY_STONE
OBJ_STOP
    OBJ_ELLAY_LHBOUNCERGUY_CJSELECTPARTY3:
OBJ_DIALOGUE UMSG::ELLAY_LHBOUNCERGUY_TRIO
OBJ_STOP
    OBJ_ELLAY_LHBOUNCERGUY_JYESNO1:
OBJ_DIALOGUE UMSG::ELLAY_LHBOUNCERGUY_OFFER_NO
    OBJ_ELLAY_LHBOUNCERGUY_JTALK0:
OBJ_STOP
    OBJ_ELLAY_LHBOUNCERGUY_MOVE0:
moveDef DIRECTIONS::RIGHT, $6, $2
moveDef DIRECTIONS::UP, $6, $1
moveDef DIRECTIONS::RIGHT, $6, $4
moveDef DIRECTIONS::LEFT, MOVE_CMD::ABOUTFACE, $1
.byte 3
    OBJ_ELLAY_LHBOUNCERGUY_MOVE1:
moveDef DIRECTIONS::DOWN, MOVE_CMD::MOVEFACE, $1
moveDef DIRECTIONS::LEFT, MOVE_CMD::MOVEFACE, $6
moveDef DIRECTIONS::RIGHT, MOVE_CMD::ABOUTFACE, $1
OBJ_STOP

OBJ_ELLAY_LHTEDDY:
objectDef OBJ_TYPE::STATIONARY_NPC_CHECKSPAWN, $2bb, DIRECTIONS::LEFT, $3c8
.addr SPRITEDEF_18 ;sprite
OBJ_FLAG_APPEAR  $1
OBJ_IS_SIGNAL  OBJ_ELLAY_LHTEDDY_JSIGNALED0-OBJ_ELLAY_LHTEDDY
OBJ_MOVE OBJ_ELLAY_LHTEDDY_MOVE0
OBJ_DIALOGUE UMSG::ELLAY_LHTEDDY_INTRO
OBJ_YESNO_IS_NO  OBJ_ELLAY_LHTEDDY_JYESNO1-OBJ_ELLAY_LHTEDDY
OBJ_DIALOGUE UMSG::ELLAY_LHTEDDY_INTRO_YES
OBJ_JUMP  OBJ_ELLAY_LHTEDDYJ_JUMP2-OBJ_ELLAY_LHTEDDY
    OBJ_ELLAY_LHTEDDY_JYESNO1:
OBJ_DIALOGUE UMSG::ELLAY_LHTEDDY_INTRO_NO
    OBJ_ELLAY_LHTEDDYJ_JUMP2:
OBJ_DIALOGUE UMSG::ELLAY_LHTEDDY_CHALLENGE
OBJ_PICK_CHARACTER  $1
    OBJ_ELLAY_LHTEDDY_JNOTMAX3:
OBJ_HEAL  $FF
OBJ_NOT_MAX_HEALTH  OBJ_ELLAY_LHTEDDY_JNOTMAX3-OBJ_ELLAY_LHTEDDY
OBJ_BATTLE  $9D
OBJ_MOVE OBJ_ELLAY_LHTEDDY_MOVE1
OBJ_JUMP  OBJ_ELLAY_LHTEDDYJ_JUMP4-OBJ_ELLAY_LHTEDDY
    OBJ_ELLAY_LHTEDDYJ_JUMP9:
OBJ_DIALOGUE UMSG::ELLAY_LHTEDDY_TEAMUP_AGREE
OBJ_MOVE OBJ_ELLAY_LHTEDDY_MOVE2
OBJ_PICK_CHARACTER_J  $2, OBJ_ELLAY_LHTEDDY_CJSELECTPARTY5-OBJ_ELLAY_LHTEDDY
OBJ_NOT_CHARACTER_SELECTED $3, OBJ_ELLAY_LHTEDDY_CJSELECTPARTY5-OBJ_ELLAY_LHTEDDY
OBJ_MOVE OBJ_ELLAY_LHTEDDY_MOVE3
    OBJ_ELLAY_LHTEDDY_CJSELECTPARTY5:
OBJ_MOVE OBJ_ELLAY_LHTEDDY_MOVE4
OBJ_DIALOGUE UMSG::ELLAY_LHTEDDY_REPLACELLOYD
OBJ_PLAY_MUSIC  $21
OBJ_DELAY  $B4
OBJ_PLAY_MUSIC  $22
OBJ_MOVE OBJ_ELLAY_LHTEDDY_MOVE5
OBJ_ADD_CHARACTER $4, OBJ_ELLAY_LHTEDDY_JSIGNALED0-OBJ_ELLAY_LHTEDDY
OBJ_REMOVE_CHARACTER $3, OBJ_ELLAY_LHTEDDY_JSIGNALED0-OBJ_ELLAY_LHTEDDY
OBJ_SET_FLAG  $35
    OBJ_ELLAY_LHTEDDYJ_JUMP7:
OBJ_PICK_CHARACTER  $3
OBJ_PICK_CHARACTER_ITEM  $0, OBJ_ELLAY_LHTEDDY_JSIGNALED0-OBJ_ELLAY_LHTEDDY
OBJ_REMOVE_ITEM  OBJ_ELLAY_LHTEDDY_JSIGNALED0-OBJ_ELLAY_LHTEDDY
OBJ_IS_NOT_SELECTED $3, OBJ_ELLAY_LHTEDDY_IJSELECTEDITEM6-OBJ_ELLAY_LHTEDDY
OBJ_JUMP  OBJ_ELLAY_LHTEDDYJ_JUMP7-OBJ_ELLAY_LHTEDDY
    OBJ_ELLAY_LHTEDDY_IJSELECTEDITEM6:
OBJ_PICK_CHARACTER  $4
OBJ_GIVE_ITEM OBJ_ELLAY_LHTEDDY_JSIGNALED0-OBJ_ELLAY_LHTEDDY
OBJ_JUMP  OBJ_ELLAY_LHTEDDYJ_JUMP7-OBJ_ELLAY_LHTEDDY
    OBJ_ELLAY_LHTEDDYJ_JUMP4:
OBJ_DIALOGUE UMSG::ELLAY_LHTEDDY_POSTFIGHT
OBJ_YESNO_IS_NO  OBJ_ELLAY_LHTEDDY_JYESNO8-OBJ_ELLAY_LHTEDDY
OBJ_JUMP  OBJ_ELLAY_LHTEDDYJ_JUMP9-OBJ_ELLAY_LHTEDDY
    OBJ_ELLAY_LHTEDDY_JYESNO8:
OBJ_DIALOGUE UMSG::ELLAY_LHTEDDY_TEAMUP_DECLINE
OBJ_YESNO_IS_NO  OBJ_ELLAY_LHTEDDY_JYESNO10-OBJ_ELLAY_LHTEDDY
OBJ_JUMP  OBJ_ELLAY_LHTEDDYJ_JUMP9-OBJ_ELLAY_LHTEDDY
    OBJ_ELLAY_LHTEDDY_JYESNO10:
OBJ_DIALOGUE UMSG::ELLAY_LHTEDDY_TEAMUP_DECLINE2
OBJ_YESNO_IS_NO  OBJ_ELLAY_LHTEDDY_JYESNO11-OBJ_ELLAY_LHTEDDY
OBJ_JUMP  OBJ_ELLAY_LHTEDDYJ_JUMP9-OBJ_ELLAY_LHTEDDY
    OBJ_ELLAY_LHTEDDY_JYESNO11:
OBJ_DIALOGUE UMSG::ELLAY_LHTEDDY_TEAMUP_DECLINE3
OBJ_YESNO_IS_NO  OBJ_ELLAY_LHTEDDY_JYESNO12-OBJ_ELLAY_LHTEDDY
OBJ_JUMP  OBJ_ELLAY_LHTEDDYJ_JUMP9-OBJ_ELLAY_LHTEDDY
    OBJ_ELLAY_LHTEDDY_JYESNO12:
OBJ_TELEPORT $6, $B1, DIRECTIONS::DOWN, $13C
OBJ_MOVE OBJ_ELLAY_LHTEDDY_MOVE6
    OBJ_ELLAY_LHTEDDY_JSIGNALED0:
OBJ_STOP
    OBJ_ELLAY_LHTEDDY_MOVE0:
moveDef DIRECTIONS::LEFT, MOVE_CMD::MOVEFACE, $4
moveDef DIRECTIONS::UP, MOVE_CMD::MOVEFACE, $1
moveDef DIRECTIONS::LEFT, MOVE_CMD::MOVEFACE, $2
.byte 3
    OBJ_ELLAY_LHTEDDY_MOVE2:
moveDef DIRECTIONS::UP, MOVE_CMD::MOVEFACE, $1
moveDef DIRECTIONS::LEFT, MOVE_CMD::MOVEFACE, $2
.byte 3
    OBJ_ELLAY_LHTEDDY_MOVE3:
moveDef DIRECTIONS::LEFT, MOVE_CMD::MOVEFACE, $1
.byte 3
    OBJ_ELLAY_LHTEDDY_MOVE4:
moveDef DIRECTIONS::DOWN, MOVE_CMD::ABOUTFACE, $1
.byte 3
    OBJ_ELLAY_LHTEDDY_MOVE5:
moveDef DIRECTIONS::DOWN, MOVE_CMD::MOVEFACE, $1
moveDef DIRECTIONS::RIGHT, MOVE_CMD::ABOUTFACE, $1
OBJ_STOP
    OBJ_ELLAY_LHTEDDY_MOVE6:
OBJ_STOP
    OBJ_ELLAY_LHTEDDY_MOVE1:
moveDef DIRECTIONS::LEFT, MOVE_CMD::ABOUTFACE, $1
.byte 3

OBJ_ELLAY_LHCOP:
objectDef OBJ_TYPE::STATIONARY_NPC_CHECKSPAWN, $2bb, DIRECTIONS::DOWN, $3c8
.addr SPRITEDEF_72 ;sprite
OBJ_FLAG_APPEAR  $2B
OBJ_IS_SIGNAL  OBJ_ELLAY_LHCOP_JSIGNALED0-OBJ_ELLAY_LHCOP
OBJ_MOVE OBJ_ELLAY_LHCOP_MOVE0
OBJ_DIALOGUE UMSG::ELLAY_LHCOP_ARREST
OBJ_MOVE OBJ_ELLAY_LHCOP_MOVE1
    OBJ_ELLAY_LHCOP_JSIGNALED0:
OBJ_STOP
    OBJ_ELLAY_LHCOP_MOVE0:
moveDef DIRECTIONS::LEFT, MOVE_CMD::MOVEFACE, $8
moveDef DIRECTIONS::RIGHT, MOVE_CMD::ABOUTFACE, $1
moveDef DIRECTIONS::DOWN, MOVE_CMD::ABOUTFACE, $1
moveDef DIRECTIONS::LEFT, MOVE_CMD::ABOUTFACE, $1
moveDef DIRECTIONS::LEFT, MOVE_CMD::MOVEFACE, $3
moveDef DIRECTIONS::DOWN, MOVE_CMD::MOVEFACE, $2
moveDef DIRECTIONS::RIGHT, MOVE_CMD::MOVEFACE, $1
moveDef DIRECTIONS::DOWN, MOVE_CMD::MOVEFACE, $1
moveDef DIRECTIONS::RIGHT, MOVE_CMD::MOVEFACE, $2
moveDef DIRECTIONS::UP, MOVE_CMD::MOVEFACE, $1
moveDef DIRECTIONS::LEFT, MOVE_CMD::ABOUTFACE, $1
moveDef DIRECTIONS::RIGHT, MOVE_CMD::ABOUTFACE, $1
.byte 3
    OBJ_ELLAY_LHCOP_MOVE1:
moveDef DIRECTIONS::DOWN, $6, $1
moveDef DIRECTIONS::RIGHT, $6, $2
moveDef DIRECTIONS::UP, $6, $2
moveDef DIRECTIONS::RIGHT, $6, $1
moveDef DIRECTIONS::UP, $6, $1
moveDef DIRECTIONS::RIGHT, $6, $5
moveDef DIRECTIONS::RIGHT, $2, $1
moveDef DIRECTIONS::DOWN, $2, $1
.byte 3

OBJ_ELLAY_LHCOP_JAILSCENE:
objectDef OBJ_TYPE::STATIONARY_NPC_CHECKSPAWN, $30c, DIRECTIONS::RIGHT, $3c6
.addr SPRITEDEF_72 ;sprite
OBJ_FLAG_APPEAR  $2B
OBJ_IS_NOT_TOUCHING  OBJ_ELLAY_LHCOP_JAILSCENE_JTOUCH0-OBJ_ELLAY_LHCOP_JAILSCENE
OBJ_DIALOGUE UMSG::ELLAY_LHCOP_JAILSCENE1
OBJ_MOVE OBJ_ELLAY_LHCOP_JAILSCENE_MOVE0
OBJ_DIALOGUE UMSG::ELLAY_LHCOP_JAILSCENE2
OBJ_JUMP  OBJ_ELLAY_LHCOP_JAILSCENEJ_JUMP1-OBJ_ELLAY_LHCOP_JAILSCENE
    OBJ_ELLAY_LHCOP_JAILSCENE_JYESNO2:
OBJ_DIALOGUE UMSG::ELLAY_LHCOP_JAILSHAME_NO
    OBJ_ELLAY_LHCOP_JAILSCENEJ_JUMP1:
OBJ_SLEEP
OBJ_DIALOGUE UMSG::ELLAY_LHCOP_JAILSHAME
OBJ_YESNO_IS_NO  OBJ_ELLAY_LHCOP_JAILSCENE_JYESNO2-OBJ_ELLAY_LHCOP_JAILSCENE
OBJ_DIALOGUE UMSG::ELLAY_LHCOP_JAILSHAME_YES
OBJ_PICK_CHARACTER_J  $0, OBJ_ELLAY_LHCOP_JAILSCENE_CJSELECTPARTY3-OBJ_ELLAY_LHCOP_JAILSCENE
OBJ_TAKE_WEAPON  OBJ_ELLAY_LHCOP_JAILSCENE_CJSELECTPARTY3-OBJ_ELLAY_LHCOP_JAILSCENE
OBJ_SET_FLAG  $63
OBJ_DIALOGUE UMSG::ELLAY_LHCOP_TAKEWEAPON
OBJ_CLEAR_FLAG  $2B
OBJ_SET_FLAG  $2E
OBJ_STOP
    OBJ_ELLAY_LHCOP_JAILSCENE_CJSELECTPARTY3:
OBJ_DIALOGUE UMSG::ELLAY_LHCOP_SEEWEAPON
OBJ_CLEAR_FLAG  $2B
OBJ_SET_FLAG  $2E
    OBJ_ELLAY_LHCOP_JAILSCENE_JTOUCH0:
OBJ_STOP
    OBJ_ELLAY_LHCOP_JAILSCENE_MOVE0:
moveDef DIRECTIONS::LEFT, $6, $6
moveDef DIRECTIONS::UP, $6, $1
moveDef DIRECTIONS::RIGHT, $6, $1
moveDef DIRECTIONS::LEFT, MOVE_CMD::ABOUTFACE, $1
moveDef DIRECTIONS::RIGHT, MOVE_CMD::MOVEFACE, $2
moveDef DIRECTIONS::UP, MOVE_CMD::MOVEFACE, $1
moveDef DIRECTIONS::LEFT, MOVE_CMD::MOVEFACE, $3
moveDef DIRECTIONS::DOWN, MOVE_CMD::ABOUTFACE, $1
OBJ_STOP

OBJ_ELLAY_LHCOP_JAIL:
objectDef OBJ_TYPE::STATIONARY_NPC_CHECKSPAWN, $306, DIRECTIONS::DOWN, $3c4
.addr SPRITEDEF_72 ;sprite
OBJ_FLAG_APPEAR  $2E
OBJ_IS_NOT_TALKING  OBJ_ELLAY_LHCOP_JAIL_JTALK0-OBJ_ELLAY_LHCOP_JAIL
OBJ_DIALOGUE UMSG::ELLAY_LHCOP_JAIL
    OBJ_ELLAY_LHCOP_JAIL_JTALK0:
OBJ_STOP

OBJ_ELLAY_JAILCOP:
objectDef OBJ_TYPE::WANDERING_NPC, $301, DIRECTIONS::LEFT, $3c7
.addr SPRITEDEF_72 ;sprite
OBJ_IS_NOT_TALKING  OBJ_ELLAY_JAILCOP_JTALK0-OBJ_ELLAY_JAILCOP
OBJ_IS_NOT_FLAG  $63, OBJ_ELLAY_JAILCOP_FJJUMP1-OBJ_ELLAY_JAILCOP
OBJ_SELECT_CONFWEAPON  OBJ_ELLAY_JAILCOP_FJJUMP1-OBJ_ELLAY_JAILCOP
OBJ_DIALOGUE UMSG::ELLAY_JAILCOP_HASWEAPON
OBJ_YESNO_IS_NO  OBJ_ELLAY_JAILCOP_JYESNO2-OBJ_ELLAY_JAILCOP
OBJ_TAKE_MONEY OBJ_ELLAY_JAILCOP_JTAKEMONEY3-OBJ_ELLAY_JAILCOP
OBJ_NOT_HAS_ITEM  $0, OBJ_ELLAY_JAILCOP_IJHASITEM4-OBJ_ELLAY_JAILCOP
OBJ_DIALOGUE UMSG::ELLAY_JAILCOP_HASWEAPON_ACCEPT
OBJ_SELECT_CONFWEAPON  OBJ_ELLAY_JAILCOP_FJJUMP1-OBJ_ELLAY_JAILCOP
OBJ_GIVE_ITEM OBJ_ELLAY_JAILCOP_JTALK0-OBJ_ELLAY_JAILCOP
OBJ_SHOW_MONEY
OBJ_PLAY_SOUND  $6
OBJ_CLEAR_FLAG  $63
OBJ_STOP
    OBJ_ELLAY_JAILCOP_IJHASITEM4:
OBJ_DIALOGUE UMSG::ELLAY_JAILCOP_NOROOM
OBJ_SELECT_CONFWEAPON  OBJ_ELLAY_JAILCOP_FJJUMP1-OBJ_ELLAY_JAILCOP
OBJ_GIVE_WEAPON OBJ_ELLAY_JAILCOP_JTALK0-OBJ_ELLAY_JAILCOP
OBJ_STOP
    OBJ_ELLAY_JAILCOP_JTAKEMONEY3:
OBJ_DIALOGUE UMSG::ELLAY_JAILCOP_NOMONEY
OBJ_STOP
    OBJ_ELLAY_JAILCOP_JYESNO2:
OBJ_DIALOGUE UMSG::ELLAY_JAILCOP_HASWEAPON_DECLINE
OBJ_STOP
    OBJ_ELLAY_JAILCOP_FJJUMP1:
OBJ_DIALOGUE UMSG::ELLAY_JAILCOP
    OBJ_ELLAY_JAILCOP_JTALK0:
OBJ_STOP

OBJ_REINDEER_MISLAYSIGN:
objectDef $19, $158, DIRECTIONS::UP, $2ca
.addr SPRITEDEF_65 ;sprite
OBJ_IS_NOT_CHECKING  OBJ_REINDEER_MISLAYSIGN_JCHECK0-OBJ_REINDEER_MISLAYSIGN
OBJ_DIALOGUE UMSG::REINDEER_MISLAYSIGN
OBJ_IS_NOT_FLAG  $74, OBJ_REINDEER_MISLAYSIGN_FJJUMP1-OBJ_REINDEER_MISLAYSIGN
OBJ_JUMP  OBJ_REINDEER_MISLAYSIGN_JCHECK0-OBJ_REINDEER_MISLAYSIGN
    OBJ_REINDEER_MISLAYSIGN_FJJUMP1:
OBJ_DIALOGUE UMSG::REINDEER_MISLAYSIGN2
OBJ_NOT_HAS_ITEM  $0, OBJ_REINDEER_MISLAYSIGN_IJHASITEM2-OBJ_REINDEER_MISLAYSIGN
OBJ_PICK_ITEM  $63
OBJ_GIVE_ITEM OBJ_REINDEER_MISLAYSIGN_JCHECK0-OBJ_REINDEER_MISLAYSIGN
OBJ_PLAY_SOUND  $6
OBJ_SET_FLAG  $74
OBJ_STOP
    OBJ_REINDEER_MISLAYSIGN_IJHASITEM2:
OBJ_DIALOGUE UMSG::INVENTORY_FULL
    OBJ_REINDEER_MISLAYSIGN_JCHECK0:
OBJ_STOP