OBJ_BANK_D:
.addr OBJ_ZOO_OFFICEENTRANCE
.addr OBJ_ZOO_MONKEYSIGN
.addr OBJ_ZOO_MONKEY
.addr OBJ_ZOO_PANDA1
.addr OBJ_ZOO_PANDA2
.addr OBJ_ZOO_BUNNY1
.addr OBJ_ZOO_BUNNY2
.addr OBJ_ZOO_BUNNY3
.addr OBJ_ZOO_BUNNY4
.addr OBJ_ZOO_PENGUIN1
.addr OBJ_ZOO_PENGUIN2
.addr OBJ_ZOO_PENGUIN3
.addr OBJ_ZOO_PENGUIN4
.addr OBJ_ZOO_FLAMINGO1
.addr OBJ_ZOO_FLAMINGO2
.addr OBJ_ZOO_FLAMINGO3
.addr OBJ_ZOO_FLAMINGO4
.addr OBJ_ZOO_MONKEY2
.addr OBJ_ZOO_MONKEY3
.addr OBJ_ZOO_MONKEY4
.addr OBJ_ZOO_MONKEY5
.addr OBJ_ZOO_GATESIGN
.addr OBJ_ZOO_GATEMONKEY
.addr OBJ_ZOO_GATE
.addr OBJ_ZOO_MUSICSWITCHER1
.addr OBJ_ZOO_MUSICSWITCHER2
.addr OBJ_ZOO_OFFICESIGN
.addr 0

OBJ_ZOO_OFFICEENTRANCE:
objectDef $18, $be, DIRECTIONS::UP, $f3
OBJ_IS_NOT_FACING @JUNK0-OBJ_ZOO_OFFICEENTRANCE
OBJ_IS_NOT_TOUCHING @JUNK0-OBJ_ZOO_OFFICEENTRANCE
OBJ_IS_NOT_FLAG $D, @FJJUMP1-OBJ_ZOO_OFFICEENTRANCE
OBJ_TELEPORT $0, $1ED, DIRECTIONS::LEFT, $86
OBJ_STOP
    @FJJUMP1:
OBJ_TELEPORT $2E, $1ED, DIRECTIONS::LEFT, $86
    @JUNK0:
OBJ_STOP

OBJ_ZOO_MONKEYSIGN:
objectDef $19, $c3, DIRECTIONS::UP, $db
.addr SPRITEDEF_ZOO_INFOPANEL ;sprite
OBJ_IS_NOT_CHECKING @JCHECK0-OBJ_ZOO_MONKEYSIGN
OBJ_DIALOGUE UMSG::ZOO_MONKEYSIGN
OBJ_IS_NOT_FLAG $D, @JCHECK0-OBJ_ZOO_MONKEYSIGN
OBJ_SIGNAL $2
    @JCHECK0:
OBJ_STOP

OBJ_ZOO_MONKEY:
objectDef OBJ_TYPE::WANDERING_NPC_CHECKSPAWN, $c0, DIRECTIONS::DOWN, $d9
.addr SPRITEDEF_MONKEY ;sprite
OBJ_FLAG_APPEAR $D
OBJ_IS_SIGNAL @JSIGNALED0-OBJ_ZOO_MONKEY
OBJ_DIALOGUE UMSG::ZOO_MONKEY
OBJ_MOVE @MOVE0
OBJ_PLAY_MUSIC $26
OBJ_DELAY $F0
OBJ_PLAY_MUSIC $12
OBJ_SET_FLAG $F5
OBJ_DIALOGUE UMSG::REMEMBER_MELODY
.ifdef VER_JP
.byte $65
.endif
    @JSIGNALED0:
OBJ_STOP
    @MOVE0:
moveDef DIRECTIONS::DOWN, MOVE_CMD::ABOUTFACE, $1
OBJ_STOP

OBJ_ZOO_PANDA1:
objectDef $19, $a8, DIRECTIONS::UP, $d8
.addr SPRITEDEF_PANDA ;sprite
OBJ_STOP

OBJ_ZOO_PANDA2:
objectDef $19, $aa, DIRECTIONS::UP, $d9
.addr SPRITEDEF_PANDA ;sprite
OBJ_STOP

OBJ_ZOO_BUNNY1:
objectDef $22, $6f, DIRECTIONS::LEFT, $ed
.addr SPRITEDEF_RABBIT ;sprite
OBJ_STOP

OBJ_ZOO_BUNNY2:
objectDef $22, $73, DIRECTIONS::LEFT, $ef
.addr SPRITEDEF_RABBIT ;sprite
OBJ_STOP

OBJ_ZOO_BUNNY3:
objectDef $22, $6d, DIRECTIONS::RIGHT, $f1
.addr SPRITEDEF_RABBIT ;sprite
OBJ_STOP

OBJ_ZOO_BUNNY4:
objectDef $22, $6f, DIRECTIONS::DOWN, $f0
.addr SPRITEDEF_RABBIT ;sprite
OBJ_STOP

OBJ_ZOO_PENGUIN1:
objectDef OBJ_TYPE::WANDERING_NPC, $88, DIRECTIONS::RIGHT, $f1
.addr SPRITEDEF_PENGUIN ;sprite
OBJ_STOP

OBJ_ZOO_PENGUIN2:
objectDef OBJ_TYPE::WANDERING_NPC, $89, DIRECTIONS::LEFT, $f3
.addr SPRITEDEF_PENGUIN ;sprite
OBJ_STOP

OBJ_ZOO_PENGUIN3:
objectDef OBJ_TYPE::WANDERING_NPC, $82, DIRECTIONS::DOWN, $f5
.addr SPRITEDEF_PENGUIN ;sprite
OBJ_STOP

OBJ_ZOO_PENGUIN4:
objectDef OBJ_TYPE::WANDERING_NPC, $87, DIRECTIONS::RIGHT, $f2
.addr SPRITEDEF_PENGUIN ;sprite
OBJ_STOP

OBJ_ZOO_FLAMINGO1:
objectDef $19, $ba, DIRECTIONS::UP, $e0
.addr SPRITEDEF_FLAMINGOS ;sprite
OBJ_STOP

OBJ_ZOO_FLAMINGO2:
objectDef $19, $b8, DIRECTIONS::UP, $e1
.addr SPRITEDEF_FLAMINGOS ;sprite
OBJ_STOP

OBJ_ZOO_FLAMINGO3:
objectDef $19, $bc, DIRECTIONS::UP, $e1
.addr SPRITEDEF_FLAMINGOS ;sprite
OBJ_STOP

OBJ_ZOO_FLAMINGO4:
objectDef $19, $b7, DIRECTIONS::UP, $e5
.addr SPRITEDEF_FLAMINGOS ;sprite
OBJ_STOP

OBJ_ZOO_MONKEY2:
objectDef OBJ_TYPE::WANDERINGFAST_NPC, $94, DIRECTIONS::DOWN, $e1
.addr SPRITEDEF_MONKEY ;sprite
OBJ_STOP

OBJ_ZOO_MONKEY3:
objectDef OBJ_TYPE::WANDERINGFAST_NPC, $95, DIRECTIONS::RIGHT, $e4
.addr SPRITEDEF_MONKEY ;sprite
OBJ_STOP

OBJ_ZOO_MONKEY4:
objectDef OBJ_TYPE::WANDERING_NPC, $92, DIRECTIONS::RIGHT, $e5
.addr SPRITEDEF_MONKEY ;sprite
OBJ_STOP

OBJ_ZOO_MONKEY5:
objectDef OBJ_TYPE::WANDERINGFAST_NPC, $97, DIRECTIONS::DOWN, $e5
.addr SPRITEDEF_MONKEY ;sprite
OBJ_STOP

OBJ_ZOO_GATESIGN:
objectDef $24, $7d, DIRECTIONS::UP, $102
.addr SPRITEDEF_ZOO_SIGN ;sprite
OBJ_STOP

OBJ_ZOO_GATEMONKEY:
objectDef OBJ_TYPE::STATIONARY_NPC_CHECKSPAWN, $7d, DIRECTIONS::DOWN, $104
.addr SPRITEDEF_MONKEY ;sprite
OBJ_FLAG_DISAPPEAR $21
OBJ_IS_NOT_TOUCHING @JTOUCH0-OBJ_ZOO_GATEMONKEY
OBJ_JUMP @JUMP1-OBJ_ZOO_GATEMONKEY
    @JTOUCH0:
OBJ_IS_NOT_TALKING @JTALK2-OBJ_ZOO_GATEMONKEY
    @JUMP1:
OBJ_DIALOGUE UMSG::ZOO_GATEMONKEY
OBJ_NOT_HAS_ITEM $56, @JTALK2-OBJ_ZOO_GATEMONKEY
OBJ_DIALOGUE UMSG::ZOO_GATEMONKEY_KEY
OBJ_PICK_ITEM $56
OBJ_REMOVE_ITEM @JTALK2-OBJ_ZOO_GATEMONKEY
OBJ_CHANGE_TYPE $26
OBJ_SET_FLAG $21
    @JTALK2:
OBJ_STOP

OBJ_ZOO_GATE:
objectDef $1d, $7d, DIRECTIONS::UP, $103
.addr SPRITEDEF_ZOO_GATE ;sprite
OBJ_FLAG_DISAPPEAR $20
OBJ_IS_NOT_CHECKING @JCHECK0-OBJ_ZOO_GATE
OBJ_JUMP @JUMP1-OBJ_ZOO_GATE
    @JCHECK0:
OBJ_IS_NOT_TOUCHING @JTOUCH2-OBJ_ZOO_GATE
    @JUMP1:
OBJ_DIALOGUE UMSG::ZOO_GATE
OBJ_SET_FLAG $20
    @JTOUCH2:
OBJ_STOP

OBJ_ZOO_MUSICSWITCHER1:
objectDef OBJ_TYPE::TRIGGER_CHECKSPAWN, $7d, DIRECTIONS::UP, $104
OBJ_FLAG_APPEAR $21
OBJ_IS_NOT_TOUCHING @JTOUCH0-OBJ_ZOO_MUSICSWITCHER1
OBJ_PLAY_MUSIC $6
    @JTOUCH0:
OBJ_STOP

OBJ_ZOO_MUSICSWITCHER2:
objectDef OBJ_TYPE::TRIGGER, $7d, DIRECTIONS::UP, $101
OBJ_IS_NOT_TOUCHING @JTOUCH0-OBJ_ZOO_MUSICSWITCHER2
OBJ_IS_NOT_FLAG $D, @FJJUMP1-OBJ_ZOO_MUSICSWITCHER2
OBJ_PLAY_MUSIC $12
OBJ_STOP
    @FJJUMP1:
OBJ_PLAY_MUSIC $11
    @JTOUCH0:
OBJ_STOP

OBJ_ZOO_OFFICESIGN:
objectDef $19, $bd, DIRECTIONS::UP, $f4
.addr SPRITEDEF_SIGN ;sprite
OBJ_IS_NOT_CHECKING @JCHECK0-OBJ_ZOO_OFFICESIGN
OBJ_DIALOGUE UMSG::ZOO_OFFICESIGN
    @JCHECK0:
OBJ_STOP