OBJ_BANK_37:
.addr OBJ_MTITOI_BOAT
.addr OBJ_MTITOI_BOATLEAVETRIGGER
.addr OBJ_MTITOI_WHIRLPOOL
.addr OBJ_MTITOI_R7038XXTRIGGER2
.addr OBJ_MTITOI_R7EVEDEAD2
.addr OBJ_MTITOI_R7EVEDEAD2HALF
.addr 0

OBJ_MTITOI_BOAT:
objectDef 40, 947, DIRECTIONS::LEFT, 781
.addr SPRITEDEF_BOAT
OBJ_FLAG_DISAPPEAR 42
OBJ_IS_NOT_TOUCHING @J_IS_NOT_TOUCHING-OBJ_MTITOI_BOAT
OBJ_DIALOGUE UMSG::MTITOI_BOAT
OBJ_NOT_HAS_CHARACTER 3, @J_NOT_HAS_CHARACTER-OBJ_MTITOI_BOAT
OBJ_HAS_STATUS 128, @J_NOT_HAS_CHARACTER-OBJ_MTITOI_BOAT
OBJ_DIALOGUE UMSG::MTITOI_BOAT_FIX
OBJ_BOAT DIRECTIONS::LEFT
OBJ_SET_FLAG 42
OBJ_SET_FLAG 114
OBJ_STOP
	@J_NOT_HAS_CHARACTER:
OBJ_DIALOGUE UMSG::MTITOI_BOAT_NOFIX
	@J_IS_NOT_TOUCHING:
OBJ_STOP

OBJ_MTITOI_BOATLEAVETRIGGER:
objectDef OBJ_TYPE::TRIGGER_CHECKSPAWN, 947, DIRECTIONS::UP, 781
OBJ_FLAG_APPEAR 114
OBJ_IS_NOT_TOUCHING @J_IS_NOT_TOUCHING-OBJ_MTITOI_BOATLEAVETRIGGER
OBJ_CLEAR_FLAG 42
OBJ_CLEAR_FLAG 114
OBJ_EXIT_VEHICLE DIRECTIONS::DOWN
	@J_IS_NOT_TOUCHING:
OBJ_STOP

OBJ_MTITOI_WHIRLPOOL:
objectDef OBJ_TYPE::TRIGGER, 930, DIRECTIONS::UP, 786
OBJ_IS_NOT_TOUCHING @J_IS_NOT_TOUCHING-OBJ_MTITOI_WHIRLPOOL
OBJ_SET_FLAG 254
OBJ_CLEAR_FLAG 114
OBJ_EXIT_VEHICLE 0
OBJ_TELEPORT 12, 237, DIRECTIONS::DOWN, 764
OBJ_SET_FADE 4
OBJ_UNK
	@J_IS_NOT_TOUCHING:
OBJ_STOP

OBJ_MTITOI_R7038XXTRIGGER2:
objectDef OBJ_TYPE::TRIGGER_CHECKSPAWN, 951, DIRECTIONS::UP, 807
OBJ_FLAG_DISAPPEAR 145
OBJ_IS_NOT_TOUCHING @J_IS_NOT_TOUCHING-OBJ_MTITOI_R7038XXTRIGGER2
OBJ_IS_NOT_FLAG 192, @J_IS_NOT_TOUCHING-OBJ_MTITOI_R7038XXTRIGGER2
OBJ_CLEAR_FLAG 192
OBJ_SET_FLAG 193
OBJ_SET_FLAG 145
OBJ_SET_FLAG 147
OBJ_CLEAR_FLAG 254
OBJ_BATTLE 144
	@J_IS_NOT_TOUCHING:
OBJ_STOP

OBJ_MTITOI_R7EVEDEAD2:
objectDef 43, 946, DIRECTIONS::UP, 806
.addr SPRITEDEF_EVE_DEAD
OBJ_FLAG_APPEAR 147
OBJ_SUBROUTINE OBJ_MTITOI_R7EVEDEAD2, SUBR_EVE_DEAD2-OBJ_MTITOI_R7EVEDEAD2
OBJ_STOP

SUBR_EVE_DEAD2:
OBJ_IS_NOT_CHECKING @J_IS_NOT_CHECKING-OBJ_MTITOI_R7EVEDEAD2
OBJ_JUMP @J_JUMP-OBJ_MTITOI_R7EVEDEAD2
	@J_IS_NOT_CHECKING:
OBJ_IS_NOT_CHECKING @J_IS_NOT_CHECKING1-OBJ_MTITOI_R7EVEDEAD2
	@J_JUMP:
OBJ_DIALOGUE UMSG::MTITOI_EVE_MELODY
OBJ_PLAY_MUSIC 42
OBJ_DELAY 240
OBJ_PLAY_MUSIC 11
OBJ_SET_FLAG 241
OBJ_DIALOGUE UMSG::REMEMBER_MELODY
.ifdef VER_JP
OBJ_CHECK_MELODIES
.endif
	@J_IS_NOT_CHECKING1:
OBJ_RETURN

OBJ_MTITOI_R7EVEDEAD2HALF:
objectDef 28, 947, DIRECTIONS::UP, 806
OBJ_FLAG_APPEAR 147
OBJ_SUBROUTINE OBJ_MTITOI_R7EVEDEAD2, SUBR_EVE_DEAD2-OBJ_MTITOI_R7EVEDEAD2
OBJ_STOP

