OBJ_BANK_31:
.addr OBJ_SWEETFACTORY_RM1EXIT
.addr OBJ_SWEETFACTORY_RM2EXIT
.addr OBJ_SWEETFACTORY_RM3EXIT
.addr OBJ_SWEETFACTORY_RM4EXIT
.addr OBJ_SWEETFACTORY_RM5EXIT
.addr OBJ_SWEETFACTORY_RM6EXIT
.addr OBJ_SWEETFACTORY_RM7EXIT
.addr OBJ_SWEETFACTORY_RM8EXIT
.addr OBJ_SWEETFACTORY_RM9EXIT
.addr OBJ_SWEETFACTORY_RM10EXIT
.addr OBJ_SWEETFACTORY_RM11EXIT
.addr OBJ_SWEETFACTORY_RM12EXIT
.addr OBJ_SWEETFACTORY_RM13EXIT
.addr OBJ_SWEETFACTORY_RM14EXIT
.addr OBJ_SWEETFACTORY_PRESENT2
.addr OBJ_SWEETFACTORY_PRESENT3
.addr OBJ_SWEETFACTORY_PRESENT4
.addr OBJ_SWEETFACTORY_PRESENT5
.addr OBJ_SWEETFACTORY_PRESENT6
.addr OBJ_SWEETFACTORY_PRESENT7
.addr OBJ_SWEETFACTORY_PRESENT8
.addr OBJ_SWEETFACTORY_PRESENT9
.addr OBJ_SWEETFACTORY_PRESENT10
.addr OBJ_SWEETFACTORY_PRESENT11
.addr OBJ_SWEETFACTORY_PRESENT12
.addr OBJ_SWEETFACTORY_PRESENT13
.addr OBJ_SWEETFACTORY_PRESENT14
.addr OBJ_SWEETFACTORY_PRESENT15
.addr 0

OBJ_SWEETFACTORY_RM1EXIT:
objectDef OBJ_TYPE::DOOR, 17, DIRECTIONS::LEFT, 934
doorArgDef 0, 65, DIRECTIONS::LEFT, 426

OBJ_SWEETFACTORY_RM2EXIT:
objectDef OBJ_TYPE::DOOR, 17, DIRECTIONS::LEFT, 966
doorArgDef 0, 33, DIRECTIONS::LEFT, 426

OBJ_SWEETFACTORY_RM3EXIT:
objectDef OBJ_TYPE::DOOR, 62, DIRECTIONS::RIGHT, 998
doorArgDef 0, 25, DIRECTIONS::DOWN, 424

OBJ_SWEETFACTORY_RM4EXIT:
objectDef OBJ_TYPE::DOOR, 30, DIRECTIONS::RIGHT, 902
doorArgDef 0, 45, DIRECTIONS::DOWN, 444

OBJ_SWEETFACTORY_RM5EXIT:
objectDef OBJ_TYPE::DOOR, 30, DIRECTIONS::RIGHT, 998
doorArgDef 0, 85, DIRECTIONS::DOWN, 424

OBJ_SWEETFACTORY_RM6EXIT:
objectDef OBJ_TYPE::DOOR, 17, DIRECTIONS::LEFT, 838
doorArgDef 0, 73, DIRECTIONS::LEFT, 446

OBJ_SWEETFACTORY_RM7EXIT:
objectDef OBJ_TYPE::DOOR, 62, DIRECTIONS::RIGHT, 838
doorArgDef 0, 53, DIRECTIONS::DOWN, 444

OBJ_SWEETFACTORY_RM8EXIT:
objectDef OBJ_TYPE::DOOR, 30, DIRECTIONS::RIGHT, 870
doorArgDef 0, 38, DIRECTIONS::RIGHT, 446

OBJ_SWEETFACTORY_RM9EXIT:
objectDef OBJ_TYPE::DOOR, 126, DIRECTIONS::RIGHT, 710
doorArgDef 0, 22, DIRECTIONS::RIGHT, 414

OBJ_SWEETFACTORY_RM10EXIT:
objectDef OBJ_TYPE::DOOR, 145, DIRECTIONS::LEFT, 710
doorArgDef 0, 117, DIRECTIONS::LEFT, 414

OBJ_SWEETFACTORY_RM11EXIT:
objectDef OBJ_TYPE::DOOR, 190, DIRECTIONS::RIGHT, 710
doorArgDef 0, 29, DIRECTIONS::DOWN, 400

OBJ_SWEETFACTORY_RM12EXIT:
objectDef OBJ_TYPE::DOOR, 62, DIRECTIONS::RIGHT, 710
doorArgDef 0, 10, DIRECTIONS::RIGHT, 430

OBJ_SWEETFACTORY_RM13EXIT:
objectDef OBJ_TYPE::DOOR, 81, DIRECTIONS::LEFT, 710
doorArgDef 0, 105, DIRECTIONS::LEFT, 418

OBJ_SWEETFACTORY_RM14EXIT:
objectDef OBJ_TYPE::DOOR, 30, DIRECTIONS::RIGHT, 710
doorArgDef 0, 57, DIRECTIONS::DOWN, 412

OBJ_SWEETFACTORY_PRESENT2:
objectDef OBJ_TYPE::PRESENT, 150, DIRECTIONS::UP, 709
.addr SPRITEDEF_PRESENT
.byte 78 ; item
.byte 4 ; flag

OBJ_SWEETFACTORY_PRESENT3:
objectDef OBJ_TYPE::PRESENT, 185, DIRECTIONS::UP, 709
.addr SPRITEDEF_PRESENT
.byte 16 ; item
.byte 5 ; flag

OBJ_SWEETFACTORY_PRESENT4:
objectDef OBJ_TYPE::PRESENT, 184, DIRECTIONS::UP, 710
.addr SPRITEDEF_PRESENT
.byte 62 ; item
.byte 6 ; flag

OBJ_SWEETFACTORY_PRESENT5:
objectDef OBJ_TYPE::PRESENT, 118, DIRECTIONS::UP, 710
.addr SPRITEDEF_PRESENT
.byte 82 ; item
.byte 7 ; flag

OBJ_SWEETFACTORY_PRESENT6:
objectDef OBJ_TYPE::PRESENT, 23, DIRECTIONS::UP, 708
.addr SPRITEDEF_PRESENT
.byte 62 ; item
.byte 8 ; flag

OBJ_SWEETFACTORY_PRESENT7:
objectDef OBJ_TYPE::PRESENT, 89, DIRECTIONS::UP, 710
.addr SPRITEDEF_PRESENT
.byte 67 ; item
.byte 9 ; flag

OBJ_SWEETFACTORY_PRESENT8:
objectDef OBJ_TYPE::PRESENT, 49, DIRECTIONS::UP, 711
.addr SPRITEDEF_PRESENT
.byte 40 ; item
.byte 10 ; flag

OBJ_SWEETFACTORY_PRESENT9:
objectDef OBJ_TYPE::PRESENT, 55, DIRECTIONS::UP, 998
.addr SPRITEDEF_PRESENT
.byte 62 ; item
.byte 11 ; flag

OBJ_SWEETFACTORY_PRESENT10:
objectDef OBJ_TYPE::PRESENT, 21, DIRECTIONS::UP, 932
.addr SPRITEDEF_PRESENT
.byte 10 ; item
.byte 12 ; flag

OBJ_SWEETFACTORY_PRESENT11:
objectDef OBJ_TYPE::PRESENT, 27, DIRECTIONS::UP, 996
.addr SPRITEDEF_PRESENT
.byte 62 ; item
.byte 13 ; flag

OBJ_SWEETFACTORY_PRESENT12:
objectDef OBJ_TYPE::PRESENT, 30, DIRECTIONS::UP, 871
.addr SPRITEDEF_PRESENT
.byte 62 ; item
.byte 14 ; flag

OBJ_SWEETFACTORY_PRESENT13:
objectDef OBJ_TYPE::PRESENT, 26, DIRECTIONS::UP, 902
.addr SPRITEDEF_PRESENT
.byte 80 ; item
.byte 15 ; flag

OBJ_SWEETFACTORY_PRESENT14:
objectDef OBJ_TYPE::PRESENT, 22, DIRECTIONS::UP, 901
.addr SPRITEDEF_PRESENT
.byte 65 ; item
.byte 16 ; flag

OBJ_SWEETFACTORY_PRESENT15:
objectDef OBJ_TYPE::PRESENT, 22, DIRECTIONS::UP, 839
.addr SPRITEDEF_PRESENT
.byte 67 ; item
.byte 17 ; flag

