OBJ_BANK_35:
.addr OBJ_MTITOI_HEALERHOUSEENTRANCE_UNUSED
.ifdef VER_JP
.addr OBJTHING_35_1
.endif
.addr OBJ_MTITOI_GIEGUEPRISONEXIT
.addr OBJ_MTITOI_PENDANTENTRANCE
.addr OBJ_MTITOI_PENDANTEXIT
.addr OBJ_MTITOI_R7038XXTRIGGER
.addr OBJ_MTITOI_R7EVEDEAD
.addr OBJ_MTITOI_R7EVEDEADHALF
.addr OBJ_MTITOI_GIEGUEPRISONGUY1
.addr OBJ_MTITOI_GIEGUEPRISONGUY2
.addr OBJ_MTITOI_PATHTOGIEGUE_ENTRANCE
.addr OBJ_MTITOI_PRESENT
.ifndef VER_JP
.addr OBJ_MTITOI_TOMBSTONE
.endif
.addr 0

OBJ_MTITOI_HEALERHOUSEENTRANCE_UNUSED:
objectDef OBJ_TYPE::DOOR, 957, DIRECTIONS::UP, 835
doorArgDef 21, 605, DIRECTIONS::LEFT, 998

.ifdef VER_JP
OBJTHING_35_1:
objectDef OBJ_TYPE::DOOR, 933, DIRECTIONS::UP, 639
doorArgDef 0, 909, DIRECTIONS::LEFT, 182
.endif

OBJ_MTITOI_GIEGUEPRISONEXIT:
objectDef OBJ_TYPE::DOOR, 910, DIRECTIONS::RIGHT, 182
.ifdef VER_JP
doorArgDef 0, 933, DIRECTIONS::DOWN, 640
.else
doorArgDef 0, 781, DIRECTIONS::DOWN, 629
.endif

OBJ_MTITOI_PENDANTENTRANCE:
objectDef OBJ_TYPE::DOOR, 981, DIRECTIONS::UP, 627
doorArgDef 0, 469, DIRECTIONS::DOWN, 526

OBJ_MTITOI_PENDANTEXIT:
objectDef OBJ_TYPE::DOOR, 469, DIRECTIONS::UP, 525
doorArgDef 0, 981, DIRECTIONS::DOWN, 628

OBJ_MTITOI_R7038XXTRIGGER:
objectDef OBJ_TYPE::TRIGGER_CHECKSPAWN, 961, DIRECTIONS::UP, 620
OBJ_FLAG_DISAPPEAR 145
OBJ_IS_NOT_TOUCHING @J_IS_NOT_TOUCHING-OBJ_MTITOI_R7038XXTRIGGER
OBJ_IS_NOT_FLAG 192, @J_IS_NOT_TOUCHING-OBJ_MTITOI_R7038XXTRIGGER
OBJ_CLEAR_FLAG 192
OBJ_SET_FLAG 193
OBJ_SET_FLAG 145
OBJ_SET_FLAG 146
OBJ_CLEAR_FLAG 254
OBJ_BATTLE 144
	@J_IS_NOT_TOUCHING:
OBJ_STOP

OBJ_MTITOI_R7EVEDEAD:
objectDef 43, 963, DIRECTIONS::UP, 619
.addr SPRITEDEF_EVE_DEAD
OBJ_FLAG_APPEAR 146
OBJ_SUBROUTINE OBJ_MTITOI_R7EVEDEAD, SUBR_EVE_DEAD-OBJ_MTITOI_R7EVEDEAD
OBJ_STOP

SUBR_EVE_DEAD:
OBJ_IS_NOT_CHECKING @J_IS_NOT_CHECKING-OBJ_MTITOI_R7EVEDEAD
OBJ_JUMP @J_JUMP-OBJ_MTITOI_R7EVEDEAD
	@J_IS_NOT_CHECKING:
OBJ_IS_NOT_CHECKING @J_IS_NOT_CHECKING1-OBJ_MTITOI_R7EVEDEAD
	@J_JUMP:
OBJ_DIALOGUE UMSG::MTITOI_EVE_MELODY
OBJ_PLAY_MUSIC 42
OBJ_DELAY 240
OBJ_PLAY_MUSIC 11
OBJ_SET_FLAG 241
OBJ_DIALOGUE UMSG::REMEMBER_MELODY
.ifdef VER_JP
OBJ_CHECK_MELODIES
.endif
	@J_IS_NOT_CHECKING1:
OBJ_RETURN

OBJ_MTITOI_R7EVEDEADHALF:
objectDef 28, 964, DIRECTIONS::UP, 619
OBJ_FLAG_APPEAR 146
OBJ_SUBROUTINE OBJ_MTITOI_R7EVEDEAD, SUBR_EVE_DEAD-OBJ_MTITOI_R7EVEDEAD
OBJ_STOP

OBJ_MTITOI_GIEGUEPRISONGUY1:
objectDef 24, 905, DIRECTIONS::UP, 180
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_MTITOI_GIEGUEPRISONGUY1
OBJ_DIALOGUE UMSG::MTITOI_GIEGUEPRISON_GUY1
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_MTITOI_GIEGUEPRISONGUY2:
objectDef 24, 904, DIRECTIONS::UP, 183
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_MTITOI_GIEGUEPRISONGUY2
OBJ_DIALOGUE UMSG::MTITOI_GIEGUEPRISON_GUY2
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_MTITOI_PATHTOGIEGUE_ENTRANCE:
.ifdef VER_JP
objectDef 24, 905, DIRECTIONS::UP, 581
OBJ_IS_NOT_FACING @J_IS_NOT_FACING-OBJ_MTITOI_PATHTOGIEGUE_ENTRANCE
OBJ_IS_NOT_TOUCHING @J_IS_NOT_FACING-OBJ_MTITOI_PATHTOGIEGUE_ENTRANCE
OBJ_BATTLE 162
	@J_IS_NOT_FACING:
OBJ_STOP
.else
objectDef OBJ_TYPE::DOOR, 905, DIRECTIONS::UP, 581
doorArgDef 50, 773, DIRECTIONS::DOWN, 641
.endif

OBJ_MTITOI_PRESENT:
objectDef OBJ_TYPE::PRESENT, 459, DIRECTIONS::UP, 526
.addr SPRITEDEF_PRESENT
.byte 54 ; item
.byte 32 ; flag

.ifndef VER_JP
OBJ_MTITOI_TOMBSTONE:
objectDef 24, 905, DIRECTIONS::UP, 594
OBJ_IS_NOT_CHECKING @J_IS_NOT_CHECKING-OBJ_MTITOI_TOMBSTONE
OBJ_PLAY_MUSIC 27
OBJ_PLAY_SOUND 18
OBJ_TOMBSTONE
OBJ_DIALOGUE UMSG::MTITOI_TOMBSTONE1
OBJ_PLAY_MUSIC 43
OBJ_DELAY 240
OBJ_SET_FLAG 240
OBJ_DIALOGUE UMSG::REMEMBER_MELODY
OBJ_DIALOGUE UMSG::MTITOI_TOMBSTONE2
OBJ_PLAY_MUSIC 11
	@J_IS_NOT_CHECKING:
OBJ_STOP
.endif