OBJ_BANK_38:
.addr OBJ_MAGICANT_GUITARMANENTRANCE
.addr OBJ_MAGICANT_COINSHOPENTRANCE
.addr OBJ_MAGICANT_RINGSHOPENTRANCE
.addr OBJ_MAGICANT_PENDANTSHOPENTRANCE
.addr OBJ_MAGICANT_INNENTRANCE
.addr OBJ_MAGICANT_HOSPITALENTRANCE
.addr OBJ_MAGICANT_MUSICSHOPENTRANCE
.addr OBJ_MAGICANT_HOUSE1ENTRANCE
.addr OBJ_MAGICANT_HOUSE2ENTRANCE
.addr OBJ_MAGICANT_HOUSE3ENTRANCE
.addr OBJ_MAGICANT_HOUSE4ENTRANCE
.addr OBJ_MAGICANT_HOUSE5ENTRANCE
.addr OBJ_MAGICANT_HOUSE6ENTRANCE
.addr OBJ_MAGICANT_OCARINAHOUSENTRANCE
.addr OBJ_MAGICANT_HOUSE7ENTRANCE
.addr OBJ_MAGICANT_HOUSE8ENTRANCE
.addr OBJ_MAGICANT_CLOSETHOUSENTRANCE
.addr OBJ_MAGICANT_PHONEHOUSENTRANCE
.addr OBJ_MAGICANT_HOUSE9ENTRANCE
.addr OBJ_MAGICANT_HOUSE10ENTRANCE
.addr OBJ_MAGICANT_BIGBAGHOUSEENTRANCE
.addr OBJ_MAGICANT_RESTROOMBOY
.addr OBJ_MAGICANT_GUITARGIRL
.addr OBJ_MAGICANT_FORGOTTENMANGIRL
.addr OBJ_MAGICANT_NORMALMONKEY
.addr OBJ_MAGICANT_MARYGIRL
.addr OBJ_MAGICANT_VANISHGIRL
.addr OBJ_MAGICANT_ANACAT
.addr OBJ_MAGICANT_LLOYDCAT
.addr OBJ_MAGICANT_BENEVOLENTBOY
.addr OBJ_MAGICANT_STRANGEGIRL
.addr OBJ_SWAMP_HOUSEENTRANCE
.addr OBJ_SWAMP_LLOYDDAD
.addr 0

OBJ_MAGICANT_GUITARMANENTRANCE:
objectDef OBJ_TYPE::DOOR, 606, DIRECTIONS::UP, 663
doorArgDef 0, 45, DIRECTIONS::LEFT, 534

OBJ_MAGICANT_COINSHOPENTRANCE:
objectDef OBJ_TYPE::DOOR, 662, DIRECTIONS::UP, 659
doorArgDef 0, 77, DIRECTIONS::LEFT, 534

OBJ_MAGICANT_RINGSHOPENTRANCE:
objectDef OBJ_TYPE::DOOR, 666, DIRECTIONS::UP, 659
doorArgDef 0, 109, DIRECTIONS::LEFT, 534

OBJ_MAGICANT_PENDANTSHOPENTRANCE:
objectDef OBJ_TYPE::DOOR, 670, DIRECTIONS::UP, 659
doorArgDef 0, 13, DIRECTIONS::LEFT, 566

OBJ_MAGICANT_INNENTRANCE:
objectDef OBJ_TYPE::DOOR, 654, DIRECTIONS::UP, 659
doorArgDef 0, 45, DIRECTIONS::LEFT, 566

OBJ_MAGICANT_HOSPITALENTRANCE:
objectDef OBJ_TYPE::DOOR, 650, DIRECTIONS::UP, 659
doorArgDef 0, 77, DIRECTIONS::LEFT, 566

OBJ_MAGICANT_MUSICSHOPENTRANCE:
objectDef OBJ_TYPE::DOOR, 646, DIRECTIONS::UP, 659
doorArgDef 0, 109, DIRECTIONS::LEFT, 566

OBJ_MAGICANT_HOUSE1ENTRANCE:
objectDef OBJ_TYPE::DOOR, 638, DIRECTIONS::UP, 667
doorArgDef 0, 13, DIRECTIONS::LEFT, 598

OBJ_MAGICANT_HOUSE2ENTRANCE:
objectDef OBJ_TYPE::DOOR, 642, DIRECTIONS::UP, 667
doorArgDef 0, 45, DIRECTIONS::LEFT, 598

OBJ_MAGICANT_HOUSE3ENTRANCE:
objectDef OBJ_TYPE::DOOR, 646, DIRECTIONS::UP, 667
doorArgDef 0, 77, DIRECTIONS::LEFT, 598

OBJ_MAGICANT_HOUSE4ENTRANCE:
objectDef OBJ_TYPE::DOOR, 654, DIRECTIONS::UP, 667
doorArgDef 0, 109, DIRECTIONS::LEFT, 598

OBJ_MAGICANT_HOUSE5ENTRANCE:
objectDef OBJ_TYPE::DOOR, 658, DIRECTIONS::UP, 667
doorArgDef 0, 13, DIRECTIONS::LEFT, 630

OBJ_MAGICANT_HOUSE6ENTRANCE:
objectDef OBJ_TYPE::DOOR, 662, DIRECTIONS::UP, 667
doorArgDef 0, 45, DIRECTIONS::LEFT, 630

OBJ_MAGICANT_OCARINAHOUSENTRANCE:
objectDef OBJ_TYPE::DOOR, 654, DIRECTIONS::UP, 675
doorArgDef 0, 77, DIRECTIONS::LEFT, 630

OBJ_MAGICANT_HOUSE7ENTRANCE:
objectDef OBJ_TYPE::DOOR, 630, DIRECTIONS::UP, 675
doorArgDef 0, 109, DIRECTIONS::LEFT, 630

OBJ_MAGICANT_HOUSE8ENTRANCE:
objectDef OBJ_TYPE::DOOR, 626, DIRECTIONS::UP, 679
doorArgDef 0, 29, DIRECTIONS::LEFT, 534

OBJ_MAGICANT_CLOSETHOUSENTRANCE:
objectDef OBJ_TYPE::DOOR, 622, DIRECTIONS::UP, 683
doorArgDef 0, 61, DIRECTIONS::LEFT, 534

OBJ_MAGICANT_PHONEHOUSENTRANCE:
objectDef OBJ_TYPE::DOOR, 618, DIRECTIONS::UP, 687
doorArgDef 0, 93, DIRECTIONS::LEFT, 534

OBJ_MAGICANT_HOUSE9ENTRANCE:
objectDef OBJ_TYPE::DOOR, 626, DIRECTIONS::UP, 687
doorArgDef 0, 125, DIRECTIONS::LEFT, 534

OBJ_MAGICANT_HOUSE10ENTRANCE:
objectDef OBJ_TYPE::DOOR, 630, DIRECTIONS::UP, 687
doorArgDef 0, 29, DIRECTIONS::LEFT, 566

OBJ_MAGICANT_BIGBAGHOUSEENTRANCE:
objectDef OBJ_TYPE::DOOR, 614, DIRECTIONS::UP, 691
doorArgDef 0, 61, DIRECTIONS::LEFT, 566

OBJ_MAGICANT_RESTROOMBOY:
objectDef OBJ_TYPE::WANDERING_NPC, 627, DIRECTIONS::DOWN, 675
.addr SPRITEDEF_MAGICANTIAN_BOY
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_MAGICANT_RESTROOMBOY
OBJ_DIALOGUE UMSG::MAGICANT_RESTROOMBOY
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_MAGICANT_GUITARGIRL:
objectDef OBJ_TYPE::WANDERING_NPC, 644, DIRECTIONS::DOWN, 668
.addr SPRITEDEF_MAGICANTIAN_GIRL
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_MAGICANT_GUITARGIRL
OBJ_DIALOGUE UMSG::MAGICANT_GUITARGIRL
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_MAGICANT_FORGOTTENMANGIRL:
objectDef OBJ_TYPE::STATIONARY_NPC, 598, DIRECTIONS::DOWN, 685
.addr SPRITEDEF_MAGICANTIAN_GIRL
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_MAGICANT_FORGOTTENMANGIRL
OBJ_DIALOGUE UMSG::MAGICANT_FORGOTTENMANGIRL
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_MAGICANT_NORMALMONKEY:
objectDef OBJ_TYPE::WANDERING_NPC, 612, DIRECTIONS::DOWN, 678
.addr SPRITEDEF_MONKEY
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_MAGICANT_NORMALMONKEY
OBJ_DIALOGUE UMSG::MAGICANT_NORMALMONKEY
OBJ_YESNO_IS_NO @J_YESNO_IS_NO-OBJ_MAGICANT_NORMALMONKEY
OBJ_DIALOGUE UMSG::MAGICANT_NORMALMONKEY_YES
OBJ_STOP
	@J_YESNO_IS_NO:
OBJ_DIALOGUE UMSG::MAGICANT_NORMALMONKEY_NO
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_MAGICANT_MARYGIRL:
objectDef OBJ_TYPE::WANDERING_NPC, 621, DIRECTIONS::DOWN, 688
.addr SPRITEDEF_MAGICANTIAN_GIRL_PINK
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_MAGICANT_MARYGIRL
OBJ_DIALOGUE UMSG::MAGICANT_MARYGIRL
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_MAGICANT_VANISHGIRL:
objectDef OBJ_TYPE::WANDERING_NPC, 645, DIRECTIONS::DOWN, 690
.addr SPRITEDEF_MAGICANTIAN_GIRL
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_MAGICANT_VANISHGIRL
OBJ_DIALOGUE UMSG::MAGICANT_VANISHGIRL
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_MAGICANT_ANACAT:
objectDef OBJ_TYPE::WANDERING_NPC, 606, DIRECTIONS::DOWN, 672
.addr SPRITEDEF_CAT
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_MAGICANT_ANACAT
OBJ_IS_NOT_FLAG 73, @J_IS_NOT_FLAG-OBJ_MAGICANT_ANACAT
OBJ_DIALOGUE UMSG::MTITOI_TEDDY_SLEEP
OBJ_STOP
	@J_IS_NOT_FLAG:
OBJ_DIALOGUE UMSG::MAGICANT_ANACAT1
OBJ_STOP
	@J_IS_NOT_TALKING:
OBJ_IS_NOT_CASTING 1, @J_IS_NOT_CASTING-OBJ_MAGICANT_ANACAT
OBJ_IS_NOT_FLAG 73, @J_IS_NOT_FLAG1-OBJ_MAGICANT_ANACAT
OBJ_DIALOGUE UMSG::MTITOI_TEDDY_SLEEP
OBJ_STOP
	@J_IS_NOT_FLAG1:
OBJ_DIALOGUE UMSG::MAGICANT_ANACAT2
OBJ_NOT_HAS_CHARACTER 2, @J_NOT_HAS_CHARACTER-OBJ_MAGICANT_ANACAT
OBJ_HAS_STATUS 128, @J_NOT_HAS_CHARACTER-OBJ_MAGICANT_ANACAT
OBJ_DIALOGUE UMSG::MAGICANT_ANACAT3
OBJ_PICK_CHARACTER 2
OBJ_CHARA_NOT_HAS_ITEM 0, @J_CHARA_NOT_HAS_ITEM-OBJ_MAGICANT_ANACAT
OBJ_PICK_ITEM 75
OBJ_GIVE_ITEM @J_IS_NOT_CASTING-OBJ_MAGICANT_ANACAT
OBJ_PLAY_SOUND 6
OBJ_SET_FLAG 73
OBJ_STOP
	@J_CHARA_NOT_HAS_ITEM:
OBJ_DIALOGUE UMSG::ABBOTT_CANTHOLD
OBJ_STOP
	@J_NOT_HAS_CHARACTER:
OBJ_DIALOGUE UMSG::MAGICANT_ANACAT_GIRLS
	@J_IS_NOT_CASTING:
OBJ_STOP

OBJ_MAGICANT_LLOYDCAT:
objectDef OBJ_TYPE::SPINNING_NPC, 647, DIRECTIONS::DOWN, 678
.addr SPRITEDEF_CAT
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_MAGICANT_LLOYDCAT
OBJ_IS_NOT_FLAG 74, @J_IS_NOT_FLAG-OBJ_MAGICANT_LLOYDCAT
OBJ_DIALOGUE UMSG::MAGICANT_LLOYDCAT_AFTER
OBJ_STOP
	@J_IS_NOT_FLAG:
OBJ_DIALOGUE UMSG::MAGICANT_LLOYDCAT
OBJ_YESNO_IS_NO @J_YESNO_IS_NO-OBJ_MAGICANT_LLOYDCAT
OBJ_DIALOGUE UMSG::PODUNK_CANARYGIRL2
OBJ_STOP
	@J_YESNO_IS_NO:
OBJ_NOT_HAS_CHARACTER 3, @J_NOT_HAS_CHARACTER-OBJ_MAGICANT_LLOYDCAT
OBJ_HAS_STATUS 128, @J_NOT_HAS_CHARACTER-OBJ_MAGICANT_LLOYDCAT
OBJ_DIALOGUE UMSG::MAGICANT_LLOYDCAT_NO
OBJ_PICK_CHARACTER 3
OBJ_CHARA_NOT_HAS_ITEM 0, @J_CHARA_NOT_HAS_ITEM-OBJ_MAGICANT_LLOYDCAT
OBJ_PICK_ITEM 76
OBJ_GIVE_ITEM @J_IS_NOT_TALKING-OBJ_MAGICANT_LLOYDCAT
OBJ_PLAY_SOUND 6
OBJ_SET_FLAG 74
OBJ_STOP
	@J_CHARA_NOT_HAS_ITEM:
OBJ_DIALOGUE UMSG::ABBOTT_CANTHOLD
OBJ_STOP
	@J_NOT_HAS_CHARACTER:
OBJ_DIALOGUE UMSG::MAGICANT_LLOYDCAT_NOLLOYD
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_MAGICANT_BENEVOLENTBOY:
objectDef OBJ_TYPE::WANDERING_NPC, 612, DIRECTIONS::DOWN, 692
.addr SPRITEDEF_MAGICANTIAN_BOY
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_MAGICANT_BENEVOLENTBOY
OBJ_DIALOGUE UMSG::MAGICANT_BENEVOLENTBOY
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_MAGICANT_STRANGEGIRL:
objectDef OBJ_TYPE::STATIONARY_NPC, 633, DIRECTIONS::DOWN, 683
.addr SPRITEDEF_MAGICANTIAN_GIRL
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_MAGICANT_STRANGEGIRL
OBJ_DIALOGUE UMSG::MAGICANT_STRANGEGIRL
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_SWAMP_HOUSEENTRANCE:
objectDef OBJ_TYPE::DOOR, 869, DIRECTIONS::UP, 407
doorArgDef 18, 909, DIRECTIONS::LEFT, 230

OBJ_SWAMP_LLOYDDAD:
objectDef 33, 867, DIRECTIONS::UP, 408
.addr SPRITEDEF_TRASH_CAN
OBJ_FLAG_DISAPPEAR 1
OBJ_IS_NOT_CHECKING @J_IS_NOT_CHECKING-OBJ_SWAMP_LLOYDDAD
OBJ_DIALOGUE UMSG::CANARY_PILLAR
OBJ_STOP
	@J_IS_NOT_CHECKING:
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_SWAMP_LLOYDDAD
OBJ_DIALOGUE UMSG::SWAMP_LLOYDDAD
OBJ_YESNO_IS_NO @J_YESNO_IS_NO-OBJ_SWAMP_LLOYDDAD
OBJ_IS_NOT_FLAG 128, @J_IS_NOT_FLAG-OBJ_SWAMP_LLOYDDAD
OBJ_DIALOGUE UMSG::SWAMP_LLOYDDAD_YES
OBJ_STOP
	@J_IS_NOT_FLAG:
OBJ_DIALOGUE UMSG::CANARY_GENERIC
	@J_YESNO_IS_NO:
OBJ_DIALOGUE UMSG::SNOWMAN_REGNAME
OBJ_REGISTER_NAME
OBJ_DIALOGUE UMSG::SNOWMAN_PHONE_CHECK
OBJ_YESNO_IS_NO @J_YESNO_IS_NO-OBJ_SWAMP_LLOYDDAD
OBJ_DIALOGUE UMSG::SWAMP_LLOYDDAD_YES
OBJ_SET_FLAG 128
	@J_IS_NOT_TALKING:
OBJ_STOP

UNK_MOVE_DATA:
moveDef DIRECTIONS::UP, MOVE_CMD::MOVEFACE, 7
OBJ_RETURN
UNK_MOVE_DATA2:
OBJ_STOP