OBJ_BANK_3E:
.addr OBJ_MAGICANT_DUNGEONEXIT
.addr OBJ_MAGICANT_DUNGEONLADDER1
.addr OBJ_MAGICANT_DUNGEONHOLE1
.addr OBJ_MAGICANT_DUNGEONLADDER2
.addr OBJ_MAGICANT_DUNGEONHOLE2
.addr OBJ_MAGICANT_DUNGEONLADDER3
.addr OBJ_MAGICANT_DUNGEONHOLE3
.addr OBJ_MAGICANT_DUNGEONLADDER4
.addr OBJ_MAGICANT_DUNGEONHOLE4
.addr OBJ_MAGICANT_DUNGEONLADDER5
.addr OBJ_MAGICANT_DUNGEONHOLE5
.addr OBJ_MAGICANT_DUNGEONLADDER6
.addr OBJ_MAGICANT_DUNGEONHOLE6
.addr OBJ_MAGICANT_DUNGEONLADDER7
.addr OBJ_MAGICANT_DUNGEONHOLE7
.addr OBJ_MAGICANT_DUNGEONLADDER8
.addr OBJ_MAGICANT_DUNGEONHOLE8
.addr OBJ_MAGICANT_DUNGEONLADDER9
.addr OBJ_MAGICANT_DUNGEONHOLE9
.addr OBJ_MAGICANT_DUNGEONLADDER10
.addr OBJ_MAGICANT_DUNGEONHOLE10
.addr OBJ_MAGICANT_DUNGEONLADDER11
.addr OBJ_MAGICANT_DUNGEONHOLE11
.addr OBJ_MAGICANT_DUNGEONLADDER12
.addr OBJ_MAGICANT_DUNGEONHOLE12
.addr OBJ_MAGICANT_DUNGEONLADDER13
.addr OBJ_MAGICANT_THEFISH
.addr OBJ_MAGICANT_THEFISHLADDER
.addr OBJ_MAGICANT_FORGOTTEN_MAN
.addr OBJ_MAGICANT_DRAGON_LEFT
.addr OBJ_MAGICANT_DRAGON_RIGHT
.addr OBJ_MAGICANT_DUNGEONPRESENT1
.addr OBJ_MAGICANT_DUNGEONPRESENT2
.addr OBJ_MAGICANT_DUNGEONPRESENT3
.addr OBJ_MAGICANT_DUNGEONPRESENT4
.addr OBJ_MAGICANT_DUNGEONPRESENT5
.addr 0

OBJ_MAGICANT_DUNGEONEXIT:
.ifdef VER_JP
objectDef OBJ_TYPE::TRIGGER, 565, DIRECTIONS::UP, 423
.else
objectDef OBJ_TYPE::TRIGGER, 533, DIRECTIONS::UP, 423
.endif
OBJ_IS_NOT_FACING @J_IS_NOT_FACING-OBJ_MAGICANT_DUNGEONEXIT
OBJ_IS_NOT_TOUCHING @J_IS_NOT_FACING-OBJ_MAGICANT_DUNGEONEXIT
OBJ_CLEAR_FLAG 0
OBJ_IS_NOT_FLAG 105, @J_IS_NOT_FLAG-OBJ_MAGICANT_DUNGEONEXIT
OBJ_JUMP @J_JUMP-OBJ_MAGICANT_DUNGEONEXIT
	@J_IS_NOT_FLAG:
OBJ_IS_NOT_FLAG 100, @J_JUMP-OBJ_MAGICANT_DUNGEONEXIT
OBJ_REMOVE_CHARACTER 7, @J_REMOVE_CHARACTER-OBJ_MAGICANT_DUNGEONEXIT
OBJ_CLEAR_FLAG 100
OBJ_JUMP @J_JUMP-OBJ_MAGICANT_DUNGEONEXIT
	@J_REMOVE_CHARACTER:
OBJ_SET_FLAG 0
OBJ_SET_FLAG 105
	@J_JUMP:
OBJ_IS_NOT_FLAG 106, @J_IS_NOT_FLAG1-OBJ_MAGICANT_DUNGEONEXIT
OBJ_JUMP @J_JUMP1-OBJ_MAGICANT_DUNGEONEXIT
	@J_IS_NOT_FLAG1:
OBJ_IS_NOT_FLAG 101, @J_JUMP1-OBJ_MAGICANT_DUNGEONEXIT
OBJ_REMOVE_CHARACTER 7, @J_REMOVE_CHARACTER1-OBJ_MAGICANT_DUNGEONEXIT
OBJ_CLEAR_FLAG 101
OBJ_JUMP @J_JUMP1-OBJ_MAGICANT_DUNGEONEXIT
	@J_REMOVE_CHARACTER1:
OBJ_SET_FLAG 0
OBJ_SET_FLAG 106
	@J_JUMP1:
OBJ_IS_NOT_FLAG 107, @J_IS_NOT_FLAG2-OBJ_MAGICANT_DUNGEONEXIT
OBJ_JUMP @J_JUMP2-OBJ_MAGICANT_DUNGEONEXIT
	@J_IS_NOT_FLAG2:
OBJ_IS_NOT_FLAG 102, @J_JUMP2-OBJ_MAGICANT_DUNGEONEXIT
OBJ_REMOVE_CHARACTER 7, @J_REMOVE_CHARACTER2-OBJ_MAGICANT_DUNGEONEXIT
OBJ_CLEAR_FLAG 102
OBJ_JUMP @J_JUMP2-OBJ_MAGICANT_DUNGEONEXIT
	@J_REMOVE_CHARACTER2:
OBJ_SET_FLAG 0
OBJ_SET_FLAG 107
	@J_JUMP2:
OBJ_IS_NOT_FLAG 108, @J_IS_NOT_FLAG3-OBJ_MAGICANT_DUNGEONEXIT
OBJ_JUMP @J_JUMP3-OBJ_MAGICANT_DUNGEONEXIT
	@J_IS_NOT_FLAG3:
OBJ_IS_NOT_FLAG 103, @J_JUMP3-OBJ_MAGICANT_DUNGEONEXIT
OBJ_REMOVE_CHARACTER 7, @J_REMOVE_CHARACTER3-OBJ_MAGICANT_DUNGEONEXIT
OBJ_CLEAR_FLAG 103
OBJ_JUMP @J_JUMP3-OBJ_MAGICANT_DUNGEONEXIT
	@J_REMOVE_CHARACTER3:
OBJ_SET_FLAG 0
OBJ_SET_FLAG 108
	@J_JUMP3:
OBJ_IS_NOT_FLAG 109, @J_IS_NOT_FLAG4-OBJ_MAGICANT_DUNGEONEXIT
OBJ_JUMP @J_JUMP4-OBJ_MAGICANT_DUNGEONEXIT
	@J_IS_NOT_FLAG4:
OBJ_IS_NOT_FLAG 104, @J_JUMP4-OBJ_MAGICANT_DUNGEONEXIT
OBJ_REMOVE_CHARACTER 7, @J_REMOVE_CHARACTER4-OBJ_MAGICANT_DUNGEONEXIT
OBJ_CLEAR_FLAG 104
OBJ_JUMP @J_JUMP4-OBJ_MAGICANT_DUNGEONEXIT
	@J_REMOVE_CHARACTER4:
OBJ_SET_FLAG 0
OBJ_SET_FLAG 109
	@J_JUMP4:
OBJ_IS_NOT_FLAG 0, @J_IS_NOT_FLAG5-OBJ_MAGICANT_DUNGEONEXIT
OBJ_CLEAR_FLAG 0
OBJ_SET_FLAG 110
	@J_IS_NOT_FLAG5:
OBJ_SET_FLAG 119
OBJ_IS_NOT_FLAG 135, @J_IS_NOT_FLAG6-OBJ_MAGICANT_DUNGEONEXIT
OBJ_TELEPORT 49, 1006, DIRECTIONS::DOWN, 515
OBJ_UNK
OBJ_STOP
	@J_IS_NOT_FLAG6:
OBJ_TELEPORT 49, 1014, DIRECTIONS::DOWN, 467
OBJ_UNK
	@J_IS_NOT_FACING:
OBJ_STOP

OBJ_MAGICANT_DUNGEONLADDER1:
objectDef OBJ_TYPE::DOOR, 457, DIRECTIONS::UP, 570
doorArgDef 9, 713, DIRECTIONS::DOWN, 663

OBJ_MAGICANT_DUNGEONHOLE1:
objectDef OBJ_TYPE::HOLE, 453, DIRECTIONS::UP, 574
doorArgDef 0, 497, DIRECTIONS::DOWN, 572

OBJ_MAGICANT_DUNGEONLADDER2:
objectDef OBJ_TYPE::DOOR, 497, DIRECTIONS::UP, 570
doorArgDef 0, 453, DIRECTIONS::DOWN, 574

OBJ_MAGICANT_DUNGEONHOLE2:
objectDef OBJ_TYPE::HOLE, 461, DIRECTIONS::UP, 574
doorArgDef 0, 537, DIRECTIONS::DOWN, 572

OBJ_MAGICANT_DUNGEONLADDER3:
objectDef OBJ_TYPE::DOOR, 537, DIRECTIONS::UP, 570
doorArgDef 0, 461, DIRECTIONS::DOWN, 574

OBJ_MAGICANT_DUNGEONHOLE3:
objectDef OBJ_TYPE::HOLE, 493, DIRECTIONS::UP, 574
doorArgDef 0, 457, DIRECTIONS::DOWN, 600

OBJ_MAGICANT_DUNGEONLADDER4:
objectDef OBJ_TYPE::DOOR, 457, DIRECTIONS::UP, 598
doorArgDef 0, 493, DIRECTIONS::DOWN, 574

OBJ_MAGICANT_DUNGEONHOLE4:
objectDef OBJ_TYPE::HOLE, 501, DIRECTIONS::UP, 574
doorArgDef 0, 497, DIRECTIONS::DOWN, 600

OBJ_MAGICANT_DUNGEONLADDER5:
objectDef OBJ_TYPE::DOOR, 497, DIRECTIONS::UP, 598
doorArgDef 0, 501, DIRECTIONS::DOWN, 574

OBJ_MAGICANT_DUNGEONHOLE5:
objectDef OBJ_TYPE::HOLE, 533, DIRECTIONS::UP, 574
doorArgDef 0, 537, DIRECTIONS::DOWN, 600

OBJ_MAGICANT_DUNGEONLADDER6:
objectDef OBJ_TYPE::DOOR, 537, DIRECTIONS::UP, 598
doorArgDef 0, 533, DIRECTIONS::DOWN, 574

OBJ_MAGICANT_DUNGEONHOLE6:
objectDef OBJ_TYPE::HOLE, 541, DIRECTIONS::UP, 574
doorArgDef 0, 457, DIRECTIONS::DOWN, 628

OBJ_MAGICANT_DUNGEONLADDER7:
objectDef OBJ_TYPE::DOOR, 457, DIRECTIONS::UP, 626
doorArgDef 0, 541, DIRECTIONS::DOWN, 574

OBJ_MAGICANT_DUNGEONHOLE7:
objectDef OBJ_TYPE::HOLE, 533, DIRECTIONS::UP, 602
doorArgDef 0, 497, DIRECTIONS::DOWN, 628

OBJ_MAGICANT_DUNGEONLADDER8:
objectDef OBJ_TYPE::DOOR, 497, DIRECTIONS::UP, 626
doorArgDef 0, 533, DIRECTIONS::DOWN, 602

OBJ_MAGICANT_DUNGEONHOLE8:
objectDef OBJ_TYPE::HOLE, 541, DIRECTIONS::UP, 602
doorArgDef 0, 537, DIRECTIONS::DOWN, 628

OBJ_MAGICANT_DUNGEONLADDER9:
objectDef OBJ_TYPE::DOOR, 537, DIRECTIONS::UP, 626
doorArgDef 0, 541, DIRECTIONS::DOWN, 602

OBJ_MAGICANT_DUNGEONHOLE9:
objectDef OBJ_TYPE::HOLE, 453, DIRECTIONS::UP, 630
doorArgDef 0, 457, DIRECTIONS::DOWN, 656

OBJ_MAGICANT_DUNGEONLADDER10:
objectDef OBJ_TYPE::DOOR, 457, DIRECTIONS::UP, 654
doorArgDef 0, 453, DIRECTIONS::DOWN, 630

OBJ_MAGICANT_DUNGEONHOLE10:
objectDef OBJ_TYPE::HOLE, 461, DIRECTIONS::UP, 630
doorArgDef 0, 497, DIRECTIONS::DOWN, 656

OBJ_MAGICANT_DUNGEONLADDER11:
objectDef OBJ_TYPE::DOOR, 497, DIRECTIONS::UP, 654
doorArgDef 0, 461, DIRECTIONS::DOWN, 630

OBJ_MAGICANT_DUNGEONHOLE11:
objectDef OBJ_TYPE::HOLE, 493, DIRECTIONS::UP, 630
doorArgDef 0, 537, DIRECTIONS::DOWN, 656

OBJ_MAGICANT_DUNGEONLADDER12:
objectDef OBJ_TYPE::DOOR, 537, DIRECTIONS::UP, 654
doorArgDef 0, 493, DIRECTIONS::DOWN, 630

OBJ_MAGICANT_DUNGEONHOLE12:
objectDef OBJ_TYPE::HOLE, 501, DIRECTIONS::UP, 630
doorArgDef 0, 521, DIRECTIONS::DOWN, 424

OBJ_MAGICANT_DUNGEONLADDER13:
.ifdef VER_JP
objectDef OBJ_TYPE::DOOR, 521, DIRECTIONS::UP, 421
.else
objectDef OBJ_TYPE::DOOR, 521, DIRECTIONS::UP, 422
.endif
doorArgDef 0, 501, DIRECTIONS::DOWN, 630

OBJ_MAGICANT_THEFISH:
objectDef OBJ_TYPE::TRIGGER, 557, DIRECTIONS::UP, 445
OBJ_IS_NOT_TOUCHING @J_IS_NOT_TOUCHING-OBJ_MAGICANT_THEFISH
OBJ_IS_NOT_FLAG 117, @J_IS_NOT_FLAG-OBJ_MAGICANT_THEFISH
OBJ_TELEPORT 0, 509, DIRECTIONS::DOWN, 536
OBJ_STOP
	@J_IS_NOT_FLAG:
OBJ_BATTLE 47
OBJ_SET_FLAG 117
OBJ_TELEPORT 0, 509, DIRECTIONS::DOWN, 536
OBJ_MOVE @MOVE_DATA
	@J_IS_NOT_TOUCHING:
OBJ_STOP

@MOVE_DATA:
moveDef DIRECTIONS::UP, 10, 1
OBJ_STOP

OBJ_MAGICANT_THEFISHLADDER:
objectDef OBJ_TYPE::DOOR, 509, DIRECTIONS::UP, 534
doorArgDef 0, 557, DIRECTIONS::DOWN, 445

OBJ_MAGICANT_FORGOTTEN_MAN:
.ifdef VER_JP
objectDef 29, 565, DIRECTIONS::DOWN, 423
.else
objectDef 29, 533, DIRECTIONS::DOWN, 423
.endif
.addr SPRITEDEF_FORGOTTEN_MAN
OBJ_FLAG_DISAPPEAR 41
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_MAGICANT_FORGOTTEN_MAN
OBJ_INCREMENT_COUNTER 2
OBJ_COUNTERLESSTHAN 2, 5, @J_COUNTERLESSTHAN-OBJ_MAGICANT_FORGOTTEN_MAN
OBJ_RESET_COUNTER 2
OBJ_INCREMENT_COUNTER 2
OBJ_DIALOGUE UMSG::MAGICANT_FORGOTTENMAN5
OBJ_YESNO_IS_NO @J_YESNO_IS_NO-OBJ_MAGICANT_FORGOTTEN_MAN
OBJ_DIALOGUE UMSG::MAGICANT_FORGOTTENMAN5_YES
.ifdef VER_JP
OBJ_NOT_HAS_ITEM 105, @J_NOT_HAS_ITEM-OBJ_MAGICANT_FORGOTTEN_MAN
OBJ_TELEPORT 9, 598, DIRECTIONS::UP, 686
OBJ_UNK
OBJ_STOP
	@J_NOT_HAS_ITEM:
OBJ_TELEPORT 9, 633, DIRECTIONS::UP, 684
OBJ_UNK
.endif
OBJ_STOP
	@J_YESNO_IS_NO:
OBJ_DIALOGUE UMSG::MAGICANT_FORGOTTENMAN6
OBJ_YESNO_IS_NO @J_YESNO_IS_NO1-OBJ_MAGICANT_FORGOTTEN_MAN
OBJ_DIALOGUE UMSG::MAGICANT_FORGOTTENMAN7
OBJ_SET_FLAG 41
OBJ_STOP
	@J_COUNTERLESSTHAN:
OBJ_COUNTERLESSTHAN 2, 4, @J_COUNTERLESSTHAN1-OBJ_MAGICANT_FORGOTTEN_MAN
OBJ_DIALOGUE UMSG::MAGICANT_FORGOTTENMAN4
OBJ_STOP
	@J_COUNTERLESSTHAN1:
OBJ_COUNTERLESSTHAN 2, 3, @J_COUNTERLESSTHAN2-OBJ_MAGICANT_FORGOTTEN_MAN
OBJ_DIALOGUE UMSG::MAGICANT_FORGOTTENMAN3
OBJ_STOP
	@J_COUNTERLESSTHAN2:
OBJ_COUNTERLESSTHAN 2, 2, @J_YESNO_IS_NO1-OBJ_MAGICANT_FORGOTTEN_MAN
OBJ_DIALOGUE UMSG::MAGICANT_FORGOTTENMAN2
OBJ_STOP
	@J_YESNO_IS_NO1:
OBJ_DIALOGUE UMSG::MAGICANT_FORGOTTENMAN1
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_MAGICANT_DRAGON_LEFT:
.ifdef VER_JP
objectDef 25, 565, DIRECTIONS::UP, 486
.else
objectDef 25, 529, DIRECTIONS::UP, 452
.endif
.addr SPRITEDEF_DRAGONLEFT
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_MAGICANT_DRAGON_LEFT
OBJ_IS_NOT_FLAG 129, @J_IS_NOT_FLAG-OBJ_MAGICANT_DRAGON_LEFT
OBJ_IS_NOT_FLAG 242, @J_IS_NOT_FLAG1-OBJ_MAGICANT_DRAGON_LEFT
OBJ_JUMP @J_IS_NOT_FLAG-OBJ_MAGICANT_DRAGON_LEFT
	@J_IS_NOT_FLAG1:
OBJ_DIALOGUE UMSG::MAGICANT_DRAGON_MELODY
OBJ_PLAY_MUSIC 41
OBJ_DELAY 240
OBJ_PLAY_MUSIC 17
OBJ_SET_FLAG 242
OBJ_DIALOGUE UMSG::REMEMBER_MELODY
.ifdef VER_JP
OBJ_CHECK_MELODIES
.endif
OBJ_STOP
	@J_IS_NOT_FLAG:
OBJ_DIALOGUE UMSG::CANARY_GENERIC
OBJ_STOP
	@J_IS_NOT_TALKING:
OBJ_IS_NOT_CHECKING @J_IS_NOT_CHECKING-OBJ_MAGICANT_DRAGON_LEFT
OBJ_IS_NOT_FLAG 129, @J_IS_NOT_FLAG2-OBJ_MAGICANT_DRAGON_LEFT
OBJ_IS_NOT_FLAG 242, @J_IS_NOT_FLAG1-OBJ_MAGICANT_DRAGON_LEFT
OBJ_DIALOGUE UMSG::MAGICANT_DRAGON_SLEEP
OBJ_STOP
	@J_IS_NOT_FLAG2:
OBJ_PICK_CHARACTER 1
OBJ_BELOW_LEVEL 25, @J_BELOW_LEVEL-OBJ_MAGICANT_DRAGON_LEFT
OBJ_DIALOGUE UMSG::MAGICANT_DRAGON_WAKE
OBJ_BATTLE 46
OBJ_SET_FLAG 129
OBJ_STOP
	@J_BELOW_LEVEL:
OBJ_DIALOGUE UMSG::MAGICANT_DRAGON_NOWAKE
	@J_IS_NOT_CHECKING:
OBJ_STOP

OBJ_MAGICANT_DRAGON_RIGHT:
.ifdef VER_JP
objectDef 25, 566, DIRECTIONS::UP, 486
.else
objectDef 25, 530, DIRECTIONS::UP, 452
.endif
.addr SPRITEDEF_DRAGONRIGHT
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_MAGICANT_DRAGON_RIGHT
OBJ_IS_NOT_FLAG 129, @J_IS_NOT_FLAG-OBJ_MAGICANT_DRAGON_RIGHT
OBJ_IS_NOT_FLAG 242, @J_IS_NOT_FLAG1-OBJ_MAGICANT_DRAGON_RIGHT
OBJ_JUMP @J_IS_NOT_FLAG-OBJ_MAGICANT_DRAGON_RIGHT
	@J_IS_NOT_FLAG1:
OBJ_DIALOGUE UMSG::MAGICANT_DRAGON_MELODY
OBJ_PLAY_MUSIC 41
OBJ_DELAY 240
OBJ_PLAY_MUSIC 17
OBJ_SET_FLAG 242
OBJ_DIALOGUE UMSG::REMEMBER_MELODY
.ifdef VER_JP
OBJ_CHECK_MELODIES
.endif
OBJ_STOP
	@J_IS_NOT_FLAG:
OBJ_DIALOGUE UMSG::CANARY_GENERIC
OBJ_STOP
	@J_IS_NOT_TALKING:
OBJ_IS_NOT_CHECKING @J_IS_NOT_CHECKING-OBJ_MAGICANT_DRAGON_RIGHT
OBJ_IS_NOT_FLAG 129, @J_IS_NOT_FLAG2-OBJ_MAGICANT_DRAGON_RIGHT
OBJ_IS_NOT_FLAG 242, @J_IS_NOT_FLAG1-OBJ_MAGICANT_DRAGON_RIGHT
OBJ_DIALOGUE UMSG::MAGICANT_DRAGON_SLEEP
OBJ_STOP
	@J_IS_NOT_FLAG2:
OBJ_PICK_CHARACTER 1
OBJ_BELOW_LEVEL 25, @J_BELOW_LEVEL-OBJ_MAGICANT_DRAGON_RIGHT
OBJ_DIALOGUE UMSG::MAGICANT_DRAGON_WAKE
OBJ_BATTLE 46
OBJ_SET_FLAG 129
OBJ_STOP
	@J_BELOW_LEVEL:
OBJ_DIALOGUE UMSG::MAGICANT_DRAGON_NOWAKE
	@J_IS_NOT_CHECKING:
OBJ_STOP

OBJ_MAGICANT_DUNGEONPRESENT1:
.ifdef VER_JP
objectDef OBJ_TYPE::PRESENT, 533, DIRECTIONS::UP, 631
.else
objectDef OBJ_TYPE::PRESENT, 538, DIRECTIONS::UP, 434
.endif
.addr SPRITEDEF_PRESENT
.byte 62 ; item
.byte 46 ; flag

OBJ_MAGICANT_DUNGEONPRESENT2:
.ifdef VER_JP
objectDef OBJ_TYPE::PRESENT, 457, DIRECTIONS::UP, 659
.else
objectDef OBJ_TYPE::PRESENT, 550, DIRECTIONS::UP, 436
.endif
.addr SPRITEDEF_PRESENT
.byte 12 ; item
.byte 47 ; flag

OBJ_MAGICANT_DUNGEONPRESENT3:
.ifdef VER_JP
objectDef OBJ_TYPE::PRESENT, 461, DIRECTIONS::UP, 604
.else
objectDef OBJ_TYPE::PRESENT, 533, DIRECTIONS::UP, 460
.endif
.addr SPRITEDEF_PRESENT
.byte 73 ; item
.byte 48 ; flag

OBJ_MAGICANT_DUNGEONPRESENT4:
.ifdef VER_JP
objectDef OBJ_TYPE::PRESENT, 509, DIRECTIONS::UP, 492
.else
objectDef OBJ_TYPE::PRESENT, 453, DIRECTIONS::UP, 659
.endif
.addr SPRITEDEF_PRESENT
.byte 62 ; item
.byte 49 ; flag

OBJ_MAGICANT_DUNGEONPRESENT5:
objectDef OBJ_TYPE::PRESENT, 509, DIRECTIONS::UP, 538
.addr SPRITEDEF_PRESENT
.byte 107 ; item
.byte 52 ; flag

