OBJ_BANK_33:
.addr OBJ_DUNCANFACTORY_RM18EXIT
.addr OBJ_DUNCANFACTORY_RM19EXIT
.addr OBJ_DUNCANFACTORY_RM20EXIT
.addr OBJ_DUNCANFACTORY_RM21EXIT
.addr OBJ_DUNCANFACTORY_RM22EXIT
.addr OBJ_DUNCANFACTORY_RM23EXIT
.addr OBJ_DUNCANFACTORY_PRESENT15
.addr OBJ_DUNCANFACTORY_PRESENT16
.addr OBJ_DUNCANFACTORY_PRESENT17
.addr OBJ_DUNCANFACTORY_PRESENT18
.addr OBJ_DUNCANFACTORY_PRESENT19
.addr OBJ_DUNCANFACTORY_PRESENT20
.addr 0

OBJ_DUNCANFACTORY_RM18EXIT:
objectDef OBJ_TYPE::DOOR, 1, DIRECTIONS::LEFT, 934
doorArgDef 0, 261, DIRECTIONS::LEFT, 874

OBJ_DUNCANFACTORY_RM19EXIT:
objectDef OBJ_TYPE::DOOR, 1, DIRECTIONS::LEFT, 710
doorArgDef 0, 301, DIRECTIONS::LEFT, 902

OBJ_DUNCANFACTORY_RM20EXIT:
objectDef OBJ_TYPE::DOOR, 177, DIRECTIONS::LEFT, 726
doorArgDef 0, 325, DIRECTIONS::LEFT, 954

OBJ_DUNCANFACTORY_RM21EXIT:
objectDef OBJ_TYPE::DOOR, 174, DIRECTIONS::RIGHT, 710
doorArgDef 0, 309, DIRECTIONS::DOWN, 972

OBJ_DUNCANFACTORY_RM22EXIT:
objectDef OBJ_TYPE::DOOR, 193, DIRECTIONS::LEFT, 710
doorArgDef 0, 301, DIRECTIONS::LEFT, 990

OBJ_DUNCANFACTORY_RM23EXIT:
objectDef OBJ_TYPE::DOOR, 14, DIRECTIONS::RIGHT, 998
doorArgDef 0, 290, DIRECTIONS::RIGHT, 998

OBJ_DUNCANFACTORY_PRESENT15:
objectDef OBJ_TYPE::PRESENT, 168, DIRECTIONS::UP, 710
.addr SPRITEDEF_PRESENT
.byte 35 ; item
.byte 67 ; flag

OBJ_DUNCANFACTORY_PRESENT16:
objectDef OBJ_TYPE::PRESENT, 10, DIRECTIONS::UP, 996
.addr SPRITEDEF_PRESENT
.byte 40 ; item
.byte 68 ; flag

OBJ_DUNCANFACTORY_PRESENT17:
objectDef OBJ_TYPE::PRESENT, 201, DIRECTIONS::UP, 710
.addr SPRITEDEF_PRESENT
.byte 97 ; item
.byte 69 ; flag

OBJ_DUNCANFACTORY_PRESENT18:
objectDef OBJ_TYPE::PRESENT, 198, DIRECTIONS::UP, 709
.addr SPRITEDEF_PRESENT
.byte 97 ; item
.byte 70 ; flag

OBJ_DUNCANFACTORY_PRESENT19:
objectDef OBJ_TYPE::PRESENT, 200, DIRECTIONS::UP, 726
.addr SPRITEDEF_PRESENT
.byte 26 ; item
.byte 71 ; flag

OBJ_DUNCANFACTORY_PRESENT20:
objectDef OBJ_TYPE::PRESENT, 12, DIRECTIONS::UP, 711
.addr SPRITEDEF_PRESENT
.byte 35 ; item
.byte 72 ; flag

