OBJ_BANK_32:
.addr OBJ_DUNCANFACTORY_RM1EXIT
.addr OBJ_DUNCANFACTORY_RM2EXIT
.addr OBJ_DUNCANFACTORY_RM3EXIT
.addr OBJ_DUNCANFACTORY_RM4EXIT
.addr OBJ_DUNCANFACTORY_RM5EXIT
.addr OBJ_DUNCANFACTORY_RM6EXIT
.addr OBJ_DUNCANFACTORY_RM7EXIT
.addr OBJ_DUNCANFACTORY_RM8EXIT
.addr OBJ_DUNCANFACTORY_RM9EXIT
.addr OBJ_DUNCANFACTORY_RM10EXIT
.addr OBJ_DUNCANFACTORY_RM11EXIT
.addr OBJ_DUNCANFACTORY_RM12EXIT
.addr OBJ_DUNCANFACTORY_RM13EXIT
.addr OBJ_DUNCANFACTORY_RM14EXIT
.addr OBJ_DUNCANFACTORY_RM15EXIT
.addr OBJ_DUNCANFACTORY_RM16EXIT
.addr OBJ_DUNCANFACTORY_RM17EXIT
.addr OBJ_DUNCANFACTORY_ROCKET
.addr OBJ_DUNCANFACTORY_HOLSTER1
.addr OBJ_DUNCANFACTORY_HOLSTER2
.addr OBJ_DUNCANFACTORY_HOLSTER3
.addr OBJ_DUNCANFACTORY_PRESENT1
.addr OBJ_DUNCANFACTORY_PRESENT2
.addr OBJ_DUNCANFACTORY_PRESENT3
.addr OBJ_DUNCANFACTORY_PRESENT4
.addr OBJ_DUNCANFACTORY_PRESENT5
.addr OBJ_DUNCANFACTORY_PRESENT6
.addr OBJ_DUNCANFACTORY_PRESENT7
.addr OBJ_DUNCANFACTORY_PRESENT8
.addr OBJ_DUNCANFACTORY_PRESENT9
.addr OBJ_DUNCANFACTORY_PRESENT10
.addr OBJ_DUNCANFACTORY_PRESENT11
.addr OBJ_DUNCANFACTORY_PRESENT12
.addr OBJ_DUNCANFACTORY_PRESENT13
.addr OBJ_DUNCANFACTORY_PRESENT14
.addr 0

OBJ_DUNCANFACTORY_RM1EXIT:
objectDef OBJ_TYPE::DOOR, 14, DIRECTIONS::RIGHT, 838
doorArgDef 0, 225, DIRECTIONS::DOWN, 860

OBJ_DUNCANFACTORY_RM2EXIT:
objectDef OBJ_TYPE::DOOR, 14, DIRECTIONS::RIGHT, 870
doorArgDef 0, 161, DIRECTIONS::DOWN, 876

OBJ_DUNCANFACTORY_RM3EXIT:
objectDef OBJ_TYPE::DOOR, 94, DIRECTIONS::RIGHT, 726
doorArgDef 0, 157, DIRECTIONS::DOWN, 888

OBJ_DUNCANFACTORY_RM4EXIT:
objectDef OBJ_TYPE::DOOR, 14, DIRECTIONS::RIGHT, 966
doorArgDef 0, 201, DIRECTIONS::DOWN, 888

OBJ_DUNCANFACTORY_RM5EXIT:
objectDef OBJ_TYPE::DOOR, 46, DIRECTIONS::RIGHT, 838
doorArgDef 0, 225, DIRECTIONS::DOWN, 884

OBJ_DUNCANFACTORY_RM6EXIT:
objectDef OBJ_TYPE::DOOR, 33, DIRECTIONS::LEFT, 870
doorArgDef 0, 233, DIRECTIONS::LEFT, 886

OBJ_DUNCANFACTORY_RM7EXIT:
objectDef OBJ_TYPE::DOOR, 46, DIRECTIONS::RIGHT, 934
doorArgDef 0, 93, DIRECTIONS::DOWN, 896

OBJ_DUNCANFACTORY_RM8EXIT:
objectDef OBJ_TYPE::DOOR, 62, DIRECTIONS::RIGHT, 758
doorArgDef 0, 78, DIRECTIONS::RIGHT, 902

OBJ_DUNCANFACTORY_RM9EXIT:
objectDef OBJ_TYPE::DOOR, 33, DIRECTIONS::LEFT, 966
doorArgDef 0, 217, DIRECTIONS::LEFT, 938

OBJ_DUNCANFACTORY_RM10EXIT:
objectDef OBJ_TYPE::DOOR, 33, DIRECTIONS::LEFT, 998
doorArgDef 0, 169, DIRECTIONS::LEFT, 942

OBJ_DUNCANFACTORY_RM11EXIT:
objectDef OBJ_TYPE::DOOR, 78, DIRECTIONS::RIGHT, 838
doorArgDef 0, 157, DIRECTIONS::DOWN, 972

OBJ_DUNCANFACTORY_RM12EXIT:
objectDef OBJ_TYPE::DOOR, 33, DIRECTIONS::LEFT, 710
doorArgDef 0, 225, DIRECTIONS::LEFT, 994

OBJ_DUNCANFACTORY_RM13EXIT:
objectDef OBJ_TYPE::DOOR, 30, DIRECTIONS::RIGHT, 726
doorArgDef 0, 213, DIRECTIONS::DOWN, 988

OBJ_DUNCANFACTORY_RM14EXIT:
objectDef OBJ_TYPE::DOOR, 78, DIRECTIONS::RIGHT, 710
doorArgDef 0, 205, DIRECTIONS::DOWN, 988

OBJ_DUNCANFACTORY_RM15EXIT:
objectDef OBJ_TYPE::DOOR, 97, DIRECTIONS::LEFT, 710
doorArgDef 0, 149, DIRECTIONS::LEFT, 990

OBJ_DUNCANFACTORY_RM16EXIT:
objectDef OBJ_TYPE::DOOR, 142, DIRECTIONS::RIGHT, 710
doorArgDef 0, 125, DIRECTIONS::DOWN, 940

OBJ_DUNCANFACTORY_RM17EXIT:
objectDef OBJ_TYPE::DOOR, 238, DIRECTIONS::RIGHT, 710
doorArgDef 0, 117, DIRECTIONS::DOWN, 964

OBJ_DUNCANFACTORY_ROCKET:
objectDef 29, 38, DIRECTIONS::UP, 758
.addr SPRITEDEF_DUNCAN_ROCKET
OBJ_FLAG_DISAPPEAR 113
OBJ_IS_NOT_CHECKING @J_IS_NOT_CHECKING-OBJ_DUNCANFACTORY_ROCKET
OBJ_JUMP @J_JUMP-OBJ_DUNCANFACTORY_ROCKET
	@J_IS_NOT_CHECKING:
OBJ_IS_SIGNAL @J_IS_SIGNAL-OBJ_DUNCANFACTORY_ROCKET
	@J_JUMP:
OBJ_IS_NOT_FLAG 113, @J_IS_NOT_FLAG-OBJ_DUNCANFACTORY_ROCKET
OBJ_JUMP @J_IS_SIGNAL-OBJ_DUNCANFACTORY_ROCKET
	@J_IS_NOT_FLAG:
OBJ_NOT_HAS_CHARACTER 3, @J_NOT_HAS_CHARACTER-OBJ_DUNCANFACTORY_ROCKET
OBJ_HAS_STATUS 128, @J_NOT_HAS_CHARACTER-OBJ_DUNCANFACTORY_ROCKET
OBJ_DIALOGUE UMSG::DUNCANFACTORY_USEROCKET
OBJ_MOVE @MOVE_DATA_1
OBJ_PLAY_SOUND2 9
OBJ_MOVE @MOVE_DATA_2
OBJ_PLAY_SOUND2 2
OBJ_WRITE_SAVEMETA 30, 82
OBJ_SET_FLAG 113
OBJ_MOVE @MOVE_DATA_3
OBJ_STOP
	@J_NOT_HAS_CHARACTER:
OBJ_DIALOGUE UMSG::ELLAY_TOWER_ROCKETCHECK
	@J_IS_SIGNAL:
OBJ_STOP

@MOVE_DATA_1:
moveDef DIRECTIONS::UP, MOVE_CMD::ABOUTFACE, 1
OBJ_RETURN
@MOVE_DATA_2:
moveDef DIRECTIONS::UP_RIGHT, MOVE_CMD::MOVE, 6
moveDef DIRECTIONS::UP_RIGHT, 27, 8
OBJ_RETURN
@MOVE_DATA_3:
OBJ_STOP

OBJ_DUNCANFACTORY_HOLSTER1:
objectDef 25, 38, DIRECTIONS::UP, 759
.addr SPRITEDEF_DUNCAN_ROCKETHOLSTER
OBJ_IS_NOT_CHECKING @J_IS_NOT_CHECKING-OBJ_DUNCANFACTORY_HOLSTER1
OBJ_SIGNAL 17
	@J_IS_NOT_CHECKING:
OBJ_STOP

OBJ_DUNCANFACTORY_HOLSTER2:
objectDef 25, 40, DIRECTIONS::UP, 757
.addr SPRITEDEF_DUNCAN_ROCKETHOLSTER
OBJ_STOP

OBJ_DUNCANFACTORY_HOLSTER3:
objectDef 25, 36, DIRECTIONS::UP, 757
.addr SPRITEDEF_DUNCAN_ROCKETHOLSTER
OBJ_STOP

OBJ_DUNCANFACTORY_PRESENT1:
objectDef OBJ_TYPE::PRESENT, 72, DIRECTIONS::UP, 837
.addr SPRITEDEF_PRESENT
.byte 35 ; item
.byte 53 ; flag

OBJ_DUNCANFACTORY_PRESENT2:
objectDef OBJ_TYPE::PRESENT, 71, DIRECTIONS::UP, 709
.addr SPRITEDEF_PRESENT
.byte 65 ; item
.byte 54 ; flag

OBJ_DUNCANFACTORY_PRESENT3:
objectDef OBJ_TYPE::PRESENT, 22, DIRECTIONS::UP, 726
.addr SPRITEDEF_PRESENT
.byte 78 ; item
.byte 55 ; flag

OBJ_DUNCANFACTORY_PRESENT4:
objectDef OBJ_TYPE::PRESENT, 15, DIRECTIONS::UP, 726
.addr SPRITEDEF_PRESENT
.byte 80 ; item
.byte 56 ; flag

OBJ_DUNCANFACTORY_PRESENT5:
objectDef OBJ_TYPE::PRESENT, 8, DIRECTIONS::UP, 726
.addr SPRITEDEF_PRESENT
.byte 79 ; item
.byte 57 ; flag

OBJ_DUNCANFACTORY_PRESENT6:
objectDef OBJ_TYPE::PRESENT, 100, DIRECTIONS::UP, 710
.addr SPRITEDEF_PRESENT
.byte 40 ; item
.byte 58 ; flag

OBJ_DUNCANFACTORY_PRESENT7:
objectDef OBJ_TYPE::PRESENT, 228, DIRECTIONS::UP, 708
.addr SPRITEDEF_PRESENT
.byte 35 ; item
.byte 59 ; flag

OBJ_DUNCANFACTORY_PRESENT8:
objectDef OBJ_TYPE::PRESENT, 136, DIRECTIONS::UP, 708
.addr SPRITEDEF_PRESENT
.byte 73 ; item
.byte 60 ; flag

OBJ_DUNCANFACTORY_PRESENT9:
objectDef OBJ_TYPE::PRESENT, 68, DIRECTIONS::UP, 725
.addr SPRITEDEF_PRESENT
.byte 65 ; item
.byte 61 ; flag

OBJ_DUNCANFACTORY_PRESENT10:
objectDef OBJ_TYPE::PRESENT, 5, DIRECTIONS::UP, 870
.addr SPRITEDEF_PRESENT
.byte 97 ; item
.byte 62 ; flag

OBJ_DUNCANFACTORY_PRESENT11:
objectDef OBJ_TYPE::PRESENT, 9, DIRECTIONS::UP, 967
.addr SPRITEDEF_PRESENT
.byte 40 ; item
.byte 63 ; flag

OBJ_DUNCANFACTORY_PRESENT12:
objectDef OBJ_TYPE::PRESENT, 36, DIRECTIONS::UP, 839
.addr SPRITEDEF_PRESENT
.byte 71 ; item
.byte 64 ; flag

OBJ_DUNCANFACTORY_PRESENT13:
objectDef OBJ_TYPE::PRESENT, 42, DIRECTIONS::UP, 869
.addr SPRITEDEF_PRESENT
.byte 104 ; item
.byte 65 ; flag

OBJ_DUNCANFACTORY_PRESENT14:
objectDef OBJ_TYPE::PRESENT, 5, DIRECTIONS::UP, 837
.addr SPRITEDEF_PRESENT
.byte 81 ; item
.byte 66 ; flag

