OBJ_BANK_39:
.addr OBJ_PODUNK_MAGICAVEEXIT
.addr OBJ_PODUNK_MAGICAVESHELL
.addr OBJ_MCAVE_MAGICAVE_EXIT
.addr OBJ_MCAVE_MAGICAVESHELL
.addr OBJ_MERRYSVILLE_MAGICAVEEXIT
.addr OBJ_YOUNGTOWN_MAGICAVEEXIT
.addr OBJ_MAGICANT_DUNGEONENTRANCE
.addr OBJ_MAGICANT_CASTLEENTRANCE
.addr OBJ_MAGICANT_FLYINGMANHOUSEENTRANCE
.addr OBJ_MAGICANT_FOUNTAIN
.addr OBJ_MAGICANT_BENEVOLENTOLDMAN
.addr OBJ_MAGICANT_STRENGTHMAN
.addr OBJ_MAGICANT_HOLEMAN
.addr OBJ_MAGICANT_FLYINGMANGRAVE5
.addr OBJ_MAGICANT_FLYINGMANGRAVE1
.addr OBJ_MAGICANT_FLYINGMANGRAVE2
.addr OBJ_MAGICANT_FLYINGMANGRAVE3
.addr OBJ_MAGICANT_FLYINGMANGRAVE4
.addr OBJ_MAGICANT_REDWEED
.addr OBJ_MAGICANT_REDWEED2
.addr OBJ_MAGICANT_REDWEED3
.addr OBJ_MAGICANT_GUARD3
.addr OBJ_MAGICANT_GUARD2
.addr OBJ_MAGICANT_GUARD1
.addr 0

OBJ_PODUNK_MAGICAVEEXIT:
objectDef OBJ_TYPE::DOOR, 962, DIRECTIONS::UP, 532
doorArgDef 6, 329, DIRECTIONS::DOWN, 232

OBJ_PODUNK_MAGICAVESHELL:
objectDef 24, 970, DIRECTIONS::UP, 514
OBJ_IS_NOT_CHECKING @J_IS_NOT_CHECKING-OBJ_PODUNK_MAGICAVESHELL
.ifdef VER_JP
OBJ_IS_NOT_FLAG 240, @J_IS_NOT_FLAG-OBJ_PODUNK_MAGICAVESHELL
.else
OBJ_IS_NOT_FLAG 224, @J_IS_NOT_FLAG-OBJ_PODUNK_MAGICAVESHELL
.endif
OBJ_JUMP @J_JUMP-OBJ_PODUNK_MAGICAVESHELL
	@J_IS_NOT_FLAG:
OBJ_DIALOGUE UMSG::REINDEER_DRAGONGIRL_CHECK
OBJ_STOP
	@J_IS_NOT_CHECKING:
OBJ_IS_NOT_CASTING 1, @J_JUMP-OBJ_PODUNK_MAGICAVESHELL
.ifdef VER_JP
OBJ_IS_NOT_FLAG 240, @J_IS_NOT_FLAG1-OBJ_PODUNK_MAGICAVESHELL
.else
OBJ_IS_NOT_FLAG 224, @J_IS_NOT_FLAG1-OBJ_PODUNK_MAGICAVESHELL
.endif
OBJ_JUMP @J_JUMP-OBJ_PODUNK_MAGICAVESHELL
	@J_IS_NOT_FLAG1:
OBJ_DIALOGUE UMSG::MAGICAVE_SHELLQUESTION
OBJ_NOT_HAS_ITEM 88, @J_JUMP-OBJ_PODUNK_MAGICAVESHELL
OBJ_DIALOGUE UMSG::MAGICAVE_SHELLDIARY
OBJ_SET_FLAG 135
OBJ_TELEPORT 9, 641, DIRECTIONS::DOWN, 680
OBJ_SET_FADE 2
OBJ_UNK
	@J_JUMP:
OBJ_STOP

OBJ_MCAVE_MAGICAVE_EXIT:
objectDef OBJ_TYPE::DOOR, 994, DIRECTIONS::UP, 552
doorArgDef 24, 77, DIRECTIONS::DOWN, 665

OBJ_MCAVE_MAGICAVESHELL:
objectDef 24, 1014, DIRECTIONS::UP, 546
OBJ_IS_NOT_CHECKING @J_IS_NOT_CHECKING-OBJ_MCAVE_MAGICAVESHELL
.ifdef VER_JP
OBJ_IS_NOT_FLAG 240, @J_IS_NOT_FLAG-OBJ_MCAVE_MAGICAVESHELL
.else
OBJ_IS_NOT_FLAG 224, @J_IS_NOT_FLAG-OBJ_MCAVE_MAGICAVESHELL
.endif
OBJ_JUMP @J_JUMP-OBJ_MCAVE_MAGICAVESHELL
	@J_IS_NOT_FLAG:
OBJ_DIALOGUE UMSG::REINDEER_DRAGONGIRL_CHECK
OBJ_STOP
	@J_IS_NOT_CHECKING:
OBJ_IS_NOT_CASTING 1, @J_JUMP-OBJ_MCAVE_MAGICAVESHELL
.ifdef VER_JP
OBJ_IS_NOT_FLAG 240, @J_IS_NOT_FLAG1-OBJ_MCAVE_MAGICAVESHELL
.else
OBJ_IS_NOT_FLAG 224, @J_IS_NOT_FLAG1-OBJ_MCAVE_MAGICAVESHELL
.endif
OBJ_JUMP @J_JUMP-OBJ_MCAVE_MAGICAVESHELL
	@J_IS_NOT_FLAG1:
OBJ_DIALOGUE UMSG::MAGICAVE_SHELLQUESTION
OBJ_CLEAR_FLAG 135
OBJ_TELEPORT 9, 641, DIRECTIONS::DOWN, 680
OBJ_SET_FADE 2
OBJ_UNK
	@J_JUMP:
OBJ_STOP

OBJ_MERRYSVILLE_MAGICAVEEXIT:
objectDef OBJ_TYPE::DOOR, 998, DIRECTIONS::UP, 520
doorArgDef 6, 358, DIRECTIONS::DOWN, 591

OBJ_YOUNGTOWN_MAGICAVEEXIT:
objectDef OBJ_TYPE::DOOR, 1021, DIRECTIONS::UP, 484
doorArgDef 8, 633, DIRECTIONS::DOWN, 400

OBJ_MAGICANT_DUNGEONENTRANCE:
objectDef OBJ_TYPE::HOLE, 713, DIRECTIONS::UP, 663
doorArgDef 17, 457, DIRECTIONS::DOWN, 572

OBJ_MAGICANT_CASTLEENTRANCE:
objectDef OBJ_TYPE::DOOR, 692, DIRECTIONS::UP, 618
doorArgDef 26, 36, DIRECTIONS::LEFT, 549

OBJ_MAGICANT_FLYINGMANHOUSEENTRANCE:
objectDef OBJ_TYPE::TRIGGER, 714, DIRECTIONS::UP, 595
OBJ_IS_NOT_FACING @J_IS_NOT_FACING-OBJ_MAGICANT_FLYINGMANHOUSEENTRANCE
OBJ_IS_NOT_TOUCHING @J_IS_NOT_FACING-OBJ_MAGICANT_FLYINGMANHOUSEENTRANCE
OBJ_CLEAR_FLAG 0
OBJ_IS_NOT_FLAG 100, @J_IS_NOT_FLAG-OBJ_MAGICANT_FLYINGMANHOUSEENTRANCE
OBJ_NOT_HAS_CHARACTER 7, @J_NOT_HAS_CHARACTER-OBJ_MAGICANT_FLYINGMANHOUSEENTRANCE
OBJ_JUMP @J_IS_NOT_FLAG-OBJ_MAGICANT_FLYINGMANHOUSEENTRANCE
	@J_NOT_HAS_CHARACTER:
OBJ_SET_FLAG 0
OBJ_SET_FLAG 105
	@J_IS_NOT_FLAG:
OBJ_IS_NOT_FLAG 101, @J_IS_NOT_FLAG1-OBJ_MAGICANT_FLYINGMANHOUSEENTRANCE
OBJ_NOT_HAS_CHARACTER 7, @J_NOT_HAS_CHARACTER1-OBJ_MAGICANT_FLYINGMANHOUSEENTRANCE
OBJ_JUMP @J_IS_NOT_FLAG1-OBJ_MAGICANT_FLYINGMANHOUSEENTRANCE
	@J_NOT_HAS_CHARACTER1:
OBJ_SET_FLAG 0
OBJ_SET_FLAG 106
	@J_IS_NOT_FLAG1:
OBJ_IS_NOT_FLAG 102, @J_IS_NOT_FLAG2-OBJ_MAGICANT_FLYINGMANHOUSEENTRANCE
OBJ_NOT_HAS_CHARACTER 7, @J_NOT_HAS_CHARACTER2-OBJ_MAGICANT_FLYINGMANHOUSEENTRANCE
OBJ_JUMP @J_IS_NOT_FLAG2-OBJ_MAGICANT_FLYINGMANHOUSEENTRANCE
	@J_NOT_HAS_CHARACTER2:
OBJ_SET_FLAG 0
OBJ_SET_FLAG 107
	@J_IS_NOT_FLAG2:
OBJ_IS_NOT_FLAG 103, @J_IS_NOT_FLAG3-OBJ_MAGICANT_FLYINGMANHOUSEENTRANCE
OBJ_NOT_HAS_CHARACTER 7, @J_NOT_HAS_CHARACTER3-OBJ_MAGICANT_FLYINGMANHOUSEENTRANCE
OBJ_JUMP @J_IS_NOT_FLAG3-OBJ_MAGICANT_FLYINGMANHOUSEENTRANCE
	@J_NOT_HAS_CHARACTER3:
OBJ_SET_FLAG 0
OBJ_SET_FLAG 108
	@J_IS_NOT_FLAG3:
OBJ_IS_NOT_FLAG 104, @J_IS_NOT_FLAG4-OBJ_MAGICANT_FLYINGMANHOUSEENTRANCE
OBJ_NOT_HAS_CHARACTER 7, @J_NOT_HAS_CHARACTER4-OBJ_MAGICANT_FLYINGMANHOUSEENTRANCE
OBJ_JUMP @J_IS_NOT_FLAG4-OBJ_MAGICANT_FLYINGMANHOUSEENTRANCE
	@J_NOT_HAS_CHARACTER4:
OBJ_SET_FLAG 0
OBJ_SET_FLAG 109
	@J_IS_NOT_FLAG4:
OBJ_IS_NOT_FLAG 0, @J_IS_NOT_FLAG5-OBJ_MAGICANT_FLYINGMANHOUSEENTRANCE
OBJ_CLEAR_FLAG 0
OBJ_SET_FLAG 110
	@J_IS_NOT_FLAG5:
OBJ_TELEPORT 0, 13, DIRECTIONS::LEFT, 534
	@J_IS_NOT_FACING:
OBJ_STOP

OBJ_MAGICANT_FOUNTAIN:
objectDef 24, 607, DIRECTIONS::UP, 607
OBJ_IS_NOT_TOUCHING @J_IS_NOT_TOUCHING-OBJ_MAGICANT_FOUNTAIN
OBJ_DIALOGUE UMSG::MAGICANT_FOUNTAIN

OBJ_PICK_CHARACTER_J 0, @J_PICK_CHARACTER_J-OBJ_MAGICANT_FOUNTAIN
OBJ_HAS_STATUS 128, @J_HAS_STATUS-OBJ_MAGICANT_FOUNTAIN
	@J_NOT_MAX_HEALTH:
OBJ_HEAL 255
OBJ_NOT_MAX_HEALTH @J_NOT_MAX_HEALTH-OBJ_MAGICANT_FOUNTAIN
	@J_HAS_STATUS:

OBJ_PICK_CHARACTER_J 1, @J_PICK_CHARACTER_J-OBJ_MAGICANT_FOUNTAIN
OBJ_HAS_STATUS 128, @J_HAS_STATUS1-OBJ_MAGICANT_FOUNTAIN
	@J_NOT_MAX_HEALTH1:
OBJ_HEAL 255
OBJ_NOT_MAX_HEALTH @J_NOT_MAX_HEALTH1-OBJ_MAGICANT_FOUNTAIN
	@J_HAS_STATUS1:

OBJ_PICK_CHARACTER_J 2, @J_PICK_CHARACTER_J-OBJ_MAGICANT_FOUNTAIN
OBJ_HAS_STATUS 128, @J_PICK_CHARACTER_J-OBJ_MAGICANT_FOUNTAIN
	@J_NOT_MAX_HEALTH2:
OBJ_HEAL 255
OBJ_NOT_MAX_HEALTH @J_NOT_MAX_HEALTH2-OBJ_MAGICANT_FOUNTAIN
	@J_PICK_CHARACTER_J:

OBJ_PLAY_SOUND 7
OBJ_STOP
	@J_IS_NOT_TOUCHING:
OBJ_IS_NOT_USING 111, @J_IS_NOT_USING-OBJ_MAGICANT_FOUNTAIN
OBJ_DIALOGUE UMSG::MAGICANT_FOUNTAINREDWEED
OBJ_PICK_ITEM 111
OBJ_REMOVE_ITEM @J_REMOVE_ITEM-OBJ_MAGICANT_FOUNTAIN
OBJ_PICK_ITEM 62
OBJ_GIVE_ITEM @J_REMOVE_ITEM-OBJ_MAGICANT_FOUNTAIN
OBJ_STOP
	@J_IS_NOT_USING:
OBJ_IS_NOT_CASTING 1, @J_REMOVE_ITEM-OBJ_MAGICANT_FOUNTAIN
OBJ_DIALOGUE UMSG::MAGICANT_BENEVOLENT_APPEAR
OBJ_SET_FLAG 112
	@J_REMOVE_ITEM:
OBJ_STOP

OBJ_MAGICANT_BENEVOLENTOLDMAN:
objectDef 29, 607, DIRECTIONS::DOWN, 607
.addr SPRITEDEF_MAGICANT_OLDMAN
OBJ_FLAG_APPEAR 112
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_MAGICANT_BENEVOLENTOLDMAN
OBJ_DIALOGUE UMSG::MCAVE_QUICKMONKEY_CAUGHT
OBJ_YESNO_IS_NO @J_YESNO_IS_NO-OBJ_MAGICANT_BENEVOLENTOLDMAN
OBJ_JUMP @J_JUMP-OBJ_MAGICANT_BENEVOLENTOLDMAN
	@J_YESNO_IS_NO:
OBJ_DIALOGUE UMSG::MAGICANT_BENEVOLENTOLDMAN_NO
OBJ_CLEAR_FLAG 112
OBJ_STOP
	@J_JUMP:
OBJ_DIALOGUE UMSG::MAGICANT_BENEVOLENTOLDMAN_YES
;jp has the old man be a pseudo-healer
.ifdef VER_JP
OBJ_MENU UMSG::MAGICANT_BENEVOLENT_MENU, @J_MENU-OBJ_MAGICANT_BENEVOLENTOLDMAN, @J_MENU1-OBJ_MAGICANT_BENEVOLENTOLDMAN
OBJ_DIALOGUE UMSG::MAGICANT_BENEVOLENT_CURE
OBJ_CHOOSE_CHARACTER @J_CHOOSE_CHARACTER-OBJ_MAGICANT_BENEVOLENTOLDMAN
OBJ_HAS_STATUS 2, @J_HAS_STATUS-OBJ_MAGICANT_BENEVOLENTOLDMAN
	@J_CHOOSE_CHARACTER:
OBJ_DIALOGUE UMSG::MAGICANT_BENEVOLENT_NO_CURE
OBJ_CLEAR_FLAG 112
OBJ_STOP
	@J_HAS_STATUS:
OBJ_DIALOGUE UMSG::MAGICANT_BENEVOLENTOLDMAN_DO_CURE
OBJ_YESNO_IS_NO @J_MENU1-OBJ_MAGICANT_BENEVOLENTOLDMAN
OBJ_DIALOGUE UMSG::MAGICANT_BENEVOLENTOLDMAN_DO_CURE2
OBJ_AND_STATUS 253
OBJ_CLEAR_FLAG 112
OBJ_STOP
	@J_MENU:
OBJ_DIALOGUE UMSG::HEALER_WHO
OBJ_CHOOSE_CHARACTER @J_CHOOSE_CHARACTER1-OBJ_MAGICANT_BENEVOLENTOLDMAN
OBJ_HAS_STATUS 1, @J_HAS_STATUS1-OBJ_MAGICANT_BENEVOLENTOLDMAN
	@J_CHOOSE_CHARACTER1:
OBJ_DIALOGUE UMSG::MAGICANT_BENEVOLENT_NO_CURE
OBJ_CLEAR_FLAG 112
OBJ_STOP
	@J_HAS_STATUS1:
OBJ_DIALOGUE UMSG::MAGICANT_BENEVOLENTOLDMAN_DO_CURE
OBJ_YESNO_IS_NO @J_MENU1-OBJ_MAGICANT_BENEVOLENTOLDMAN
OBJ_DIALOGUE UMSG::MAGICANT_BENEVOLENTOLDMAN_DO_CURE2
OBJ_AND_STATUS 254
OBJ_CLEAR_FLAG 112
OBJ_STOP
	@J_MENU1:
OBJ_DIALOGUE UMSG::MAGICANT_BENEVOLENTOLDMAN_LEAVE
OBJ_CLEAR_FLAG 112
.else
OBJ_YESNO_IS_NO @J_YESNO_IS_NO-OBJ_MAGICANT_BENEVOLENTOLDMAN
OBJ_DIALOGUE UMSG::MAGICANT_BENEVOLENTOLDMAN_MONEY
OBJ_INPUT_NUMBER @J_YESNO_IS_NO-OBJ_MAGICANT_BENEVOLENTOLDMAN
OBJ_DEPOSIT @J_DEPOSIT-OBJ_MAGICANT_BENEVOLENTOLDMAN
OBJ_GIVE_MONEY @J_GIVE_MONEY-OBJ_MAGICANT_BENEVOLENTOLDMAN
OBJ_SHOW_MONEY
OBJ_DIALOGUE UMSG::MAGICANT_BENEVOLENTOLDMAN_GIVE
OBJ_CLEAR_FLAG 112
OBJ_STOP
	@J_GIVE_MONEY:
OBJ_WITHDRAW @J_GIVE_MONEY-OBJ_MAGICANT_BENEVOLENTOLDMAN
OBJ_DIALOGUE UMSG::MAGICANT_BENEVOLENTOLDMAN_TOOMUCH
OBJ_CLEAR_FLAG 112
OBJ_STOP
	@J_DEPOSIT:
OBJ_DIALOGUE UMSG::MAGICANT_BENEVOLENTOLDMAN_NOTENOUGH
OBJ_CLEAR_FLAG 112
.endif
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_MAGICANT_STRENGTHMAN:
objectDef OBJ_TYPE::WANDERING_NPC, 605, DIRECTIONS::DOWN, 611
.addr SPRITEDEF_BAG_MAN_PINK
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_MAGICANT_STRENGTHMAN
OBJ_DIALOGUE UMSG::MAGICANT_STRENGTHMAN
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_MAGICANT_HOLEMAN:
objectDef OBJ_TYPE::WANDERING_NPC, 603, DIRECTIONS::DOWN, 609
.addr SPRITEDEF_BAG_MAN_PINK
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_MAGICANT_HOLEMAN
OBJ_DIALOGUE UMSG::MAGICANT_HOLEMAN
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_MAGICANT_FLYINGMANGRAVE5:
objectDef 29, 725, DIRECTIONS::UP, 594
.addr SPRITEDEF_GRAVESTONE
OBJ_FLAG_APPEAR 109
OBJ_IS_NOT_CHECKING @J_IS_NOT_CHECKING-OBJ_MAGICANT_FLYINGMANGRAVE5
OBJ_DIALOGUE UMSG::MAGICANT_FLYINGMANGRAVE5
	@J_IS_NOT_CHECKING:
OBJ_STOP

OBJ_MAGICANT_FLYINGMANGRAVE1:
objectDef 29, 717, DIRECTIONS::UP, 594
.addr SPRITEDEF_GRAVESTONE
OBJ_FLAG_APPEAR 105
OBJ_IS_NOT_CHECKING @J_IS_NOT_CHECKING-OBJ_MAGICANT_FLYINGMANGRAVE1
OBJ_DIALOGUE UMSG::MAGICANT_FLYINGMANGRAVE1
	@J_IS_NOT_CHECKING:
OBJ_STOP

OBJ_MAGICANT_FLYINGMANGRAVE2:
objectDef 29, 719, DIRECTIONS::UP, 595
.addr SPRITEDEF_GRAVESTONE
OBJ_FLAG_APPEAR 106
OBJ_IS_NOT_CHECKING @J_IS_NOT_CHECKING-OBJ_MAGICANT_FLYINGMANGRAVE2
OBJ_DIALOGUE UMSG::MAGICANT_FLYINGMANGRAVE2
	@J_IS_NOT_CHECKING:
OBJ_STOP

OBJ_MAGICANT_FLYINGMANGRAVE3:
objectDef 29, 721, DIRECTIONS::UP, 594
.addr SPRITEDEF_GRAVESTONE
OBJ_FLAG_APPEAR 107
OBJ_IS_NOT_CHECKING @J_IS_NOT_CHECKING-OBJ_MAGICANT_FLYINGMANGRAVE3
OBJ_DIALOGUE UMSG::MAGICANT_FLYINGMANGRAVE3
	@J_IS_NOT_CHECKING:
OBJ_STOP

OBJ_MAGICANT_FLYINGMANGRAVE4:
objectDef 29, 723, DIRECTIONS::UP, 595
.addr SPRITEDEF_GRAVESTONE
OBJ_FLAG_APPEAR 108
OBJ_IS_NOT_CHECKING @J_IS_NOT_CHECKING-OBJ_MAGICANT_FLYINGMANGRAVE4
OBJ_DIALOGUE UMSG::MAGICANT_FLYINGMANGRAVE4
	@J_IS_NOT_CHECKING:
OBJ_STOP

OBJ_MAGICANT_REDWEED:
objectDef 24, 657, DIRECTIONS::UP, 637
OBJ_SUBROUTINE OBJ_MAGICANT_REDWEED, OBJ_MAGICANT_REDWEEDSUBR-OBJ_MAGICANT_REDWEED
OBJ_STOP

OBJ_MAGICANT_REDWEEDSUBR:
OBJ_IS_NOT_CHECKING @J_IS_NOT_CHECKING-OBJ_MAGICANT_REDWEED
OBJ_PICK_ITEM 111
OBJ_DIALOGUE UMSG::PRESENT_ITEM
OBJ_NOT_HAS_ITEM 0, @J_NOT_HAS_ITEM-OBJ_MAGICANT_REDWEED
OBJ_PICK_ITEM 111
OBJ_GIVE_ITEM @J_NOT_HAS_ITEM-OBJ_MAGICANT_REDWEED
OBJ_DIALOGUE UMSG::GET_ITEM
OBJ_PLAY_SOUND 6
OBJ_RETURN
	@J_NOT_HAS_ITEM:
OBJ_DIALOGUE UMSG::INVENTORY_FULL
	@J_IS_NOT_CHECKING:
OBJ_RETURN

OBJ_MAGICANT_REDWEED2:
objectDef 24, 693, DIRECTIONS::UP, 633
OBJ_SUBROUTINE OBJ_MAGICANT_REDWEED, OBJ_MAGICANT_REDWEEDSUBR-OBJ_MAGICANT_REDWEED
OBJ_STOP

OBJ_MAGICANT_REDWEED3:
objectDef 24, 698, DIRECTIONS::UP, 638
OBJ_SUBROUTINE OBJ_MAGICANT_REDWEED, OBJ_MAGICANT_REDWEEDSUBR-OBJ_MAGICANT_REDWEED
OBJ_STOP

OBJ_MAGICANT_GUARD3:
objectDef OBJ_TYPE::STATIONARY_NPC, 685, DIRECTIONS::DOWN, 628
.addr SPRITEDEF_MAGICANT_GUARD
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_MAGICANT_GUARD3
OBJ_DIALOGUE UMSG::CANARY_GENERIC
OBJ_STOP
	@J_IS_NOT_TALKING:
OBJ_IS_SIGNAL @J_IS_SIGNAL-OBJ_MAGICANT_GUARD3
OBJ_MOVE @MOVE_DATA
	@J_IS_SIGNAL:
OBJ_STOP

@MOVE_DATA:
moveDef DIRECTIONS::DOWN, MOVE_CMD::ABOUTFACE, 1
OBJ_STOP

OBJ_MAGICANT_GUARD2:
objectDef OBJ_TYPE::STATIONARY_NPC, 687, DIRECTIONS::DOWN, 628
.addr SPRITEDEF_MAGICANT_GUARD
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_MAGICANT_GUARD2
OBJ_DIALOGUE UMSG::CANARY_GENERIC
OBJ_STOP
	@J_IS_NOT_TALKING:
OBJ_IS_SIGNAL @J_IS_SIGNAL-OBJ_MAGICANT_GUARD2
OBJ_SIGNAL 21
OBJ_MOVE @MOVE_DATA
	@J_IS_SIGNAL:
OBJ_STOP

@MOVE_DATA:
moveDef DIRECTIONS::DOWN, MOVE_CMD::ABOUTFACE, 1
moveDef DIRECTIONS::LEFT, MOVE_CMD::MOVE, 4
OBJ_STOP

OBJ_MAGICANT_GUARD1:
objectDef OBJ_TYPE::STATIONARY_NPC, 686, DIRECTIONS::DOWN, 628
.addr SPRITEDEF_MAGICANT_GUARD
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_MAGICANT_GUARD1
OBJ_IS_NOT_FLAG 76, @J_IS_NOT_FLAG-OBJ_MAGICANT_GUARD1
OBJ_DIALOGUE UMSG::MAGICANT_GUARD_BYE
OBJ_HAS_MOVED @J_HAS_MOVED-OBJ_MAGICANT_GUARD1
	@J_JUMP:
OBJ_SIGNAL 22
OBJ_MOVE @MOVE_DATA
OBJ_STOP
	@J_IS_NOT_FLAG:
OBJ_DIALOGUE UMSG::MAGICANT_GUARD1
OBJ_SET_FLAG 75
OBJ_STOP
	@J_IS_NOT_TALKING:
OBJ_IS_NOT_CASTING 1, @J_HAS_MOVED-OBJ_MAGICANT_GUARD1
OBJ_IS_NOT_FLAG 75, @J_HAS_MOVED-OBJ_MAGICANT_GUARD1
OBJ_IS_NOT_FLAG 76, @J_IS_NOT_FLAG1-OBJ_MAGICANT_GUARD1
OBJ_JUMP @J_HAS_MOVED-OBJ_MAGICANT_GUARD1
	@J_IS_NOT_FLAG1:
OBJ_DIALOGUE UMSG::MAGICANT_GUARD2
OBJ_SET_FLAG 76
OBJ_JUMP @J_JUMP-OBJ_MAGICANT_GUARD1
	@J_HAS_MOVED:
OBJ_STOP

@MOVE_DATA:
moveDef DIRECTIONS::DOWN, MOVE_CMD::ABOUTFACE, 2
moveDef DIRECTIONS::LEFT, MOVE_CMD::MOVE, 2
OBJ_STOP
