OBJ_BANK_3D:
.addr OBJ_MAGICANT_CASTLEEXIT
.addr OBJ_MAGICANT_CASTLEDOOR1
.addr OBJ_MAGICANT_CASTLEDOOR2
.addr OBJ_MAGICANT_CASTLEDOOR3
.addr OBJ_MAGICANT_CASTLEDOOR4
.addr OBJ_MAGICANT_CASTLEDOOR5
.addr OBJ_MAGICANT_CASTLEDOOR6
.addr OBJ_MAGICANT_CASTLEDOOR7
.addr OBJ_MAGICANT_CASTLEDOOR8
.addr OBJ_MAGICANT_CASTLEDOOR9
.addr OBJ_MAGICANT_CASTLEDOOR10
.addr OBJ_MAGICANT_CASTLEDOOR11
.addr OBJ_MAGICANT_CASTLEDOOR12
.addr OBJ_MAGICANT_CASTLEDOOR13
.addr OBJ_MAGICANT_CASTLEDOOR14
.addr OBJ_MAGICANT_CASTLEDOOR15
.addr OBJ_MAGICANT_CASTLEDOOR16
.addr OBJ_MAGICANT_CASTLEDOOR17
.addr OBJ_MAGICANT_CASTLEDOOR18
.addr OBJ_MAGICANT_MARIA
.addr OBJ_MAGICANT_MARIAFADE
.addr OBJ_MAGICANT_NIGHTMAREGUY
.addr OBJ_MAGICANT_LOVEGUY
.addr OBJ_MAGICANT_QUEENGUY
.addr OBJ_MAGICANT_SICKNESSGUY
.addr OBJ_MAGICANT_CASTLEPRESENT1
.addr OBJ_MAGICANT_CASTLEPRESENT2
.addr OBJ_MAGICANT_CASTLEPRESENT3
.addr OBJ_MAGICANT_CASTLEPRESENT4
.addr OBJ_MAGICANT_CASTLEPRESENT5
.addr OBJ_MAGICANT_CASTLEPRESENT6
.addr OBJ_MAGICANT_CASTLEPRESENT7
.addr OBJ_MAGICANT_CASTLEPRESENT8
.addr OBJ_MAGICANT_CASTLEPRESENT9
.addr OBJ_MAGICANT_CASTLEPRESENT10
.addr OBJ_MAGICANT_CASTLEPRESENT11
.addr OBJ_MAGICANT_CASTLEPRESENT12
.addr OBJ_MAGICANT_CASTLEPRESENT13
.addr 0

OBJ_MAGICANT_CASTLEEXIT:
objectDef OBJ_TYPE::DOOR, 37, DIRECTIONS::RIGHT, 549
doorArgDef 9, 692, DIRECTIONS::DOWN, 619

OBJ_MAGICANT_CASTLEDOOR1:
objectDef OBJ_TYPE::DOOR, 21, DIRECTIONS::UP, 547
doorArgDef 0, 124, DIRECTIONS::LEFT, 581

OBJ_MAGICANT_CASTLEDOOR2:
objectDef OBJ_TYPE::DOOR, 125, DIRECTIONS::RIGHT, 581
doorArgDef 0, 21, DIRECTIONS::DOWN, 548

OBJ_MAGICANT_CASTLEDOOR3:
objectDef OBJ_TYPE::DOOR, 119, DIRECTIONS::UP, 579
doorArgDef 0, 92, DIRECTIONS::LEFT, 581

OBJ_MAGICANT_CASTLEDOOR4:
objectDef OBJ_TYPE::DOOR, 93, DIRECTIONS::RIGHT, 581
doorArgDef 0, 119, DIRECTIONS::DOWN, 580

OBJ_MAGICANT_CASTLEDOOR5:
objectDef OBJ_TYPE::DOOR, 9, DIRECTIONS::UP, 547
doorArgDef 0, 20, DIRECTIONS::LEFT, 581

OBJ_MAGICANT_CASTLEDOOR6:
objectDef OBJ_TYPE::DOOR, 21, DIRECTIONS::RIGHT, 581
doorArgDef 0, 9, DIRECTIONS::DOWN, 548

OBJ_MAGICANT_CASTLEDOOR7:
objectDef OBJ_TYPE::DOOR, 13, DIRECTIONS::UP, 579
doorArgDef 0, 84, DIRECTIONS::LEFT, 549

OBJ_MAGICANT_CASTLEDOOR8:
objectDef OBJ_TYPE::DOOR, 85, DIRECTIONS::RIGHT, 549
doorArgDef 0, 13, DIRECTIONS::DOWN, 580

OBJ_MAGICANT_CASTLEDOOR9:
objectDef OBJ_TYPE::DOOR, 9, DIRECTIONS::UP, 579
doorArgDef 0, 124, DIRECTIONS::LEFT, 549

OBJ_MAGICANT_CASTLEDOOR10:
objectDef OBJ_TYPE::DOOR, 125, DIRECTIONS::RIGHT, 549
doorArgDef 0, 9, DIRECTIONS::DOWN, 580

OBJ_MAGICANT_CASTLEDOOR11:
objectDef OBJ_TYPE::DOOR, 117, DIRECTIONS::UP, 547
doorArgDef 0, 76, DIRECTIONS::LEFT, 613

OBJ_MAGICANT_CASTLEDOOR12:
objectDef OBJ_TYPE::DOOR, 77, DIRECTIONS::RIGHT, 613
doorArgDef 0, 117, DIRECTIONS::DOWN, 548

OBJ_MAGICANT_CASTLEDOOR13:
objectDef OBJ_TYPE::DOOR, 113, DIRECTIONS::UP, 547
doorArgDef 0, 12, DIRECTIONS::LEFT, 613

OBJ_MAGICANT_CASTLEDOOR14:
objectDef OBJ_TYPE::DOOR, 13, DIRECTIONS::RIGHT, 613
doorArgDef 0, 113, DIRECTIONS::DOWN, 548

OBJ_MAGICANT_CASTLEDOOR15:
objectDef OBJ_TYPE::DOOR, 109, DIRECTIONS::UP, 547
doorArgDef 0, 60, DIRECTIONS::LEFT, 581

OBJ_MAGICANT_CASTLEDOOR16:
objectDef OBJ_TYPE::DOOR, 61, DIRECTIONS::RIGHT, 581
doorArgDef 0, 109, DIRECTIONS::DOWN, 548

OBJ_MAGICANT_CASTLEDOOR17:
objectDef OBJ_TYPE::DOOR, 7, DIRECTIONS::UP, 611
doorArgDef 0, 44, DIRECTIONS::LEFT, 613

OBJ_MAGICANT_CASTLEDOOR18:
objectDef OBJ_TYPE::DOOR, 45, DIRECTIONS::RIGHT, 613
doorArgDef 0, 7, DIRECTIONS::DOWN, 612

OBJ_MAGICANT_MARIA:
objectDef OBJ_TYPE::STATIONARY_NPC, 58, DIRECTIONS::RIGHT, 549
.addr SPRITEDEF_MARIA
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_MAGICANT_MARIA
OBJ_INCOMPLETE_MELODIES @J_INCOMPLETE_MELODIES-OBJ_MAGICANT_MARIA
OBJ_DIALOGUE UMSG::MAGICANT_MARIA1
OBJ_PICK_CHARACTER 1
OBJ_AND_STATUS 0
	@J_NOT_MAX_PP:
OBJ_PPHEAL 255
OBJ_NOT_MAX_PP @J_NOT_MAX_PP-OBJ_MAGICANT_MARIA
OBJ_PICK_CHARACTER_J 1, @J_PICK_CHARACTER_J-OBJ_MAGICANT_MARIA
OBJ_AND_STATUS 0
	@J_NOT_MAX_PP1:
OBJ_PPHEAL 255
OBJ_NOT_MAX_PP @J_NOT_MAX_PP1-OBJ_MAGICANT_MARIA
OBJ_PICK_CHARACTER_J 2, @J_PICK_CHARACTER_J-OBJ_MAGICANT_MARIA
OBJ_AND_STATUS 0
	@J_NOT_MAX_PP2:
OBJ_PPHEAL 255
OBJ_NOT_MAX_PP @J_NOT_MAX_PP2-OBJ_MAGICANT_MARIA
	@J_PICK_CHARACTER_J:
OBJ_PLAY_MUSIC 1
OBJ_DELAY 250
OBJ_DELAY 250
OBJ_DELAY 250
OBJ_DELAY 250
OBJ_DELAY 250
OBJ_DELAY 190
OBJ_DELAY 90
OBJ_DIALOGUE UMSG::MAGICANT_MARIA2
OBJ_DELAY 90
OBJ_PLAY_MUSIC 25
OBJ_DELAY 250
OBJ_DELAY 250
OBJ_DELAY 250
OBJ_DELAY 250
OBJ_DELAY 250
OBJ_DELAY 190
OBJ_DELAY 90
OBJ_DIALOGUE UMSG::MAGICANT_MARIA3
OBJ_DARKEN
OBJ_DIALOGUE UMSG::MAGICANT_MARIA4
OBJ_DARKEN
OBJ_DIALOGUE UMSG::MAGICANT_MARIA5
OBJ_DARKEN
OBJ_DIALOGUE UMSG::MAGICANT_MARIA6
OBJ_DARKEN
OBJ_MOVE @MOVE_DATA
OBJ_TELEPORT 0, 1015, DIRECTIONS::LEFT, 504
OBJ_SET_FADE 6
OBJ_STOP
	@J_INCOMPLETE_MELODIES:
OBJ_DIALOGUE UMSG::MAGICANT_MARIA
	@J_IS_NOT_TALKING:
OBJ_STOP

@MOVE_DATA:
moveDef DIRECTIONS::LEFT, 10, 5
moveDef DIRECTIONS::LEFT, 2, 5
OBJ_RETURN

OBJ_MAGICANT_MARIAFADE:
objectDef OBJ_TYPE::STATIONARY_NPC, 1014, DIRECTIONS::UP, 504
.addr SPRITEDEF_MARIA_FADE
OBJ_IS_NOT_TOUCHING @J_IS_NOT_TOUCHING-OBJ_MAGICANT_MARIAFADE
OBJ_REMOVE_CHARACTER 7, @J_REMOVE_CHARACTER-OBJ_MAGICANT_MARIAFADE
	@J_REMOVE_CHARACTER:
OBJ_MOVE @MOVE_DATA
OBJ_DELAY 80
OBJ_DIALOGUE UMSG::MAGICANT_MARIAFADE
OBJ_PLAY_MUSIC 9
OBJ_DELAY 150
OBJ_SET_FLAG 224
OBJ_TELEPORT 11, 905, DIRECTIONS::UP, 595
OBJ_SET_FADE 6
OBJ_UNK
OBJ_WRITE_SAVEMETA 27, 123
	@J_IS_NOT_TOUCHING:
OBJ_STOP

@MOVE_DATA:
moveDef DIRECTIONS::UP, MOVE_CMD::ABOUTFACE, 1
moveDef DIRECTIONS::RIGHT, MOVE_CMD::ABOUTFACE, 1
moveDef DIRECTIONS::UP, MOVE_CMD::ABOUTFACE, 1
moveDef DIRECTIONS::RIGHT, MOVE_CMD::ABOUTFACE, 1
moveDef DIRECTIONS::DOWN, MOVE_CMD::ABOUTFACE, 1
moveDef DIRECTIONS::RIGHT, MOVE_CMD::ABOUTFACE, 1
moveDef DIRECTIONS::DOWN, MOVE_CMD::ABOUTFACE, 1
moveDef DIRECTIONS::LEFT, MOVE_CMD::ABOUTFACE, 1
moveDef DIRECTIONS::DOWN, MOVE_CMD::ABOUTFACE, 1
moveDef DIRECTIONS::LEFT, MOVE_CMD::ABOUTFACE, 1
moveDef DIRECTIONS::UP, 10, 1
OBJ_STOP

OBJ_MAGICANT_NIGHTMAREGUY:
objectDef OBJ_TYPE::WANDERING_NPC, 117, DIRECTIONS::RIGHT, 581
.addr SPRITEDEF_BAG_MAN
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_MAGICANT_NIGHTMAREGUY
OBJ_DIALOGUE UMSG::MAGICANT_NIGHTMAREGUY
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_MAGICANT_LOVEGUY:
objectDef OBJ_TYPE::STATIONARY_NPC, 57, DIRECTIONS::RIGHT, 551
.addr SPRITEDEF_BAG_MAN_RED
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_MAGICANT_LOVEGUY
OBJ_NOT_HAS_ITEM 107, @J_NOT_HAS_ITEM-OBJ_MAGICANT_LOVEGUY
OBJ_DIALOGUE UMSG::MAGICANT_LOVEGUY
OBJ_STOP
	@J_NOT_HAS_ITEM:
OBJ_DIALOGUE UMSG::MAGICANT_LOVEGUY_ONYXHOOK
OBJ_DIALOGUE UMSG::MAGICANT_LOVEGUY
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_MAGICANT_QUEENGUY:
objectDef OBJ_TYPE::WANDERING_NPC, 120, DIRECTIONS::RIGHT, 582
.addr SPRITEDEF_BAG_MAN
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_MAGICANT_QUEENGUY
OBJ_DIALOGUE UMSG::MAGICANT_QUEENGUY
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_MAGICANT_SICKNESSGUY:
objectDef OBJ_TYPE::STATIONARY_NPC, 81, DIRECTIONS::DOWN, 548
.addr SPRITEDEF_BAG_MAN_RED
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_MAGICANT_SICKNESSGUY
OBJ_DIALOGUE UMSG::MAGICANT_SICKNESSGUY
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_MAGICANT_CASTLEPRESENT1:
objectDef OBJ_TYPE::PRESENT, 38, DIRECTIONS::UP, 612
.addr SPRITEDEF_PRESENT
.byte 112 ; item
.byte 39 ; flag

OBJ_MAGICANT_CASTLEPRESENT2:
objectDef OBJ_TYPE::PRESENT, 36, DIRECTIONS::UP, 614
.addr SPRITEDEF_PRESENT
.byte 67 ; item
.byte 40 ; flag

OBJ_MAGICANT_CASTLEPRESENT3:
objectDef OBJ_TYPE::PRESENT, 40, DIRECTIONS::UP, 612
.addr SPRITEDEF_PRESENT
.byte 62 ; item
.byte 41 ; flag

OBJ_MAGICANT_CASTLEPRESENT4:
objectDef OBJ_TYPE::PRESENT, 40, DIRECTIONS::UP, 614
.addr SPRITEDEF_PRESENT
.byte 0 ; item
.byte 42 ; flag

OBJ_MAGICANT_CASTLEPRESENT5:
objectDef OBJ_TYPE::PRESENT, 69, DIRECTIONS::UP, 612
.addr SPRITEDEF_PRESENT
.byte 31 ; item
.byte 43 ; flag

OBJ_MAGICANT_CASTLEPRESENT6:
objectDef OBJ_TYPE::PRESENT, 71, DIRECTIONS::UP, 612
.addr SPRITEDEF_PRESENT
.byte 67 ; item
.byte 44 ; flag

OBJ_MAGICANT_CASTLEPRESENT7:
objectDef OBJ_TYPE::PRESENT, 73, DIRECTIONS::UP, 612
.addr SPRITEDEF_PRESENT
.byte 62 ; item
.byte 45 ; flag

OBJ_MAGICANT_CASTLEPRESENT8:
objectDef OBJ_TYPE::PRESENT, 54, DIRECTIONS::UP, 580
.addr SPRITEDEF_PRESENT
.byte 24 ; item
.byte 73 ; flag

OBJ_MAGICANT_CASTLEPRESENT9:
objectDef OBJ_TYPE::PRESENT, 55, DIRECTIONS::UP, 580
.addr SPRITEDEF_PRESENT
.byte 73 ; item
.byte 73 ; flag

OBJ_MAGICANT_CASTLEPRESENT10:
objectDef OBJ_TYPE::PRESENT, 56, DIRECTIONS::UP, 580
.addr SPRITEDEF_PRESENT
.byte 82 ; item
.byte 73 ; flag

OBJ_MAGICANT_CASTLEPRESENT11:
objectDef OBJ_TYPE::PRESENT, 54, DIRECTIONS::UP, 583
.addr SPRITEDEF_PRESENT
.byte 40 ; item
.byte 73 ; flag

OBJ_MAGICANT_CASTLEPRESENT12:
objectDef OBJ_TYPE::PRESENT, 55, DIRECTIONS::UP, 583
.addr SPRITEDEF_PRESENT
.byte 109 ; item
.byte 73 ; flag

OBJ_MAGICANT_CASTLEPRESENT13:
objectDef OBJ_TYPE::PRESENT, 56, DIRECTIONS::UP, 583
.addr SPRITEDEF_PRESENT
.byte 69 ; item
.byte 73 ; flag

