OBJ_BANK_3C:
.addr OBJ_MAGICANT_HOUSE1EXIT
.addr OBJ_MAGICANT_HOUSE2EXIT
.addr OBJ_MAGICANT_HOUSE3EXIT
.addr OBJ_MAGICANT_HOUSE4EXIT
.addr OBJ_MAGICANT_HOUSE5EXIT
.addr OBJ_MAGICANT_HOUSE6EXIT
.addr OBJ_MAGICANT_OCARINAHOUSEEXIT
.addr OBJ_MAGICANT_HOUSE7EXIT
.addr OBJ_MAGICANT_HOUSE8EXIT
.addr OBJ_MAGICANT_CLOSETHOUSEEXIT
.addr OBJ_MAGICANT_PHONEHOUSEEXIT
.addr OBJ_MAGICANT_HOUSE9EXIT
.addr OBJ_MAGICANT_HOUSE10EXIT
.addr OBJ_MAGICANT_BIGBAGHOUSEEXIT
.addr OBJ_MAGICANT_NOEXITBOY
.addr OBJ_MAGICANT_CANNOTPARTMAN
.addr OBJ_MAGICANT_NICKNAMEMAN
.addr OBJ_MAGICANT_STRANGERBOY
.addr OBJ_MAGICANT_PHILOSOPHYMAN
.addr OBJ_MAGICANT_INNBOY
.addr OBJ_MAGICANT_OCARINAMAN
.addr OBJ_MAGICANT_FOUNTAINMAN
.addr OBJ_MAGICANT_CLOTHINGMAN
.addr OBJ_MAGICANT_HOLEGIRL
.addr OBJ_MAGICANT_MIMICKER
.addr OBJ_MAGICANT_EARRINGGIRL
.addr OBJ_MAGICANT_REDWEEDGIRL
.addr OBJ_MAGICANT_BIGBAGGUY
.addr OBJ_MAGICANT_OUTSIDEMAN
.addr OBJ_MAGICANT_GOODSKEEPER
.addr 0

OBJ_MAGICANT_HOUSE1EXIT:
objectDef OBJ_TYPE::DOOR, 14, DIRECTIONS::RIGHT, 598
doorArgDef 0, 638, DIRECTIONS::DOWN, 668

OBJ_MAGICANT_HOUSE2EXIT:
objectDef OBJ_TYPE::DOOR, 46, DIRECTIONS::RIGHT, 598
doorArgDef 0, 642, DIRECTIONS::DOWN, 668

OBJ_MAGICANT_HOUSE3EXIT:
objectDef OBJ_TYPE::DOOR, 78, DIRECTIONS::RIGHT, 598
doorArgDef 0, 646, DIRECTIONS::DOWN, 668

OBJ_MAGICANT_HOUSE4EXIT:
objectDef OBJ_TYPE::DOOR, 110, DIRECTIONS::RIGHT, 598
doorArgDef 0, 654, DIRECTIONS::DOWN, 668

OBJ_MAGICANT_HOUSE5EXIT:
objectDef OBJ_TYPE::DOOR, 14, DIRECTIONS::RIGHT, 630
doorArgDef 0, 658, DIRECTIONS::DOWN, 668

OBJ_MAGICANT_HOUSE6EXIT:
objectDef OBJ_TYPE::DOOR, 46, DIRECTIONS::RIGHT, 630
doorArgDef 0, 662, DIRECTIONS::DOWN, 668

OBJ_MAGICANT_OCARINAHOUSEEXIT:
objectDef OBJ_TYPE::DOOR, 78, DIRECTIONS::RIGHT, 630
doorArgDef 0, 654, DIRECTIONS::DOWN, 676

OBJ_MAGICANT_HOUSE7EXIT:
objectDef OBJ_TYPE::DOOR, 110, DIRECTIONS::RIGHT, 630
doorArgDef 0, 630, DIRECTIONS::DOWN, 676

OBJ_MAGICANT_HOUSE8EXIT:
objectDef OBJ_TYPE::DOOR, 30, DIRECTIONS::RIGHT, 534
doorArgDef 0, 626, DIRECTIONS::DOWN, 680

OBJ_MAGICANT_CLOSETHOUSEEXIT:
objectDef OBJ_TYPE::DOOR, 62, DIRECTIONS::RIGHT, 534
doorArgDef 0, 622, DIRECTIONS::DOWN, 684

OBJ_MAGICANT_PHONEHOUSEEXIT:
objectDef OBJ_TYPE::DOOR, 94, DIRECTIONS::RIGHT, 534
doorArgDef 0, 618, DIRECTIONS::DOWN, 688

OBJ_MAGICANT_HOUSE9EXIT:
objectDef OBJ_TYPE::DOOR, 126, DIRECTIONS::RIGHT, 534
doorArgDef 0, 626, DIRECTIONS::DOWN, 688

OBJ_MAGICANT_HOUSE10EXIT:
objectDef OBJ_TYPE::DOOR, 30, DIRECTIONS::RIGHT, 566
doorArgDef 0, 630, DIRECTIONS::DOWN, 688

OBJ_MAGICANT_BIGBAGHOUSEEXIT:
objectDef OBJ_TYPE::DOOR, 62, DIRECTIONS::RIGHT, 566
doorArgDef 0, 614, DIRECTIONS::DOWN, 692

OBJ_MAGICANT_NOEXITBOY:
objectDef OBJ_TYPE::WANDERING_NPC, 9, DIRECTIONS::DOWN, 599
.addr SPRITEDEF_MAGICANTIAN_BOY
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_MAGICANT_NOEXITBOY
OBJ_DIALOGUE UMSG::MAGICANT_NOEXITBOY
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_MAGICANT_CANNOTPARTMAN:
objectDef OBJ_TYPE::WANDERING_NPC, 41, DIRECTIONS::DOWN, 596
.addr SPRITEDEF_MAGICANTIAN_ADULT_BLUE
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_MAGICANT_CANNOTPARTMAN
OBJ_DIALOGUE UMSG::MAGICANT_CANNOTPARTMAN
OBJ_YESNO_IS_NO @J_YESNO_IS_NO-OBJ_MAGICANT_CANNOTPARTMAN
OBJ_DIALOGUE UMSG::MAGICANT_CANNOTPARTMAN_YES
OBJ_STOP
	@J_YESNO_IS_NO:
OBJ_DIALOGUE UMSG::MAGICANT_CANNOTPARTMAN_NO
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_MAGICANT_NICKNAMEMAN:
objectDef OBJ_TYPE::WANDERING_NPC, 72, DIRECTIONS::DOWN, 596
.addr SPRITEDEF_MAGICANTIAN_ADULT
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_MAGICANT_NICKNAMEMAN
OBJ_IS_NOT_FLAG 78, @J_IS_NOT_FLAG-OBJ_MAGICANT_NICKNAMEMAN
OBJ_DIALOGUE UMSG::MAGICANT_NICKNAMEMAN_QUEST
OBJ_STOP
	@J_IS_NOT_FLAG:
OBJ_IS_NOT_FLAG 79, @J_IS_NOT_FLAG1-OBJ_MAGICANT_NICKNAMEMAN
OBJ_DIALOGUE UMSG::MAGICANT_NICKNAMEMAN_AFTER
OBJ_YESNO_IS_NO @J_YESNO_IS_NO-OBJ_MAGICANT_NICKNAMEMAN
OBJ_DIALOGUE UMSG::MAGICANT_NICKNAMEMAN_AFTER_YES
OBJ_SET_FLAG 78
OBJ_STOP
	@J_YESNO_IS_NO:
OBJ_DIALOGUE UMSG::TRAIN_DECLINE
OBJ_STOP
	@J_IS_NOT_FLAG1:
OBJ_DIALOGUE UMSG::MAGICANT_NICKNAMEMAN
OBJ_YESNO_IS_NO @J_YESNO_IS_NO1-OBJ_MAGICANT_NICKNAMEMAN
OBJ_DIALOGUE UMSG::MAGICANT_NICKNAMEMAN_YES
OBJ_JUMP @J_JUMP-OBJ_MAGICANT_NICKNAMEMAN
	@J_YESNO_IS_NO1:
OBJ_DIALOGUE UMSG::MAGICANT_NICKNAMEMAN_NO
	@J_JUMP:
OBJ_SET_FLAG 80
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_MAGICANT_STRANGERBOY:
objectDef OBJ_TYPE::WANDERING_NPC, 105, DIRECTIONS::DOWN, 597
.addr SPRITEDEF_MAGICANTIAN_BOY_RB
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_MAGICANT_STRANGERBOY
OBJ_DIALOGUE UMSG::MAGICANT_STRANGERBOY
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_MAGICANT_PHILOSOPHYMAN:
objectDef OBJ_TYPE::WANDERING_NPC, 8, DIRECTIONS::DOWN, 631
.addr SPRITEDEF_MAGICANTIAN_ADULT_BLUE
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_MAGICANT_PHILOSOPHYMAN
OBJ_DIALOGUE UMSG::MAGICANT_PHILOSOPHYMAN
OBJ_YESNO_IS_NO @J_YESNO_IS_NO-OBJ_MAGICANT_PHILOSOPHYMAN
OBJ_IS_NOT_FLAG 80, @J_IS_NOT_FLAG-OBJ_MAGICANT_PHILOSOPHYMAN
OBJ_DIALOGUE UMSG::MAGICANT_PHILOSOPHYMAN_YES
OBJ_SET_FLAG 79
OBJ_STOP
	@J_IS_NOT_FLAG:
OBJ_DIALOGUE UMSG::MAGICANT_PHILOSOPHYMAN_YESFLAG
OBJ_STOP
	@J_YESNO_IS_NO:
OBJ_DIALOGUE UMSG::MAGICANT_PHILOSOPHYMAN_NO
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_MAGICANT_INNBOY:
objectDef OBJ_TYPE::WANDERING_NPC, 39, DIRECTIONS::DOWN, 630
.addr SPRITEDEF_MAGICANTIAN_BOY
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_MAGICANT_INNBOY
OBJ_IS_NOT_FLAG 96, @J_IS_NOT_FLAG-OBJ_MAGICANT_INNBOY
OBJ_DIALOGUE UMSG::MAGICANT_INNBOY_AGAIN
OBJ_YESNO_IS_NO @J_YESNO_IS_NO-OBJ_MAGICANT_INNBOY
OBJ_SLEEP
OBJ_DIALOGUE UMSG::MAGICANT_INNBOY_GOODBYE
OBJ_STOP
	@J_YESNO_IS_NO:
OBJ_DIALOGUE UMSG::MAGICANT_INNBOY_AGAINNO
OBJ_STOP
	@J_IS_NOT_FLAG:
OBJ_DIALOGUE UMSG::MAGICANT_INNBOY
OBJ_YESNO_IS_NO @J_YESNO_IS_NO1-OBJ_MAGICANT_INNBOY
OBJ_DIALOGUE UMSG::MAGICANT_INNBOY_YES
OBJ_YESNO_IS_NO @J_YESNO_IS_NO2-OBJ_MAGICANT_INNBOY
OBJ_DIALOGUE UMSG::MAGICANT_INNBOY_STAY
OBJ_SLEEP
OBJ_DIALOGUE UMSG::MAGICANT_INNBOY_GOODBYE2
OBJ_SET_FLAG 96
OBJ_STOP
	@J_YESNO_IS_NO2:
OBJ_DIALOGUE UMSG::MAGICANT_INNBOY_NOSTAY
OBJ_STOP
	@J_YESNO_IS_NO1:
OBJ_DIALOGUE UMSG::MAGICANT_INNBOY_NO
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_MAGICANT_OCARINAMAN:
objectDef OBJ_TYPE::WANDERING_NPC, 75, DIRECTIONS::DOWN, 631
.addr SPRITEDEF_MAGICANTIAN_ADULT_BLUE
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_MAGICANT_OCARINAMAN
OBJ_IS_NOT_FLAG 81, @J_IS_NOT_FLAG-OBJ_MAGICANT_OCARINAMAN
OBJ_DIALOGUE UMSG::MAGICANT_OCARINAMAN_AFTER
OBJ_STOP
	@J_IS_NOT_FLAG:
OBJ_DIALOGUE UMSG::MAGICANT_OCARINAMAN
OBJ_YESNO_IS_NO @J_YESNO_IS_NO-OBJ_MAGICANT_OCARINAMAN
OBJ_DIALOGUE UMSG::MAGICANT_OCARINAMAN_YES
OBJ_JUMP @J_JUMP-OBJ_MAGICANT_OCARINAMAN
	@J_YESNO_IS_NO:
OBJ_DIALOGUE UMSG::MAGICANT_OCARINAMAN_NO
	@J_JUMP:
OBJ_NOT_HAS_ITEM 0, @J_NOT_HAS_ITEM-OBJ_MAGICANT_OCARINAMAN
OBJ_PLAY_SOUND 6
OBJ_PICK_ITEM 102
OBJ_GIVE_ITEM @J_IS_NOT_TALKING-OBJ_MAGICANT_OCARINAMAN
OBJ_SET_FLAG 81
OBJ_STOP
	@J_NOT_HAS_ITEM:
OBJ_DIALOGUE UMSG::PETVENDOR_NOCARRY
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_MAGICANT_FOUNTAINMAN:
objectDef OBJ_TYPE::WANDERING_NPC, 104, DIRECTIONS::DOWN, 629
.addr SPRITEDEF_MAGICANTIAN_ADULT
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_MAGICANT_FOUNTAINMAN
OBJ_DIALOGUE UMSG::MAGICANT_FOUNTAINMAN
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_MAGICANT_CLOTHINGMAN:
objectDef OBJ_TYPE::WANDERING_NPC, 25, DIRECTIONS::DOWN, 534
.addr SPRITEDEF_MAGICANTIAN_ADULT_BLUE
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_MAGICANT_CLOTHINGMAN
OBJ_DIALOGUE UMSG::MAGICANT_CLOTHINGMAN
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_MAGICANT_HOLEGIRL:
objectDef OBJ_TYPE::WANDERING_NPC, 22, DIRECTIONS::RIGHT, 533
.addr SPRITEDEF_MAGICANTIAN_GIRL_PINK
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_MAGICANT_HOLEGIRL
OBJ_DIALOGUE UMSG::MAGICANT_HOLEGIRL
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_MAGICANT_MIMICKER:
objectDef OBJ_TYPE::STATIONARY_NPC, 91, DIRECTIONS::DOWN, 532
.addr SPRITEDEF_MAGICANTIAN_ADULT
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_MAGICANT_MIMICKER
OBJ_DIALOGUE UMSG::MAGICANT_MIMICKER
OBJ_NO_NEW_MONEY @J_NO_NEW_MONEY-OBJ_MAGICANT_MIMICKER
OBJ_DIALOGUE UMSG::PHONE_NEWMONEY
	@J_NO_NEW_MONEY:
OBJ_DIALOGUE UMSG::PHONE_NEXTLVL
OBJ_PICK_CHARACTER_J 0, @J_PICK_CHARACTER_J-OBJ_MAGICANT_MIMICKER
OBJ_NOT_CHARACTER_SELECTED 7, @J_NOT_CHARACTER_SELECTED-OBJ_MAGICANT_MIMICKER
OBJ_JUMP @J_JUMP-OBJ_MAGICANT_MIMICKER
	@J_NOT_CHARACTER_SELECTED:
OBJ_GET_NEXT_EXP
OBJ_DIALOGUE UMSG::PHONE_EXPLVL
	@J_JUMP:
OBJ_PICK_CHARACTER_J 1, @J_PICK_CHARACTER_J-OBJ_MAGICANT_MIMICKER
OBJ_NOT_CHARACTER_SELECTED 7, @J_NOT_CHARACTER_SELECTED1-OBJ_MAGICANT_MIMICKER
OBJ_JUMP @J_JUMP1-OBJ_MAGICANT_MIMICKER
	@J_NOT_CHARACTER_SELECTED1:
OBJ_GET_NEXT_EXP
OBJ_DIALOGUE UMSG::PHONE_EXPLVL
	@J_JUMP1:
OBJ_PICK_CHARACTER_J 2, @J_PICK_CHARACTER_J-OBJ_MAGICANT_MIMICKER
OBJ_NOT_CHARACTER_SELECTED 7, @J_NOT_CHARACTER_SELECTED2-OBJ_MAGICANT_MIMICKER
OBJ_JUMP @J_JUMP2-OBJ_MAGICANT_MIMICKER
	@J_NOT_CHARACTER_SELECTED2:
OBJ_GET_NEXT_EXP
OBJ_DIALOGUE UMSG::PHONE_EXPLVL
	@J_JUMP2:
OBJ_PICK_CHARACTER_J 3, @J_PICK_CHARACTER_J-OBJ_MAGICANT_MIMICKER
OBJ_NOT_CHARACTER_SELECTED 7, @J_NOT_CHARACTER_SELECTED3-OBJ_MAGICANT_MIMICKER
OBJ_JUMP @J_PICK_CHARACTER_J-OBJ_MAGICANT_MIMICKER
	@J_NOT_CHARACTER_SELECTED3:
OBJ_GET_NEXT_EXP
OBJ_DIALOGUE UMSG::PHONE_EXPLVL
	@J_PICK_CHARACTER_J:
OBJ_DIALOGUE UMSG::PHONE_SAVEPROMPT
OBJ_MENU UMSG::MENU_YES_NO, @J_MENU-OBJ_MAGICANT_MIMICKER, @J_MENU-OBJ_MAGICANT_MIMICKER
OBJ_SAVE
OBJ_DIALOGUE UMSG::PHONE_SAVED_RESETPROMPT
OBJ_MENU UMSG::MENU_CONTINUE_REST, @J_MENU1-OBJ_MAGICANT_MIMICKER, @J_MENU2-OBJ_MAGICANT_MIMICKER
	@J_MENU2:
OBJ_DIALOGUE UMSG::PHONE_RESET_NO
OBJ_DIALOGUE UMSG::PHONE_END
OBJ_STOP
	@J_MENU1:
OBJ_DIALOGUE UMSG::PHONE_RESET_YES
OBJ_DIALOGUE UMSG::PHONE_END
OBJ_RESET
	@J_MENU:
OBJ_DIALOGUE UMSG::PHONE_GOODLUCK
OBJ_DIALOGUE UMSG::PHONE_END
OBJ_STOP
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_MAGICANT_EARRINGGIRL:
objectDef OBJ_TYPE::WANDERING_NPC, 119, DIRECTIONS::DOWN, 533
.addr SPRITEDEF_MAGICANTIAN_GIRL
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_MAGICANT_EARRINGGIRL
OBJ_DIALOGUE UMSG::MAGICANT_EARRINGGIRL
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_MAGICANT_REDWEEDGIRL:
objectDef OBJ_TYPE::WANDERING_NPC, 23, DIRECTIONS::RIGHT, 566
.addr SPRITEDEF_MAGICANTIAN_GIRL_PINK
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_MAGICANT_REDWEEDGIRL
OBJ_DIALOGUE UMSG::MAGICANT_REDWEEDGIRL
OBJ_SET_FLAG 83
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_MAGICANT_BIGBAGGUY:
objectDef OBJ_TYPE::WANDERING_NPC, 58, DIRECTIONS::DOWN, 566
.addr SPRITEDEF_MAGICANTIAN_ADULT_BLUE
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_MAGICANT_BIGBAGGUY
OBJ_IS_NOT_FLAG 84, @J_IS_NOT_FLAG-OBJ_MAGICANT_BIGBAGGUY
OBJ_DIALOGUE UMSG::MAGICANT_BIGBAGGUY_AFTER
OBJ_STOP
	@J_IS_NOT_FLAG:
OBJ_IS_NOT_FLAG 85, @J_IS_NOT_FLAG1-OBJ_MAGICANT_BIGBAGGUY
OBJ_DIALOGUE UMSG::MAGICANT_BIGBAGGUY_GIFT1
	@J_JUMP:
OBJ_NOT_HAS_ITEM 0, @J_NOT_HAS_ITEM-OBJ_MAGICANT_BIGBAGGUY
OBJ_PLAY_SOUND 6
OBJ_PICK_ITEM 1
OBJ_GIVE_ITEM @J_IS_NOT_TALKING-OBJ_MAGICANT_BIGBAGGUY
OBJ_SET_FLAG 84
OBJ_STOP
	@J_NOT_HAS_ITEM:
OBJ_DIALOGUE UMSG::MAGICANT_BIGBAGGUY_NOROOM
OBJ_STOP
	@J_IS_NOT_FLAG1:
OBJ_IS_NOT_FLAG 86, @J_IS_NOT_FLAG2-OBJ_MAGICANT_BIGBAGGUY
OBJ_DIALOGUE UMSG::MAGICANT_BIGBAGGUY_RETURN1
OBJ_NOT_HAS_ITEM 0, @J_NOT_HAS_ITEM1-OBJ_MAGICANT_BIGBAGGUY
OBJ_PLAY_SOUND 6
OBJ_PICK_ITEM 110
OBJ_GIVE_ITEM @J_IS_NOT_TALKING-OBJ_MAGICANT_BIGBAGGUY
OBJ_SET_FLAG 85
OBJ_DIALOGUE UMSG::MAGICANT_BIGBAGGUY_GIFT2
OBJ_JUMP @J_JUMP-OBJ_MAGICANT_BIGBAGGUY
	@J_NOT_HAS_ITEM1:
OBJ_DIALOGUE UMSG::MAGICANT_BIGBAGGUY_NOROOM2
OBJ_STOP
	@J_IS_NOT_FLAG2:
OBJ_DIALOGUE UMSG::MAGICANT_BIGBAGGUY_ASK
OBJ_YESNO_IS_NO @J_YESNO_IS_NO-OBJ_MAGICANT_BIGBAGGUY
OBJ_DIALOGUE UMSG::MAGICANT_BIGBAGGUY_CARD
OBJ_YESNO_IS_NO @J_YESNO_IS_NO1-OBJ_MAGICANT_BIGBAGGUY
OBJ_NOT_HAS_ITEM 110, @J_NOT_HAS_ITEM2-OBJ_MAGICANT_BIGBAGGUY
OBJ_DIALOGUE UMSG::MAGICANT_BIGBAGGUY_RETURN2
OBJ_PICK_ITEM 110
OBJ_REMOVE_ITEM @J_IS_NOT_TALKING-OBJ_MAGICANT_BIGBAGGUY
OBJ_SET_FLAG 86
OBJ_STOP
	@J_NOT_HAS_ITEM2:
OBJ_DIALOGUE UMSG::MAGICANT_BIGBAGGUY_NOHAVE
OBJ_STOP
	@J_YESNO_IS_NO1:
OBJ_DIALOGUE UMSG::MAGICANT_BIGBAGGUY_CARD_NO
OBJ_STOP
	@J_YESNO_IS_NO:
OBJ_DIALOGUE UMSG::MAGICANT_BIGBAGGUY_ASK_NO
OBJ_STOP
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_MAGICANT_OUTSIDEMAN:
objectDef OBJ_TYPE::WANDERING_NPC, 7, DIRECTIONS::DOWN, 598
.addr SPRITEDEF_MAGICANTIAN_ADULT
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_MAGICANT_OUTSIDEMAN
OBJ_DIALOGUE UMSG::MAGICANT_OUTSIDEMAN
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_MAGICANT_GOODSKEEPER:
objectDef OBJ_TYPE::STATIONARY_NPC, 57, DIRECTIONS::DOWN, 533
.addr SPRITEDEF_MAGICANTIAN_GIRL
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_MAGICANT_GOODSKEEPER
OBJ_DIALOGUE UMSG::MAGICANT_GOODSKEEPER
OBJ_YESNO_IS_NO @J_YESNO_IS_NO-OBJ_MAGICANT_GOODSKEEPER
OBJ_MENU UMSG::MYHOME_MINNIE_STORAGE, @J_MENU-OBJ_MAGICANT_GOODSKEEPER, @J_MENU1-OBJ_MAGICANT_GOODSKEEPER
	@J_JUMP1:
OBJ_NO_ITEMS @J_NO_ITEMS-OBJ_MAGICANT_GOODSKEEPER
OBJ_CHOOSE_ITEM @J_MENU1-OBJ_MAGICANT_GOODSKEEPER
OBJ_IS_NOT_SELECTED 3, @J_IS_NOT_SELECTED-OBJ_MAGICANT_GOODSKEEPER
OBJ_JUMP @J_JUMP-OBJ_MAGICANT_GOODSKEEPER
	@J_IS_NOT_SELECTED:
OBJ_ADD_ITEM_TO_CLOSET @J_ADD_ITEM_TO_CLOSET-OBJ_MAGICANT_GOODSKEEPER
OBJ_PLAY_SOUND 6
OBJ_REMOVE_ITEM @J_IS_NOT_TALKING-OBJ_MAGICANT_GOODSKEEPER
OBJ_DIALOGUE UMSG::MAGICANT_GOODSKEEPER_SEND
OBJ_YESNO_IS_NO @J_MENU1-OBJ_MAGICANT_GOODSKEEPER
OBJ_JUMP @J_JUMP1-OBJ_MAGICANT_GOODSKEEPER
	@J_MENU:
OBJ_NO_ITEMS_CLOSET @J_NO_ITEMS_CLOSET-OBJ_MAGICANT_GOODSKEEPER
OBJ_CHOOSE_ITEM_CLOSET @J_MENU1-OBJ_MAGICANT_GOODSKEEPER
OBJ_PICK_CHARACTER 1
OBJ_PICK_CHARACTER_J 1, @J_PICK_CHARACTER_J-OBJ_MAGICANT_GOODSKEEPER
	@J_JUMP2:
OBJ_CHOOSE_CHARACTER @J_MENU1-OBJ_MAGICANT_GOODSKEEPER
	@J_PICK_CHARACTER_J:
OBJ_GIVE_ITEM @J_GIVE_ITEM-OBJ_MAGICANT_GOODSKEEPER
OBJ_PLAY_SOUND 6
OBJ_TAKE_ITEM_FROM_CLOSET @J_IS_NOT_TALKING-OBJ_MAGICANT_GOODSKEEPER
OBJ_DIALOGUE UMSG::MAGICANT_GOODSKEEPER_GIVE
OBJ_YESNO_IS_NO @J_MENU1-OBJ_MAGICANT_GOODSKEEPER
OBJ_JUMP @J_MENU-OBJ_MAGICANT_GOODSKEEPER
	@J_GIVE_ITEM:
OBJ_PICK_CHARACTER_J 1, @J_PICK_CHARACTER_J1-OBJ_MAGICANT_GOODSKEEPER
OBJ_DIALOGUE UMSG::MAGICANT_GOODSKEEPER_SOMEONEELSE
OBJ_YESNO_IS_NO @J_MENU1-OBJ_MAGICANT_GOODSKEEPER
OBJ_JUMP @J_JUMP2-OBJ_MAGICANT_GOODSKEEPER
	@J_PICK_CHARACTER_J1:
OBJ_DIALOGUE UMSG::PODUNK_PIPPI_NOROOM2
OBJ_STOP
	@J_ADD_ITEM_TO_CLOSET:
OBJ_DIALOGUE UMSG::MAGICANT_GOODSKEEPER_FULL
OBJ_STOP
	@J_JUMP:
OBJ_DIALOGUE UMSG::MYHOME_MINNIE_STORAGE_CANT
OBJ_STOP
	@J_MENU1:
OBJ_DIALOGUE UMSG::MAGICANT_GOODSKEEPER_BYE
OBJ_STOP
	@J_NO_ITEMS:
OBJ_DIALOGUE UMSG::MYHOME_MINNIE_STORAGE_INVNOTHING
OBJ_STOP
	@J_NO_ITEMS_CLOSET:
OBJ_DIALOGUE UMSG::MYHOME_MINNIE_STORAGE_NOTHING
OBJ_STOP
	@J_YESNO_IS_NO:
OBJ_DIALOGUE UMSG::MAGICANT_GOODSKEEPER_BAGS
	@J_IS_NOT_TALKING:
OBJ_STOP

