OBJ_BANK_2F:
.addr OBJ_SWEETFACTORY_ENTRANCE
.addr OBJ_SWEETFACTORY_RM1ENTRANCE
.addr OBJ_SWEETFACTORY_RM2ENTRANCE
.addr OBJ_SWEETFACTORY_RM3ENTRANCE
.addr OBJ_SWEETFACTORY_RM4ENTRANCE
.addr OBJ_SWEETFACTORY_RM5ENTRANCE
.addr OBJ_SWEETFACTORY_RM6ENTRANCE
.addr OBJ_SWEETFACTORY_RM7ENTRANCE
.addr OBJ_SWEETFACTORY_RM8ENTRANCE
.addr OBJ_SWEETFACTORY_RM9ENTRANCE
.addr OBJ_SWEETFACTORY_RM10ENTRANCE
.addr OBJ_SWEETFACTORY_RM11ENTRANCE
.addr OBJ_SWEETFACTORY_RM12ENTRANCE
.addr OBJ_SWEETFACTORY_RM13ENTRANCE
.addr OBJ_SWEETFACTORY_RM14ENTRANCE
.addr OBJ_SWEETFACTORY_BOTTLEROCKETS
.addr OBJ_MYHOME_BASEMENTEXIT
.addr OBJ_MYHOME_PRESENT1
.addr OBJ_MYHOME_PRESENT2
.addr OBJ_MYHOME_PRESENT3
.addr OBJ_SWEETFACTORY_PRESENT1
.addr 0

OBJ_SWEETFACTORY_ENTRANCE:
objectDef OBJ_TYPE::DOOR, 114, DIRECTIONS::RIGHT, 430
doorArgDef 6, 342, DIRECTIONS::DOWN, 600

OBJ_SWEETFACTORY_RM1ENTRANCE:
objectDef OBJ_TYPE::DOOR, 74, DIRECTIONS::RIGHT, 446
doorArgDef 0, 18, DIRECTIONS::RIGHT, 838

OBJ_SWEETFACTORY_RM2ENTRANCE:
objectDef OBJ_TYPE::DOOR, 53, DIRECTIONS::UP, 443
doorArgDef 0, 61, DIRECTIONS::LEFT, 838

OBJ_SWEETFACTORY_RM3ENTRANCE:
objectDef OBJ_TYPE::DOOR, 45, DIRECTIONS::UP, 443
doorArgDef 0, 29, DIRECTIONS::LEFT, 902

OBJ_SWEETFACTORY_RM4ENTRANCE:
objectDef OBJ_TYPE::DOOR, 37, DIRECTIONS::LEFT, 446
doorArgDef 0, 29, DIRECTIONS::LEFT, 870

OBJ_SWEETFACTORY_RM5ENTRANCE:
objectDef OBJ_TYPE::DOOR, 85, DIRECTIONS::UP, 423
doorArgDef 0, 29, DIRECTIONS::LEFT, 998

OBJ_SWEETFACTORY_RM6ENTRANCE:
objectDef OBJ_TYPE::DOOR, 66, DIRECTIONS::RIGHT, 426
doorArgDef 0, 18, DIRECTIONS::RIGHT, 934

OBJ_SWEETFACTORY_RM7ENTRANCE:
objectDef OBJ_TYPE::DOOR, 34, DIRECTIONS::RIGHT, 426
doorArgDef 0, 18, DIRECTIONS::RIGHT, 966

OBJ_SWEETFACTORY_RM8ENTRANCE:
objectDef OBJ_TYPE::DOOR, 25, DIRECTIONS::UP, 423
doorArgDef 0, 61, DIRECTIONS::LEFT, 998

OBJ_SWEETFACTORY_RM9ENTRANCE:
objectDef OBJ_TYPE::DOOR, 9, DIRECTIONS::LEFT, 430
doorArgDef 0, 61, DIRECTIONS::LEFT, 710

OBJ_SWEETFACTORY_RM10ENTRANCE:
objectDef OBJ_TYPE::DOOR, 106, DIRECTIONS::RIGHT, 418
doorArgDef 0, 82, DIRECTIONS::RIGHT, 710

OBJ_SWEETFACTORY_RM11ENTRANCE:
objectDef OBJ_TYPE::DOOR, 57, DIRECTIONS::UP, 411
doorArgDef 0, 29, DIRECTIONS::LEFT, 710

OBJ_SWEETFACTORY_RM12ENTRANCE:
objectDef OBJ_TYPE::DOOR, 21, DIRECTIONS::LEFT, 414
doorArgDef 0, 125, DIRECTIONS::LEFT, 710

OBJ_SWEETFACTORY_RM13ENTRANCE:
objectDef OBJ_TYPE::DOOR, 118, DIRECTIONS::RIGHT, 414
doorArgDef 0, 146, DIRECTIONS::RIGHT, 710

OBJ_SWEETFACTORY_RM14ENTRANCE:
objectDef OBJ_TYPE::DOOR, 29, DIRECTIONS::UP, 399
doorArgDef 0, 189, DIRECTIONS::LEFT, 710

OBJ_SWEETFACTORY_BOTTLEROCKETS:
objectDef 25, 35, DIRECTIONS::UP, 397
.addr SPRITEDEF_TRASH_CAN
OBJ_IS_NOT_CHECKING @J_IS_NOT_CHECKING-OBJ_SWEETFACTORY_BOTTLEROCKETS
OBJ_PICK_ITEM 97
OBJ_DIALOGUE UMSG::PRESENT_ITEM
OBJ_NOT_HAS_ITEM 0, @J_NOT_HAS_ITEM-OBJ_SWEETFACTORY_BOTTLEROCKETS
OBJ_PICK_ITEM 97
OBJ_GIVE_ITEM @J_NOT_HAS_ITEM-OBJ_SWEETFACTORY_BOTTLEROCKETS
OBJ_DIALOGUE UMSG::GET_ITEM
OBJ_PLAY_SOUND 6
OBJ_STOP
	@J_NOT_HAS_ITEM:
OBJ_DIALOGUE UMSG::INVENTORY_FULL
	@J_IS_NOT_CHECKING:
OBJ_STOP

OBJ_MYHOME_BASEMENTEXIT:
objectDef OBJ_TYPE::STAIRS, 766, DIRECTIONS::RIGHT, 134
doorArgDef 18, 41, DIRECTIONS::DOWN, 132

OBJ_MYHOME_PRESENT1:
objectDef OBJ_TYPE::PRESENT, 759, DIRECTIONS::UP, 132
.addr SPRITEDEF_PRESENT
.byte 16 ; item
.byte 0 ; flag

OBJ_MYHOME_PRESENT2:
objectDef OBJ_TYPE::PRESENT, 755, DIRECTIONS::UP, 134
.addr SPRITEDEF_PRESENT
.ifdef VER_JP
.byte 113 ; item
.else
.byte 71 ; item
.endif
.byte 1 ; flag

OBJ_MYHOME_PRESENT3:
objectDef OBJ_TYPE::PRESENT, 761, DIRECTIONS::UP, 135
.addr SPRITEDEF_PRESENT
.byte 88 ; item
.byte 2 ; flag

OBJ_SWEETFACTORY_PRESENT1:
objectDef OBJ_TYPE::PRESENT, 19, DIRECTIONS::UP, 406
.addr SPRITEDEF_PRESENT
.byte 65 ; item
.byte 18 ; flag

