OBJ_BANK_34:
.addr OBJ_MTITOI_CAVELASTDOOR
.addr OBJ_MTITOI_LLOYDSAVESTART
.addr OBJ_MTITOI_LLOYDSAVELLOYD
.addr OBJ_MTITOI_LLOYDSAVENINTEN
.addr OBJ_MTITOI_LLOYDSAVEANA
.addr OBJ_MTITOI_LLOYDSAVETEDDY
.addr OBJ_MTITOI_LLOYDSAVETANK
.addr OBJ_MTITOI_HEALERHOUSEENTRANCE
.addr 0

OBJ_MTITOI_CAVELASTDOOR:
objectDef OBJ_TYPE::DOOR, 893, DIRECTIONS::UP, 883
doorArgDef 19, 1021, DIRECTIONS::DOWN, 221

OBJ_MTITOI_LLOYDSAVESTART:
objectDef 28, 902, DIRECTIONS::UP, 883
OBJ_FLAG_APPEAR 201
OBJ_IS_NOT_TOUCHING @J_IS_NOT_TOUCHING-OBJ_MTITOI_LLOYDSAVESTART
OBJ_SIGNAL 6
	@J_IS_NOT_TOUCHING:
OBJ_STOP

OBJ_MTITOI_LLOYDSAVELLOYD:
objectDef OBJ_TYPE::STATIONARY_NPC_CHECKSPAWN, 902, DIRECTIONS::UP, 884
.addr SPRITEDEF_LLOYD
OBJ_FLAG_APPEAR 1
OBJ_IS_SIGNAL @J_IS_SIGNAL-OBJ_MTITOI_LLOYDSAVELLOYD
OBJ_MOVE @MOVE_DATA_1
OBJ_DIALOGUE UMSG::MTITOI_LLOYDSAVE
OBJ_MOVE @MOVE_DATA_2
OBJ_CLEAR_FLAG 204
OBJ_MOVE @MOVE_DATA_3
OBJ_CLEAR_FLAG 203
OBJ_MOVE @MOVE_DATA_4
OBJ_CLEAR_FLAG 202
OBJ_MOVE @MOVE_DATA_5
	@J_IS_SIGNAL:
OBJ_STOP

@MOVE_DATA_1:
moveDef DIRECTIONS::RIGHT, MOVE_CMD::MOVEFACE, 1
moveDef DIRECTIONS::DOWN, MOVE_CMD::ABOUTFACE, 1
OBJ_RETURN
@MOVE_DATA_2:
moveDef DIRECTIONS::DOWN, MOVE_CMD::MOVEFACE, 1
moveDef DIRECTIONS::UP, MOVE_CMD::ABOUTFACE, 2
OBJ_RETURN
@MOVE_DATA_3:
moveDef DIRECTIONS::LEFT, MOVE_CMD::MOVEFACE, 1
moveDef DIRECTIONS::UP, MOVE_CMD::ABOUTFACE, 2
OBJ_RETURN
@MOVE_DATA_4:
moveDef DIRECTIONS::LEFT, MOVE_CMD::MOVEFACE, 1
moveDef DIRECTIONS::UP, MOVE_CMD::ABOUTFACE, 2
OBJ_RETURN
@MOVE_DATA_5:
moveDef DIRECTIONS::UP, MOVE_CMD::MOVEFACE, 1
moveDef DIRECTIONS::RIGHT, MOVE_CMD::MOVEFACE, 1
OBJ_STOP

OBJ_MTITOI_LLOYDSAVENINTEN:
objectDef 29, 901, DIRECTIONS::UP, 885
.addr SPRITEDEF_TELEPORT_FRY
OBJ_FLAG_APPEAR 202
OBJ_STOP

OBJ_MTITOI_LLOYDSAVEANA:
objectDef 29, 902, DIRECTIONS::UP, 885
.addr SPRITEDEF_TELEPORT_FRY
OBJ_FLAG_APPEAR 203
OBJ_STOP

OBJ_MTITOI_LLOYDSAVETEDDY:
objectDef 29, 903, DIRECTIONS::UP, 885
.addr SPRITEDEF_TELEPORT_FRY
OBJ_FLAG_APPEAR 204
OBJ_STOP

OBJ_MTITOI_LLOYDSAVETANK:
objectDef 44, 893, DIRECTIONS::UP, 884
.addr SPRITEDEF_TANK
OBJ_FLAG_APPEAR 201
OBJ_IS_SIGNAL @J_IS_SIGNAL-OBJ_MTITOI_LLOYDSAVETANK
OBJ_MOVE @MOVE_DATA_1
OBJ_SIGNAL 2
OBJ_MOVE @MOVE_DATA_2
OBJ_CLEAR_FLAG 201
OBJ_CLEAR_FLAG 255
OBJ_REMOVE_CHARACTER 4, @J_IS_SIGNAL-OBJ_MTITOI_LLOYDSAVETANK
OBJ_REMOVE_CHARACTER 2, @J_IS_SIGNAL-OBJ_MTITOI_LLOYDSAVETANK
OBJ_PICK_CHARACTER 2
OBJ_AND_STATUS 0
OBJ_ADD_CHARACTER 2, @J_IS_SIGNAL-OBJ_MTITOI_LLOYDSAVETANK
OBJ_TELEPORT 18, 757, DIRECTIONS::RIGHT, 966
OBJ_SET_FADE 7
OBJ_MOVE @MOVE_DATA_3
	@J_IS_SIGNAL:
OBJ_STOP

@MOVE_DATA_1:
moveDef DIRECTIONS::RIGHT, MOVE_CMD::ABOUTFACE, 4
moveDef DIRECTIONS::RIGHT, MOVE_CMD::MOVEFACE, 9
moveDef DIRECTIONS::RIGHT, MOVE_CMD::ABOUTFACE, 4
OBJ_RETURN
@MOVE_DATA_2:
moveDef DIRECTIONS::RIGHT, MOVE_CMD::ABOUTFACE, 20
moveDef DIRECTIONS::DOWN, MOVE_CMD::ABOUTFACE, 1
moveDef DIRECTIONS::LEFT, MOVE_CMD::MOVEFACE, 9
moveDef DIRECTIONS::LEFT, MOVE_CMD::ABOUTFACE, 4
OBJ_RETURN
@MOVE_DATA_3:
OBJ_STOP

OBJ_MTITOI_HEALERHOUSEENTRANCE:
objectDef OBJ_TYPE::DOOR, 957, DIRECTIONS::UP, 835
doorArgDef 18, 13, DIRECTIONS::LEFT, 294

