OBJ_BANK_30:
.addr OBJ_EVE_ENTRANCE1
.addr OBJ_EVE_ENTRANCE2
.addr OBJ_EVE_ENTRANCE3
.addr OBJ_EVE_ENTRANCE4
.addr OBJ_EVE_ENTRANCE5
.addr OBJ_EVE_ENTRANCE6
.addr OBJ_EVE_ENTRANCE7
.addr OBJ_EVE_EXIT1
.addr OBJ_EVE_ENTRANCE8
.addr OBJ_EVE_EXIT2
.addr OBJ_EVE_EVE
.addr OBJ_EVE_ELEVATOR
.addr OBJ_EVE_FISH1
.addr OBJ_EVE_FISH2
.addr OBJ_EVE_FISH3
.addr OBJ_EVE_FISH4
.addr OBJ_EVE_FISH5
.addr OBJ_EVE_FISH6
.addr OBJ_EVE_FISH7
.addr OBJ_EVE_FISH8
.addr OBJ_EVE_FISH9
.addr OBJ_EVE_FISH10
.addr OBJ_EVE_FISH11
.addr OBJ_EVE_STARTCRACKS
.addr OBJ_EVE_STARTCRACK1
.addr OBJ_EVE_STARTCRACK2
.addr OBJ_EVE_EXPLODECRACK1
.addr OBJ_EVE_EXPLODECRACK2
.addr OBJ_EVE_EXPLODECRACK3
.addr OBJ_EVE_EXPLODECRACK4
.addr OBJ_EVE_EXPLODECRACK5
.addr OBJ_EVE_EXPLOSION
.addr 0

OBJ_EVE_ENTRANCE1:
objectDef OBJ_TYPE::DOOR, 193, DIRECTIONS::LEFT, 822
doorArgDef 0, 181, DIRECTIONS::LEFT, 802

OBJ_EVE_ENTRANCE2:
objectDef OBJ_TYPE::DOOR, 153, DIRECTIONS::LEFT, 802
doorArgDef 0, 141, DIRECTIONS::LEFT, 802

OBJ_EVE_ENTRANCE3:
objectDef OBJ_TYPE::DOOR, 129, DIRECTIONS::LEFT, 802
doorArgDef 0, 117, DIRECTIONS::LEFT, 802

OBJ_EVE_ENTRANCE4:
objectDef OBJ_TYPE::DOOR, 93, DIRECTIONS::LEFT, 802
doorArgDef 0, 81, DIRECTIONS::LEFT, 802

OBJ_EVE_ENTRANCE5:
objectDef OBJ_TYPE::DOOR, 65, DIRECTIONS::LEFT, 802
doorArgDef 0, 29, DIRECTIONS::LEFT, 802

OBJ_EVE_ENTRANCE6:
objectDef OBJ_TYPE::DOOR, 9, DIRECTIONS::LEFT, 802
doorArgDef 0, 217, DIRECTIONS::LEFT, 778

OBJ_EVE_ENTRANCE7:
objectDef OBJ_TYPE::DOOR, 173, DIRECTIONS::LEFT, 778
doorArgDef 0, 161, DIRECTIONS::LEFT, 778

OBJ_EVE_EXIT1:
objectDef OBJ_TYPE::DOOR, 162, DIRECTIONS::RIGHT, 778
doorArgDef 0, 174, DIRECTIONS::RIGHT, 778

OBJ_EVE_ENTRANCE8:
objectDef OBJ_TYPE::DOOR, 101, DIRECTIONS::LEFT, 778
doorArgDef 0, 89, DIRECTIONS::LEFT, 778

OBJ_EVE_EXIT2:
objectDef OBJ_TYPE::DOOR, 90, DIRECTIONS::RIGHT, 778
doorArgDef 0, 102, DIRECTIONS::RIGHT, 778

OBJ_EVE_EVE:
objectDef 43, 129, DIRECTIONS::DOWN, 756
.addr SPRITEDEF_EVE
OBJ_FLAG_DISAPPEAR 192
OBJ_IS_NOT_CHECKING @J_IS_NOT_CHECKING-OBJ_EVE_EVE
OBJ_DIALOGUE UMSG::EVE_EVECHECK
OBJ_DIALOGUE UMSG::EVE_EVE
OBJ_MOVE @MOVE_DATA
OBJ_SET_FLAG 151
OBJ_SIGNAL 26
	@J_IS_NOT_CHECKING:
OBJ_STOP

@MOVE_DATA:
moveDef DIRECTIONS::DOWN, MOVE_CMD::ABOUTFACE, 2
OBJ_STOP

OBJ_EVE_ELEVATOR:
objectDef 26, 237, DIRECTIONS::UP, 768
.addr SPRITEDEF_PLATFORM
OBJ_IS_NOT_TOUCHING @J_IS_NOT_TOUCHING-OBJ_EVE_ELEVATOR
OBJ_HAS_MOVED @J_IS_NOT_TOUCHING-OBJ_EVE_ELEVATOR
OBJ_ELEVATOR 4
OBJ_MOVE @MOVE_DATA_1
OBJ_EXIT_VEHICLE 4
OBJ_MOVE @MOVE_DATA_2
	@J_IS_NOT_TOUCHING:
OBJ_STOP

@MOVE_DATA_1:
moveDef DIRECTIONS::DOWN, 7, 52
OBJ_RETURN
@MOVE_DATA_2:
OBJ_STOP

OBJ_EVE_FISH1:
objectDef OBJ_TYPE::WANDERINGFAST_NPC, 120, DIRECTIONS::LEFT, 771
.addr SPRITEDEF_FISH_GRAY
OBJ_STOP

OBJ_EVE_FISH2:
objectDef OBJ_TYPE::WANDERINGFAST_NPC, 147, DIRECTIONS::RIGHT, 773
.addr SPRITEDEF_FISH_RED
OBJ_STOP

OBJ_EVE_FISH3:
objectDef OBJ_TYPE::WANDERINGFAST_NPC, 144, DIRECTIONS::RIGHT, 772
.addr SPRITEDEF_FISH_BLUE
OBJ_STOP

OBJ_EVE_FISH4:
objectDef OBJ_TYPE::WANDERINGFAST_NPC, 138, DIRECTIONS::RIGHT, 771
.addr SPRITEDEF_FISH_RED
OBJ_STOP

OBJ_EVE_FISH5:
objectDef OBJ_TYPE::WANDERINGFAST_NPC, 104, DIRECTIONS::RIGHT, 797
.addr SPRITEDEF_FISH_GRAY
OBJ_STOP

OBJ_EVE_FISH6:
objectDef OBJ_TYPE::WANDERINGFAST_NPC, 23, DIRECTIONS::RIGHT, 796
.addr SPRITEDEF_FISH_RED
OBJ_STOP

OBJ_EVE_FISH7:
objectDef OBJ_TYPE::WANDERINGFAST_NPC, 140, DIRECTIONS::RIGHT, 773
.addr SPRITEDEF_FISH_GRAY
OBJ_STOP

OBJ_EVE_FISH8:
objectDef OBJ_TYPE::WANDERINGFAST_NPC, 125, DIRECTIONS::RIGHT, 772
.addr SPRITEDEF_FISH_RED
OBJ_STOP

OBJ_EVE_FISH9:
objectDef OBJ_TYPE::WANDERINGFAST_NPC, 108, DIRECTIONS::RIGHT, 797
.addr SPRITEDEF_FISH_BLUE
OBJ_STOP

OBJ_EVE_FISH10:
objectDef OBJ_TYPE::WANDERINGFAST_NPC, 18, DIRECTIONS::RIGHT, 796
.addr SPRITEDEF_FISH_RED
OBJ_STOP

OBJ_EVE_FISH11:
objectDef OBJ_TYPE::WANDERINGFAST_NPC, 114, DIRECTIONS::RIGHT, 773
.addr SPRITEDEF_FISH_BLUE
OBJ_STOP

OBJ_EVE_STARTCRACKS:
objectDef OBJ_TYPE::TRIGGER_CHECKSPAWN, 129, DIRECTIONS::UP, 762
OBJ_FLAG_DISAPPEAR 149
OBJ_IS_NOT_TOUCHING @J_IS_NOT_TOUCHING-OBJ_EVE_STARTCRACKS
OBJ_SET_FLAG 149
	@J_IS_NOT_TOUCHING:
OBJ_STOP

OBJ_EVE_STARTCRACK1:
objectDef OBJ_TYPE::STATIONARY_NPC_CHECKSPAWN, 126, DIRECTIONS::UP, 762
.addr SPRITEDEF_CRACK
OBJ_FLAG_APPEAR 149
OBJ_STOP

OBJ_EVE_STARTCRACK2:
objectDef OBJ_TYPE::STATIONARY_NPC_CHECKSPAWN, 132, DIRECTIONS::LEFT, 762
.addr SPRITEDEF_CRACK
OBJ_FLAG_APPEAR 149
OBJ_STOP

OBJ_EVE_EXPLODECRACK1:
objectDef OBJ_TYPE::STATIONARY_NPC_CHECKSPAWN, 124, DIRECTIONS::RIGHT, 754
.addr SPRITEDEF_CRACK
OBJ_FLAG_APPEAR 151
OBJ_IS_SIGNAL @J_IS_SIGNAL-OBJ_EVE_EXPLODECRACK1
OBJ_MOVE OBJ_EVE_CRACKSET2
OBJ_SET_FLAG 152
OBJ_SIGNAL 27
	@J_IS_SIGNAL:
OBJ_STOP

OBJ_EVE_EXPLODECRACK2:
objectDef OBJ_TYPE::STATIONARY_NPC_CHECKSPAWN, 135, DIRECTIONS::UP, 752
.addr SPRITEDEF_CRACK
OBJ_FLAG_APPEAR 152
OBJ_IS_SIGNAL @J_IS_SIGNAL-OBJ_EVE_EXPLODECRACK2
OBJ_MOVE OBJ_EVE_CRACKSET4
OBJ_SET_FLAG 153
OBJ_SIGNAL 28
	@J_IS_SIGNAL:
OBJ_STOP

OBJ_EVE_EXPLODECRACK3:
objectDef OBJ_TYPE::STATIONARY_NPC_CHECKSPAWN, 127, DIRECTIONS::DOWN, 754
.addr SPRITEDEF_CRACK
OBJ_FLAG_APPEAR 153
OBJ_IS_SIGNAL @J_IS_SIGNAL-OBJ_EVE_EXPLODECRACK3
OBJ_MOVE OBJ_EVE_CRACKSET3
OBJ_SET_FLAG 154
OBJ_SIGNAL 29
	@J_IS_SIGNAL:
OBJ_STOP

OBJ_EVE_EXPLODECRACK4:
objectDef OBJ_TYPE::STATIONARY_NPC_CHECKSPAWN, 129, DIRECTIONS::LEFT, 751
.addr SPRITEDEF_CRACK
OBJ_FLAG_APPEAR 154
OBJ_IS_SIGNAL @J_IS_SIGNAL-OBJ_EVE_EXPLODECRACK4
OBJ_MOVE OBJ_EVE_CRACKSET1
OBJ_SET_FLAG 155
OBJ_SIGNAL 30
	@J_IS_SIGNAL:
OBJ_STOP

OBJ_EVE_EXPLODECRACK5:
objectDef OBJ_TYPE::STATIONARY_NPC_CHECKSPAWN, 132, DIRECTIONS::LEFT, 754
.addr SPRITEDEF_CRACK
OBJ_FLAG_APPEAR 155
OBJ_IS_SIGNAL @J_IS_SIGNAL-OBJ_EVE_EXPLODECRACK5
OBJ_MOVE OBJ_EVE_CRACKSET4
OBJ_SIGNAL 31
	@J_IS_SIGNAL:
OBJ_STOP

OBJ_EVE_EXPLOSION:
objectDef 24, 132, DIRECTIONS::LEFT, 754
OBJ_IS_SIGNAL @J_IS_SIGNAL-OBJ_EVE_EXPLOSION
OBJ_SHAKE
OBJ_SHAKE
OBJ_SHAKE
OBJ_TELEPORT 11, 898, DIRECTIONS::DOWN, 782
OBJ_SET_FADE 5
OBJ_UNK
OBJ_ADD_CHARACTER 6, @J_IS_SIGNAL-OBJ_EVE_EXPLOSION
OBJ_SET_FLAG 192
	@J_IS_SIGNAL:
OBJ_STOP

OBJ_EVE_CRACKSET1:
moveDef DIRECTIONS::UP, MOVE_CMD::ABOUTFACE, 2
OBJ_STOP
OBJ_EVE_CRACKSET2:
moveDef DIRECTIONS::RIGHT, MOVE_CMD::ABOUTFACE, 2
OBJ_STOP
OBJ_EVE_CRACKSET3:
moveDef DIRECTIONS::DOWN, MOVE_CMD::ABOUTFACE, 2
OBJ_STOP
OBJ_EVE_CRACKSET4:
moveDef DIRECTIONS::LEFT, MOVE_CMD::ABOUTFACE, 2
OBJ_STOP