OBJ_BANK_2C:
.addr OBJ_DUNCANFACTORY_EXIT
.addr OBJ_DUNCANFACTORY_RM1ENTRANCE
.addr OBJ_DUNCANFACTORY_RM2ENTRANCE
.addr OBJ_DUNCANFACTORY_RM3ENTRANCE
.addr OBJ_DUNCANFACTORY_RM4ENTRANCE
.addr OBJ_DUNCANFACTORY_RM5ENTRANCE
.addr OBJ_DUNCANFACTORY_RM6ENTRANCE
.addr OBJ_DUNCANFACTORY_RM7ENTRANCE
.addr OBJ_DUNCANFACTORY_RM8ENTRANCE
.addr OBJ_DUNCANFACTORY_RM9ENTRANCE
.addr OBJ_DUNCANFACTORY_RM10ENTRANCE
.addr OBJ_DUNCANFACTORY_RM11ENTRANCE
.addr OBJ_DUNCANFACTORY_RM12ENTRANCE
.addr OBJ_DUNCANFACTORY_RM13ENTRANCE
.addr OBJ_DUNCANFACTORY_RM14ENTRANCE
.addr OBJ_DUNCANFACTORY_RM15ENTRANCE
.addr OBJ_DUNCANFACTORY_RM16ENTRANCE
.addr OBJ_DUNCANFACTORY_RM17ENTRANCE
.addr OBJ_DUNCANFACTORY_RM18ENTRANCE
.addr OBJ_DUNCANFACTORY_RM19ENTRANCE
.addr OBJ_DUNCANFACTORY_RM20ENTRANCE
.addr OBJ_DUNCANFACTORY_RM21ENTRANCE
.addr OBJ_DUNCANFACTORY_RM22ENTRANCE
.addr OBJ_DUNCANFACTORY_RM23ENTRANCE
.addr 0

OBJ_DUNCANFACTORY_EXIT:
objectDef OBJ_TYPE::DOOR, 233, DIRECTIONS::UP, 967
doorArgDef 6, 310, DIRECTIONS::DOWN, 252

OBJ_DUNCANFACTORY_RM1ENTRANCE:
objectDef OBJ_TYPE::DOOR, 225, DIRECTIONS::UP, 859
doorArgDef 0, 13, DIRECTIONS::LEFT, 838

OBJ_DUNCANFACTORY_RM2ENTRANCE:
objectDef OBJ_TYPE::DOOR, 161, DIRECTIONS::UP, 875
doorArgDef 0, 13, DIRECTIONS::LEFT, 870

OBJ_DUNCANFACTORY_RM3ENTRANCE:
objectDef OBJ_TYPE::DOOR, 157, DIRECTIONS::UP, 887
doorArgDef 0, 93, DIRECTIONS::LEFT, 726

OBJ_DUNCANFACTORY_RM4ENTRANCE:
objectDef OBJ_TYPE::DOOR, 201, DIRECTIONS::UP, 887
doorArgDef 0, 13, DIRECTIONS::LEFT, 966

OBJ_DUNCANFACTORY_RM5ENTRANCE:
objectDef OBJ_TYPE::DOOR, 225, DIRECTIONS::UP, 883
doorArgDef 0, 45, DIRECTIONS::LEFT, 838

OBJ_DUNCANFACTORY_RM6ENTRANCE:
objectDef OBJ_TYPE::DOOR, 234, DIRECTIONS::RIGHT, 886
doorArgDef 0, 34, DIRECTIONS::RIGHT, 870

OBJ_DUNCANFACTORY_RM7ENTRANCE:
objectDef OBJ_TYPE::DOOR, 93, DIRECTIONS::UP, 895
doorArgDef 0, 45, DIRECTIONS::LEFT, 934

OBJ_DUNCANFACTORY_RM8ENTRANCE:
objectDef OBJ_TYPE::DOOR, 77, DIRECTIONS::LEFT, 902
doorArgDef 0, 61, DIRECTIONS::LEFT, 758

OBJ_DUNCANFACTORY_RM9ENTRANCE:
objectDef OBJ_TYPE::DOOR, 218, DIRECTIONS::RIGHT, 938
doorArgDef 0, 34, DIRECTIONS::RIGHT, 966

OBJ_DUNCANFACTORY_RM10ENTRANCE:
objectDef OBJ_TYPE::DOOR, 170, DIRECTIONS::RIGHT, 942
doorArgDef 0, 34, DIRECTIONS::RIGHT, 998

OBJ_DUNCANFACTORY_RM11ENTRANCE:
objectDef OBJ_TYPE::DOOR, 157, DIRECTIONS::UP, 971
doorArgDef 0, 77, DIRECTIONS::LEFT, 838

OBJ_DUNCANFACTORY_RM12ENTRANCE:
objectDef OBJ_TYPE::DOOR, 226, DIRECTIONS::RIGHT, 994
doorArgDef 0, 34, DIRECTIONS::RIGHT, 710

OBJ_DUNCANFACTORY_RM13ENTRANCE:
objectDef OBJ_TYPE::DOOR, 213, DIRECTIONS::UP, 987
doorArgDef 0, 29, DIRECTIONS::LEFT, 726

OBJ_DUNCANFACTORY_RM14ENTRANCE:
objectDef OBJ_TYPE::DOOR, 205, DIRECTIONS::UP, 987
doorArgDef 0, 77, DIRECTIONS::LEFT, 710

OBJ_DUNCANFACTORY_RM15ENTRANCE:
objectDef OBJ_TYPE::DOOR, 150, DIRECTIONS::RIGHT, 990
doorArgDef 0, 98, DIRECTIONS::RIGHT, 710

OBJ_DUNCANFACTORY_RM16ENTRANCE:
objectDef OBJ_TYPE::DOOR, 125, DIRECTIONS::UP, 939
doorArgDef 0, 141, DIRECTIONS::LEFT, 710

OBJ_DUNCANFACTORY_RM17ENTRANCE:
objectDef OBJ_TYPE::DOOR, 117, DIRECTIONS::UP, 963
doorArgDef 0, 237, DIRECTIONS::LEFT, 710

OBJ_DUNCANFACTORY_RM18ENTRANCE:
objectDef OBJ_TYPE::DOOR, 262, DIRECTIONS::RIGHT, 874
doorArgDef 0, 2, DIRECTIONS::RIGHT, 934

OBJ_DUNCANFACTORY_RM19ENTRANCE:
objectDef OBJ_TYPE::DOOR, 302, DIRECTIONS::RIGHT, 902
doorArgDef 0, 2, DIRECTIONS::RIGHT, 710

OBJ_DUNCANFACTORY_RM20ENTRANCE:
objectDef OBJ_TYPE::DOOR, 326, DIRECTIONS::RIGHT, 954
doorArgDef 0, 178, DIRECTIONS::RIGHT, 726

OBJ_DUNCANFACTORY_RM21ENTRANCE:
objectDef OBJ_TYPE::DOOR, 309, DIRECTIONS::UP, 971
doorArgDef 0, 173, DIRECTIONS::LEFT, 710

OBJ_DUNCANFACTORY_RM22ENTRANCE:
objectDef OBJ_TYPE::DOOR, 302, DIRECTIONS::RIGHT, 990
doorArgDef 0, 194, DIRECTIONS::RIGHT, 710

OBJ_DUNCANFACTORY_RM23ENTRANCE:
objectDef OBJ_TYPE::DOOR, 289, DIRECTIONS::LEFT, 998
doorArgDef 0, 13, DIRECTIONS::LEFT, 998

