OBJ_BANK_2B:
.addr OBJ_GRAVEYARD_CHURCHEXIT
.addr OBJ_SNOWMAN_CHURCHEXIT
.addr OBJ_YOUNGTOWN_CHURCHEXIT
.addr OBJ_ELLAY_TOWEREXIT
.addr OBJ_ELLAY_BOTTOMELEVATOR
.addr OBJ_ISLAND_HOUSEEXIT
.addr OBJ_ISLAND_HOUSEROOMENTRANCE
.addr OBJ_ISLAND_HOUSEROOMEXIT
.addr OBJ_MTITOI_HEALERHOUSEROOMEXIT
.addr OBJ_ISLAND_SCIENTIST
.addr OBJ_ISLAND_ABLE
.addr OBJ_ISLAND_BAKER
.addr OBJ_GRAVEYARD_PRIEST
.addr OBJ_SNOWMAN_PRIEST
.addr OBJ_SNOWMAN_ANA
.addr OBJ_ELLAY_TOWERBELLHOP
.addr OBJ_ELLAY_TOWER_GUY
.addr OBJ_MTITOI_FALLINLOVENINTEN
.addr OBJ_MTITOI_FALLINLOVEANA
.addr OBJ_MTITOI_FALLINLOVETEDDY
.addr 0

OBJ_GRAVEYARD_CHURCHEXIT:
objectDef OBJ_TYPE::DOOR, 846, DIRECTIONS::RIGHT, 150
doorArgDef 13, 181, DIRECTIONS::DOWN, 568

OBJ_SNOWMAN_CHURCHEXIT:
objectDef OBJ_TYPE::DOOR, 814, DIRECTIONS::RIGHT, 150
doorArgDef 10, 977, DIRECTIONS::DOWN, 1000

OBJ_YOUNGTOWN_CHURCHEXIT:
objectDef OBJ_TYPE::DOOR, 878, DIRECTIONS::RIGHT, 150
doorArgDef 48, 709, DIRECTIONS::DOWN, 464

OBJ_ELLAY_TOWEREXIT:
objectDef OBJ_TYPE::DOOR, 46, DIRECTIONS::RIGHT, 214
doorArgDef 6, 737, DIRECTIONS::DOWN, 208

OBJ_ELLAY_BOTTOMELEVATOR:
objectDef OBJ_TYPE::DOOR, 40, DIRECTIONS::UP, 211
doorArgDef 0, 59, DIRECTIONS::DOWN, 364

OBJ_ISLAND_HOUSEEXIT:
objectDef OBJ_TYPE::DOOR, 1006, DIRECTIONS::RIGHT, 134
doorArgDef 6, 977, DIRECTIONS::DOWN, 476

OBJ_ISLAND_HOUSEROOMENTRANCE:
objectDef OBJ_TYPE::DOOR, 993, DIRECTIONS::LEFT, 134
doorArgDef 0, 925, DIRECTIONS::LEFT, 150

OBJ_ISLAND_HOUSEROOMEXIT:
objectDef OBJ_TYPE::DOOR, 926, DIRECTIONS::RIGHT, 150
doorArgDef 0, 994, DIRECTIONS::RIGHT, 134

OBJ_MTITOI_HEALERHOUSEROOMEXIT:
objectDef OBJ_TYPE::DOOR, 894, DIRECTIONS::RIGHT, 134
doorArgDef 18, 2, DIRECTIONS::RIGHT, 294

OBJ_ISLAND_SCIENTIST:
objectDef OBJ_TYPE::STATIONARY_NPC, 998, DIRECTIONS::DOWN, 135
.addr SPRITEDEF_GLASSES_GUY
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_ISLAND_SCIENTIST
OBJ_DIALOGUE UMSG::ISLAND_SCIENTIST
OBJ_YESNO_IS_NO @J_YESNO_IS_NO-OBJ_ISLAND_SCIENTIST
OBJ_DIALOGUE UMSG::ISLAND_SCIENTIST_YES
OBJ_STOP
	@J_YESNO_IS_NO:
OBJ_DIALOGUE UMSG::ISLAND_SCIENTIST_NO
OBJ_STOP
	@J_IS_NOT_TALKING:
OBJ_IS_NOT_USING 69, @J_IS_NOT_USING-OBJ_ISLAND_SCIENTIST
OBJ_NOT_HAS_ITEM 69, @J_IS_NOT_USING-OBJ_ISLAND_SCIENTIST
OBJ_PICK_ITEM 69
OBJ_REMOVE_ITEM @J_IS_NOT_USING-OBJ_ISLAND_SCIENTIST
OBJ_IS_NOT_FLAG 87, @J_IS_NOT_FLAG-OBJ_ISLAND_SCIENTIST
OBJ_DIALOGUE UMSG::ISLAND_SCIENTIST_AFTER
OBJ_STOP
	@J_IS_NOT_FLAG:
OBJ_NOT_HAS_ITEM 0, @J_IS_NOT_USING-OBJ_ISLAND_SCIENTIST
OBJ_PICK_ITEM 28
OBJ_GIVE_ITEM @J_IS_NOT_USING-OBJ_ISLAND_SCIENTIST
.ifdef VER_JP
OBJ_PLAY_SOUND 6
.endif
OBJ_SET_FLAG 87
OBJ_DIALOGUE UMSG::ISLAND_SCIENTIST_GIVE
.ifndef VER_JP
OBJ_PLAY_SOUND 6
.endif
	@J_IS_NOT_USING:
OBJ_STOP

OBJ_ISLAND_ABLE:
objectDef OBJ_TYPE::WANDERING_NPC, 920, DIRECTIONS::RIGHT, 150
.addr SPRITEDEF_ABLE_BAKER
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_ISLAND_ABLE
OBJ_DIALOGUE UMSG::ISLAND_ABLE
OBJ_STOP
	@J_IS_NOT_TALKING:
OBJ_IS_NOT_USING 69, @J_IS_NOT_USING-OBJ_ISLAND_ABLE
OBJ_NOT_HAS_ITEM 69, @J_IS_NOT_USING-OBJ_ISLAND_ABLE
OBJ_PICK_ITEM 69
OBJ_REMOVE_ITEM @J_IS_NOT_USING-OBJ_ISLAND_ABLE
OBJ_IS_NOT_FLAG 88, @J_IS_NOT_FLAG-OBJ_ISLAND_ABLE
OBJ_DIALOGUE UMSG::ISLAND_SCIENTIST_AFTER
OBJ_STOP
	@J_IS_NOT_FLAG:
OBJ_DIALOGUE UMSG::ISLAND_ABLE_GIVE
OBJ_SET_FLAG 88
	@J_IS_NOT_USING:
OBJ_STOP

OBJ_ISLAND_BAKER:
objectDef OBJ_TYPE::WANDERING_NPC, 922, DIRECTIONS::LEFT, 151
.addr SPRITEDEF_ABLE_BAKER
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_ISLAND_BAKER
OBJ_DIALOGUE UMSG::ISLAND_BAKER
OBJ_STOP
	@J_IS_NOT_TALKING:
OBJ_IS_NOT_USING 69, @J_IS_NOT_USING-OBJ_ISLAND_BAKER
OBJ_NOT_HAS_ITEM 69, @J_IS_NOT_USING-OBJ_ISLAND_BAKER
OBJ_PICK_ITEM 69
OBJ_REMOVE_ITEM @J_IS_NOT_USING-OBJ_ISLAND_BAKER
OBJ_IS_NOT_FLAG 89, @J_IS_NOT_FLAG-OBJ_ISLAND_BAKER
OBJ_DIALOGUE UMSG::ISLAND_SCIENTIST_AFTER
OBJ_STOP
	@J_IS_NOT_FLAG:
OBJ_DIALOGUE UMSG::ISLAND_BAKER_GIVE
OBJ_NOT_HAS_ITEM 0, @J_IS_NOT_USING-OBJ_ISLAND_BAKER
OBJ_PICK_ITEM 29
OBJ_GIVE_ITEM @J_IS_NOT_USING-OBJ_ISLAND_BAKER
OBJ_PLAY_SOUND 6
OBJ_SET_FLAG 89
	@J_IS_NOT_USING:
OBJ_STOP

OBJ_GRAVEYARD_PRIEST:
objectDef OBJ_TYPE::STATIONARY_NPC, 834, DIRECTIONS::RIGHT, 150
.addr SPRITEDEF_PRIEST
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_GRAVEYARD_PRIEST
OBJ_DIALOGUE UMSG::GRAVEYARD_PRIEST
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_SNOWMAN_PRIEST:
objectDef OBJ_TYPE::STATIONARY_NPC, 802, DIRECTIONS::RIGHT, 150
.addr SPRITEDEF_PRIEST
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_SNOWMAN_PRIEST
OBJ_NOT_HAS_CHARACTER 2, @J_NOT_HAS_CHARACTER-OBJ_SNOWMAN_PRIEST
OBJ_HAS_STATUS %10000000, @J_HAS_STATUS-OBJ_SNOWMAN_PRIEST
OBJ_DIALOGUE UMSG::SNOWMAN_PRIEST_AFTER
OBJ_SLEEP
OBJ_DIALOGUE UMSG::SNOWMAN_PRIEST_GOODBYE
OBJ_STOP
	@J_HAS_STATUS:
OBJ_DIALOGUE UMSG::SNOWMAN_PRIEST_ANADEAD
OBJ_STOP
	@J_NOT_HAS_CHARACTER:
OBJ_DIALOGUE UMSG::SNOWMAN_PRIEST
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_SNOWMAN_ANA:
objectDef OBJ_TYPE::STATIONARY_NPC_CHECKSPAWN, 807, DIRECTIONS::RIGHT, 148
.addr SPRITEDEF_ANA_NOHAT
OBJ_FLAG_DISAPPEAR 92
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_SNOWMAN_ANA
OBJ_DIALOGUE UMSG::SNOWMAN_ANA
OBJ_STOP
	@J_IS_NOT_TALKING:
OBJ_IS_NOT_USING 98, @J_IS_NOT_USING-OBJ_SNOWMAN_ANA
OBJ_NOT_HAS_ITEM 98, @J_IS_NOT_USING-OBJ_SNOWMAN_ANA
OBJ_PICK_ITEM 98
OBJ_REMOVE_ITEM @J_IS_NOT_USING-OBJ_SNOWMAN_ANA
OBJ_DIALOGUE UMSG::SNOWMAN_ANA_NINTEN
OBJ_YESNO_IS_NO @J_YESNO_IS_NO-OBJ_SNOWMAN_ANA
OBJ_JUMP @J_JUMP-OBJ_SNOWMAN_ANA
	@J_YESNO_IS_NO:
OBJ_DIALOGUE UMSG::SNOWMAN_ANA_SILLY
	@J_JUMP:
OBJ_DIALOGUE UMSG::SNOWMAN_ANA_GO
OBJ_MOVE @MOVE_DATA_1
OBJ_DIALOGUE UMSG::SNOWMAN_ANA_GOODBYE
OBJ_PICK_CHARACTER_J 1, @J_PICK_CHARACTER_J-OBJ_SNOWMAN_ANA
OBJ_MOVE @MOVE_DATA_2
OBJ_JUMP @J_JUMP1-OBJ_SNOWMAN_ANA
	@J_PICK_CHARACTER_J:
OBJ_MOVE @MOVE_DATA_3
	@J_JUMP1:
OBJ_ADD_CHARACTER 2, @J_IS_NOT_USING-OBJ_SNOWMAN_ANA
OBJ_PLAY_MUSIC 33
OBJ_DELAY 180
OBJ_PLAY_MUSIC 10
OBJ_SET_FLAG 92
	@J_IS_NOT_USING:
OBJ_STOP

@MOVE_DATA_1:
moveDef DIRECTIONS::DOWN, 6, 2
moveDef DIRECTIONS::LEFT, 6, 4
OBJ_RETURN
@MOVE_DATA_2:
moveDef DIRECTIONS::DOWN, MOVE_CMD::MOVEFACE, 1
moveDef DIRECTIONS::RIGHT, MOVE_CMD::MOVEFACE, 3
moveDef DIRECTIONS::UP, MOVE_CMD::MOVEFACE, 1
OBJ_STOP
@MOVE_DATA_3:
moveDef DIRECTIONS::DOWN, MOVE_CMD::MOVEFACE, 1
moveDef DIRECTIONS::RIGHT, MOVE_CMD::MOVEFACE, 2
moveDef DIRECTIONS::UP, MOVE_CMD::MOVEFACE, 1
OBJ_STOP

OBJ_ELLAY_TOWERBELLHOP:
objectDef OBJ_TYPE::STATIONARY_NPC, 41, DIRECTIONS::DOWN, 212
.addr SPRITEDEF_BELLHOP_WOMAN
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_ELLAY_TOWERBELLHOP
OBJ_DIALOGUE UMSG::ELLAY_TOWERBELLHOP
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_ELLAY_TOWER_GUY:
objectDef OBJ_TYPE::WANDERING_NPC, 39, DIRECTIONS::DOWN, 214
.addr SPRITEDEF_ABLE_BAKER
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_ELLAY_TOWER_GUY
OBJ_DIALOGUE UMSG::ELLAY_TOWER_GUY
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_MTITOI_FALLINLOVENINTEN:
objectDef OBJ_TYPE::STATIONARY_NPC_CHECKSPAWN, 888, DIRECTIONS::LEFT, 134
.addr SPRITEDEF_NINTEN
OBJ_FLAG_APPEAR 255
OBJ_IS_SIGNAL @J_IS_SIGNAL-OBJ_MTITOI_FALLINLOVENINTEN
OBJ_SIGNAL 18
OBJ_MOVE @MOVE_DATA
	@J_IS_SIGNAL:
OBJ_STOP

@MOVE_DATA:
moveDef DIRECTIONS::LEFT, MOVE_CMD::MOVE, 1
moveDef DIRECTIONS::RIGHT, MOVE_CMD::ABOUTFACE, 8
moveDef DIRECTIONS::RIGHT, MOVE_CMD::MOVE, 1
moveDef DIRECTIONS::LEFT, MOVE_CMD::ABOUTFACE, 8
moveDef DIRECTIONS::LEFT, MOVE_CMD::MOVE, 1
moveDef DIRECTIONS::RIGHT, MOVE_CMD::ABOUTFACE, 8
moveDef DIRECTIONS::RIGHT, MOVE_CMD::MOVE, 1
moveDef DIRECTIONS::LEFT, MOVE_CMD::ABOUTFACE, 8
moveDef DIRECTIONS::UP, MOVE_CMD::MOVE, 1
moveDef DIRECTIONS::DOWN, MOVE_CMD::ABOUTFACE, 1
moveDef DIRECTIONS::LEFT, MOVE_CMD::MOVE, 1
moveDef DIRECTIONS::RIGHT, MOVE_CMD::ABOUTFACE, 1
moveDef DIRECTIONS::DOWN, MOVE_CMD::MOVE, 1
moveDef DIRECTIONS::RIGHT, MOVE_CMD::ABOUTFACE, 4
moveDef DIRECTIONS::RIGHT, MOVE_CMD::MOVE, 1
moveDef DIRECTIONS::LEFT, MOVE_CMD::ABOUTFACE, 8
moveDef DIRECTIONS::DOWN, MOVE_CMD::MOVE, 1
moveDef DIRECTIONS::UP, MOVE_CMD::ABOUTFACE, 1
moveDef DIRECTIONS::LEFT, MOVE_CMD::MOVE, 1
moveDef DIRECTIONS::RIGHT, MOVE_CMD::ABOUTFACE, 1
moveDef DIRECTIONS::UP, MOVE_CMD::MOVE, 1
moveDef DIRECTIONS::RIGHT, MOVE_CMD::ABOUTFACE, 4
moveDef DIRECTIONS::RIGHT, MOVE_CMD::MOVE, 1
moveDef DIRECTIONS::LEFT, MOVE_CMD::ABOUTFACE, 8
moveDef DIRECTIONS::UP, MOVE_CMD::MOVE, 1
moveDef DIRECTIONS::DOWN, MOVE_CMD::ABOUTFACE, 1
moveDef DIRECTIONS::LEFT, MOVE_CMD::MOVE, 1
moveDef DIRECTIONS::RIGHT, MOVE_CMD::ABOUTFACE, 1
moveDef DIRECTIONS::DOWN, MOVE_CMD::MOVE, 1
moveDef DIRECTIONS::RIGHT, MOVE_CMD::ABOUTFACE, 4
moveDef DIRECTIONS::DOWN, MOVE_CMD::MOVE, 1
moveDef DIRECTIONS::UP, MOVE_CMD::ABOUTFACE, 1
moveDef DIRECTIONS::RIGHT, MOVE_CMD::MOVE, 1
moveDef DIRECTIONS::LEFT, MOVE_CMD::ABOUTFACE, 1
moveDef DIRECTIONS::UP, MOVE_CMD::MOVE, 1
moveDef DIRECTIONS::LEFT, MOVE_CMD::ABOUTFACE, 4
moveDef DIRECTIONS::LEFT, MOVE_CMD::MOVE, 1
moveDef DIRECTIONS::RIGHT, MOVE_CMD::ABOUTFACE, 8
moveDef DIRECTIONS::RIGHT, MOVE_CMD::MOVE, 1
moveDef DIRECTIONS::LEFT, MOVE_CMD::ABOUTFACE, 8
moveDef DIRECTIONS::LEFT, MOVE_CMD::MOVE, 1
moveDef DIRECTIONS::RIGHT, MOVE_CMD::ABOUTFACE, 8
moveDef DIRECTIONS::RIGHT, MOVE_CMD::MOVE, 1
moveDef DIRECTIONS::LEFT, MOVE_CMD::ABOUTFACE, 8
moveDef DIRECTIONS::RIGHT, MOVE_CMD::MOVE, 1
moveDef DIRECTIONS::UP, MOVE_CMD::MOVE, 1
moveDef DIRECTIONS::DOWN, MOVE_CMD::ABOUTFACE, 1
moveDef DIRECTIONS::LEFT, MOVE_CMD::MOVE, 3
moveDef DIRECTIONS::RIGHT, MOVE_CMD::ABOUTFACE, 1
moveDef DIRECTIONS::DOWN, MOVE_CMD::MOVE, 2
moveDef DIRECTIONS::UP, MOVE_CMD::ABOUTFACE, 1
moveDef DIRECTIONS::RIGHT, MOVE_CMD::MOVE, 3
moveDef DIRECTIONS::LEFT, MOVE_CMD::ABOUTFACE, 1
moveDef DIRECTIONS::UP, MOVE_CMD::MOVE, 1
moveDef DIRECTIONS::LEFT, MOVE_CMD::MOVE, 1
moveDef DIRECTIONS::LEFT, MOVE_CMD::ABOUTFACE, 2
moveDef DIRECTIONS::UP, MOVE_CMD::ABOUTFACE, 1
moveDef DIRECTIONS::RIGHT, MOVE_CMD::ABOUTFACE, 1
moveDef DIRECTIONS::DOWN, MOVE_CMD::ABOUTFACE, 1
moveDef DIRECTIONS::LEFT, MOVE_CMD::ABOUTFACE, 1
moveDef DIRECTIONS::UP, MOVE_CMD::ABOUTFACE, 1
moveDef DIRECTIONS::RIGHT, MOVE_CMD::ABOUTFACE, 1
moveDef DIRECTIONS::DOWN, MOVE_CMD::ABOUTFACE, 1
moveDef DIRECTIONS::LEFT, MOVE_CMD::ABOUTFACE, 2
moveDef DIRECTIONS::UP_LEFT, MOVE_CMD::MOVEFACE, 1
moveDef DIRECTIONS::DOWN_LEFT, MOVE_CMD::MOVEFACE, 1
moveDef DIRECTIONS::DOWN_RIGHT, MOVE_CMD::MOVEFACE, 1
moveDef DIRECTIONS::UP_RIGHT, MOVE_CMD::MOVEFACE, 1
moveDef DIRECTIONS::UP_LEFT, MOVE_CMD::MOVEFACE, 1
moveDef DIRECTIONS::DOWN_LEFT, MOVE_CMD::MOVEFACE, 1
moveDef DIRECTIONS::DOWN_RIGHT, MOVE_CMD::MOVEFACE, 1
moveDef DIRECTIONS::UP_RIGHT, MOVE_CMD::MOVEFACE, 1
moveDef DIRECTIONS::LEFT, MOVE_CMD::ABOUTFACE, 1
moveDef DIRECTIONS::UP, MOVE_CMD::ABOUTFACE, 1
moveDef DIRECTIONS::RIGHT, MOVE_CMD::ABOUTFACE, 1
moveDef DIRECTIONS::DOWN, MOVE_CMD::ABOUTFACE, 1
moveDef DIRECTIONS::LEFT, MOVE_CMD::ABOUTFACE, 1
moveDef DIRECTIONS::UP, MOVE_CMD::ABOUTFACE, 1
moveDef DIRECTIONS::RIGHT, MOVE_CMD::ABOUTFACE, 1
moveDef DIRECTIONS::DOWN, MOVE_CMD::ABOUTFACE, 1
moveDef DIRECTIONS::LEFT, MOVE_CMD::ABOUTFACE, 2
moveDef DIRECTIONS::UP_LEFT, MOVE_CMD::MOVEFACE, 1
moveDef DIRECTIONS::DOWN_LEFT, MOVE_CMD::MOVEFACE, 1
moveDef DIRECTIONS::DOWN_RIGHT, MOVE_CMD::MOVEFACE, 1
moveDef DIRECTIONS::UP_RIGHT, MOVE_CMD::MOVEFACE, 1
moveDef DIRECTIONS::UP_LEFT, MOVE_CMD::MOVEFACE, 1
moveDef DIRECTIONS::DOWN_LEFT, MOVE_CMD::MOVEFACE, 1
moveDef DIRECTIONS::DOWN_RIGHT, MOVE_CMD::MOVEFACE, 1
moveDef DIRECTIONS::UP_RIGHT, MOVE_CMD::MOVEFACE, 1
moveDef DIRECTIONS::LEFT, MOVE_CMD::ABOUTFACE, 1
moveDef DIRECTIONS::LEFT, MOVE_CMD::ABOUTFACE, 1
OBJ_STOP


OBJ_MTITOI_FALLINLOVEANA:
objectDef OBJ_TYPE::STATIONARY_NPC_CHECKSPAWN, 893, DIRECTIONS::LEFT, 134
.addr SPRITEDEF_ANA
OBJ_FLAG_APPEAR 125
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_MTITOI_FALLINLOVEANA
OBJ_DIALOGUE UMSG::MTITOI_ANA
OBJ_YESNO_IS_NO @J_YESNO_IS_NO-OBJ_MTITOI_FALLINLOVEANA
OBJ_JUMP @J_JUMP-OBJ_MTITOI_FALLINLOVEANA
	@J_YESNO_IS_NO:
OBJ_DIALOGUE UMSG::MTITOI_ANA_NO
	@J_JUMP:
OBJ_DIALOGUE UMSG::MTITOI_ANA2
OBJ_MOVE @MOVE_DATA_1
OBJ_SET_FLAG 255
OBJ_PLAY_MUSIC 8
OBJ_PLAY_MUSIC 21
OBJ_DELAY 240
OBJ_DELAY 240
OBJ_DELAY 80
OBJ_SIGNAL 17
OBJ_STOP
	@J_IS_NOT_TALKING:
OBJ_IS_SIGNAL @J_IS_SIGNAL-OBJ_MTITOI_FALLINLOVEANA
OBJ_MOVE @MOVE_DATA_2
OBJ_CLEAR_FLAG 255
OBJ_DELAY 240
OBJ_DELAY 40
OBJ_DIALOGUE UMSG::MTITOI_ANALOVE
OBJ_YESNO_IS_NO @J_YESNO_IS_NO1-OBJ_MTITOI_FALLINLOVEANA
OBJ_DIALOGUE UMSG::MTITOI_ANALOVE_YES
OBJ_JUMP @J_JUMP1-OBJ_MTITOI_FALLINLOVEANA
	@J_YESNO_IS_NO1:
OBJ_DIALOGUE UMSG::MTITOI_ANALOVE_NO
	@J_JUMP1:
OBJ_MOVE @MOVE_DATA_3
OBJ_ADD_CHARACTER 2, @J_IS_SIGNAL-OBJ_MTITOI_FALLINLOVEANA
OBJ_CLEAR_FLAG 125
OBJ_SET_FLAG 200
OBJ_SIGNAL 19
OBJ_MOVE @MOVE_DATA_4
	@J_IS_SIGNAL:
OBJ_STOP

@MOVE_DATA_1:
moveDef DIRECTIONS::LEFT, 6, 1
moveDef DIRECTIONS::RIGHT, MOVE_CMD::ABOUTFACE, 1
moveDef DIRECTIONS::LEFT, 7, 5
moveDef DIRECTIONS::RIGHT, MOVE_CMD::ABOUTFACE, 1
OBJ_RETURN

@MOVE_DATA_2:
moveDef DIRECTIONS::RIGHT, MOVE_CMD::MOVE, 1
moveDef DIRECTIONS::LEFT, MOVE_CMD::ABOUTFACE, 8
moveDef DIRECTIONS::LEFT, MOVE_CMD::MOVE, 1
moveDef DIRECTIONS::RIGHT, MOVE_CMD::ABOUTFACE, 8
moveDef DIRECTIONS::RIGHT, MOVE_CMD::MOVE, 1
moveDef DIRECTIONS::LEFT, MOVE_CMD::ABOUTFACE, 8
moveDef DIRECTIONS::LEFT, MOVE_CMD::MOVE, 1
moveDef DIRECTIONS::RIGHT, MOVE_CMD::ABOUTFACE, 8
moveDef DIRECTIONS::DOWN, MOVE_CMD::MOVE, 1
moveDef DIRECTIONS::UP, MOVE_CMD::ABOUTFACE, 1
moveDef DIRECTIONS::RIGHT, MOVE_CMD::MOVE, 1
moveDef DIRECTIONS::LEFT, MOVE_CMD::ABOUTFACE, 1
moveDef DIRECTIONS::UP, MOVE_CMD::MOVE, 1
moveDef DIRECTIONS::LEFT, MOVE_CMD::ABOUTFACE, 4
moveDef DIRECTIONS::LEFT, MOVE_CMD::MOVE, 1
moveDef DIRECTIONS::RIGHT, MOVE_CMD::ABOUTFACE, 8
moveDef DIRECTIONS::UP, MOVE_CMD::MOVE, 1
moveDef DIRECTIONS::DOWN, MOVE_CMD::ABOUTFACE, 1
moveDef DIRECTIONS::RIGHT, MOVE_CMD::MOVE, 1
moveDef DIRECTIONS::LEFT, MOVE_CMD::ABOUTFACE, 1
moveDef DIRECTIONS::DOWN, MOVE_CMD::MOVE, 1
moveDef DIRECTIONS::LEFT, MOVE_CMD::ABOUTFACE, 4
moveDef DIRECTIONS::LEFT, MOVE_CMD::MOVE, 1
moveDef DIRECTIONS::RIGHT, MOVE_CMD::ABOUTFACE, 8
moveDef DIRECTIONS::DOWN, MOVE_CMD::MOVE, 1
moveDef DIRECTIONS::UP, MOVE_CMD::ABOUTFACE, 1
moveDef DIRECTIONS::RIGHT, MOVE_CMD::MOVE, 1
moveDef DIRECTIONS::LEFT, MOVE_CMD::ABOUTFACE, 1
moveDef DIRECTIONS::UP, MOVE_CMD::MOVE, 1
moveDef DIRECTIONS::LEFT, MOVE_CMD::ABOUTFACE, 4
moveDef DIRECTIONS::UP, MOVE_CMD::MOVE, 1
moveDef DIRECTIONS::DOWN, MOVE_CMD::ABOUTFACE, 1
moveDef DIRECTIONS::LEFT, MOVE_CMD::MOVE, 1
moveDef DIRECTIONS::RIGHT, MOVE_CMD::ABOUTFACE, 1
moveDef DIRECTIONS::DOWN, MOVE_CMD::MOVE, 1
moveDef DIRECTIONS::RIGHT, MOVE_CMD::ABOUTFACE, 4
moveDef DIRECTIONS::RIGHT, MOVE_CMD::MOVE, 1
moveDef DIRECTIONS::LEFT, MOVE_CMD::ABOUTFACE, 8
moveDef DIRECTIONS::LEFT, MOVE_CMD::MOVE, 1
moveDef DIRECTIONS::RIGHT, MOVE_CMD::ABOUTFACE, 8
moveDef DIRECTIONS::RIGHT, MOVE_CMD::MOVE, 1
moveDef DIRECTIONS::LEFT, MOVE_CMD::ABOUTFACE, 8
moveDef DIRECTIONS::LEFT, MOVE_CMD::MOVE, 1
moveDef DIRECTIONS::RIGHT, MOVE_CMD::ABOUTFACE, 8
moveDef DIRECTIONS::LEFT, MOVE_CMD::MOVE, 1
moveDef DIRECTIONS::DOWN, MOVE_CMD::MOVE, 1
moveDef DIRECTIONS::UP, MOVE_CMD::ABOUTFACE, 1
moveDef DIRECTIONS::RIGHT, MOVE_CMD::MOVE, 3
moveDef DIRECTIONS::LEFT, MOVE_CMD::ABOUTFACE, 1
moveDef DIRECTIONS::UP, MOVE_CMD::MOVE, 2
moveDef DIRECTIONS::DOWN, MOVE_CMD::ABOUTFACE, 1
moveDef DIRECTIONS::LEFT, MOVE_CMD::MOVE, 3
moveDef DIRECTIONS::RIGHT, MOVE_CMD::ABOUTFACE, 1
moveDef DIRECTIONS::DOWN, MOVE_CMD::MOVE, 1
moveDef DIRECTIONS::RIGHT, MOVE_CMD::MOVE, 1
moveDef DIRECTIONS::RIGHT, MOVE_CMD::ABOUTFACE, 2
moveDef DIRECTIONS::UP_RIGHT, MOVE_CMD::MOVEFACE, 1
moveDef DIRECTIONS::DOWN_RIGHT, MOVE_CMD::MOVEFACE, 1
moveDef DIRECTIONS::DOWN_LEFT, MOVE_CMD::MOVEFACE, 1
moveDef DIRECTIONS::UP_LEFT, MOVE_CMD::MOVEFACE, 1
moveDef DIRECTIONS::UP_RIGHT, MOVE_CMD::MOVEFACE, 1
moveDef DIRECTIONS::DOWN_RIGHT, MOVE_CMD::MOVEFACE, 1
moveDef DIRECTIONS::DOWN_LEFT, MOVE_CMD::MOVEFACE, 1
moveDef DIRECTIONS::UP_LEFT, MOVE_CMD::MOVEFACE, 1
moveDef DIRECTIONS::RIGHT, MOVE_CMD::ABOUTFACE, 1
moveDef DIRECTIONS::UP, MOVE_CMD::ABOUTFACE, 1
moveDef DIRECTIONS::LEFT, MOVE_CMD::ABOUTFACE, 1
moveDef DIRECTIONS::DOWN, MOVE_CMD::ABOUTFACE, 1
moveDef DIRECTIONS::RIGHT, MOVE_CMD::ABOUTFACE, 1
moveDef DIRECTIONS::UP, MOVE_CMD::ABOUTFACE, 1
moveDef DIRECTIONS::LEFT, MOVE_CMD::ABOUTFACE, 1
moveDef DIRECTIONS::DOWN, MOVE_CMD::ABOUTFACE, 1
moveDef DIRECTIONS::RIGHT, MOVE_CMD::ABOUTFACE, 2
moveDef DIRECTIONS::UP_RIGHT, MOVE_CMD::MOVEFACE, 1
moveDef DIRECTIONS::DOWN_RIGHT, MOVE_CMD::MOVEFACE, 1
moveDef DIRECTIONS::DOWN_LEFT, MOVE_CMD::MOVEFACE, 1
moveDef DIRECTIONS::UP_LEFT, MOVE_CMD::MOVEFACE, 1
moveDef DIRECTIONS::UP_RIGHT, MOVE_CMD::MOVEFACE, 1
moveDef DIRECTIONS::DOWN_RIGHT, MOVE_CMD::MOVEFACE, 1
moveDef DIRECTIONS::DOWN_LEFT, MOVE_CMD::MOVEFACE, 1
moveDef DIRECTIONS::UP_LEFT, MOVE_CMD::MOVEFACE, 1
moveDef DIRECTIONS::RIGHT, MOVE_CMD::ABOUTFACE, 1
moveDef DIRECTIONS::UP, MOVE_CMD::ABOUTFACE, 1
moveDef DIRECTIONS::LEFT, MOVE_CMD::ABOUTFACE, 1
moveDef DIRECTIONS::DOWN, MOVE_CMD::ABOUTFACE, 1
moveDef DIRECTIONS::RIGHT, MOVE_CMD::ABOUTFACE, 1
moveDef DIRECTIONS::UP, MOVE_CMD::ABOUTFACE, 1
moveDef DIRECTIONS::LEFT, MOVE_CMD::ABOUTFACE, 1
moveDef DIRECTIONS::DOWN, MOVE_CMD::ABOUTFACE, 1
moveDef DIRECTIONS::RIGHT, MOVE_CMD::ABOUTFACE, 2
moveDef DIRECTIONS::RIGHT, MOVE_CMD::ABOUTFACE, 1
moveDef DIRECTIONS::RIGHT, MOVE_CMD::ABOUTFACE, 2
OBJ_RETURN
@MOVE_DATA_3:
moveDef DIRECTIONS::RIGHT, MOVE_CMD::MOVEFACE, 2
OBJ_RETURN
@MOVE_DATA_4:
OBJ_STOP

OBJ_MTITOI_FALLINLOVETEDDY:
objectDef OBJ_TYPE::STATIONARY_NPC_CHECKSPAWN, 893, DIRECTIONS::LEFT, 134
.addr SPRITEDEF_TEDDY
OBJ_FLAG_APPEAR 1
OBJ_IS_SIGNAL @J_IS_SIGNAL-OBJ_MTITOI_FALLINLOVETEDDY
OBJ_MOVE @MOVE_DATA_1
OBJ_DIALOGUE UMSG::MTITOI_TEDDY_POSTDANCE
OBJ_MOVE @MOVE_DATA_2
OBJ_PLAY_SOUND2 2
OBJ_DIALOGUE UMSG::MTITOI_TEDDYLEAVE
OBJ_PLAY_SOUND2 2
OBJ_MOVE @MOVE_DATA_3
OBJ_PLAY_SOUND2 2
OBJ_DIALOGUE UMSG::MTITOI_TEDDYLEAVE2
OBJ_PLAY_SOUND2 2
OBJ_DELAY 30
OBJ_ADD_CHARACTER 4, @J_IS_SIGNAL-OBJ_MTITOI_FALLINLOVETEDDY
OBJ_CLEAR_FLAG 123
OBJ_SET_FLAG 201
OBJ_SET_FLAG 202
OBJ_SET_FLAG 203
OBJ_SET_FLAG 204
OBJ_SET_FLAG 255
OBJ_SET_FLAG 140
OBJ_SET_FLAG 142
OBJ_SET_FLAG 143
OBJ_BATTLE 145
OBJ_MOVE @MOVE_DATA_4
	@J_IS_SIGNAL:
OBJ_STOP

@MOVE_DATA_1:
moveDef DIRECTIONS::DOWN_LEFT, MOVE_CMD::MOVEFACE, 1
moveDef DIRECTIONS::LEFT, MOVE_CMD::MOVEFACE, 5
moveDef DIRECTIONS::UP, MOVE_CMD::MOVEFACE, 1
moveDef DIRECTIONS::RIGHT, MOVE_CMD::ABOUTFACE, 1
OBJ_RETURN
@MOVE_DATA_2:
moveDef DIRECTIONS::DOWN_RIGHT, 6, 1
moveDef DIRECTIONS::UP_RIGHT, 6, 1
moveDef DIRECTIONS::RIGHT, 6, 4
OBJ_RETURN
@MOVE_DATA_3:
moveDef DIRECTIONS::DOWN, MOVE_CMD::MOVEFACE, 1
moveDef DIRECTIONS::LEFT, MOVE_CMD::MOVEFACE, 3
moveDef DIRECTIONS::UP, MOVE_CMD::MOVEFACE, 1
moveDef DIRECTIONS::LEFT, MOVE_CMD::ABOUTFACE, 1
moveDef DIRECTIONS::UP, MOVE_CMD::ABOUTFACE, 1
moveDef DIRECTIONS::LEFT, MOVE_CMD::ABOUTFACE, 1
OBJ_RETURN
@MOVE_DATA_4:
OBJ_STOP
