OBJ_BANK_2E:
.addr OBJ_ROSEMARYHOUSE_EXIT
.addr OBJ_ROSEMARYHOUSE_DOOR49
.addr OBJ_ROSEMARYHOUSE_DOOR50
.addr OBJ_ROSEMARYHOUSE_DOOR51
.addr OBJ_ROSEMARYHOUSE_DOOR52
.addr OBJ_ROSEMARYHOUSE_DOOR53
.addr OBJ_ROSEMARYHOUSE_DOOR54
.addr OBJ_ROSEMARYHOUSE_DOOR55
.addr OBJ_ROSEMARYHOUSE_DOOR56
.addr OBJ_ROSEMARYHOUSE_DOOR57
.addr OBJ_ROSEMARYHOUSE_DOOR58
.addr OBJ_ROSEMARYHOUSE_DOOR59
.addr OBJ_ROSEMARYHOUSE_DOOR60
.addr OBJ_ROSEMARYHOUSE_DOOR61
.addr OBJ_ROSEMARYHOUSE_DOOR62
.addr OBJ_ROSEMARYHOUSE_MOUSE
.addr OBJ_ROSEMARYHOUSE_NOBODYHERE
.addr OBJ_ROSEMARYHOUSE_HAHAHA
.addr 0

OBJ_ROSEMARYHOUSE_EXIT:
objectDef OBJ_TYPE::DOOR, 734, DIRECTIONS::RIGHT, 134
doorArgDef 6, 760, DIRECTIONS::DOWN, 806

OBJ_ROSEMARYHOUSE_DOOR49:
objectDef OBJ_TYPE::DOOR, 722, DIRECTIONS::LEFT, 133
doorArgDef 0, 445, DIRECTIONS::LEFT, 134

OBJ_ROSEMARYHOUSE_DOOR50:
objectDef OBJ_TYPE::DOOR, 720, DIRECTIONS::LEFT, 135
doorArgDef 0, 477, DIRECTIONS::LEFT, 134

OBJ_ROSEMARYHOUSE_DOOR51:
objectDef OBJ_TYPE::DOOR, 446, DIRECTIONS::RIGHT, 134
doorArgDef 0, 723, DIRECTIONS::RIGHT, 133

OBJ_ROSEMARYHOUSE_DOOR52:
objectDef OBJ_TYPE::DOOR, 434, DIRECTIONS::LEFT, 133
doorArgDef 0, 654, DIRECTIONS::LEFT, 978

OBJ_ROSEMARYHOUSE_DOOR53:
objectDef OBJ_TYPE::DOOR, 432, DIRECTIONS::LEFT, 135
doorArgDef 0, 29, DIRECTIONS::LEFT, 166

OBJ_ROSEMARYHOUSE_DOOR54:
objectDef OBJ_TYPE::DOOR, 478, DIRECTIONS::RIGHT, 134
doorArgDef 0, 721, DIRECTIONS::RIGHT, 135

OBJ_ROSEMARYHOUSE_DOOR55:
objectDef OBJ_TYPE::DOOR, 466, DIRECTIONS::LEFT, 133
doorArgDef 0, 605, DIRECTIONS::LEFT, 134

OBJ_ROSEMARYHOUSE_DOOR56:
objectDef OBJ_TYPE::DOOR, 464, DIRECTIONS::LEFT, 135
doorArgDef 0, 61, DIRECTIONS::LEFT, 166

OBJ_ROSEMARYHOUSE_DOOR57:
objectDef OBJ_TYPE::DOOR, 510, DIRECTIONS::RIGHT, 134
doorArgDef 0, 593, DIRECTIONS::RIGHT, 1019

OBJ_ROSEMARYHOUSE_DOOR58:
objectDef OBJ_TYPE::DOOR, 498, DIRECTIONS::LEFT, 133
doorArgDef 0, 30, DIRECTIONS::LEFT, 134

OBJ_ROSEMARYHOUSE_DOOR59:
objectDef OBJ_TYPE::DOOR, 496, DIRECTIONS::LEFT, 135
doorArgDef 0, 637, DIRECTIONS::LEFT, 134

OBJ_ROSEMARYHOUSE_DOOR60:
objectDef OBJ_TYPE::DOOR, 30, DIRECTIONS::RIGHT, 166
doorArgDef 0, 433, DIRECTIONS::RIGHT, 135

OBJ_ROSEMARYHOUSE_DOOR61:
objectDef OBJ_TYPE::DOOR, 18, DIRECTIONS::LEFT, 165
doorArgDef 0, 29, DIRECTIONS::LEFT, 326

OBJ_ROSEMARYHOUSE_DOOR62:
objectDef OBJ_TYPE::DOOR, 16, DIRECTIONS::LEFT, 167
doorArgDef 0, 61, DIRECTIONS::LEFT, 262

OBJ_ROSEMARYHOUSE_MOUSE:
objectDef 34, 723, DIRECTIONS::RIGHT, 134
.addr SPRITEDEF_MOUSE
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_ROSEMARYHOUSE_MOUSE
OBJ_DIALOGUE UMSG::ROSEMARYHOUSE_MOUSE
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_ROSEMARYHOUSE_NOBODYHERE:
objectDef OBJ_TYPE::TRIGGER_CHECKSPAWN, 19, DIRECTIONS::UP, 165
OBJ_FLAG_DISAPPEAR 15
OBJ_IS_NOT_TOUCHING @J_IS_NOT_TOUCHING-OBJ_ROSEMARYHOUSE_NOBODYHERE
OBJ_DIALOGUE UMSG::ROSEMARYHOUSE_NOBODYHERE
	@J_IS_NOT_TOUCHING:
OBJ_STOP

OBJ_ROSEMARYHOUSE_HAHAHA:
objectDef OBJ_TYPE::TRIGGER_CHECKSPAWN, 467, DIRECTIONS::UP, 133
OBJ_FLAG_DISAPPEAR 15
OBJ_IS_NOT_TOUCHING @J_IS_NOT_TOUCHING-OBJ_ROSEMARYHOUSE_HAHAHA
OBJ_DIALOGUE UMSG::SPOOKANE_HOTELBELLHOP
	@J_IS_NOT_TOUCHING:
OBJ_STOP

