OBJ_BANK_3B:
.addr OBJ_MAGICANT_FLYINGMANHOUSEEXIT
.addr OBJ_MAGICANT_GUITARMANEXIT
.addr OBJ_MAGICANT_COINSHOPEXIT
.addr OBJ_MAGICANT_RINGSHOPEXIT
.addr OBJ_MAGICANT_PENDANTSHOPEXIT
.addr OBJ_MAGICANT_INNEXIT
.addr OBJ_MAGICANT_HOSPITALEXIT
.addr OBJ_MAGICANT_MUSICSHOPEXIT
.addr OBJ_MAGICANT_FLYINGMAN1
.addr OBJ_MAGICANT_FLYINGMAN2
.addr OBJ_MAGICANT_FLYINGMAN3
.addr OBJ_MAGICANT_FLYINGMAN4
.addr OBJ_MAGICANT_FLYINGMAN5
.addr OBJ_MAGICANT_GUITARIST
.addr OBJ_MAGICANT_COINVENDOR
.addr OBJ_MAGICANT_RINGVENDOR
.addr OBJ_MAGICANT_PENDANTVENDOR
.addr OBJ_MAGICANT_INNKEEPER
.addr OBJ_MAGICANT_DOCTOR
.addr OBJ_MAGICANT_MUSICVENDOR
.addr 0

OBJ_MAGICANT_FLYINGMANHOUSEEXIT:
objectDef OBJ_TYPE::DOOR, 14, DIRECTIONS::RIGHT, 534
doorArgDef 0, 714, DIRECTIONS::DOWN, 596

OBJ_MAGICANT_GUITARMANEXIT:
objectDef OBJ_TYPE::DOOR, 46, DIRECTIONS::RIGHT, 534
doorArgDef 0, 606, DIRECTIONS::DOWN, 664

OBJ_MAGICANT_COINSHOPEXIT:
objectDef OBJ_TYPE::DOOR, 78, DIRECTIONS::RIGHT, 534
doorArgDef 0, 662, DIRECTIONS::DOWN, 660

OBJ_MAGICANT_RINGSHOPEXIT:
objectDef OBJ_TYPE::DOOR, 110, DIRECTIONS::RIGHT, 534
doorArgDef 0, 666, DIRECTIONS::DOWN, 660

OBJ_MAGICANT_PENDANTSHOPEXIT:
objectDef OBJ_TYPE::DOOR, 14, DIRECTIONS::RIGHT, 566
doorArgDef 0, 670, DIRECTIONS::DOWN, 660

OBJ_MAGICANT_INNEXIT:
objectDef OBJ_TYPE::DOOR, 46, DIRECTIONS::RIGHT, 566
doorArgDef 0, 654, DIRECTIONS::DOWN, 660

OBJ_MAGICANT_HOSPITALEXIT:
objectDef OBJ_TYPE::DOOR, 78, DIRECTIONS::RIGHT, 566
doorArgDef 0, 650, DIRECTIONS::DOWN, 660

OBJ_MAGICANT_MUSICSHOPEXIT:
objectDef OBJ_TYPE::DOOR, 110, DIRECTIONS::RIGHT, 566
doorArgDef 0, 646, DIRECTIONS::DOWN, 660

OBJ_MAGICANT_FLYINGMAN1:
objectDef OBJ_TYPE::WANDERING_NPC_CHECKSPAWN, 7, DIRECTIONS::DOWN, 532
.addr SPRITEDEF_FLYINGMAN
OBJ_FLAG_DISAPPEAR 100
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_MAGICANT_FLYINGMAN1
OBJ_SUBROUTINE OBJ_MAGICANT_FLYINGMAN1, SUBR_FLYINGMAN-OBJ_MAGICANT_FLYINGMAN1
OBJ_NOT_HAS_CHARACTER 7, @J_NOT_HAS_CHARACTER-OBJ_MAGICANT_FLYINGMAN1
OBJ_DIALOGUE UMSG::MAGICANT_FLYINGMAN_SERVE
OBJ_STOP
	@J_NOT_HAS_CHARACTER:
OBJ_IS_NOT_FLAG 110, @J_IS_NOT_FLAG-OBJ_MAGICANT_FLYINGMAN1
OBJ_DIALOGUE UMSG::MAGICANT_FLYINGMAN_REPLACE
OBJ_JUMP @J_JUMP-OBJ_MAGICANT_FLYINGMAN1
	@J_IS_NOT_FLAG:
OBJ_DIALOGUE UMSG::MAGICANT_FLYINGMAN_INTRO
	@J_JUMP:
OBJ_PICK_CHARACTER 7
OBJ_AND_STATUS 0
OBJ_HEAL 255
OBJ_PLAY_MUSIC 33
OBJ_DELAY 180
OBJ_PLAY_MUSIC 9
OBJ_ADD_CHARACTER 7, @J_IS_NOT_TALKING-OBJ_MAGICANT_FLYINGMAN1
OBJ_SET_FLAG 100
	@J_IS_NOT_TALKING:
OBJ_STOP

SUBR_FLYINGMAN:
OBJ_NOT_HAS_CHARACTER 7, @J_NOT_HAS_CHARACTER1-OBJ_MAGICANT_FLYINGMAN1
OBJ_RETURN
	@J_NOT_HAS_CHARACTER1:
OBJ_CLEAR_FLAG 0
OBJ_IS_NOT_FLAG 100, @J_IS_NOT_FLAG1-OBJ_MAGICANT_FLYINGMAN1
OBJ_SET_FLAG 0
OBJ_SET_FLAG 105
	@J_IS_NOT_FLAG1:
OBJ_IS_NOT_FLAG 101, @J_IS_NOT_FLAG2-OBJ_MAGICANT_FLYINGMAN1
OBJ_SET_FLAG 0
OBJ_SET_FLAG 106
	@J_IS_NOT_FLAG2:
OBJ_IS_NOT_FLAG 102, @J_IS_NOT_FLAG3-OBJ_MAGICANT_FLYINGMAN1
OBJ_SET_FLAG 0
OBJ_SET_FLAG 107
	@J_IS_NOT_FLAG3:
OBJ_IS_NOT_FLAG 103, @J_IS_NOT_FLAG4-OBJ_MAGICANT_FLYINGMAN1
OBJ_SET_FLAG 0
OBJ_SET_FLAG 108
	@J_IS_NOT_FLAG4:
OBJ_IS_NOT_FLAG 104, @J_IS_NOT_FLAG5-OBJ_MAGICANT_FLYINGMAN1
OBJ_SET_FLAG 0
OBJ_SET_FLAG 109
	@J_IS_NOT_FLAG5:
OBJ_IS_NOT_FLAG 0, @J_IS_NOT_FLAG6-OBJ_MAGICANT_FLYINGMAN1
OBJ_CLEAR_FLAG 0
OBJ_SET_FLAG 110
	@J_IS_NOT_FLAG6:
OBJ_RETURN

OBJ_MAGICANT_FLYINGMAN2:
objectDef OBJ_TYPE::WANDERING_NPC_CHECKSPAWN, 6, DIRECTIONS::DOWN, 533
.addr SPRITEDEF_FLYINGMAN
OBJ_FLAG_DISAPPEAR 101
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_MAGICANT_FLYINGMAN2
OBJ_SUBROUTINE OBJ_MAGICANT_FLYINGMAN1, SUBR_FLYINGMAN-OBJ_MAGICANT_FLYINGMAN1
OBJ_NOT_HAS_CHARACTER 7, @J_NOT_HAS_CHARACTER-OBJ_MAGICANT_FLYINGMAN2
OBJ_DIALOGUE UMSG::MAGICANT_FLYINGMAN_SERVE
OBJ_STOP
	@J_NOT_HAS_CHARACTER:
OBJ_IS_NOT_FLAG 110, @J_IS_NOT_FLAG-OBJ_MAGICANT_FLYINGMAN2
OBJ_DIALOGUE UMSG::MAGICANT_FLYINGMAN_REPLACE
OBJ_JUMP @J_JUMP-OBJ_MAGICANT_FLYINGMAN2
	@J_IS_NOT_FLAG:
OBJ_DIALOGUE UMSG::MAGICANT_FLYINGMAN_INTRO
	@J_JUMP:
OBJ_PICK_CHARACTER 7
OBJ_AND_STATUS 0
OBJ_HEAL 255
OBJ_PLAY_MUSIC 33
OBJ_DELAY 180
OBJ_PLAY_MUSIC 9
OBJ_ADD_CHARACTER 7, @J_IS_NOT_TALKING-OBJ_MAGICANT_FLYINGMAN2
OBJ_SET_FLAG 101
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_MAGICANT_FLYINGMAN3:
objectDef OBJ_TYPE::WANDERING_NPC_CHECKSPAWN, 5, DIRECTIONS::DOWN, 534
.addr SPRITEDEF_FLYINGMAN
OBJ_FLAG_DISAPPEAR 102
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_MAGICANT_FLYINGMAN3
OBJ_SUBROUTINE OBJ_MAGICANT_FLYINGMAN1, SUBR_FLYINGMAN-OBJ_MAGICANT_FLYINGMAN1
OBJ_NOT_HAS_CHARACTER 7, @J_NOT_HAS_CHARACTER-OBJ_MAGICANT_FLYINGMAN3
OBJ_DIALOGUE UMSG::MAGICANT_FLYINGMAN_SERVE
OBJ_STOP
	@J_NOT_HAS_CHARACTER:
OBJ_IS_NOT_FLAG 110, @J_IS_NOT_FLAG-OBJ_MAGICANT_FLYINGMAN3
OBJ_DIALOGUE UMSG::MAGICANT_FLYINGMAN_REPLACE
OBJ_JUMP @J_JUMP-OBJ_MAGICANT_FLYINGMAN3
	@J_IS_NOT_FLAG:
OBJ_DIALOGUE UMSG::MAGICANT_FLYINGMAN_INTRO
	@J_JUMP:
OBJ_PICK_CHARACTER 7
OBJ_AND_STATUS 0
OBJ_HEAL 255
OBJ_PLAY_MUSIC 33
OBJ_DELAY 180
OBJ_PLAY_MUSIC 9
OBJ_ADD_CHARACTER 7, @J_IS_NOT_TALKING-OBJ_MAGICANT_FLYINGMAN3
OBJ_SET_FLAG 102
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_MAGICANT_FLYINGMAN4:
objectDef OBJ_TYPE::WANDERING_NPC_CHECKSPAWN, 8, DIRECTIONS::DOWN, 533
.addr SPRITEDEF_FLYINGMAN
OBJ_FLAG_DISAPPEAR 103
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_MAGICANT_FLYINGMAN4
OBJ_SUBROUTINE OBJ_MAGICANT_FLYINGMAN1, SUBR_FLYINGMAN-OBJ_MAGICANT_FLYINGMAN1
OBJ_NOT_HAS_CHARACTER 7, @J_NOT_HAS_CHARACTER-OBJ_MAGICANT_FLYINGMAN4
OBJ_DIALOGUE UMSG::MAGICANT_FLYINGMAN_SERVE
OBJ_STOP
	@J_NOT_HAS_CHARACTER:
OBJ_IS_NOT_FLAG 110, @J_IS_NOT_FLAG-OBJ_MAGICANT_FLYINGMAN4
OBJ_DIALOGUE UMSG::MAGICANT_FLYINGMAN_REPLACE
OBJ_JUMP @J_JUMP-OBJ_MAGICANT_FLYINGMAN4
	@J_IS_NOT_FLAG:
OBJ_DIALOGUE UMSG::MAGICANT_FLYINGMAN_INTRO
	@J_JUMP:
OBJ_PICK_CHARACTER 7
OBJ_AND_STATUS 0
OBJ_HEAL 255
OBJ_PLAY_MUSIC 33
OBJ_DELAY 180
OBJ_PLAY_MUSIC 9
OBJ_ADD_CHARACTER 7, @J_IS_NOT_TALKING-OBJ_MAGICANT_FLYINGMAN4
OBJ_SET_FLAG 103
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_MAGICANT_FLYINGMAN5:
objectDef OBJ_TYPE::WANDERING_NPC_CHECKSPAWN, 7, DIRECTIONS::DOWN, 534
.addr SPRITEDEF_FLYINGMAN
OBJ_FLAG_DISAPPEAR 104
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_MAGICANT_FLYINGMAN5
OBJ_SUBROUTINE OBJ_MAGICANT_FLYINGMAN1, SUBR_FLYINGMAN-OBJ_MAGICANT_FLYINGMAN1
OBJ_NOT_HAS_CHARACTER 7, @J_NOT_HAS_CHARACTER-OBJ_MAGICANT_FLYINGMAN5
OBJ_DIALOGUE UMSG::MAGICANT_FLYINGMAN_SERVE
OBJ_STOP
	@J_NOT_HAS_CHARACTER:
OBJ_IS_NOT_FLAG 110, @J_IS_NOT_FLAG-OBJ_MAGICANT_FLYINGMAN5
OBJ_DIALOGUE UMSG::MAGICANT_FLYINGMAN_REPLACE
OBJ_JUMP @J_JUMP-OBJ_MAGICANT_FLYINGMAN5
	@J_IS_NOT_FLAG:
OBJ_DIALOGUE UMSG::MAGICANT_FLYINGMAN_INTRO
	@J_JUMP:
OBJ_PICK_CHARACTER 7
OBJ_AND_STATUS 0
OBJ_HEAL 255
OBJ_PLAY_MUSIC 33
OBJ_DELAY 180
OBJ_PLAY_MUSIC 9
OBJ_ADD_CHARACTER 7, @J_IS_NOT_TALKING-OBJ_MAGICANT_FLYINGMAN5
OBJ_SET_FLAG 104
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_MAGICANT_GUITARIST:
objectDef OBJ_TYPE::WANDERING_NPC, 41, DIRECTIONS::DOWN, 534
.addr SPRITEDEF_GUITARIST
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_MAGICANT_GUITARIST
OBJ_BELOW_LEVEL 25, @J_BELOW_LEVEL-OBJ_MAGICANT_GUITARIST
OBJ_DIALOGUE UMSG::MAGICANT_GUITARMAN_SONG
OBJ_STOP
	@J_BELOW_LEVEL:
OBJ_DIALOGUE UMSG::MAGICANT_GUITARIST_UNDER
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_MAGICANT_COINVENDOR:
objectDef 25, 73, DIRECTIONS::UP, 532
.addr SPRITEDEF_MAGICANTIAN_SHOPKEEP
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_MAGICANT_COINVENDOR
OBJ_DIALOGUE UMSG::MAGICANT_VENDORINTRO
	@J_JUMP:
OBJ_SET_FLAG 0
OBJ_NOT_HAS_ITEM 0, @J_NOT_HAS_ITEM-OBJ_MAGICANT_COINVENDOR
OBJ_CLEAR_FLAG 0
	@J_NOT_HAS_ITEM:
OBJ_DISPLAY_ITEMS 62, 45, 46, 47, @J_DISPLAY_ITEMS-OBJ_MAGICANT_COINVENDOR
OBJ_IS_NOT_FLAG 0, @J_IS_NOT_FLAG-OBJ_MAGICANT_COINVENDOR
OBJ_DIALOGUE UMSG::DRUGSVENDOR_NOMORE
OBJ_CLEAR_FLAG 0
OBJ_STOP
	@J_IS_NOT_FLAG:
OBJ_TAKE_MONEY @J_TAKE_MONEY-OBJ_MAGICANT_COINVENDOR
OBJ_DIALOGUE UMSG::SHOP_CONFIRM
OBJ_YESNO_IS_NO @J_YESNO_IS_NO-OBJ_MAGICANT_COINVENDOR
OBJ_DIALOGUE UMSG::BURGERSHOP_GOODBYE
OBJ_PLAY_SOUND 11
OBJ_SHOW_MONEY
OBJ_GIVE_ITEM @J_IS_NOT_TALKING-OBJ_MAGICANT_COINVENDOR
OBJ_DIALOGUE UMSG::BURGERSHOP_ANYMORE
OBJ_YESNO_IS_NO @J_YESNO_IS_NO1-OBJ_MAGICANT_COINVENDOR
OBJ_JUMP @J_JUMP-OBJ_MAGICANT_COINVENDOR
	@J_YESNO_IS_NO1:
OBJ_DIALOGUE UMSG::BURGERSHOP_GOODBYE
OBJ_STOP
	@J_YESNO_IS_NO:
OBJ_GIVE_MONEY @J_IS_NOT_TALKING-OBJ_MAGICANT_COINVENDOR
	@J_DISPLAY_ITEMS:
OBJ_DIALOGUE UMSG::MISLAY_MOUTHWASHKID_NOTAKE
OBJ_CLEAR_FLAG 0
OBJ_STOP
	@J_TAKE_MONEY:
OBJ_DIALOGUE UMSG::HOSPITAL_NURSE_NOMONEY
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_MAGICANT_RINGVENDOR:
objectDef 25, 105, DIRECTIONS::UP, 532
.addr SPRITEDEF_MAGICANTIAN_SHOPKEEP_PINK
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_MAGICANT_RINGVENDOR
OBJ_DIALOGUE UMSG::MAGICANT_VENDORINTRO
	@J_JUMP:
OBJ_SET_FLAG 0
OBJ_NOT_HAS_ITEM 0, @J_NOT_HAS_ITEM-OBJ_MAGICANT_RINGVENDOR
OBJ_CLEAR_FLAG 0
	@J_NOT_HAS_ITEM:
OBJ_DISPLAY_ITEMS 62, 48, 49, 50, @J_DISPLAY_ITEMS-OBJ_MAGICANT_RINGVENDOR
OBJ_IS_NOT_FLAG 0, @J_IS_NOT_FLAG-OBJ_MAGICANT_RINGVENDOR
OBJ_DIALOGUE UMSG::DRUGSVENDOR_NOMORE
OBJ_CLEAR_FLAG 0
OBJ_STOP
	@J_IS_NOT_FLAG:
OBJ_TAKE_MONEY @J_TAKE_MONEY-OBJ_MAGICANT_RINGVENDOR
OBJ_DIALOGUE UMSG::SHOP_CONFIRM
OBJ_YESNO_IS_NO @J_YESNO_IS_NO-OBJ_MAGICANT_RINGVENDOR
OBJ_DIALOGUE UMSG::BURGERSHOP_GOODBYE
OBJ_PLAY_SOUND 11
OBJ_SHOW_MONEY
OBJ_GIVE_ITEM @J_IS_NOT_TALKING-OBJ_MAGICANT_RINGVENDOR
OBJ_DIALOGUE UMSG::BURGERSHOP_ANYMORE
OBJ_YESNO_IS_NO @J_YESNO_IS_NO1-OBJ_MAGICANT_RINGVENDOR
OBJ_JUMP @J_JUMP-OBJ_MAGICANT_RINGVENDOR
	@J_YESNO_IS_NO1:
OBJ_DIALOGUE UMSG::BURGERSHOP_GOODBYE
OBJ_STOP
	@J_YESNO_IS_NO:
OBJ_GIVE_MONEY @J_IS_NOT_TALKING-OBJ_MAGICANT_RINGVENDOR
	@J_DISPLAY_ITEMS:
OBJ_DIALOGUE UMSG::MISLAY_MOUTHWASHKID_NOTAKE
OBJ_CLEAR_FLAG 0
OBJ_STOP
	@J_TAKE_MONEY:
OBJ_DIALOGUE UMSG::HOSPITAL_NURSE_NOMONEY
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_MAGICANT_PENDANTVENDOR:
objectDef 25, 9, DIRECTIONS::UP, 564
.addr SPRITEDEF_MAGICANTIAN_SHOPKEEP_RED
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_MAGICANT_PENDANTVENDOR
OBJ_DIALOGUE UMSG::MAGICANT_VENDORINTRO
	@J_JUMP:
OBJ_SET_FLAG 0
OBJ_NOT_HAS_ITEM 0, @J_NOT_HAS_ITEM-OBJ_MAGICANT_PENDANTVENDOR
OBJ_CLEAR_FLAG 0
	@J_NOT_HAS_ITEM:
OBJ_DISPLAY_ITEMS 4, 51, 52, 53, @J_DISPLAY_ITEMS-OBJ_MAGICANT_PENDANTVENDOR
OBJ_IS_NOT_FLAG 0, @J_IS_NOT_FLAG-OBJ_MAGICANT_PENDANTVENDOR
OBJ_DIALOGUE UMSG::DRUGSVENDOR_NOMORE
OBJ_CLEAR_FLAG 0
OBJ_STOP
	@J_IS_NOT_FLAG:
OBJ_TAKE_MONEY @J_TAKE_MONEY-OBJ_MAGICANT_PENDANTVENDOR
OBJ_DIALOGUE UMSG::SHOP_CONFIRM
OBJ_YESNO_IS_NO @J_YESNO_IS_NO-OBJ_MAGICANT_PENDANTVENDOR
OBJ_DIALOGUE UMSG::BURGERSHOP_GOODBYE
OBJ_PLAY_SOUND 11
OBJ_SHOW_MONEY
OBJ_GIVE_ITEM @J_IS_NOT_TALKING-OBJ_MAGICANT_PENDANTVENDOR
OBJ_DIALOGUE UMSG::BURGERSHOP_ANYMORE
OBJ_YESNO_IS_NO @J_YESNO_IS_NO1-OBJ_MAGICANT_PENDANTVENDOR
OBJ_JUMP @J_JUMP-OBJ_MAGICANT_PENDANTVENDOR
	@J_YESNO_IS_NO1:
OBJ_DIALOGUE UMSG::BURGERSHOP_GOODBYE
OBJ_STOP
	@J_YESNO_IS_NO:
OBJ_GIVE_MONEY @J_IS_NOT_TALKING-OBJ_MAGICANT_PENDANTVENDOR
	@J_DISPLAY_ITEMS:
OBJ_DIALOGUE UMSG::MISLAY_MOUTHWASHKID_NOTAKE
OBJ_CLEAR_FLAG 0
OBJ_STOP
	@J_TAKE_MONEY:
OBJ_DIALOGUE UMSG::HOSPITAL_NURSE_NOMONEY
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_MAGICANT_INNKEEPER:
objectDef 25, 43, DIRECTIONS::DOWN, 564
.addr SPRITEDEF_MAGICANTIANGIRL_SHOPKEEP
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_MAGICANT_INNKEEPER
OBJ_DIALOGUE UMSG::MAGICANT_INNKEEPER1
OBJ_YESNO_IS_NO @J_YESNO_IS_NO-OBJ_MAGICANT_INNKEEPER
OBJ_DIALOGUE UMSG::MAGICANT_INNKEEPER2
OBJ_YESNO_IS_NO @J_YESNO_IS_NO1-OBJ_MAGICANT_INNKEEPER
OBJ_DIALOGUE UMSG::MAGICANT_INNKEEPER3
OBJ_SLEEP
OBJ_DIALOGUE UMSG::MAGICANT_INNKEEPER_GOODBYE
OBJ_STOP
	@J_YESNO_IS_NO1:
OBJ_DIALOGUE UMSG::MAGICANT_INNKEEPER2_NO
OBJ_STOP
	@J_YESNO_IS_NO:
OBJ_DIALOGUE UMSG::MAGICANT_INNKEEPER1_NO
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_MAGICANT_DOCTOR:
objectDef 25, 74, DIRECTIONS::DOWN, 564
.addr SPRITEDEF_MAGICANTIANGIRL_SHOPKEEP_BLUE
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_MAGICANT_DOCTOR
OBJ_DIALOGUE UMSG::MAGICANT_DOCTOR
OBJ_PICK_CHARACTER_J 1, @J_PICK_CHARACTER_J-OBJ_MAGICANT_DOCTOR
OBJ_CHOOSE_CHARACTER @J_CHOOSE_CHARACTER-OBJ_MAGICANT_DOCTOR
OBJ_JUMP @J_JUMP-OBJ_MAGICANT_DOCTOR
	@J_PICK_CHARACTER_J:
OBJ_PICK_CHARACTER_J 0, @J_JUMP-OBJ_MAGICANT_DOCTOR
	@J_JUMP:
OBJ_AND_STATUS 0
	@J_NOT_MAX_HEALTH:
OBJ_HEAL 255
OBJ_NOT_MAX_HEALTH @J_NOT_MAX_HEALTH-OBJ_MAGICANT_DOCTOR
	@J_NOT_MAX_PP:
OBJ_PPHEAL 255
OBJ_NOT_MAX_PP @J_NOT_MAX_PP-OBJ_MAGICANT_DOCTOR
OBJ_PLAY_SOUND 7
OBJ_DIALOGUE UMSG::PODUNK_HOSPITALDOCTOR_ACCEPT
OBJ_STOP
	@J_CHOOSE_CHARACTER:
OBJ_DIALOGUE UMSG::PODUNK_HOSPITALDOCTOR_DECLINE
	@J_IS_NOT_TALKING:
OBJ_STOP

OBJ_MAGICANT_MUSICVENDOR:
objectDef 25, 106, DIRECTIONS::DOWN, 564
.addr SPRITEDEF_MAGICANTIANGIRL_SHOPKEEP_BLUE
OBJ_IS_NOT_TALKING @J_IS_NOT_TALKING-OBJ_MAGICANT_MUSICVENDOR
OBJ_DIALOGUE UMSG::MAGICANT_MUSICVENDOR
	@J_IS_NOT_TALKING:
OBJ_STOP

